### ISSUE TITLE
[MU4 Task] Notehead popup design improvements

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10028]
[Tasks updated 14 Dec '21]

**Task description**
This task comprises a few minor UX improvements to the notehead popup in **Properties**. 
Importantly, it reinstates the "small notehead" functionality from MS3.6, which has been accidentally omitted from the MS4 project.

Tasks for implementation are:

1. Reposition "Hide notehead" checkbox beneath "Notehead type" panel
2. Implement "Notehead parentheses" toggle buttons (toggling functionality of notehead parentheses palette item)
3. Reinstate checkbox from MS3.6 (Inspector > Note > Small) and rename label to "Small notehead"
4. Rename "Dotted note position" label to "Duration note position"

<img width="1442" alt="NEW NOTEHEAD POPUP DESIGN_v2" src="https://user-images.githubusercontent.com/86290556/145932364-9636cbab-d88e-4fa3-9db5-f64df35475b7.png">

The "small notehead" functionality to be reinstated from MS3.6 **(TASK 2)** is this:
![small-notehead-3 6-2](https://user-images.githubusercontent.com/86290556/145932502-97e985e9-e9af-4afc-a367-d6e15355b2d0.gif)

Link to Figma design file: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=20835%3A668717

**Note also**
Issue #9169 includes a bug fix for this panel, as well as a task for disabling the "Duration dot position" buttons depending on what is selected in the score. Please advise if these tasks require further illustration and I'll be happy to supply it. 

Let me know if anything is unclear, or if you have any questions!
Thanks 🙂

**Comment by Tantacrul** [comment]
Just to point out: this fixes a regression in the Inspector that I missed. It is already possible in MS3.

**Comment by cbjeukendrup** [comment]
Two remarks:
- Would it make sense to put the "Hide notehead" and "Small notehead" checkboxes above the "Dotted note position" control? Because those checkboxes are related to the notehead type settings. 
- Would it make sense to rename "Dotted note position" control to "Augmentation dot position"? 
  - And to move it to the "Show more" section"?
  - And to hide it for notes that do not have any dots?

**Comment by Tantacrul** [comment]
I think you're right that dotted note options should probably go under 'hide notehead' / 'small notehead'.

I wouldn't have thought to put them in 'show more' because the options are not quite so niche. But I don't feel very strongly about that.

I agree it should only be enabled when a dotted note head is chosen. I also prefer 'Augmentation dot position' :)

**Comment by bkunda** [comment]
I too agree with the repositioning of the "dotted note position" settings beneath the checkbox options ✅.
And also that this setting should only be available when a dotted note is selected ✅.

Like @Tantacrul, I also don't have a strong opinion about whether this setting should go in "show more" or not. If pressed for a decisive resolution, however, I might  be slightly in favour of leaving them where they are (i.e. not in "show more") for these reasons:

1. I can see there being some _not-so-atypical_ user cases where the dot needs to be manually repositioned, particularly where note clusters are concerned, in which instances MuseScore currently doesn't always render the dots correctly (i.e. dots appear to not be visible against certain notes). Solving this problem by having to click through to a separate properties subsection feels clunky (as it presently does in MS3.6). Exposing these settings more visibly would make the solution to these cases easier to discover. 
2. The current options in "show more" only affect the notehead, and only in ways that solve very esoteric problems. I do think that correcting the position of the dot is less niche than these other options.

Lastly, I would be in favour of labelling this setting "duration dot position". I don't particularly like the word "Augmentation" as it is, at least in my mind, too strongly associated with a harmonic principle, rather than a rhythmic one. 

lmk if there is any strong opposition to the above, or other thoughts that we collectively haven't considered. I'd be happy to post an updated design shortly 🙂

**Comment by cbjeukendrup** [comment]
Ok, I agree, let's keep the "dotted note position" settings visible directly 👍 (at least until MuseScore's automatic placement is always correct).

I'm not completely sure whether I would like "duration dot". I believe that "Augmentation dot" is quite a common name, and sounds slightly more professional to me. But I feel I might not be able to judge about this very well because I'm not a native English speaker, and your point about the possible confusion with harmony is also a very fair one.

@Tantacrul what are your thoughts?

**Comment by bkunda** [comment]
fwiw: 

- SMuFL = "Augmentation dot"
- Gould = "Duration dot"

I do expect that "augmentation dot" is more common than I'm aware, in which case I'd be happy for it to take this name 🙂

**Comment by Tantacrul** [comment]
Hmmm. Another of these juicy instances where the generally agreed upon term is vague and technical...

I might just create a poll to find out what people prefer because I think we're damned no matter what choice we make here. The  accompanying icons are probably going to have to do the heavy lifting. Setting up the poll now!

**Comment by Tantacrul** [comment]
We're live: https://twitter.com/Tantacrul/status/1470335804547518466

**Comment by bkunda** [comment]
The people have spoken! It seems that "Duration dot position" is the preferred label by around 70% of respondents, so in the interests of supporting the greatest understanding, I think we'll go with this. 

Design spec has been updated in the task above. Let me know if further info is needed!
