### ISSUE TITLE
[MU4 Issue] Mixer top bar overlay issue

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10047]
**Describe the bug**
This is in an unlikely situation (I found this while trying to make OBS recordings in 300% scaling) when scaling this big but the top bar on Mixer has a strange behaviour that is doesn't overlay the panels section

https://user-images.githubusercontent.com/71656189/145575714-582dad04-8976-4101-bb05-4c316242b73d.mp4

**Desktop:**
 - OS: Windows

**Comment by jessjwilliamson** [comment]
@cbjeukendrup

**Comment by cbjeukendrup** [comment]
There are two problems here: 
- The mixer should not be able to get that tall at all (or rather: the things between the Mixer and the top toolbars should not be able to become that small at all). See #10019.
- The title bar of the mixer is apparently transparent. In normal circumstances, this is no problem because the background of the mixer itself is behind the title bar, but apparently there is some strange z-order, so those buttons from the palettes are between the background of the mixer and the title bar... 
 But if we add a background to the title bar, the rounded corners for the floating window don't work well anymore (left = bad, right = good):
  <img width="1231" alt="Schermafbeelding 2021-12-13 om 15 43 58" src="https://user-images.githubusercontent.com/48658420/145832941-29c33fe9-2a10-40ee-ae64-38a637729656.png">
 We could set a corner radius for the background of the title bar, so that it looks good when the widget is floating, but when it is docked, you would theoretically still see things behind the title bar through the gaps in the corners created by the radius. Setting the radius conditionally is also not completely trivial. 
  Anyway, if #10019 gets fixed, the problem of _this_ issue will in practice not occur anymore, so I think it is not worth it to investigate much time into this.

**Comment by cbjeukendrup** [comment]
Haha, forget what I said! Fixed it :)
I made a typo (`source` instead of `maskSource`) which leaded to another uninformative QML warning, which made me think the trick was not possible. But it turns out it works.
