### ISSUE TITLE
[MU4 Issue] Score position changes after selecting a bar with some lines even those are not out of the screen

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10078]
**To Reproduce**
1. Open [test_palette.zip](https://github.com/musescore/MuseScore/files/7704530/test_palette.zip)
2. Zoom in the score
3. Select some bars - see **video below**

https://user-images.githubusercontent.com/90187801/145831493-bf5f8ae8-bccf-4625-aaf5-34fa352024cf.mp4

**Desktop:**
 - OS: Win10 (didn't try others)

**Comment by wizofaus** [comment]
I get this when you select a measure with a hairpin or indeed any line object in it, it seems to have the wrong canvasBoundingRect.
In fact something seems broken with EngravingItem::canvasPos() for items that don't have an explicit parent, which appears to include quite a lot of things, including Text and Line objects.  In at least one case the _parent of my text object was a TextLineBaseSegment but that that its type property set to "HAIRPIN_SEGMENT", so something's definitely not right there...might be one for you @igorkorsukov ?

**Comment by wizofaus** [comment]
Actually the interesting thing is that when you click on a hairpin what you're actually selecting is the HairpinSegment (which makes sense, given it could be split across systems/pages, and it matters which segment you've selected for rendering purposes).  But when you select a *measure* and it automatically selects all elements "contained" by that measure it selects the Hairpin itself, rather than the segment, and it seems to be the Hairpin itself that has the wrong canvasBoundingRect - that for the segment is OK.  So perhaps the error is just the logic that determines what elements to select when you click on a measure, as logically it's only the segment that would belong to a particular measure.
Not sure if that's true for text elements too.

**Comment by igorkorsukov** [comment]
> might be one for you @igorkorsukov ?

most likely )

**Comment by wizofaus** [comment]
Dug a bit further, and the behaviour of having the hairpin (or any line) itself automatically selected when you select a measure, rather than its segment, is the same in MS3. As is the fact that canvasBoundingRect for a hairpin element is wrong (it has x=0, as though relative to its own position, rather than relative to the left side of the whole canvas), but unlike MS4, MS3 doesn't try to work out if the union of *all* selected elements' canvas bounding-rectangles are within the current viewport, in fact it doesn't automatically scroll the viewport on mouse-click at all in order to ensure that all selected elements are visible,  however it does do it on using the keyboard to change the selection - but this is just done by ensuring each individual element is within the viewport as it is added to the selection in response to particular commands (see ScoreView::cmd( ), adjustCanvasPosition is explicitly called when commands such as "select-next-chord" or "select-staff-below" are activated).

OTOH MS4 does seem to have an issue with calculating the canvas bounding rectangles for Text elements, which in MS3 have an explicit parent of a ChordRest (Or a VBox etc. if part of a frame).  Still investigating.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
