### ISSUE TITLE
Dynamics show broken 'underline' and 'strikethrough' visuals.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10081]
**Describe the bug**
Users are able to apply 'strikethrough' and 'underline' to dynamics, both of which look wrong. With 'underline', this is a regression. With Strikethrough, it is a new problem. None of these styling options (italic, bold, underline & strikethrough) should affect dynamic markings.

![image](https://user-images.githubusercontent.com/21022311/145890512-1e934356-4eb2-49b5-bcb2-067e02e53c66.png)

**Comment by Tantacrul** [comment]
@Jojo-Schmitz - would you be able to address the issue for strikethrough?

**Comment by wizofaus** [comment]
If you really do want it so that strikethrough & underline are both ignored for musical symbols the same way bold & italic are, that's straightforward (basically the lines in TextFragment::Font that do setUnderline( ) and setStrike( ) need to be moved from line 959-60 to the 'else' clause towards the end, line 1005).

**Comment by Jojo-Schmitz** [comment]
That indeed seems to make the most sense.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
