### ISSUE TITLE
[MU4 Issue] Scrolling is too sensitive in various menus

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10085]
**Describe the bug**
Scrolling in a number of menus remains very sensitive, and in particular doesn't always stop when the mouse wheel is stopped (in other words, the scroll animation continues after the user has stopped the mouse wheel from moving). 

This is particularly noticeable in the following long menus:

- Preferences > Keyboard shortcuts
- Preferences > Appearance > Font face
- Preferences > Import > Character set used when importing binary files (both dropdowns)
- Add-ons > Languages
- Score > Customise toolbar

Aside from the above, I suspect this is a global issue throughout the program.

**Demo 1** Showing customise toolbar, and comparison expected scroll behaviour with OS finder dialog, where the scroll behaviour stops as soon as the mouse wheel stops moving:

https://user-images.githubusercontent.com/86290556/145936148-edfdc2e8-0de9-4427-a205-c405d34b236b.mov

**Demo 2** Languages menu

https://user-images.githubusercontent.com/86290556/145936186-65b4cc16-6da4-4d4d-a4c8-54b48b54482f.mov

**Demo 3** Keyboard shortcuts menu

https://user-images.githubusercontent.com/86290556/145936214-96a54091-4e81-4b7e-b601-d021e878ad26.mov

**Expected behavior**
Scrolling should stop as soon as mouse wheel has stopped moving. It would probably be sufficient that scroll speed and general behaviour match MS3.6.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
See #7805, not yet merged and potentially not a global fix

**Comment by cbjeukendrup** [comment]
My experience:
- On macOS, scrolling feels perfectly natural with the built-in trackpad and with Apple's Magic Mouse 2 (it starts as soon as you start scrolling, and stops as soon as you stop; the scrolling speed is comparable with native macOS apps).
- But with a simple external Logitech mouse, it is indeed a bit problematic. The ease-in-out animations are too slow, so there is always some delay, and if you turn the wheel a tiny bit, it will continue scrolling quite far.
- On Windows (via Parallels on macOS), it is totally problematic with both my trackpad and my two mouses; if I just move my fingers a tiny bit on the trackpad, it starts scrolling with the speed of light. The ease-in-out animations also play a role here. The behaviour is also not completely consistent; sometimes, it seems to work ok for a moment, but then suddenly it takes a run and scrolls to the top or bottom with the speed of light again.

I also have a theory _why_ it is like this: on macOS, some smart mouses may report the number of _pixels_ scrolled, while other mouses just report the number of _steps_ scrolled. I think that the built-in trackpad and the Magic Mouse do report the number of pixels on macOS, while the Logitech mouse only works with steps. On Windows, maybe all mouses report just steps. Maybe the QML Flickable is implemented correctly for pixel-scrolling mouses, and incorrectly for step-mouses.

For the score view, for which we implemented a custom scrolling mechanism, it works okay.

By the way, the QML Flickable has more bugs. When scrolling, the view sometimes suddenly jumps. In extreme cases, this makes it impossible to scroll to the bottom of the view, because it jumps upwards every time. This seems to happen only with the Magic Mouse and the trackpad, so is probably specific to pixel-mouses.

Here's an example about the Appearance page in the Preferences dialog. It's the best visible if you look at the scrollbar; it jumps up and down. Especially in the beginning of the video.

https://user-images.githubusercontent.com/48658420/146675850-ccc2b8e9-21a1-4e69-b465-e11f7323becf.mov

**Comment by llui85** [comment]
I can experience this issue too on Linux with both a touchpad and mouse. This is also an issue with the MU3 palette.

The ideal would be a preference similar to Firefox's "Use smooth scrolling", that disables smooth scrolling/"flicking" across the whole application (is this possible with `Flickable`?). There's a similar complaint in #7657

**Comment by DmitryArefiev** [comment]
Hi @bkunda can you check this in build from #10162.

For me it's better now with touchpad, but **with mouse the each one scroll is small**

**Comment by bkunda** [comment]
Hi @DmitryArefiev, I have just returned from holidays and have now had a chance to look into this (thanks for your patience 🙂).

I agree with you that mouse scroll is now a bit too slow (especially when I compare it to other apps). Touch pad seems to work better. 

There seems to be an extra issue for me on Windows, which is that the scroll continues for too long even after the touching the trackpad again (which usually stops the scroll motion on other apps). This doesn't seem to be a problem for me in MacOS.

**Comment by llui85** [comment]
@DmitryArefiev I also tested this (but forgot to post a comment until bkunda's comment), and think that it's somewhat better for the touchpad, but still a bit too sensitive. I agree with @bkunda - mouse scrolling is still much too sensitive as well.

___

The main issue I'm finding is that unlike the other applications (which uses GTK), the touchpad scrolling has a fixed velocity; in GTK the scroll velocity is based on how **much** (if that makes sense) the touchpad is flicked. Here's a quick screen recording of the scroll behaviour in gedit which implements this:

https://user-images.githubusercontent.com/47158068/148359951-45c3c33b-9789-4ee2-b949-7cc98c1b9861.mp4

(I'm using Linux, GNOME 3.38 by the way).

I'm not sure how feasible this behaviour would be though in (terms of development). It might just be better to add an option to set the maximum velocity to 0, to disable the smooth scrolling/"flicking" behaviour entirely.

**Comment by llui85** [comment]
See also various discussions on the forums (re the 3.3 palette):

- https://musescore.org/en/node/318628
- https://musescore.org/en/node/299776
- https://musescore.org/en/node/294613
- https://musescore.org/en/node/318628

**Comment by cbjeukendrup** [comment]
Palettes have an additional problem. They make use of the QML ListView component. That component only loads the list items that are currently in the viewable area; items that are scrolled out of view are destroyed (to save memory) and will be recreated when they will get into the view again. 

Because not all items are loaded at a time, the total height of the scrollable area cannot be calculated. It can only be estimated, which is what QML does: it takes the average height of all visible items, and then uses that height to estimate the total height.

This works perfectly fine if all list items have exactly the same height, which is the case in most list views. But in the Palettes, this is totally different: collapsed palettes are very small, while expanded palettes vary from tall to very tall. The estimated total height will be totally wrong. Also, it will change continuously while scrolling, because other items become visible, so the average height of the visible items changes. That causes jumping and other strange behaviour. 

I'm not totally sure about a solution. One option would be to replace the ListView by a Flickable+Column+Repeater. I also believe that you can control the "cache size" of the ListView, so if that works, that would be another option.

**Comment by Eism** [comment]
Summary:
Currently, the problem is on the Qt side and we can't completely disable inertia. Qt 6 allows you to control inertia. Therefore, we will merge the new solution from #10162(which slightly improves scrolling) and return to this problem when MuseScore is updated to Qt 6.
