### ISSUE TITLE
Score Migration

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10120]
**Task description**
The following documents specify updates to our score migration process given the engraving changes made for MS4.

Simon has specified the alterations here: (Apologies about this being a restricted document. We'll post the details publicly shortly)
https://alice.mu.se/display/UK/Score+migration+for+MuseScore+4.0

Updated Figma assets here:
https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/?node-id=2584%3A0

![image](https://user-images.githubusercontent.com/21022311/146411587-e86034da-b08c-4662-a56d-72a870e60d89.png)

![image](https://user-images.githubusercontent.com/21022311/146412611-d54074f9-fed1-4819-9c20-897df6663bdd.png)

**Comment by Jojo-Schmitz** [comment]
The patch level is not mentioned? Like 3.6.2, 2.2.1, 3.2.3, etc? That would give a bit of extra info without having to dive into Score Properties. And is what 3.x did.

**Comment by Tantacrul** [comment]
An oversight. Just fixed it.

![image](https://user-images.githubusercontent.com/21022311/146438858-48ff2a51-d39d-429a-89e3-ebcc1997a8e3.png)

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10133

**Comment by DmitryArefiev** [comment]
@igorkorsukov Tested #10133 on Win10, Mac12, LinuxMint 20.2 - found some things:

1. The version at the top doesn't correspond with the MU version were the score was created. 
E.g. **This file was created in 2.2.5** this message appears for score created in **MU 2.0.1**.  
In fact the dialogs just show 2.2.5 or 3.3.2

2. The wrong dialog applied for score created in **MU3.6.2**

This: 

![Capture](https://user-images.githubusercontent.com/90187801/150406536-4290c1cb-1544-44d7-aec6-f73087e42d8e.png)

Instead of this:

![Capture2](https://user-images.githubusercontent.com/90187801/150406703-2c54bcfa-8ea8-4082-a827-8664b9bf3064.PNG)

3. Since the two dialogs (for 2.2.5 and 3.3.2) are for two kinds of scores, **'Don't ask again'** checkbox should work independently for each of them (minor issue)

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/151545822-bd13e8d8-adfe-4182-8e0a-b12547a90fab.mp4

@RomanPudashkin Also there is a bug when clicking on X button in the export dialog it shows an error message. 
Let's make X behavior as Cancel button. X button should trigger no error message and no action. Thanks!

FYI @Tantacrul @bkunda
