### ISSUE TITLE
[MU4 Issue] Alt + F and other shortcuts to invoke menu bar should work with Russian keyboard layout as well 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10181]
**Describe the bug**
Alt + F and other shortcuts to invoke menu bar should work with Russian keyboard layout as well (like it works in Firefox)

**To Reproduce**
1. Switch to Russian keyboard Layout 
2. Press Alt+F - **it should open File menu**

**Desktop:**
 - OS: Windows

**Additional context**
Works in **MU3**

**Comment by cbjeukendrup** [comment]
I'm afraid this can be difficult to solve. Qt's shortcuts system is character-based, rather than key-based. So if you press `Alt` + `F` with a Russian keyboard layout, Qt will interpret this as `Alt` + `а` (at least, that is the character it produces for me when I type an `F` with a Russian keyboard layout). 
This causes problems in many Qt apps, and I'm not sure whether workarounds exist.

**Comment by Eism** [comment]
Btw, It works on a lot of app in Linux like Qt Creator, Slack, Git Craken and I think we need to implement it in priority because it is a real headache for users who are switching between languages often.
Just need to do more research

**Comment by DmitryArefiev** [comment]
Fixed in #10749
