### ISSUE TITLE
[MU4 Issue] Properties in drop-downs are not updated when changing object selection 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10259]
**Describe the bug**
When changing an object's property in a dropdown menu in **Properties**, the value in said dropdown menu does not change when a different object is selected – unless the selection is cleared first.   

This was first noticed when changing the font face and/or size of a text object: 

![GIF 1-13-22 at 21 03 50](https://user-images.githubusercontent.com/86290556/149309851-26e0c040-b3ce-4136-98cb-e812b8ba6dcd.gif)

@boryskuzmenko confirms this problem is general across all possible score elements (including articulations, ornaments, dynamics, etc.). 

**Expected behavior**
Selecting any score object should cause all relevant dropdown menus in Properties to update with the correct values for that selection.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
Related to https://github.com/musescore/MuseScore/issues/8813
Note also: new design for text size dropdown in https://github.com/musescore/MuseScore/issues/9769

**Comment by maryszabo** [comment]
Hi, is this still available? If so, I am new to this (and first time working on open source code). I would really appreciate any tips or advice on how to approach solving this problem.

**Comment by RobFog** [comment]
> Hi, is this still available? If so, I am new to this (and first time working on open source code). I would really appreciate any tips or advice on how to approach solving this problem.

Looks like it is. Maybe @cbjeukendrup can help? :)

**Comment by cbjeukendrup** [comment]
Sure!

@maryszabo Hi! I investigated a bit into this issue myself, and after some testing I found that it seems to be specific to dropdown items, rather than having to do anything with text specifically. For example, the inspector panel for key signatures also contains a dropdown, which shows the same problem.

I also discovered that it only happens when you have just changed the value in the dropdown. So, if you select one item, don't change any settings, and then directly select another item, it updates fine; but if you select one item, then change the value of a dropdown, and then select another item, the value of the dropdown will not update anymore, until you clear the selection (because then the dropdown is destroyed altogether and will be recreated when you make a new selection).

So, to fix this issue, I would suggest to look the file DropdownPropertyView.qml. If you add some logging statements like this, you can see in the console what happens. What I see there when doing so, is not completely expected.

<img width="430" alt="Schermafbeelding 2022-01-26 om 23 07 23" src="https://user-images.githubusercontent.com/48658420/151255097-75788c06-9365-4477-bcc4-af9271c1bdf8.png">

Maybe the actual fix will be in Dropdown.qml. That component behaves a bit different from many other components; most of our components emit a signal when the value is edited by the user (like `IncrementalPropertyControl` has the `valueEdited` signal which can be listened for using `onValueEdited: function(newValue) {...}`). 
But `Dropdown` does not emit a signal, but modifies its `currentValue` property. To be notified when the user changes the value, other components can listen for `onCurrentValueChanged`. But that is also emitted when the value is changed programmatically, for example when the value from the model updates. I think this is not a very good situation. You could try what happens if you rewrite the DropDown component so that it emits a dedicated `valueEdited` signal, only when the user actively edits it, like with IncrementalPropertyView. 
Of course, this will require you to update _all_ instances of Dropdown, which is not worth the effort if it turns out that this does not fix the issue. So, I would recommend to update the Dropdown component itself, and then the instance in DropdownPropertyView, and then try whether it works. Other Dropdowns in the app will be broken until you update those too, but at least that allows you to test whether it works to fix the issue.

**Comment by maryszabo** [comment]
@cbjeukendrup 
Thank you so much for the suggestions! I really appreciate it! Planning to work on the code this weekend. Thanks again!!

**Comment by duanjr** [comment]
> @cbjeukendrup Thank you so much for the suggestions! I really appreciate it! Planning to work on the code this weekend. Thanks again!!

Hi maryszabo, are you still working on this? I wonder if I can participate in this issue.

**Comment by maryszabo** [comment]
> > @cbjeukendrup Thank you so much for the suggestions! I really appreciate it! Planning to work on the code this weekend. Thanks again!!
> 
> Hi maryszabo, are you still working on this? I wonder if I can participate in this issue.

Hi @duanjr . Go for it! I'm still working on understanding qml

**Comment by iamjithinjohn** [comment]
The issue seems inactive. Can I try working on it? @bkunda

**Comment by duanjr** [comment]
I once tried what [cbjeukendrup](https://github.com/cbjeukendrup) suggested and some other changes but all failed. In my pr [#10566](https://github.com/musescore/MuseScore/pull/10566) this issue still exist.
I'm not working on this now.

**Comment by bkunda** [comment]
I think this means the issue is again open @iamjithinjohn! Please feel welcome to tackle it (and reach out to @cbjeukendrup with any questions) :-)

**Comment by iamjithinjohn** [comment]
>I think this means the issue is again open @iamjithinjohn! Please feel welcome to tackle it (and reach out to @cbjeukendrup with any questions) :-)

Sure, Thanks for confirming! I'll start working on it :+1:

**Comment by DmitryArefiev** [comment]
Fixed in #10862
