### ISSUE TITLE
[MU4 Task] [GP] Show only pitches in tab notation when it is displayed along with standard notation

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10308]
**Task description**
Legato (slur or tie) for tab notation should not be shown IF tab notation is shown TOGETHER with standard notation. If tab notation is shown separately, legato should stay.
The same about note duration: hide note duration when tab notation is shown along with standard notation

Current state:
![Screenshot 2022-01-24 at 21 59 40](https://user-images.githubusercontent.com/24373905/150846769-44f10641-7c17-43da-b790-47bcd9a639ad.png)

Expected:
![Screenshot 2022-01-24 at 22 01 33](https://user-images.githubusercontent.com/24373905/150846921-616be646-f336-48ac-9d0d-9c73c3114082.png)

**Comment by Jojo-Schmitz** [comment]
As this seems to be about slurs, not ties, it'd be clearer if the notes in the example wouldn't have the same pitch

**Comment by bkunda** [comment]
I'm not sure I entirely agree with this. I can certainly find a number of good examples where slurs are displayed across both TAB and standard notation staves. Since slurs communicate technical information (not just musical information) for guitarists, I think it is reasonable to be able to see them in both the TAB and standard notation staves.

At any rate, this might be something we could develop as a toggle-able option, so users can choose which staff they show this kind of information. This would of course require some careful design work.

But if I understand the issue correctly, I don't think we should remove slurs and ties from TAB notation when a TAB staff is shown together with a standard notation staff.

**Comment by boryskuzmenko** [comment]
Will be done in scope of https://github.com/musescore/MuseScore/issues/11688
