### ISSUE TITLE
[MU4 Task] [GP] Display half note correctly in tab notation

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10304]
**Task description**
Half-note is shown with two extra lines across the note

**Current state:**
representation of half notes:
![Screenshot 2022-01-26 at 21 10 46](https://user-images.githubusercontent.com/24373905/151221757-aed5d413-6f9f-47b5-b896-681c149e29af.png)

**Expected:**
representation of half notes:
![Screenshot 2022-01-26 at 21 13 43](https://user-images.githubusercontent.com/24373905/151222201-a054b5aa-f9ff-4b25-897d-b9d138f1485d.png)

**Comment by cbjeukendrup** [comment]
Those slashes might be intended (by whoever created them); there is a style setting that allows choosing the appearance of half notes, which you can edit in MuseScore's UI by right-clicking the TAB staff and choosing "Staff/Part properties" > "Advanced Style Properties" > "Note values" > "Half notes". 
In the code, this is controlled using the enum `TablatureMinimStyle` (but you've probably already found that out, sorry in that case 🙂).

**Comment by alexpavlov96** [comment]
@cbjeukendrup thank you! Yes, I just had a quick look and didn't do a quick fix, cause it would stop 1/8 have having slashes too. But maybe I didn't pay enough time.

**Comment by alexpavlov96** [comment]
@cbjeukendrup I updated the description! For guitarists it's not common to see the slashed stem, so I will fix default and ability to change the value in menu. Should there be some differences between "Tab. 6-str. common" and "Tab. 6-str. full" in the way of default values?

**Comment by alexpavlov96** [comment]
I noticed that "Preview" disappeared (compare "menu" pics).
Created https://github.com/musescore/MuseScore/issues/10384

**Comment by cbjeukendrup** [comment]
> @cbjeukendrup I updated the description! For guitarists it's not common to see the slashed stem, so I will fix default and ability to change the value in menu. Should there be some differences between "Tab. 6-str. common" and "Tab. 6-str. full" in the way of default values?

I'm not sure about this, I'm by no means a guitar/tablature expert. But in the MuseScore 3 user manual, I found this: https://musescore.org/en/handbook/3/tablature#from_instruments. That section suggest that it is intended for the "Tab. 6-str. full" staff type to have those different stems. But of course, there is nothing against revising intentions :)

@oktophonie what is your opinion on this?

**Comment by MarcSabatella** [comment]
I think you'll also find there is a lot of variation from publisher to publisher in how they present tablature.  Many show no rhythms at all.  So I wouldn't assume just because you personally are more familiar with one style than another because of the books or sites you've seen, that this is true for all guitarists in all genres of music in all countries.

Anyhow, to be clear, in MuseScore 3, the *default* is not to show the slashes - it's to use the short stems.  That's because short stems are how the "Common" (as opposed to "Simple" or "Full") style does it.  And the "Common" style is what is used if you add a tablature instrument from the instrument list or the tablature template.  The combined standard notation + tablature template uses the "Simple" style, which doesn't show rhythm at all.  You have to go out of your way to choose the "Full" style.

So to me it's not at all clear there is anything wrong here.

**Comment by cbjeukendrup** [comment]
Thanks, Marc! 
Then I think the solution would be to make sure that the Guitar Pro import uses the default "Common" style Tab staff, instead of what it is currently using (namely "Full", apparently).

**Comment by alexpavlov96** [comment]
those are different styles and there is no mistake, probably guitar pro files will be opened by default in "common" style
