### ISSUE TITLE
[MU4 Task] [GP] Display indications for special repeats and jumps

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10327]
**Task description**
Display indications for special repeats and jumps (for ex, Da Coda, D.C. al Fine and different signs)

**Expected:**
![Screenshot 2022-01-19 at 19 40 40](https://user-images.githubusercontent.com/24373905/150175040-f03e2e77-3f21-4863-bc9a-d9116f53fc2a.png)

**Comment by oktophonie** [comment]
Please note that some of these are effectively feature requests for MuseScore, and ideally would be handled as such rather than a cheap hack being used to 'make it work'. For example, assuming the GP segno is in its 'default' position, that should map to a segno of 'default' position in MU even if there is a visual difference. In this case I don't see the visual difference as significant (I prefer the more prominent positioning that MuseScore uses) but if exact matching is considered essential, this may require a new style option in MU.

Sometimes it is a grey area. The separation of codas has never been possible as standard in MU (and would be a significant feature to add) but a reasonable workaround exists that could be simulated at import time: https://musescore.org/en/node/11368

On the other hand, the 'Fine' is simply being imported as 'Repeat Text Left' rather than 'Repeat Text Right', which is an easy import fix :)

**Comment by boryskuzmenko** [comment]
@oktophonie Great your're here, Simon! If I uderstand you right there only one point (about space between measures) should be a separate feature. 
- All manipulations with Fine will be ok as a bug fix
- Segno default position in MU is the same as in GP, so can be fixed as a bug also
- Space between measures to be report as a separate improvement.
Please, confirm

**Comment by oktophonie** [comment]
Yes, agreed:

- yes, 'Fine' just needs an import bug fix
- default Segno position is slightly different in MU than GP (when in first bar of a system), but this is not significant
- space before coda can be its own issue, possible to represent via a workaround upon import

**Comment by boryskuzmenko** [comment]
As was decided above: Only 'fine' bug is to be fixed.

**Comment by boryskuzmenko** [comment]
🟡 **Can't reproduce**
'Fine' is rendered correct after import
