### ISSUE TITLE
[MU4 Task] [GP] Display meta-information

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10332]
**Task description**
Display meta-information:
- Display 'Words by' section
- Display 'Music by' section

**Comment by boryskuzmenko** [comment]
**REOPENED**
System behavior when score with empty title/subtitle/artist fields imported
![Capture 2022-04-20_12-39-27_AM](https://user-images.githubusercontent.com/101250347/164106365-5e7523e9-5a8b-4d27-992b-a1307d2b43da.png)

**Comment by Tantacrul** [comment]
For this, I think @oktophonie may have some ideas.

What do you think? If we import a blank title field (or other type of blank field), should we just remove it? Any lurking demons?

**Comment by oktophonie** [comment]
If there's no content for the text frame, then it makes sense to me to just omit the frame entirely. It just creates extra space at the top for no reason. The only reason to keep it would be if we expect to populate the title etc later in some way, because then the placeholder space might be useful in terms of minimising layout changes once the text is added. (I'm thinking in the context of unsupervised conversion of many files, here; if we "need" a title then maybe there's some way to derive one from elsewhere in the metadata, even from the filename; but that's a separate issue.)

**Comment by Tantacrul** [comment]
Cheers @oktophonie! I'm guessing that if we added titles to imported MusicXML files which didn't already have them, we'd be fiddling with the layout anyway. I guess it then makes sense to just remove these empty containers.

Sounds good to us @boryskuzmenko

**Comment by boryskuzmenko** [comment]
Great! Thanks @oktophonie @Tantacrul 
So, @alexpavlov96 please, remove the frame in this case

**Comment by boryskuzmenko** [comment]
@alexpavlov96 The issue is partly fixed. 
When opening a part in the title-free score - that blank frame is displayed on the main score. Looks like it happens due to the part name in a part. Please, fix.

https://user-images.githubusercontent.com/101250347/165361277-32e87034-8a69-48de-a278-c879cf9f8251.mov

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Empty Vertical frame is still displayed in the headerless main score after opening a part. This issu is reported as another [bug](https://github.com/musescore/MuseScore/issues/11408)
