### ISSUE TITLE
[MU4 Task] [GP] Display triplets correctly

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10331]
**Task description**
Triplets of 1/8 duration have no "lines" around "3"

**Current state:**
![Screenshot 2022-01-19 at 22 57 26](https://user-images.githubusercontent.com/24373905/150204399-f627a1a1-ab1d-4d92-b330-acf61bef5f0b.png)

**Expected:**
![Screenshot 2022-01-19 at 22 58 29](https://user-images.githubusercontent.com/24373905/150204541-629865b7-c683-4745-9bfd-0f7f4eba2b29.png)

**Comment by cbjeukendrup** [comment]
This is also a thing the user can edit in MuseScore using the Inspector for tuplets. Actually, I think MuseScore's default is better here; it is usual to hide the bracket if the notes are already grouped by a beam (except when the beam also spans notes that do _not_ belong to the tuplet; see also #8969). Of course, if this is a customizable setting in GP too, then it would be nice if that setting would be imported. Otherwise, I would personally prefer to let MuseScore do its default thing, which may be better (and will surely better once #8969 gets fixed).

**Comment by alexpavlov96** [comment]
@cbjeukendrup thank you, I will learn and ask about that!

**Comment by alexpavlov96** [comment]
can be edited in Musescore
