### ISSUE TITLE
Selection rectangle stretches over the whole page when selecting certain bars in certain scores

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10342]
**To Reproduce**
1. Open  [direction.zip](https://github.com/musescore/MuseScore/files/7907085/direction.zip)
2. Select 14th bar 

https://user-images.githubusercontent.com/90187801/150385470-8d1e2374-9aa5-4a2c-96c0-3147470c223e.mp4

**Comment by cbjeukendrup** [comment]
This seems to happen when there is after the measure a horizontal frame with a customized width.

**Comment by wizofaus** [comment]
Brief investigation showed it to be related to the skyline calculation which uses 100000 as a maximum y in certain cases, and this ends up being part of the boundingRect for the selection.  Specifically SkylineLine::add( ), line 192 of skyline.cpp.  I don't really understand why it's doing this, but that much is the same in v3.  But I'm not sure if v3 has the same selection rect issue...

**Comment by Tantacrul** [comment]
Just checked. Still occurring. I've never seen this before!

**Comment by cbjeukendrup** [comment]
Adding this case: (reported on Discord today)
![image](https://github.com/musescore/MuseScore/assets/48658420/d92888b6-f551-4a60-85e4-bd346a7ddab6)
![image](https://github.com/musescore/MuseScore/assets/48658420/5fb7bf4a-8b00-48dc-9e51-554ae540298c)

**Comment by adazem009** [comment]
**Here's how I reproduced this:**
1. Open [10342.zip](https://github.com/musescore/MuseScore/files/12038104/10342.zip)
2. Remove the articulations from the first note.
3. Select the first measure.

**Result:**
![Screenshot 1](https://github.com/musescore/MuseScore/assets/68537469/31e6df58-1cd5-491d-bfec-740b2e13c78b)

**Possibly related:**
When you select the second measure after these steps, the dynamic markings are selected instead of the measure.

![Screenshot 2](https://github.com/musescore/MuseScore/assets/68537469/ee2fc1f2-794a-4729-b820-1d54c288747b)
