### ISSUE TITLE
[MU4 Task] [GP] Display capo and relate fingering to it

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10378]
**Task description**
Show fingering related to capo, not zero. 
(Notes in standard notation are correct, the task is only about tab notation)
Capo itself should be also displayed

**Current state:**
Counting starts from 2
![Screenshot 2022-01-25 at 19 15 17](https://user-images.githubusercontent.com/24373905/151015239-ba65af5c-331d-4505-b402-5ca091df7651.png)

**Expected:**
Counting starts from 0, cause capo is 2
![Screenshot 2022-01-25 at 19 14 25](https://user-images.githubusercontent.com/24373905/151015089-f8285750-995b-4558-a226-4b435909488c.png)

**Comment by boryskuzmenko** [comment]
Reopen due to the issue is partly fixed.
Each Capo mark should be placed above it's related staff. Also Capo mark is absent in the part
See screenshots:
![Capture 2022-04-18_10-05-46_PM](https://user-images.githubusercontent.com/101250347/163861697-3f125957-14c3-44be-84ef-03aa3abda22a.png)
![Capture 2022-04-18_09-54-54_PM](https://user-images.githubusercontent.com/101250347/163861706-14b0612f-a8e4-4ec8-b0bc-378bc205ad9f.png)

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/10765
Tested on macOS 12, Win 11, Ubuntu 20
