### ISSUE TITLE
[MU4 Task] Add support for Noteperformer

### ISSUE THREAD

**Issue by ShawkMusic** [musescore/MuseScore#10388]
**Task description**
A short and clear description of what the task is.
Add support for Noteperformer

I've heard some pieces that use Noteperformer and I've been blown away by how good and expressive it sounds, especially for a digital instrument. It would be great to be able to use it in Musescore!
In [this post](https://musescore.org/en/node/280970), a user sent Noteperformer a request to support Musescore and this is what they said:

> WI Technical Support
> 
> Hi -----!
> 
> It's not an active decision by us to not support Musescore, but
> Musescore does not at all support 3rd party audio plug-ins, which is a
> technical necessity to begin with along with some form of configurable
> patch/articulation management over MIDI. So you'll probably be better
> off asking Musescore about this. :)
> 
> If Musescore were to add a system where we could create a high-quality
> integration, we would be happy to port our software.
> 
> Best regards,
> Arne
> Wallander Instruments

The replies also have lots of people supporting the request.
I think this would be a great addition to Musescore. Noteperformer is the closest I've ever heard digital software come to sounding like a real performance of a piece, and being able to hear my music come to life like that would truly be amazing for me and for every other composer out there who can't get a real orchestra to play their pieces.

**Comment by cbjeukendrup** [comment]
This is a _feature request_, not a _development task_. For feature requests, please use the forum on MuseScore.org. 

But for this particular feature request, you don't need to post anything, since we already know that some people think they would like to have NotePerformer in MuseScore, and people already know (or should know) that this is not a priority for us at the moment, as stated in announcements on MuseScore.org posted by the team. Instead, we are focussing on other playback features for now, including a system to properly map notated technique markings to proper playback.
