### ISSUE TITLE
Choose Instruments Panel: Search categories are often incorrect.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10420]
**Describe the bug**
When searching for an instrument, the categories shown on the left can often be wrong. For example, when searching for 'Snare', I became confused because I wanted the 'Marching Band' type. When I checked the categories on the left, they did not highlight the 'Percussion - Marching' category.

![image](https://user-images.githubusercontent.com/21022311/151946753-2fc850b5-3edc-4628-b4f8-846781219007.png)

The next snare down, also has this problem:
![image](https://user-images.githubusercontent.com/21022311/151946841-3074fa1b-e32b-4e9f-aace-7a82b90f8122.png)

I also notice that the category dropdown still say 'Common', where it should say (while the user is searching) 'All instruments'. 

Here's another example:
![image](https://user-images.githubusercontent.com/21022311/151947189-146422af-95be-46f3-be7e-9863160423fe.png)

And one more:
![image](https://user-images.githubusercontent.com/21022311/151947292-eb15d0c0-50dc-4c67-818f-4462032941ce.png)

**Comment by Tantacrul** [comment]
The reason I'm marking this as a P2 (and not a P3) is because it causes confusion and reduces communication, which makes it harder to select the correct instrument.

In MS3, this handy thing existed, which made your instrument choice very simple to understand. Without this bug being fixed, MS4 is a bit more obscure.
![image](https://user-images.githubusercontent.com/21022311/151949013-cae3675d-1597-4df4-b043-e02d437fb046.png)

**Comment by oktophonie** [comment]
The marching instruments are awkward as they have similar names to other instruments but different instrument definitions (different labels, numbers of lines, etc.)

Fortunately there are only four of them. How about we change the _score labels_ to:
- Snares / S.
- Tenors / T.
- Toms / Tom
- Basses / B.

And their names in the instrument panel to the same, perhaps with "(marching)" suffixed? (Since "Tenors" and "Basses" remain ambiguous).

We should remove "Concert" from the instrument labels for the orchestral Snare Drum, Bass Drum, Tom-toms etc. too (but they could remain in the name used in the instrument panel, for extra clarity).

**Comment by shoogle** [comment]
To be clear, as you type characters in the search box, no category is highlighted on the left. This is the **correct** behaviour (because the search results can include instruments from multiple categories).

![image](https://user-images.githubusercontent.com/11011881/152075038-f5808e72-6df4-4a7b-9c39-cdd1b17c843c.png)

However, if you then select one of the instruments from the search results, sometimes an incorrect category is highlighted on the left.

![image](https://user-images.githubusercontent.com/11011881/152075189-25eb309f-9bee-41b2-aa73-6b3a9fabf718.png)

As @Tantacrul said, when 'Snare Drum' is selected on the right, we would expect to see 'Percussion - Marching' highlighted on the left instead of 'Free Reed'.

**Comment by DmitryArefiev** [comment]
Fixed in #10828
