### ISSUE TITLE
Nothing should be selected on the score when a new score is created, or an existing score opened

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10428]
**Describe the bug**

1. When you **first create a score**, MS4 selects a rest in the first bar by default. The consequence is that your very first note input action produces an unexpected result (splitting or lengthening a rest). This is very different experience to MuseScore 3, which has nothing selected by default.  It makes the opening experience of MS4 weird & unexpected.

2. When opening an **existing score**, MS4 selects the left-most bar line by default. This is even worse because when the user tries to select a duration in the note input bar, it appears not to do anything (it actually deselects the barline). Then you have to click on it a second time for it to work.

**Expected behaviour**
When a score (new or existing) is opened, nothing on the score should be selected by default

**Video**

https://user-images.githubusercontent.com/21022311/152172123-080c8e1a-dcb9-4a70-ad1b-51db933d9c80.mov

**Comment by Tantacrul** [comment]
Ah, I just worked in the default template (the one stave piano) in MS3 and noticed it didn't do that.

However, I definitely think it does not make sense to select a rest by default when a new score is created, for the reasons I gave above. What do you think?

When opening an existing score in MS3, it seems to not select anything by default and I think MS4 should do the same. As I mentioned, it selects a barline by default:
![image](https://user-images.githubusercontent.com/21022311/152195756-ece67dde-1a77-4863-8f54-c5adfedbc028.png)

**Comment by DmitryArefiev** [comment]
> However, I definitely think it does not make sense to select a rest by default when a new score is created, for the reasons I gave above. What do you think?

Oh that's fine for me! My only suggestion for the new behavior is that the first Tab (when navigating) should move focus to the score and select something in the score (the first clef or rest)

**Comment by Tantacrul** [comment]
Perhaps we should have a call to discuss that last suggestion so I fully understand. Tomorrow?

**Comment by DmitryArefiev** [comment]
Sure!

**Comment by MarcSabatella** [comment]
I'm not really understanding the issue regarding having the first note/rest selected as per how MuseScore has always worked in the past.  The first action one normally takes in entering notes is to press "N" for note input mode, and this works the same regardless of whether there is a selection at start or not.  It also works the same whether the initial selection is the first note/rest or the initial barline.

For accessibility reasons, first score element (usually barline if present, clef if not) makes more sense when opening an existing score, btw - because then all you need to do is navigate right to read the entire score.  With the first note/rest selected, you have to first navigate left to understand the clef/key/meter.  When creating a new score, this is less important, since presumably you know what you just created.  But for consistency's sake, it should be harmless to just always select the first barline.  Or, for that matter, the title frame if present.

BTW, regarding note input, I understand changes have been over the past couple of years to also allow things to work if you forget or don't know to do this and instead try selecting a duration first and then typing a letter, but are we really expecting many users to be doing exactly that?  Seems to me new users might select a duration but still not know what to do next - they are unlikely to realize they can now simply type a letter.  And experienced users know to use note input mode.  Unless we are actually getting rid of that for MU4?  I'm guessing not, and the concert here is just to avoid the surprise of the duration icon changing the score unexpectedly.  That's solved nicely by selecting the initial barline / clef / title frame instead of the first note, whether it's a new or existing score.

**Comment by Tantacrul** [comment]
We've updated the accessibility so it is much easier (and more in line with accessibility standards), so I'm less concerned about issues there.

To answer your question: yes, I think the majority of new users will click on a duration first and try to place it on the score. I've done a bunch of testing of various apps and that's by and large what people do.

Your first action should not produce a puzzling result. It should not have to be to deselect a rest (or a bar line).

**Comment by Tantacrul** [comment]
We will need to do some accessibility testing once beta is released for sure. There are bound to be some bear traps and we'll need to refine the experience for sure.

We have dedicated a lot of time to accessibility in this release and will continue to do so.

**Comment by MarcSabatella** [comment]
Agreed that it seems logical that new users would click a duration symbol as their first action, and this shouldn't do something unexpected like change the default measure rest into something else, which is exactly what it does in 3.6.2 for new score because we are selecting the first note/rest.  So I'm all in favor of changing that.

I just think it makes the most sense to solve this by selecting the first *element* of the score - title frame, barline, or clef normally - than by selecting nothing.  In 3.6.2, opened (as opposed to newly created) scores do just that, and it works perfectly - if you then click a duration icon, you are put into note input mode on the first measure with that duration selected.  I see that indeed, MU4 broke this and does nothing but deselect the element.  I propose it simply be fixed to work exactly as 3.6.2 does when the first element (title, barline, or clef) is selected.  And furthermore, to select the first element both when opening and creating scores, as opposed to only when opening them as 3.6.2 does.

**Comment by Tantacrul** [comment]
I don't have an issue as long as the duration buttons work right away.

Thanks, Marc!

**Comment by Tantacrul** [comment]
Just to be clear: I think the existing MS3.6.2 behaviour when a new score is created is wrong. It selects a rest, which gives a weird result when you click on a duration for the first time.

**Comment by MarcSabatella** [comment]
Agreed.  What 3.6.2 does on *open* of a score is good, but on *create* not so much.  I'd like to see MU4 select the first element (title/barline/clef) in both cases - open and create.  Although selecting nothing could be fine *if* it can be made clear to a blind user how to start navigation.  The advantage of selecting something is that the screenreader will read it so you know something loaded successfully. but as long as people can figure out what to press to begin navigation, it would probably be fine to have nothing read right away.  As it is, we have a kind of uncomfortable split between Left/Right versus Alt+Left/Alt+Right in terms of how they behave if nothing is selected, or if something other than a note or rest is selected: Left/Right do nothing useful, Alt+Left/Alt+Right do.  And that's actually the one nice thing about the 3.6.2 new score behavior - with the first rest selected, it's ready for you to press Right and have something happen.  Still, it would be better to somehow steer screenreader users towards Alt+Right, since that's the command meant for this purpose.

**Comment by Tantacrul** [comment]
Now that I experience this more, the existing behaviour is doubly problematic. First off, if some random element is selected on the score by default, then the inspector doesn't show global options. In the case of a barline, it shows some really weird stuff and the user won't have any context to understand what any of it means (because those options didn't appear as a result of anything they've done).

Again, I do not see the purpose of selecting something on the score by default and I think it is almost certainly going to cause confusion for the vast majority of people. I've checked the other major notation apps and none of them do it either.

So, I think we should remove this behaviour and have nothing selected on the score by default.

I don't think a blind user is aided by having something like a bar line selected by default. If they press tab, then they will immediately be taken through the proper ordering.

@DmitryArefiev - I'd like to understand better why tab should first select an element on the score. At some point, we can have this conversation. But for now, I think we can just remove the existing behaviour and change the tab behaviour later.

**Comment by MarcSabatella** [comment]
The point of selecting something for accessibility's sake is so the screenreader says something meaningful right off the bat.  And as I said, that would actually be more relevant if we did this for *existing* scores - there isn't anything meaningful to read for newly created scores anyhow.  We *don't* select anything in existing scores, which is a minor nuisance at most for blind users, but no loss at all if we don't do it for new scores either.

BTW, the first a blind user would press after loading or creating a score is not Tab, at least not currently in either MU3 or MU4.  That starts selecting UI controls - definitely not what one would normally want.  Instead, to read an existing score, you start with Alt+Right, or in a new score, presumably you want to start entering notes and thus press N.  Tab might be a reasonable choice for a very first time blind user just wanting to explore the interface.  But in regular use after that, they would normally want to go straight into browsing an existing score or entering notes into a new one - so, either Alt+Right or Tab.

BTW, a related note - it is generally considered an important principle for operations to not *lose* the selection in any program where selection relates to navigation.  We enhanced Alt+Left/Right a couple of releases so that even if the selection ever gets lost (including the user accidentally pressing Esc too many times), we remember where the last selection was and continue navigation from there.  but we didn't do that for Left/Right, and we should have, and should for MU4.  That way you can begin browsing a score with just Left/Right even though nothing is selected on either load of existing score or create of new one.  Right now those keys do nothing with no selection, so there is no loss in functionality or usability impact if we start doing something reasonable.

**Comment by Tantacrul** [comment]
I certainly agree on many of those last few points and I think they should be raised as separate issues. By and large, if tab, left or alt+left immediately selects something, I think we'll be in a v.good place.

**Comment by Tantacrul** [comment]
We also need to put out the alpha so blind users can test it and give feedback.

**Comment by Tantacrul** [comment]
@cbjeukendrup - if you've time, can you tackle this one? I've already watched enough people accidentally split a rest rather than enter a note ... and be shown senseless options in the Properties panel related to a selected item on the score to be able to stand this any further :D

**Comment by cbjeukendrup** [comment]
Yes!

I also noticed that there is no visual indication when the notation view is focused by keyboard navigation. Would it be an idea to give it the same kind of focus border as other UI elements? That would look like this:
<img width="1262" alt="Schermafbeelding 2022-03-30 om 19 51 42" src="https://user-images.githubusercontent.com/48658420/160899534-84a4600f-6e4c-46c3-8a13-46c327254a47.png">

**Comment by Tantacrul** [comment]
Very much agreed
