### ISSUE TITLE
[MU4 Issue] Migration dialog: X button should work as Cancel and should not open the score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10421]
https://user-images.githubusercontent.com/90187801/151978016-115f50a9-5911-4cfe-b534-69c328e046f0.mp4

**X button** in Migration dialog (when open a score older than v4) **should not open the score** (should only close the migration dialog)

**Additional details**

X button should work as Cancel in all 3 dialogs:
![01](https://user-images.githubusercontent.com/90187801/152418027-cc619a55-9122-4956-84ba-c13e1b3f1a45.PNG)
![02](https://user-images.githubusercontent.com/90187801/152418034-706e6fbc-09e5-4e2a-b45c-e70d3ef4302b.png)
![03](https://user-images.githubusercontent.com/90187801/152418045-be2f152f-07ba-4789-b6b0-3888cccb16e9.PNG)

**Comment by iwoithe** [comment]
Hi there! I would like to work on this issue. Is there any other details I should know?

**Comment by vihaanthora** [comment]
@DmitryArefiev Is there a need to assign this issue to someone, or can we work on it and eventually send a PR?
Thanks

**Comment by RomanPudashkin** [comment]
@vihaanthora

You can work on it, but make sure that you and @iwoithe don't do the same thing at the same time. If you fix this issue together, I can assign it to one of you

**Comment by vihaanthora** [comment]
@iwoithe Could you please let me know the approach you're using to deal with this issue?
Thanks

**Comment by rzvxa** [comment]
@DmitryArefiev @RomanPudashkin  Hi, I've spend few hours reading the codes to understand the structure of the projects and I've found a few obvious bugs, Firstly we don't use the result of migration dialog nor the result of variable isApplyingMigration variable from dialog, there is also some problems with where the migration functions are called and i guess it's not working 100% correctly(need some more tracing to be sure). I think there is some problems with porting these stuff from mscore 3 so i would love to just refactor this section of the project so we don't get more bugs as we going toward alpha release and other releases.
@vihaanthora @iwoithe as it's been 3 days since u guys wanted to start working on this issue I was wondering if there is any progress from you guys or may i get the task and send PR?

**Comment by vihaanthora** [comment]
I have not made much progress as of now, you can go ahead with it @rzvxa .

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
