### ISSUE TITLE
Lyrics: Extender lines can be too short.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10441]
**Describe the bug**
I've noticed that extender lines for lyrics (created using the shortcut **Shift + -**) don't always range far enough:

Here's an example from MS3 and 4:
![image](https://user-images.githubusercontent.com/21022311/152386395-3cc029dd-cd91-4b5c-aa41-8acc24559fce.png)

Here's an older example from MS2... although this only looks clearer partially because the font is narrower
![image](https://user-images.githubusercontent.com/21022311/152386475-e2afe035-d4ee-45c5-908b-af4682d17647.png)

**See video**
https://user-images.githubusercontent.com/21022311/152386503-db3beba9-e54d-49e1-b3fd-117b5b8c2032.mov

**Comment by Tantacrul** [comment]
@oktophonie, @shoogle and @bkunda, I thought I'd tag you first to get your feels. I get that when the word is shorter, the line is more visible. It just looks weird in MS4 now because it appears like a full stop.

But this also strikes me as odd:
![image](https://user-images.githubusercontent.com/21022311/152387128-1a8388f4-8913-450f-bec0-9fb08bc88553.png)

**Comment by Jojo-Schmitz** [comment]
Those very short melismas can happen in 3.x too BTW

**Comment by Tantacrul** [comment]
Yes. I've noticed that. Initially, I thought it was an MS4 thing.

**Comment by shoogle** [comment]
> Min. melisma length

A minimum length setting sounds like a good idea.

I think that "melisma" just means a syllable that is sung for multiple notes, so lyric hyphens and extender lines are both melismas. Perhaps we should avoid using the term "melisma" to refer to just the extender lines?

**Comment by MarcSabatella** [comment]
The question is, what happens if the minimum is not met?  In cases like this, what I *think* most editors would do is simply omit the extender.  That would make sense to me.  What I wouldn't want to see happen is have MU4 artificially extend the extender past the edge of the note, or worse, add unnecessary extra space before the note.  Unless @oktophonie tells me I'm wrong about all this...

**Comment by bkunda** [comment]
I actually think these extenders are probably behaving as expected. From my understanding, extenders usually go only to the last written note – that is, to the notehead itself, and not the end of that note's duration. 

What I find interesting about the "Blues for Muse(Score)" example is that the text in question is set on a (short) off-beat that ties over to a longer note. It's all too easy to find examples where an extender line connects a long note to a short note, but I suspect examples of the opposite are rarer. The tie across two notes necessitates the extender, but the extender's length needs only to start from the end of the word and finish at the next notehead. 

Depending on the horizontal spacing between the two notes, as well as the length of the word itself, this might produce only a very short extender (like what we see in this issue). If the word is so long that it actually crosses into the tied (longer) note, then perhaps an argument can be made that an extender wouldn't be required at all (as @MarcSabatella has suggested). 

Extenders in this situation make more sense if the horizontal space is greater, as in this example:

![Screenshot 2022-02-04 at 5 10 32 pm](https://user-images.githubusercontent.com/86290556/152483656-7de36dfe-8fcd-4de5-a278-a01cb21e7176.png)

But really, this question lies in the domain of our expert (@oktophonie!). I merely present my thoughts because I was asked, and because I enjoy perusing juicy scores for yummy examples 😋. 

Also I don't think an extender would be required in the example of the word "Damn_" (above) 🙂

**Comment by oktophonie** [comment]
I think Marc is right here - we could set a minimum length for the extender (1sp, or something); if there is not space for an extender line of at least that length, between the right side of the syllable and the right edge of the final notehead, then we simply omit the line. This is what I'm used to and would expect to see.

For sure we shouldn't arbitrarily extend the line past the note, and (definitely) not increase space between notes purely to accommodate the line.

A partial fix for this was attempted in the 3.6 backend, but as well as needing ported over still, it also is faulty (see #9747) so will need some corrections.

**Comment by mike-spa** [comment]
Yeah, I agree with @MarcSabatella and @oktophonie: the extender line should be simply omitted when too short, as it serves no purpose at that point. I think I may have fixed it, would you mind taking a look at the attached screen capture and let me know if that is also how you would expect it to behave?


https://user-images.githubusercontent.com/93707756/152540442-fb5bf27d-0307-4952-930e-a11d4e380e46.mp4

**Comment by Jojo-Schmitz** [comment]
Looks good but stops showing the extenter line too early

**Comment by mike-spa** [comment]
> Looks good but stops showing the extender line too early. At least the length of a dash should still be shown IMHO

Yeah I agree, indeed I've already gone back and changed it. I think the minimum length should be 1 sp as @oktophonie suggested.

**Comment by Jojo-Schmitz** [comment]
Or reusing the Min. or Max Lyrics Dash length (0.4sp and 0.8sp by default, respectivly)?
