### ISSUE TITLE
[MU4 Issue] Additional Score Information>Time Signature>Popup elements are cut off

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10489]
**To Reproduce**
1. Go to Create New Score>Next>Additional Score Information>Time Signature

![TS](https://user-images.githubusercontent.com/90187801/152972827-50d39c37-3baf-4e81-8c04-02d96f071c93.png)

**Platform information**
 macOS, Windows, Linux

**Additional context**
Broken recently

**Comment by cbjeukendrup** [comment]
I think it has to do with PR #10162. This PR sets `clip: true` on StyledFlickable etc., and RadioButtonGroup now uses StyledFlickable, but did not have `clip: true` in the past. Therefore, it is now clipped while it shouldn't be.

Obviously, one solution would be to set `clip: false` in RadioButtonGroup.qml. But I believe I have seen more cases where clipping is not desired (unfortunately, I don't remember where...). So, maybe we should remove `clip: true` from StyledFlickable etc. and apply it only in the cases where it is desired. 
We should just figure out whether there are more cases where we _do_ want clipping than where we _don't_ want it; if so, choose the first solution, otherwise the second.

**Comment by vihaanthora** [comment]
Hi, can I work on this issue? 
P.S. I am quite new to the MuseScore code base and might require some assistance to get started, but believe that this issue is a good way to get started :)
Thank You

**Comment by duanjr** [comment]
> Hi, can I work on this issue? P.S. I am quite new to the MuseScore code base and might require some help to get started, but I believe that this issue is a good way to get started :) Thank You

[cbjeukendrup](https://github.com/cbjeukendrup) had shown it clearly. But one more thing to notice is that: RadioButtonGroup uses StyledListView, instead of StyledFlickable.

**Comment by vihaanthora** [comment]
@cbjeukendrup, in your opinion, which would be the way to go for now; removing `clip: true` or changing it to `clip: false`? I saw [this ](https://doc.qt.io/qt-5/qtquick-visualcanvas-scenegraph-renderer.html#clipping) documentation and I think it indicates that setting clip to true should be avoided for some items if possible. Please let me know if this holds for our use case also.
Regards

**Comment by cbjeukendrup** [comment]
@vihaanthora I did not know yet about that documentation. It looks like it is okay to use clipping on items like `ListView` and `GridView`, so we're not doing something really bad. However, clipping does come with some cost, apparently.

I estimate that in most cases we _do_ want clipping, so let's keep `clip: true` in StyledFlickable, StyledListView, StyledGridView etc.. So you'd only need to add `clip: false` in RadioButtonGroup.qml.

**Comment by vihaanthora** [comment]
@cbjeukendrup Understood your point, can I make the change and send a PR?

**Comment by cbjeukendrup** [comment]
@vihaanthora Yes, that would be great!

**Comment by vihaanthora** [comment]
I have sent a PR, please check and let me know if any changes are required.
