### ISSUE TITLE
[MU4 Issue] Changing Score properties settings doesn't make score dirty and some fields don't save

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10522]
**Describe the bug**
1. Changing Score properties settings doesn't make score dirty (see video to compare with MU3)

2.  Some fields don't save - **workTitle** and **creationDate**. If they shouldn't be editable then should be greyed out

https://user-images.githubusercontent.com/90187801/153402027-eb069153-7491-41bb-97d6-d6cd9aaed78a.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by sammik** [comment]
Possibly related info at forum.
https://musescore.org/en/node/327924#comment-1110792

**Comment by Jojo-Schmitz** [comment]
I disagree on `creationDate` being readonly. Needed when importing a file, which sets the creatinDate to the import date (as thatr is whxn this score gets created) rather than the creation date of the imported file, so may need to get corrected

**Comment by cbjeukendrup** [comment]
Then we either need to come up with a decent date picker instead of just a textfield, or we should always treat it as plain text rather than trying to parse it as an ISO date (see [src/project/internal/notationproject.cpp:651](https://github.com/musescore/MuseScore/blob/37f1382e992cd23f395c5a766e580a3e76e7265c/src/project/internal/notationproject.cpp#L651) and [src/engraving/libmscore/page.cpp:463](https://github.com/musescore/MuseScore/blob/37f1382e992cd23f395c5a766e580a3e76e7265c/src/engraving/libmscore/page.cpp#L463)).

**Comment by Jojo-Schmitz** [comment]
Either way is fine by me.

**Comment by HemantAntony** [comment]
This is likely solved by the new Project Properties Dialog (#10630)
