### ISSUE TITLE
[MU4 Issue] Unable to extend slur to the next system after selection (using shortcut)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10525]
**Describe the bug**
The same behavior in MU3 because the middle grip is selected and not the right end, but it can be improved.

**To Reproduce**
1. Select slur with mouse
2. Using shortcut Shift+Right, try to extend slur to the next system

https://user-images.githubusercontent.com/90187801/153417352-922951c8-884c-469b-b2ea-4b738dcf9060.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Occurs in MU3 too

**Comment by wizofaus** [comment]
The problem is that what's selected after the slur extends to the next system is just the first *segment*, rather than the whole slur. In fact in general there's no way of extending a slur that is broken over two systems.
However if it's agreed that the desired behaviour is for Shift+Right to extend a slur even if only one segment of it is actively selected, we can make that change. But I'm not sure it should be P2 if it's the same as MU3...

**Comment by Tantacrul** [comment]
Excellent find, @DmitryArefiev! It should just work as it does when you press **S** to create a slur and the use **Shift+Ctrl (command)** to extend it.

**Comment by Tantacrul** [comment]
Bumping to P1 because of how important it is and how easily someone could encounter it.

**Comment by DmitryArefiev** [comment]
Fixed in #11931
