### ISSUE TITLE
Quality of Life Improvement: Double Click to enter Note Input Mode

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10642]
**Task description**
This is a simple one. I think we should provide another way for users to trigger Note Input.

If a user double-clicks on a measure, Note Input mode should be activated.

<img width="107" alt="image" src="https://user-images.githubusercontent.com/21022311/155115933-3b0d63f5-926e-4e2e-9bc0-723dd75c92fe.png">

The result should be the same as selecting a measure and clicking the Note Input button:

<img width="99" alt="image" src="https://user-images.githubusercontent.com/21022311/155115968-435df365-1d89-4726-b1ab-15ae641dc284.png">

---

Once we do this, the natural next question is: **_should we also do this when a user double-clicks on a duration?_** Right now, doing this allows the user to reposition notes / rests with more freedom. I would argue that we should stop allowing this:

- It provides an obscure way for users to accidentally reposition notes in a way that looks weird. I have seen it in user testing a few times.
- There is very little practical advantage in allowing it and no user cases that I can currently think of that aren't highly niche / theoretical

**Comment by helloworld12321** [comment]
Currently taking a look at this. 🙂

**Comment by Tantacrul** [comment]
@helloworld12321 - just assigned you :)

**Comment by MarcSabatella** [comment]
I have mixed feelings about this.  Double-click of empty space to enter note input mode, that's harmless enough.  But double-click of an element in order to go to edit mode and thus enable fine adjustments - that's basic functionality that works for all other elements, and I'm not really comfortable with removing it for notes and rests.  On one hand, I share the e concern that people end up accidentally dragging things way too often, but on the other, it's not really that rare at all to need to do these sorts of adjustments.  Not every day, sure, but plenty of use cases come up in real world music - wanting to offset voices 1 & 3, for instance, or adjusting the position of a note relative to its lyric or chord symbol to achieve more efficient spacing, etc.  Presumably it would still be possible via the Inspector, and I guess that's good enough, but I really like being able to use arrow keys.  I guess as long as the "edit mode" command itself is still accessible via keyboard, that's good enough for me.  But it definitely feels like the sort of removal of functionality we'll be needing to explain to people over and over on the forums.

FWIW, at least some of the common use cases for these manual adjustments could be eliminated if we revisited a couple of older WIP PR's of mine:

https://github.com/musescore/MuseScore/pull/6312
https://github.com/musescore/MuseScore/pull/5840

@mike-spa , would you have any interest in seeing if any of these ideas could still be of use?

**Comment by cbjeukendrup** [comment]
Some tangentially related thoughts on "edit mode": I think it is really not MuseScore's strongest point. In MuseScore 3, it was already a bit vague, that the dragging behaviour suddenly becomes totally different after double-clicking on an element instead of single-clicking, but at least you could see in the status bar that "edit mode" was activated.
In MuseScore 4, it is even worse at the moment: there is no indication at all whether you are in edit mode or not. This makes it feel unpredictable, and even less discoverable than it was in MU3.
I think we should preserve the functionality of "edit mode", but we should probably overhaul the concept and at least give a clear indication whether "edit mode" is activated or not.

**Comment by MarcSabatella** [comment]
It should be noted that in order for *drag* to work, you don't really need a concept of a separate mode, as far as I can tell.  The only real point of a separate edit mode is to allow for *keyboard* adjustment.  Which is why in theory I'm fine with making it be activated by keyboard as well, although the shortcut in MuseScore 3 is probably known only to a small number of users, because double-click is so ingrained.

**Comment by Tantacrul** [comment]
> I guess as long as the "edit mode" command itself is still accessible via keyboard, that's good enough for me. But it definitely feels like the sort of removal of functionality we'll be needing to explain to people over and over on the forums.
> 

I think the idea of just making sure the keyboard shortcut is maintained and well documented is a good one. For me, double-click is just too important and interaction for this - very much a refuge for people who are just starting out.

Perhaps the right first step is to just do double-clicking for measures and then we can see if we also like it for notes and rests too?

**Comment by MarcSabatella** [comment]
Makes sense to try.  In practice, it can be hard to find an empty spot in a measure sometimes, so I'd not want this to be the main way anyone got to note input mode.  Even if we do decide to allow it for notes and rests, there are still the other symbols we definitely don't want to abandon edit mode for - articulations, accidentals, text, pretty much everything else.  So I have a sense it's going to feel a bit random, sometimes double-click goes to note input mode sometimes it doesn't.  Until the user figures out the pattern, anyhow.

**Comment by Tantacrul** [comment]
I am highly suspicious that most users don't know what edit mode is and probably just consider it to be a bug. I may be wrong. 

Question: it is unclear to me why edit mode is so useful for dynamics / accidentals / articulations / lyrics, etc. You can already move those things around by just dragging them and you can _**also**_ switch off automatic placement too. What specific additional benefit does double-clicking on them bring?

**Comment by Tantacrul** [comment]
OK, that's good to know.

For the record, I would be surprised if even 2% of our users know what 'edit mode' is and even less who use it for any practical purpose. Going to figure out how I can go about trying to determine this in a statistically significant way...

**Comment by MarcSabatella** [comment]
To me, it doesn't matter if it's 10% or 1%. what the number is.  It's still a feature relied upon daily by what would amount to many thousands of experienced users.  I am never in favor of "dumbing down" the program to make it easier for beginners but then not as useful after you progress past that stage.  Instead, if there are concerns that a useful feature isn't sufficiently well-known, let's address that directly, not remove it.

That said, again, there *is* a command to enter Edit mode via keyboard, and since the whole point of Edit mode is to allow keyboard adjustments, having the keyboard be the command be the only way isn't necessarily the end of the world, although people will grip if it's not easily discoverable.

**Comment by Tantacrul** [comment]
Actually, the % matters a great deal. If very few people know it exists and many more encounter bugs because it is obscure, then it should be replaced by something that can be understood, so the maximum number of people who would use it (if they knew it existed) can actually use it.

There is never an excuse to keep a poorly implemented feature. It's not 'dumbing down', it's just good design practice.

Anyway, I created a poll to get some kind of idea about how this feature is perceived. My '2%' is already proving to be too pessimistic but it is already clear that the feature is confusing and not well liked.

https://twitter.com/Tantacrul/status/1496480072714395649

**Comment by Tantacrul** [comment]
Also, can we just skip the usual 'why would you delete this' part of the argument because (as always) I am advocating for improving the feature, not removing it.

The only thing I think should be removed is the double-click assignment.

**Comment by Jojo-Schmitz** [comment]
I'm not on Twitter, but count my voice as "I'm aware and it is usefull"

**Comment by MarcSabatella** [comment]
But sure, I do agree if a feature that is useful to some but ends up causing confusion to others, there is room for improvement, and the numbers will help in making the determination of what to do about that.

**Comment by MarcSabatella** [comment]
By the way, by far the worst aspect of Edit mode as is 0 and, I think, the source of virtually all of the complaints about it your poll - is *specifically* about the fact that people accidentally enter edit mode when they are intending to drag notes as a way of transposing them.  That's based on comments I see as well as on years of experience answering questions about this on the forums ("how come I have a C but it pls like an E"), where we get to see sample scores and understand how the user accidentally did this.

So assuming we don't want to make transposing by drag harder, the fix as far as I'm concerned is simply to make make a drag operation automatically turn off edit mode, at least for notes and rests specifically.  That way edit mode is *only* about use of cursor keys.  Or maybe introduce a delay, here double-click followed *immediately* by drag is interpreted as transpose, but after half a second or whatever, it's a manual adjustment.

**Comment by Tantacrul** [comment]
I really would like to just move away from using double-click to enter into the mode at all... however, I don't have a concrete suggestion for a replacement yet. I have a few ideas but I'll need to flesh them out and share them.

**Comment by Jojo-Schmitz** [comment]
Right-click > Edit, like it also ever worked

**Comment by Jojo-Schmitz** [comment]
Also Alt+Shift+E

**Comment by MarcSabatella** [comment]
I certainly recommend keeping the context menu, and keyboard shortcut, but I recommend a shortcut that is more obvious than Alt+Shift+E.  Ctrl+E seems simpler and more logical, and I'd have no qualms about reassigning "add expression text".  But probably there is precedent in other apps to consider.  The idea of wanting to edit a selected element is common enough.  What shortcuts do they use?  Sure, for some, there is no separate edit mode - ones in which the cursor has no "navigation" function.  But presumably there is an intersection here, apps where cursor alone does navigation, but a command allows editing.  I suspect both double-click and Ctrl+E are common here, but I have no data on that.  Enter might be a possibility too, although we use that to add breaks and that probably is more important.

I'd note that whatever mechanism we use, it should probably be the same as for text edit, lyrics edit, chord symbol edit, etc.  It currently is - double-click works for all of these, as does the context menu, as does Alt+Shift+E.

**Comment by MarcSabatella** [comment]
Another thing to consider - if double-click becomes the way to enter note input mode, what effect does this have on people who currently are accidentally dragging notes when they intend to transpose them?  To me, that's a problem that needs solving completely independent of what the double-click actually does.  If the goal was to transpose, and accidentally double-clicking now puts you into note input mode instead of edit mode, what happens next?  Currently, if you try dragging in note input mode, nothing happens at all.  If the user accidentally double-clicks and finds nothing happens on the subsequent drag, I'm guessing their next impulse is to just try again.  Except this time, the click to initial the drag is about equally as likely to remove the existing note, add a new one, or do nothing  So it's almost as bad as the dragging in edit mode.

All of which says to me, the problem with dragging after double-click needs to be solved either way.  That is, regardless of whether double-click takes you to note input or edit mode, dragging isn't going to do what most users expect.  Simple solution here is actually to just make drag of a note *always* be transpose, never manual adjustment, regardless of mode.

**Comment by Tantacrul** [comment]
I think there is a case to be made for **not doing anything** on double click. However, entering a user into Note Input mode is at least a comprehensible thing to do, since that mode is so fundamental to basic understanding of how MuseScore works.

**Comment by MarcSabatella** [comment]
I agree that double-click needn't do anything in particular, but note input is as sensible as anything else.  Edit mode definitely should be more obvious no matter how you get there, like maybe highlighting the element being edited and graying everything else out (hmmm).

I do suspect think that even if double-click goes to note input mode, it's still likely to not be noticed right away if someone is just trying to transpose, and even if you notice, it's likely to be seen as an annoyance.  Frankly, although I'm never normally one to recommend removing features, I'd have been happy to have never had a transpose-by-drag feature in the first place.

**Comment by micpap25** [comment]
Hi; what's the status on this issue?

**Comment by Tantacrul** [comment]
Not sure. I can see the PR has double-click working.

However, I agree with @Jojo-Schmitz and @MarcSabatella that we should keep the Edit Element option in the context menu:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/21022311/162849984-463cef5b-3eca-4250-a48c-feba8d333d4a.png">

@helloworld12321 - is it possible you could include this and I'll ask @RomanPudashkin to review it then?

It will really help avoid situations where people accidentally double click on notes and displace them, so thanks!

**Comment by helloworld12321** [comment]
@Tantacrul PR #10691 is ready for review—thanks for your patience!
