### ISSUE TITLE
Spaces after commas not working. Typo correction & copy change for 'Learn' section

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10736]
**Describe the bug**
The text when videos can't load in the 'Learn' section needs a tiny bit of revision. There are two ',' symbols with no spaces after them and (being pedantic) you shouldn't have the word 'but' after a comma.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/21022311/156675766-eddbead1-4ba6-470f-b040-49fa7a400a03.png">

**Desired**
**"Sorry, we are unable to load these videos right now"**
"Please check your internet connection or try again later"

**Comment by cbjeukendrup** [comment]
Actually, there _is_ a space, but apparently in that font something strange happens with commas. Here's how it looks in Fira Sans:
<img width="644" alt="Schermafbeelding 2022-03-04 om 01 36 11" src="https://user-images.githubusercontent.com/48658420/156676713-1feb0407-f102-477c-98ff-b740ba303747.png">
I remember that I've seen that problem with commas eating spaces earlier... I think it was in the score migration dialog in MU3.6.

**Comment by Tantacrul** [comment]
Interesting! Although the copy should change anyway... we should look into this.

We're definitely planning to revert back to the OS default UI fonts anyway. This example is SF Pro.

**Comment by Tantacrul** [comment]
I've changed it to a P2 since it is shaping up to be a more significant problem.

**Comment by cbjeukendrup** [comment]
@Tantacrul curious observation:
- If you choose `.AppleSystemUIFont` in the dropdown in Preferences, this issue occurs;
- If you choose `SF Pro`, the issue does not occur. 

So apparently, `.AppleSystemUIFont` points to a wrong version of the font. 

Also, there is SF Pro, SF Pro Display, SF Pro Rounded and SF Pro text. Do you know which is the correct one?

Somehow, in MuseScore, these system fonts don't look like in the rest of macOS to me. But it must be an optical illusion, because if I take a screenshot of MuseScore and overlay it on a screenshot of another app, it turns out to be perfectly the same.
