### ISSUE TITLE
[MU4 Issue] Rewind and Play buttons don't behave as in MU3 when barline, line, slur etc. are selected 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10732]
( **Bug 1** )
When barline (or repeat line)  is selected,  Rewind button doesn't move selection to the first note (rest) of score - **UPDATE**: **NOT A BUG**, expected in **MU4**

**Bug 2** (most important)
When barline (or repeat line), lines (hairpin, ped), slur etc. are selected, Play button doesn't start playback from that location

https://user-images.githubusercontent.com/90187801/156643760-a723c477-d067-4a7f-b91e-d6120673e275.mp4

https://user-images.githubusercontent.com/90187801/157649478-30e47944-d6ea-42e7-bcfe-876f6b1348e6.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
I'm not sure about Bug 1, is this intentional or not for MU4.  But it doesn't correspond to MU3 behavior.

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I have indeed experienced cases where the space bar does not start playback at all (nothing seems to happen). Specifically, that seems to happen when selecting an element that will show grips when it is selected, such as barlines, slurs, etc.. Is that what you mean? That is indeed a separate bug. 

About bug 1, I think that there is indeed an intentional change in behavior. In MU3, the rewind button seems to work indirectly, by selecting the first element and thus triggering the playback cursor to jump to that element. But in MU4, the rewind button directly talks to the playback system. 

However, I discovered that when there is a range selection, the rewind button will rewind to the beginning of the range, rather than to the beginning of the score. In the code, it looks like this was added deliberately by Roman in 965710a7b4697a700d50e1683ffe6c8e53744eb1, but I'm not sure if that is how @Tantacrul has it in mind.

**Comment by Tantacrul** [comment]
I didn't specifically state that this is how it should work but I may have miscommunicated.

My feeling is that the rewind button should be 'dumb' (not contextual). However, I would like second opinions. What do you think @cbjeukendrup ?

**Comment by cbjeukendrup** [comment]
I also think that the rewind button should always rewind to the beginning of the piece, or if looping is enabled, to the beginning of the loop. 
At the moment that you _make_ a range selection, the playback position is already rewinded to the start of that range selection, so it would be pointless or even confusing if the rewind button would also rewind to that selection (it would seem like the rewind button is broken, because nothing happens, because the playback position is already at the place you're "rewinding" to).

**Comment by Tantacrul** [comment]
Agreed. Let's go for consistency and predictability. :)

**Comment by cbjeukendrup** [comment]
Fix pushed to #11322!

**Comment by DmitryArefiev** [comment]
> I have indeed experienced cases where the space bar does not start playback at all (nothing seems to happen). Specifically, that seems to happen when selecting an element that will show grips when it is selected, such as barlines, slurs, etc.. Is that what you mean? That is indeed a separate bug.

@cbjeukendrup Yes, I found after pressing Escape (when grips disappear) Space working fine with slurs/hairpins. Will log it separately.

**Comment by DmitryArefiev** [comment]
> Fix pushed to #11322!

@cbjeukendrup I found a regression in your latest build:

**Playback cursor do

https://user-images.githubusercontent.com/90187801/165581283-e6a91040-1260-4e21-adbe-f6e1399bd2cc.mp4

esn't move to clicking notes** (only to range selections):

**Comment by DmitryArefiev** [comment]
Fixed in #11322

Issue about Space bar logged in #11450
