### ISSUE TITLE
[MU4 Issue] Tab key does not function to navigate while entering chord symbols

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#10745]
The Tab key is intended to navigate measure by measure while entering chord symbols (or Roman numeral analysis, or other related elements).  However, this currently does not work - it instead transfers keyboard focus to other GUI elements within the main window.  That's expected behavior while not in one of the text edit modes, but not while entering text.

To reproduce:

1) new score
2) select first rest
3) Ctrl+K
4) type C7
5) press Tab

Result: keyboard focus moves to another area of the GUI, rather than simply moving the chord symbol input cursor to the next measure of the score

**Comment by boryskuzmenko** [comment]
@MarcSabatella can't understand why Tab should navigate to the next chord? For me it's expected behavior if Tab moves cursor to the next GUI element (by basic accessibility rules) and for chords there're specific shortcuts ` ; `and` : ` Ain't they?

**Comment by MarcSabatella** [comment]
Tab has always been the shortcut to move from measure to measure while in chord symbol entry mode.  "Most" music doesn't change chords every beat but rather only around once a measure, so really, this command is probably the single most important and commonly used shortcut for chord symbol navigation.  I'm not aware of a conscious decision having been made to remove that functionality or to change the shortcut. @bkunda was this deliberate?  I notice that Ctrl+Right - which was the most obvious alternative I could think of - does indeed do what Tab used to.  If that was the plan all along, OK.

FWIW, I do understand that Tab has an important accessibility function when *not* in chord symbol edit mode, but really, I'm not convinced that needs to take precedence over its function here.  After all, we actually allow you to use Tab to enter tab characters within normal text, even though they don't really do anything different from space.  Someday we might support tab characters more fully., though, and then we'll need Tab to do that.  And obviously, other programs that support tabbed text deal with this - Tab just does one thing while editing the text, something else while navigating the interface.  I don't think users find this surprising at all, so I think this will just come off as an unnecessary/gratuitous change.  But, now that I know Ctrl+Right does at least work, I'd be OK if that's still the official decision.

**Comment by wizofaus** [comment]
Probably wasn't intentional - I did a fair bit of the work on ensuring keyboard "shortcuts" that were element-specific (including while editing/entering chord symbols) worked as per v3, so it may just have been overlooked. But it doesn't sound like this is particularly critical if there are easy workarounds.

**Comment by bkunda** [comment]
@MarcSabatella I don't recall any intentional decision to change the functionality of tab in this context, but then again I wasn't a part of the accessibility redesign, in which perhaps this re-assignment took place 🤷‍♂️.
At any rate, the Ctrl+Left/Right shortcuts do seem to solve this problem fairly neatly, so I'd be inclined not to change anything here (particularly given the role Tab now plays in GUI navigation).

**Comment by ecstrema** [comment]
Unfortunately, although we can assign "go to next measure" to Tab, we cannot assign "go to previous measure" to shift-tab. 

It is for some reason not allowed.
