### ISSUE TITLE
Glissando text has poor formatting and often disappears

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10767]
**Describe the bug**
See video.

https://user-images.githubusercontent.com/21022311/157447397-2bc2c545-df67-449f-818c-eda745cfb3c1.mov

You can see the issue also affects the symbol in palettes too, which is also missing the 'gliss.' text.

**Comment by cbjeukendrup** [comment]
I found the root cause of this issue. See https://github.com/cbjeukendrup/MuseScore/commit/a55ddd803b27e18ac67ac8aa22d2959660ac511c for an explanation and a very dirty solution that is obviously no more than a proof-of-concept. Also see how it was in MU3: https://github.com/musescore/MuseScore/blob/2513676e512d29d554cb6c4d37d3efaf53ea2c5b/libmscore/glissando.cpp#L121
When testing any solution, we must also make sure that it works when exporting to pdf/png/..., not only on screen.

**Comment by DmitryArefiev** [comment]
@Tantacrul @oktophonie Now the gap between text and line became smaller, is it OK for you?
 (now it looks more regular fro my eyes, but asking just in case)

https://user-images.githubusercontent.com/90187801/175327365-01dd10f9-d118-4103-8735-1fbe2f40b061.mp4

**Comment by oktophonie** [comment]
It's much better than before! (it looks just like MU3 now, to me)

**Comment by DmitryArefiev** [comment]
Fixed in #10767
