### ISSUE TITLE
Instrument playback should be dynamic, based on the users selection on the score.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10795]
**Task description**
In most other notation apps (excluding Finale), users can quickly solo an instrument or hear a range of specific instruments by making a selection on the score. This is an incredibly useful feature that removes the need to fiddle with Mute/Solo buttons in the mixer and is long overdue in MuseScore.

It should work like this:

If a user selects an **element** on the score and then presses 'play', playback will behave as normal, including all instruments.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/21022311/158022006-d742191f-b056-477c-a9f8-fb703a355db5.png">

If the user makes the following type of selection (using 'Shift' or by selecting the measure), then playback will only be heard for the selected stave. In the example below, the user has selected the viola and cello, so only those instruments should be audible when the user presses 'play'.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/21022311/158022092-f63ae2f9-995f-4366-845d-3e9bf5d20e7d.png">

Bear in mind that multiple selections like this would NOT affect playback (see below). Only the 'blue box' selection should do that.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/21022311/158022366-e469d467-158d-4a95-bcc7-4ea42b453692.png">

This behaviour should not have any effect on the mixer UI or settings. In other words, the users selection should not alter the states of the **solo/mute** buttons. Also, if a user mutes an instrument in the mixer, it won't be heard regardless of the user's selection on the score.

Undoubtedly, this behaviour will be new for some users. However, when they become accustomed to it, the benefit will very evident.

**Comment by MarcSabatella** [comment]
I'm glad to see this coming back, it is indeed something many have requested.  But, I do wonder if one small tweak could improve the experience: special-case a selection of a single measure on a single staff, and treat that the same as a single-note selection.  Selecting a measure by clicking an empty area within it is a very simple and common way to start playback, and allowing that case to continue to work as easily as before should eliminate the unpleasant-surprise factor, I think.  You could still get a single staff to playback by selecting anything but exactly one measure.

**Comment by Tantacrul** [comment]
@MarcSabatella I understand the idea. I guess the problem would be that you can't then solo an instrument in the same way,right?

I suggest we run with this for beta. See what comes back and make sure to document this specific change in a video and perhaps add an option to disable.

**Comment by MarcSabatella** [comment]
You could solo an instrument by selecting *more* than a single measure.  But true, not totally consistent, and that's not good for learnability (although it's also what we do when adding clefs, key signatures, and time signatures, BTW).

Anyhow, maybe people will adjust to needing to click a note or rest.  But I have to say, several weeks into playing with MuseScore 4 builds regularly, *I* haven't adjusted yet.  I keep selecting a measure to start playback, and it doesn't work now.  It doesn't do this soloing thing, of course; it just does *nothing* - playback starts wherever it left off, as I hadn't selected anything.  So then I have to stop and select a note and restart.

And I know it won't be just me that has trouble adjusting.  I can't remember if you were around when this exact same behavior was implemented a few years ago, I think in a release candidate for 3.something, but it was withdrawn before release after a flood of complaints on the forum.  Withdrawing it was a mistake - I wish instead we had simply found a solution to allow both to coexist peacefully.  But we didn't give ourselves time to do anything but revert the change.

I definitely am not arguing about the feature, nor would I want to have to disable it for myself to get the old behavior back.  I just want the more common case of wanting normal playback to not be made more difficult - to somehow have my cake and eat it too.

If we don't want to special-case the single measure / single staff selection, another possibility is to have two separate commands - say, Space (or clicking the Play button) and Shift+Space (or Shift+clicking Play) - where one solos the selected staves and the other does not.  We could even make the Play button on the toolbar have a little dropdown like the note input to switch between the two modes, so whichever mode you've selected for the default operation of Space / Play, the *other* is available via Shift.  Or it could be a Preference to switch between the two.  Or other possibilities along those lines.

Anyhow, I'm all in favor of putting this out there as is and getting feedback.  But I'd advocate for sooner rather than later - the public alpha if possible.  Then if we decide it's the wrong call, we have more time to design an alternative.  And if it's the right call, we have more time to adjust.
