### ISSUE TITLE
Add the 'section' strings to the 'common' category

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10794]
**Describe the bug**
Currently, in the '**common**' category of the add instruments / new score dialog, we only show solo viol instruments. We shoudl also add the sections here too and rename them slightly.

To avoid confusing english speakers, who might not easily notice the difference between singular and plural, I think we should use the following naming convention:

- Violin
- Violins (section)
- Viola
- Violas (section)
- Violoncello
- Violoncellos (section)
- Contrabass
- Contrabasses (section) 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/21022311/158021256-697ad4f0-5ccc-41b9-8b2a-0accff33e689.png">

I considered adding 'solo' to the end of the solo instruments but felt it may get confused with the 'make soloist' button.

@shoogle - any thoughts?
@wizofaus - another simple enough one, if you have the time :)

**Comment by wizofaus** [comment]
Yeah very simple one to fix, just need to add `<genre>common</genre>` to each of those Instruments, but I'll do it once you decide that you definitely want to rename to "Violins (section)". Actually they already have a "description" field that is "Violin section" currently, but this isn't used in the Instruments dialog (and for other instruments that's quite long, like "Highest-pitched member of the viol family." for Pardessus de viole.)
The problem is that whatever's displayed here will be the same as the track title once added to the score, and you probably wouldn't want "Violin section" there.

**Comment by oktophonie** [comment]
The `longName` is what gets used in the score itself (or if it isn't, it should be!), so it's fine for the `trackName` (which is displayed in the new score wizard and in the mixer) to be different.

**Comment by wizofaus** [comment]
Yes, it uses the long name (except on subsequent staves etc. if you've opted to show the short name).
So do we want "Violins (section)" etc.?  Noting that it will display that in the mixer...

**Comment by Tantacrul** [comment]
> Yes, it uses the long name (except on subsequent staves etc. if you've opted to show the short name). So do we want "Violins (section)" etc.? Noting that it will display that in the mixer...

I guess so. Obviously there isn't a lot of room for text in the mixer, so that is a problem (not just in this case but in other cases too).

Perhaps later, we might decide to change the mixer so it uses the names displayed on the score. In fact, I'm not 100% sure why we don't do that... I'll need to check later. Curious if anyone has any opinions on that.

**Comment by shoogle** [comment]
Sorry I didn't see this earlier. I think these are sensible changes, but they have to be made in the [online spreadsheet](https://docs.google.com/spreadsheets/d/1SwqZb8lq5rfv5regPSA10drWjUAoi65EuMoYtG-4k5s/edit#gid=516529997) first before they can go in instruments.xml. Currently I'm the only person who can edit the spreadsheet. We can discuss opening it up to other people although that would require some coordination to prevent conflicts.

**Comment by shoogle** [comment]
@Tantacrul
> we might decide to change the mixer so it uses the names displayed on the score... Curious if anyone has any opinions on that.

It can be useful to have a part name in the Mixer that is different to the instrument name displayed in the score.

1. The instrument name might be empty because the user doesn't want it to appear on the score (e.g. on a piano staff).
2. The part name could show the English name of instruments that use the German names in the score (for example).
3. Part names such as "Guitar (tablature)", "Trombone (treble clef)", "Baritone Horn (Central Europe)", "Violins (section)" clarify information that is not given in the instrument name, which would just be "Guitar", "Trombone", "Baritone Horn" or "Violins".

**Comment by Tantacrul** [comment]
I would probably prefer the mixer to contain a name that matches what is written on the main score itself. It's also worth pointing out that the mixer doesn't have much horizontal space, so we'd not be able to display a lot of a name like **Baritone Horn (Central Europe)**

**Comment by Tantacrul** [comment]
I don't know if this comment squares with the desire to not include things like the word 'section' in 'Violins (section)'. It would be preferable if the mixer just said 'Violins'.
