### ISSUE TITLE
MuseScore failed to build with many error on arm64 windows 

### ISSUE THREAD

**Issue by YangYang129** [musescore/MuseScore#10850]
MuseScore failed to build with many error on arm64 windows. It can reproduces on version https://github.com/musescore/MuseScore/commit/4c4099777ca3a8cd05ff96e8c2dcc95612c74617. Could you please help look at this issue? Thank you very much

Environment
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019

Steps to reproduce:
1. open VS2019 x64 tools command
2. git clone https://github.com/musescore/MuseScore F:\MuseScore
3. cd F:\MuseScore
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. git submodule update --init --recursive
6. Cd F:\gitP\microsoft\vcpkg
7. bootstrap-vcpkg.bat
8. vcpkg.exe install --recurse sndfile --triplet arm64-windows --clean-after-build
9. install QT5(select UWP ARMv7 (MSVC 2019)) to folder C:\Qt
![image](https://user-images.githubusercontent.com/86757616/159220823-efe84cc7-8ff5-4802-a081-a5e9b552e467.png)
10. mkdir build_arm64 & cd build_arm64
11. set PATH=C:\Qt\5.15.1\winrt_armv7_msvc2019\bin;%PATH%
12. cmake -G "Visual Studio 16 2019" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="F:\gitP\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=arm64-windows ..
13. msbuild /m /p:Platform=arm64 /p:Configuration=Release mscore.sln /t:Rebuild >msbuild.log

Build.log:
[MuseScore_msbuild.log](https://github.com/musescore/MuseScore/files/8313790/MuseScore_msbuild.log)

Error info:
78>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB3721: The command "echo MASM not supported on this platform [F:\MuseScore\build_arm64\src\diagnostics\google_crashpad_client\gcrashpad.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB3721: exit 1" exited with code 1. [F:\MuseScore\build_arm64\src\diagnostics\google_crashpad_client\gcrashpad.vcxproj]
77>C:\Qt\5.15.1\winrt_armv7_msvc2019\include\QtCore\qprocess.h(49,1): error C2338: static_assert failed: 'Required feature processenvironment for file C:\Qt\5.15.1\winrt_armv7_msvc2019\include\QtCore\qprocess.h not available.' (compiling source file F:\MuseScore\build_arm64\src\framework\global\CMakeFiles\global.dir\Unity\unity_2_cxx.cxx)
77>F:/MuseScore/src/framework/global/internal/interactive.cpp(243,9): error C2653: 'QProcess': is not a class or namespace name (compiling source file F:\MuseScore\build_arm64\src\framework\global\CMakeFiles\global.dir\Unity\unity_2_cxx.cxx) [F:\MuseScore\build_arm64\src\framework\global\global.vcxproj]
    77>F:/MuseScore/src/framework/global/internal/interactive.cpp(243,19): error C3861: 'startDetached': identifier not found (compiling source file F:\MuseScore\build_arm64\src\framework\global\CMakeFiles\global.dir\Unity\unity_2_cxx.cxx) [F:\MuseScore\build_arm64\src\framework\global\global.vcxproj]

**Comment by Jojo-Schmitz** [comment]
Why Qt 5.15.1 rather than 5.15.2? (Not sure it makes a difference, but it may well do)

**Comment by YangYang129** [comment]
@Jojo-Schmitz  QT 5.15.2 does not display in QT setup
![image](https://user-images.githubusercontent.com/86757616/159236827-0e20897f-de9a-4e61-ac9b-c8a2c160233c.png)

**Comment by Jojo-Schmitz** [comment]
It certainly does for me, on Windows 11 and an x64 arch.

**Comment by cbjeukendrup** [comment]
Actually all those errors seem to refer to things outside MuseScore that are not supported yet on arm64. It might be a bit better with Visual Studio 2022, and it might be better in the future when we switch to Qt 6.3+.

**Comment by AntonioBL** [comment]
Ciao.
For the first error, you can try to disable the Crashpad client by modifying this line:
https://github.com/musescore/MuseScore/blob/c238f8cc471b3cc70dfb304fb2698b4bbf33adb0/src/diagnostics/CMakeLists.txt#L74

For the following ones, the culprit line seems to be:
https://github.com/musescore/MuseScore/blob/c238f8cc471b3cc70dfb304fb2698b4bbf33adb0/src/framework/global/internal/interactive.cpp#L243
I am not familiar with that part of the code. Maybe you can modify those lines so that the behavior, in this arm64 case, is like the one under Linux (i.e. https://github.com/musescore/MuseScore/blob/c238f8cc471b3cc70dfb304fb2698b4bbf33adb0/src/framework/global/internal/interactive.cpp#L247-L248 ). Or maybe you can simply "comment out" those lines and see if at least the compilation works, and then see if you have problems when trying to open files (I think those lines are related to the file opening dialog).


I think you will have also to avoid the installation of crashpad_handler (done during "install" step), and you will have to correct some enum class from "char" to "signed char".
It is quite a mess, but you can have a look at the modifications I made (by trial and error) for a custom arm compilation under Linux: https://github.com/AntonioBL/MuseScore/commits/4.0_ARM

Good luck :wink: 
Ciao,
ABL

**Comment by Jojo-Schmitz** [comment]
Maybe change to `#elif defined(Q_OS_WIN) && ! defined (Q_PROCESSOR_ARM)`, or `if QSysInfo::buildCpuArchitecture() == "arm64"`

**Comment by Jojo-Schmitz** [comment]
Reg. these enums see #10206

**Comment by Jojo-Schmitz** [comment]
#10206 just got merged, #11584 is related to this issue too , but still pending

**Comment by cbjeukendrup** [comment]
Another challenge is obtaining ARM versions of `zlibstat`, `libsndfile`, and all those other precompiled libraries in the `dependencies` folder. Also, google crashpad client contains asm code that is not supported on ARM.

**Comment by Tantacrul** [comment]
Issues related to building MS4 are best discussed on our Discord server. Closing for now.
