### ISSUE TITLE
[MU4 Issue] Ornament is not played when grace note is added to the same note

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11015]
**To Reproduce**
1. Create a score
2. Add a note with trill ornament (sounds good)
3. Add a grace note before the note with trill
4. Play them and pay attention to the ornament playback

**Expected behavior**
Ornament is also played when grace note is added to the same note

**Screenshots**
https://www.dropbox.com/s/78mu0y0fr8mrfgk/grace-notes-trills.mov?dl=0

**Platform information**
 - OS: [macOS]

**Additional context**
The issue is reproducible with all types of ornaments and grace notes

**Comment by Tantacrul** [comment]
Confirmed. All you have to do is this:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/21022311/173247579-a7c6fa76-e565-4a7c-ae79-f2d880299b3c.png">

**Comment by cbjeukendrup** [comment]
I looked a bit at the code and experimented accordingly, and found that this problem with the interaction between various kinds of items is a bit bigger. To give some examples:
- (for me, the issue with grace notes vs trills manifests the other way around: trill wins)
- various items are stopping glissandi from working. None of the following glissandos are working:
    <img width="630" alt="Scherm­afbeelding 2022-10-01 om 01 29 16" src="https://user-images.githubusercontent.com/48658420/193369077-76a02bf5-1545-4982-8172-2b35ec4a9aa1.png">
   (of course, it is debatable whether these examples make sense in any way)
- grace notes stop ties from working: in this example, you won't hear the second half of the measure
    <img width="225" alt="Scherm­afbeelding 2022-10-01 om 01 33 47" src="https://user-images.githubusercontent.com/48658420/193369315-4fa8b626-7e10-4104-bf97-af793f6e3c43.png">
- Tied notes stop glissandi from working: you won't hear this glissando
    <img width="236" alt="Scherm­afbeelding 2022-10-01 om 01 34 35" src="https://user-images.githubusercontent.com/48658420/193369364-eb6c9178-b91a-4151-9bef-65240c9e0065.png">
- Swing: 
    - Glissando seems not to be adjusted according to swing
    - tremolo, arpeggio and others cause swing not to be applied
    <img width="491" alt="Scherm­afbeelding 2022-10-01 om 01 42 47" src="https://user-images.githubusercontent.com/48658420/193369751-5e82f91e-a6d9-4376-b96e-0f4a8b8c4f59.png">

Anyway, I could go on mentioning examples, but generally the code has the following hierarchy:
1. ornaments / tremolo / arpeggio / grace notes (whatever is coincidentally the first in the list of so-called "chord articulations")
2. swing
3. tied notes
4. glissandos

If one of these is encountered, the following ones are sometimes not rendered.

The code in `PlaybackEventsRenderer::renderArticulations` (and the members called inside) is built on the assumption that different kinds of annotations are mutually exclusive and independent, but generally they are neither.

However, I'm reluctant of fixing it myself, since it might involve a relatively slightly big overhaul of certain functions.
