### ISSUE TITLE
[MU4 Issue] Default paper color, grey, does not tally with "Preferences" display

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11022]
**Describe the bug**
When the program is first opened (or you revert to factory settings), the default paper color is a light grey. However inspection of Edit > Preferences > Appearance > Paper > Color" shows that white is selected. 

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by boryskuzmenko** [comment]
Sorry, I don't see inconsistency here. Both colors on the references and on the paper itself are identical. And I do not see 'White' word on this preference.
![Capture 2022-04-01_10-30-29_PM](https://user-images.githubusercontent.com/101250347/161329922-1647df6f-c7b0-44b7-ab6b-7226b399f970.png)
![Capture 2022-04-01_10-31-35_PM](https://user-images.githubusercontent.com/101250347/161329932-94448144-7c30-41c2-b849-52fdf79aab82.png)


The issue is closed.
