### ISSUE TITLE
Preferences: defaults to "General", rather than last user choice

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11062]
**Describe the bug**
In MS3, Preferences always opened at the Tab which was open when the window was last closed. Now it always defaults to the "General" section rather than remembering the user's last choice.

**Expected behavior**

Preferences should open at the section last selected on closure.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by bkunda** [comment]
This is an interesting one. I'd actually like to do some proper user testing on this to see what people expect to happen. 

My design intuition tells me that, for those who _recognise_ that the tab they see on opening the dialog is in fact the last one they opened, this behaviour could be leveraged for enhanced workflow efficiency. But for those who _don't recognise_ this behaviour, the result could easily be confusion (which we always want to avoid whenever we can). 

I'd like to put this one down for a usability test in the near future. If it turns out I'm wrong and most people expect this dialog to behave this way, then I'm sure it can be easily changed. 

FWIW, I can also see that the master palette works in the same way that you've described, so this issue could potentially extend beyond the Preferences dialog.
