### ISSUE TITLE
[MU4 Issue] Actions without shortcuts are missing in Preferences

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11060]
**Describe the bug**

In MU4 Preferences > Shortcuts, the actions list is missing all the actions that did not have defined shortcuts in MU3.

For example, in MU3 there are actions for adding intervals above or below the current note. Only the "above" actions had shortcuts assigned.

![image](https://user-images.githubusercontent.com/11011881/172459052-802665c9-40e1-44f3-91e5-ec2c55122bb9.png)

The actions list in MU4 only has the "above" intervals, so it is not possible to assign shortcuts to "below" intervals at all.

![image](https://user-images.githubusercontent.com/11011881/172482802-2af3fc97-3720-44c8-932e-b87854b80d1b.png)

**Expected behavior**

All actions in MS3 should be available in MS4 as well.

https://user-images.githubusercontent.com/101250347/161807657-966ad3d1-64c6-4458-9d58-a0ea49dda132.mp4

**Platform information**
OS: Linux Mint 20.1 (Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7), MacOS, WIN 11

**Comment by boryskuzmenko** [comment]
Thank you for logging the issue. 
Screen record of the issue added

**Comment by MarcSabatella** [comment]
Right now from what I can see, the most glaringly obvious missing shortcuts are the navigation commands that are absolutely essential for accessibility as well as for keyboard use in general. In particular, the shortcuts for next/previous staff or voice. These commands seem to just be gone, unless they've been renamed to something I can't find, which is certainly possible.

Without these commands, it's impossible to navigate or edit anything but the top staff of a score without the mouse. So if they are truly missing, adding them back should be P0, as it's a complete showstopper for accessibility, and also quite bad for anyone trying to enter notes via keyboard.

Next most important missing shortcuts to me are F2 (special characters dialog) and Z (symbols palette). I would also put in votes for Shift+K/T for key/time signatures palettes. These are ones I find myself most often being disappointed by.

**Comment by cbjeukendrup** [comment]
@igorkorsukov In PR #11144, you commented that the solution to this issue would be to put all actions that _can_ have shortcuts in shortcuts.xml, even if they have no shortcut by default. 

Keeping task #11804 in mind (it's closed but still needs to be done), I had another idea. 

I propose that we give each UiAction in cpp a new field called `category`. We could have action categories like this:
```cpp
enum ActionCategory {
    Undefined = -1,
    Articulations,
    DialogsAndWindows,
    LayoutAndFormatting,
    ...
}
```
Actions that are not meant to be exposed, will get the Undefined category, which would be the default value. 

Also, I think that the current concepts of UiContext and ShortcutContext could be merged into one concept called ActionContext, and that it should be a property of the action itself. 

I would prefer if shortcuts.xml just provides a mapping between action code and one or more shortcuts, and nothing else. We should keep in mind that users have their own shortcuts.xml, which they can easily modify. I think we should not rely on a user-editable file for "sensitive" information like shortcut context or which actions should be public or not. For these things, I would prefer the cpp code to be the single source of truth. 

What do you think about these ideas?

**Comment by shoogle** [comment]
@cbjeukendrup, I like the idea of populating the actions list automatically from the C++ code rather than from the XML. I suggest calling the default category `Private` or `Hidden` if it has semantic meaning, rather than `Undefined` which implies we just haven't got around to giving it a category yet, otherwise someone might submit a PR that "helpfully" assigns categories to all the undefined ones.

**Comment by wizofaus** [comment]
Definitely agree that using shortcuts.xml is the wrong way to ensure actions show up in the shortcuts preferences page.  If there are actions that shouldn't be shown there, then having a way to mark them as 'private' makes sense, and then the shortcuts dialog should simply show all actions that aren't marked as such.  Whether 'private' should be a separate flag or a category I don't have a particular opinion on, though personally I'd go with whatever's the safest to implement at this stage.

**Comment by igorkorsukov** [comment]
> @igorkorsukov In PR #11144, you commented that the solution to this issue would be to put all actions that _can_ have shortcuts in shortcuts.xml, even if they have no shortcut by default.
> 
> Keeping task #11804 in mind (it's closed but still needs to be done), I had another idea.
> 
> I propose that we give each UiAction in cpp a new field called `category`. We could have action categories like this:
> 
> ```c++
> enum ActionCategory {
>     Undefined = -1,
>     Articulations,
>     DialogsAndWindows,
>     LayoutAndFormatting,
>     ...
> }
> ```
> 
> Actions that are not meant to be exposed, will get the Undefined category, which would be the default value.
> 
> Also, I think that the current concepts of UiContext and ShortcutContext could be merged into one concept called ActionContext, and that it should be a property of the action itself.
> 
> I would prefer if shortcuts.xml just provides a mapping between action code and one or more shortcuts, and nothing else. We should keep in mind that users have their own shortcuts.xml, which they can easily modify. I think we should not rely on a user-editable file for "sensitive" information like shortcut context or which actions should be public or not. For these things, I would prefer the cpp code to be the single source of truth.
> 
> What do you think about these ideas?

I like the idea of adding a category! 

But I think it is impossible to merge Ui Context and ShortcutContext , these are different things. Whether it is possible to send a shortcut depends on the current focus, and whether it is possible to send an action depends on the technical conditions. For example, when editing text, we cannot send a space shortcut to start playback, but we can send an action to play, for example by clicking a button or remote control by means of a midi controller.

**Comment by cbjeukendrup** [comment]
@igorkorsukov Thanks for your reply! @VanSHOE Let's work on this!

> I think it is impossible to merge Ui Context and ShortcutContext

Ah, yes, I see now how they are different. Let's not touch this area for now.

**Comment by Jojo-Schmitz** [comment]
Wouldn't this need to get reoipened, with the PR's changed being reverted?

**Comment by shoogle** [comment]
I don't understand why ShortcutContext is saved in Shortcuts.xml. I also don't think it is fully separate to UI Context.

>> @cbjeukendrup: I think that the current concepts of UiContext and ShortcutContext could be merged into one concept called ActionContext, and that it should be a property of the action itself
>
> @igorkorsukov: I think it is impossible to merge Ui Context and ShortcutContext , these are different things. Whether it is possible to send a shortcut depends on the current focus, and whether it is possible to send an action depends on the technical conditions. For example, when editing text, we cannot send a space shortcut to start playback, but we can send an action to play, for example by clicking a button or remote control by means of a midi controller.

I understand that there are two different requirements here:

1. The **Playback action** can be triggered on the NotationView at any time when a score is loaded.
2. The **Spacebar** is available for use as a **shortcut key** whenever it is not needed for text editing.

But these can be linked as follows:

1. The **Playback action** belongs to which UI Context? Answer: `UiContext::NotationOpened`.
2. Is the **Spacebar key** available in `UiContext::NotationOpened`? Answer: Yes.
    - It doesn't matter that spacebar is sometimes needed for text editing (that is handled by [`TextBase::isEditAllowed()`](https://github.com/musescore/MuseScore/blob/master/src/engraving/libmscore/textedit.cpp#L246-L275), which [blocks the shortcut](https://github.com/musescore/MuseScore/blob/b32a4b2623a28b36398781383a7fac7e8aa8a77a/src/notation/view/notationviewinputcontroller.cpp#L786) before any associated action can be triggered). All that matters is the shortcut is available at least some of the time in this context.

Both requirements can be satisfied, so the Assign Shortcuts dialog should allow Spacebar to be assigned as the shortcut for the Playback action.

Now consider a hypothetical action called "Repeat last word". Users can assign shortcuts to whichever actions they like via Preferences, so let's imagine the user wants to use Spacebar as the shortcut for this new action instead of using it for Playback. The new requirements are:

1. The **Repeat last word action** can be triggered during text editing in the notation view.
2. The **Spacebar** is available for use as a **shortcut key** whenever it is not needed for text editing.

Requirement (2) hasn't changed even though we are talking about a different action, so Shortcuts.xml is probably not the right place to store information about shortcut context. Instead, we should get the shortcut context from the UI Context like this:

1. The **Repeat last word action** belongs to which UI Context? Answer: `UiContext::EditingText`.
2. Is the **Spacebar key** available in `UiContext::EditingText`? Answer: No.
    - You can think of `UiContext::EditingText` as being a subcontext of `UiContext::NotationOpened` where spacebar is never available, so here the answer is "no".

In this case the requirements are contradictory, so the Assign Shortcut dialog should prevent the user from being able to assign Spacebar as the shortcut for the "Repeat last word" action even though it is allowed for the "Playback" action.

How can we know which keyboard keys are available to be used as shortcuts for a given action? It could be done like this:

```c++
bool isShortcutAvailable(UiContext ctx, Shortcut sc) {
    switch (ctx) {
    case UiContext::NotationOpened: return true;
    case UiContext::EditingText:    return !TextBass::isEditingAllowed(sc);
    }
    return false;
}
```

**Comment by wizofaus** [comment]
I always liked the way it was done in MFC, where the framework automatically asked the most focused window (or associated controller or viewmodel) first whether it could handle an action, then if that failed, would go to the parent, etc. etc.
Shortcut->Action mapping is context independent, and if it really was the case that, e.g. Ctrl+Alt+A should map to ActionX in one context and ActionY in a different context, then it's just two shortcut mappings, and when you press Ctrl+Alt+A, first the most focused window is asked if it can perform ActionX, if not, then if can handle ActionY, then if not, move up to the parent etc.
The only slight challenge there is preventing the user from assigning Ctrl+Alt+A to two actions that are both possible in the same context, basically it requires every action definition having some sort of tag to identity which viewmodel or controller handles it. The shortcuts dialog would know about this, such as if you associate Ctrl+Alt+A with an action from a context called, e.g. "Notation", then you can't also associate it with another action from the same context.

But I'd say it's too late for change for 4.0...

**Comment by shoogle** [comment]
@wizofaus, the present issue will need to be fixed in a relatively straightforward way in 4.0, but there is scope for doing something more ambitious in 4.x which is where the bulk of @VanSHOE's work is targeted for inclusion.

**Comment by igorkorsukov** [comment]
> I don't understand why ShortcutContext is saved in Shortcuts.xml. I also don't think it is fully separate to UI Context.

For example
```
    <key>pitch-up</key> <- action
    <seq>Up</seq>         <- shortcut

    <key>string-above</key> <- action
    <seq>Up</seq>                <- shortcut
```

Suppose we have a notation open and it is in focus. We press the Up key, what action should we send? Both of them?

**Comment by wizofaus** [comment]
I would think so yes, then ensure that only one controller handles the action.
But at any rate, unless the ShortcutContext is something the user can *choose* for a particular short-cut, it doesn't make sense to keep it in an external (per-user) file surely?

**Comment by igorkorsukov** [comment]
> I would think so yes, then ensure that only one controller handles the action.

**Comment by igorkorsukov** [comment]
> I would think so yes, then ensure that only one controller handles the action.

In general, we cannot guarantee this, in general, both actions can be performed. But what exactly should be done depends on the context in which the shortcut is sent.

The shortcut context is similar to the sections in the shortcuts dialog  in QtCreator (I would like to see something similar in the MuseScore )
![image](https://user-images.githubusercontent.com/3818029/176778206-53be4437-f106-485c-922c-31c82403bbcc.png)

**Comment by wizofaus** [comment]
Which doesn't look like it would need storing the "context" in a user file? The dialog should be able to work even if shortcuts.xml is deleted surely...

**Comment by igorkorsukov** [comment]
We have a build-in file shortcuts.xml , which is part of the program data, it is not user-defined. This file is a place to describe the shortcuts - what kind of shortcuts we have, their contexts, their default value. We can somehow describe this information in a different way, but at the moment it is described in this xml file. This is not user data, it is program data, as well as a number of others.

The user can override this data, at which point a user's shortcuts.xml  file appears. We can store the user's  file in some other format, but probably for simplicity at the moment it is just a copy of the built-in. At the same time, when loading files, there is a merge of the built-in and user  to be able to add new shortcuts in new versions.

**Comment by wizofaus** [comment]
That possibly explains some of the confusion then (though I can't say it's the way I would have designed it).
Personally I'm a big fan of any factory-defaults like that being in a format that's type-checked at compile time.

**Comment by igorkorsukov** [comment]
> I'm still not totally convinced that shortcut context and UI context couldn't be combined somehow

UI Context determines whether an action can be performed (there are other conditions as well, but this is one of the main ones). 
In this case, the action can be sent in different ways: 
1. Shortcut 
2. UI Control (for example, a button) in the interface    
3. Midi remote     
4. Some more remote control         
5. Programmatically according to some conditions 

The shortcut context determines which of several actions should be sent at the moment for which the same keyboard shortcuts are assigned (at the same time, it is important, maybe other actions can also be performed in general cases)

I believe that adding a shortcut context in cpp to the description of the action is a not bad idea (instead of the previously proposed categories, which are essentially the same, just not a fully formed idea).
The only confusing thing is that in this case, the description of the information about the shortcuts will be in different places, the context in one place, the default value of the shortcut in another place.

**Comment by shoogle** [comment]
@igorkorsukov, I think I understand this now:

1. Actions with the same shortcut context cannot share the same key combination (otherwise it is a conflict).
2. You put shortcut context in the XML files to make it easy for people editing those files to see conflicting key combinations.
3. Your plan was eventually to use the shortcut contexts to form action categories in the Preferences with the rule that actions in the same category cannot share a shortcut key.

That's certainly a valid way to implement it, but I think there are advantages to doing things a bit differently.

Regarding (2), it's a choice between the safety of defining shortcut context in the C++ vs. the convenience of having it visible in the XML. I think safety is more important here. People can check for conflicts by trying to assign shortcuts in Preferences before they edit the XML.

Regarding (3), I very much like this idea! I think @bkunda has already defined some categories along the lines of "Navigation" and "Add symbol", which may not line up exactly with the shortcut contexts. Maybe we can massage them a bit to make it work using subcategories, or we could group by shortcut context and then filter by Bradley's categories.

Regarding (1), I think what you call "shortcut context" is useful for more than just managing key conflicts. Consider the example you gave [earlier](https://github.com/musescore/MuseScore/issues/11060#issuecomment-1171660993). I've added context to the actions:

```yaml
Action: pitch-up
Context: note_or_range_of_notes_selected

Action: string-above
Context: note_input_in_tab_staff
```

The actions are only valid in these contexts regardless of how they are sent or which keys are assigned to them. It doesn't matter whether the `pitch-up` action is sent by a keyboard shortcut, MIDI remote, or programmatically: it will only work when there are notes selected in the score. Similarly, `string-above` only works in note input mode on a tab staff regardless of how the action is sent.

For this reason, I see "shortcut context" as being a property of the action rather than the shortcut. I also see shortcut context and action context as being very much related, although I appreciate there may be some edge cases that prevent us from making them truly equivalent.

**Comment by igorkorsukov** [comment]
> The actions are only valid in these contexts regardless of how they are sent or which keys are assigned to them. It doesn't matter whether the pitch-up action is sent by a keyboard shortcut, MIDI remote, or programmatically: it will only work when there are notes selected in the score. Similarly, string-above only works in note input mode on a tab staff regardless of how the action is sent.

This is not quite true, in the tab staff, we can do both `pitch-up` and `string-above` for selected note, why not?

**Comment by shoogle** [comment]
> in a tab staff, we can do both pitch-up and string-above for selected note

You have identified a case where both contexts are true:

- `note_input_in_tab_staff = true`
- `note_or_range_of_notes_selected = true`

Now we have to decide which one to send when the user presses the Up key. Your solution in the code was to narrow one of the contexts so they can't both be true:

- `note_input_in_tab_staff = true`
- `note_or_range_of_notes_selected_not_tab_staff = false` (false because the note is selected in a tab staff)

But what happens if the user changes the shortcut for `string-above` to Ctrl+Up? Now it no longer collides with the Up shortcut for `pitch-up`, but the restricted context prevents this shortcut being used in a situation where it is valid.

I would solve this by defining a priority for the contexts like this:

```c++
enum Context {
    ApplicationRunning, // most general context (lowest shortcut priority)
    ApplicationFocus,
    NotationView,
    NotationLoaded,
    ElementSelected,
    NoteOrRangeOfNotesSelected,
    NoteInput,
    NoteInputInTabStaff,
    EditingText,
    EditingLyrics, // most specific context (highest shortcut priority)
}
```

Since the `note_or_range_of_notes_selected` context appears later in the enum, it's shortcuts take higher priority over `note_or_range_of_notes_selected`, so we trigger `string-above` rather than `pitch-up`.

> shortcuts work only on the panel that is currently in focus [...] We can increase the volume at any time. But we can send the action increase_general_volume by Up shortcut only in a specific context

We should be able to send an increase_general_volume shortcut regardless of whether the Mixer has focus.

> Action: increase_general_volume (suppose)
> Shortcut: Up
> Context: ?

The context could be `ApplicationFocus` or something like that, and it would work according to the priorities outlined above.
This would enable users to define a keyboard shortcut for increase_general_volume that works even when the score has focus.

**Comment by wizofaus** [comment]
See NotationActionController::canReceiveAction though,  there are as lot of more sophisticated cases that determine whether particular actions are possible.  It's not really feasible to have an enumerated/ ordered list of every possible such state. I don't think it's unreasonable to restrict allowing the user to assign the same shortcut key to two actions in the same broader context (e.g. notation window focused) even if some of the factory defaults are like that for historical reasons or because they make use of "insider" knowledge to guarantee one shortcut can never trigger two actions.

**Comment by shoogle** [comment]
> It's not really feasible to have an enumerated/ ordered list of every possible such state.

The list doesn't have to be exhaustive. It just needs to cover the cases where we already know that we want to use overlapping keyboard shortcuts, which presumably means roughly one enum value for each of the existing shortcut contexts. If a new case arises then we would add another value to the enum later on.

The enum mainly exists to prevent obvious conflicts at the time you _assign_ shortcuts. When it comes to actually _using_ the shortcut, you don't need to rely solely on the enum to decide which action to call. The enum tells you to try `string-above` before you try `pitch-up`, but if an advanced function like `canReceiveAction()` tells you that `string-above` isn't available for some reason then you can move on to trying the next action that uses the same shortcut.

> I don't think it's unreasonable to restrict allowing the user to assign the same shortcut key to two actions in the same broader context (e.g. notation window focused)

NotationWindowFocused is the broad context for about 99% of our shortcuts 😉. I don't think we need to restrict users in this way when the current implementation is so close to getting it right already. I think we can avoid making assumptions like `play-next-chord` must always use the same shortcut as `move-text-cursor-right`, and so on.

> even if some of the factory defaults are like that for historical reasons or because they make use of "insider" knowledge to guarantee one shortcut can never trigger two actions

If we ship with Up as the default shortcut for both `string-above` and `pitch-up` then we at least need to allow users to get back to that state without having to reset all their custom shortcuts or edit an XML file.

**Comment by shoogle** [comment]
Come to think of it, we could just allow users to assign conflicting shortcuts everywhere and simply show a warning rather than an error 😆. We could highlight the potentially conflicting ones in red in the UI, but still allow them to be set up that way. When there is a conflict, the action that is defined first in the C++ action list wins. So we determine priority by making sure that `string-above` is higher than `pitch-up` in the action list. Now, it's just a pity that all the actions are listed in separate C++ files...

Anyway, on a more serious note, I think the enum priority order might have cracked it, but if not then I'm happy to stick with the current implementation of shortcut contexts and just move them from the XML to the C++. @igorkorsukov's implementation already handles the vast majority of use-cases perfectly adequately.

**Comment by wizofaus** [comment]
> 
> If we ship with Up as the default shortcut for both `string-above` and `pitch-up` then we at least need to allow users to get back to that state without having to reset all their custom shortcuts or edit an XML file.

Agreed, you should definitely be able to reset individual short-cuts back to what the dialog would otherwise consider conflicts.  I don't think that's so hard to achieve.

**Comment by shoogle** [comment]
Actually, it turns out that context priorities are already [defined](https://github.com/musescore/MuseScore/blob/c83d6630a2fe670ded88db6906d258b0b1734995/src/context/shortcutcontext.h#L42-L53) and [used](https://github.com/musescore/MuseScore/blob/c83d6630a2fe670ded88db6906d258b0b1734995/src/framework/shortcuts/internal/shortcutscontroller.cpp#L57-L83)! ❤️ So literally the only change needed is that `pitch-up` should have `CTX_NOTATION_FOCUSED` rather than `CTX_NOTATION_STAFF_NOT_TAB`. That allows `pitch-up` to be called from tab staves as long as it has a different shortcut to `string-above` (if the shortcuts are the same then `string-above` has priority).
