### ISSUE TITLE
[MU4 Issue] Navigation with arrows doesn't start after switching focus to score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11168]
**To Reproduce**
1. Open a score
2. Start navigation with Tab and go to score - **nothing becomes selected and left/right arrows can't start the navigation**

(but playback with space and entering notes from keyboards work fine)

https://user-images.githubusercontent.com/90187801/162999892-8dec5066-b714-4da7-9071-b51d7a0248bc.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
This is critical issue for accessibility

**Comment by MarcSabatella** [comment]
It’s related to the question of whether something is selected or not - that’s probably why it doesn’t work, because left/right never work with no selection.  But they should, regardless of how you get to the no selection state.  They should use the same code we use for Alt+Left/Right to reestablish a selection

**Comment by llui85** [comment]
Pressing `Alt` (enabling menu mnemonics) also gets the score in and out of this state.

**Comment by DmitryArefiev** [comment]
FIxed in #11208
