### ISSUE TITLE
Accessibility - Export dialog does not take the keyboard focus.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11195]
**Describe the bug**
See image: when going to file > export, the keyboard focus remains on the main application. This is particularly bad because it is the only place where a user can export Braille (apart from any score output). Hence, it's a P0.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/21022311/163377728-744a7471-37af-47e3-9aca-4376c9e7e94c.png">

Tested on Mac OS only.

**Comment by VanSHOE** [comment]
If this helps anyone:
https://user-images.githubusercontent.com/75690289/163384198-4f19d201-fe92-457a-9372-4637ae889824.mp4
Issue not there on Windows as far as I can understand

**Comment by Tantacrul** [comment]
Ah, I've discovered some nuance. Updated here with explanation:

https://user-images.githubusercontent.com/21022311/163386360-b43dba9c-89cd-4e12-a878-3eb0855f7942.mov

**Comment by shoogle** [comment]
I've noticed this occurs occasionally with the New Score Wizard too. It usually happens after switching focus to another app (or changing virtual desktop in fullscreen mode) and then switching focus back to MuseScore again: focus will go to MuseScore's main window rather than the dialog.

Pressing the Tab key a few times is usually enough to get focus back to the dialog, but this shouldn't be necessary. If a modal dialog like Export or the NSW is visible then it shouldn't be possible to focus the main window at all.

**Comment by DmitryArefiev** [comment]
Fixed in #11233
