### ISSUE TITLE
New playhead cursor should be thinner

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11221]
**Describe the bug**
(Edited)

Currently our playhead looks like this. It appears to be centred to the beat, which is fine.
<img width="634" alt="image" src="https://user-images.githubusercontent.com/21022311/163711366-7abfcc57-04ca-4d0f-adea-8227a0e5d757.png">

I propose we simply make is quite a bit narrower. I think we should try 4px wide (when at 100% zoom) to begin with and then we can quickly test to get a feel for it.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/21022311/176196785-cd2127f5-fa50-4bcb-a08b-2d4e414003cd.png">

**Comment by cbjeukendrup** [comment]
I wonder what is the purpose of the cursor being so wide. Many other apps have just a small solid line, which is very clear and never obstructive in my experience. 
For such a line, I think I would prefer it to move smoothly. (Dorico's cursor is such a line as I'm thinking of, and it moves in small jumps, which is not very pleasant to look at.)

**Comment by Tantacrul** [comment]
Basically, if it is smooth, it doesn't make sense for the play head to be wide. However, if it jumps between beats, it makes sense.

I think the beat jumping makes more musical sense. The smooth animation is form over function, IMO

**Comment by Tantacrul** [comment]
I think we can improve the animation for sure... but unless someone takes it on as a task after we've fixed the major bugs, I think our safest bet is to stick to what worked before and change later, when we have more time.

**Comment by shoogle** [comment]
I actually prefer the smooth cursor motion. It took a bit of getting used to, but now I find it much easier to follow than the instantaneous jumps of MU3's playback cursor, which I actually find to be quite distracting. It's really a matter of personal taste though, so it might be a good idea to provide both options.

I find MU3's "jumpy" cursor is particularly bad in scores that contain a mixture of long notes and short notes (i.e. most scores) because then the motion is very erratic. If you combine that with tempo changes then it becomes very difficult to know when longer notes are going to end, because MU3's cursor gives no warning before it immediately jumps to the next note. MU4's cursor moves all the way through the note so you can tell exactly when it will end. Well, maybe not exactly because the cursor is a rectangle, not a line, but you get the idea.

> For such a line, I think I would prefer it to move smoothly. (Dorico's cursor is such a line as I'm thinking of, and it moves in small jumps, which is not very pleasant to look at.)

This might be done to reduce [ghosting / motion blur](https://upload.wikimedia.org/wikipedia/commons/5/5e/Onion_skin.png) (i.e. visible cursor trails) which can be a problem on LCD monitors and would also be unpleasant to look at. Ghosting will be less noticeable if the line is wider or if it jumps instantaneously rather than in a smooth motion.

As was mentioned on Discord, one thing that's arguably better about MU3's cursor is that it colours the active notes in each voice, whereas notes in MU4 are just black. If the highlight was restored in MU4 then it would help with knowing exactly when each note starts and ends.
![image](https://user-images.githubusercontent.com/11011881/163734607-75f37a59-0497-4184-9d2f-6fa9cfd5d740.png)

**Comment by Tantacrul** [comment]
I think the note highlight needs to be raised as a separate bug. It was a lovely touch in 3 that seems to have been overlooked. @shoogle was that you nominating yourself to raise it? :D

**Comment by anonymous7002** [comment]
What do you think about adding an option to change between the two playheads?

**Comment by Tantacrul** [comment]
Step one is to revert back to the original. Step 2 is to create a better looking version of the smooth playback scroll. Problem with these kinds of options is that only a tiny % of people will ever know there's an alternative to the default. It's not quite the solution many people think it is.

**Comment by Tantacrul** [comment]
@HemantAntony - I've just seriously simplified this task. I don't suppose you'd possibly be willing to take it on? Assuming it is basically a single value change!

**Comment by HemantAntony** [comment]
@Tantacrul this is the PR: #12209
