### ISSUE TITLE
[MU4 Task] Add playback and appearance settings for accelerando and ritardando lines in Properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11251]
**Task description**
This is a task to implement some basic settings that affect the playback and visual appearance of newly-added accelerando and ritardando lines. 

These settings will be contained in the **Properties** panel.

See this Figma document for the complete design spec: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=23492%3A586050

@Tantacrul can provide further context if required. 

Worth singling-out is that we would really like to be able to interpret playback instructions for accel. and rit. lines from imported MusicXML files, using the settings and parameters specified in this design document. 

Many thanks!

**Comment by Tantacrul** [comment]
Since @bkunda is on vacation starting tomorrow - I'll happily answer any questions about this.

Please note that this is a vital design to include. Without it, the rit. and accel. lines will not be functional because they do not allow the user to specify _**how**_ the speed up or slow down.

I want to also mention the importance of making sure that MusicXML import of rit. accel. is understood so that we use these lines with the appropriate %s. This was the most urgent request of the MuseClass team who would greatly benefit from it. (Currently, they have to set invisible tempo markings for each score they create, which is killing them!)

**Comment by Tantacrul** [comment]
Also @MarcSabatella mentioned that the status line for the tempo lines is currently:

**"Tempo changed ranged"** (including the type). Marc, what would you suggest instead?

**Comment by MarcSabatella** [comment]
Something like “gradual tempo change”, or “tempo change (gradual)”, maybe.  Or another synonym for “gradual”, line “incremental”.  The word “range” (without the “d”) is accurate but not as self-explanatory.

Presumably what we call it here is also what we call it in the Properties window.

**Comment by Jojo-Schmitz** [comment]
"accelerando/ritardando"?

**Comment by Jojo-Schmitz** [comment]
Actually the Figma has it as "Accelerando & Ritardando"
