### ISSUE TITLE
[MU4 Issue] Text styles menu: font-sizes not displaying correctly when style name is clicked

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11262]
**Describe the bug**
The font-sizes are not displaying correctly in the text styles submenu.

**To Reproduce**

1. Go to Format > Styles > Text Style, then click on "Title".
2. Now scroll down and click on "Text-line.

RESULT: The 20px "Size" from "Title" persists when you click on "Text Line". 

_Note_: Try clicking on various styles to see how the "font-size" behaves. There is a problem but it's not immediately obvious what the common factor is.

**Expected behavior**
When you click on any text style in the list the font-size displayed should be WYSIWYG.

**Platform information**
 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7. / Laptop screen: 15 in.

**Comment by Tantacrul** [comment]
I'm unable to reproduce this. I also can't see a style called 'text line'. Perhaps I misunderstood you issue?

Could you test again and confirm this is still happening? There have been some fixes to text styles and sizes lately that may have fixed this.

Also, can you provide some screenshots if the issue is persisting? Just to make sure we don't have to come back to ask for more clarifications. 

Thanks very much!

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2248878809, revision: github-musescore-musescore-bb06849

Yes, looks to be fixed in the latest dev. duild.

**Comment by Tantacrul** [comment]
Sweet! Thanks!
