### ISSUE TITLE
Mixer ordering needs to match the score ordering.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11320]
**Describe the bug**
At the moment, when adding a new instrument to your score, it will always be positioned to the right-most position in the mixer.

Example, if adding a second flute, it will appear near the top of your score but at the right-end of the mixer. Worse, if you add an instrument change, the new track it creates **also** gets added to the end of the mixer. This makes it really hard to find where the track is for any newly added instrument (or instrument change).

**Desired Behaviour**
1. The vertical position on the score should be matched from left to right in the mixer.
2. When adding an instrument change, the newly created track should be placed to the right of the original instrument. So if I have a Flute on the score and I then create an **instrument change** to Piccolo - in the Mixer, the Piccolo track will sit next to the Flute track, on the right side. If I then add another instrument change (this time, a bass flute) to the same staff, the newly created 'Bass flute' track will sit to the right of the Piccolo track. etc.

**Comment by cbjeukendrup** [comment]
It seems all problems mentioned here have been fixed by #12009.

However, one closely related problem is left: when you reorder parts in the Instruments panel, the mixer order is not updated. I tried to create a solution, but if you move a part up and down very quickly, so that the Mixer has to reset the order very often, a crash occurs inside Qt. Not sure how/whether we can circumvent that, so I don't really know what to do.

**Comment by Tantacrul** [comment]
I think we can live with that for 4.0.

I think the way we'd fix that is to alter how the instruments panel works: rather than it constantly updating _**as you drag**_, it should only update when you _**release**_. That way it wouldn't really be possible to drag things quickly. I think I'll close this issue in the meantime.
