### ISSUE TITLE
[MU4 Issue] Parts - Parts window Open/Close buttons

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11359]
**Describe the bug**
Parts windows buttons are somewhat confusing as Open button Opens part and Close button closes window.

As both buttons have similar design, are placed next to each other, and have exact opposite action descriptions, it would be expected that should should have exact opposite behaviors.

**To Reproduce**
1. Click on "Parts" Icon in top navigation
2. Click on "Open" button to open part (Parts window automatically closes)
3. Click on "Parts" Icon in top navigation
4. Click on "Close" button to close Parts window

**Expected behavior**
It is expected that Open should be an action applied to individual part and should have some form of action/icon connected with the individual part instead of the window.

**Screenshots**
<img width="762" alt="Screen Shot 2022-04-25 at 6 19 06 PM" src="https://user-images.githubusercontent.com/30370609/165120104-952e7f26-5a4f-4853-9cf5-b9cd748a1f4c.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by MarcSabatella** [comment]
There was some discussion of this on Discord a couple of weeks ago.  What I had proposed, and still think is a good idea, is to actually remove the need to open this dialog at all for most people.

Right now, it's both less obvious *and* more work than the infamous "New All" button - not obvious you need to actually select parts to open before opening, more work to do the selection since selecting all requires several clicks.  For the usual case 99% of users will face - wanting all parts opened - MU3 requires three actions: one to open the dialog, one to press "New All" or "All Parts" or whatever it is called in any given release, and one to press OK.  MU4 requires more like five or six actions - one to open the dialog, one to select the first part, one or more to scroll down to the bottom of the list, one to Shift+click the last part, and then finally one to press "Open".  But what if it could be only *one* action required??

I propose making the Parts button work like the note input button, with a main action that does what you want 99% of the time but also a dropdown menu for the niche cases.  Clicking the button simply would simply open all parts, no questions asked.  Clicking the dropdown button would give you a menu with an option to open the dialog, for those niche cases where people actually need to fiddle with parts individually.  But also, direct options to "open all" and "close all", in case you've previously closed some part tabs.

Aside from that, yes, absolutely, there was consensus in the previous discussion that the buttons are not well named.  My proposal then was that they should be called "Cancel" and "Open selected parts", since that's what they do, at least currently.  That is, hitting the "Close" button does more than just exit the dialog, it actually discards all changes.  For the "Open" button, I think the word "selected" is important here because otherwise it is not at all obvious you need to select anything or that selecting multiple parts is possible (especially since Ctrl+A is not functioning).  Although that might be less crucial if the no-dialog-needed-at-all-99%-of-the-time solution I am advocating were implemented.

**Comment by Tantacrul** [comment]
Don't agree that people will want all their parts open at once. Once you get to 10+ part scores, that becomes very annoying and noisy. The only reason we did it with V3 was because there was no other choice.

Also don't think that the action of clicking on a part, holding shift and selecting the range you want and pressing 'open' is particularly hard - and I think it is laughable to suggest that the MS3 system is even a 10th as intuitive.

**Comment by MarcSabatella** [comment]
I am not saying we should generate the parts right away or automatically - that would be a mistake for performance reasons indeed.  I just want it to be a single-click to get there instead of needing to wade through dialogs with multiple clicks of confusingly-labeled controls required just to perform a basic function of notation software.

As it is, the fact that the process is more convoluted and hard to discover than necessary is part of why more people don't do so themselves before uploading to musescore.com.  In other words, the fact that they don't do so already isn't evidence people don't want parts - it's evidence we should make it easier to create them.

And I definitely maintain that the vast majority of people who want parts at all, usually want them all, even if it's more than ten.  Either you are trying to have your piece performed by human musicians (or published for that purpose) or you are not.  If you are, you need all parts eventually., so why not make that task simpler?  Sure, sometimes it can be valuable to open just a few at a time if that suits your own personal workflow, and hence the dialog could be useful.  I'm not proposing eliminating it.  Just recognizing it's a niche usage compared to the common use case of just wanting all parts, and wanting the UI to reflect this.  Same rationale for why other niche commands have been hidden away a bit and more common ones exposed better.

FWIW, though, the nice little X's we now have on the part tabs are a huge win as well, and to me, those combined with the two menu options I proposed would virtually eliminate the need for the dialog.

**Comment by MarcSabatella** [comment]
But to be clear: I am not saying MU3 was intuitive.  It wasn't.  I am asking us to recognize that MU4 isn't an improvement.  If it's hard for a user to intuit they need to click a button labeled "All Parts" followed by a button labeled "OK", it's not easier to intuit they need to click the first part, scroll to the bottom of the list, and Shift+click the last part, then click a button labeled "Open".  But aside from intuitiveness for newbies, I'm also concerned with *efficiency* for regular users, and that/s what I was focused on in the comparison.  Two clicks still beats five for regular users, even if neither is intuitive to new users.

So yes, make it more intuitive, but *also* don't make less efficient.  I still say, my proposal accomplish both goals and shouldn't be dimissed.

**Comment by Tantacrul** [comment]
Well, we all agree the current dialog needs work and I suspect the fixes will be easy, once @bkunda gets his mitts on it 😀

**Comment by MarcSabatella** [comment]
Another suggestion would be to have three buttons: "Cancel", "Open selected parts" (and perhaps leave dialog open?), and "Open all parts" (and definitely close dialog).  That would improve both intuitiveness and efficiency over both MU3 and what we have now in MU4, without requiring anything as radical as what I suggested above.

I actually think this was the first version of my idea, then I thought, maybe we could eliminate the need for the dialog at all since now it's only basically just a confirmation. But, it does make the other cases a little more awkward (actually a lot more, that little arrow next to the note input icon is next to impossible for me to click for some reason).  So maybe the "Open all parts" or whatever @bkunda comes up with would be better.

**Comment by mccoydtromb** [comment]
The Note Input button is left click to toggle, right click to show options (I also tried left clicking the arrow in the corner for a little while! Probably just because of using MU3). Since you have used that functionality once, it could be used again for the Parts. Although I like the proposal in #11420 to open the dialog but have different buttons. Gives the user a good place to go from when working with parts.

**Comment by DmitryArefiev** [comment]
Fixed in #11858

**Comment by wizofaus** [comment]
> (I also tried left clicking the arrow in the corner for a little while! Probably just because of using MU3).

No, because that's what that arrow "affords".  I've reported it as a bug that it doesn't do what I'd suggest most users would reasonably expect.
