### ISSUE TITLE
[Playback] Ornaments (Trills, turns, mordents, etc.) don't follow accidentals

### ISSUE THREAD

**Issue by moritzviolin** [musescore/MuseScore#11361]
**Describe the bug**
Ornaments are currently always defaulting to being a semitone, even when the key signature suggests that it should be a full tone.

**To Reproduce**
In the video below, the first trill goes from B to C (which is a semitone). However, when the key signature changes, this trill should now be playing a C sharp.

**Expected behavior**
Ornaments should follow accidentals.

**Screenshots**

https://user-images.githubusercontent.com/95185309/165122168-fe1f8c2d-04d6-4efc-80b8-0ddd0ba19e00.mp4

(sorry for the bad audio but you can clearly hear the problem)

**Platform information**
 - OS: EndeavourOS (Linux)

**Comment by Tantacrul** [comment]
I've slightly reworded this to make it clearer. I also think that we should have some inspector options to allow users to specify exactly what the trill should do.

Worth mentioning that trills in MS3 do take key signatures and accidentals.

In the example below, the second trill plays a full tone because of the C# at the beginning of the second measure.
<img width="828" alt="image" src="https://user-images.githubusercontent.com/21022311/165186650-6423909b-7056-42ea-98aa-50095d246714.png">


@bkunda - this would be another good one to create some inspector options for.

**Comment by Tantacrul** [comment]
Mordents and inverted mordents also have this problem. In this example, the first mordent should play an F sharp but plays an F natural. The inverted mordent plays an F natural instead of an E.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/21022311/167485537-a7cf18f0-7567-4b8c-a6e3-2bd83c2463aa.png">

**Comment by Tantacrul** [comment]
In fact, it's just a problem with all ornaments. None of them honour the key signature:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/21022311/167486315-59cc9b12-f6e7-4a48-a2da-8ff3dff7700d.png">
