### ISSUE TITLE
[MU4 Issue] Instruments - Edit Instrument names

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11371]
**Describe the bug**
After editing instrument names, only option is "Replace Instrument", not save changes, which opens dialogue to replace the instrument, not replace the instrument names. 

**To Reproduce**
1. Go to instruments
2. Click on instrument settings icon
3. Edit text
4. Click on "Replace Instrument" because that is the only open
5. See the challenge

**Expected behavior**
Ability to save changes to instrument names should be present. 
Replace instrument should be a separate option.

**Screenshots**
<img width="290" alt="Screen Shot 2022-04-26 at 12 51 17 AM" src="https://user-images.githubusercontent.com/30370609/165181078-e72f515f-48e4-4249-b7bb-e178736bddaf.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
I'm legit confused by this one, since the changes you make update instantly in the panel and also on the score. I think this one may require some user testing. It might just mess with people's heads. Not sure.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/21022311/165182058-8c00f241-f816-45c0-b39b-81005605df27.png">

**Comment by Tantacrul** [comment]
Closing this because I don't really think we need to change the UX here. We'll wait until we do some user testing to get an idea of a more comprehensive set of changes that we can apply to this panel.
