### ISSUE TITLE
[MU4 Issue] Project Properties - Inconsistent behavior of text changes (Сopyright only)

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11425]
**Describe the bug**
When updating text in Project Properties, behavior is inconsistent.

**To Reproduce**
1. Go to File > Project Properties
2. Edit title text 
3. Press OK
4. See nothing happen
5. Go to File > Project Properties
2. Edit copyright text 
3. Press OK
4. See nothing happen
5. Click on footer text (if no text there click on area where you think it should be)
6. Watch text change appear

**Expected behavior**
Updates to text fields in Project Properties should update the corresponding text fields in the score.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165518173-03849609-14b2-4aa8-b26d-9531686466c8.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Thanks... and thanks...

**Comment by shoogle** [comment]
> **Expected behavior**
> Updates to text fields in Project Properties should update the corresponding text fields in the score.

This is only the expected behaviour for the copyright field. The other fields (title, composer, etc.) were not linked in MuseScore 3 between the File Properties dialog and the score.

I can see why you would expect the other fields to be linked as well but it is difficult for these reasons:

1. The score allows individual text characters to be formatted (e.g. some characters in the title to be made bold or superscript while other characters are normal) but the Properties dialog does not allow this.
2. You might want the metadata to be different in Project Properties compared to the score.
    - Score composer is "W. A. Mozart" and metadata composer is "Wolfgang Amadeus Mozart".
3. The score might contain multiple title frames with different information (e.g. one for each movement), or no title frame at all.

This is why the fields were unlinked in MuseScore 3. An alternative solution would be to link them but make them read-only in the Properties dialog, so it just displays a plaintext version of whatever appears in the first frame in the score. But that wouldn't help in every situation.

**Comment by DmitryArefiev** [comment]
Fixed in #12959
