### ISSUE TITLE
[MU4 Issue] Preferences > General > Languages - Not possible to change back to English

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11432]
**Describe the bug**
If you change language from English to any other language, it is not possible to change back to English (no option is displayed).

**To Reproduce**
1. Go to Preferences > General > Languages
2. Change language from English to any other
3. Press Ok
4. Go to Preferences > General > Languages
5. Try to change language back to English
6. See error

**Expected behavior**
English should be displayed in the language list.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165524815-d18e9809-9781-4843-b9ff-49a6949b1487.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Nice spot!

**Comment by shoogle** [comment]
We're actually missing three options here:

- English (GB)
- English (US)
- System (i.e. follow the operating system's language setting)

System is the default. It should appear as the first option in the menu like in MuseScore 3.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/11011881/165935166-2f023cf8-d28b-4e89-a20e-85ae059d2419.png">

We need "System" in the menu so that you can return to it after choosing a different option.

**Comment by DmitryArefiev** [comment]
@Eism When chatted in Slack, @Tantacrul proposed to change **System** to **System default** (the same as in I/O>Audio device)

(@Tantacrul please change if I misunderstood something :) )

**Comment by Tantacrul** [comment]
All good!

**Comment by DmitryArefiev** [comment]
**System default** added in #12474
