### ISSUE TITLE
[MU4 Issue] Transposition - Concert Pitch - Horn in F key signature issue

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11436]
**Describe the bug**
Horn in F is does not show proper transposition of key signature, though instrument does transpose when toggling between Concert Pitch.

**To Reproduce**
1. Open attached score
2. Toggle Concert Pitch checkbox

**Example file**
[Fanfare_for_the_Common_Man.zip](https://github.com/musescore/MuseScore/files/8574657/Fanfare_for_the_Common_Man.zip)

**Expected behavior**
Horn in F should be in F.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165576502-ae46e131-e59e-47e3-a838-12d1db52e9dd.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by lengthwave** [comment]
Yes. This score was imported from a previous version.

**Comment by sammik** [comment]
Its probably because horns has "atonal key", which means it is always without key signature.

As far, as I know, it is common way of writing for horns.

To be sure, please upload also previous version of score.

**Comment by MarcSabatella** [comment]
Indeed, writing horns with no key signature was the traditional for centuries, and in some circles still is.  We've always supported this tradition by Ctrl+adding the open/tonal key signature, and this score appears to have used that technique.  So I don't think there is a bug here.

I do wonder, though, if we shouldn't consider a staff property to support this more directly, so you don't have to manually add this (and repeat for every key change)?  It's not the same as simply not *displaying* the key signature, which we already support.  That doesn't automatically add the necessary accidentals (nor should it).  For increased discoverability, we could also add a "Horn in F (no key signature)" to the instrument list if desired.

**Comment by lengthwave** [comment]
This issue definitely does highlight that we need to have a bit more consistency in instrument definitions and that supporting fringe use cases creates confusion.

I think we can close this issue and address this point later and in another issue to further refine/define instrument properties and behaviors.

**Comment by sammik** [comment]
To be clear. It is not horn itself, what is atonal. 
User creating this score set local key signature for each horn instruments. (And user can add it to any staff / instrument).

By default, MS works, like You would expect.

**Comment by Tantacrul** [comment]
Thanks @sammik for that clarification. I never thought of the user applying an atonal key sig.

**Comment by Jojo-Schmitz** [comment]
```
          <KeySig>
            <custom>1</custom>
            <mode>none</mode>
            </KeySig>
 ```
v.s.
```
          <KeySig>
            <accidental>-2</accidental>
            </KeySig>
 ```

**Comment by MarcSabatella** [comment]
Indeed, that was what I meant by "we've always supported this tradition by Ctrl+adding the open/tonal key signature, and this score appears to have used that technique".  But it's non-obvious that this would be the way to get that result, and as mentioned, it's also more work than it should be to do this, in that you have to reestablish it at every key change.

That's why I also proposed we *eventually* make this easier, via a checkbox in Staff/Part Properties and/or an explicit entry in the instrument list.  Because far from a fringe case, this really is the historical norm for horn writing, even if the practice it's slowly starting to fade away among modern composers.  When I've seen polling on this it's pretty much 50/50 among horn players as to whether they prefer the historic no-key-signature notation.
