### ISSUE TITLE
[MU4 Issue] - staff scaling change hides custom key signatures

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#11461]
When user changes staff scaling, custom key signature disapear.

It is regresion, something form today (29.4.) 
I checked commit [a6ab311,](https://github.com/musescore/MuseScore/commit/a6ab311e28e592e0f01bf8012446c2cd5c6280a1) that one works fine.

**To Reproduce**
1. Add Custom Key Signature
2. Change Scaling, or Line Distance (Staff / Part Properties -> Line Distance)
3. Apply
4. Custom Key Signature disappears

**Expected behavior**
Signature remains, where it was

**Platform information**
 - OS: [Linux]

**Additional context**
Regression

**Comment by cbjeukendrup** [comment]
I could only reproduce this if the custom key signature is at directly the beginning of the piece. 
It seems the problematic commit is 839b484d45e54066e919b4c43322acd8c1598a1b. And the core of the problem is that `Score::transposeKeys` (which is called by `Score::transpositionChanged`) does not seem to take custom key signatures into account. 

@sammik Would you like to attempt to fix this yourself?

**Comment by sammik** [comment]
Thanks, done.
@cbjeukendrup You were right about `Score::transposeKeys`
Bug actually comes from my transpositing commit [fbe8d57](https://github.com/sammik/MuseScore/commit/fbe8d579364c367f4c8e42b537f794f797a97ff5), I missed this.

I wonder, how did you find it out. 
And also, why scaling change affects (triggers) transposition.

**Comment by cbjeukendrup** [comment]
Hm... how I found this... well, I had just been working on the issue about changing instrument transposition when replacing instruments. While doing that, I learned about the existence of the `Score::transpositionChanged` function. So when I heard about this issue, and the fact that it was such a recent regression, I immediately feared that my commit had caused it, which turned out to be the case. Of course, I then started looking what the transpositionChanged function actually does, and then made the (slightly educated) guess that `Score::transposeKeys` would be relevant. 

And why changing the scaling affects transposition: I found out that you don't even need to change the scaling. Just opening 'Staff/part properties' and clicking OK without changing anything already causes it. That's because when clicking OK, all possible changes in the dialog are applied. There are some conditions to avoid unnecessary applications of settings, for example `if (m_instrument != m_orgInstrument)` in `EditStaff::applyPartProperties`, but apparently that one is not really working. I should maybe investigate why. 

So your 'bug' in the transposition commit revealed interesting things!

**Comment by sammik** [comment]
> That's because when clicking OK, all possible changes in the dialog are applied.

This also seems to happen also when You click "Apply", which I think is not good everytime - if I click 3 times Apply and then OK, I didnt change anything, but actually had 4 empty undos in App. 
Should it be reported as issue, or is it something intended?

**Comment by cbjeukendrup** [comment]
Yeah, let's create a new issue for it, that seems a good idea in this case. If necessary, we can have discussion about it in the new issue.

**Comment by DmitryArefiev** [comment]
Hi! @sammik @cbjeukendrup I've tested this issue in #11470 - it **looks good** (macOS, Windows, Linux)
