### ISSUE TITLE
[MU4 Issue] Staff / Tablature: no "unlinked" option in "New Score"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11468]
**Describe the bug**

In MS4, It has become more difficult for the user to create an _unlinked_ (but same instrument) Staff/Tab system; you can't do this in the "New Score" section but only on the score page (but see #11027).

_Suggestion_: Add unlinked (but same instrument) Staff/TAB for Guitar to "New Score > Create from template > Solo". (_Note_: unlinked staff/tab option allows independent editing of staff and tab for correct notation of harmonics and 8va etc. Not possible with linked staff/tab.)

**Comment by cbjeukendrup** [comment]
It sounds like using unlinked staff/tab in one instrument is rather workaround for some bugs, than something really useful. 

Therefore, we'd better fix the bugs that prevent you from properly using linked staves (which is more convenient anyway), instead of trying to support this workaround (which will doubtlessly be confusing for many users). 

As far as I know, some efforts for better harmonics notation and 8va notation are already being made, so you should see the results of that in the latest builds. It would be helpful if you could be more specific about the problems you're encountering, so that we can fix them.

**Comment by Tantacrul** [comment]
I don't 100% understand the request. To echo @cbjeukendrup - we're really pressed for time, so please submit very specific and well explained issues.
