### ISSUE TITLE
[MU4 Issue] Exported parts don't have correct PDF size

### ISSUE THREAD

**Issue by hackbar** [musescore/MuseScore#11464]
**Describe the bug**
Exported parts don't have correct PDF size.

**To Reproduce**
1. Format > Page Settings, make a custom size page. Eg 7.75" x 5.5", landscape.
2. Export a part to a PDF
3. The PDF is not 7.75"x5.5", but 8.26"x11.69. The score is in the upper left.

**Expected behavior**
The PDF size should match the page size, as it did in MS3.

**Platform information**
 - OS: linux

version: OS: Ubuntu 20.04.4 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by Tantacrul** [comment]
Can confirm. I had my page size set to A3:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/21022311/166100871-86562b21-62a7-470e-809c-15b57e542083.png">


Here's what my score looks like in the app:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/21022311/166100879-62be4a7d-9383-4689-8839-375e1f35d189.png">

Here's what the PDF export looks like:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/21022311/166100852-688f8d82-a574-4dad-9cc1-4c45f7170294.png">

Since PDF export is our primary function: this is a clear P0.

Thanks @hackbar for noticing this regression!

**Comment by HemantAntony** [comment]
@Tantacrul I'm working on this. I have a fix. I should be submitting a PR soon
