### ISSUE TITLE
[MU4 Issue] Slurs imported from MS3 shift to wrong position in MS4

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11477]
**Describe the bug**

Slurs in MS3, default or customised, shift significantly in MS4 resulting in non-optimal layout and collisions.

**To Reproduce**
1. Open the attached score. 
[slurs_bug.zip](https://github.com/musescore/MuseScore/files/8597382/slurs_bug.zip)

2. Inspect the slurs in mm 4, 6, 9, 14.
RESULT: They have shifted position resulting in non-optimal placement and collisions.

**Expected behavior**
Slurs should keep the same position more or less as in MS3. There should be no additional collisions.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2248878809, revision: github-musescore-musescore-bb06849

**Comment by Tantacrul** [comment]
@oktophonie - what do you think?

Is this known / unavoidable?

**Comment by MarcSabatella** [comment]
In general, it's impossible to retain the exact appearance of manually adjusted symbols if the default layout changes.  That's the inevtiable price of progress  it means adjustments made to work around defiencies in older versions can now end up being counterproductive and are often better off being reset.  And that's what the dialog warns about on import.

However, in this particular case, it's mostly about one specific thing that was *not* improved: slurs colliding with tuplets.  If this were addressed, then reset to default would do the right thing.  As it is, it leaves collisions that are indeed worse in some cases than the collisions that were also present in the default layout in MU3.

**Comment by oktophonie** [comment]
Marc said it all for me here. Slurs are going to move, yes, which may require manual adjustments be made again in some cases (hopefully fewer cases!)

The real issue here is slurs avoiding tuplets, which I'd dearly like to fix, but will first need to fix the default placement of tuplets (which is bad); a further complication is that it's not always clear whether the tuplet number should move out of the way of the slur or vice versa, so this is hard to automate.
