### ISSUE TITLE
[MU4 Issue] Imported GP score which contain tuplets can't be opened after saving in .mscz file 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11515]
**To Reproduce**
1. Import any of test GP scores to MU4 
[Test scores.zip](https://github.com/musescore/MuseScore/files/8621409/Test.scores.zip)
[0___triplet.gp.zip](https://github.com/musescore/MuseScore/files/8630654/0___triplet.gp.zip)

2. Without changes save it as .mscz file (just via ctrl+S)
3. Close imported score (don't close the app)
4. Via 'Open file' open saved .mscz score

**Expected behavior**
Saved score is opened as expected

**Screenshots**
![Capture 2022-05-04_05-44-44_PM](https://user-images.githubusercontent.com/101250347/166706643-d081009c-4ad6-46da-88ee-db3a2e5b8090.png)

**Additional context**
The issue was caught on .gp (version 7) of GP, but could be reproducible on other versions also

**Comment by alexpavlov96** [comment]
the bug appears only when gp score has tuplets

**Comment by alexpavlov96** [comment]
- Too many notes are added to triplet
- Triplets are rendered too far from notes
<img width="411" alt="Screenshot 2022-06-06 at 12 33 13" src="https://user-images.githubusercontent.com/24373905/172135443-f646f11a-090e-4be1-ae68-78bfbfb66ed8.png">

Also separate consecutive notes of different tuplet duration would be shown as the same tuplet duration (3, 3, 3 instead of 3, 4:3, 3)
<img width="271" alt="Screenshot 2022-06-06 at 12 35 39" src="https://user-images.githubusercontent.com/24373905/172135869-120777ef-eb08-4457-a324-d03d52bdb337.png">

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11891
Tested on macOS 12, Win 11, Ubuntu 20
