### ISSUE TITLE
[MU4 Issue] Horizontal scrollbar does not work when Mixer is undocked (Windows only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11605]
**Describe the bug**
https://github.com/musescore/MuseScore/pull/11585#issuecomment-1122195343 :

https://user-images.githubusercontent.com/90187801/167902789-dfbacc3b-10a8-47c9-bfa4-f67cb72d859f.mp4

**Platform information**
 Windows only

**Additional context**
#11585

**Comment by cbjeukendrup** [comment]
This issue seems to be even worse. It is not limited to the scrollbar in the mixer, but happens with a quite big area of _all_ dockable panels (even palettes and toolbars, etc.).

https://user-images.githubusercontent.com/48658420/167908673-d21d278b-9ca0-4b4f-b35c-39e4da8d72bd.mov

I feel like this came up before (even before PR #11585), and I even thought somebody had a fix, but I can't find it.

**Comment by DmitryArefiev** [comment]
> This issue seems to be even worse. It is not limited to the scrollbar in the mixer, but happens with a quite big area of _all_ dockable panels (even palettes and toolbars, etc.).
> Schermopname.2022-05-11.om.19.16.06.mov
> 
> I feel like this came up before (even before PR #11585), and I even thought somebody had a fix, but I can't find it.

@cbjeukendrup Oh I see.. Also I found you can use mouse scroll wheel (instead of scrollbar dragging with mouse) with **Palettes**, **Piano** etc. But **scroll wheel doesn't work with Mixer scrollbar**, because it works with mixer faders. 

What about to **add ability to use Shift+Mouse scroll with Mixer scrollbar**? The same how it works with score - Mouse scroll to vertical scrolling and Shift+Mouse scroll for horizontal scrolling. I can create a separate ticket for that.

**Comment by cbjeukendrup** [comment]
@DmitryArefiev It turns out that QML's scrollview already supports horizontal scrolling when pressing shift (at least on mouses that are unable to scroll horizontally by themselves). That's good news, so your idea already works as long as the mouse pointer is not on a volume or pan control.

But when it is, the control takes priority over the scrollview (#11128). Unfortunately, we don't have many options:
- disable scroll interaction with controls altogether;
- as a compromis, disable it only when pressing Shift. This has two problems:
    - if the user is not pressing shift because they way to scroll vertically, the controls will still take over
    - if the user has a mouse or trackpad that supports horizontal scrolling, the user won't be pressing shift (because no need) so the controls will still take over.
- disable scroll interaction with controls by default, and only let controls respond when the user is also pressing some key, like Ctrl/Cmd. This has the problem that users are not likely to discover that they can use that Ctrl/Cmd key.

The optimal solution would be to replicate macOS's native behaviour for nested scrollable components:
- If the user has started scrolling while the mouse was _not_ on any control (i.e. the initial scroll event was sent to the scrollview), then the whole scroll gesture will be handled by the scrollview from start to end, and the controls won't take over.
- if the user started scrolling while the mouse was on a control, that control will receive the scroll gesture. 

But in Qt/QML, we can't do this, since it treats every step/pixel\* you scroll as a separate event, and it has no way to see that multiple events form one gesture together. So it can't see that you started scrolling while pointing at the scrollview. If you have scrolled so many pixels that the mouse is now pointing to a control, the next events will be sent to whatever the mouse is _currently_ pointing to, instead of to the thing it was pointing to when starting the scroll gesture. 

\* (Not really pixels, the reality is even more complicated, but let's not delve further here.)

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Thanks for such detailed explanation!

> It turns out that QML's scrollview already supports horizontal scrolling when pressing shift (at least on mouses that are unable to scroll horizontally by themselves). That's good news, so your idea already works as long as the mouse pointer is not on a volume or pan control.

I see now..  But it works on Mac, and **doesn't work** on **Windows** and **Linux** (Shift+Mouse scroll) :

https://user-images.githubusercontent.com/90187801/168282892-6061cb23-5364-4a7f-b3e3-47080d45dc64.mp4

(but touchpad works on Windows  to scroll Mixed horizontally)

**Comment by DmitryArefiev** [comment]
> I see now.. But it works on Mac, and doesn't work on Windows and Linux (Shift+Mouse scroll) :

Logged that separately #11625 (to leave the current issue for scrollbar mouse dragging)

**Comment by DmitryArefiev** [comment]
Fixed in #12919

**Comment by shoogle** [comment]
> The optimal solution would be to replicate macOS's native behaviour [...] But in Qt/QML, we can't do this, since it treats every step/pixel* you scroll as a separate event, and it has no way to see that multiple events form one gesture together.

When we receive a scroll event on a scroll view, could we temporarily disable scrolling on controls (e.g. for 200 milliseconds)? If we receive another scroll event before the timer runs out then we scroll on the view and extend the timer by another 200 ms. When the timer runs out, we re-enable scrolling on controls, and any subsequent scroll events go to the control.
