### ISSUE TITLE
[MU4 Issue] Regression: tempo override control missing (formerly in Play Panel)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11617]
Previous versions of MuseScore had a slider to override the tempo of a piece, allowing you to play it back faster or slow than the marked tempo. This was used very extensively by people wanting to practice along with the playback, or by people wanting to listen more closely to each chord of the playback to be sure there are not wrong notes etc.  You could even turn it down to a ridiculous low and then use the arrow keys during playback to achieve a "scrubbing" effect.

Merely changing the initial tempo marking is not the same thing at all, since that won't affect any subsequent tempo changes.  The tempo slider worked across the entire piece.

![image](https://user-images.githubusercontent.com/21022311/173245162-9273388f-a960-4999-9723-92630a5c1d7a.png)

**Comment by Tantacrul** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/21022311/168119327-a189be8b-520f-4019-af79-4f82f3b23913.png">

**Comment by MarcSabatella** [comment]
Hmm, I see the slider when I do that, but as far as I can tell it doesn't affect tempo at all - just the current play position.  A play position slider is kind of sort of sometimes useful, but the tempo slider is indispensible.

The loop markers I had already noticed via the gear icon.

**Comment by cbjeukendrup** [comment]
@Tantacrul Marc means this slider:
<img width="375" alt="Schermafbeelding 2022-05-12 om 20 26 39" src="https://user-images.githubusercontent.com/48658420/168143814-5da7207a-aac7-4a21-9424-708164e75aff.png">

I agree that is quite useful to have, especially when composing. At least for the time that we don't have real scrubbing playback like Finale. Since we are already _displaying_ the tempo in the toolbar, we could somehow make that component interactive so that it brings up a popup with controls to override the tempo.

**Comment by MarcSabatella** [comment]
FWIW, no particular reason the slider itself need be present.  A spin box with the percentage would actually be completely sufficient, I think.  It could display right next to the existing tempo display.

**Comment by Tantacrul** [comment]
I have put together this suggested solution. It's handy that this panel gets bigger when undocked. Makes it quite easy to expand. I'm not sure if we can get this in for 4.0 but I'll keep the issue open for now. If a community member would like to take it on, they're welcome to try although since our playback system is completely new, it will almost certainly not be a case of porting over the MS3 functionality.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/21022311/168442737-d5ab939d-ba6f-4b42-ad10-7381ce666838.png">

**Comment by Tantacrul** [comment]
Incidentally, this oversight is mine. I just missed it completely.

**Comment by Obliquely** [comment]
This addresses: https://musescore.org/en/node/331538 - Good to see this is in scope. Useful for composition but also for people who use MuseScore for practice and want to play along at slower to written tempo. Suggested design looks good to me.

**Comment by MarcSabatella** [comment]
I like the design, and "hiding" it in the undocked pay controls is not especially worse than being in the almost equally hidden play panel for MU3.

It will be good if the slider is controllable by keyboard, both for general accessibility reasons but also for precision, to set exactly 50% or whatever.

**Comment by DmitryArefiev** [comment]
Fixed in #12803

(please notice the tempo slider doesn't work on Windows - #12817)

**Comment by MarcSabatella** [comment]
It's not missing, just hiding within the playback toolbar.  Undock it to display.  See the comment and screenshot above.

**Comment by daddadpfc** [comment]
Thanks Marc. I have re-booted the programme several times. The slider has appeared. Which is great. thank you. However, the playback is extremely problematical. It is skipping, jumping, different parts at different points. I'm not sure why this is happening. This also happened in the Beta versions I loaded previously. The files this is happening on work perfectly well in 3.6.2. Is this reported elsewhere? Can you guide me please if other people are experiencing this? should I post  a recording here?

**Comment by MarcSabatella** [comment]
If you are havinh with playback on a specific score, best to open a new issue, attach the score,e and give precise steps to reproduce the problem.  Also mention system specs - what OS, CPU, RAM, etc.
