### ISSUE TITLE
[MU4 Issue] Drumset Palette - Palette Order

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11741]
**Describe the bug**
Drumset palette order seems random instead of following order in instruments.xml

**To Reproduce**
1. Create score with any unpitched percussion instrument
2. Enter note entry mode
3. View Drumset Palette

**Expected behavior**
Drumset Palette order should follow order as listed in instruments.xml

**Screenshots**
<img width="915" alt="2022-05-25_11-34-51" src="https://user-images.githubusercontent.com/30370609/170219802-ad4bfa6b-5126-4e1d-809c-f74795bb4a82.png">

**Platform information**
OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2368923748, revision: github-musescore-musescore-8e6cd1f

**Comment by boryskuzmenko** [comment]
@Tantacrul Really confusing thing. I'd put P2

**Comment by HemantAntony** [comment]
I can take a look. I hope this is as easy as it seems

**Comment by Tantacrul** [comment]
@boryskuzmenko - thanks. Done.
@HemantAntony - yes please!

**Comment by boryskuzmenko** [comment]
After discussion with @RomanPudashkin decided to close this issue as not actual. 
Better to leave the implementation as is (same as in MU3). Notes in drum palette use chromatic notes order and it makes sense. And linking to Instruments.xml is a bad idea due to this document has now fixed logic so can't be a reference for any instrument orders in the app
