### ISSUE TITLE
[Inspector] Reset option is missing in Properties>Appearance>Arrange section 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11790]
**Describe the bug**
See compare with MU3

https://user-images.githubusercontent.com/90187801/170735311-efe18eda-7adf-4ae0-aca0-e9b561e1ae3f.mp4

![Untitled](https://user-images.githubusercontent.com/90187801/170734711-b268bf5b-6e31-4391-9a3f-c04faf5c849e.png)

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3** (in MU3 it's called Reset to style default)

MU4 Backward/Forwards buttons in Arrange section are equivalent of Stacking order (Z) feature in MU3

**Comment by Tantacrul** [comment]
Since the design for this has changed, I don't think the issue is really that bad anymore. Now that we have classic: Back / Forward / To Back / To Front - the user can achieve whatever they want easily enough and there's always the Undo button too.

I'm not completely against a reset option but I don't think it's something that should be in Beta 1 (or a P2) anymore.

**Comment by DmitryArefiev** [comment]
Fixed in #19131
