### ISSUE TITLE
[MU4 Issue] Corruption details are not available in the 'corruption warning' when opening corrupted score 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11807]
**To Reproduce**
1. Open the score 
[The_Avengers_Theme_Song_full_orchestra.mscz.zip](https://github.com/musescore/MuseScore/files/8798949/The_Avengers_Theme_Song_full_orchestra.mscz.zip)
2. Pay attention to the corruption warning

**Screenshots**

![Capture 2022-05-30_04-46-51_PM](https://user-images.githubusercontent.com/101250347/171010141-3684214d-424d-4789-bb29-2ac0b6ecc980.png)

**Expected behavior**
Corruption details button with corresponding info is available in the 'corruption warning' when opening corrupted score 
![Capture 2022-05-30_05-12-11_PM](https://user-images.githubusercontent.com/101250347/171010174-ef197a2a-da11-479a-9c3b-c8b754e9373e.png)

**Comment by jeetee** [comment]
@Tantacrul I'd like to make a (small) stand for increasing the priority on this task.
While we of course hope that we don't corrupt scores, it is inevitable that already corrupted scores will be opened in MS4. We are already seeing some forum posts about this and I expect a good lot more to follow after initial release.

Not being able to see the details hampers the users (and forum volunteers) in their efforts of fixing those. I thus expect an additional forum load from users that used to be able to fix their scores themselves, but will now come to us because they don't know where to start looking for the corruption.

**Comment by Tantacrul** [comment]
Upped the priority. Thanks!

**Comment by Tantacrul** [comment]
This is now being worked on by @bkunda. After @RomanPudashkin or @Eism - if you could tackle it, that would be great. Cheers!

**Comment by oktophonie** [comment]
Superseded by task https://github.com/musescore/MuseScore/issues/11807

**Comment by RobFog** [comment]
#11807 is this issue?
