### ISSUE TITLE
[MU4 Issue] Fixed spacer down gets negative default size and thus appears to break layout

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11826]
The fixed spacer down does something very strangely wrong.  To reproduce, create an empty score with any number of instruments, select the first measure in the last instrument, and click "fixed spacer down" in the Layout palette.  It should add a spacer down to the next staff/system, ready for you to resize to increase or decrease the spacing.  Instead, you get what looks like two staves overlapping each other.  That's because the default value for the height of the spacer is now -4 sp - exactly enough to force the next staff to overlap the current one.

The correct behavior is for the default value to be calculated at the moment you add the spacer, based on the current actual distance to the next staff.  So adding the space doesn't actually change the spacing, but instead gives you a perfectly-sized spacer ready for you to adjust in either direction.

Here is what it currently looks like:

![image](https://user-images.githubusercontent.com/1799936/171200560-57cc4503-f876-430d-a9ff-1821f32ad8a9.png)

versus what it is supposed to look like:

![image](https://user-images.githubusercontent.com/1799936/171200673-dafab914-2ea7-495e-b70f-2668f498e733.png)

I recall this having been an issue in 3.x but only in the special case of adding to the last system of a score (see https://musescore.org/en/node/317588).  That was supposedly fixed for 4.0, but actually, it broken for all systems as far as I can see.  It works for staves within a system, but not when attached to the bottom staff of system (eg, for any measure at all when dealing with single-staff scores).

**Comment by njvdberg** [comment]
This is as expected because the vertical space distributions kicks in. This algorithm tries to make the space between staves as evenly as possible (taking some weight factors into account). This is what you see here. It is also sea to check by switching off the justification of staves in the style editor.

**Comment by boryskuzmenko** [comment]
Ok. The case with the last staff on a big score looks as expected, but the case with a single staff is not. I checkd MU3 and there's no behavior like this. I definitely looks like a bug.

**Comment by njvdberg** [comment]
For me the behavior is the same as in MU3:

https://user-images.githubusercontent.com/48352523/172110897-f981bfa0-b677-49ea-adf4-49cbd8c76d29.mp4

You see that changing the size of the fixed spacer also change the spacing between the other staves. This is because of the vertical adjustment of staves. However, due to a bug you see the spaces doesn't touch the staff below the spacer. This is a bug in MU3. The reason is, in the first stage the algorithm tries to make the space between all staves the same (with taking some scale factors and limits into account). If there is still space left on the page, it tries to add some extra space between the staves so the lowest staff will touch to bottom margin of the page. However, it does also add this extra space between staves "spaced" by the fixed spacer and as the name **fixed** spacer suggest, this space should be fixed.
This demonstrated by setting the style parameter `Max. page fill distance` to 0sp. This parameter limits the extra space added in that last phase of the distribution algorithm. By setting this parameter to 0sp this last phase is actually disabled and now you see the fixed spacer always touches both staff above and below.

This issue is solved in MU4 (hence the different behavior?). Unfortunately, a PR is now broken and you need PR #11826 to fix this and show the behavior in MU4.

**Comment by boryskuzmenko** [comment]
See MU3 behavior on my mac:

https://user-images.githubusercontent.com/101250347/172120996-4584e80e-2cea-41ff-ae3c-d9b0d63bbf26.mov

@MarcSabatella is it expected for this case?

**Comment by MarcSabatella** [comment]
@boryskuzmenko Unless I'm missing something, the last video looks as expected to me.  Is there something in particular that seems off to you?

However, what you originally pointed out in https://github.com/musescore/MuseScore/issues/11826#issuecomment-1145907339 is definitely not what I expect.  I *think* I might I understand the explanation by @njvdberg, but I am not sure, so I'm going to think aloud here.

What I believe is happening is that MuseScore is first starting from a place of creating the minimum system distance between staves, then equalizing things if one system happens to require more space (by adding more space to systems that don't require it), and then spreading things out from there to fill the page.

With no spacer, the initial space between systems is equal before spreading, so there is nothing to do during the equalization, and when things are spread, distance remain equal.  With the space, several things happen: 1) the initial space is no longer equal because the space is actually forcing the distance below that system to be the spread distance instead of the minimum distance, and thus 2) the pass where MuseScore tries to equalize system distances now adds space below the next system, and then 3) MuseScreo now tries to spread from there but the first system won't spread because of the fixed spacer.

What isn't clear really to me is why the total amount of spread differs in these two cases.  The order in which things are done differs, and presumably that is the reason, but it does seem like there is room for improvement there.  But, my understanding might be way off, and maybe there is no better solution.

**Comment by Tantacrul** [comment]
@njvdberg - that is exactly how I think it should work!

**Comment by njvdberg** [comment]
@MarcSabatella 
> What I believe is happening....

It's clear you are a teacher and I'm not :wink: but this indeed what's happening.

> What isn't clear really to me is why the total amount of spread differs in these two cases.

This is the [_what to do on the last page_ discussion](https://musescore.org/en/node/332364). 
In the first stage the algorithm increases the space between staff 2 and 3 so it is the same as the space between staff 1 and 2 (as forced by the fixed spacer). Next it sees there is still space left on the the page so it adds extra space in order to fill the page.
However, since the space between staff 1 and 2 is fixed, no space is added. So only space between staff 2 and 3 added. That's why the space between staves 1-2 differs from staves 2-3.
This can be demonstrated by having 4 staves:

https://user-images.githubusercontent.com/48352523/172354754-d5cda04b-56bc-4126-b01a-0611a4a3e4e4.mp4

Now you see the distance between staves 2-3 and 3-4 are the same.
After setting `Max. page fill distance` to 0sp (actually disabling the last sage in which the algorithm tries to use all remaining space on the page) the distance between all staves is now the same until the `Min. system distance` kicks in. In that case the fixed spacer forces a small distance between staves 1-2 but the space between staves 2-3 and 3-4 will not go below this `Min. system distance`

**Comment by oktophonie** [comment]
The basic principle is (or should be) that, conceptually, the staves start bunched up closely together, then the space is distributed between them according to various rules/parameters.

According to that concept, adding a spacer between the top two staves, like in the above example, shouldn't cause anything else to change, since space _would have been_ added to reach that point. However, I understand from the explanations here why it's happening the way it is now.

Fixing or changing that would require more work and rethinking so, at this stage, is probably for a subsequent release. However, #11863 appears to fix the specific problem described in this issue so should be merged anyway!
