### ISSUE TITLE
[MU4 Issue] Figured bass - misplaced figures if begins with accidental

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#11833]
**Describe the bug**
If figured bass beginswith accidental (#, or b) it is horizontaly wrongly placed

**To Reproduce**
1. Write some notes in one bar
2. Add figure to first note, press space
3. Add figure begining with accidental to second note
4. Figure is placed down

**Expected behavior**
Figures should be horizontally aligned

**Screenshots**

https://user-images.githubusercontent.com/1646034/171287031-a7406c96-d583-41b7-9f5d-c3272f84ac7d.mp4

**Platform information**
 - OS: tested on Linux,but probably platform independent

**Additional context**
Misplaced only if figures are close each other. If there is extra gap (between bars, ...), figures are placed right.

**Comment by Tantacrul** [comment]
@oktophonie - what say you?

**Comment by oktophonie** [comment]
(This is not a regression from 3.6, as the same issue is evident there.)

The problem here (I _think_) is that the grey line above the figure which shows its duration, and which extends right the way up to the next duration, is not being treated as invisible, and so autoplace is bumping subsequent figures down where they have an accidental at the beginning, because the accidental is placed to the left of the origin point of the string.

![image](https://user-images.githubusercontent.com/20604032/173048997-9fad8370-4dfa-4ef6-8ec6-f6fe25f0d365.png)

Note that the first note in the second bar is _not_ bumped down, as the duration line of the previous figure stops at the barline, so autoplace does not kick in.

**Comment by sammik** [comment]
I think, gray duration line should be took into count in autoplace, see first two examples here

![figured_bass](https://user-images.githubusercontent.com/1646034/173057736-e732a2be-3233-4eec-8677-e6d5b1b1b499.png)

So probably accidental in figured bass should be ignored (in autoplace count).

**Comment by oktophonie** [comment]
It feels backwards (to me) for autoplace to consider an invisible component while ignoring a visible one.
For vertical alignment, aligning figured bass text like lyrics (i.e. consistent along the whole system, though that's configurable via Style -> Autoplace -> Vertical align range) might prove a better solution; other options could then be added, like making sure all figures stay below the lowest note of the system, etc.

**Comment by MarcSabatella** [comment]
See the discussion and analysis in the issue that was filed about this for MU3 some time ago - https://musescore.org/en/node/312291

Bottom line - I agree the gray line should *probably* not be considered when doing autoplace - which is to say, it shouldn't added to the "bbox" for the element.  That is definitely what cause the issue, anyhow.  But, it *does* appear to have been done deliberately - see https://github.com/musescore/MuseScore/blob/master/src/engraving/libmscore/figuredbass.cpp#L611-L614

And I *think* the reason is to avoid this:

![image](https://user-images.githubusercontent.com/1799936/173095968-ce51519d-4a58-4611-973e-793253f490c1.png)

Not sure it's worth it, though.

**Comment by sammik** [comment]
I just realized, probably we also shouldn't forget continuation lines
![figured_bass_cont](https://user-images.githubusercontent.com/1646034/173152945-a6ca6073-2e54-4284-a3bb-94e8f75e5be4.png)
(sorry, if it is offtopic)

**Comment by Tantacrul** [comment]
I'm going to bump to 4.x, since this is an existing issue.
