### ISSUE TITLE
[MU4 Issue] [GP] Default space between staves in imported score is less than in created score

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11840]
**Describe the bug**
The issue relates to both regular linked staves 

**To Reproduce**
1. Open any GP score
2. Pay attention to the space between staves
3. Create a linked staff for any staff
4. Pay attention to the space between linked staves

**Expected behavior**
Default space between staves in imported score is the same as in created score

**Screenshots**
![Capture 2022-06-01_01-33-58_PM](https://user-images.githubusercontent.com/101250347/171386973-058c9d47-342b-4c90-a6b4-4b53d1784c83.png)
![Capture 2022-06-01_01-33-33_PM](https://user-images.githubusercontent.com/101250347/171386978-b17f501e-6aa1-4611-8fbc-5ec7b529cbb7.png)

**Comment by Tantacrul** [comment]
@oktophonie - this is possibly by design, right?

**Comment by boryskuzmenko** [comment]
@oktophonie I investigated more and now see that the issue is actual for cases when additional elements are placed between them. Due to this issue, sometimes, there's unclear which staff an element relates to. See video.
Maybe, we should increase min distance between linked staves when additional elements present below the top staff or above the bottom staff? Or system should calculate the min distance for staves considering the lowest element on the top staff and the highest on the bottom one?

https://user-images.githubusercontent.com/101250347/173364659-06870197-cbe3-42f2-abf6-5679b5776d6d.mov

**Comment by abariska** [comment]
@oktophonie  To me looks like there's not enough space between staves when adding let ring. Could you please confirm that behavior on the last video is expected as a default style?

**Comment by oktophonie** [comment]
Yes, it is.
If you really want more space, increase Style... > Score > Min. vertical distance (under 'Autoplace') (when importing a score; do not change the default value).

**Comment by abariska** [comment]
🟢 **Not Actual** See comments above
