### ISSUE TITLE
[MU4 Issue] [macOS] Content is shaking when scrolling on trackpad 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11846]
**Describe the bug**
The issue is reproducible in cases when scrolling with inertia 

**To Reproduce**
1. Open any score
2. Open lots of pallets in inspector (scroll bar should appear )
3. Scroll a bit and leave trackpad to get inertia scrolling 
4. Try to do it with different intensity 

**Expected behavior**
Content is moving smoothly when scrolling on trackpad 

**Screenshots**

https://user-images.githubusercontent.com/101250347/171407344-355675d4-b22c-49ef-a6db-7515a01037b3.mov

**Platform information**
 - OS: macOS

**Comment by cbjeukendrup** [comment]
Cool that you found that it happens specifically when releasing the trackpad!

It may be worth noting that it works fine in the score view, where we implemented the scrolling ourselves. 

Note that this kind of inertia is caused by macOS, which keeps sending scroll events even after the user has released the trackpad. It is not created by us or by QML. (So that's different from the scrolling problems on Windows.)

QML Flickable does make use of "scroll phases". Probably it has a bug in the "momentum" phase. I'll try if I can tweak it in my self-built version of Qt.
