### ISSUE TITLE
[MU4 Issue] All instruments can be deleted via Inspector Instruments 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11909]
**Describe the bug**
At least one instrument should be present on score and you shouldn't be able to delete the last one. This rule works for creating score procedure and Instruments dialog, but doesn't for Instruments tab in Inspector. You can delete the last instrument by clicking Backspace.
As result we have another weird behavior. After all instruments deleted playback still can be run.

**To Reproduce**
1. Create a score
2. In Inspector delete all instruments by clicking Backspace
3. Press Play

**Expected behavior**
At least one instrument should be present on score and you shouldn't be able to delete the last one

**Screenshots**
![Capture 2022-06-07_12-52-06_AM](https://user-images.githubusercontent.com/101250347/172256349-1f9b755b-0084-4f22-b036-07cbffef8a84.png)

**Platform information**
 - OS: macOS, Windows, Linux

**Comment by shoogle** [comment]
You're right: there should always be at least one instrument in the score, and possibly in each part (`Excerpt`) too.

It's not because we want to stop users creating empty scores. It's because there will be other bugs if we allow empty scores. For example, text frames are stored in the top staff in the MSCX, so those frames will be lost when the file is saved with no staves and reopened later on. The safest option is to disallow empty scores.

**Comment by cbjeukendrup** [comment]
I'm not sure about disallowing empty `Excerpts` though, because when you create a new one, it is empty at first too.

**Comment by shoogle** [comment]
@cbjeukendrup, that's a good point. I tried it now and noticed more bugs with deleting instruments in `Excerpts` so I think we should concentrate on the main score here and deal with `Excepts` in a separate issue.

**Comment by Tantacrul** [comment]
So this is actually my doing! I intentionally asked to get rid of the old MS3 behaviour of needing to have one instrument present on the score at all times because I keep finding that the MS3 rule results in frustrating experience under certain circumstances.

Mainly, when users want to change a score with one instrument to have something else instead (like they do with those 1 staff piano scores), they have to add the instrument they want first and then delete the one they don't want, which is really weird.

Also, there's no good UX reason to force the behaviour of always needing one instrument.

If there are associated issues, we should solve them individually. For example:
- If the play feature still works when the score is empty, I think it should be disabled.
- If there is UI that can be interacted with while the score is empty it should (potentially) also be disabled

**Comment by Tantacrul** [comment]
I should also mention that we'll need the concept of the score being empty in future anyway.

For example, we want to introduce the capability of creating **sections** (movements, songs, etc.) in an upcoming release. These can also be switched on and off using an 'eye' button. If there was a 'score can never be empty' rule, it would cause some annoying UX problems with those too.

Specifically, if I have two movements visible on my score and I only want to see Movement 2, I might decide to hide movement 1 first, which would momentarily leave the score empty.
