### ISSUE TITLE
[MU4 Issue] Beaming options in Properties can make 32nd beam look like 16th

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#11919]
**Describe the bug**
Using the beaming options in the Properties panel, you can make beamed 32nd notes look like 16th notes.

**To Reproduce**
1. Create a score with 32nd notes
2. Select their beam
3. In the properties panel, click the "begin 32" beaming option (it has the wrong icon/tooltip by the way, see #9977)

Result: the notes look like 16th notes

**Screenshots**

https://user-images.githubusercontent.com/48658420/172494542-9bc35fa6-673b-49c2-8583-4775974394e4.mov

**Expected behavior**
This situation should not be possible. 

I think we should reimagine the beaming options to make something that's both comprehensive and comprehensible and always produces valid results. 
The current situation feels like we are providing some random options, which together after some fiddling enable you to create the situation that you want if you're working with 8th or 16th notes. 
Instead, I think we should consider a WYSIWYG control that lets you choose for each beam level whether the note should be connected to the notes at the left and right sides. If you disconnect both sides, you will get a "fractional beam"/beamlet or flag, otherwise a connecting beam will be created as you specify. 
For now, if you disconnect the primary beam, the secondary etc. should be disconnected too, but in the future we can drop this restriction, making it possible to create unconventional beamings.
(These are just musings though, probably we'll have to stick with what we have now until after 4.0.)

**Platform information**
 - OS: reported on macOS

**Comment by cbjeukendrup** [comment]
@Tantacrul Feel free to reprioritize :)

**Comment by oktophonie** [comment]
A few problems to solve here:

1. Up to MU3.6 these beam options were intended to be applied to _notes_, not beams; if a beam were selected and one of the 'Beam properties' palette items was clicked, nothing would happen. (Exception: the feathering options, but that's been moved elsewhere now and in any case is awaiting reimplementation in MU4.)

The 'Beam properties' items are now duplicated as 'Beam types' in the Properties panel under Note -> Beam:
![image](https://user-images.githubusercontent.com/20604032/172590189-2572b5af-ff35-492c-99a6-28ffb35a6b22.png)

but their behaviour is different: the beam type chosen will be applied to every note that the beam spans. The behaviour _should_ match that of the palette, i.e. nothing should happen. In fact, since several of these options make no sense to be applied to all notes of a beam, I argue they should be greyed out (if not removed) when a beam, rather than note(s), is selected.

Valid 'Beam types' to apply to the beam itself would be:
- AUTO: would reset any alterations made to beam subdivisions (the Format -> Reset beams menu option also does this)
- Beam middle: this would, effectively, remove any beam subdivisions
- No beam: effectively removes the beam, making all notes separate. (Is there not a case for this being achievable simply by selecting the beam and pressing 'Delete'?)

The other options only make sense when applied to specific notes, so should not be available.

2. While we first want to fix the behaviour of the 'Beam types' in the Properties panel, that same behaviour is still available by selecting all or multiple notes within a beam, and can still produce nonsensical results as originally described in this issue. Obviously, whatever beams result should always show the proper rhythmic duration for the notes to which they apply.

For example, applying 'Beam 16th sub', i.e.
![image](https://user-images.githubusercontent.com/20604032/172596353-da5afcfc-5732-4a1b-8d77-e1d2ac189521.png)
to a 32nd note should never result in that note itself having fewer than 3 beams in total. However, it should reduce the number of beams connecting that note to the previous note to 1, if applicable, so it still has an effect. (And likewise for 'Beam 32nd sub').

Apart from 'No beam', none of the beam options have any (visual) effect when applied to the first note of a beamed group.
