### ISSUE TITLE
[MU4 Issue] Toolbar buttons disable for lines and layouts only after hover

### ISSUE THREAD

**Issue by KLee1248** [musescore/MuseScore#11984]
**(edited by @Tantacrul)**

**Describe the bug**
When the user selects a line or frame, it appears that the toolbar is supposed to disallow the user from doing certain actions (such as adding a sharp or marcato marking). However, those buttons are still enabled until the user hovers over a button long enough for the tooltip to appear.

Seems to affect at least the following:
* All Lines (Slurs, Crescendos, Trills, etc.)
* Barlines (Repeats, Normal Barlines, etc.)
* Vertical / Horizonal Frames

**To Reproduce**
1. Create a new score with a piano (should work for any instrument).
2. Add a crescendo hairpin to the rest in measure 1.
3. Select the crescendo hairpin
4. Hover over the voice 2 button in the toolbar (or any button that's not tuplet or flip direction).
5. Wait until the tooltip appears.
6. Note that most of the toolbar buttons are now disabled (can't be clicked).

**Crash details**
On MacOS, select a crescendo line and hover over Voice2 to produce a 100% reproducible crash.

https://user-images.githubusercontent.com/21022311/173198369-cc203a75-53a4-4ed5-b926-cd5cfbfb5b3c.mov

**Expected behavior**
- If the intention is for the buttons to be disabled, then it should happen immediately
- Otherwise, the buttons should not become disabled at all (should just do nothing)

**Screencast**

https://user-images.githubusercontent.com/2625852/173157563-24a2ab1c-33c5-4ae0-a014-5ec8f5cc4121.mp4

**Platform information**
 - OS: Windows
 - Build: Nightly MuseScoreNightly-202206090431-master-8a3bf7c-x86_64

**Comment by Tantacrul** [comment]
Have added more details, since this can also reliably cause the MacOS version to crash. (Not confirmed for Windows or Linux)

**Comment by cbjeukendrup** [comment]
The crash happens with a lot of elements: hairpins, voltas, ottavas, probably more. It happens when the notation view gets focus while one of these elements is selected, which happens for example if a tooltip is hidden, and when a popup is closed while the notation view was the last focused item before the tooltip or popup was opened. It also happens when the notation view receives focus by keyboard navigation while such element is selected.

All these elements are constructed directly instead of created via the `Factory`, and therefore they don't have an accessibility item attached. Thus a crash occurs when trying to focus that accessibility item. So the solution is simple but time-consuming: making sure that every element is created via the `Factory`.

**Comment by DmitryArefiev** [comment]
Fixed in #12013
