### ISSUE TITLE
Document views (Side by side / Stacked) lost in MS4; restore?

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11991]
**Describe the bug**

Not only has the ability to open multiple documents in the same window been lost (see #11989) but so have the document view options: "Stacked" and "Side by side".

These are still useful, even essential, options, even if only one document can be opened at a time. IME, there are times when it is useful to be able to view two instances of the same document, for example to copy a section from one location to another.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2478704457, revision: github-musescore-musescore-594ee1a

**Comment by Tantacrul** [comment]
This is a feature we were unfortunately forced to delay for MU4.0. Since we needed to move to a system comparable to most other DAWs and notation apps (for reasons to do with audio plugins and CPU load), this feature was not trivial to re-implement. In fact, we don't yet have an exact answer for how we'd reimplement it.

Perhaps we'll built a more limited version that allows you to still keep multiple views of 1 score. That would be perfectly possible.

Closing as not planned for 4.0.
