### ISSUE TITLE
[MU4 Issue] Mixer: Pan & volume settings from MU3 not remembered in MU4  

### ISSUE THREAD

**Issue by awrog** [musescore/MuseScore#12037]
**Describe the bug**
I've set pan-settings and volume levels per staff in the mixer in MU3.
Upon opening the same score in MU4 the pan-settings and volume levels have lost

**To Reproduce**
1. set pan-settings and levels per staff/track in the mixer in MU3 and save the score
2. open the same score in MU4 and observe in the mixer: pan-settings and volume levels are not present

**Expected behavior**
I expect the saved pan-settings and mixer-levels to be present in MU4

**Screenshots**
![image](https://user-images.githubusercontent.com/12153667/173900828-324a88cf-02fa-4701-871a-1662fa22ff85.png)

![image](https://user-images.githubusercontent.com/12153667/173900868-08720842-430f-49a8-b7e8-157cddd2e7d1.png)

**Platform information**
 - OS: Windows 10

**Comment by Tantacrul** [comment]
@vpereverzev - is this even something we can approximately fix, given that every aspect of the playback system and audio engine is new?

If now, I think we bump this to Post Beta or even disregard.

**Comment by Tantacrul** [comment]
I think this is going to be significantly difficult for us (not impossible of course, just really time consuming) because everything about the playback of MuseScore 4 is different to V3 - and any translation would be approximate anyway.

Basically, with playback we are starting again in order to support much more sophisticated samplers now and in future and we don't see a gigantic need to be able to provide a 1:1 translation for soundfont. This was a one-time thing, which we won't be doing again. It's not something we made a decision on - just something that became obvious as we proceeded.

Incidentally, when you hear Muse Sounds, you'll understand why we went to so much trouble. When we begin attracting more 3rd party plugin manufacturer to create sounds specifically for MuseScore, that'll only improve matters further.

I'm going to close this bug for now as a 'won't fix'. For those who are wedded to the sounds they created in MS3, the obvious consolation is that V4 will not overwrite V3 and both can be used on the same OS.
