### ISSUE TITLE
[MU4 Issue] Clicking on bottom-right triangle in "note entry" toolbar button doesn't work as expected

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#12217]
**Describe the bug**
In v3 there's a "v" button next to the note entry toolbar button for which a single click will bring up the expected context menu.
v4 has a little black triangle in the corner that I assume is for the same purpose but doesn't appear to work - a single click on it just turns on/off note entry mode.

**To Reproduce**
1. Create/open any score
2. Click on this:
![image](https://user-images.githubusercontent.com/5364225/176546191-afac66bc-11a1-4127-abb8-0f5583031dfa.png)
3. MuseScore goes into note entry mode and no dropdown menu is shown

**Expected behavior**
As per v3, should show dropdown/context menu with different note entry modes.
It's not even clear how to reliably bring this up (it seems you have to hold down the mouse button).

**Screenshots**

**Platform information**
Windows 10

**Additional context**
Debug build running under Visual Studio from latest source on master

**Comment by Tantacrul** [comment]
Yes. We're going to leave this for now - not least because there's not much on offer when you actually do figure it out.

Incidentally, this pattern is taken from other creation apps (long press to reveal more). I have no problem changing it in future but we'll do it after 4.0.

Bumping to 4.x for now. Will reopen then.
