### ISSUE TITLE
[MU4 Issue] MuseScore window is too large

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#12226]
**Describe the bug**
When you open MuseScore, the window is too large compared to before, not to mention everything is magnified.

**To Reproduce**
1. Open MuseScore
2. Everything is magnified and large

**Expected behavior**
MuseScore window should not be this large and magnified.

**Screenshots**
![image](https://user-images.githubusercontent.com/88136054/176639144-820458a0-cf7a-45f7-b4df-0807a2320850.png)

This highlights the difference (One is an old MuseScore):
![image](https://user-images.githubusercontent.com/88136054/176641423-a83f82f5-0845-4ba4-98c3-499094c7c9cb.png)

**Platform information**
 - OS: Windows 11

**Additional context**
I'm using Qt Creator. Bit weird no one has reported this yet
@Tantacrul

**Comment by cbjeukendrup** [comment]
Is this a recent change? If so, could #10285 play a role?

**Comment by HemantAntony** [comment]
I can't say if its super recent. I just updated my branch. The last time my branch was updated was like 5 days ago

**Comment by oktophonie** [comment]
(For me the UI recently - i.e. a day or two ago - went all tiny again (Linux), but I can't say I've investigated this at all yet.)

**Comment by HemantAntony** [comment]
That would make sense. The said PR was merged two days ago (@Eism). Feel free to add images to the original issue :)

**Comment by Eism** [comment]
Yes, it's because of my pr https://github.com/musescore/MuseScore/pull/10285.
But it needs to be clarified
Everything is magnified and larger than before in MuseScore 
OR 
Everything is magnified and larger than other programs

If second, then that's the problem.

Also we need to compare with programs that support fractional scaling.

**Comment by HemantAntony** [comment]
@Eism I think its both

**Comment by DmitryArefiev** [comment]
@HemantAntony Yes, that's expected because of #10285. 
Now MU reacts when changing Display>Scale and Layout> Size of text, apps etc settings to **125%** 

![Capture](https://user-images.githubusercontent.com/90187801/176668890-b2ff50a0-455f-450d-b5d3-99a5f86e1290.PNG)

Previously MU didn't change UI size elements when switching between 100 and 125, and changed the size only when select 150. But on 150 it was too big (MU looked as on 200)

Are you using 125? and what display size and resolution do you have?

Thanks!

(also there is blurry issue now on 125,150 you might have noticed - #12193)

**Comment by HemantAntony** [comment]
Yeah I'm using 125%. Its the default one. My display resolution is 1920 x 1080

![image](https://user-images.githubusercontent.com/88136054/176672828-18e9ba4f-ac4a-4c0b-b5f9-d4ae763312bc.png)

**Comment by DmitryArefiev** [comment]
> Yeah I'm using 125%. Its the default one. My display resolution is 1920 x 1080
> 
> ![image](https://user-images.githubusercontent.com/88136054/176672828-18e9ba4f-ac4a-4c0b-b5f9-d4ae763312bc.png)

@HemantAntony Thanks for the info! But is this really annoying? On my laptop with **16'** display,  **2560x1600** res and **125%**, MU4 now looks better. The UI size looks similar to other apps now (e.g. comparing with Firefox).

Maybe you can try 100%?

**Comment by HemantAntony** [comment]
Okay fair point. It isn't that annoying. I guess the change caused it to be annoying. But now it isn't too bad. Changing it to 100% does make MuseScore look better. But then all programs get scaled down.

So, if you want me to close this issue (and wait for other people's opinions regarding this), I'm okay with it.

However, I do like the idea of scaling things in MuseScore as a setting (suggested by @MarcSabatella)

**Comment by Tantacrul** [comment]
Regarding scaling settings, this is how we should approach it.

- Default scaling for MS4 should work on all OSs.
- We should never suggest fixing an OS scaling issue with settings in MS4
- Scaling settings in MS4 are for people who choose to do it in MS4 specifically because they **don't** want to choose an OS scaling option. In this case, we should implement scaling features in later releases, not in MS4.0.

I'm going to close this for now.
