### ISSUE TITLE
[MU4 Issue] Add staff > Bass clef added to Treble clef instruments

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12353]
**Describe the bug**
That seems to be **occur only with templates** and **only with treble clef instruments**

![Capture](https://user-images.githubusercontent.com/90187801/178472428-6b384870-f6f3-4a82-8018-033f9708fc6f.PNG)

**To Reproduce**
1. Open String quartet template 
2. Add staff to violin - **added staff has a Bass clef instead of Treble clef**

https://user-images.githubusercontent.com/90187801/178472898-78475844-3e5e-4330-ad85-c6a6b577864f.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
See comments below

**Comment by sammik** [comment]
Acording to a discord chat - @softcat477  found out, core problem of issue seems to be, that MU doesnt save treble clef.

So issue is not only with templates, but also in any score with instrument in trebleclef, after save and open.

Question now is: is not saving treble clef intended?

**Comment by softcat477** [comment]
Add more detail about what I found, this issue exists not only in templates but to any saved score,  when saving a score with instruments using treble clef, loading the score back, and adding staffs to that instrument. Here's the step to recreate this issue:
1. Create a new score -> Choose instruments -> Select instruments with treble clef. e.g. violin.
2. Click Add staff -> successfly add a treble clef. This is the behaviour we want.
3. Remove the new staff so there's only one staff left.
4. Save this score. Reopen the saved score.
5. Click Add staff -> a bass clef is added. This is wrong and we want a clef staff. 

https://user-images.githubusercontent.com/25975988/187043593-3d1ec273-deab-4659-ad6c-4bcf4ceb8863.mov

---

This is because an instrument's clef determines the new staff's clef type. When the score is saved, treble clefs are not saved. So once we load the score back, instruments using treble clef have no clefs, and their _clefList is empty. Later on, when adding new staff to an instrument, there's no clef in the _clefList to determine the desired clef type, and MuseScore generates a bass clef as its default clef and causing the issue. 

Since the treble clef is the clef being discarded, changing the default clef to treble clef can fix this issue. As far as I know, this change will not be problematic for keyboard instruments, considering that the second staff should use a bass clef instead of a treble clef. Keyboard instruments have at least one treble clef and one bass clef, and deleting the bass clef will not affect the _clefList of the instrument. So when we do these operations:
1. Create a keyboard instrument. e.g. piano
2. Delete its bass clef so there's only one treble clef left.
3. Save the score.
4. Load it back and add a new staff as the second staff.

We will not trigger the default clef. This is because step 2 does not delete the bass clef of the instrument, and in step 3, the bass clef is still saved even though it is not shown on the score. Finally, step 4 reads the bass clef back and uses this clef to generate the second staff. So the second staff will still be a bass clef instead of using the default clef type.

---

Of course another way to solve this issue is to save treble clef.

**Comment by Tantacrul** [comment]
Moving to post-beta since it isn't a ship-blocker. We could release with this issue (although obviously I'd prefer we didn't):

- Users can easily change the clef back to a treble clef
- It's very unlikely a user would add a new staff to a single-staff instrument in most cases

**Comment by DmitryArefiev** [comment]
Fixed in #12888

**Comment by DmitryArefiev** [comment]
@softcat477 Thanks for fixing!

I found another case and logged it separately #13461
