### ISSUE TITLE
[MU4 Issue] Menu won't close when you click on the desktop panel/taskbar

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12402]
**Describe the bug*
In MS3, if you had a menu open it would close if you click on the panel (linux) which lies outside the MS program window (Taskbar in Windows). However, the menu stays open if you do the same thing in MS4.

A similar issue was fixed in #10993.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2667920094, revision: github-musescore-musescore-0f1e7fb

**Comment by Eism** [comment]
Tested. Yes, the menu does not close.

But I think it isn't a bug. Behaviour is the same as on macOS
The application does not change the state, the user can continue to work.
The shortcuts and navigation still work

Closed as expected behaviour
@rgreen5 you can reopen if you find a critical bug blocking the user's work
