### ISSUE TITLE
[MU4 Issue] Can't access edit mode by double-clicking symbols added from Master Palette

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12423]
**Describe the bug**

In MS3 you could double-click on a symbol added from the master palette to access edit mode. This would allow you to reposition the symbol using the keyboard arrows. In MS4, this mode of access has been lost (the short cut and context menu options are still extant). It needs to be added back

**To Reproduce**

1. Add any symbol to the score from the "Symbols" section of the "Master palette".
2. Try to access edit mode by double-clicking. Check that you are in edit mode by trying to move the symbol with the keyboard arrows.
RESULT: You can't access edit mode. The program remains in "normal mode".
3. Compare this behaviour with the same situation in MS3.

**Expected behavior**

Double-clicking a symbol added from the Master palette should put the user in edit mode and allow it to be moved using keyboard arrows (as in MS3.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2674645330, revision: github-musescore-musescore-fa566a6

**Comment by wizofaus** [comment]
Are you sure this is specific to master palette? It shouldn't really matter how the item is added to the score.  Will have a look though, edit mode in v4 is was a reimplementation from v3 that works quite differently in general.

**Comment by wizofaus** [comment]
Confirmed it also happens when adding symbols from, e.g. the Accordion palette.  Basically there's no code to handle double-click in the case of Symbol-type elements on the score.  We can add it back easily enough, but I note that double-click to activate edit-mode for *notes*/rests has been disabled too -  personally I'm glad to see this because previously it was far too easy to accidentally activate this mode just when adding a note then clicking on it to drag (though there are other ways that could have been addressed).
Currently the only element type for which double-click activates edit mode is "instrument names" (as per notatonviewinputcontroller.cpp, line 738, in NotationViewInputController::mouseDoubleClickEvent).
Do we want to restore it for Symbols too @Tantacrul ?

**Comment by rgreen5** [comment]
(Incidentally, in MS3 there was a mode indication on the right hand side of the status bar which showed the user whether s/he was in normal / note input / edit mode. This is no longer present in MS4.)

**Comment by wizofaus** [comment]
Yes, have raised that and even come up with a proposal for getting rid of edit mode entirely (would require using modifier keys).

**Comment by Tantacrul** [comment]
I don't think we should use double-click for this mode due to the confusion it causes. Since there is already a way of entering the mode via the context menu, I think this is covered for now. I want to make some significant changes to how users can achieve the same aims in a more discoverable way in future releases.

Incidentally 'edit mode' is a **really** confusing name. I'm thinking we should call it something like 'free movement mode' or something like that. Thoughts?

**Comment by wizofaus** [comment]
"Free movement mode" might make sense for notes but not really for other symbols.  "Position-adjustment mode" would be more accurate. But the fact it's hard to think of a good name and the fact it's hard to provide feedback that such a mode is active are good reasons to scrap it, and just rely on keyboard modifier combinations or different shortcuts.

**Comment by MarcSabatella** [comment]
To me, "free" means the opposite of "restricted" in this context, but that's not accurate.  You don't need a special mode for "free" movement - dragging does that nicely without first going to a new mode.  The real point of edit mode for symbols is that it allows for *constrained* movement, and in particular, *keyboard* movement, using the cursor keys.  Precisely horizontal versus precisely horizontal, precisely in 0.1 sp or 1 sp increments.

This is pretty crucial functionality, so whatever it's called should sound inviting and be easy to invoke.

For the naming, "restricted" and "constrained" of course sound pretty negative.  "Precise keyboard adjustment mode" would be more neutral and also accurate, if not very poetic.  Whatever term is chosen, though, should have the same meaning.  Nothing about the words "edit" or "free" really suggest that at all.

As for how to invoke this mode, double-click is much simpler than fiddling with context menus, so disabling that is definitely a step backwards in efficiency, and I question whether it buys anything in return.  On the other hand, since the whole point of edit mode is to enable keyboard-based motion, really, getting into the habit of using a shortcut to enable it is not a bad idea anyhow.  And having it be something simpler than Alt+Shift+E (e.g., F2) will be appreciated

**Comment by wizofaus** [comment]
"On the other hand, since the whole point of edit mode is to enable keyboard-based motion" - except for notes/rests, where it significantly changes what dragging with the mouse does, which I believe is why @Tantacrul suggested "free movement mode".

If it were purely about being able to use the keyboard to make more precise adjustments, scrapping edit mode entirely would be a no-brainer, and just defining new shortcuts for "precise move left", "precise move right" etc.

**Comment by MarcSabatella** [comment]
Even for notes, edit mode allows for the same keyboard adjustment (or is meant to, anyhow, and always has in the past).  If it has some other unfortunate effect with respect to dragging, I'd say, that's a separate issue, and yes, solving it would be nice too.  Disabling double-click as a method of ending edit mode does help. I will grant that.  But still, notes *do* need to be nudged sometimes just like anything, so whatever mechanism is chosen for nudging symbols should be the same for notes.

Whether that mechanism is double-click then arrow, F2 then arrow, or Ctrl+Alt+Shift+Fn+Arrow or whatever, wouldn't matter at all to me except that if there is to be a really significant change to how it's worked before, I'd like there to be a clearly definable *advantage* to the change.  The downside of double-click is clear for notes, so it's down to the others as the primary method.  F2 then arrow is nice because it's discoverable via the context menu.  Other programs that have nudge usually don't also have ordinary linear navigation, so the "easy" key combinations aren't normally taken already, but in MuseScore, we'd be forced into combinations involving three or more modifiers.  I don't really see the advantage of requiring complex key combinations for operations many of us do thousands of times a day
