### ISSUE TITLE
[MU4 Issue] Custom grace note positions in tablature are lost when MS3 file is opened

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12440]
**Describe the bug**

When you open an MS3 file in MS4, the _custom_ positions of _tablature_ grace notes are lost making the tablature very messy. (Tablature grace notes at default positions are not affected.)

**To reproduce**

1. Open the attached MS3 speciemen score. 
[specimen_score.zip](https://github.com/musescore/MuseScore/files/9125608/specimen_score.zip)

2. Inspect the grace note positions.
3. Compare it with MS3.

RESULT: In the tablature, measure 2, the grace note position, which was at default, is preserved. In measure 4, the custom-positioned grace notes (and the slur around them) are way out of position. They have to be reset by the user and repositioned.
![grace_notes](https://user-images.githubusercontent.com/87246583/179352090-fd0885fb-275f-40d0-8a4a-f045ba764588.png)

**Expected behavior**

Custom grace note positions in tablature should be preserved.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2680600421, revision: github-musescore-musescore-315cfb3

**Comment by mike-spa** [comment]
Two separate problems are causing this issue. 
1) A small error in grace notes layout which causes them to apply a larger offset than requested. This is now fixed in #12469.
2) People used to apply manual offsets because default positioning was often bad in older versions, particularly with grace notes. In 4.0, however, the default position is usually correct, and applying the old offsets will most likely make it wrong. We will takle this separately, probably by resetting grace notes position when migrating older scores.
