### ISSUE TITLE
[MU4 Issue] Duplets wrong length in compound time

### ISSUE THREAD

**Issue by alexh90** [musescore/MuseScore#12546]
Musescore 4 creates duplets of the wrong length - dotted instead of straight quavers in a duplet in 12/8.
![MS4](https://user-images.githubusercontent.com/8417513/180750904-38cca619-8b73-457a-9580-4e6c70da48d4.png)

Works in Musescore 3.6
![MS36](https://user-images.githubusercontent.com/8417513/180750940-6ae824bf-8900-40f4-b0ae-e84755596115.png)

1) In 12/8 I am attempting to create a duplet of two quavers in the place of 3, one beat.

2) I select the rest of a dotted crotched and press ctrl-2 and it creates me two dotted quavers in a duplet instead of a quavers.

3) Have tried using the menu to create the duplet - same result.

4) Have tried selecting a crochet before turning into a duplet - this creates notes of the correct length but adds an incorrect rest
![MS4-2](https://user-images.githubusercontent.com/8417513/180751013-5c068b61-b54b-4b96-9c9c-bd7431c23b04.png)

MuseScoreNightly-202207240437-master-5e7884d-x86_64

**Comment by Tantacrul** [comment]
@alexh90, @oktophonie - this seems to be just a wrong visual, since the playback is correct. One for the engraving team?

**Comment by Tantacrul** [comment]
If not, the probs for @vpereverzev to decide

**Comment by oktophonie** [comment]
An odd one. Nothing springs to mind that we've done on the engraving side that might account for this. Anyway, we'll take a look!

**Comment by MarcSabatella** [comment]
This wouldn't be an engraving issue exactly, but more of the tuplet-creation behavior.  I seem to recall this having been a conscious change based on user feedback at some point.  It's really a matter of whether the default ratio is calculated as 2:3 (two eighths), 4:3 (four eights, or two quarters), or 2:2 (two dotted eighths) - always a controversial choice in cases like this it seems.  Reasonable (to me) cases have been made in favor of each of those as being somehow "logical".

Anyhow, if you prefer the two eighths, you get it via Add / Tuplets / Other, and setting the ratio to 2:3.  If you prefer two quarters as others do, set it to 4:3, but be annoyed that the number displays as 4 (as it should if you're actually entering four eighths) instead of 2 (as you'd prefer if entering two quarters).  The result you get now comes from the Ctrl+2 algorithm choosing 2:2 if a dotted duration is selected.

To me, the current default of 2:2 is the least desirable, and Gould recommends against it.  She's steadfastly non-committal regarding whether two eighths or two quarters under a duplet is better, or whether two dotted eighths with no duplet is better than either.  Frankly, I've seen all four in the wild.

**Comment by oktophonie** [comment]
It would seem most sensible to have a style preference for whether to notate duplets as 2:3 or (effectively) 2:1.5 as both are fairly commonly encountered. A similar issue exists for some other divisions, like 7 (7:8 vs 7:4). Fortunately, there are far more comprehensive texts than Gould's covering all this.

For now though, I see no reason to default to 2:2, which (I concur with Marc) is the least desirable option, and the most confusing. So unless someone has a good reason not to, we will revert to 3.6 behaviour in this regard.

Adding a duplet/quadruplet/octuplet to a non-dotted note (point 4 in the original post) doesn't really make any sense. One could argue that MuseScore's current behaviour in this situation is sort of logical. One option would be to disallow this, but I'm sure someone's found a use for it somewhere.
