### ISSUE TITLE
[MU4 Issue] Splash-screen is not displayed when running MU4 on Linux

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12550]
**To Reproduce**
1. Open the last master build https://github.com/musescore/MuseScore/actions/runs/2729870681
2. Pay attention to the frame on the center of screen

**Expected behavior**
Splash-scree is displayed when running MU4

**Screenshots**
![Screenshot from 2022-07-25 20-08-36](https://user-images.githubusercontent.com/101250347/180836443-d810c73d-d8b1-4f56-b3eb-b5808efb7457.png)

**Platform information**
 - OS: Linux

**Comment by Eism** [comment]
On Windows, the background should be transparent

![image](https://user-images.githubusercontent.com/10116828/180945226-dce302a8-bf03-4355-a0af-4543e8edb1fa.png)

**Comment by sammik** [comment]
In my desktop (Ubuntu studio, KDE, Plasma), splash screen is there (latest nightly - 28.7.).
Corners are not transparent.

https://user-images.githubusercontent.com/1646034/181507022-499b0d72-f51b-479c-83b3-60f0f251cda8.mp4

**Comment by MarcSabatella** [comment]
For me on Debian (running under ChromeOS, so no Linux-side window manager), the splash screen is there, and annoyingly, it's also there again every time I create a new score.  I guess because a new instance of MuseScore is created for each new score, but only the first should create the splash screen.

**Comment by HemantAntony** [comment]
But what if the score is quite large and it takes time to load. Won't it be annoying if there is no indication that the score is being opened?

**Comment by cbjeukendrup** [comment]
The loading of the score happens after the app has already launched, so when the splash screen is already gone. 

If we want, we can make the splash screen appear only for the first instance that is being launched, but I wouldn't know why we'd do that. For secondary instances, it takes exactly as long to load as for the first instance, and there is no indication that a new instance is being loaded, so the user has to wait multiple seconds while nothing seems to happen.

**Comment by MarcSabatella** [comment]
I would just say, I can't recall ever seeing a splash screen used for that - they are normally startup only.  Instead, a separate loading progress dialog would normally be used if needed.  As it is, seeing the splash screen again look like a bug, since it is unexpected based on how other programs work.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Can't be reproduce anymore
