### ISSUE TITLE
[MU4 Issue] Text lines end on the note preceding the last selected 

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#12558]
**Describe the bug**
Text lines end on the note preceding the last selected 

**To Reproduce**
1. Select two individual notes
2. Insert a text line (staff line, system line, ottava, etc...)

**Expected behavior**
Lines should end on the last selected note.

**Additional context**
If the whole range is selected (basically, if you do Shift+Click instead of Ctrl+Click) you get the correct result.
The is very likely related also to [this](https://github.com/musescore/MuseScore/issues/9975).

**Screenshots**

https://user-images.githubusercontent.com/93707756/180971402-2653ffe3-46d6-406e-9020-6e693888a2fc.mp4

**Comment by wizofaus** [comment]
In general when adding lines to the score if you want to have it span between two notes/rests, you need to select them as a range. Wasn't it the same in v3?
Interestingly, it's true for all items in the Lines palette - except slurs.
What's arguably unexpected is that if you select two individual notes separated by rests (even whole measures), it still behaves the same way - ending the line just *before* the later selected note.  There's half an argument it shouldn't let you add lines unless you first select the range over which it should span (but no, I wouldn't advocate for that, unless there was a clear explanation why you couldn't add the line).

**Comment by HemantAntony** [comment]
@mike-spa I think this affects specifically spanners because I have seen similar behaviour in an element which inherits Spanner

**Comment by MarcSabatella** [comment]
See my comment in https://github.com/musescore/MuseScore/issues/12564#issuecomment-1196769300 regarding reasons why it's important to carefully consider changes here.  But also, keep in mind there is special casing for different types of lines to make them start and end at the "correct" place relative to the note/rest to which they are anchored.  Some of the code regarding selection is optimized to feel the most natural for each line type.

One case that is *not* so optimized is pedal lines like "___/", where a range selection of a single measure really should be automatically adjusted to place the bracket under the first note of the next measure (by changing the anchor, probably, rather than changing the layout).  But anyhow, this is the sort of thing that could stand a good hard look across the board.

**Comment by Tantacrul** [comment]
I agree that for text lines, the current behaviour seems very unintuitive. I believe we stand alone with this specific behaviour, compared to anyone else. I think we should implement @mike-spa's suggestion.

- It should work consistently when holding **shift** and selecting _and_ when using **Ctrl/cmd** to select two different notes
