### ISSUE TITLE
[MU4 Issue] Hairpins end one note early

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#12564]
**Describe the bug**
When you add a hairpin (not via palettes), the hairpin does not end on the second selected note. It rather ends on the note previous to that one

**To Reproduce**
1. Select two notes
2. Add a hairpin (either `Add->Lines->Crescendo` or shortcut `<`)
3. The hairpin ends early

**Expected behavior**
Hairpins should end on specified note

**Screenshots**
[Issue.webm](https://user-images.githubusercontent.com/88136054/181192619-bc40a931-6881-4b99-bb6e-83c687ba947b.webm)
(I can't seem to embed the video correctly)

**Platform information**
- OS: Ubuntu

**Additional context**
When adding via palettes, the hairpin gets placed fine
@Tantacrul this seems important

**Comment by oktophonie** [comment]
The difference seems to be between whether you select two notes, or a range.

If you select a range, e.g.
![image](https://user-images.githubusercontent.com/20604032/181225018-f3621804-5407-4277-8f7c-e87751c331f9.png)
and add a hairpin - either via palette or keyboard shortcut - you get this:
![image](https://user-images.githubusercontent.com/20604032/181225149-cd04a1d5-99ec-45eb-bb57-2e8977f4e14c.png)
where the hairpin ends on (or 'after') the last selected note.

If you select just the outer notes, e.g.
![image](https://user-images.githubusercontent.com/20604032/181225277-c6d3c354-e56f-4610-b72d-1bcb41383674.png)
and add a hairpin (again, either way), it ends before the last note:
![image](https://user-images.githubusercontent.com/20604032/181225425-fb15ad72-f62d-4c7d-8604-f158afa86a91.png)

Since the behavoiur in MU3.6 is the same I wonder whether this is by design, but I'm not sure why.

I just realised this is probably the same issue as reported in #12558, effectively.

**Comment by HemantAntony** [comment]
Oh thanks for the workaround. I'm working on something related

Since this is already reported, I'll close this issue

**Comment by Tantacrul** [comment]
One of the things most in need to improvement for 4.x is how to place, change and move dynamics and hairpins. It's on our shortlist, for sure.

**Comment by MarcSabatella** [comment]
I don't think it was by design, exactly, that range selections yield different results than selecting start and end points individually - more an accident of how the code works.  Range selections include the total duration of the last selected note, so all the way up to the next note.

When you consider the possibility of a range consisting of a single note (eg, a measure with a whole note), you realize it definitely has to be that way for ranges - the hairpin needs to extend to the end of the last note of the selection.  Only question is whether the separate start/end selection case should be made to match.

The main use case for selecting start and end notes separately - this wouldn't be a normal thing to try - would be to create lines that cross voices in a way that a range selection can't quite capture.  For example, this:

![image](https://user-images.githubusercontent.com/1799936/181259344-4e5c02da-d342-460a-bd70-6873b8e7a326.png)

You can't select exactly that using range selections, but you can by Ctrl+clicking the C on beat 2 and A on beat 4.

If the code were changed to be more consistent with how range selections work, I'm not sure this result would be possible, except by first adding the hairpin incorrectly then adjusting it.  Perhaps not a huge loss, but anyhow, I think that's the tradeoff.

**Comment by HemantAntony** [comment]
Maybe you can just adjust the algorithm which determines the length of the hairpin. Isn't that the "proper" way?

**Comment by martin-danhier** [comment]
It does seems intentional in the code:

https://github.com/musescore/MuseScore/blob/4c6a7f3f708715a463d57f31d222807963d19a97/src/engraving/libmscore/edit.cpp#L1955-L1988

If two chords/rests are selected on the same staff, then the last chord is exclusive, and in other cases (ranges, or only 1 chord selected) it is inclusive. Setting the parameter to "true" would consider it inclusive every time:

![image](https://user-images.githubusercontent.com/36641081/181359184-b084fa48-3f14-488b-b588-d711bcf9596b.png)
![image](https://user-images.githubusercontent.com/36641081/181359261-232132aa-2b64-43a6-978b-d3eea7b85282.png)

Also, since it is caused by a function specific to hairpins, I don't think it is the same issue as the one for text lines, although the reasoning behing the code might be similar :thinking:
