### ISSUE TITLE
[MU4 Issue] Buttons on the right side of drop-downs are overlapped by scroll bar

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12602]
**Describe the bug**
The issue relates to Palettes and Add Palette first and a bit to rest of windows in Inspector

**To Reproduce**
1. Open/create any score
2. Set the MU4 app window size to get scroll bars Palettes
3. Open Add Palettes and scroll 

**Expected behavior**
Buttons on the right side of drop-downs are not overlapped by scroll bar

**Screenshots**
<img width="1181" alt="Знімок екрана 2022-07-29 о 18 42 18" src="https://user-images.githubusercontent.com/101250347/181797791-4fd4bd8a-daf4-487c-b1b7-bcc1859b4a64.png">

**Comment by jessjwilliamson** [comment]
@cbjeukendrup Can the scrollbar be moved more to the right side next to the plus buttons? like this? 
![image](https://user-images.githubusercontent.com/71656189/187905165-dbde8367-33b7-4ba1-8198-d809f27b94cd.png)
Also I realised currently it's 8 pixels width and not 6 pixels
I made a general guideline about the types of scrollbars here:
![image](https://user-images.githubusercontent.com/71656189/187905382-e2b2e58b-686f-4639-b5c3-f68c4db00758.png)

I think we need to review all of the scroll bars in the entire app because there are 8 pixel and 6 pixel width versions in wrong places and some just don't look right. Let me know when and how we can review them :)
