### ISSUE TITLE
[MU4 Issue] AppImage desktop file has wrong Name, leading to missing icon

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12600]
**Describe the bug**
If you install the AppImage (via the install option), then run from the command line, the window manager is unable to match the process to the desktop file, leading to a missing icon

**To Reproduce**
1. run the AppImage from the command line with the "install" option
2. run the AppImage from the command line again, without the "install" option
3. look at your taskbar, or whatever your window manager provides to show icons for your running programs

**Result**
Unless your window manager is doing some special magic to try to find the right desktop file, you'll see only a generic icon for MuseScore 4, not the actual MuseScore icon

**Expected behavior**
MuseScore icon should appear on the taskbar

**Screenshots**
Here's what I see - the icon to right is what represents MuseScore 4 for me:
![image](https://user-images.githubusercontent.com/1799936/181789981-3bcb0ab4-6d02-4e42-9a3b-5c7e157fb6d2.png)

**Platform information**
 - OS: Linux - debian, running within ChromeOS (but presumably similar issues exist for other window managers)

**Additional context**
This issue is fixed simply by changing the Name field in the desktop file to be what the application actually registers itself as on startup: MuseScore4Development at the moment, presumably it will be other things for milestone releases.

**Comment by HemantAntony** [comment]
Something related, on my Ubuntu, when I build MuseScore, it does not show up with an icon. However, since then I have installed MuseScore 2.0 (`sudo apt install musescore`). Now the icon for MU4 becomes MU2's icon. I have only tested this with compiled builds

**Comment by MarcSabatella** [comment]
As per https://musescore.org/en/node/316255, this is definitely a more widespread issue.  An important but trivially simple fix for anyone who knows how the AppImage packaging process works - just get the "Name" field right.

**Comment by shoogle** [comment]
I'm afraid I can't reproduce this as my desktop environment (GNOME) on Ubuntu 20.04 seems to be clever enough to pair the process with the .desktop file, even when run from the command line (perhaps it looks at the Exec line of the .desktop file to get the binary location?).

Anyway, I would rather change the process name to match the `Name` field in the .desktop file rather than the other way around. If the Name field in the .desktop file was changed to a fixed string like "MuseScore" then you could only have one version of the app installed at a time because only one version would show up in your OS's application launcher. Version numbers and a "-portable" or "-portable-nightly" suffix were appended to the Name in MuseScore 3; so that different versions and build types would show up separately in the app launcher.

But it might not be necessary to change the process name. See #13654 for another possible solution.
