### ISSUE TITLE
[MU4 Issue] Some text strings in toolbar are using incorrect data

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12608]
**Describe the bug**
I suspect that since #12414 was merged, some of the text strings in the UI are now using data from `proposed new description (used in preferences)` instead of `Description.` (Referring here to the MScore Actions spreadsheet @VanSHOE @shoogle).  

The idea behind #12414 was to change only the action titles in the preferences dialog, not elsewhere in the UI. 

This problem can be seen, for example, in the playback settings menu (current nightly) (E.g. "toggle enable MIDI input"):

<img width="267" alt="Screenshot 2022-07-30 at 9 58 04 am" src="https://user-images.githubusercontent.com/86290556/181861726-5c021bc5-35b2-4021-b40d-fe9ad160bb93.png">

This menu should look like this:

<img width="286" alt="Screenshot 2022-07-30 at 9 58 51 am" src="https://user-images.githubusercontent.com/86290556/181861760-4d26f5d5-32a4-40e0-b9d8-d54b941420e6.png">

Tooltips have also been affected. For example, "Manage parts" now reads as "Parts...", which is less useful as a tooltip. 

**Expected behavior**
Tooltips and text labels in the UI should retain their data from `Description` instead of `Proposed new description (used in preferences`)

**Platform information**
 - MacOS 12.3.1

**Additional context**
Flagging as priority because this should be addressed before string freeze

**Comment by cbjeukendrup** [comment]
This is why I had doubts about using the description in #12414. It means that all tooltips in the playback toolbar, the note input bar and the parts/mixer toolbar now use the same text as in Preferences, which is often not desirable. 

So I think each action needs up to three things:
1. Every action that can have a shortcut must have a _name_, that is used in Preferences. (So that would be what's currently called `description` since #12414.)
2. Every action that is exposed in a menu or toolbar must additionally have a _title_, that is displayed in the menu or used by screen readers and for the tooltip title. (So that's what's currently already called title.)
(Actions that are never exposed in a menu or toolbar should preferably _not_ have such a title, to reduce the amount of unnecessary translatable strings. That means probably that we should remove quite a few existing titles.)
3. Some of the UI-exposed actions may additionally have a _description_. This may be used as extra screen reader info and as the second line in a tooltip, to give the user some extra hint about potentially non-obvious actions. (So this should generally be the `description` as it was before #12414, but in most cases just empty.)

(That means that the UiAction class needs 3 constructor overloads to account for the cases `name` / `name+title` / `name+title+description`, and of course maybe a few more to account for `icon` / `no icon` and `checkable` / `not checkable`.)

(I'm not particularly confident about the terminology `name` / `title` / `description`; better suggestions about this are welcome!)

@VanSHOE Maybe you have input about this too. If we decide that the above is a good plan, then you could maybe use an adjusted version of your script to help realizing this plan.

**Comment by shoogle** [comment]
I was also aware that we were going to clobber the tooltips with #12414, but I could only find very few cases (about 10 out of 500) where the tooltip was meaningfully different to the name in Preferences. I figured we could just add those tooltips back as an extra parameter, but keep using the description for the rest.

I didn't notice that that the playback setting menu used descriptions though. Maybe that should be using titles anyway?

**Comment by cbjeukendrup** [comment]
About the playback settings menu, in that case it was intentional to use the description, because at that time the action description matched the design more closely than the title, and for some reason we couldn't simply change the title (probably because back then the title was also used in Preferences). But now we should change it to use the title, and I don't see anything anymore that prevents us from updating the title.

**Comment by bkunda** [comment]
@cbjeukendrup @shoogle That playback settings menu is definitely the priority here, and if we can correct the tooltips then that's good too. Let me know if I need to make any changes to the spreadsheet.

**Comment by VanSHOE** [comment]
Sure I can work on this! Please let me know what the final decision is. Should I make another parameter for the old descriptions or should I change the tooltips to read from titles?

**Comment by shoogle** [comment]
@VanSHOE, thanks! Don't change the tooltips for now. I'll go through the old descriptions with @bkunda next week to pick out the few tooltips we want to save and then you can create a new optional parameter for just those ones. The rest of the tooltips will continue to use the preferences string.

For now, please just find where the [Playback Settings menu](https://user-images.githubusercontent.com/86290556/181861726-5c021bc5-35b2-4021-b40d-fe9ad160bb93.png) is created and have it display titles instead of descriptions. Also change the title strings in playbackuiactions.cpp to look like [this](https://user-images.githubusercontent.com/86290556/181861760-4d26f5d5-32a4-40e0-b9d8-d54b941420e6.png) (don't change the descriptions). @bkunda, should `Enable 'MIDI input'` just be `Enable MIDI input` now (i.e. no quotes around `MIDI input`)?

**Comment by VanSHOE** [comment]
@shoogle Please have a look at https://github.com/VanSHOE/MuseScore/commit/a485401a9ac2ed0419c0d5426a9b92a91c8e6cf6

**Comment by shoogle** [comment]
@VanSHOE, looks good! Please submit a PR. We won't merge until we've heard from @bkunda though.

**Comment by bkunda** [comment]
Just checked this on MacOS. Looks like it's back on track 👍🏻
Thanks @VanSHOE for jumping on this so quickly.
And yes @shoogle I think we should lose the quotation marks, so it should just be `Enable MIDI input`.
