### ISSUE TITLE
[MU4 Issue] Melisma is not created when `Shift`+`-` is pressed once

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12601]
**To Reproduce**
1. Create a score with a few notes
2. Go to Lyrics mode
3. Add a symbol to the first note 
4. Then press `Shift`+`-` (no melisma created after the first note

Melisma is created only after pressing `Shift`+`-` second time

**Expected behavior**
Melisma is created when `Shift`+`-`  is pressed once

**Screenshots**

https://user-images.githubusercontent.com/101250347/181793602-24e9574c-c5ea-4c0c-bf94-0494e558fd9b.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by cbjeukendrup** [comment]
Wasn't this on purpose because we hide melismas that are too short? (@oktophonie?)
(After pressing Shift+- a second time, the melisma is extended so that it becomes long enough to become visible.)

**Comment by wizofaus** [comment]
If someone can confirm this is different to v3 behaviour and the "what's expected" is definitely what's wanted, I'll have a look as I did a fair bit of the work on ensuring keyboard addition of melisma worked as expected (I even made some changes to the rendering, as there was a scaling bug at one point).

**Comment by Jojo-Schmitz** [comment]
Same in 3.x, `_` needs to be used twice to cover the next note.

**Comment by boryskuzmenko** [comment]
> Wasn't this on purpose because we hide melismas that are too short? (@oktophonie?)
> (After pressing Shift+- a second time, the melisma is extended so that it becomes long enough to become visible.)

If so it would be shown after increasing space between the notes. But it doesn't work like this

**Comment by boryskuzmenko** [comment]
> Also what do you mean by adding a "symbol"

I mean any letter/character just to start from

Also, your case with repeats is a different story and looks like edge case. But I'll report it for future

**Comment by boryskuzmenko** [comment]
> Same in 3.x (and 2.x and 1.x, so ever since), `_` needs to be used twice to cover the next note. The first press 'just' right-aligns the syllable (and may give a very short melisma, depending on space)

Actually, it works by using '_' once in MU3 for me. And behavior you described is like in MU4 now :)

**Comment by wizofaus** [comment]
How does it show in v3 though? I can't think of a case I'd expect to see a letter and a melisma on a single note (that doesn't extend to the next note).

**Comment by MarcSabatella** [comment]
Indeed, MuseScore 3 always shows a very short melisma line on the first press of underscore.  MuseScore 4 shows nothing, making the command look broken.

As far as I can see, a melisma of just a single note is nonsensical; it won’t occur in a finished score.  It only happens temporarily while preparing to enter a second underscore.  We should probably force the display of a nominal-length melisma for melismas off only a single note.  I think that’s actually how MU3 did it.  Just so people do t think the command is broken.

An alternative, BTW, is to try to do people a favor and make the first press of underscore actually act as if you had pressed it twice. , and extend the underscore all the way to the next note and move the cursor forward.  Sounds strangely illogical when I say it like that, but it’s actually a fairly common request, as it does seem odd you always have to press underscore twice to get started.

**Comment by boryskuzmenko** [comment]
> An alternative, BTW, is to try to do people a favor and make the first press of underscore actually act as if you had pressed it twice. , and extend the underscore all the way to the next note and move the cursor forward. Sounds strangely illogical when I say it like that, but it’s actually a fairly common request, as it does seem odd you always have to press underscore twice to get started.

For me it make a bigger sense as implemented in MU3. I also checked how it works in Sibelius. They don't have specific shortcut for melisma and it automatically applies after second space click (same as doubled click '_' in MU). And to skip melisma you should use shft+space. Thats more weird for me. 
So, I'd go with last Mark's propose.
@oktophonie please visit this thread :)

**Comment by boryskuzmenko** [comment]
> How does it show in v3 though? I can't think of a case I'd expect to see a letter and a melisma on a single note (that doesn't extend to the next note).

It's not about real case, it's about visual confirmation that you use specific shortcut. But, as I mentioned above, I'd even improve this as Mark described. At least leave as implemented in MU3. 
Anyway, I think there's too much discussion around this minor thing :)

**Comment by Tantacrul** [comment]
> > An alternative, BTW, is to try to do people a favor and make the first press of underscore actually act as if you had pressed it twice. , and extend the underscore all the way to the next note and move the cursor forward. Sounds strangely illogical when I say it like that, but it’s actually a fairly common request, as it does seem odd you always have to press underscore twice to get started.
> 

I also would like to know @oktophonie's opinion on this :)

In part, it's an interaction question. Marc's idea makes sense to me, although there may be cases where it isn't desirable. I'm a bit too distracted at present to delve too deeply!

**Comment by wizofaus** [comment]
As long as there's a way to just add a regular underscore without indicating you want a melisma, I think that makes sense too.  Currently I think you can only do it using copy & paste.  There's not exactly a lot of cases you'd actually want a real underscore in music lyrics, but if you're the sort of person that links setting C++ code to music who knows...

**Comment by MarcSabatella** [comment]
Underscores within syllable are entered with Ctrl+_, similarly to how you enter hyphens and spaces within syllables.  That doesn’t really have any bearing on this, which is let about real underscores but is about melismas-that-aren’t-melismas.

**Comment by oktophonie** [comment]
A summary and my thoughts (for what they may be worth):

Having typed a syllable under a note, one moves to the next note in any of three ways:

- pressing space (to start a new word on the next note)
- pressing hyphen (to create dashes to the next syllable)
- pressing underscore (to create a melisma line)

The difference between dashes and melisma lines is that dashes go all the way to the next text, whereas melisma lines only go to the end of the right hand side of the note _before_ the next text. Meaning, in effect, that a melisma line is (almost) never necessary unless it spans more than one note.

From an interaction point of view it makes sense - to me, at least - that these three keys behave consistently, in that they each move you to the next note, rather than underscore behaving differently and moving you two notes. It would also make the (admittedly rare) cases where you want a 'one-note melisma' difficult or impossible.

In MU3 a short melisma line would be shown after the initial syllable upon the first underscore keypress. In MU4, no melisma line is shown after the first keypress, because (as Casper said) we now hide them when they are below a certain length. (And to answer Borys' point: increasing the distance between notes has no effect here, because the line is not meant to extend to the next note at that point.) I stand by that change, as these tiny melisma lines cause all kinds of spacing issues and graphical ugliness, but I agree that the current behaviour is confusing. It is strange to press the 'melisma key' and have no melisma line appear on screen. (There is _some_ visual feedback, as Jojo points out, since the syllable will become left-aligned rather than centred.)

To me, the most natural thing would be for a single press of underscore to move the cursor to the next note (as happens already), but also to _draw a melisma line up to the right hand side of that note_. Subsequent presses of underscore will continue to advance both cursor and line to the next note. Whenever the user types text, though, the melisma line then recedes to end on the _prior_ note (whereupon, if it's too short, or if that was also the note on which it began, it will disappear.)

This means that cases like the following:

![image](https://user-images.githubusercontent.com/20604032/187203036-2fe721a9-81ce-4702-8362-2aa7011a0cea.png)

would be input simply by typing "moist_" (without requiring a second underscore).

---

Postscript:

There are some rare cases where the melisma line should go _up to_ the next note (not stopping on the previous one). This might happen if you want to indicate a sung syllable switching to a hummed (or other nasal etc sound) on a subsequent note, or to indicate the rearticulation of a vowel during a melisma, e.g.:

![image](https://user-images.githubusercontent.com/20604032/187188638-50cd26af-ef8b-4e39-9271-8a3ac10a7059.png)

![image](https://user-images.githubusercontent.com/20604032/187188661-5f1a5b2e-fb8b-4f0c-9422-63f26ff523ac.png)

(Apologies for taking photographs of a computer monitor, a very odd thing to do.)

Melisma lines cannot be independently edited at the moment in MuseScore, but in any case I feel it would be better in future to implement these as options on the text syllable itself ("Never hide melisma line", "Extend line up to next note" and similar).

**Comment by Yannick76** [comment]
With my version of MuseScore 4.0.0 revision: 7fffffff, I am not able to insert a Melisma in any lyrics, I am using a french keyboard. I followed exactly the same steps as in MuseScore 3.6.2.

**Comment by abariska** [comment]
@Yannick76 Only ENG keyboard shortcuts are supported for now in MU4
Is it work correct when using ENG keyboard language?

**Comment by Yannick76** [comment]
@abariska as soon as I switched to ENG keyboard I was able to insert a Melisma in my lyrics. This makes it difficult for me to start using version 4.0 of MuseScore. I guess that the solution would be to switch keyboards when correcting my lyrics. :)
Thanks for your input.

**Comment by Jojo-Schmitz** [comment]
This issue is a show stopper for me. Along with the numpad shortuts issue and a few others

**Comment by Tantacrul** [comment]
> This issue is a show stopper for me. Along with the numpad shortuts issue and a few others

I've asked our guys to look at the numpad issue in particular. This one needs a little agreement with @oktophonie and I. I also want to do a little looking around to see how this is handled by other apps too.
