### ISSUE TITLE
[MU4 Issue] Some dialogs require minor tweaks to UI copy

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12630]
**Describe the bug**
These dialogs require minor tweaks to the UI copy before string freeze: 

1. Getting started dialog > Close dialog (when user attempts to close the "Getting Started" dialog)
**_Current_**
<img width="751" alt="Screenshot 2022-08-01 at 6 35 19 pm" src="https://user-images.githubusercontent.com/86290556/182157284-a70246d3-026d-45b5-8a4c-f656dcda374b.png">

_**Expected**_
<img width="656" alt="Screenshot 2022-08-01 at 11 23 52 pm" src="https://user-images.githubusercontent.com/86290556/182157769-3fae7f01-ec0d-4d02-a677-43358589004d.png">

2. Alert dialog when entering text object without correct selection. 
_**Current**_
<img width="525" alt="Screenshot 2022-08-01 at 11 25 15 pm" src="https://user-images.githubusercontent.com/86290556/182158040-c9698e6c-4a2c-40df-8076-42006183aea5.png">

**_Expected_** (UI issue only)
<img width="475" alt="Screenshot 2022-08-01 at 11 25 24 pm" src="https://user-images.githubusercontent.com/86290556/182158079-494423ae-be77-4cd3-9c17-c72630b39299.png">

...and the same for issue 3:
3. Alert dialog when entering figured bass text object without correct selection4. 
**_Current_**
<img width="524" alt="Screenshot 2022-08-01 at 11 26 27 pm" src="https://user-images.githubusercontent.com/86290556/182158302-11ab0169-8d91-4aaf-b0e2-4a79a0b41023.png">

**_Expected_**
<img width="475" alt="Screenshot 2022-08-01 at 11 27 08 pm" src="https://user-images.githubusercontent.com/86290556/182158398-0d188dda-42d1-4049-9e18-b47f99655ee9.png">

**Platform information**
 - MacOS 12.3.1 
 
**Additional context**

**Comment by cbjeukendrup** [comment]
@bkunda Due to the way we currently put the text on those dialogs, we can have only a title in bold font. We'll fix it properly later, but for now I rushed in a quick fix so that the translatable strings will already be correct, and then we can fix the presentation later.
<img width="637" alt="Schermafbeelding 2022-08-01 om 16 20 28" src="https://user-images.githubusercontent.com/48658420/182168768-75909419-7c5c-4b44-b9bd-8ea357b0e1f3.png">
