### ISSUE TITLE
[MU4 Issue][macOS] Chords cursor is not moved to the previous beat by clicking shortcut ' : ' (Shft+;)

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12632]
**To Reproduce**
1. Create a simple score
2. Enable Chords input
3. Use shortcut `;` to move cursor to the next beat
4. Try to use shortcut `Shift`+`;` to move cursor to the previous beat

**Expected behavior**
Chords cursor is moved to the previous beat by clicking shortcut ' : '

**Screenshots**
![Capture 2022-08-01_05-39-32_PM](https://user-images.githubusercontent.com/101250347/182174988-dd5eecd2-e1e4-4990-8c4c-9e95d6f9bb2e.png)

**Platform information**
 - OS: macOS only

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/10745.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12654
Tested on macOS 12

**Comment by Jojo-Schmitz** [comment]
on a German keyboard `Shift` is needed to get the `;`

**Comment by boryskuzmenko** [comment]
@Jojo-Schmitz For now only English keyboard layout is covered. Another languages will be covered in future

**Comment by Jojo-Schmitz** [comment]
If you want `:` just use that. (It needs `Shift`on a German keyboard too

**Comment by cbjeukendrup** [comment]
It looks like MU4's keyboard shortcuts system has become key-based, where MU3 (like Qt itself) was character-based. This has advantages and disadvantages; advantage is that shortcuts still work if your "software" keyboard layout differs from your "hardware" keyboard layout (for example, when typing Cyrillic characters using a US keyboard). Disadvantage is that keyboard shortcuts are not portable anymore between different "physical" keyboard layouts, like we're experiencing here: on certain keyboard layouts, a character has its own key, on others, it must be accessed via some other key using Shift. Because we now need to specify the physical combination of keys, we must do so for all possible keyboard layouts separately.

**Comment by boryskuzmenko** [comment]
You right, @cbjeukendrup 
Now our priority is Alpha2, so we will be solving this after

**Comment by Eism** [comment]
At the moment, the solution is implemented only for macOS. 
Tests have shown that the solution is good, but if there are real problems, we will think about how to fix them. The decision is not final, we need feedback.

The main idea is that the user does not have to worry about what keyboard layout he currently has.
For example, I often change the layout from Russian to English and when I try to enter Ctrl+Shift+F in QtCreator in the Russian layout, nothing happens and it really annoys me.

This approach is planned to be implemented for both Windows and Linux If there are no problems with the solution on macOS
