### ISSUE TITLE
The title frame should not scale with general staff size

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#12685]
(I've been meaning to post this for a while, please let me know if it's a duplicate. Also, it isn't really a MU4 issue, this seems to be identical in 3.6. Probably not a priority atm, just a bit of clumsiness. @oktophonie @Tantacrul )

**Describe the bug**
The title frame should not scale with staff size, otherwise text placement is messed up and the music can end up colliding with the title (see video). Consider that, since [this PR](https://github.com/musescore/MuseScore/pull/11898), staff size reduction may also happen at score creation, which means the user is directly presented with a messed up first page. Not ideal. (Maybe the solution is as simple as using a text frame - rather than a vertical frame - to create the title? Those don't scale with staff size, if I'm not mistaken.)

**To Reproduce**
1. Create a score.
2. Reduce staff size from page settings.

**Expected behavior**
I think the title frame should retain the original size regardless of document staff size.

**Video**

https://user-images.githubusercontent.com/93707756/183033514-c2de38d6-167f-4601-ad81-bfd2b9ad8221.mp4

**Comment by mike-spa** [comment]
Here's an example of recreating the title using text frames instead of vertical frames. I think this is closer to the expected behavior.

https://user-images.githubusercontent.com/93707756/183044683-fe59f307-6013-43a2-b158-4100ec586f6c.mp4

**Comment by HemantAntony** [comment]
From what I remember from working on frames, the title frame is an Horizontal frame whose parent is the first measure. This could explain why this behaviour occurs. Maybe someone can use this as a clue?

**Comment by Tantacrul** [comment]
Bumping this to 4.x unless someone disagrees.

**Comment by MarcSabatella** [comment]
Although it's true in 3.6.2 also, I just realized it's rather more annoying in MU4 because by default there is a subtitle, thus guaranteeing it will stick out below the frame.  With no subtitle, it's not obviously bad that the frame resizes.

The title frame is not a horizontal frame; it's a vertical frame.  And it doesn't have the first measure as a parent; it's place *before* the first measure in the list of MeasureBases (frames and measures share the same MeasureBase base class).

FWIW, using a text frame for title info is not an option because they can contain only a single text element.  Also, vertical frames containing ordinary (scaling) text probably *should* scale with spatium.  But frames containing non-scaling text like titles should not.  And what if there is a mix of scaling and non-scaling texts in the same frame?  I'm not sure it makes sense to try to sort that out.  I propose there simply be a new "Match staff size" property on vertical frames like there is for text.  This should be set false normally but set true on the automatically-generated title frame.  That will be the correct behavior most of the time, and the user can override when it isn't.
