### ISSUE TITLE
[MU4 Issue] Stem direction in Properties does not always enable/disable as expected

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#12720]
**Describe the bug**
It appears that stem direction is meant to be disabled (greyed out) for notes that don't have a stem (whole notes, breves, etc.):

![image](https://user-images.githubusercontent.com/20604032/183382012-e7b7ffdc-0e55-4004-88ef-feeef5feceb2.png)

However, the enabled/disabled state does not always seem to update correctly as items are selected.

**To Reproduce**
Steps to reproduce the behaviour:

First select a note which has a stem, and open Note -> Stem in the properties panel:

![image](https://user-images.githubusercontent.com/20604032/183382273-abdf9543-a982-4b34-8619-a53016680515.png)

The stem direction options are available, as expected.
Now, select another note which doesn't have a stem:

![image](https://user-images.githubusercontent.com/20604032/183382424-b94dbcaa-448b-44ab-a777-774d17ff9f4c.png)

Note that the enabled state of these options does not update.

**Expected behaviour*
The enabled/disabled state of the options should always reflect the selected item.

(PS. I could have sworn I reported a very similar version of this issue with a different setting in the properties panel, but now can neither find it not recall which setting it was. It may be that some other options in the Properties panel exhibit the same faulty behaviour, anyhow.)

**Comment by MarcSabatella** [comment]
FWIW, I won't claim this is crucial functionality, but - the stem direction setting does - or did in MuseScore 3, anyhow - have an effect even on whole notes, because it would influence which notes in other voices the whole note would be aligned with.  For instance, in the following example, the first measure has the whole note "stem up", the second "stem down":

![image](https://user-images.githubusercontent.com/1799936/183424923-ef93ccea-ff13-4242-8ca5-fe61890ce7cf.png)

I think there were a few other subtle effects here and there.  Anyhow, I'd just say, it could be worth considering not disabling this setting.

**Comment by oktophonie** [comment]
I quite agree. (Fortunately one can still flip with the keyboard shortcut/toolbar button.) The nominal stem direction of a stemless note does have various implications even if there is no visible stem; so, maybe having this be always enabled is actually the simplest solution to the problem.

**Comment by Tantacrul** [comment]
Glad we came to an agreement. Let us potentially return to this in the future!
