### ISSUE TITLE
[MU4 Issue] slurs should be less curved

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#12741]
The slurs should be less curved I think.....
Windows platform

**Comment by MarcSabatella** [comment]
Can you attach your score and say which slurs specifically you feel should be less curved?

**Comment by mart661331** [comment]
![Slurs 2022-08-09 180228](https://user-images.githubusercontent.com/110895947/183702016-574c828e-1ea3-41d6-8c77-c7cb4e1d6b6c.png)
The middle one is the default one, Too curved for me. it is not quiet to the eyes....

**Comment by HemantAntony** [comment]
If you feel like its curved, you can manually adjust it by first clicking on the slur. Then you have to drag a node

**Comment by mart661331** [comment]
Yes i did.
600 times....

In printed scores also not so curved.

I am not  the only one with this wish.

..
Martin van Noord
Netherlands



Op di 9 aug. 2022 18:11 schreef Hemant Antony ***@***.***>:

**Comment by HemantAntony** [comment]
@oktophonie ?

**Comment by mart661331** [comment]
Maybe make it adjustable in preferences...

Greetz

Op di 9 aug. 2022 18:11 schreef Hemant Antony ***@***.***>:

**Comment by mart661331** [comment]
??

Op di 9 aug. 2022 18:17 schreef Hemant Antony ***@***.***>:

**Comment by oktophonie** [comment]
!!
He tagged me because I'm theoretically in charge of engraving issues.

I agree that slurs which are level are a bit too curved (this can feel especially so when at the beam side, as in the illustration). We did experiment at one point with incorporating the vertical difference in endpoints into the curvature calculation (so that 'flat' slurs would be less tall, basically) to achieve this but were not happy with the results at the time. However, we do plan to look at this again before release, and refine it in a manner which will specifically address the exact issue you have brought up here.

**Comment by mart661331** [comment]
Thanks!

Op wo 10 aug. 2022 10:44 schreef Simon Smith ***@***.***>:
