### ISSUE TITLE
[MU4 Issue] Some common palletes are missing by default (Lines, Grace notes, Beam properties)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12746]
**Describe the bug**
When you start MuseScore at the first time some important palettes not enabled (comparing with MU3) - **Lines**, **Brace**, not sure about **Beam properties**

![Capture](https://user-images.githubusercontent.com/90187801/183658102-1fcefd64-75cb-438c-adc4-e45331728fb2.PNG)

**To Reproduce**
1. To repro just trigger **Revert to factory settings**

**Platform information**
macOS, Windows, Linux

**Additional context**

**Comment by oktophonie** [comment]
I'm fairly sure this is deliberate. Many of the palettes have been hidden in the default initial view to simplify the UI (and to encourage exploration of the 'Add Palettes' popup!)

**Comment by MarcSabatella** [comment]
Indeed, see https://github.com/musescore/MuseScore/issues/11057 - it's deliberate for now that the default workspace is pretty bare.  But as per comments there, the door is open for some additional workspaces, which I'd definitely like to see, as I think the amount of work required to not only add but also sensibly order palettes - and make things consistent across multiple systems you might use - seems to be underestimated.

As for the actual defaults in MU4, I might argue Lines is not so crucial now that its most important content can be found elsewhere (eg, hairpins under Dynamics, voltas under Repeats).  In theory, Brackets isn't important for the default workspace since most of that is now handled automatically (and could have been dropped from Basic in MU3 also once the automatic facility was added). 
 Beam properties is *deifnitely* not needed, probably can and should be removed entirely now in fact, since its functionality is reproduced in Properties.

If I were to add anything to the default set, it would be Grace Notes and possibly Ornaments.

**Comment by DmitryArefiev** [comment]
Sure! If it's by design let's close it now.
