### ISSUE TITLE
[MU4 Issue]MIDI Keyboard coesn't work

### ISSUE THREAD

**Issue by stefanorattini** [musescore/MuseScore#12805]
The MIDI keyboard that worked for years with MS3 seems not to work in MS4

**Platform information**
 - OS: [Windows]

Many thanks

**Comment by DmitryArefiev** [comment]
Hi @stefanorattini, this is probably the same as #10769. Can you check please if MIDI Keyboard works after selecting it in Preferences>I/O>MIDI

Thanks!

**Comment by romainmastro** [comment]
Hi! First, thanks for the astonishing work!! This is amazing!!

I think I'm experiencing the same "issue" as Stefanorattini. I write "issue" between "" because it may work as intended but I couldn't find any details about it so here it is :  My Midi Keyboard (Arturia Keylab 88) is hooked up, I selected it in Preferences>I/O> MIDI. When I enter "Writing mode" the midi input works just fine but when I get out of that mode, I can't hear/ply my instruments. 
Is it working as intended?

Thanks again for the great work!

**Comment by DmitryArefiev** [comment]
> My Midi Keyboard (Arturia Keylab 88) is hooked up, I selected it in Preferences>I/O> MIDI. When I enter "Writing mode" the midi input works just fine but when I get out of that mode, I can't hear/play my instruments even when I select a bar (like I used to do in MS3).
> Is it working as intended?

Hi @romainmastro , the issue your talking about is probably #11234. 
Sound preview doesn't work prefect in MS3 and totally doesn't work in MS4 yet.

Thanks!

**Comment by stefanorattini** [comment]
Many thanks, DmitryArefiev: you have solved my problem! It works well, now! Many thanks for this wonderful new version of MuseScore!

**Comment by DmitryArefiev** [comment]
> Many thanks, DmitryArefiev: you have solved my problem! It works well, now! Many thanks for this wonderful new version of MuseScore!

Cool! Thanks for testing!
