### ISSUE TITLE
[MU4 Issue] Round corners do not match thumbnails in Plugins

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#12818]
The selected state does not match the round corner value to the thumbnail artworks. The states need to be a bit more rounded :)

![image](https://user-images.githubusercontent.com/71656189/184341991-88802362-aa78-44ac-8a93-f5d991b60c95.png)

**Comment by DmitryArefiev** [comment]
Fixed in #12854

**Comment by DmitryArefiev** [comment]
@jessjwilliamson you can recheck in master to make sure I didn't miss anything :)

**Comment by jessjwilliamson** [comment]
The corners seem to have no change

**Comment by cbjeukendrup** [comment]
@jessjwilliamson If you're using nightly builds, you'll need to wait for tomorrow's one.

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson If you're using nightly builds, you'll need to wait for tomorrow's one.

Ah okay thanks I'll check then :)

**Comment by jessjwilliamson** [comment]
It's still not quite there yet.. almost! bit more curve!
![image](https://user-images.githubusercontent.com/71656189/187681034-328da499-d09a-4160-8ab6-c5a72438841b.png)

Ideal is to have it look like this:
![image](https://user-images.githubusercontent.com/71656189/187681349-3cfc7764-a7b3-44b7-9e7f-9caae7d4064e.png)

**Comment by cbjeukendrup** [comment]
I also noticed this, and it appears to be a QML bug/quirk. All numbers are entered correctly, but the radius of the image is slightly larger than specified. Apparently this happens to more people: https://stackoverflow.com/a/47989395 but the solution proposed there didn't seem to work for me.

So the only way might be to specify in QML a few pixels less radius than actually desired, so that it will look good. Code-wise that is a bit ugly, but it looks like we're forced to do something like that.

**Comment by jessjwilliamson** [comment]
Okay, if it's an issue not able to be solved then it's not a massive must-have to do. Thanks Casper! :)
