### ISSUE TITLE
[MU4 Issue] Sound doesn't change after changing channel.

### ISSUE THREAD

**Issue by Offert4324** [musescore/MuseScore#12827]
**Describe the bug**
I'm not sure if it's a feature that's not supported yet, but I couldn't find the related issue, so I'm writing it down here.
In case of string, changing channel into pizzicato/tremolo, or into mute for brass doesn't change their timbre at all.
Moreover, I couldn't even find the option for other channels in the new mixer.

**To Reproduce**
1. Enter note in the input mode
2. Input some notes
3. Press Ctrl+T on any notes and type in anything.
4. Right click the text and go to Staff text property.
5. Choose any voice and change its channel.
6. Click playback.

**Expected behavior**
The sound must change into suitable one.
And the its sound must be changeable in the new mixer.

**Screenshots**

https://user-images.githubusercontent.com/104715700/184370104-401e7ca1-d234-45c5-903b-b45ecff6bfab.mp4

**Platform information**
 - OS: Windows

**Comment by MarcSabatella** [comment]
I don't think it's intended you should have to mess with channels anymore.  Just add the appropriate text from the palette; they are already preconfigured to do the right thing internally.

**Comment by DmitryArefiev** [comment]
@Offert4324 Yes, as Marc mentioned, Change Channel and MIDI Action tabs will be removed from MU4 soon (#12903)

So it should work when using **con sord, pizz** etc. from Palettes. 
Also you can edit the text of pizz e.g.  and it should work after renaming as well (switching to pizz) . 
If it doesn't work in that way please reopen.

**Comment by Jojo-Schmitz** [comment]
How else then is this (supposed to be) working in MU4?

**Comment by Jojo-Schmitz** [comment]
Esp.: How to make these text work only on certain voices, esp. those S/A, T/B, T/L and B/B texts?

**Comment by DmitryArefiev** [comment]
> How else then is this (supposed to be) working in MU4?

Yes, it works for entire staff for now in MU4. I guess that feature (variant of Change Channel tab) will be added later in the next releases.

**Comment by Jojo-Schmitz** [comment]
So yet another feature from MuseScore 3 not available in MuseScore 4.0?
It is a vital feature to me, used for Choir rehearsal...

**Comment by DmitryArefiev** [comment]
> Esp.: How to make these texts work only on certain voices, esp. those S/A, T/B, T/L and B/B texts?

@Jojo-Schmitz But what technique changes are important on Choir scores? (comparing with pizz and arco on Strings staves)

**Comment by cbjeukendrup** [comment]
@DmitryArefiev These channel changes are not only used for playing techniques, but also in general to switch sounds or route different voices to different sounds. This is what those "S/A" texts do:
<img width="1066" alt="Scherm­afbeelding 2022-08-17 om 14 48 13" src="https://user-images.githubusercontent.com/48658420/185133260-27291b32-8eaf-49e9-85f1-ccd7e87ed995.png">

**Comment by Jojo-Schmitz** [comment]
Exactly.

**Comment by DmitryArefiev** [comment]
Oh I see.. Thanks!

**Comment by Jojo-Schmitz** [comment]
Plus (and more important IMHO) the ability to adjust the volume in Mixer separately for Soprano and Alto (in a Closed Score SATB), like to hear the own voice loud the other(s) in the background, for harmonies and context

**Comment by mkj42** [comment]
Resurrecting this and adding my +1 to this closed? / put on hold? issue.
The channel use was immensely important to my MuseScore use.
It is the biggest regression which has kept me to 3.7 Evo in the meantime.

**Comment by cbjeukendrup** [comment]
@mkj42 I agree that losing functionality is bad, but I'm afraid it's unlikely that the "Channels" feature will come back in its MS3 form in MS4.
The reason that I think that, is that it was somewhat difficult to find and understand when you don't know yet how it works. It doesn't fully seem to fit in the MS4 philosophy, of reducing the amount of "concepts" that the user has to understand in order to solve their problem.

It may be more successful to take a step back and try to answer the question: _what problem(s) does this feature solve?_

Then the next question is of course, _what is the best way to solve this problem, from a user experience point of view?_

I think it would be better to open a new feature request, focussing on answering the first question, i.e. on the actual problem that needs to be solved, rather than on the missing old feature. 
Then the second question is mostly for the design team to answer, but suggestions are welcome of course.

**Comment by mkj42** [comment]
@cbjeukendrup 
Thanks for your thoughts on this.
I actually found and replied to this post because I was issue searching while contemplating exactly that, opening a new one.
I have been bemoaning this loss for a while now.
Maybe a new approach is needed. My posts have fallen on reluctant ears in the past; I'm clearly not explaining just how useful this feature was, and how handicapping its absence is.
https://musescore.org/en/node/366507
Slightly less relevant, but I clearly was enjoying this feature for a while now:
https://musescore.org/en/node/278497
https://musescore.org/en/node/278059

I still would like an add channel button, or add track if you will, an arrow which allows you to switch sounds _without_ new clefs or transposition unless wanted, and then collapse them.  Then add a staff text which could switch to it.
This would also fix my issue of not having direct access to pizz, arco, mute sounds anymore; I could just add my own if needed.
I think I just need to stop referring to it as a 'channel' and come up with a new term for it. 😉 

If you have any further thoughts, I'm all ears.
Thanks

**Comment by cbjeukendrup** [comment]
So what you want to do, is switching specific sounds to different sounds, mid-score, is that accurate? 
In that case, this feature request could be phrased as an extension for "sound flags", that we have for Muse Sounds. These let you do exactly that, but in a limited way, because you can only switch between sound variations within one sound. But what you presumably need, is the ability to switch between different presets in a sound font, and perhaps even between different sound fonts, right?

**Comment by mkj42** [comment]
Precisely, preferably from any soundfont.
I haven't dove into MuseSounds yet, so I've heard of but am not super-familiar with sound flags.
This might be a first step on the path.

**Comment by mkj42** [comment]
How about this?
https://github.com/musescore/MuseScore/issues/22714
Close enough? or is any tweaking required?

**Comment by cbjeukendrup** [comment]
@mkj42 Your comment there looks good. You might want to edit it once more to tell about your use case for mid-score sound changes. The obvious use case in MS3 was pizz./arco/open/mute, but for those things we now have dedicated text elements in MS4. So it would be good to know why else a mid-score sound change may still be useful. Of course, we can think of cases ourselves, but adding your specific case may be helpful.

One thing that I can think of myself, is that the new pizz/arco/etc texts may not always work with custom sound fonts (as opposed to MS Basic). They trigger specific banks/presets numbers, that work well with MS Basic, but cannot be customised, so won't work with custom sound fonts that have a custom layout.

If that does indeed describe why MS4's pizz/arco/etc texts are not useful in your case, you could open a new feature request, asking to make the playback effects (i.e. which bank/preset gets selected) of these texts customisable per sound font.

**Comment by mkj42** [comment]
@cbjeukendrup 
Actually, I was asking if the issue was close enough, or if I needed to open my own - would it get flagged and closed for being a near duplicate?

I will think about editing or posting again.  I don't want to flat out threadjack the OP's original issue.

My main dream:
Enter editable text which then can be set to insert any sound from any soundfont into a hopefully collapsible mixer channel with full control.
The better pizz/arco/etc. access is merely a side benefit to me.

**Comment by MarcSabatella** [comment]
That’s basically what an instrument change does already, except for the collapsibility of the mixer channel.  But at least they are reused where possible and don’t proliferate as they used to.

So really, I think the only thing you describe that needs anything new is the collapsibility of mixer channels.

**Comment by mkj42** [comment]
No it isn't.
I want no clef change, or transposition unless I ask for it, no sign anything heppened but the text.
They are not the same.
I wish you could understand this.

**Comment by MarcSabatella** [comment]
I don't understand because a) I dont' recall you explaining that before, and b) it's already the case that you won't get clef or transposition changes unless you choose an instrument that actually requires a different clef or transposition.  As long as you change to an instrument that in real life uses the same clef and transposition, there will be no change shown.  And if the instrument in real like uses a different clef and transposition, then it's normally pretty imperative to show that if you want the music to be playavkle.

Perhaps - although you haven't explicitly stated this here - you aren't writing for "real" instruments at all, but intend the score to be read by a synthesizer player instead?  In that case, it's true you don't want to show transpositions.  So that's fine, just choose an instrument that uses the same clef & transposition as the instrument you are starting with.  So for example, if you are writing not for "real" instruments but are just wanting a "patch change" on a synthesizer, just choose another synthesizer instrument.  Or you could choose clarinet (for example) then alter its transposition in staff/part properties.  Or just show the score in concert pitch.  As far as I can tell, there are lots of ways of doing this already without inventing a new one.

If there is something I'm missing here and for reason I am not understanding, instrument changes to appropriate instrument tsruly won't work for reasons as yet not explained, best to start a new thread on the forums at musescore.org and describe your use case in more detail.  Then perhaps you and other users can find a consensus on what is actually needed above and beyond what is already provided, plus perhaps the slight enhancement of collapsible channels, and you can start a new issue with the use case and proposal explained in more detail - ideally with relevant examples.

**Comment by mkj42** [comment]
@MarcSabatella 

Here is our most recent exchange, from all of 6-11 days ago:
https://musescore.org/en/node/366507
I know you react to literally everyone it seems, but I do get tired of re-explaining my situation if you sincerely don't remember our exchanges.

Heck, you even started this one:
https://musescore.org/en/node/278497
It seems you might have once been on my side on this.

Unlike you I don't feel 4.x has been a panacea - quite the opposite in fact.
It's only since 4.3.2 I've even started exploring it.
Finally it's somewhat tolerable with guitar bends, tab, and individual non-MS soundfont choices.
Right now, MS literally wrecks even previous MuseScore General sound by ditching the previous FluidSynth.
Seriously, even the old soundfont sounds flat out bad.
For now, I'll stick with 3.7 primarily until 4 gets better still.
I really don't enjoy being told repeatedly that the new way is great, and if I just get used to it, all will be fine.
I stopped using instrument changes ages ago and have no plan to go back.

Also, hiding the pizz and tremolo presets etc. behind a non-separately-adjustable channel is just wrong.
Pizz is too quiet? Well, the soundfont designer should have done better reflecting human performers.
Go in and fix all your sounds so MuseScore doesn't need to provide a simple control you could tweak in two seconds for fear of others doing something 'not realistic'.  Please.

As I've said, I don't care about reality when it comes to music production.
I usually am composing with synths in the mix.
Extreme example: If I want to suddenly go from a Bb trumpet to a double bass on the same staff with no visible evidence, my reasoning shouldn't matter.  If I want to care about reality I am fully capable of doing so without MS forcing me to.

All that being said, I may look into just generic 'synth' type sounds, but as I've also said, I'm in no particular rush until 4.x gets better.  It sure looks nice, but that's about it.

My apologies to you if any of what I wrote came off terse.  I meant no harm, and I know you mean well.

**Comment by MarcSabatella** [comment]
Yes, I recall that conversation, although i think I missed that specific response  It doesn’t answer my questions about why your aren’t simply using instrument changes for what are obvious instrument changes.  Hence my suggestion that you consider what I’ve suggested, and if somehow you feel something else is missing, please start a *new* discussion in the forum to elaborate and try to find consensus.

And as I explained earlier, resorting to the old 90’s style hack of having a separate “channel” just for two specific articulations (pizz and tremolo) is wrong.  There is absolutely no reason there should be separate mixer channels for those two specific articulation but no others.  Independent control over behavior of articulations is better achieved by other means, as I also explained previously.

As for whatever issue you are perceiving with the sounds themselves,s that seems unrelated and but should be address in a separate forum post.  Maybe you are just noticing the difference in how the cutoff filters work, which is a known issue indeed.

**Comment by mkj42** [comment]
> simply do it 

Simply is the problem.  I have lots of scores already where sounds are achieved through channel selection.
I cannot simply open them; I have to manually re-create all the sound changes and settings if I wish to retain them.
This is frankly a giant pain in the rear.

> 90’s style hack

...seems a little unfair.  It is how MS behaved until last year.

>having a separate “channel” just for two ... is wrong. ...no reason there should be separate mixer channels for those two specific articulation but no others. 

These are still the only ones called out for strings for instance.  How is it better now exactly? It's worse in that you cannot even adjust the sounds used at all.  They retained a small handful of channels while removing most of the control previously had.

>issue you are perceiving with the sounds themselves...difference in how the cutoff filters work

Definitely unrelated - just mentioning as another big regression in sound quality keeping me in 3.7 for now; I know they know.
It might just be the LPF; it might be the new synth is generally inferior to Fluid; we'll see.

**Comment by MarcSabatella** [comment]
As has been explained, this is not the place to try to ask questions about how things work or refine your ideas or build a consensus on a new feature request.  Please start a forum thread for that purpose.

Instrument changes definitely work, but it’s true that there is no automatic conversion from the old and very limited channel hack method to the much more powerful instrument changes.  That would make a valid second feature request (along with the collapsibility) once you have discussed and reached a consensus on a concrete proposal.  Then if there are any additional feature requests that come about as a result of your consensus-building forum discussion, they can also be submitted separately.

The 90’s General MIDI hack that resulted in MuseScore being forced to support separate channels for pizz and tremolo but not other articulations (not staccato, not marcato, etc) meant that those two articulations alone provided limited controls (over pan and volume only, not duration or start time, etc).  The articulation customization system being proposed elsewhere to replace that would provide appropriate controls over all of that.  But I don’t know how far along those designs are.  I don’t think a separate feature request is needed for this though since it is already on the radar.

Anyhow, the goal is that each feature request here be something very clear and actionable and based on a solid understanding how things work and what is missing that a significant number of users would benefit from.  The discussion leading to that clarity should happen on the forum.  Ideally things would be so clearly stated in the issue description that no further discussion here is necessary.

**Comment by bkunda** [comment]
A closed issue is not the place to resurrect a lengthy discussion about potential feature changes. 

As @MarcSabatella has rightly stated, the forums on musescore.org are the best place for this kind of discussion. 

FWIW, we do have a concept for the sound flags feature that will, one day, extend to soundfont and VST. For the initial release though, its application needed to be limited to Muse Sounds for practical purposes.
