### ISSUE TITLE
[MU4 Issue] - Chord Input

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#12834]
**Describe the bug**
in chord input, tab does not advance to next measure

**To Reproduce**
1. enter a chord symbol
2. press Tab to advance to next measure
3. Tabbing navigates through various parts of the score: workspace>home>parts>etc.

**Expected behavior**
pressing Tab will advance to the next measure for chord input

**Platform information**
 - Windows 11

**Comment by MarcSabatella** [comment]
See https://github.com/musescore/MuseScore/issues/10745.  Because Tab is a crucial bit of accessibility functionality - it's how blind users navigate any computer program - the shortcut has changed to Ctrl+Right.  That's the same as what is used to navigate by measure in note input and normal modes as well.

**Comment by drbirkenstocks** [comment]
Perfect, thanks for the feedback! Sorry I didn't catch that.
