### ISSUE TITLE
[MU4 Issue] "Cannot split tuplet" error is not given when changing time signature

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#12887]
**Describe the bug**
When changing a time signature in existing music, which causes the following music to be rebarred, if it were impossible for the music to be rebarred due to a tuplet that would now have to cross a barline, MU3 would alert the user with an error window:

![image](https://user-images.githubusercontent.com/20604032/184880270-53cf4127-b409-4a1b-93d1-b1058e8eee25.png)

MU4 currently just fails silently. (As though the "Show this message again" checkbox had been unticked, though it hasn't.)

UPDATE: related is this:
![image](https://user-images.githubusercontent.com/20604032/186210443-b38d279a-8ad7-4a19-aa83-5986fb8815f2.png)
which 3.6 would give if you Add -> Tuplet -> Other and put in a ratio that makes sense (i.e. 4:3 on an undotted note). Quoth @asattely: "_the message box is libmscore calling a qt warning box unilaterally, and there was a big push to divorce libmscore from qt, so that's not an option anymore_".

**To Reproduce**
Steps to reproduce the behaviour:
In a score such as this:
![image](https://user-images.githubusercontent.com/20604032/184886574-369134a0-8315-4720-bb17-fb7083f74f06.png)
change the initial time signature to 3/4, for example.

**Expected behavior**
The user should get some feedback about the rebarring not happening.

**Comment by cbjeukendrup** [comment]
It looks like this applies to many more error dialogs. `MScore::setError` is used in a lot of places, but the errors reported through that function are never handled. 
It must be said though that this is not _always_ a problem because in some cases there might be some error prevention on higher levels like NotationInteraction and NotationActionController.
But to name just one example, the "cannot split measure repeat" dialog never appears (it should be shown when trying to split or join measures where one of them contains a measure repeat). There are many more, but all seem somewhat niche, most of them relating to tuplets, local time signatures or measure repeats.
It must also be said that this is only a user information problem: simply nothing happens. It's not that MuseScore or the score can get into an inconsistent state.
