### ISSUE TITLE
[MU4 Issue] Cursor changes to ban sign after clicking on time signatures help button

### ISSUE THREAD

**Issue by Just-your-average-Github-user** [musescore/MuseScore#12916]
**Describe the bug**
Cursor changes to ban sign after clicking on time signatures help

**To Reproduce**
1. Go to the Time Signatures pallette
2. Click on 'Create new signature' 
3. Click on the question mark

**Expected behavior**
Expected to be directed to a help page

**Screenshots**

**Platform information**
 - OS: Windows

**Additional context**

**Comment by Tantacrul** [comment]
I don't understand what this bug is. Main problem is that I don't see a question mark. Closing until more info is provided.

**Comment by cbjeukendrup** [comment]
@Tantacrul This is the problem: (Windows only, because only on Windows you have that question mark)

https://user-images.githubusercontent.com/48658420/194721383-e2845725-382e-4d6d-ad23-e062a8570634.mov

The easiest solution is to remove that question mark, like we do for almost all dialogs. That's trivial to do, by unsetting the `Qt::WindowContextHelpButtonHint` flag.

**Comment by Tantacrul** [comment]
Thanks @cbjeukendrup !
