### ISSUE TITLE
[MU4 Issue] Unable to delete image inside frame 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12934]
**Describe the bug**
1. Click on image inside frame
2. Press Delete - **it deletes the whole frame**

https://user-images.githubusercontent.com/90187801/185659398-0cca3482-0aec-4d65-9f38-706f1bbc7198.mp4

**Platform information**
Windows 10

**Additional context**
Doesn't occur in **MU3**

**Comment by softcat477** [comment]
Hello, Can I solve this issue simply by preferring images over frames when clicking an image inside a frame? I found out that this issue is because musescore cannot select images inside a frame but always select the frame, so the `delete` action deletes the selected frame instead of its image. I recorded a short video to show that the image inside a frame cannot be selected (not shown in the property panel on the left-hand side), while the title, subtitle, and composer, which are also inside a frame, can be selected. And also, when the frame is smaller than the image, I can select the image by clicking the region that is not overlapped with the frame and drag/delete the image.

https://user-images.githubusercontent.com/25975988/187273341-36a72b3e-3a4f-46ab-9a33-5d6e20483d9a.mov

**Comment by MarcSabatella** [comment]
The reason you can't select the image simply by clicking is that it's default "z-index" aka "stacking order" is too low.  So you will instead need to select the frame and them hit the "to back" button to push it below the image.  Probably the image z-index is fine and the frame should be lower.

But, also see https://github.com/musescore/MuseScore/issues/10225.  It's *supposed* to be possible to select elements that are undnearth elements with a simple Ctrl+click.  Unfortunately this is currently broken in MU4. but supposedly will be looked at for beta.

**Comment by softcat477** [comment]
Thanks for your reply! So, as far as I know, Musescore4 prefers selecting the item with the higher z-index. Now the z-index (accessed from `z()`) of an element is determined by the order in ElementType; it is `11,200` for a vertical frame and `7,000` for an image. So preferring frames (order: `11,200`) over images (order: `7,000`) seems like a reasonable behavior in MU4.
Then, to delete the image inside a frame (aka to solve this issue), we could:
1. Rely on the to-back button to move the frame to the bottom and select images we want to delete. This solution is currently functioning well.
2. Rely on issue 10225 to implement the crtl+click feature.

Or, if selecting frames over images is not the preferable behavior, as the description of the issue mentioned that Musescore 3 prefers images over frames, and this issue does not occur in Musescore 3, there might be at least two solutions:

3. Rearrange the z-index of frames so it is smaller than the images.
4. Add rules to ignore the z-index and prefer images over frames. In my understanding this is how titles and frames work. The z-index of a vertical frame (`11,200`) is actually higher than a title (a text with index `600`). But Musescore 4 prefers text over frame by additional rules to ignore their z-order. This might (?) be problematic and cause problems with the to-back button and the future crtl+click feature. So I guess we would not prefer this solution.

**Comment by oMrSmith** [comment]
I confirm: 
You can't select images inside a vertical frame
like you can in MU3
unless the image exceed the borders of the frame...

**Comment by DmitryArefiev** [comment]
Fixed in #15139

**Comment by DmitryArefiev** [comment]
Retested on Win10
