### ISSUE TITLE
[MU4 Issue] Joining beams over rests will cause beams to intersect rests

### ISSUE THREAD

**Issue by dxing97** [musescore/MuseScore#12953]
**Describe the bug**
Joined beams of eighth notes over rests will intersect the rests and cause the score to look not good. 

**To Reproduce**
1. Open a new score, go into note input mode.
2. Create an alternating eighth note/eighth rest pattern
3. Apply "Join beams" (from Beam properties palette) to every other eighth rest

**Expected behavior**
Beams to not intersect rests, either by raising the beams above the rests (done in 3.6) or by moving the rests up/down. 

**Screenshots**

https://user-images.githubusercontent.com/3182625/185833899-a8689348-c466-433d-b360-cffbbb88d76e.mov

**Platform information**
OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2897146315, revision: github-musescore-musescore-89ef1de

**Additional context**

**Comment by oktophonie** [comment]
It is intended behaviour that beams are no longer displaced because of rests (in general, the rests should move to avoid the beams).

It's obviously not desirable that the beams and rests should collide, but we have not yet got to implementing the functionality for moving the rests automatically out of the way, and it's extremely unlikely there is now time before the 4.0 release. Therefore these adjustments will need to be made manually by the user for now, I'm afraid. The necessary functionality will be implemented asap in a future version.

**Comment by oktophonie** [comment]
Ended up duplicated as #15301, fixed by https://github.com/musescore/MuseScore/pull/16410!
