### ISSUE TITLE
[MU4 Issue] Tablature: When entering "c" from keyboard, the wrong number/letter appears on the staff

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13019]
**Describe the bug**

There seems to be a problem with using the key "c" to enter a fretmark in tablature.

**To Reproduce**

1. Create a tablature staff.
2. Go into note input mode, and navigate to string 1, say.
3. Press consecutively the letters a, b, c, etc.

RESULT: When you press "c", 12 appears as a fret mark (or "n", if you have "Letters" specified in "Advanced stye properties").

**Expected behavior**

When you press "c", the number 2 (or "c") should appear as a fretmark. 

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2923999686, revision: github-musescore-musescore-d717792

**Comment by Tantacrul** [comment]
@boryskuzmenko - can you confirm this? Is it a regression?

**Comment by Tantacrul** [comment]
I've given it a P2 for now but it might be higher... depending on  what Borys thinks.

**Comment by boryskuzmenko** [comment]
Keys correspond to numbers, not notes. As described in the Hand book it's an expected behavior (see https://musescore.org/en/handbook/3/tablature#enter-notes)
<img width="1053" alt="CleanShot 2022-09-08 at 13 16 34" src="https://user-images.githubusercontent.com/101250347/189097960-18306454-dcd7-4b09-8465-2900b8e15503.png">

@Tantacrul But in future I'd change this approach: leave numbers as is and use A,B,C,D,E,F,G,B(H) keys as notes (not equals to digits)
So, I'd close this issue for now and will come back to it after MU4 release

**Comment by Tantacrul** [comment]
Thank you!

**Comment by Tantacrul** [comment]
Will reopen when 4.0 is released.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3012488403, revision: github-musescore-musescore-7f4a1f9

Apologies. My mistake. The reason I got "12" (or "n" with letters enabled) was that I pressed the "c" too soon after "b". So, in fact, there was no bug to report in the first place.
