### ISSUE TITLE
[MU4 Task] -2 octave/keyswitching

### ISSUE THREAD

**Issue by Uncodeable864** [musescore/MuseScore#13049]
**Description**
Currently, MuseScore can only reach the -1st octave. The VST instruments I use have key switches at C-2. This makes  switching playing styles impossible. It would be great if MuseScore either had a dedicated "key switches" section, or allowed you to set the lowest possible octave.

**Comment by cbjeukendrup** [comment]
The VST plugins that I have that support C-2, are using C3 as the middle C. MuseScore uses C4 as the middle C, and thus is C-1 the lowest note in MuseScore. So in fact, the lowest supported note is the same in MuseScore as in the plugin, but it just has a different name. Is that maybe the case for you too?

**Comment by Uncodeable864** [comment]
Unfortunately, this is not the case, and C4 is set as the Middle C.

**Comment by Uncodeable864** [comment]
Hello?

**Comment by cbjeukendrup** [comment]
I have found what's the situation: 
- What I said about C-1 versus C-2 must be true: otherwise, it would mean that VST supports negative MIDI note numbers, which is nonsense.
- For notation, MuseScore does indeed support C-1, which is C-2 in the VST plugin, and MIDI note 0.
- But for playback, MuseScore does apparently _not_ support notes below C0 (MIDI note 12). This is a general issue, not specific to VST, so I have logged it in #16657. So I will close this issue in favour of the new general issue.
