### ISSUE TITLE
[MU4 Issue] Application of barlines is inconsistent

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13126]
**Describe the bug**

The following applies to barline applied from the palette:

1. If you apply a barline to the _first_ note of a measure, the barline replaces the start barline of the _following_ measure. However if you apply a barline to any other note except the first, the barline always appears _in front_ of the note.

__Suggestion__: If a barline is applied to the first note of a measure, it should replace the previous end barline (and not the start barline of the next measure).

2. If a barline is applied to a measure, the barline appears _after_ the measure _except_ if the applied barline is a start repeat—in which case it appears _before_ the selected measure.

__Suggestion__: If a barline is applied to a measure, it should always replace the _following_ start barline.

See also #9429.

**Comment by Tantacrul** [comment]
Agree on the following:

1. If a barline is applied to the first note of a measure, it should replace the **previous end barline** (and not the start barline of the next measure).

To your second point @rgreen5, I think it does behave that way now?

**Comment by rgreen5** [comment]
> To your second point @rgreen5, I think it does behave that way now?

Yes. "2" seems to be fixed.

**Comment by bakajikara** [comment]
While testing my PR, I noticed that with this specification, applying a barline to the first note of a new system would change the last barline of the previous system.
Instead of this specification, I suggest the following.

**Suggestion**
If you apply a barline to any element that can be applied a barline, always replace/add the barline immediately after the element. So if you apply a barline to a measure, replace the end barline of the measure. If you apply a barline to the first chord of a measure, add the barline immidiately after the chord. If you apply a barline to the last chord of a measure, replace the end barline of the measure. 

I think this would make more sense and keep things consistent. (I'm ignoring development costs, though.) What do you think? @Tantacrul

**Comment by bakajikara** [comment]
> 1. If a barline is applied to the first note of a measure, it should replace the **previous end barline** (and not the start barline of the next measure).

If implemented this way, it creates some confusion. (You can check this in #16534)
- When applied to a measure, it replaces the start barline of the next measure, but when applied to a full rest, it replaces the end barline of the previous measure.
- When applied to the first note of a system, it replaces the end barline of the last measure of the previous system.

https://user-images.githubusercontent.com/102702868/222657803-afc85fcf-c4dc-4ad4-8eb8-29ff6309d940.mp4

　
Instead, I suggest the following:
	If the barline type is start repeat, add it before the selected chordrest. Otherwise, add after the chordrest.

This way, there will be no unnatural behavior and the behavior will be consistent when applied to notes and when applied to bars. You can test this in #16641.

https://user-images.githubusercontent.com/102702868/222696729-b5167e73-3519-4a8d-80ad-38d2f9c023d8.mp4

@Tantacrul Could you try these and let me know your thoughts?

**Comment by Tantacrul** [comment]
I personally don't agree that if you select a full-measure rest, the barline should appear at the beginning of the next measure. My reasons? Simply because it's not what I'd expect because I didn't select the following measure.

However, this is one of those things where I could be in the minority... so..... I think we need to apply the utilitarian approach:

https://twitter.com/Tantacrul/status/1631643146084921344

**Comment by Tantacrul** [comment]
I must admit that I'd expect the line to appear at the beginning of a measure... but I created a quick poll which has informed me that I'm in the minority.

https://twitter.com/Tantacrul/status/1631643146084921344

With that in mind, I guess it does make sense what you're saying @bakajikara
