### ISSUE TITLE
Tool to split bars is missing essential steps

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13142]
If you split a bar, 
there should appear a system break between both parts of the bar
and the bar-line in the middle should be hidden.

**Comment by cbjeukendrup** [comment]
This is not what this tool is supposed to do. The tool is only supposed to do what you can expect from the name: just split the bar. Creating a mid-measure system break is just one of the procedures where you can use this tool as one of the steps. 

Also, since MuseScore 4 behaves exactly the same as MuseScore 3, this is not a MuseScore 4 bug, but it would be yet another new feature. Therefore we unfortunately can't look into it until after the release of MuseScore 4.0.

Sooner or later, we want to build _proper_ support for mid-measure system breaks, so that 'hacky' ways involving the Split Measure tool will be a thing of the past.

**Comment by oMrSmith** [comment]
Thanks for letting me know!
How about adding another type of bar-line
to the inspector as a workaround for now:
the hidden barline.

**Comment by cbjeukendrup** [comment]
But isn't it easier to just hit the "Visible" checkbox in the Inspector to make a barline hidden? (Or use the keyboard shortcut 'V')

**Comment by oMrSmith** [comment]
I love the "V" shortcut. However incase of the barline,
it will only hide it in one instrument and not
in the whole "Akkolade". Or is there a hack?

**Comment by cbjeukendrup** [comment]
Ah, I see. This is something we might want to change. I think that in practice it is more common that you need to do things with the whole barline than only for one instrument. 

We could do something similar to what we do with key/time signatures. By default, when you click on them, you select them on all staves, but when using Cmd/Ctrl, you can select them for one staff separately.

**Comment by oMrSmith** [comment]
> We could do something similar to what we do with key/time signatures. By default, when you click on them, you select them on all staves, but when using Cmd/Ctrl, you can select them for one staff separately.

This sounds like a good solution!

**Comment by oMrSmith** [comment]
Double click could also work, but I noticed that this is already reserved for another function...

**Comment by MarcSabatella** [comment]
Meanwhile, I would guess a plugin could probably automate the process of splitting the measure, adding the break, hiding the barline, and also marking the second measure to be excluded from the measure count.

**Comment by oMrSmith** [comment]
> We could do something similar to what we do with key/time signatures: [...] when you click on them, you select them on all staves, but when using Cmd/Ctrl, you can select them for one staff separately.

This would also make it a lot easier to hide a bar line as a whole
which is currently necessary when splitting a system in the middle of a bar...
