### ISSUE TITLE
[MU4] [MU3] Take a deep breath: Changing the "Music top margin" is ineffective

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13163]
Please don't get mad at me ;)

So in the manual I read this:

![image](https://user-images.githubusercontent.com/78870770/188310517-d574842f-5450-4502-a819-226fa0351189.png)

![image](https://user-images.githubusercontent.com/78870770/188310554-a0256023-164e-438f-b948-d74bcfc60bb2.png)

**Comment by Jojo-Schmitz** [comment]
Same in MuseScore 3. Remove the vertical frame for that setting to take effect

**Comment by oMrSmith** [comment]
I see. Thank you for our support. I think this is an extremely odd behavior though.

**Comment by Jojo-Schmitz** [comment]
I'm not saying this isn't a bug, but if it is, then a rather old one

**Comment by oMrSmith** [comment]
I don't dare to reopen. If Marc reads this, he's gonna kill me!

**Comment by Jojo-Schmitz** [comment]
Marc isn't that violent ;-)

**Comment by HemantAntony** [comment]
yet (Its a Sunday) :)

**Comment by oMrSmith** [comment]
Ok, so what I can do in order to increase distance on the first page
is change this value:

![image](https://user-images.githubusercontent.com/78870770/188311808-5fd35a64-aaea-4bb0-8532-e590e957ab2e.png)

**Comment by oMrSmith** [comment]
And: Pssst, let's just pretend, nothing has happend!

**Comment by HemantAntony** [comment]
In case you didn't know, we have a discord server (https://discord.gg/HwHhXEbJ4r) where you can see GitHub comments :)

**Comment by oMrSmith** [comment]
Good to know. I might take this into account for the future! :D

**Comment by MarcSabatella** [comment]
No worries, but yeah, definitely use the forum first, especially for new people still learning their way around, it's easy to just misunderstand how things work and think something is a bug that isn't.

In this case, I *do* think there is a bug, but it's not that *music top margin* doesn't have an effect on the position of the frame or the distance between the music and the frame - it was not meant to.  The bug is that the *frame top gap* doesn't have an effect on *the position of the frame*.  But, it was that way in 3.6.2 too.  So while it's definitely something that could be addressed in the future, my guess is it won't be for 4.0 because right now the focus is on the new functionality and on *regressions* (as opposed to long-standing bugs we've learned to live with) in existing functionality.
