### ISSUE TITLE
[MU4] Problematic Auto-placing with Lyrics at the end of a bar

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13208]
The Auto-placement avoids
that the syllable "space" goes past the bar line, which looks a bit odd.

I think this behavior is counter-productive - at least in the middle of a system -
since bar lines for staves with lyrics by default don't go through the system 
to avoid striking through lyrics.

One work around is to disable the auto-place, 
which I did on the right hand side.
This however has a significant disadvantage:

The vertical auto-placing, which is brilliant and doesn't cause the problem, get's lost too.

![image](https://user-images.githubusercontent.com/78870770/188672814-6de83564-a31d-4635-8bc9-c12225af7454.png)

**Comment by MarcSabatella** [comment]
The practical reason why this happens is, horizontal spacing is mostly done one measure at a time, and at the point where that last syllable is being laid out, it's impossible to know if extending it over the barline will cause a problem in the next measure.  Even in the next measure, it's not generally possible to know if there was a syllable extending over the barline from the previous measure, because at this point we havebn't decided how many measures will fit on the system or how wide they will be stretched.  So, it's a hard problem to solve.  Which is not to say that someone clever enough won't be able to find a solution someday!

**Comment by oMrSmith** [comment]
Thanks for taking it into account! 
Overall the spacing-automation of Muse Score is pretty amazing.
Maybe a temporary solution for the future could be to allow
disabling only the horizontal spacing automation for selected syllables...
Having lyrics automatically stay in line is just an enormous time saver...

**Comment by MarcSabatella** [comment]
Yes, I could imagine a temporary workaround where MuseScore only added the *left* portion of the syllable to the "shape" - so it still spaced itself well with respect to the preceding lyric - but would not allocate space on the right  It's a hack, but would be simple to implement at least.  probably some other places where a similar approach could be useful.  Like, if autoplace wasn't so all-or-nothing.  Another example: hairpins that align themselves to dynamics, which is normally great, but sometimes you want to break that association but not otherwise disable collision avoidance.  Probably some larger design could consider all of that.

**Comment by oMrSmith** [comment]
> The practical reason why this happens is, horizontal spacing is mostly done one measure at a time

This has just made me think: What if the algorithm, which spaces lyircs horizontally, 
would just pretend, that all measures within on system
are actually on long bar ? :D

**Comment by MarcSabatella** [comment]
To some extent, that's kind of what some of the new engraving improvements do, but it's not that simple, because, MuseScore doesn't know how many measures will fit on a system until it first calculates the minimum width of each measure.  But then it can go back and shuffle things around to get more consistent spacing between measures - so all eighth notes are the same space on any given system, for example.  That's the work @mike-spa did, and it's pretty great.    I am guessing it would be possible to also do some adjustments to lyrics at that time.

**Comment by oktophonie** [comment]
(Superseded by https://github.com/musescore/MuseScore/issues/17423)
