### ISSUE TITLE
[MU4 Issue] 'Play chord symbols' option doesn't save 'sound off' state for next opened scores and next MU sessions

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13271]
**Description**
'Play chord symbols' option **doesn't save sound off state** for next opened scores - **the option is unchecked but you hear the chord sounds**

https://user-images.githubusercontent.com/90187801/189388069-d084c0e9-bd32-41d6-b70c-a8c6273771af.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**

**Comment by wizofaus** [comment]
How did you even get that menu? For me I get the "Customize toolbar" menu (which looks a little odd, with many "--- Separator Line ---" entries).

**Comment by wizofaus** [comment]
I don't have any problem with it being *saved*, but for me it simply doesn't do anything, regardless of whether it's off or on chords are played back.
It's also rather confusing having the same icon on two different toolbars...

**Comment by wizofaus** [comment]
Um, it'd be a fair bit easier if there were textual repro steps/expected behaviour as per the issue template.  Screen recordings can be helpful in some cases but I don't usually find are the best way to convey what it is you did you cause the problem.

Anyway your updated description now does sound somewhat like what I was seeing - that even though the option was showing as unchecked (and was correctly being remembered as such), the chords were still getting played back.

**Comment by Tantacrul** [comment]
@DmitryArefiev - is this happening in the RC?

**Comment by DmitryArefiev** [comment]
Yes, it's not fixed yet. To reproduce, just uncheck that option and restart MU - all scores with chords have sounding chords during playback

**Comment by DmitryArefiev** [comment]
Fixed in #14948
