### ISSUE TITLE
[MU4 Issue] Chords and metronome can't be muted on mixer.

### ISSUE THREAD

**Issue by Wim4rk** [musescore/MuseScore#13283]
**Chords and metronome can't be muted on the mixer**
Channels for chords and the metronome can't be muted on the mixer. Button is non-responsive.
Using "Playback settings" I can toggle "Play chord symbols" witch is then reflected on the mixer - mute button changes. Same with the metronome, clicking the icon on the playback panel toggles the mute button on the mixer.

**To Reproduce**
1. Open any music file.
2. Open mixer
3. Playback music
4. Toggle mute button for metronome and chords. No difference.
5. Toggle metronome icon on playback pane. Mute button on mixer reflects this.
6. Toggle "Play chord symbols" in Playback settings. Mute button on mixer reflects this.

**Expected behavior**
Mute button on mixer should toggle sound for metronome and chords.

Edit 2024/04/23: Since the implementation of notation-dependent solo-mute states in #20758, there's a design question about what the expected interaction should be between the metronome's mute-state and the current notation. Should the mute state of the metronome act like any other instrument (notation-dependent), or should it be a global toggle?

**Platform information**
 - OS: Linux

**Additional context**
Might be related to issue #13271

**Comment by MarcSabatella** [comment]
Currently, I think this is by design.  Presumably the idea is to simplify things by providing just one place to toggle these rather than two separate controls that can potentially get out of sync with each other.  Having dealt with plenty of bugs over the years where two controls for the same thing do get out of sync, I'm fine with this solution.  But I'm also fine with a design where toggling either automatically updates the other.  FWIW, I just submitted a PR hitting these exact lines of code, so hopefully any PR for this issue doesn't conflict with mine or vice versa - see https://github.com/musescore/MuseScore/pull/13282

**Comment by RomanPudashkin** [comment]
Mute and Solo now work for Chords. As for the metronome, we have this issue: https://github.com/musescore/MuseScore/issues/11031
