### ISSUE TITLE
Hairpin dash settings broken - causing invisibility

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13318]
**Describe the bug**
When applying the middle 'dash' setting for hairpins, the default 'dash' and 'gap' settings are '0', so the hairpin becomes invisible. In addition, when changing the settings to something visible and saving it as a style, the style does not apply to other hairpins, which also default to 0, 0.

**See video**

https://user-images.githubusercontent.com/21022311/189772620-49ab4662-300a-44e4-80fe-f581b76f1b8e.mov

**Platform information**
 - MacOS (not tried other platforms yet)

**Comment by Tantacrul** [comment]
@oktophonie - any chance one of you fine folk can fix this?

**Comment by wizofaus** [comment]
Why are the line style options different for slurs and hairpins though? There's no option to set "dash" and "gap" lengths for slurs, but there are 2 preset dashed styles that would seem more than adequate for most users.  For hairpins, there's only the single dashed style option shown but on selection does allow settings those dash/gap properties.
It seems that the code for slurs has the dash/gap lengths hard-coded (it's 3.0/3.0 for "dashed" and 5.0/6.0 for "wide dashed").
There is a hard-coded default for these lengths in the code (in SLine.h, it's 5.0 for both), but it's getting overridden by an "invalid" value because the hairpin has an invalid "type" at the point the defaults are getting initialised.
