### ISSUE TITLE
[MU4 Task] Dynamics should work for different voices

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13326]
**Task description**
When users specify different dynamics for different voices, they should be audible. At present, a dynamic affects the entire track and not the individual voice.

![image](https://user-images.githubusercontent.com/21022311/189866714-147f9552-9583-46c8-b68e-17f89e9274c5.png)

This is quite limiting for piano writing as well as orchestral scores, where multiple instruments will be represented on the same stave via different voices.

**Comment by Tantacrul** [comment]
Closing until 4.0 is released.

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/58031

**Comment by davidhealey** [comment]
> Closing until 4.0 is released.

Can this be reopened now?

**Comment by Jojo-Schmitz** [comment]
Yes, please

**Comment by quinnouyang** [comment]
I assume dynamics should also be separate for shared staves? E.g. grand staff with a different dynamic in each.

Though then we would need to decide (or enable users to determine) how dynamics affect staves/voices other than their own.

**Comment by DaddyLudwig** [comment]
Yeah, I would assume that too. Currently, if I want to bring a left hand melody out underneath some chords in part of the piece but not other parts, I need 2 piano instruments with the bass clef staves set to Hide when Empty, and with a brace across all 4 staves so that no matter which staves are playing, there's that grand staff brace. With Muse Sounds anyway, MS Basic and soundfonts, I can do velocity adjustment of the notes with.

**Comment by Tantacrul** [comment]
This is definitely true that grand staves need separate dynamics. However, these are two different challenges: dynamics and grand staves. We're planning on tackling the former in 4.1. The latter a little later. 4.2 or 4.3

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/19137
