### ISSUE TITLE
[MU4 Issue] Multiple stacked tempo marking added to top staff

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13342]
**Describe the bug**
If you select a range across multiple staves and add a tempo marking, it adds multiple stacked tempo markings to the top staff.

**To Reproduce**
1. Create or open a multi-staff score such as String Quartet
2. Use Ctrl+A to select the whole score (or click on first measure of top staff then shift+click on a measure in a lower staff)
3. Add any tempo marking from the palette
4. The tempo marking is shown repeated, stacked vertically, one for each staff selected, but all above the top staff

**Expected behavior**
Just a single tempo marking should be added, the same as if only a single staff had been selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/5364225/190021588-fc618168-3b81-471f-b1e3-a659afb516e3.png)

**Platform information**
Windows 10

**Additional context**
Debug build from master branch as of 14-Sep-2022.

**Comment by wizofaus** [comment]
Non-critical, the behaviour is far worse in v3.6 (esp. if you select all then add a tempo marking).

**Comment by wizofaus** [comment]
I wanted the tempo to applied to the whole score, so selecting the whole thing made sense :)
In future I very much hope there is the ability to have different tempi for different staves.

**Comment by MarcSabatella** [comment]
Since internally there is already the ability to identify certain staves as being ones that should display tempo and other system text, presumably a UI to allow you to specify that yourself would also come.  but, not likely it would actually involve *different* tempos for different staves.  That's something else entirely, experimental notation best discussed elsewhere.

Anyhow, to be clear: to apply a tempo marking to the whole score, simply add it to the first note of the first staff.  Never any need to do more than that.

**Comment by wizofaus** [comment]
As I've said before, applying a tempo marking to a note seems very counterintuitive to me, and not always straightforward if your score has a lot of notes. Thankfully v4 now does the "expected" thing when adding it to a measure.
Honestly this is a fairly minor annoyance now in the list of issues still outstanding with v4, I just wanted to ensure it was recorded for when we start working on 4.1 or whatever it is.

**Comment by HemantAntony** [comment]
@DmitryArefiev check #13406 :)

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev check #13406 :)

@HemantAntony Yes, looks good in #13406

Thanks for fixing!
