### ISSUE TITLE
[MU4 Issue] Editing dynamics is broken

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13344]
**Describe the bug**
Attempting to edit the text inside a dynamic element often returns in incorrect fonts being used or text disappearing entirely

**To Reproduce**
1. Create a new score
2. Add an ***f*** dynamic
3. Triple click to select the element and enter edit mode (or just enter edit mode and select the "f" - you can also use various other methods, as long as the text is selected while in edit mode)
4. Type p
5. A p in a strange font shows
6. Click away or press ESC to end editing mode
7. The dynamic disappears completely

**Expected behavior**
Text for dynamics should be editable as expected.  Note that pressing 'p' *isn't* actually expected to show a ***p*** dynamic marking - that requires using ctrl+shift+p. But it should show a regular p in the default font.

**Screenshots**
N/A

**Platform information**
Windows 10

**Additional context**
Latest nightly build, Sep-14-2022.
NB similar issues happen for other text elements after inserting musical symbols, though don't seem quite as bad.
I'd put a heap of work into this about a year ago and it was all working :(

**Comment by MarcSabatella** [comment]
I see a similar effect - I'm guessing the same thing - editing tempo markings, and that's a more critical problem I think, because editing tempo is incredibly common.  In particular:

1) Alt+Shift+T to add a tempo marking
2) Ctrl+A to select the default "(quarter) = 80"
3) type something like "tempo primo"

Same issue: the font seems random (presumably as a result of the special character at the beginning of the text), and it's likely to disappear upon completion of editing - when you press Esc.  But worse, the tempo marking is there, it's not visible.  You can find it only via navigation by Alt+Left/Right.  So you're going to have a lot of people with random invisible 80 BPM tempo markings all over their scores until they figure the workaround.  Which is to not do the Ctrl+A to select all, but to instead first type the new text, then delete the old.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3224155784, revision: github-musescore-musescore-c6f3e75

Same issue with tempo text.

**Comment by wizofaus** [comment]
Confirmed it's still happening with latest build, and as Marc notes, it's pretty serious as it actually applies to *any* text element (that happens to contain musical symbols) and the invisible elements left over can wreak havoc.
