### ISSUE TITLE
[MU4 Issue] Tremolo playback issues

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13369]
**Describe the bug**
Two parts to this issue:
1. "Eighth through stem" tremolo not playing back (except for crotchet notes). "16th through stem" tremolo plays back as "Eighth through stem" should. "32nd through stem" plays back as "16th through stem" should, and so on.2. 
2. Tremolo on triplets plays back with dotted rhythm3. 

See demo video: https://www.dropbox.com/s/ldqrw138v3y07s2/tremolo-issues.mov?dl=0

Test files:
[tremolo-test-files.zip](https://github.com/musescore/MuseScore/files/9576505/tremolo-test-files.zip)

**Expected behavior**
1. Practically speaking, a tremolo stroke attached to a note stem should double the number of notes played at halve the value of the note to which it is attached. 
2. There should be no dotting of the playback rhythm 

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by cbjeukendrup** [comment]
@bkunda I have a potential fix (still needs to be code-reviewed) for the first issue: #13575. 

The triplet issue turns out to be a more general problem, so I logged a separate issue for it in #13576.
(What's actually going on there, is that the durations of the tremolo notes are not taking into account the fact that they are in a tuplet; so they behave like they stem from a normal eighth note. That's why it sounds like the different notes are overlapping a bit.)
