### ISSUE TITLE
[MU4 Issue] Lyrics: Underlines are not beeing considered by the anti-collision automation

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13426]
![image](https://user-images.githubusercontent.com/78870770/191314326-1d923096-d70e-4451-8826-b2580f4e4cd5.png)

**Comment by MarcSabatella** [comment]
FWIW, this is something we'd have loved to get working in MuseScore 3, but we just couldn't figure out a good way, since things were being done in the wrong order to make it feasible.  See https://musescore.org/en/node/280139 for some discussion.  No doubt it's possible, but it's not just a simple oversight that I would expect to be easily fixed, unless more has changed about layout than I think is actually the case.  But if you can pull it off @asattely , that would be pretty awesome!

**Comment by oktophonie** [comment]
Best leave it until 4.X then.
