### ISSUE TITLE
[MU4 Issue] "Re-zeroing" an offset does not return the object to its default position

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13477]
**Describe the bug**

The same offset reading in Properties > Appearance may accompany two different positions in the score.

**To Reproduce**

1. Open the attached file. 
[offset_issue.zip](https://github.com/musescore/MuseScore/files/9638593/offset_issue.zip)
2. Click on a fingering and change the vertical offset, say (drag or use arrows)
3. Open "Appearance" and type 0 (zero) in to the vertical offset spinbox.

RESULT: The fingering does not return to its original position even though the offset readings are the same as before.

**Expected behavior**

The readings in the Offset spinboxes should always tally with object position in the score.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3117031689, revision: github-musescore-musescore-bd3e1bb

**Comment by oktophonie** [comment]
This is, in effect, the same issue as #13261.

This happens because changing the vertical offset can also cause the Minimum distance to change, but unfortunately that value does not update in its respective field. The offset, even when reset, is then applied in conjunction with an altered minimum distance, which causes the object to appear in a different position than it did by default. (Ctrl+R will reset the offsets and minimum distance together.)

See Marc's comment here for a more thorough explanation: https://github.com/musescore/MuseScore/issues/13246#issuecomment-1240687326
