### ISSUE TITLE
[MU4 Issue] Export svg file doesn't work well in score with complex layout

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#13486]
**Describe the bug**
When exporting to svg the attached file doesn't work correctly, showing parts that are supposed to be hidden and hiding other. Exporting to pdf and png is correct 

**To Reproduce**
1. Open the attached score
2. Click on 'export' > svg

**Expected behavior**
File is exported as a copy of the score in svg

**Screenshots**
See attached

**Platform information**
 - OS:  Linux - Fedora 36

**Additional context**

[Test 2.zip](https://github.com/musescore/MuseScore/files/9640803/Test.2.zip)

![Test 2-1](https://user-images.githubusercontent.com/55401477/192144876-7b73d52f-cc9c-42b9-ac60-5bfdf5f3e6c9.svg)

**Comment by cbjeukendrup** [comment]
This glitch seems not super scary: in SVG export specifically, there is an optimisation to draw the staff lines in a separate pass. This is to reduce the size and complexity of the generated SVG file, because otherwise the lines would be drawn per measure. Apparently, the optimisation is not smart enough for complex scores like this. 
This is issue must have existed in MS3 too, hasn't it?

**Comment by geekabit-nl** [comment]
Rehearsal marks are moved around as well. They seem to be auto placed, instead of on the user-tweaked location. It might be related to this issue.

**Comment by cbjeukendrup** [comment]
@sberla365 It would be great if you could test if #21558 solves the problem for you!
