### ISSUE TITLE
[MU4 Issue] Change "Style" to "Line style" in Properties panel (for text-line, hairpin etc)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13562]
**Describe the bug**

For all kinds of lines there is a "Style" tab in the properties toolbar. There is often a property in this tab called "Style" which allows a selection of line styles. e.g.

![hairpin_properties](https://user-images.githubusercontent.com/87246583/193405860-4ff032a3-0564-44a7-958e-fa56316f6e76.png)

However, IMV, "Style" should be relabelled "Line style", wherever it occurs in the panel, to avoid a clash both with the "Style" tab, and with the concept of "Style" generally in the program.

**Comment by hstanekovic** [comment]
Or perhaps "Line pattern" instead of "Line style"? Sorry for dropping-in.

**Comment by EricManiez** [comment]
I'll pick this one up if that's ok!

**Comment by cbjeukendrup** [comment]
I realised that the linked PR has one potentially undesired side effect, namely that the same change would be applied for the Slurs and Ties inspector views. For a slur, "line style" sounds a bit unnatural to me, because it _is_ not a line. @EricManiez perhaps we should avoid that, by allowing to override the title of `LineStyleSection` with some QML property. We'd make the default title "Line style", and override it in the SlurAndTieSettings to just "Style".
