### ISSUE TITLE
Cross staff beams/notes: can't edit placement

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#13580]
If I change placement the stem disappears.

Please fix this, it is important for me.

**Comment by oktophonie** [comment]
It is important for me too :)

Are you able to attach a score (in a .zip) in which you encounter this problem? Or, at least, a screenshot of a particular cross-staff context in which it appears. Also, which build are you using?

**Comment by mart661331** [comment]
![auto place Schermafbeelding 2022-10-06 141642](https://user-images.githubusercontent.com/110895947/194310557-b7de6c45-24ff-449e-83c9-0286db8f9b85.png)
![after edit place Schermafbeelding 2022-10-06 141716](https://user-images.githubusercontent.com/110895947/194310565-1aef88df-ba00-4ad6-b45d-4d0f2582da0a.png)

2 screenshots

**Comment by oktophonie** [comment]
This problem was fixed long ago, as was the issue of the first two stems of each group being much too close together.

Using the 6 Oct nightly, I can adjust the beams with no problem:

![image](https://user-images.githubusercontent.com/20604032/194315321-b777183f-f264-4edb-9c7f-bd0a862ca7db.png)

We will need the actual file to investigate any further.
