### ISSUE TITLE
[MU4 Issue] "Gap Above" is ineffective for frames, which are placed on top of a page

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13665]
This is hard to comprehend from a user perspective and
it also requires to add another frame just to add space.

**Comment by MarcSabatella** [comment]
There's certainly room for restructuring of the various options here.  But to be clear: this is by design, and for a valid reason that makes sense in the cases for which this control was intended..  The gap isn't meant to be a gap between the frame and the page margin - it's a gap between the frame and the *previous system or frame*.  It's there to make sure there is enough space above the frame if it occurs on the same page as the previous system or frame.  If there is not enough room to place this frame on the same page as the previous, it wraps to the next page - but then, the gap isn't needed anymore, and it look entirely wrong to have unnecessary extra space above the frame.  So in the main expected use case, this is correct behavior.

There may also be additional use cases where you have no intention of this frame ever being on the previous page - where you explicitly want this frame to start a new page.  And in those cases, a separate control for distance from margin could be useful.  While it could be made into a property on the frame itself, for ordinary systems, a spacer is how we do that.  So it might make more sense to simply allow frames to have spacers also.

**Comment by MarcSabatella** [comment]
Meanwhile, of course you can set the margin on the frame, and also adjust the position of the contents of the frame.  So in practice,. there is nothing a new control would do that can't already be done by other means.  Still, a direct control for the gap between the frame and the margin could be useful for consistency and simplicity.

**Comment by oMrSmith** [comment]
> So it might make more sense to simply allow frames to have spacers also.

That sounds like a good idea. Or the "gap above" takes the page margin into account
but sets the "gap above" to 0 by default when on top, or the "gap below" to 0 by default when on the bottom...

**Comment by oMrSmith** [comment]
Just had a second thought, which might not have gone until the end:
Would it really be a disadvantage for the gap above and below a frame
to take the page margins into account? Like if a frame ends
up on  top or bottom of a page, you could just set the correspoding value to 0 in the inspector.

**Comment by MarcSabatella** [comment]
I'm not quite sure what you're suggesting, but certainly, the gap value should not magically change itself just because a frame happens to not fit on one page and thus gets pushed onto the next.  After all, if the layout then changes such that the page can now fit on the previous page again, it will still need the original gap.  If there is to be a "gap between frame and top margin" setting, it needs to be separate from the existing "gap between frame and previous system or frame" - they are entirely separate things.  As mentioned, the spacer is already the natural way to implement a "gap between frame and top margin".
