### ISSUE TITLE
[MU4 Issue] Remove "Insert measures" from Properties panel?

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13663]
**Describe the issue**

IMV, the Properties panel "Insert measures" dialog seems out of place. Firstly, it is a command rather than a property. Secondly, it requires the user to preselect a measure before accessing the "At start/end of score" options, whereas you can do the same thing from the menu without preselection.

**Comment by oMrSmith** [comment]
I think this - in conjunction with the delete button - is quite handy. It doesn't take much space either...
I wouldn't use it myself though to append bars.

**Comment by Tantacrul** [comment]
I strongly strongly disagree.

The old inspector was a very useful tool, with tons of potential. By changing it to 'Properties' we are preparing to supercharge it so that it contains more and more useful stuff.

Finding it hard to add / delete measures was a common problem among new users. This just provides another way to make it easier.

I'm going to close this.
