### ISSUE TITLE
[MU4 Issue] Lyrics: "Verse" is missing from Properties toolbar

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13673]
**Describe the bug**
MS3 has a property for lyrics called "Verse":

![lyrics_verse](https://user-images.githubusercontent.com/87246583/194765901-03ad311e-cd41-419f-b49e-3fca49ccc2f3.png)

This is missing from the Properties panel in MS4

**Expected behaviour**

There should be a "Verse" property in a "Lyrics" section of the Property panel.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3212880438, revision: github-musescore-musescore-435b197

**Comment by MarcSabatella** [comment]
Yikes!  That's a pretty big miss.  This is how you do things like move lyrics from verse 1 to 2 if you decide to insert a new verse.

**Comment by MarcSabatella** [comment]
@Tantacrul - this is a missing feature from MU3 that as far as I can tell "just" needs a spin box added to the Properties panel

**Comment by Tantacrul** [comment]
Oh man. I thought we'd found the last of 'em.

@bkunda - we are missing a relatively useful option here. Could you possibly mock it up and add to the issue here? I feel any community member could probably do this.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/21022311/195660298-2d73ef09-3b49-483e-acf7-34354b7cf855.png">

**Comment by HemantAntony** [comment]
Job for me? :)

**Comment by Tantacrul** [comment]
Yeah, that would be very much appreciated!
