### ISSUE TITLE
[MU4 Issue] Tied note does not sound when entered

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13687]
**Describe the bug**

In MS3, entering a tied note in note input mode caused the note to sound. In MS4 tied notes are entered without any sound.

**Platform information**

 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3216906122, revision: github-musescore-musescore-eb51740

**Comment by MarcSabatella** [comment]
@Tantacrul - this is an important accessibility issue; without this feedback it's hard for a blind user to know if they entered a note.  Made especially important since "T" is a new shortcut they won't be trusting yet (and realistically, if they previously were testing the alpha, it may or may not work).

**Comment by Tantacrul** [comment]
Thanks @MarcSabatella

**Comment by MarcSabatella** [comment]
See https://github.com/musescore/MuseScore/pull/14347, which fixes this
