### ISSUE TITLE
'Customise Toolbar' popup has super-long descriptions again

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13685]
**Describe the bug**

The long descriptions at the top of the popup are falling outside the area of the popup again. Not sure when this regression occurred. 

We need to fix this again and return to our previous solution which is that hemidemisemiquavers, and all smaller durations, only show the number.

eg: **Hemidemisemiquaver (32nd) note**  becomes  **32nd note**

<img width="336" alt="image" src="https://user-images.githubusercontent.com/21022311/194851931-d6cb0a76-fb95-4696-a52e-7bf65b3c4cce.png">

**Comment by oktophonie** [comment]
I am also massively triggered by the inconsistently lower-cased "demisemiquaver" and "semiquaver".

**Comment by Tantacrul** [comment]
Incidentally, this is a P2 because it looks very amateurish :)

**Comment by shoogle** [comment]
This has been fixed on Transifex for a while but we haven't updated the translations in the repository since near Alpha 2. We should definitely update them before the Beta.

In the meantime, you can update your en_GB translation in Preferences to see the new strings.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/11011881/194866013-321c58db-881d-43e1-befe-1c6c6e2c683c.png">

Here's what the new strings look like:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/11011881/194866285-50ea696b-425c-4ca5-8c7d-f1351034e807.png">

**Comment by cbjeukendrup** [comment]
> We should definitely update them before the Beta.

Not strictly necessary, since the latest strings are pulled from Transifex as part of the release workflow, and bundled into the returned binary. So what's inside the repo is purely for local development purposes (and maybe for nightly builds).

**Comment by shoogle** [comment]
@cbjeukendrup, that covers our builds but we'll still need to update the repo translations for the sake of Linux distributions and people building from source. Rather than fetching the translations, maybe the release flow should terminate if the translations are not up to date in the repository?
