### ISSUE TITLE
"Gap below" of a frame (placed at the end of a page) is ineffective but still reserving space

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13766]
If the "gap below" of the following text-frame is increased above "0",
the frame will move over to the next page
even though the "gap below" doesn't actually effect the space between the frame and the page number.

This means: If the default value for "gap below" frames, which are placed at the bottom of a page,
is not reduced to "0", the program will reserve space, which isn't actually used.

(Just found this by accident as I was trying to fit the copyright at the end of the first page.)

![image](https://user-images.githubusercontent.com/78870770/195939627-0f312b5b-c658-47e2-84f7-9f1330f2618a.png)

Possible Solution:

If a frame ends up on top of a page, the "gap above" is locked to "0".
If a frame ends up on the bottom of a page, the "gap below" is locked to "0".

**Comment by MarcSabatella** [comment]
For the record, I don't think I ever said anything about gap below.  But indeed, I don't expect it affect the distance to the bottom margin - only to the next frame or system.  And while I haven't given it much thought, my gut feel is that you are right - if a given frame fits on the page, increasing the gap below should never move it to the next page.  No need for MuseScore to play games with changing the user-specific gap values, though - it should simply ignore the gap for purposes of deciding whether the frame fits on the page or not.

For your copyright message, though, this really this belongs in the footer, not a frame.  This wouldn't have worked so well in MU3 because the extra space would be allocated on all pages, but it works as expected in MU4.

**Comment by oMrSmith** [comment]
> For your copyright message, though, this really this belongs in the footer, not a frame. This wouldn't have worked so well in MU3 because the extra space would be allocated on all pages, but it works as expected in MU4.

The problem is, that both sheetmusicplus.com and sheetmusicdirect.com require the copyright to be on the first page (only) whereas the label "licensed to ..." will then be printed on every page... So for that purpose I would always need to use a text frame and apply a page break to it...

**Comment by MarcSabatella** [comment]
No, copyright messages are by default on the first page only.  Just make all that text part of the actual copyright message - copy & paste it directly into the copyright box when creating your score or in File / Project Properties.

There *is* a bug where although multi-line footers work well general, it might require you to make some other edit or something else after adding one, before the layout adjusts.

**Comment by oMrSmith** [comment]
Thanks for your tip, I got it! Think I used a frame in MU3 because the footer overlaps with the system above,
which is no longer the case in MU4. It is still quite narrow though and it looks as though the "Min. vertical distance"
does not apply... At least the distance between the system and the footer won't increase if you set the "Min. vertical distance" to let's say "1".

![image](https://user-images.githubusercontent.com/78870770/195997340-ab394cd0-4805-4d96-8a64-0428af23d285.png)
