### ISSUE TITLE
[MU4 Task] Mixer can't be docked to the left/right side of the screen

### ISSUE THREAD

**Issue by UnaidedButton86** [musescore/MuseScore#13803]
**Task description**
If this isn't intentional (at least I don't hope it is), the mixer can't be docked to the left/right side of the screen; only the top and bottom side.

The mixer:
![image](https://user-images.githubusercontent.com/87303800/196252550-6931ec94-081a-4870-aa75-297aa549efbf.png)

It's actually way too big, and It's annoying to write music while you're displaying the mixer.

So here you can see how you can't dock it:
https://user-images.githubusercontent.com/87303800/196253541-70d4b8a5-b09b-4946-a3d2-190490c69bc0.mp4

**Comment by cbjeukendrup** [comment]
For now, it is intentional. However, in the future, when we have enough time, we will perhaps design a version of the mixer that can be docked at the left or right side, since we recognize that vertical space is valuable while working on a score.

I'll mark this as a not-_yet_-planned feature request for 4.x, but we'll surely come back to it.

**Comment by MarcSabatella** [comment]
FWIW, the mixer is *mostly* not needed while actually working on the score, since the main functionality of soloing staves can now be accomplished directly without use of the mixer.  However, that only works for contiguous staves, and there is no correspond way to mute jus a few staves.  To me, a relatively simple enhancement would be if we had mute/solo buttons in the instruments panel, which has come up in other contexts as well.  Or something like the continuous view panel, so the controls are right there on the score.

**Comment by UnaidedButton86** [comment]
> FWIW, the mixer is _mostly_ not needed while actually working on the score, since the main functionality of soloing staves can now be accomplished directly without use of the mixer. However, that only works for contiguous staves, and there is no correspond way to mute jus a few staves. To me, a relatively simple enhancement would be if we had mute/solo buttons in the instruments panel, which has come up in other contexts as well. Or something like the continuous view panel, so the controls are right there on the score.

Agree, though I would like it on the side, because (e.g.) creating concert pieces requires a mixer left or right, even if you can use the main functionality of soloing staves; I need to listen multiple staves at once

**Comment by UnaidedButton86** [comment]
I don't work in musescore 4 yet, so there isn't a problem now

**Comment by al808909** [comment]
Still can't dock the mixer to the left? 
I hope you guys haven't given up on implementing this,  to me this such an obvious waste of precious space.
Anyway, thanks for providing this great software.
