### ISSUE TITLE
[MU4 Issue] Reducing the "Spacing Ratio" should better not effect the continuous view. 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13816]
Sometimes reducing the "spacing ratio" is needed to save space in the score.
Unfortunately this setting then also applies for the continuous view,
making it rather uncomfortable to input notes due to a lack of space.

Wouldn't it make sense to lock the spacing ratio inside the continuous view to minimum value
since this viewing-mode is meant for easier editing?

In general measures in the continuous view should never become so condensed 
that entering notes is difficult, I think.

**Comment by MarcSabatella** [comment]
The spacing ratio isn't about saving space - it's about the ratio of spacing between notes of different durations.  So, how much more space than a quarter note does a half note take.  it's designed more to create special effects like direct proportional spacing (where a half note takes twice as much space as a quarter instead of the usual 1.5).  And this definitely *should* continue to be true in continuous view - if you want direct proportion spacing, you'll probably want it always, not just in page view.

if your goal is to reduce space, that's more something for the minimum measure width, or the stretch commands.  Probably adjustments to those should be ignored in continuous view, though.

**Comment by MarcSabatella** [comment]
@oMrSmith FWIW, there is definitely merit to the idea of making sure continuous view spacing is reasonable in general.  I recommend starting a forum discussion on this - which is always a good idea before submitting an issue anyhow unless something is very obviously a bug like a crash.  The questions to pose would be, given that the ratio is *not* the correct way to simply compress space in the score, what *is* the better way, and is there a way to make sure continuous view remains viable for mouse entry.

**Comment by oMrSmith** [comment]
I know @MarcSabatella, I have to hold myself back and reduce the number of issue, I'm trying!
But I was playing around and noticed: Hmm measures in the continuous-view get pretty condensed,
which I still believe is an issue or as you say, maybe unwanted side-effect. But now the issue is closed anyway ;).

**Comment by MarcSabatella** [comment]
To be clear, I absolutely applaud your interest in seeing improvements made, and your proactiveness in starting discussions on the topic - I don't want you to hold back at all!  I'm just suggesting you start these discussions in the forum (or Discord, or even GitHub discussions but don't expect many people to see the discussion there) rather than here.
