### ISSUE TITLE
[MU4 Issue] The standard for the buffer is way too low

### ISSUE THREAD

**Issue by tygoee** [musescore/MuseScore#13819]
**Describe the bug**
A really 'cracky' sound is made when the audio is just played. There's an easy fix, eventho it took me a while to find it, which is setting the buffer higher in Edit → Prefences → I/O → Buffer Size and set it to 2048 or 4096

**To Reproduce**
1. Make any song
2. Play the song with default settings

**Expected behavior**
The sound should just.. play

**Screenshots**
Not needed

**Platform information**
 - OS: Windows

**Additional context**
The problem would be solved by setting the default to 2048 (or even 4096 but that 2048 works for me), where it does play normal for me.

**Comment by oMrSmith** [comment]
Why does the program not adapt the buffer size of which the sound card is set to?

**Comment by RomanPudashkin** [comment]
This issue is very old one... I hope it works better now, as we had some massive performance improvements in 4.1/4.2 and will have some others in 4.4 (which will be released soon, or you can download [the latest nightly here](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-4.4.0-x86_64.7z)). 1024 is a very common default buffer size, and we won't change it now (as it is a balance between performance and latency)
