### ISSUE TITLE
Remove velocity settings for dynamics and hairpins

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13858]
**Task description**
This is a step we need to take to have a simpler, universal system for velocity change in MuseScore 4. In MuseScore 3, there are competing velocity parameters which the user then needs to be able to learn to either combine or prioritise. It is too complex and unworkable for the future.

So for MS4, velocity can only be placed on notes themselves.

Hence, these options need to be removed of hairpins and dynamics:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/21022311/197176109-11e51077-12c8-4228-a701-8c71458bb76c.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/21022311/197176261-f5c80c3c-029c-49d9-b7d2-42ff84f3d8d1.png">

---

Moreover, we now should also remove the tab in 'playback' that distinguishes between 'General' and 'Dynamics'
<img width="293" alt="image" src="https://user-images.githubusercontent.com/21022311/197176401-d9fe9221-4df6-4220-9c67-c1475a4c0173.png">

**Comment by Tantacrul** [comment]
@HemantAntony - you think you could take this one?

**Comment by Tantacrul** [comment]
> @Tantacrul Yeah I'll take a look at it

Thanks! Let me know and I'll test

**Comment by HemantAntony** [comment]
@Tantacrul Just to clarify, I should be deleting the entire Dynamics section, right? After that, only the General section is to remain?

**Comment by Tantacrul** [comment]
@HemantAntony - yes.

Which means we also no longer need these tabs:
![image](https://user-images.githubusercontent.com/21022311/197533055-b3486efa-7b96-4dca-a3f3-9a4d93d76fcf.png)

**Comment by fsgregs** [comment]
God, I totally disagree with this thread.  Dynamics MUST be editable in both dynamics marks and hairpins.  The default dynamics, of "ppp", "pp", "p", "mp", etc. are just too broad.  They can be 10 -15 or more velocity points.  Frequently, a dynamic jump that much is just too large.  We need to be able to soften some of the loud dynamics or boost some of the soft ones so that the score's instruments play at the "correct" volume.  In a full orchestra, the composer or conductor will verbally tell the musicians to soften it or boost it a bit as a nuance.  MS 4 should be able to mimic that, particularly if the Mixer is playing the score.  The guy who objected to this existing feature in MS 3.6 was just wrong!!!

Likewise, a hairpin should by itself be editable as it was in MS 3.6, so that we can create global crescendos.  For example, in this actual score posted below, the red hairpin at the top has set velocity of ALL instruments in the score 8 points higher, to create a modest **global** crescendo.  Without it, the score, which has 24 instruments, would have to be adjusted staff by staff to boost all 25 instruments to the next highest default dynamic, which is NOT only 8 pts higher in volume but may be up to 15 points higher.  That sound easily can sound awful.  

![image](https://github.com/musescore/MuseScore/assets/133777637/85db1bec-4230-4818-a5a3-9598bd92f477)

Please restore the ability of both dynamics and hairpins to be Play editable.  Many others on GitHub have also asked for the same thing.  Thanks.

**Comment by cbjeukendrup** [comment]
Don't worry. What you couldn't know, is that we're planning to build something much more usable in MuseScore 4.2, to achieve the same, and more than that. It's called "automation" (that term comes from the DAW world); it means that you will be able to specify how the dynamics level should change over time. And this won't be done using abstract numbers in the Inspector, but with a nice graphical interface.

**Comment by Tantacrul** [comment]
As @cbjeukendrup says, the purpose of all of the above was to remove the highly bizarre and limited way that things were done in V3 in order to make way for a far faster and more powerful way to do it in version 4.
