### ISSUE TITLE
[MU4 Issue] Ubuntu 22.04 MuseSound Playback Missing Most Notes

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#13874]
**Describe the bug**

*   Playback on MuseSound only plays back few notes, others silent.  Usually it is the same 3-4 notes that successfully play back, but not always.  
*   Testing MuseScore-4.0.0-3289917644-x86_64.AppImage and Muse_Hub_Linux.zip
*   BASIC Soundfont playback works ok

**To Reproduce**

1.  Ubuntu 22.04/64/LTC Desktop
2.  Installed MuseHub under Ubuntu 22.04, downloaded "Harp" (had to do this twice to show up on /srv/muse-hub)
3.  Installed MuseScore-4.0.0-3289917644-x86_64.AppImage
4.  Created a score w/ Harp, 2-3 measures of notes
5.  Mixer defaulted to BASIC, plays back normally
6.  Mixer change to MuseSound Harp (menu visible)
7.  Most notes are missing on playback - some initial time delays (hangs) 
THEN --
8.  Exit Musescore
9. Reloaded the score
10. Verified playback still not consistent, most notes missing

**Expected behavior**

All notes should play after switching to MuseSound

**Screenshots**

Available upon request 

**Platform information**

Ubuntu 22.04/64/LTC, 2nd-gen i7 8-cores 8GB (Dell Lattitude), Internal soundcard

**Additional context**

Available upon request 

-----------------------
Tags:
@Tantacrul

**Comment by MarcSabatella** [comment]
I get the delay before playback starts too, then sometimes random dropouts, but this is my slower computer.  Will try on a faster on in a little while (an hour or two).

**Comment by ShawTakeuchi** [comment]
I found a possible problem for the delays and hangups (but not missing notes):

(Reminder: Ubuntu-2204)  Seems that Muse-hub process is not terminating and running in background under 'root', even though GUI is closed, pegging 100% CPU usage on one core.   Running Muse-hub under non-root it is highly recommended to avoid future security incidents -- either create a non-login UID, or perhaps you can move the sound library install under /home/username/.hiddenfolder  instead of /srv/Muse-hub, running Muse-hub at user level?

Killing these processes (multiple) didn't fix the missing notes issue but improved responsiveness (and my CPU fan stopped spinning at full rate!)

This error is repeatable - will file a new bug report.

@Tantacrul @MarcSabatella

**Comment by MarcSabatella** [comment]
Defintily pretty hit or miss even on my faster machine (the fanless version of 11th gen core i5).  Simple things play well, anything more complex and entire passages just get dropped, even when soloing the instrument in question.  Trying to see if I can isolate anything more specific...

**Comment by MarcSabatella** [comment]
I tested with my biggest score, and the passage that were dropping out entirely aren't doing that anymore.  So, that's great!

But, one of the places that was dropping out completely (even when soloed) is still unusually quiet even though marked "f".  It's *probably* not related, but since it's one of the very same passages that was not playing at all earlier, who knows, maybe there is still some connection.  It's in violins I, and it's notated in octaves (divisi), which is likely one of the keys here.  By the time it reaches "ff", it sounds better.

To reproduce, download this score: https://musescore.com/user/2975/scores/8880078

Then go to measure 60 and solo just the strings.  I expect violins 1 to dominate the section (as they do in MS Basic), but they don't.

I can file this separately if you like.
