### ISSUE TITLE
[MU4 Issue] Small notes sound staccato when they shouldn't

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#13892]
**Describe the bug**
So, I tested Musescore 4 with Beethoven's Fifth and overall, it's not that great, but one thing I did not expect was at the oboe cadenza. It sounds staccato. There are no staccato marks however, so why in the world would it be sounding staccato? I've tried writing out a simpler score in MU4. I've tried writing out that same score in MU3 and then saving a copy and opening that copy in MU4. It doesn't seem to be reproducible in simple scores, so maybe this only happens with orchestral scores? Anyway, here is how I produced it in the Beethoven's Fifth Symphony file.

**To Reproduce**
1. Open Symphony no. 5 in C minor Op. 67 in MU3
2. Save a Copy and rename to Symphony no. 5 in C minor Op. 67 MU4
3. Open Symphony no. 5 in C minor Op. 67 MU4 in MU4
4. Play
5. See error

**Expected behavior**
Oboe should sound legato at Measure 268

**Screenshots**

https://user-images.githubusercontent.com/6530761/197372561-f79bcce9-d87e-48c9-953a-c5a01afc7bbe.mp4

**Platform information**
 - OS: Windows 10

**Additional context**
I've only had it happen with this one file so far.

Score link:
https://musescore.com/user/50070/scores/8862729/s/KGta2O?share=copy_link

**Comment by Tantacrul** [comment]
The main thing I want to know relates to that horrible stuttering.

1.  Is the stuttering occurring when you aren't capturing your screen?
2. What happens when you set your buffer size to 2048? Any better?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/21022311/197386320-8968cd05-df20-4129-bf8d-72708ac97a08.png">

Another point I should make is that older scores downloaded from MuseScore.com were built for the soundfont playback and will have very varied results when used with Muse Sounds. For example, I created this score in MS4 and got an infinitely better result: https://musescore.com/user/31604498/scores/8726328

**Comment by DaddyLudwig** [comment]
The stuttering happens at 1024 buffer size regardless of whether or not I'm capturing my screen. It's significantly better at 2048, almost no stuttering as long as nothing is loading in like my browser or anything. Here's a screen capture at 2048 buffer size

https://user-images.githubusercontent.com/6530761/197399903-eb4ed8f7-7b59-4b55-8dbb-b10bce967580.mp4

**Comment by cbjeukendrup** [comment]
I downloaded the score from MuseScore.com and can't reproduce the problem; the oboe sounds legato for me. It seems like I get an opposite problem: the half note with the fermata sounds too long, it continues sounding while the next note already starts. Rest sounds fine though.

Also, @DaddyLudwig, I noticed that in your score, the strings are not using Muse Sounds, not even after doing "View > Playback settings > Muse Sounds > Activate this profile". The reason for this, is that all the strings sections have `strings` as their instrument IDs, and there is no Muse Sounds sound for that. This can be fixed by going to the Instruments panel, clicking the ⚙️ button for those instruments, choosing "Replace instrument" and selecting the correct instrument (e.g. "Viloins (section)", "Violas (section)", etc.

**Comment by DaddyLudwig** [comment]
Alright, I noticed the staccato issue in another score. It seems that I get the staccato issue at slow tempos when I do this:

1. Write a score for at least 2 instruments with a fast section followed by a slow section and then another fast section, like Allegro - Adagio - Allegro in MU3
2. Import the MU3 score to MU4
3. Slow section sounds staccato, fast sections sound legato

Now to see if actually transcribing it in MU4 from the start makes any difference, I'll probably transcribe like a Mozart Sonata or something

**Comment by DaddyLudwig** [comment]
Alright, I just wrote a little score for 2 instruments with tempo changes directly into MU4 and I don't get the staccato issue, so it seems to only affect scores that were written in MU3 and then imported, as well as being specific to 2 or more instruments as already mentioned.

**Comment by DaddyLudwig** [comment]
I'm no longer getting the staccato even with imports from MU3, so I think it's safe to close this issue now as fixed.
