### ISSUE TITLE
Wrong colour definition used for the 'Active' text in 'Playback Setup' dialog

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13905]
**Describe the bug**
In the light theme, the word 'Active' can not be read since the colour definition appears to be wrong

<img width="899" alt="image" src="https://user-images.githubusercontent.com/21022311/197384333-e9ea1a1e-0408-4fab-aaf7-b7a6465d4860.png">

**Fix**
It should be using **FONT_PRIMARY_COLOUR**, set to 70% opacity

**Comment by Tantacrul** [comment]
@HemantAntony, another one it would be great to get your help with, if you have the time!

**Comment by HemantAntony** [comment]
Sure, I'll add this to my log :)

**Comment by HemantAntony** [comment]
@Tantacrul check #13966 :)
![image](https://user-images.githubusercontent.com/88136054/197510834-fa143ac4-660d-4f6e-bff1-7aa166f1cc5a.png)

The opacity values are as follows:
MuseScore Basic  - 100%
Active                    - 70%
Muse Sounds        - 30%
Inactive                  - 25%

Also, shouldn't it be **MuseSounds** instead of **Muse Sounds**

**Comment by Tantacrul** [comment]
Thanks very much!

Quick adjustment:

MuseScore Basic - 100%
Active - 70%
Muse Sounds - 30%
**Inactive - 30%**

Also, I'd keep it as **Muse Sounds**.

**Comment by HemantAntony** [comment]
@Tantacrul I have updated the PR!
