### ISSUE TITLE
General Muse Sounds Issues

### ISSUE THREAD

**Issue by Baol77** [musescore/MuseScore#13904]
**Description of the issue**
Using the MuseSound instruments, during the playback of the attached zipped score, I came across several issues:

- Volume of **brasses**, **choir**, **percussions** and **violas** is generally very low so that the instruments are pratically inaudible (they pop up very clear only with **f** dynamics upwards)
- accent marks are not taken into account
- **pizz. / arco** need to be restored from the palette in order to work
- the **gong** instrument is present in the score but not in the mixer

**To Reproduce**
Here you have the related mcsz file in zip format
[Io sono Gander ed amo il male_v4.zip](https://github.com/musescore/MuseScore/files/9846085/Io.sono.Gander.ed.amo.il.male_v4.zip)

**Screenshots**
- Gong issue
![image](https://user-images.githubusercontent.com/3105101/197383467-edbe402b-300c-4776-9fe8-9e918c6f6df6.png)

**Platform information**
 - MS 4 OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Additional context**
I needed to set the buffer size to 2048 as suggested, in order to avoid major playback issues

**Comment by Tantacrul** [comment]
We have a few of these issues logged already. Unfortunately, this particular bug isn't actionable because it is a laundry list of very different problems.

Could you please log each one separately? In particular, the gong issue, which I wasn't able to replicate because MS4 on my machine was not able to open the file you sent (corruption error message)
