### ISSUE TITLE
MU4 beta doesn't work with OpenSuse 15.1 - missing dependencies (also for the nightly builds anymore)

### ISSUE THREAD

**Issue by kuwitt** [musescore/MuseScore#13921]
The beta doesn't work anymore with OpenSuse 5.1 ( the alpha2 (OS: openSUSE Leap 15.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2826032396, revision: github-musescore-musescore-2d21253) works fine). 
I assume it's the issue of missing dependencies, it's was already once fixed in an earlier version (https://github.com/musescore/MuseScore/issues/6630#issuecomment-704792697). See also the screenshot.

For the nightlies: it's the same for the nightly builds, they are actual downloadable. I found a nightly from august, which I can run (OS: openSUSE Leap 15.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-1103871279, revision: github-musescore-musescore-494061a).

So it was probably changed sometime after that.

![glibc](https://user-images.githubusercontent.com/37350572/197396440-f72cc5ea-c501-4b80-8cc3-a6a81a5e4ced.png)

**Comment by cbjeukendrup** [comment]
Seeing something about GLIBC makes me afraid that this is related to the fact that we now compile MuseScore on Ubuntu 20.04 instead of 18.04. We were forced to do this because GitHub has deprecated 18.04.

@shoogle Do you have any suggestions what we can do?

**Comment by kuwitt** [comment]
Probably not important, but for report: just noticed, the nightly from August I mentioned is from 2021 ;-), after it I  used (and overwrote)  always the MuseScoreNightly-latest...AppImage, so not sure from when it stopped working.

**Comment by shoogle** [comment]
I'm afraid OpenSUSE 15.1 is at end-of-life so we can no longer support it. If it works, great! If not then you're out of luck I'm afraid. The oldest version that we will consider supporting is OpenSUSE 15.3, because that is the oldest version still supported by the OpenSUSE project itself. See https://en.wikipedia.org/wiki/OpenSUSE#Version_history

> Seeing something about GLIBC makes me afraid that this is related to the fact that we now compile MuseScore on Ubuntu 20.04 instead of 18.04.

Yes, that's almost certainly the reason.

> We were forced to do this because GitHub has deprecated 18.04.

Also true. Ubuntu 18.04 doesn't go EOL until April next year but GitHub started doing "brownouts" earlier this year so it's not really usable for us. It's annoying that GitHub chose to do brownouts rather than just cutting off support in April like Canonical.

If we want to go back to building on 18.04 then we could do so inside a Docker container running on the Ubuntu 20.04 GitHub environment. Apparently that might be as easy as adding `container: ubuntu:18.04` to our GitHub Actions workflow. But I'm not sure it's really worth it because it goes EOL soon anyway, and also because [Qt 6 doesn't support Ubuntu 18.04](https://doc.qt.io/qt-6/linux.html) so we would just end up dropping support part way through the 4.x series when we upgrade to Qt 6.

> Or maybe we can fix it by simply using an older compiler (even on the new Ubuntu)?

Maybe, I'm not sure. I've never tried downgrading a compiler before. My instinct would be to build on the older Ubuntu in case there are other library that have changed besides the C++ standard library.

**Comment by Tantacrul** [comment]
@shoogle - it seems I can close this issue then. If you disagree, feel free to reopen.

**Comment by kuwitt** [comment]
In general it's okay for me, probably someday I upgrade the OS (it's not my favourite subject,once a system is running for me ;-).
But for my understanding (with my limited knowledge): Wouldn't not fix it to add the library into the AppImage (see also: https://github.com/musescore/MuseScore/issues/6630#issuecomment-704792923) or isn't it possible anymore after the change to Ubuntu 20.04 as compiler. As mentioned the alpha2 (and also probably the nightlies until this time) worked.

**Comment by cbjeukendrup** [comment]
@kuwitt Just as an experiment, I switched to an old GCC version on the new Ubuntu. Could you please try if this test build can run on your system? https://github.com/cbjeukendrup/MuseScore/actions/runs/3455538377
