### ISSUE TITLE
[MU4 Issue] Note after trill in the next measure doesn't play

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#13932]
**Describe the bug**
If I place a trill on the last note of the measure, the note right after it in the next measure in the same staff doesn't play

**To Reproduce**
1. Write some notes
2. Place a trill on the last note of the measure

**Expected behavior**
The note in the next measure should play after the trill as normal

**Screenshots**

https://user-images.githubusercontent.com/6530761/197408948-0fc6dec7-a2e7-4166-a381-bfbb04db975b.mp4

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by cbjeukendrup** [comment]
I can reproduce this with several Muse Sounds instruments, simply by writing that measure. Also note that the trill itself doesn't sound great either; you hear E E F E F... instead of E F E F E....
It behaves differently for different sounds; for example, for marimba and harp, the upper note of the trill doesn't sound at all.

**Comment by Tantacrul** [comment]
Can you both advise on how the examples compare to MS Basic? This will generally be helpful in understanding whether it is a sampler problem or a MS4 problem.

**Comment by DaddyLudwig** [comment]
In MS Basic, I hear a normal E F E F alternation and I hear that F in the next measure playing. In Muse Sounds, I hear E E F E F and the F in the next measure is silent.

**Comment by DaddyLudwig** [comment]
The trill itself still has that E E F E F in Muse Sounds, but I'm hearing the F after the trill now, so that part of it is fixed now.
