### ISSUE TITLE
[MU4 Issue] [macOS] Some shortcuts are conflicting with systemwide/in-app shortcut

### ISSUE THREAD

**Issue by David-C0pperfield** [musescore/MuseScore#13951]
# Paste half/double duration

Mac users cannot use the paste half duration keyboard shortcut (<kbd>CMD</kbd> + <kbd>Shift</kbd> + <kbd>Q</kbd>), since this shortcut is a system global shortcut for logging out

1. Create a new score in MuseScore.
2. Add a note and copy this note.
3. Try using the paste half duration keyboard shortcut (<kbd>CMD</kbd> + <kbd>Shift</kbd> + <kbd>Q</kbd>)
4. Nothing will be applied and you will see system log out prompt.

**Expected behavior**
Should apply the paste half duration command without conflicting with other commands.

**Screenshots**
<img width="512" alt="The default keyboard shortcut for pasting half duration on macOS" src="https://user-images.githubusercontent.com/43368961/197434087-e86d1aeb-98d7-4e74-8127-df25db35620a.png">
<img width="512" alt="Seeing system prompt for logging out when using the keyboard shortcut" src="https://user-images.githubusercontent.com/43368961/197434137-259e060b-5a0c-431e-9eb5-cfe70e6d185c.png">

**Platform information**
 - OS: macOS 13 (More than that)

**Additional context**
 - This shortcut conflicts with system global shortcut for logging out.
 - <kbd>control</kbd> + <kbd>shift</kbd> + <kbd>q</kbd>/<kbd>w</kbd>/<kbd>x</kbd> seems to be the proper candidate shortcuts

**Comment by David-C0pperfield** [comment]
Similarly, could not use "Add octava 8va Alta", as well. 
I can only use cmd + Y to add octava 8va Bassa

<img width="603" alt="Screenshot 2022-11-01 at 20 02 31" src="https://user-images.githubusercontent.com/43368961/199209574-104debc2-ed77-43ce-9ce9-84a611e88bd4.png">

## Additional context

- cmd + O is a universal in-app shortcut for opening files.
- cmd + A is a systemwide shortcut for selecting all. 
- cmd + B has been already assigned to add a measure.

## Suggestion
The following shortcut keys on Mac have not been assigned. 

- control + O
- control + A
- control + B

***Note**: command (cmd) and control are two different keys on Mac.*

**Comment by David-C0pperfield** [comment]
# Adding Clef

- Only <kbd>cmd</kbd> + <kbd>Y</kbd> works for adding a bass clef.
- <kbd>cmd</kbd> + <kbd>1</kbd> doesn't work, while <kbd>cmd</kbd> + <kbd>2</kbd> is for adding the duplet. 

<img width="598" alt="Screenshot 2022-11-01 at 20 49 23" src="https://user-images.githubusercontent.com/43368961/199217876-e429ae20-6878-4f80-b0c9-a37a440b4433.png">

**Comment by TheMathGuyd** [comment]
This was assigned 6 or 7 months ago, and is still a pretty massive issue on Mac.

**Comment by cbjeukendrup** [comment]
You can easily customise the shortcuts yourself to whatever you want, so I wouldn't call this a "massive" issue. (And it only concerns _relatively_ niche functions anyway). 

Using Ctrl instead of Cmd is very non-macOS-ish (and may lead to confusion in documentation, because many macOS users would automatically read "ctrl" as "cmd"), but could be a solution. 

The story with Cmd+Y, Cmd+O, Cmd+A for ottava markings is a slightly different story. This is _supposed_ to be a so-called "key sequence", which means that when you press those keys in succession, the command will be performed. However, there are several problems with this concept:
- it does not exist in any other macOS apps, so macOS users won't understand it anyway
- beside macOS users, most other users don't understand it either, and confuse it with _alternative_ shortcuts for the same command
- it seems like the same applied to the developers, so key sequences are currently broken.

So, at least for now, these "key sequences" should be banned (there is already a separate task about that).

**Comment by TheMathGuyd** [comment]
While they might seem like niche functions to you, it might be an important function for someone who uses MuseScore exclusively for correcting scans. 

Also, I have the shortcut changed on my machine, but EVERY time I tell a music teacher about MuseScore I do not want to have to ask "Do you use a Mac?" and then respond "Oh you do? Well then make sure you change these shortcuts..."

When I start explaining this to a potential user, they mindlessly navigate to the Sibelius or Finale site and prepare to pay to not have to deal with this "Fix it yourself" mentality. 

If the team needs help fixing this issue, then the person it is assigned to should ask.

**Comment by cbjeukendrup** [comment]
Yes, of course, every command is important for _someone_. 

There is no "fix it yourself" mentality, there is proper priority management, and there is open source software where people have the opportunity to contribute if they get the chance to fix something sooner than we do.

**Comment by MarcSabatella** [comment]
FWIW, we do - or did, at least - ship separate shortcuts files for macOS, specifically to deal with these kinds of issues.  So it would be possible to come up with ones that don't conflict and include them in that file.

I would wager that 99.99% of users have never used any of these shortcut *sequences* - the ones for clefs and ottavas.  So in discussing MsueScore with other teachers, there is no need to even mention these shortcuts.  People virtually never use shortcuts to enter clefs or ottavas; even experienced power users normally add these from the palette.  We don't even document that these shortcuts exist in the Handbook.

As far as I can see, the only affected commands that the average user might know about and want to see work with shortcuts in addition to the menu are paste half/double duration (not ones that would be commonly used when correcting scans, BTW, but in other contexts, yes).  I'd recommend changing these shortcuts in the Mac shortcuts file, and if that means substituting Ctrl for Cmd, so be it.  I'd recommend not bothering with the others - or maybe even just removing them completely.

**Comment by cosmoglint** [comment]
Hi folks, is this issue unclaimed. I would love to contribute and work on this issue

**Comment by cbjeukendrup** [comment]
@cosmoglint Yes, welcome. It would seem best to me to change simply <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>Q</kbd>/<kbd>W</kbd> to <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Q</kbd>/<kbd>W</kbd>; just those two, since <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> does not conflict with anything, and for the other shortcuts mentioned in this issue there will be different solutions. 

For the macOS shortcuts file, see `src/framework/shortcuts/data/shortcuts-Mac.xml`; but note that this file is currently unreferenced, so you'll need to fix that first. Because the file is unreferenced, it might be out of sync with the normal `shortcuts.xml` file, so make sure to check if all differences make sense. 

The ideal solution for the future would be to unify both shortcuts files, but add the ability to make certain shortcuts OS-specific, so that the same shortcuts file can be used on all OSs, but still each OS can have some shortcuts different. Feel free to give that a try, but you don't _really_ need to do that in your first PR.

**Comment by pandu-12345** [comment]
Hello sir, is this issue already solved?
Because I can't find Command + Shift + Q/W in src/framework/shortcuts/data/shortcuts-Mac.xml or in shortcuts.xml . Instead of Command + Shift + Q/W I found Ctrl + Shift + Q/W. 
If this is already solved then can you please close this issue.

**Comment by cbjeukendrup** [comment]
In those shortcut files (and in general, quite often when working with the Qt framework), the shortcuts are spelled in a universal way for all operating systems. On macOS, `Ctrl` is translated to `Cmd`, and if you write `Meta` in the file, that will be interpreted as `Ctrl` on Mac. See https://doc.qt.io/qt-6/qt.html#KeyboardModifier-enum for Qt's explanation.

**Comment by pandu-12345** [comment]
If this issue is unclaimed, then can I work on it.

**Comment by cbjeukendrup** [comment]
@pandu-12345 Yes, feel free to do so!

**Comment by pandu-12345** [comment]
Sir, do i have to change shortcut for both the src/framework/shortcuts/data/shortcuts-Mac.xml and shortcuts.xml or only in src/framework/shortcuts/data/shortcuts-Mac.xml

**Comment by cbjeukendrup** [comment]
Only `src/framework/shortcuts/data/shortcuts-Mac.xml`; the proposed changes are only intended for macOS.

**Comment by efu98** [comment]
Hi! I just saw that the pull request was merged. If it is not resolved, I'll be happy to take this one !

**Comment by cbjeukendrup** [comment]
Yes you're welcome to take a look at this issue! The current status is that the edited shortcuts were added to shortcuts-Mac.xml, but as I said in https://github.com/musescore/MuseScore/issues/13951#issuecomment-1666941151 that won't have any effect because `shortcuts-Mac.xml` is not referenced anywhere. So, what needs to happen is that this file _will_ get used on macOS instead of `shortcuts.xml`, and you'd also need to compare the two XML files to ensure no undesired discrepancies have arisen during the time that the Mac one was not used (for example, someone might have made edits to the normal one but forgotten to make the same edits in the Mac one).

**Comment by Jojo-Schmitz** [comment]
In Mu3 this used to be covered at install time by the setup wizzard, along with the AZERTY versions
