### ISSUE TITLE
[MU4 issue] Publish: missing option to disable overwriting existing score on MuseScore.com

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13997]
**Describe the bug**
If you use the **Publish to MuseScore.com** button, there is no option to publish as a new score instead of overwriting the existing score on MuseScore.com. 

This option can be very useful at times; for example, create a score, publish it, make modifications and publish it again but as a new score, so that you can show both scores on MuseScore.com for comparison. 

I'm not sure why we decided to leave this option out; was it an oversight?

@bkunda Could you provide a design for this? (or remind me why we dropped this option?)

**Comment by bkunda** [comment]
This functionality hasn't been lost – there are still two ways to publish a new score (rather than overwriting an existing score) on musescore.com:

1. Save As... --> Save to Cloud: Public, or
2. Upload directly to musescore.com

Certainly if these options appear undiscoverable to users, then we could revisit the option you're referring to. I suspect our decision to remove this option from the new save to cloud dialog would have been based on simplifying the dialog for the majority of user cases, which would be to make changes to an existing published score, rather than publishing multiple versions of the same score.

**Comment by Tantacrul** [comment]
@bkunda - agreed. Closing for now.

**Comment by shoogle** [comment]
See https://github.com/musescore/MuseScore/issues/16957#issuecomment-1532729740

@bkunda and I decided to put the option back. We realised that it's only needed in the situation that there already is an existing online score that could be overwritten. If the score hasn't been published previously then we don't need to see this option, hence the dialog will remain simple for first-time users of this feature.
