### ISSUE TITLE
MU4 Issue: distorted sound

### ISSUE THREAD

**Issue by Chabrol7** [musescore/MuseScore#14025]
At playback sound is distorted.

**Platform information**
 - OS: Windows 10

**Comment by MarcSabatella** [comment]
Have you tried increasing the buffer size in Edit / Preferences / I/O?

If that doesn't help, please attach the score you are having trouble with, and a video showing the problem.

**Comment by Chabrol7** [comment]
There is still problem with certain files like this, which have distorted sound (bang) at the beginning:
https://musescore.com/user/1021946/scores/5019506
or
https://musescore.com/user/1021946/scores/5459165
And of course, dynamic problem; piano (violin) is almost mute.

**Comment by Tantacrul** [comment]
Hey there. Could you try this build and let us know how you get on? It has a lot of performance fixes specifically for Windows.
WIN - https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

I'm going to close this issue simply because it has been reported already dozens of times. Please do respond though! If your problem persists, we might find out more and reopen.
