### ISSUE TITLE
[MU4 Issue] Linux (Debian AVL) Muse.Service keeps running after Musescore is closed.

### ISSUE THREAD

**Issue by toadzroc** [musescore/MuseScore#14023]
After closing MU4, Muse.Service keeps going, and no amount of attempts to kill it work. I've tried from htop and a Terminal to no avail.

Linux 64bit (Debian AVL-EFL 21.1)

**Comment by JoshuaPettus** [comment]
That brings up a good question?  How is this service controlled in the background?  Is it a systemd service?

**Comment by rgreen5** [comment]
Not sure if this is connected. But after installing Muse Hub I found that boot up time was significantly slower. Normal boot-up was only restored after the hub was uninstalled.

**Comment by toadzroc** [comment]
" Linux Mint 20.1.
 
 Not sure if this is connected. But after installing Muse Hub I found that PC boot up time was noticeably slower. Normal boot-up was only restored after uninstalling the hub."

Same here. I've just uninstalled MuseHub, and run MS4. No Muse sounds present in sounds selection in the mixer. So it seems we need to have muse-hub installed, and running, in order to use the sounds.

I understand MH is closed source, but I don't understand crippling performance to run a proprietary service we can't turn off.

However, to be fair,  it's very early days, and maybe this will change.

**Comment by MarcSabatella** [comment]
muse-hub does not need to be running in order to use the sounds; merely having the muse-hub folder present seems sufficient in my tests.

I was able to kill the various muse-hub processes (search for both "muse" and "Muse") with kill -9, using sudo in some cases, being sure to get all the processes.  In the end, it's probably simpler to reboot.

I do believe muse-hub-service uses systemd as there are reports that on systems where that is disabled, you have to enable it to get Muse Hub working.  But I really don't have any inside knowledge - I only know what I've discovered through my own experimentation or heard reported by others.

**Comment by toadzroc** [comment]
Yep, i've done this with no success.
Muse.Service is the process that won't die, and keeps restarting.

alex@alex:~/Downloads/Muse_Hub_Linux
$ sudo killall -9 Muse.Service
alex@alex:~/Downloads/Muse_Hub_Linux
$ sudo killall -9 Muse.Service
Muse.Service: no process found
alex@alex:~/Downloads/Muse_Hub_Linux
$ sudo killall -9 Muse.Service
alex@alex:~/Downloads/Muse_Hub_Linux
$ htop

alex@alex:~/Downloads/Muse_Hub_Linux
$ sudo killall -9 Muse.Service
alex@alex:~/Downloads/Muse_Hub_Linux
$ sudo killall -9 Muse.Service
Muse.Service: no process found
alex@alex:~/Downloads/Muse_Hub_Linux
$


It's a root process. When i kill quickly, i get the no process found message, for a moment. But it revives anyway. I'm currently trying this with systemd active.

Reboot doesn't work either. When i start MU4 after reboot, the Muse.Service process is initiated, and, well, I'm back to attempting to kill it again, with no success.

**Comment by MarcSabatella** [comment]
Presumably you find where Muse.Service is being started (some config file somewhere) and simply disable that.  FWIW, I don't seem to have a process by that name running on my system right now, unless it's running in a way that doesn't show with ps -ef, which is certainly possible.

I would guess that the reason uninstalling Muse Hub prevents Muse Sounds from working is that the uninstall actually removes the whole /srv/muse-hub folder.  So if for whatever reason you do choose to uninstall muse-hub rather than simply disable the running or Muse.Service at startup, you'd want to preserve the contents of that folder first.

**Comment by MarcSabatella** [comment]
Changing the location of the folder is fine for download, but that won't help MuseScore find it.  As far as I know you will still need to put it back where it belongs when the downlaod is complete.

**Comment by toadzroc** [comment]
Marc, this doesn't make sense. There is a custom option for storing the sounds, right? You can choose the folder where the sounds reside, and there's a popup box that warns you about system wide access or for single user. 

Or is that location only for downloads?

**Comment by toadzroc** [comment]
And when I put them back, muse-hub doesn't recognize the default location and only gives me the option to D/L them again. MU4 doesn't see them either.

I'm off for a coffee....

**Comment by cbjeukendrup** [comment]
Closing, since this is a Muse Hub issue and not related to MuseScore in any way. Muse Hub issues can be discussed at https://musehub.zendesk.com/, if necessary.
