### ISSUE TITLE
Muse Sounds: Missing notes with solo violin at fast tempi

### ISSUE THREAD

**Issue by Lighwan** [musescore/MuseScore#14038]
At fast tempos, some notes get dropped.

https://user-images.githubusercontent.com/68567124/197862981-f5171483-3cdc-4e2b-8a8c-0fed7cf125b7.mp4

Here's the score
https://musescore.com/user/13502736/scores/5582243 (var 2)

**Comment by Tantacrul** [comment]
Would you do me the favour of just describing the problem and not writing 'self explanatory', to save me having to write it myself?

**Comment by Lighwan** [comment]
@Tantacrul Didn't even write that on this issue. I feel the title was concise enough since I wasn't exactly sure what was causing it.

**Comment by cbjeukendrup** [comment]
Possibly related to #14051

**Comment by pmarx810** [comment]
This issue is still present with me, especially with MuseSounds Choir. When voices are played at a fast tempo, all you hear is the faint attack of the note, but obviously there is not enough time to hear the actual pitch.

**Comment by bkunda** [comment]
I hate to throw a spanner in the works here, but I have reason to suspect that the problem might actually have to do with how MuseSounds plays ball (or doesn't) with scores created _prior_ to 4.0.

To test this, I re-created the problematic parts of the Paganini score above and did a side-by-side comparison. Here are the results:

https://www.dropbox.com/s/6nj4n1y4wmflnqf/caprice-paganini-notes-dropping.mov?dl=0
_(Also note the beaming doesn't affect playback – I fixed my version after making this video so that it used the same beaming as the example score)._

Also see this follow-up (contains variation 2):
https://www.dropbox.com/s/vsk1kinozafhkk5/caprice-paganini-notes-dropping-2.mov?dl=0

I'd suggest closing this issue for now, especially seeing as the problem – at least the specific one given in the issue description – isn't reproducible _in MuseScore 4.0_, and that he question of backwards compatibility with older scores is a separate matter.

**Comment by Lighwan** [comment]
@bkunda You're wrong, it was caused by the next variation having a forte marking, which made the violin part in piano break. 

https://github.com/musescore/MuseScore/issues/15062

Dynamics seem really broken for violins especially, as a dynamic in the future affects this section.
