### ISSUE TITLE
[MU4 Feature request]. Expand options for instruments to use with chords

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#14073]
**Describe the bug**
A short and clear description of what the bug is.
Chord symbols playback is using piano sound when MS Basic soundfont is used.
The mixer has an extra channel for chord playback, but you can only select the MS Basic soundfont and you do not have the option to select another sound within the soundfont.

**To Reproduce**
1. Create a new score
2. Add the accordion instrument 
3. Enter some notes
4. Enter some chord symbols
5. Hit play

**Expected behavior**
Chord symbols should playback using the same sound as used for the instrument and have an option to change to another sound (from within the MS Basic soundfont) when desired. 

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by MarcSabatella** [comment]
No, that would be bad in many cases.  People generally won't want a choir singing the chords when adding chord symbols to a vocal staff in pop sheet music :-).  There really should be a way to select the playback sound.  Right now, you can, *if* you have an alternate soundfont containing just the sound you want.  That's obviously not much of a workaround, but it's what we have, I guess.

Perhaps another solution would be to somehow create a mechanism to add an instrument that gets used to supply the playback sound.  Or an option (checkbox) somewhere on the staff or the chord symbol to use the current instrument sound instead of piano.

**Comment by henkdegroot** [comment]
Well then Muse Sounds should get extended to support all instruments available in MS Basic :) 

A selected sound option would be great indeed (as we already have in MS3).

**Comment by Tantacrul** [comment]
This is not going to be addressed in V4.0. We had to rewrite the chord symbol playback due to incompatibility with V3. Will reopen for 4.x

**Comment by zacjansheski** [comment]
Re-scoping.  By the way, if you can find a VST for accordion you can use that for the chord instrument in the mixer

**Comment by henkdegroot** [comment]
Maybe this will be resolved by #17233 ?

**Comment by zacjansheski** [comment]
FIXED by https://github.com/musescore/MuseScore/issues/17233

(There is a limitation as chords sound indefinitely)

<img width="978" alt="Screen Shot 2023-08-24 at 2 36 39 PM" src="https://github.com/musescore/MuseScore/assets/69917893/527841c6-7fa6-46ce-999b-af65dc709eec">
