### ISSUE TITLE
Muse Sounds - Too much reverb added on any instrument.

### ISSUE THREAD

**Issue by maestroharmony** [musescore/MuseScore#14107]
I'm not sure if this describes as a bug but more of a request, by some of the users that told me to address this issue.

**Describe the bug**

Probably due to some algorithmic reverb that is pre-built in Muse Sounds... adding some Muse FX Reverb (Small Room) into Muse Sounds makes it sound all washy even in the lowest settings.

**Expected behavior**
A less reverb-y hall from the Muse Sounds, so we can use Muse FX Reverb or any external reverb without any problem of having washy sound.

**Platform information**
Windows 11 latest update, R7 3700x 32Gb RAM

**Additional context**
Even if it isn't possible to do anything about this, please dismiss this issue.

[reverb test.zip](https://github.com/musescore/MuseScore/files/9881552/reverb.test.zip)

**Comment by Tantacrul** [comment]
This won't be altered now, as the library has been built to include a set amount of reverb, which (on balance) works really well.

**Comment by erinic04** [comment]
@Tantacrul this issue is still in To Do in the Muse Sounds project, despite being closed. Not sure if this was intentional or not

**Comment by shoogle** [comment]
Muse Sounds instruments were recorded dry. The reverb you hear is being added artificially by the sampler, so we should be able to add a control in MuseScore to reduce the reverb or disable it entirely. However, we won't be able to do this in time for the initial release of MuseScore 4.

> this issue is still in To Do in the Muse Sounds project, despite being closed

Thanks! I've added this to the MuseScore 4.X project so that we can find it again later when we get around to reopening all the temporarily closed issues.

**Comment by SebLacroix** [comment]
@Tantacrul there has been an epic discussion on the forum recently about this problem (https://musescore.org/en/node/338522)
I can provide a sample score that shows the impact on brass instrument for Classical Jazz (Glenn Miller), sounding like in a cathedral, where a drier sound would be more appropriate.
Could the team provide an insight about the plan for this issue?

**Comment by Tantacrul** [comment]
Epic eh? Is it ever any other way on the forum? 😄 

Anyway, providing controls to allow users to tweak the reverb used by Muse Sounds is very much on the cards. We decided not try and tackle it for V4 because there are a few related things that need to be implemented first.

1. We need a better native reverb effect that comes packaged with MuseScore
2. We need aux channels for this reverb
3. We need to agree on exactly how the above two concepts work with Muse Sounds, which has its own reverb. More than likely, we'll just provide controls so users can edit this themselves.

**Comment by dgealow** [comment]
I don't know, "a toggle to turn off added reverb completely" doesn't sound like the kind of thing that really needs a boatload of dev work.

**Comment by Tantacrul** [comment]
@dgealow - thanks for your expert opinion! You know, you really should provide more insights like these!

But just a little more info:

- We've got an entirely new reverb because the one packaged with Fluid is horrifically non-performant
- We are implementing auxiliary channels in the mixer, which reverb will be added to by default, so there isn't an instance of reverb on each instrument. Just a single reverb. From a sound design POV, this is the best and most performant way to do it
- This means users can add more FX to aux channels and manipulate them precisely too. (Wet / dry / amount / volume of FX)
