### ISSUE TITLE
[MU4 Issue] At random, either 1 or 0 tracks will play. Never the full score.

### ISSUE THREAD

**Issue by nottellingyouanything** [musescore/MuseScore#14126]
**Describe the bug**
This is either a feature that is cagily explained, or a massive bug that seems to be affecting me and me alone. In one score, only one staff plays. In another, none of them play. This is not an audio setup or configuring issue afaik. Notes play when selected or inputted.

**To Reproduce**
1. Go to any score.
2. Play.
3. The playhead moves, but nothing comes out of any but one instrument. Or none.

**Expected behavior**
I expected there to be audio.

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Additional context**
This issue existed both before and after i downloaded any Muse Sounds instruments. Version/origin of score has no effect. Restart has no effect.

**Comment by MarcSabatella** [comment]
If you select a measure or other range instead of just a single note when starting playback, MuseScore 4 now will now solo the selected staves.  This is by design.  Probably that is what you are seeing.  Be sure to select a single note - or really, a single anything; just not a range - before stating playbacl
