### ISSUE TITLE
[MU4 Issue] Tie not applied during playback

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#14137]
**Describe the bug**
A short and clear description of what the bug is.
Notes which are tied sound in playback as individual notes. 
Meaning the first eight A in measure one, first G eight in measure two.

**To Reproduce**
Create a new score and select Trumpet as the instrument.
Make sure MS Basic is used for the sound.
Enter the following notes:
![image](https://user-images.githubusercontent.com/13550012/198590324-ae05e78e-356b-4680-942c-981988a6ab4b.png)
Hit playback and listen.

**Expected behavior**
The duration of the first note should be extended with length of the tied note.

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by MarcSabatella** [comment]
@Tantacrul Yikes - not just trumpet, not just this passage - ties within slurs don't work in current builds, period (current nightly build).

**Comment by MarcSabatella** [comment]
OK, and I just tested a revert of #14026 and that didn't fix it.  I'll stop playing detective now, then (and I edited out my speculation on the cause in my previous comment).

The extra note in MuseSounds happens only with some sounds, but I can hear it clearly with harp.  On others, I hear only a vague hint of the wrong note on 2& along with the correct note, but with harp, it's articulated clearly.

**Comment by henkdegroot** [comment]
@MarcSabatella, your hearing is much better than mine....I can hear it when using Harp indeed.

**Comment by MarcSabatella** [comment]
Another aspect of this that I assume is related even though no slur is involved - the tie on the final chord of "Reunion" (https://musescore.com/user/2975/scores/8899170/s/uaX1Pt?share=copy_link) fails also.  Here, it seems to be the pedal that breaks it.  So I suspect it is, any tie within any other type of spanner gets ignored.

**Comment by Tantacrul** [comment]
Confirmed.

https://user-images.githubusercontent.com/21022311/199348188-78a6c7fb-15ce-40dd-be77-ed5c745c8067.mov

Score: https://www.dropbox.com/s/5f0hb7y27noi2tl/Ties_Slurs.mscz?dl=0

**Comment by MarcSabatella** [comment]
Still an issue in beta 2.

**Comment by Tantacrul** [comment]
> Still an issue in beta 2. I won't bother updating _all_ issues with this info, but this is the biggest (by far) regression in beta 2 compared to beta 1, was really hoping to see it fixed.

If this issue had been fixed, then this comment would be welcome. **please** do not go on each issue that is not closed and clearly not being worked on yet and remind us that it isn't fixed. Focus on what **is** fixed.

**Comment by cbjeukendrup** [comment]
I found that this was caused by https://github.com/musescore/MuseScore/commit/8088327288fa8311af4fb7c225b8947f50028560. A Slur gives the notes a "Legato" articulation, which is considered a "multi-note articulation". When a note that continues or ends a tie chain has a multi-note articulation, it is played as if it started a tie.

**Comment by cbjeukendrup** [comment]
By looking at the code I found that this is triggered not only by slurs, but also by other things. Pedal markings are an example; and in a way, glissandi too: if you add a glissando like this:
<img width="259" alt="Scherm­afbeelding 2022-11-05 om 00 18 52" src="https://user-images.githubusercontent.com/48658420/200088200-f8f6cfea-4347-4bcb-a189-a7db46157118.png">
the second note of the tie will be re-triggered but it shouldn't. The expected behaviour is that you _only_ hear the other notes of the glissando, but not the 'bottom note', because that is tied to the previous note. I imagine it could be relatively tricky to render a case like this correctly...
<img width="862" alt="Scherm­afbeelding 2022-11-05 om 00 25 04" src="https://user-images.githubusercontent.com/48658420/200088651-31f4e26b-cae5-42d1-b509-2c36396566be.png">
