### ISSUE TITLE
[MU4 Issue] Appoggiatura never stop playing

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14170]
Appogiatura never stop playing

https://user-images.githubusercontent.com/1835871/198846540-044a107b-4e90-4302-aaa5-165c769a7646.mp4

**Comment by Tantacrul** [comment]
Thought we had eliminated all of those. Can I ask: is it playing using MS Basic or Muse Sounds?

What is the instrument? A tenor sax?

Next: is this the Beta release you are testing or the latest nightly?

Lastly, could you zip the score and attach it here? Even better if you can isolate the part of the score where this issue is occurring and supply that instead.

**Comment by Gai-Luron** [comment]
Tested in Nigthly, seems to work. Issue solved.

Thank's
