### ISSUE TITLE
Unable to trigger any Muse Brass mutes

### ISSUE THREAD

**Issue by TobyTwo32** [musescore/MuseScore#14191]
If there are really recorded sounds of Mute Muse Brass sounds, I can't really seem to trigger them. No stops (+) for Horns, or Muted Trumpets or Trombones.

Maybe a mapping issue?

**Comment by mccoydtromb** [comment]
The information given in MuseHub doesn't actually promise any muted sounds. Can someone from Muse confirm if there are samples recorded at all?

**Comment by bkunda** [comment]
@maestroharmony I've been able to trigger the mute samples using both the "+" symbol for individual notes, and the text instructions "mute" and "open" for note passages. 
(Please note that the actual "mute" and "open" text elements from the Text palette need to be used: entering these words as staff or expression text won't work, and neither will the use of a line element). 

[Please see this video for a demo](https://www.dropbox.com/s/tm6hac2hr3f9g44/brass-mutes.mov?dl=0).

If there's anything I've missed in the video demo above, please let us know here. Otherwise, it seems we might be able to close this one.

**Comment by MarcSabatella** [comment]
Indeed, this started working as of Muse Sampler 0.5 I believe.

**Comment by julenComposer** [comment]
Dear all, I hope this is not too old, but I have the same issue. However, not even the "+" articulation works in my case. I'm using musescore in italian, so for me I guess the text to use is "Sordino", but no effect.
To test this further I switched to MS Basic, but both "Sordino" and the "+" articulation only shorten a bit the notes, as an half-staccato, so not the desired behaviour.

I made a small [video](https://drive.google.com/file/d/1l07JR5RdJRMX751XXj82gztxSIdCCq12/view?usp=sharing)showing this behaviour. 

Might it be a language mapping problem?

**Comment by MarcSabatella** [comment]
Make sure you are using MuseScore 4.2 (see Help / About MuseScore) and then see Diagnostic / Muse Sampler / Check Muse Sampler.  If that is not 0.5 or later, you need to update it via Muse Hub, the restart MuseScore.  If you continue to have trouble after making sure MuseScore reports that Muse Sampler is 0.5 or later, please ZIP and attach your score here.

**Comment by julenComposer** [comment]
Oh I see, thank you Marc! Indeed my muse sampler is still 0.4.3. I'm trying to update it but unsuccessfully, but that's a different issue.
Thank you for the hint!

**Comment by zacjansheski** [comment]
I believe this is resolved, but if there continues to be a MuseSounds specific issue, Please report to MuseHub support team: https://support.musehub.com/hc/en-gb/requests/new.
