### ISSUE TITLE
[MU4 Issue] Muse Sounds piano articulation is non-legato

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14222]
**Describe the bug**
The articulation in the piano on Muse Sounds is very detached by default, and adding a slur or tenuto doesn't change this

**To Reproduce**
1. Create a score for piano, using Muse Sounds, 120 BPM
2. Enter a measure full of sixteenths
3. Play
4. Hear error: they sound almost staccato, and neither slurs nor tenuto markings help

**Expected behavior**
Piano by default should be more legato than this

**Screenshots**
Here is a sample to try:
![image](https://user-images.githubusercontent.com/1799936/199071198-b7e395a6-bc37-49bc-ba9f-41dd53dcfa25.png)

**Additional context**
Longer notes are not so problematic, as the notes *do* sustain.  I think the issue is that attack is simply too much louder than the sustain.  And probably that is a matter of this having been close-mic'ed and thus baked into the samples, which would in turn mean it might not be addressable without re-recording.  Unless MuseSampler is capable of fiddling with ADSR curves.

Anyhow, I don't really expect to see this changed, but I definitely notice this myself and have heard it discussed on Discord.  So I figure, there should be an issue for it here to track even if it is postponed.

**Comment by DaddyLudwig** [comment]
I agree with this. As a pianist, I play legato by default unless marked otherwise(like slur with staccato dots or just the staccato itself) or it's chords or has repeated notes.

**Comment by maestroharmony** [comment]
Hi Marc, the solution to this problem is very simple since all notes are articulated as sustains or staccatos, it would be to use sustain over 100%, this means that the note will overlap to the next one 105%/110% is good around that.
 
Now tenuto is holding the note in their full total. Thus around 90 - 95% of the full sound of recorded sample.

**Comment by MarcSabatella** [comment]
I am not so sure it's really about length, though.  As mentioned, it sounds like it's about the attack portion of the sound to me - it decays too rapidly to the sustain portion and the different in volume between the two is too great.  At least that's how it sounds to me.  And in any event, it's certainly possible to sound legato without extending duration beyond 100%.  It's only 95% in MU3 and still sounds legato enough,

But I'd certainly settle for whatever solution works to give the illusions of more legato playing.

**Comment by Dima-S-Jr** [comment]
> I agree with this. As a pianist, I play legato by default unless marked otherwise(like slur with staccato dots or just the staccato itself) or it's chords or has repeated notes.

I have already written a [comment](https://github.com/musescore/MuseScore/issues/22140#issuecomment-2087793007) about this. By default, it should be _non legato_, since this is the only playing technique that does not have any visible articulations (unlike the same _legato_, which is indicated either by verbal instructions or slurs).

**Comment by MarcSabatella** [comment]
Um, no.  Except for Baroque works originally intended for harpsichord or similar instruments, the normal default for piano music is definitely legato.  Luckily this bug was fixed long ago.
