### ISSUE TITLE
[MuseHub] Enhancement request: include release notes

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#14286]
When showing available updates MuseHub simply shows "Muse Percussion 0.4.4" or "Audacity 3.2.1" but offers no further details about what that update entails.
It would be nice if we could click through on it and see a release notes/history before downloading the update.

@Tantacrul for triage

**Comment by cbjeukendrup** [comment]
I think this can be closed now, since this basically has been implemented with Muse Hub V2.
(Would still be nice to be able to see the full history of release notes instead of only the latest release, but that's something for the Muse Hub team to consider and doesn't need an open issue in our repo.)
