### ISSUE TITLE
[MU4 Issue] When Instrument is not visible, "Solo" Selector can be check

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14280]
**Describe the bug**
When Instrument is not visible, In mixer "Solo" Selector can be check (Anyway do nothing), "Mute" No (Normal behaviour)

**To Reproduce**
1. Hide a Part
2. Got to Mixer
3. Look to selector

**Expected behavior**
"Solo" Selector must be disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/1835871/199591491-a4568314-61be-4630-91d7-bc7465a3f647.png)

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Comment by HayatoYagi** [comment]
Hi! Can I work on this?

**Comment by HayatoYagi** [comment]
Which do you think is better?

When you hide a part with solo checked, 
1. simply uncheck and disable solo selector
2. disable solo while invisible, and enable solo after the part become visible again

I prefer 1 because I think it's confusing a part that's been hidden for a while and then re-shown become solo.

**Comment by DmitryArefiev** [comment]
Fixed in #15872
