### ISSUE TITLE
[MU4 Issue] Musesampler not able to be installed

### ISSUE THREAD

**Issue by Mr-Freeze-is-cool** [musescore/MuseScore#14317]
**Describe the bug**
Unable to get downloaded muse sounds to work with musescore 4, I believe this is due to an issue with a correct musesampler configuration being missing resulting in it not being able to be downloaded.

**To Reproduce**
1. Open Muse Hub
2. Click "Get" for one of the muse sounds
3. During download Muse Service will seemingly disconnect and an error on the download bar will ask to reconnect
4. after reconnecting a popup window inside of the hub will come up saying that "Muse Hub was unable to find the required configuration to install this application. Please try again."
5. After clicking okay on the pervious error message another will pop up saying "Something went wrong, please try again later"

**Expected behavior**
Clicking "Get" on a muse sound will download it and I will be able to use it in musescore 4

**Platform information**
Windows 10 21H2

**Additional context**

Logs from issue:
2022-11-04 22:29:50.0158|INFO|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.Actions.UpdateAppStateAction, Data: -
2022-11-04 22:29:50.4296|INFO|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.AlertMessage, Data: Title=Unable to install MuseSampler;Description=Muse Hub was unable to find the required configuration to install this application. Please try again.
2022-11-04 22:29:50.4296|INFO|Muse.Services.WindowsDialogService|Displaying Alert: Unable to install MuseSampler | Muse Hub was unable to find the required configuration to install this application. Please try again.
2022-11-04 22:29:50.4425|INFO|Muse.Services.WindowsDialogService|Displaying Alert: Unable to download MuseSampler | Something went wrong, please try again later

ID: musesampler
Type: Application

**Comment by iamtesch** [comment]
We have just released a muse hub update that should resolve this.  Can you:
(1) check for updates, and update the hub
(2) after the hub restarts, download a new instrument (if you have downloaded all already, alt-click to delete one and then start to redownload)
(3) wait 10-15 seconds, then check that the sampler has downloaded properly.

Sorry for the issue here!

**Comment by iamtesch** [comment]
(I'll leave this open to verify the issue if fixed for you, and for visibility if anyone else runs into it in the next day or two)

**Comment by Valdessir** [comment]
I was about to log the same issue today but then I saw this thread, and now I'm here to confirm that I experience exactly the same issue.

**Comment by Mr-Freeze-is-cool** [comment]
The issue was resolved, thank you very much.

**Comment by henkdegroot** [comment]
I have the same issue, running on Win10. I have tried all suggestions here but still no working musesampler.
Please advise on how I can completely remove MuseHub and re-install (there must be something left behind on my system which fails).

Already tried:
(1) check for updates, and update the hub
(2) after the hub restarts, download a new instrument (if you have downloaded all already, alt-click to delete one and then start to redownload)
(3) wait 10-15 seconds, then check that the sampler has downloaded properly.

Also tried:
Removing ALL MuseSound libraries and re-download

Also tried:
Remove MuseHub
Install MuseHub

Attached the MuseHub log (modified my external ip address in the log, so that is not an error/issue):
[current - mod.txt](https://github.com/musescore/MuseScore/files/9945369/current.-.mod.txt)

**Comment by henkdegroot** [comment]
Update: 

I got MuseSounds working again by using this procedure:

Uninstall MS4
Uninstall all MuseSound libs
Quit MuseHub
Uninstall MuseHub
Delete folders:
 - C:\ProgramData\MuseHub
 - C:\ProgramData\MuseSampler

Reboot PC

Download latest Musehub from https://www.musehub.com/
Install MuseHub
Download all MuseSounds
Install MS4 Beta

Now it works again.

**Comment by iamtesch** [comment]
Closing this issue, as the new hub release seems to have addressed the root problem.  We are working to address potential causes of the hub getting into this state.
