### ISSUE TITLE
Minor issue: GitHub doesn't recognize license.

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#14356]
On the "Code" page on GitHub, it shows the license as "Unknown."
![image](https://user-images.githubusercontent.com/87204246/200149035-9677a82b-d01d-4197-8869-b492ae59ae23.png)

**Comment by Gravifer** [comment]
Can confirm. Is the content of the license somehow deviating from the standard GPLv3, or is GitHub just being dumb once again?

**Comment by cbjeukendrup** [comment]
Yes, in our license there is a small exception / clarification about user scores that were made using the notation fonts packaged with MuseScore. I guess that's why GitHub doesn't recognise it. Not sure what we can do about that.

**Comment by Gravifer** [comment]
Would this create any legal loophole to allow proprietary projects to evade the GPL license? I know absolutely nothing about copyright laws.

**Comment by cbjeukendrup** [comment]
I must say I'm not an expert either, but I don't think so, since this exception is only about files that users create using MuseScore; those files do indeed evade the GPL license, but not any part of MuseScore itself. (For comparison, it would be similar to say that documents created with Microsoft Word are not affected by the license under which Microsoft Word is released.)
