### ISSUE TITLE
[MU4 Issue] Edwin chord font raises parenthesis for "add 11" chords

### ISSUE THREAD

**Issue by RobH1964** [musescore/MuseScore#14352]
**Describe the bug**
The Edwin chord font is still "raising" the first parenthesis for "add 11" chords 

**To Reproduce**
For the Edwin chord font:
- set the modifier scaling to 0.70
- set the vertical offset to -4
- create an add11 chord

**Platform information**
 - OS: [Linux Mint 21]

**Additional context**
Hi there.  I'm not a developer and this is my first post.  I'm just checking out MS4 and thought I'd pass this info along.  Congrats on taking on such a massive project.  Everyone should be very proud of the work you've done - it's been noticed!
![Screenshot](https://user-images.githubusercontent.com/117548979/200147780-2a58b468-87d9-4669-9e28-6d333bd22565.jpg)

**Comment by RobH1964** [comment]
I also saw the same behaviour with "(add 4)", if it helps

**Comment by RobH1964** [comment]
Sorry, I hit the wrong button!  I didn't mean to close the issue - far from it.

: )

**Comment by oktophonie** [comment]
Easily done! :)

It's not specific to Edwin, incidentally; any font is the same:
![image](https://user-images.githubusercontent.com/20604032/203261372-83b1aea2-760d-41e8-883f-64ae38987b91.png)

And it's the same in 3.6:
![image](https://user-images.githubusercontent.com/20604032/203261699-19d4ec50-b09e-499f-b2a2-2dd0c97fe867.png)

So it looks like the presence of the 'add' is cancelling the modifier vertical offset; if we remove it we get this:
![image](https://user-images.githubusercontent.com/20604032/203261945-65c60fa7-d673-46cc-b2cc-acc33b35bbee.png)

(I'm assuming we actually _want_ the bit in parentheses raised, since the offset was explicitly set to -4).

It seems the problem is with how the modifier is (or is not) being parsed; a related issue was reported here: https://musescore.org/en/node/299930. I may have to invoke @MarcSabatella on this one!

**Comment by MarcSabatella** [comment]
My memory is foggy on this, but I seem to recall "add" was special-cased originally to allow it to remain on the baseline in some style or other.  But obviously, the parentheses handling isn't right, and really now that the option to scale & offset modifiers is present, I can't see why we would exclude "add".  Oddly, it *does* respond to offset & scaling in the jazz style, so maybe we did something special in chords_jazz.xml?  I don't actually see what though.  Maybe somehow these lines are help "add" to be seen as a modifier - https://github.com/musescore/MuseScore/blob/master/share/styles/chords_jazz.xml#L246-L249 - and somehow that could be leveraged into chords_std.xml?

Presumably also the existing parser/renderer could be hacked to fix this.  I think somehow the "add" token just isn't being honored as a modifier (presumbaly due to the earlier special-casing).  It looks like it *should* be happening at https://github.com/musescore/MuseScore/blob/master/src/engraving/libmscore/chordlist.cpp#L827-L830.  I'd want to understand if that is not getting hit, if it's being set then lost later, or if it's not doing what I think it should be doing.  Then we could see how to fix it.

All of this is kind of hacks on top of hacks to support all the different styles out there, but of course, we do have all the work done for GSoC a year or so ago to leverage as well.

**Comment by MarcSabatella** [comment]
OK, I can verify that simply adding these lines to chords_std.xml fixes this:

`  <token class="modifier">
    <name>add</name>
    <render>add</render>
    </token>
`

To be honest, I'm not sure *why* it fixes it, pretty sure it's working around a bug in the parser somehow.  But anyhow, I can submit a PR for that much.  Also, it was more difficult to test this fix than it should have been because of another bug - https://github.com/musescore/MuseScore/issues/14002.  I may see if I can fix that as well, should also be simple once I find the right place in the code.

**Comment by MarcSabatella** [comment]
The PR #14669 fixes this by making sure add, sus, no, and omit *all* get raised if you apply a modifier offset.  All of them suffer the same issue.

And in fixing that, I uncovered a bit more about how this happened in the first place - it's because "sus" is explicitly *not* meant to be raised in the "Jazz" style while "add", "no", and "omit" are.  Because, Brandt/Roemer.  So the code itself is designed to put them all on the baseline, and then chords_jazz.xml explicitly raises add/no/omit.  But outside that world, I don't think anyone else would expect sus to be treated different from the others.

Which leads to another similar bug in the jazz style where if you use sus with parentheses, the opening bracket gets raised but the sus does not.  Unfortunately I don't have a good simple risk-free fix for that, and think it should wait until we can hopefully revisit the GSoC work.
