### ISSUE TITLE
[MU4 Issue] Muse Hub not supported in Ubuntu 18.04

### ISSUE THREAD

**Issue by gandsnut** [musescore/MuseScore#14361]
Trying to install Muse Hub on Ubuntu 18.04

Checked in Synaptic for libgcc-s1 :  not found

![muse-hub_install_error1](https://user-images.githubusercontent.com/29338195/200166927-aaa353cb-8d26-4690-8df4-0403c64fa96f.png)

![muse-hub_install_error2](https://user-images.githubusercontent.com/29338195/200166928-8cd1fcbb-8d72-4466-9736-204375200019.png)

![muse-hub_install_error3](https://user-images.githubusercontent.com/29338195/200166929-f6ba30f7-6a20-4b34-960d-b23a9078c692.png)

![muse-hub_install_error4](https://user-images.githubusercontent.com/29338195/200166930-ca621aa1-9c2d-43a3-ae66-b2debecfb511.png)

![muse-hub_install_error5](https://user-images.githubusercontent.com/29338195/200166931-255546a2-0aa9-4d52-a959-99d0240c4253.png)

**Comment by iamtesch** [comment]
Due to the EOL of Ubuntu 18.04 in the next few months, and the difficulty of packaging a single .deb that works on 18.04 through 22.04 (due to some major system package changes), we decided we could not at this time support Ubuntu 18.04.

Sorry for the bad news, and I hope this is understandable.  Is there something preventing an update to a more recent version in the near future for you?

**Comment by gandsnut** [comment]
Will 20.04 be sufficient?

**Comment by Tantacrul** [comment]
Sounds like we can close this? If anyone disagrees, let me know!
