### ISSUE TITLE
MuseSounds will not show up

### ISSUE THREAD

**Issue by njimenez07** [musescore/MuseScore#14453]
I have gone to the hub and downloaded all of the sounds, but I cannot activate them at all

**Comment by iamtesch** [comment]
Can you provide information on:
(1) OS version
(2) Hub version
(3) MuseScore version
(4) The results of the diagnostics > musesampler info menu item
(5) What the symptoms are (are they not showing up in the mixer dialog, are they not playing back, are you having trouble finding where to set them?

Thanks!

**Comment by njimenez07** [comment]
I'm not great with technology, but I'll answer each of these to my best abilities
1) Windows 10
2) 0.0.9.515
3) 4.0.0.223072007
4) It just says "MuseSampler lib not found"
5) If I open the mixer, it does not provide me with the option to set to MuseSounds. If I go to View > Playback Setup, it is grayed out and says "Inactive"
![Screenshot (4)](https://user-images.githubusercontent.com/117788672/201079820-efbc22f6-ccd2-4a0d-aff8-c2c3d5a9a966.png)

![Screenshot (2)](https://user-images.githubusercontent.com/117788672/201079856-d7b6724f-816d-4f46-a3e6-31007a2207bd.png).

**Comment by LuisLiszt** [comment]
Go to C:\ProgramData\MuseHub\Downloads\Installers . In one of the folders in this folder, there will be .zip file called "MuseSamplerCoreLib". Open it and extract the file inside into the bin folder of your MuseScore4 folder (probably located in C:\Program Files\MuseScore 4 ). Open MuseScore4, this should fix the issue.

**Comment by merc4derp** [comment]
Having the same issue. Tried everything I could think of, Muse Sounds are all installed through the hub, but musescore can't see them.

Here's my info as requested from the other poster earlier

OS: Windows 11 Pro 22H2 22621.819
Hub: 0.9.9.515 (x64)
MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155
MuseSampler lib is not found
The symptom is they're not showing anywhere in MuseScore but they have been downloaded and they seem installed in the hub.

As for the suggestion to copy MuseSamplerCoreLib zip posted earlier, the only MuseSampler reference I could find was a MuseSampler folder under programdata that had a since .config file inside pointing to the download directory of Muse Sounds.

Seems to me that this sampler whatever it is, isn't included in the download package and that's what's breaking it.

Any suggestions?

**Comment by MalignantCarp** [comment]
I'm experiencing the same issue. Windows 10 Pro 21H2 19044.2251.
MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155
Hub is Hub: 0.9.9.515 (x64)
I've reinstalled MuseHub and MuseScore three times with no success. Not finding a copy of this MuseSamplerCoreLib.zip, either. Should it matter that I have a custom installation directory?

**Comment by iamtesch** [comment]
We have fixed this, and should have a new release of Muse Hub out soon that addresses the issue on affected systems.  Sorry for the inconvenience!

**Comment by iamtesch** [comment]
Can you confirm if this is still happening?  This should now be fixed

**Comment by MalignantCarp** [comment]
> Can you confirm if this is still happening? This should now be fixed

Alas, I cannot confirm as yet. Need to wait until #14975/#14976 and #15032 are resolved to test the fix.

**Comment by MalignantCarp** [comment]
Okay, this now seems to be fixed for me.

**Comment by vpereverzev** [comment]
doesn't occur to me as well on Windows

**Comment by Tantacrul** [comment]
I have interviewed 20 new users over the last two days and no one reported this problem. I think we can close it.
