### ISSUE TITLE
[MU4 Issue] Staff Text won't work for articulation changes during Playback

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#14455]
So I understand that there are some articulation texts available, but whenever I insert the name of the articulation from the staff text presets, the articulation playback doesn't change for either MS Basic or Muse Sounds.

For example, if I wan the strings to play in a sul ponticello setting, or have the saxophones use non-vibrato, I would of course type them in, but there are no articulation texts for these specific ones, and it doesn't help inserting the name of the articulation using staff text. In MuseScore 3, I could customize the sounds of the articulations with the staff text properties, but NOT in MuseScore 4, which only has Swing and Capo settings.

**Comment by Tantacrul** [comment]
There are specific objects in the 'Text' palette you can add for the 'Sul Pont.' and 'non vibrato' (and col legno and others besides).

We have removed the old MS3 staff text properties system for assigning sounds because it is incompatible with our new setup. We are going to instead implement much more flexible systems for assigning sounds to text (and symbols) in a later release. For now, you should just use the appropriate directions in Palettes - and adjust the wording as you see fit.

**Comment by cunningar0807** [comment]
@Tantacrul I understand, though I StILL DON'T see the non-vibrato text in the Master Palette, neither con-sordino. Plus, the sounds don't change when I edit an articulation text. I forgot to mention that Mute and Open articulations don't work in the Muse Brass, and vowel changing doesn't work in Muse Choir when inserting a lyric.

**Comment by Tantacrul** [comment]
Brass mutes should be working shortly. That's a known issue. In the 'Text' palette. Try the 'more' option to find additional performance directions. Worth mentioning that not all text will trigger sounds. Some (like col legno) will.

Choir vocals will not respond to changes in lyrics for this version I'm afraid.

**Comment by cunningar0807** [comment]
I see. So when will the non-vibrato articulation text come out soon? I tried inserting "Normal" in some sax parts, but they still wouldn't use non-vibrato.
