### ISSUE TITLE
[MU4 Task] No dynamic options in the Properties panel when compared to MU3

### ISSUE THREAD

**Issue by matts5323** [musescore/MuseScore#14472]
Would love to see more options in the properties panel in MU4 that are from MU3. Currently, I can't find a way to customize dynamics or any other element as deep with the properties panel in MU4 the same way I could with the inspector in MU3. Maybe I'm missing something?

https://user-images.githubusercontent.com/58175783/201242944-b3d0cbfc-b9d9-4a4e-8216-a7352b0a0a78.mp4

**Comment by Tantacrul** [comment]
We have removed all playback settings for dynamics because the velocity system in MS3 is incompatible with the new MS4 system. We want velocity information to be stored in one place (a velocity 'lane), which we will be implementing shortly.

In the meantime, velocity settings are found on notes only.

As for any other (functional and non-functional) settings:
1. Begin hook / end hook are nonsensical options, so we have removed them
2. The options to change the hairpin to a different type of hairpin are better off being removed because the user can simply add their desired hairpin via Palettes
3. Placement: 'above/'below' can be found in 'more'
4. All positioning options (under 'Element' in MS3) can be found by clicking on 'Appearance'
5. All options in 'Text' in MS3 can be found in 'Text' in MS4, although less common options are tucked away to avoid over complicating the interface
