### ISSUE TITLE
[MU4 Issue][Sound] No Sound for sax baritone under B4 note (With Muse Sounds)

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14507]
No Sound for sax baritone under note in Green (With Muse Sounds)
![image](https://user-images.githubusercontent.com/1835871/201534897-5afaa62b-97e0-4a08-a75a-bd75e4599687.png)

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223170411, revision: github-musescore-musescore-7b85777

**Comment by cbjeukendrup** [comment]
Actually this turns out to be a mapping issue. If you choose the Baritone Saxophone instrument, it will by default use the Alto Sax, which goes only to B4 (C#3 in concert pitch), which seems reasonable to me for an Alto Sax. If you select the Baritone Sax sound manually in the Mixer, it will go down to A3 (C2 in concert pitch), which seems reasonable to me too.

With the lowest note of the Baritone Sax sound, something curious happens: it is only audible with ***mf*** dynamic or louder. For softer dynamics, the lowest note doesn't sound.

**Comment by erinic04** [comment]
Just FYI, I just tested this and it is fixed @davidwhearn

**Comment by cbjeukendrup** [comment]
This seems fixed for me too, including the extra issue about the lowest not at soft dynamics. Closing as completed!
