### ISSUE TITLE
[MU4 Issue] Add a Measure on mmRest with "Ins" Add measure at end of score, revert with Ctrl+z crash MS4

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14556]
**Describe the bug**
] Add a Measure on mmRest with "Ins" Add measure at end of score, revert with Ctrl+z crash MS4

**To Reproduce**
1. Create a score with an empty measure between two measures with notes
2. Select empty measure
3. Pressing the "Ins" key adds a measure
4. Switch to mmRest mode
5. Select the mmRest Measure
6.  Pressing the "Ins" key adds a measure at end of score
7. Reverting with Ctrl+Z crash Musescore

https://user-images.githubusercontent.com/1835871/202280840-d17fd03b-8a2b-4bed-ae70-1d12105e8fbf.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223200405, revision: github-musescore-musescore-4bd88ed

**Comment by oktophonie** [comment]
https://github.com/musescore/MuseScore/pull/14642 appears to fix the crash, at least.
What remains wrong (and is a regression) is that Ins, when a multirest is selected, inserts the new bar at the end of the score, rather than after the selected rest (where it should automatically combine into the multirest, as happens in MU3)

PS. The cats are very pretty
