### ISSUE TITLE
[MU4 Issue] No space after dot or comma in UI on macOS

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#14560]
Whenever a UI string contains a dot (period/full stop) followed by a space, or a comma followed by a space, the space is missing in the UI.

**Screenshots**

<img width="700px" src="https://user-images.githubusercontent.com/11011881/202306710-54eb723c-3497-40ae-b43c-7cbc4bc96699.png"/>

<img width="700px" src="https://user-images.githubusercontent.com/11011881/202307366-d9ed710c-d388-47e3-96ab-8e87abd140f8.png"/>

<img width="700px" src="https://user-images.githubusercontent.com/11011881/202306379-8952d10a-5e1d-4280-af3e-62686867c4ae.png"/>

**Platform information**
 - OS: macOS Big Sur

**Comment by shoogle** [comment]
Closing as this is a [Qt bug](https://bugreports.qt.io/browse/QTBUG-88495) that is fixed in Qt 6. It's also fixed in Qt 5.15.3 but sadly that's [not available for open source](https://www.phoronix.com/news/Qt-5.15.3-LTS-Released), at least [not via the official Qt Online Installer](https://raymii.org/s/blog/Qt_5.15.3_OpenSource_released.html).

**Comment by cbjeukendrup** [comment]
Indeed, this is fixed in 5.15.3 and higher. The latest available open source version is 5.15.7 at the moment. It is provided by HomeBrew, and I use it on a daily basis. If we want, we can easily put that on our S3 server, from where it is downloaded during CI builds.

(HomeBrew even seems to provide an ARM64 version, but I can't get that to work with MuseScore.)

**Comment by shoogle** [comment]
That's something to check with the other developers. It should be safe to upgrade to a patch release, but it's not guaranteed of course. We might prefer to stick with what we are currently using for the time being.
