### ISSUE TITLE
[MU4] Layout objects (frames) should not affect parts and vice versa

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#14591]
Description:
When inserting a frame in a part, it appears also in the score. The same happens the other way around.

Reproduce:
1. Open a score with music
2. Select a bar
3. Palettes > Layouts > insert horizontal frame
4. Open the parts > the layout element is applied to the parts too

Expected behaviour:
The layout element is displayed only in the score or in the part depending on which one is applied to. Having it show on both makes it impossible to customise the layout of single scores and have different layouts for score and parts.

**Comment by JeffRocchio** [comment]
throwing down my 2-cents... I agree with Marc. The ability to format parts independently of each other, and the master score, is very, very important (at least to me it is). On the other hand it can be quite tedious due to having to deal with certain ripple-effects on the one hand (e.g., frames) and certain things not propagating (e.g., I change the subtitle text style in the 'Melody' part, yet changing that style in a given part does **not** ripple across to the other parts, so I have to tediously go through every part to make that format change. So a better way to manage all that would be nice. Tho I couldn't say how best to design it. (Except to put forth the idea that a 'Style' change should ripple, format changes made to an individual element should not ripple. Not sure what to do about frames.)

**Comment by MarcSabatella** [comment]
Actually, style changes are easy - change one part, then hit "Apply to all parts" (in the Format / Style dialog).

**Comment by JeffRocchio** [comment]
> hit "Apply to all parts" 

I do use that all the time in MS3. But as I was working through a multi-part test score for this latest MS4 nightly build it never gave me that option, which I was looking for. Sometime in the next day or two I'll try it again because, yeah, that really should still be there.

**Comment by MarcSabatella** [comment]
It's the same place it has always been, at the bottom of the Format / Style dialog box.  Only enabled if you're currently viewing a part.

**Comment by JeffRocchio** [comment]
Yes, I see it now. I can only assume the UI changes confused my tired brain.

**Comment by oktophonie** [comment]
Closed as incorporated into https://github.com/musescore/MuseScore/issues/16544
