### ISSUE TITLE
[MU4 Issue] Crash when appending measures to new score

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14597]
**Describe the bug**
Appending measures with Ctrl+B immediately upon creating a score crashes

**To Reproduce**
1. Create a new score with treble clef template, all default settings
2. When score appears, press Ctrl+B
3. See error: crash

**Expected behavior**
Measure should be appended.

**Platform information**
 - OS: Linux

**Additional context**
For me, this is reproducible 90% of the time if I literally do the Ctrl+B first thing after creating the score.  I did wait for "loading audio samples" to complete (I have MS Basic as my default sounds).  But if I do anything else first, then Ctrl+B works.  This includes, simply scrolling.  Or just waiting an additional 5 seconds.  So I assume there is something still going on in the background during those first few seconds.

**Comment by cbjeukendrup** [comment]
I can reproduce this, and have been trying to investigate it. The problem is that some RepeatSegment somehow contains pointers to invalid measures, leading to use-after-free, but it is unclear how those get in there. Address Sanitizer seems a little bit confused about when these measures are deleted; it gives stack traces that make very little sense to me.

**Comment by DmitryArefiev** [comment]
Fixed in #14638
