### ISSUE TITLE
[MU4 Issue] MuseHub/MuseSounds - Guess I'm too poor (MacOS 10.15)

### ISSUE THREAD

**Issue by rnbrocker** [musescore/MuseScore#14602]
I know it's formulated a bit mean, but is there any reason that MuseHub (and currently MuseSounds) is only available on newer Macs? I think this is just bad practice. I liked MuseScore3 bc you could basically run it smoothly on a toaster – and it produced nice looking and sounding scores, when you knew how to use the program. I often use it to transcribe baroque manuscripts that aren't recorded yet. Plus: I like all the new features for composing that MuseScore4 offers. But keep in mind that we are in a major economical crisis. I think it's just not a good idea to lock people with older computers out. Don't get me wrong. I'D LOVE to buy a new computer, I simply don't have another 1.5k€ lying around here right now, and I still would love to hear how the sound library has improved.

So, yeah, like I said, just keep that in mind – this I would suggest.

**Comment by cbjeukendrup** [comment]
The reason is that MuseHub is built using macOS APIs that are only available on BigSur and later. I'm also hoping that Muse Hub will eventually work on all the same macOS versions as MuseScore (i.e. 10.14 and higher), but that isn't likely to happen in the very near future, unfortunately. 

I'll close this for now, but we do have it in mind. On Linux, there's some work to do too, in expanding Muse Hub's availability.
