### ISSUE TITLE
[MU4 Issue] Crash when opening MuseScore 3 score with nested frames

### ISSUE THREAD

**Issue by mxmou** [musescore/MuseScore#14643]
**Describe the bug**
In MuseScore 3, it was possible to insert a horizontal frame inside a vertical frame. Opening a score with nested frames in MS4 results in a crash.

**To Reproduce**
Open this score in MuseScore 3 and 4 and compare the results: [ms4_crash_test.zip](https://github.com/musescore/MuseScore/files/10059796/ms4_crash_test.zip)

**Expected behavior**
The score would open normally.

**Platform information**
 - OS: Windows

**Comment by asattely** [comment]
The source of this issue is that a Box (H or V) apparently require that they are parented to system, not to other boxes: https://github.com/musescore/MuseScore/blob/46ce4889fcec55e4f1a1e949f51c8d73c7388917/src/engraving/libmscore/box.cpp#L317

I'll do some more research into making the changes the comments suggest.
