### ISSUE TITLE
[MU4 Issue] Adding Or Removing A Niente Circle Only Effects Currently Opened Part

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#14676]
**Describe the bug**
Adding or remove a niente circle to/from a hairpin in a part or the main score does not effect the main score / parts.

**To Reproduce**
1. Add or remove a niente circle to/from a hairpin in a part or the main score
2. Click on the main score or the respective part
3. niente at the end of the hairpin did not appear / was not removed

**Expected behavior**
Niente circle at the end of the hairpin should be toggled in the part/main score as well

**Screenshots**
Even got you guys a screen recording :D
[Bildschirmaufnahme 2022-11-23 um 00.07.40.zip](https://github.com/musescore/MuseScore/files/10071737/Bildschirmaufnahme.2022-11-23.um.00.07.40.zip)

**Platform information**
 - OS: OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072008, revision: github-musescore-musescore-2c34155

**Comment by MarcSabatella** [comment]
Indeed, since day one of the linked parts feature, it's been known there should be a way of providing control over what gets linked and what doesn't.  Both to *force* linking of properties that are normally *not* linked, and to *prevent* linking of properties that normally *are*.

I've thought about this some over the years, and I do think the internal architecture would support it without major changes, if only we had a design for how the user might exercise this ability.

**Comment by oktophonie** [comment]
Closed as incorporated into Closed as incorporated into https://github.com/musescore/MuseScore/issues/16544
