### ISSUE TITLE
[MU4 Issue] ALL audio sources cannot be used normally after uninstallation and reinstallation

### ISSUE THREAD

**Issue by ZiwenYin1014** [musescore/MuseScore#14694]
### Describe the bug
**ALL** audio sources cannot be used normally after uninstallation and reinstallation

### To Reproduce
1. Uninstall it
2. Reinstall it
Repeat several times (about 3,4) and all audio sources, including the original Mubasic, Musoud and vst, have disappeared and cannot be loaded. Later, I reinstalled it several times, even reinstalling Muse Hub without changing it back to its original state .(all functions can be used normally at the beginning)

### Screenshots
![X-85-TC52-NYCHMTXH1-B-EWP.png](https://i.postimg.cc/PrKfg5Wh/X-85-TC52-NYCHMTXH1-B-EWP.png)
Because I use Chinese, I would like to translate it. The first line is no effect plug-in. Normally, Mubasic appears in the newly installed software (after all "basic"), but there is **nothing** here and the sound cannot be loaded normally. (I can use it normally before)
### Platform information
Windows 11 22H2

I would like to express my gratitude to the developers for allowing us this fabulous software. It would be my honor if you could give me a reply.

**Comment by cbjeukendrup** [comment]
The dropdown on the screenshot is not the "sound source" dropdown, but the "effects" dropdown. So that's why MS Basic, VST and Muse Sounds won't appear there :)

This screen recording is perhaps the quickest way to explain what I think that's happening:

https://user-images.githubusercontent.com/48658420/203607241-6723d164-1815-4977-a79b-52462c65d10c.mov

Also, as you can see in the following recording, the Mixer window sometimes becomes smaller when you resize the MuseScore window:

https://user-images.githubusercontent.com/48658420/203607516-d1bbda43-39b0-41bb-b55e-dce3d22e1e71.mov

I believe that this happens not only when you "actively" resize the MuseScore window, but also when the window is closed while it has some size but has a different size when re-opened. 

So _that_ might be how your Mixer got into this (somewhat confusing) state :)

Please let me know if this is helpful and if it makes any sense to you!

**Comment by ZiwenYin1014** [comment]
I'm gonna cry because I'm so stupid and careless.
It's very helpful to me! This is very helpful to me.  :)
