### ISSUE TITLE
[MU4 RC] Update All Translation Files

### ISSUE THREAD

**Issue by Gootector** [musescore/MuseScore#14764]
Please update all translation files before the release of MuseScore 4 RC. Instruments too. Thanks.

**Comment by cbjeukendrup** [comment]
@Gootector We don't need to worry very much about this, since the latest translations are downloaded and packaged automatically when we create the release build. However, we will still update the translation files at some point so that nightly builds (and potential third-party builds) will also have the latest.

**Comment by Gootector** [comment]
@cbjeukendrup Thanks for the info. I didn't know that translations are downloaded and packaged automatically during the release build.
BTW Could you update the translations in the master, for example, after the release of MuseScore 4.0 RC?

Thanks and greetings,
Gootector

**Comment by cbjeukendrup** [comment]
> BTW Could you update the translations in the master, for example, after the release of MuseScore 4.0 RC?

Yes, that's certainly possible!

**Comment by Gootector** [comment]
OK, thanks. So, I'm closing this issue.
