### ISSUE TITLE
[MU4 Issue] Finale Maestro / Broadway: repeat dots appear too low

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14787]
Expected behaviour (Leland and all other fonts):
<img width="108" alt="Scherm­afbeelding 2022-11-27 om 15 22 52" src="https://user-images.githubusercontent.com/48658420/204140259-99ddd6dc-fb6f-4949-bd4b-d02cb7d43686.png">

Actual behaviour with Finale Maestro and Finale Broadway:
<img width="108" alt="Scherm­afbeelding 2022-11-27 om 15 28 51" src="https://user-images.githubusercontent.com/48658420/204140548-03d05d4e-83af-4f6c-b413-66271fa850c2.png">

This is obviously an issue with these fonts rather than with MuseScore, but we might want to add a workaround for the time being. 

(That brings us to another question: how do we know when there are updates available for the Finale fonts? Do we know where to download updated versions of these fonts?)

**Comment by Jojo-Schmitz** [comment]
Somhwo sounds familiar.
See https://github.com/musescore/MuseScore/blob/fab9db01fa9e52f39ae74600dd5a412f1b950860/src/engraving/libmscore/barline.cpp#L505-L512

**Comment by Jojo-Schmitz** [comment]
IHMO the contrary is the case: "Emmentaler, Gonville, MuseJazz: repeat dots appear too high" with a workaround for that being in place, but by accident (ommission) also affecting Finale Maestro / Broadway

**Comment by Tantacrul** [comment]
@oktophonie - which set of fonts is at fault here? 😄

I'm going to make an uninformed observation that if you have two camps:

1. Gonville, MuseJazz and Emmentaler 
2. Bravura, Leland and Petaluma

Group 1. is more likely to be wrong! I say this having had to make a ton of changes to Emmentaler last year so it corresponded with the SMuFL spec properly. It'll be just my luck now to discover I'm wrong.

**Comment by cbjeukendrup** [comment]
@Tantacrul See https://github.com/musescore/MuseScore/pull/14797; Jojo has created a fix already

**Comment by Jojo-Schmitz** [comment]
Add Finale Maestro and Finale Broadway to the 2nd camp, makes it a 3 : 5 majority vote ;-)
In the beginning (MuseScore 2!) It was 2 : 1 (Emmentaler, Gonville vs. Bravura).

**Comment by oktophonie** [comment]
Bravura is, as always, the model. 
The double dot glyph (E043) should have the dots vertically centered on (approximately) y=375 and y=625.
The single dot glyph (E044) should be vertically centered on y=0.

There is a question over which glyph is getting used; some fonts don't have the double dot glyph, and presumably will use Bravura's if it's called for. The single dot glyph will of course have to be used anyway for more than two dots, or for a non-standard line width, like in guitar tab.

Martin's uninformed observation about the camps turns out to be actually informed, and also right!
- Bravura, Leland, Petaluma, Finale Maestro have both glyphs, and both are correct;
- Finale Broadway doesn't have the double dot, but has a correct single dot;
- Emmentaler and Gonville don't have the double dot, and the single dot is too high;
- MuseJazz has a double dot which is correct, but the single dot is too high.

**Comment by Jojo-Schmitz** [comment]
The dingle dot `repeatDot` is used, always, unconditionally (and twice, of course).
And as you said: that is too high for Emmentaler, Gonfille and MuseJazz.
