### ISSUE TITLE
[MU4 Issue] Added sharp to the chord signature ?!

### ISSUE THREAD

**Issue by wyldcrd** [musescore/MuseScore#14789]
**Describe the bug**
Cannot use the shortcut **CTRL + #** (Option + #) to place a # symbol in a chord signature. This is a regression on older versions of MS4.
(https://musescore.org/en/node/337234)

**To Reproduce**
1. Option + # when adding an accidental to a chord 

**Expected behavior**
To be able to add these to chords:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/21022311/204341132-e684a332-2d22-456b-9d4d-a87811e0713f.png">

**Platform information**
 - OS: macOS Monterey 

**Additional context**
https://musescore.org/en/node/337234
(Reposted for Claudio Riffero)

**Comment by Tantacrul** [comment]
Urg. I noticed this over the weekend. @cbjeukendrup - if you are looking for something urgent in Release, this is a really bad one.

**Comment by cbjeukendrup** [comment]
@Tantacrul I was a bit confused at first, because on a Dutch keyboard the only key that requires the Option key is the `€` character. But apparently on other keyboards even the `#` needs this. 

Anyway, PR created: https://github.com/musescore/MuseScore/pull/14812

I could obviously only use the `€` character to test, but this must also fix it for the `#` character on British keyboards.
