### ISSUE TITLE
中国大陆登不上去

### ISSUE THREAD

**Issue by molihuaacha** [musescore/MuseScore#14794]
我要是能登上去我还搁这给你反馈？

**Comment by cbjeukendrup** [comment]
Maybe @Harmoniker1 can help translating :)

macOS translates it as "Mainland China can't log in". I assume that is, you can't log in with your MuseScore.com account in the MuseScore desktop app?

**Comment by scilxurkel001** [comment]
请遵守社区规范。
我们讨论的是MuseScore3/MuseScore4的软件的Bug。
不是你家网络的问题！
中国大陆登不上去，是因为中国的防火长城把MuseScore.com的域名墙了！你需要用VPN访问此域名。
这不叫软件的问题！这是中国本身网络的问题！
请不要再次在GitHub的Issues专栏反馈这类问题！
-----------------------
Please follow the community norms.
We are discussing bugs in the software for MuseScore3/MuseScore4.
Not a problem with your home network!
Mainland China can't log on because the Great Firewall of China has walled up the MuseScore.com domain! You need to use a VPN to access this domain name.
This is not a software problem! This is a problem with China's own network!
Please don't feed the Issues section of GitHub with this kind of problem again!

**Comment by scilxurkel001** [comment]
> 

以后有中文的问题可以给我帮忙翻译，我是中国本土人。
In the future, you can give me help translating Chinese questions, I am a native Chinese.

**Comment by scilxurkel001** [comment]
> Maybe @Harmoniker1 can help translating :)
> 
> macOS translates it as "Mainland China can't log in". I assume that is, you can't log in with your MuseScore.com account in the MuseScore desktop app?

以后有中文的问题可以给我帮忙翻译，我是中国本土人。
In the future, you can give me help translating Chinese questions, I am a native Chinese.

**Comment by Harmoniker1** [comment]
@scilxurkel001 MuseScore.com并没有被墙，只是有时连接不稳定。
@molihuaacha 这里的确只应讨论与MuseScore应用本身相关的问题，而不是网络问题。
