### ISSUE TITLE
[MU4 Issue] MuseScore crashes when opening .mscz file w/ effects

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#14826]
So I was testing out Muse Sounds with one of my old MuseScore files, and the results sounded great. I tried adding Muse effects like Dee-Ess and ProEQ, and saved the .mscz file. But when I opened it back up in MuseScore, the program crashes after loading everything.

I have the .mscz file right here just to see if you guys might end up with the same issue: https://we.tl/t-chTMSkwG9u

**Comment by Tantacrul** [comment]
Ah! This is crashing for me too. Nice find!

**Comment by Tantacrul** [comment]
For a permanent link, here's that same file: https://www.dropbox.com/s/2aq7mo9fs84i5ma/Traumerei.mscz?dl=0

**Comment by Tantacrul** [comment]
@cunningar0807 - we think the file became corrupt due to some older issues which we've since resolved. Here's an uncorrupted version, which should work now.

https://www.dropbox.com/s/lzt7yeja0lmuar6/Traumerei_ressurected.mscz?dl=0

I'm closing this issue unless you find it hasn't been solved with this file. Thanks!
