### ISSUE TITLE
[MU4 Issue] Missing part-group stop in MusicXML export

### ISSUE THREAD

**Issue by lvinken** [musescore/MuseScore#14859]
See instructions in https://musescore.org/en/node/337405, the MusicXML file exported from the blank staff contains a part-group start, but the corresponding part-group stop is missing. Resulting files attached.

[no-part-group-stop.zip](https://github.com/musescore/MuseScore/files/10129792/no-part-group-stop.zip)

**Comment by Jojo-Schmitz** [comment]
Apparently affects MU3 and MU4

**Comment by lvinken** [comment]
Indeed, in MU4 the same result is produced when using "New score", "Create from template" with category "General" and template "Treble Clef".

**Comment by Jojo-Schmitz** [comment]
So this is maybe also a problem with that template?

**Comment by lvinken** [comment]
The issue is caused by a combination of two things:
- the treble clef template (single part / single staff) incorrectly contains a bracket (with span 2)
- the MusicXML exporter does not detect this condition and fails to generate a part-group stop (because the calculated staff to end the span on is never found)

**Comment by lvinken** [comment]
Fix available in my 14859-part-group-end branch, work in progress, test and cleanup still required.

**Comment by Jojo-Schmitz** [comment]
I wonder why the bass clef template doesn't have the same problem (or maybe it does?), it too has `<bracket type="1" span="2" col="2"/>`

**Comment by Jojo-Schmitz** [comment]
Difference with and without your change (in a backport to 3.x, haven't tested with 4.x), when importing that MusicXML (into 3.6.2): with it there's now a single-staff brace, which wasn't there before.
With and Without, when adding another (bass-clef) staff: there's no brace covering both staves, like it is when doung the same with a score created from the template

**Comment by MarcSabatella** [comment]
To me the behavior described in terms of the bracket is good - no bracket by default, but a curly brace appears automatically when adding a second staff.  This works as expected in 3.6.2 in this case, but not really well overall, because the curly brace *also* appears when adding a violin or any other instrument below the original staff.  Current MU4 RC is the same.

I assume the open bracket is the cause of the bug when adding a second instrument.  What I don't know is if it is also the cause of the *good* behavior when adding a second staff to the original instrument.  I'd like to think the automatic bracketing system is smart enough to do that on its own.

**Comment by Jojo-Schmitz** [comment]
Hmm, true, so the brace is used not only when adding a staff to the existing instrument, but also when adding another instrument.
That then should finally be enough of a reason to get rid of it in the template

**Comment by lvinken** [comment]
Pull request fixes only the incorrect MusicXML export, but leaves everything else untouched.

**Comment by Jojo-Schmitz** [comment]
My backport to 3.x also fixes the templates
