### ISSUE TITLE
Hide 'Advanced' tab in 'Learn' section

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#14886]
**Describe the bug**
Since there will be no videos ready for the release of MS4, we can't have this tab empty. We should simply hide it for now:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/21022311/205305647-bf268a36-a8c9-443a-837f-944f1182f474.png">

When more content is ready, we'll enable it again in an upcoming minor / patch release.

**Comment by MarcSabatella** [comment]
FWIW, I *have* been working on content that could be appropriate for this, although it's no big deal if they don't get used.  Here are two examples I recently created:

Piano music: https://youtu.be/IPluwNLI658
Choral music: https://youtu.be/ky8A3534d6A

The plan is to also have one for lead sheet and one for ensemble music, and the music and outline is ready - they had been waiting for some bug fixes that appear to be going in now.  So I could have those done in the next few days.

If these are not the sort of thing you're looking for, that's fine.  BTW, these are all "part 1 of 2" because there is a second part I'm including within my course.

**Comment by Tantacrul** [comment]
I think it'll probably be safer to ditch 'advanced' for now (rather than face more issues) and simply link to a video or two of yours in the regular section. Later, we can move them over to advanced if we want.

**Comment by MarcSabatella** [comment]
That's fine, whatever works.  I'll be using the videos myself either way, but if there is a way to surface them more broadly, great.
