### ISSUE TITLE
[MU4 Issue] Audio playback restarting, but playback indicator not restarting after a pause

### ISSUE THREAD

**Issue by pmarx810** [musescore/MuseScore#14910]
When using the space bar to pause playback, the indicator line does not move back to the start of the selected playback when the space bar is pressed again, causing the playback indicator to be out of sync with the actual audio.

Reproduce Error:
1. select a point to start playback and press the space bar
2. Use the space bar to pause
3. once again, press the space bar to restart playback from the initially selected point

Expected Behavior:
Playback indicator jumps back to the initially selected point and remains in sync with audio playback

 - OS: Windows 10

**Comment by MarcSabatella** [comment]
I'm a little confused, the playback isn't *supposed* to start over from the beginning, but instead it's meant to continue where it left off.  And for me that's exactly what it does.  Are you testing using the RC?  Cna you attach your score and also show a screen recording of what you are seeing if you continue to experience problems?

**Comment by MarcSabatella** [comment]
Hmm, now I'm actually seeing this as well: I have somehow gotten into a situation where every time I start playback, it plays from the beginning, but the playback cursor shows the location of where the playback *should* be (continuing where it left off).  I have no idea what put me into this state, however.  It seems to only happen when using Muse Sounds, though - the problem goes away when I switch to MS Basic.  Maybe that's why I couldn't reproduce this before.

**Comment by MarcSabatella** [comment]
Here it is in action:

https://user-images.githubusercontent.com/1799936/205520550-ac2f0764-aee2-4269-8ebc-95ffb3caabfa.mp4

**Comment by MarcSabatella** [comment]
Here it is in action:

https://user-images.githubusercontent.com/1799936/205520700-ff5eb5a8-dbd5-47da-8619-95a135726357.mp4

**Comment by pmarx810** [comment]
@MarcSabatella just now seeing this, looks nearly identical to what I previously identified.

**Comment by RomanPudashkin** [comment]
@pmarx810 @MarcSabatella @Tantacrul please check it again on the latest master

fixed in https://github.com/musescore/MuseScore/pull/14987
