### ISSUE TITLE
[MU4 Issue] (RC) MS4 RC instantly crashes when opening a score with Compress effect

### ISSUE THREAD

**Issue by LuisLiszt** [musescore/MuseScore#15026]
**Describe the bug**
When I open this score the second RC instantly crashes. With RC1 everything was fine.

**To Reproduce**
1. Use RC2.
2. Open this score.

**Expected behavior**
MS4 should open normally.

**Platform information**
 - OS: Windows 11

[Score.zip](https://github.com/musescore/MuseScore/files/10179402/Score.zip)

**Comment by LuisLiszt** [comment]
Btw. this doesn't only happen with this score, it happens with alot of scores of mine...

**Comment by Eism** [comment]
@LuisLiszt 
Please add a few more scores for testing

**Comment by RomanPudashkin** [comment]
The app crashes because of the Compress effect on Klavier. We call IComponent::setState (vstplugin.cpp, line 254) and this causes the app to crash

**Comment by vpereverzev** [comment]
@LuisLiszt 

The score's audio settings have been corrupted, unfortunately. But I have two good news for you:
- https://github.com/musescore/MuseScore/pull/15057 - should fix the root cause of that corruption
- here is "non-corrupted" version of the score you've attached - [Fantaisie-Impromptu.zip](https://github.com/musescore/MuseScore/files/10188052/Fantaisie-Impromptu.zip)

**Comment by LuisLiszt** [comment]
@vpereverzev First of all, thank you! But will the RC with the fix be able to open my other files too? Or do they need to be manually fixed?

**Comment by vpereverzev** [comment]
> @vpereverzev First of all, thank you! But will the RC with the fix be able to open my other files too? Or do they need to be manually fixed?

Let's chat about this in Discord
