### ISSUE TITLE
[MU4 Issue] Broken stems in drum score

### ISSUE THREAD

**Issue by RobFog** [musescore/MuseScore#15166]
**Describe the bug**
In a drum score, trying to write a) bass drum, pedal hi-hat or high floor tom and b) other parts of the drum set in one voice while otherwise using MuseScore defaults (stem directions downward for bass drum, pedal hi-hat note, high floor tom) results in broken stems. This happens both when entering notes in a newly created drum score in MuseScore 4 and when opening a drum score created in MuseScore 3 in MuseScore 4.

By default, MuseScore's drum input places bass drum, pedal hi-hat and high floor tom in the second voice but in drum notation it is also common to place all parts of the drum set in one voice.

**To Reproduce**
1. Create a drum score in MuseScore 4.
2. Write consecutive beamed notes (16ths, quavers, …) of bass drum and snare drum hits with both placed in the same voice.

or
1. Open the attached score in MuseScore 4: [CultOfPersonality-IntroFill.zip](https://github.com/musescore/MuseScore/files/10228439/CultOfPersonality-IntroFill.zip)
2. See the broken stems in bars 1, 3 and 5.

**Expected behavior**
No broken stems

**Screenshots**
MuseScore 3: <img width="1392" alt="MuseScore3" src="https://user-images.githubusercontent.com/2267373/207615568-0f5e7f25-a88d-4158-a986-19b9bbc93867.png">
MuseScore 4: <img width="1392" alt="MuseScore4" src="https://user-images.githubusercontent.com/2267373/207615319-91f879dd-28d0-4f13-91c6-fe7b97a118d2.png">

**Platform information**
 - OS: macOS 11.7.2, final release of MuseScore 4

**Comment by MarcSabatella** [comment]
These notes seem to have messed up stem directions - some pointing up, others pointing down, within the same beam.  MsueScre 3.6.2 would ignore this condition and use the overall beam direction in place of individual note stem directions.  Looks like that confused MuseScore.

Workaround: reset these stem directions to auto.  Shouldn't be a problem in a new score unless you are working from an unsuually customized drumset definition that attempts to force backward stems.  Looks like maybe this was the result of taking voice 2 notes and then changing them to voice 1?

**Comment by RobFog** [comment]
This is not about a "customised drumset definition". The defaults for bass drum and pedal hi-hat (and high floor tom, as I just found out) are stems down. MuseScore needs to be able to handle beaming notes where, by default, some stem directions are up and some are down.

**Comment by MarcSabatella** [comment]
I agree, as I said, this condition does need to be handled better.  I'm just pointing out, it's an unusual situation - this is *not* the default way drums are entered.  The original report didn't make clear what was actually going on when saying "This happens both when opening a drum score created in MuseScore 3 in MuseScore 4 and when entering notes in a newly created drum score in MuseScore 4".  It definitely doesn't happen in new scores *unless* you go out of your way in a way to override the defaults in way that might not have been obvious.

So I was trying to understand how the score got into this state, since that wasn't explained.  And along the way, my post was meant to clarify possible steps to reproduce this problem, and also provide a workaround - simply correct the stem directions.

**Comment by RobFog** [comment]
I agree that the issue description was not as clear as it could or should have been. I've rewritten it in an attempt to make it easier to understand.

Writing all parts of the drumset in one voice may not be MuseScore's default but it's anything but unusual when it comes to notating drums.

Thanks for the suggested workaround. I think it would be too much hassle having to do this all the time. I will stick with MuseScore 3 until this issue is resolved.

**Comment by MarcSabatella** [comment]
It's not unusual to write that way, but normally you'd simply alter the drumset definition if that's how you prefer to write.  Either to put both notes in the same voice by default, or to have the stem direction be auto.

**Comment by asattely** [comment]
I am working on fixing this one right now, but for now an easy workaround is to highlight the affected measure and press ctrl-R to reset shapes and positions.

**Comment by cbjeukendrup** [comment]
@Tantacrul @oktophonie I just thought, would this be a candidate for the patch release?

**Comment by MarcSabatella** [comment]
I know it's "only" an engraving issue (!) but it definitely does completely ruin the appearance of some scores, and it's probably the only engraving-relating issue I know of that is as bad, or as commonly reported.

**Comment by Tantacrul** [comment]
Since we're currently testing the first patch, which solves major corrupting files / crashing issues, I suggest we get that out and then add this to the second patch, which will fix the second tier of missing items and bugs.

It's simply a case of fixing the corruption issues as quickly as possible before too many people become affected.

**Comment by RobFog** [comment]
Any reason this has not been ported to 4.0.2, yet?

**Comment by cbjeukendrup** [comment]
It's in the 4.0.2 project at least, so probably yes. The linked PR is still in progress / in review, so therefore it is not ported yet.

**Comment by bkunda** [comment]
✅ Re-tested in macOS
