### ISSUE TITLE
[MU4 Issue] Custom interface font settings don't apply to top menu bar

### ISSUE THREAD

**Issue by Letheward** [musescore/MuseScore#15187]
**Describe the bug**

The settings under Preferences - Appearance - Appearance (`Font face` and `Body text size`) don't apply to the top menu bar of MuseScore.

**To Reproduce**

1. Open MuseScore 4
2. Go into Preferences - Appearance - Appearance
3. Change `Font face` to a non system default font (for example, `Comic Sans MS`)
4. Change `Body text size` to `18pt`

**Expected behavior**

Just as the rest of UI, the top menu bar should also renders using the custom font face, and using bigger font size.

**Screenshots**

![bug](https://user-images.githubusercontent.com/59071629/207781064-66fa3be2-0c20-4960-93f2-257b23126193.png)

**Platform information**

- OS: Windows 10

**Additional context**

This behavior is especially bad for Chinese locales on Windows, or any other locale + OS combination that Qt decided to choose a bad default font with.

Here is a screenshot of MuseScore in Simplified Chinese locale:

![bug_cn](https://user-images.githubusercontent.com/59071629/207771360-965911b4-d696-491b-af77-2a42bcf7e2cb.png)

I choose `Microsoft YaHei` (微软雅黑) for `Font face`, and it does apply to other parts of the UI. The menu bar still renders using the `simsun` (宋体) font, which is very ugly, and super blurry in this case. Since font size setting doesn't apply to menu bar either, there is no way to make this more readable, other than changing language.

(`Microsoft YaHei` is actually the **real** system default UI font for Simplified Chinese in Windows 10, not `simsun`.)

Similar problem in Traditional Chinese:

![bug_cn_t](https://user-images.githubusercontent.com/59071629/207774610-cc59237d-8b71-4afe-90c0-5d552cfb9c92.png)

**Comment by qaziquza** [comment]
You seriously had to pick comic sans as your example font, yes? There wasn't any other one in the world available? (I kid, of course)

In all seriousness, this is a rather major issue. I hope it gets fixed soon.

**Comment by Leonerd-04** [comment]
Can confirm this also happens on Linux.

I also hope this gets fixed soon, as the smaller font face is much harder for me to make out.

**Comment by Eism** [comment]
Fixed Font face is by design. see #8090 and #10214

@Tantacrul @jessjwilliamson what do you think about font size?

**Comment by Tantacrul** [comment]
Yes, we don't want to be interfering with the top menu, I'm afraid.

**Comment by Letheward** [comment]
> Fixed Font face is by design.

> Use native OS font for Windows (Segoe UI)

If the goal is to match native Windows default UI font for title bar, this is still a problem (at least for Chinese users), because the **actual** system default UI fonts in Windows 10 are **not** what showed in the last 2 screenshots.

Also, I will argue that letting users to change the font for this is a good idea anyway, especially when they already want to customize UI font. Adding this option doesn't prevent us from making the default settings default.

**Comment by Letheward** [comment]
@Tantacrul I think this issue should be re-opened, as it describes that behaviors in some locales didn't match with the design goals stated in #8090.

**Comment by Tantacrul** [comment]
It's not getting reopened. Please do not bother us with this any further.

**Comment by cbjeukendrup** [comment]
@Tantacrul There turns out to be a bug, so we can't say it's by design. Yes, it is by design that the menu bar uses the system font. _But that's broken for Chinese locales_. Apparently, the system font on Windows is not Segoe UI for these locales, but something else (`Microsoft YaHei` as mentioned?). So Chinese users will see the wrong font in their menu bar, namely _not_ the Chinese system font.

I can't tell how bad it is for Chinese users to see something other than the system font even though we intended to show them the system font, but in principle we should support all locales equally well.

**Comment by Letheward** [comment]
@cbjeukendrup 

> Apparently, the system font on Windows is not Segoe UI for these locales, but something else (Microsoft YaHei as mentioned?).

Yes, on Windows 10, `Microsoft YaHei` is the default UI font for Simplified Chinese. For Traditional Chinese, it's `Microsoft Jhenghei`.

> I can't tell how bad it is for Chinese users to see something other than the system font even though we intended to show them the system font, but in principle we should support all locales equally well.

See replies under this [tweet](https://twitter.com/Tantacrul/status/1597886814014279680?cxt=HHwWgMDQyezl6qwsAAAA), there are other users that are disgusted by this font as well.

**Comment by Letheward** [comment]
@cbjeukendrup It does use the wrong font for the whole app:

![bug_default](https://user-images.githubusercontent.com/59071629/207992812-02c209dd-a82a-4136-9433-f06de1745a19.png)

**Comment by cbjeukendrup** [comment]
Okay, thanks. I propose to open a new issue about MuseScore choosing the incorrect system font for Chinese (and possible other locales), so that we can leave this issue behind us.

**Comment by lorenzosu** [comment]
Hi,
I'm experiencing this issue with Musescore 4.0.0 on KDE Plasma 5.26.4 - This is the repository version installed on Manjaro.
Qt version as reported by Musescore itself is 5.15.7.

I have set the font size in the Appearance settings to 14px but this doesn't seem to be picked in many parts of the UI... Essentially it would seem only in the 'tabs' (Home, Score, Publish) at the top (?)
See screenshots below.

Note that I have set the 'menu' font in KDE Plasma font settings to Noto Sans 12 but this is not the case in Musescore.

If Musescore is using its own style for the UI and not picking up system settings it might be useful to look into how other application in a similar situation approach this; for example Ardour (which I believe uses its own styled / modified GTK), has a global 'scale' parameter and recently introduced this as the fist option when first started, which makes sense because if everything is too small it might even be difficult for the user to actually find the setting to scale up fonts and UI.

![image](https://user-images.githubusercontent.com/463937/210058855-f9605c8d-d464-4618-9003-1178cfa1443e.png)

![image](https://user-images.githubusercontent.com/463937/210058986-fe18bc21-07c5-497b-ab1f-952f4629e99e.png)
