### ISSUE TITLE
[MU4 Issue] Muse Hub does not open on Mac

### ISSUE THREAD

**Issue by rowild** [musescore/MuseScore#15196]
**Describe the bug**
After changing the default folder for sounds in Muse Hub, it does not start anymore.

**To Reproduce**
1. Change the default folder for Mus Sound installation
2. Restart Muse Hub (from "Programme" folder

**Expected behavior**
Muse Hub starts.

**Screenshots**
<img width="314" alt="Bildschirmfoto 2022-12-15 um 12 57 40" src="https://user-images.githubusercontent.com/213803/207854072-5807439d-b80f-4a68-ba3d-b262bd679919.png">

**Platform information**
 - OS: macOS 12.6, MacBook Pro M1

**Additional context**

1. the very initial default folder that is shown after downloading the Hub on a Mac does not exist at all. (It is sth with '[../]Containers/com.muse.org/[...]'. But instead they can be found in `[User]/Library/Containers/Muse Hub/Data/InstallData/[...]` Maybe this could be fixed, too? (It is a very unusual location... wouldn't sounds better be stored at `/User/Shared/...`?)
2. I first downloaded PlugIns and Muse Sounds, then did I change the default folder. Maybe that is what messes up Muse Hub?

**Comment by iamtesch** [comment]
Thanks for the report.  Can you try uninstalling and then reinstalling the hub?  This has resolved most of the helper connection issues on Mac.  If there are still issues, a system restart should help.  We are working to address the root cause here.

Also, can you let us know:
- What is the current version of the hub you have installed
- Was the custom folder on an external drive?  There are some known issues surrounding there at the moment.

Regarding the details you provided:
1. This default location is inside the Muse Hub package folder, so it doesn't affect other apps or files on the system (i.e., is "sandboxed") unless the user specifically asks for downloads in `/User/Shared` or similar.
2. The folder should be able to be changed after downloading items, so this may be related (e.g., the external drive comment above), but shouldn't be the direct cause here.

Thanks for reporting -- we'll get this addressed!

**Comment by rowild** [comment]
@iamtesch Thank you for your fast response! :-)

Yes, my custom folder is on an external drive, and changing that to e.g. "Documents" on the main drive (after re-installing) fixes problems.

Here are the infos about Hub and OS etc:
- Muse Hub 1.0.0
- MacOS 12.6, M1

I would like to mention that the default location I am talking about (the one for the the downloaded sound files) is indeed `.../Library/Containers/Muse Hub/Data/InstallData/[...]` (as mentioned above) and not inside the Muse Hub package. Could it be that we are talking about 2 different things here?

2 more observations:

- Currently, when changing the default folder, sound files AND effects will be stored there. Not sure if my observation is totally right, but in case it is, I would like to vote for an option that allows to store only the sound files on an external drive and leave programs on the main drive.

- In case a download cannot be reached, the rotating circle never stops and cannot be interrupted. Is there any chance to implement something like a "cancel download" or "Cancel all downloads" buttons?

**Comment by 1aurens** [comment]
Same error for me, MacOS 13.0, Muse Hub 1.0.0, default sounds location
