### ISSUE TITLE
[issue] cross page glissando lines

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15295]
**Describe the bug**
Glissando direction can be wrong if crossing a page turn, angle of the gliss can also be too steep.

**To Reproduce**
1. make a glissando between two different bars
2. make the first bar the end of a page so the glissando is between the two pages (easiest to do on a score with many instruments)
3. see the glissando line can be too steep and sometimes going the wrong direction for the pitch bend (an upwards gliss could point down)
4. if the error is not seen, maybe save and restart musescore to see what happens

**Expected behavior**
Glissando line should be going in the direction towards the next pitch on the next page at a reasonable angle.

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/208273026-8f06d147-0831-423c-9b86-6200549b929c.png)

**Platform information**
windows

**Additional context**
It also happened frequently in musescore 3.
The gliss line automatically collides with the crescendo at the bottom of the screenshot.

**Comment by cbjeukendrup** [comment]
Now I see what's happening here: the direction/angle of the glissandos is based on the positions of the notes relative to their systems. That's why the endpoints of the glissandos match horizontally in case of one system per page:
<img width="323" alt="Scherm­afbeelding 2022-12-18 om 02 47 18" src="https://user-images.githubusercontent.com/48658420/208275496-d4c359c6-cbd5-4c54-b4e9-9df99e08da7d.png">

I think the direction should be based on the note positions relative to the _staves_ instead.

**Comment by oktophonie** [comment]
Will be fixed by https://github.com/musescore/MuseScore/pull/14890

**Comment by Jojo-Schmitz** [comment]
@Vykoiazon do you have an example where this bug shows in Mu3?

**Comment by Vykoiazon** [comment]
> 

the files where it happened in m3 were already manually fixed so I do not have any examples
