### ISSUE TITLE
[MU4 Issue] Wrong key signature when i add a transposition instrument in this score 

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#15314]
1 - Open this file : [Test Score.zip](https://github.com/musescore/MuseScore/files/10253555/Test.Score.zip)
![image](https://user-images.githubusercontent.com/1835871/208291853-a647eec8-9fd0-4bbf-95c9-eddc2cd662e8.png)

2 - Add new Alto Saxophone 2
![image](https://user-images.githubusercontent.com/1835871/208291864-2c87d558-f6c8-4577-956b-74d14a88080a.png)

3 - Result in 3 Sharps key signature  Instead of 1
![image](https://user-images.githubusercontent.com/1835871/208291873-a3b5d422-f476-4685-85b7-ded2705c91df.png)

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223510501, revision: github-musescore-musescore-5485621

**Comment by mike-spa** [comment]
We can reproduce the issue only on the file you attached, but not on newly created scores. Now, because of the nature of the problem, if the file was created with any build preceding the fix (which happened in #14849), the issue will be still there because it was saved into the file. It would be great if you can try to grab the latest nightly build from the top of the list [here](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D) and let us know if you can reproduce it on a newly created file

**Comment by oktophonie** [comment]
Thanks for this! (I tried it myself now and can reproduce the problem)

Regarding deleting a key signature (step 4) - I think that is intentional, and it's also what 3.6 does - it basically leaves you with an 'open/atonal' key signature, rather than 'C major/A minor'. If you want a different key then you apply it from the palette in the usual way.

**Comment by Gai-Luron** [comment]
Thank's for the answer. Ok for the Atonal mode, but if I put on a key signature again, this atonal mode must disapear, isn't it?. 
The first time i remove the key signature is not intentional.

**Comment by mike-spa** [comment]
@Gai-Luron thanks for your help in figuring this out! The linked PR should fix it
