### ISSUE TITLE
[MU4 Issue] Numerical property values are not applied consistently

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15328]
**Describe the bug**

if you adjust an offset by 0.1 sp you have to press RETURN to apply it to the score. But if you adjust it by 0.05 sp. it is applied without the RETURN.

**To Reproduce**

1. Open the attached file: 
[tie_positions.zip](https://github.com/musescore/MuseScore/files/10253847/tie_positions.zip)
2. Click on a tie in tablature.
3. Open APPEARANCE and put ".1" (dot one) after the zero in the vertical offset box.
4. Press RETURN.

RESULT: The position of the tie in tablature updates.

6. Reset the position and this time enter ".05" (dot zero five) after the zero in the vertical offset box.

RESULT: The position updates in the score without pressing RETURN.

**Expected behavior**

The new value should be applied consistently.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223520506, revision: github-musescore-musescore-5485621

**Comment by Harmoniker1** [comment]
The position updates automatically whenever the two digits after the decimal point are filled in. I agree that it should be consistent, but should it be always update or always not update till pressing return? @Tantacrul

**Comment by oktophonie** [comment]
Perhaps this can be fixed by extending https://github.com/musescore/MuseScore/pull/15107? That PR implements a behaviour for the Style and Page Settings dialogs, and also for instrument names in the Instruments panel, where changes made in a numeric/text box are not applied until Tab/Return is pressed, or the box is clicked away from. Perhaps it is best to apply this same behaviour universally (and for the same reason - some modifications, even small ones of a single item, can trigger a time-consuming recalculation of the entire score layout).
@HemantAntony

**Comment by HemantAntony** [comment]
@oktophonie I have created a new PR for that: #15538. That PR fixes the offset property behaviour

That PR also includes fixes similar behaviour for Size Property for Texts (a bit difficult to reproduce that bug),  Left and Right Beam Height Properties and Time Signature Width and Height properties
