### ISSUE TITLE
[FEATURE] Trills, mordents & Turns should have additional settings in the properties panel to allow different intervals

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#15332]
- There could be a palette to pick a desired accidental,
which will then automatically be placed on top of the trill
- and a switch to toggle between diatonic playback and "custom interval".

**Comment by Tantacrul** [comment]
Design for this is ready **[here:](https://www.figma.com/file/7Hr6wLYlNxOs05vQQ69AeA/Ornament-Playback-With-Accidentals?node-id=1%3A2&t=J3AWoDarc2MRDx48-1)**

It has a few UI / engraving and playback tasks associated with it.

**Comment by oMrSmith** [comment]
I just took a first glance and say: Wow, that looks like a very good and sophisticated solution.

**Comment by hstanekovic** [comment]
The option name "Automatic (diatonic)" sounds misleading to me. The document says that this option takes into account the key as well as any prior accidentals within the same bar. 
"Diatonic" suggests to me that only the key will be taken into account. Why? Because accidentals in bars are normally used to produce altered (chromatic) tones from diatonic tones (which are determined by the key). Thus I think the better name for the option would be simply "Automatic".
