### ISSUE TITLE
[MU4 Issue] Save as Style - regressive new design

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#15333]
The beloved little buttons
to save or reset a style have been taken out
in order to declutter the inspector.

I understand this descission although I don't think it was good
since the buttons hardly take more space
than the new three little dots.

The new design comes at a cost:

1. You need to click twice as much.
2. You can no longer see **at first glance** weather a style has been altered or not. 
3. The symbol (three dots) is too unspecific to be associated with the function.

Problem number **2** is caused by the fact,
that the three dots will always show up, even if they don't contain any vailid option to select.

Remember: The old buttons would be greyed out in this case.

![Unbenannt 2](https://user-images.githubusercontent.com/78870770/208302760-b4d97bd3-151f-4e4d-bf18-09b8303433a8.JPG)

This leads me to the following idea:

**Why not bring back the good old buttons, 
but only show them when they can actually be clicked?**

Advantages:
- specific symbol for specific task
- no need to click more often
- changes to the style-default are visable at first glance
- the inspector still gets decluttered

Thought: If you don't want to go back, you could still at least hide the three dots,
if they don't contain options to select and the UI would declutter even more.

**Comment by Tantacrul** [comment]
We are definitely not bringing back the old buttons:

- Absolutely incomprehensible to the overwhelming majority of users. In testing no one could even begin to fathom what they were.
- Add incredible visual clutter unnecessarily. Every item has an additional two buttons assigned to it, which makes the overall interface feel stressful to look at. This is a legitimate problem because it makes the other options harder to find.

I do think there are avenues to explore in order to indicate whether something is using a general style or not. However, turning it a weird colour is (again) incomprehensible.

I do not agree with the point about number of clicks. Setting general styles is an operation you only do a few times in a score (if at all). It is therefore not really hampered by the requirement to click twice. This would not be true for something you need to use a lot like, say, the accidentals in the note input bar.

I'm closing this issue because we're not returning to the old system. Am happy to accept suggestions about how we can improve the existing one.

**Comment by MarcSabatella** [comment]
FWIW, I agree the buttons were cluttery, and that save as style is relatively infrequent for most users.  Plus in the cases where you *are* making lots of style adjustments (eg, creating a template), usually you're better off using the Format / Style dialog.

However, I also agree that a clear visual indication that a value is not at the default would be useful.  Simply hiding - or graying out - the "..." menu seems like kind of a no-brainer.

I would also claim that *resetting* a value to the default is reasonably common.  In other places in the UI, we use double-click as a way of quickly resetting a control.  Not sure it makes sense to enable that directly for spin boxes or other controls in Properties, but double-clicking the "..." itself could work.

So, those are my suggestions:

1) hide or gray out the "..." when the value is at the default
2) enable double-click on the "..." to invoke reset

I'm happy to make open a separate issue or task if there is agreement.

**Comment by oMrSmith** [comment]
> However, I also agree that a clear visual indication that a value is not at the default would be useful. Simply hiding - or graying out - the "..." menu seems like kind of a no-brainer.

Yeah, so my original idea would look like this:

![image](https://user-images.githubusercontent.com/78870770/223711447-a3cf4854-d6d9-4cc3-9fb8-6415f4e79de0.png)

The symbol to save or reset the style-change
is visable at first glance and can be clicked right away.
However, there is only one pair of symbols shown,
since only the font-size had been altered.
Everything looks orderly and decluttered in my eyes.

**Comment by Tantacrul** [comment]
I don't think anyone should be expected to understand what those symbols are. It fixes one problem while returning to the previous problem of them not making any sense.

The advantage of the V4 design is that the functions are explained in text so the user can get some idea of what they are for. This advantage needs to be maintained.

**Comment by oMrSmith** [comment]
Te me those buttons make a lot of sense, more than three little dots, which could literally mean everything, 
but even if not I find: Once you have understood  it, it is rather frustrating to get reminded over and over again.
Do you know what I mean? (I know I must be a strange user, but at least for text, I use these buttons constantly,
since I don't get out the workflow by opening the style page.)

**Comment by oMrSmith** [comment]
> 1. hide or gray out the "..." when the value is at the default

Anyway, actually my main point was to agree with this.
I think this could be a good compromise...

**Comment by Tantacrul** [comment]
It's not three little dots though. You click on it and you see an explanation. You know this full well.

The only reason you understand the MS3 version is because you learned it - and I bet it wasn't through trial and error. You're in the 0.02% of people who did. In testing, absolutely no one understood this.

I'm going to lock this now because the suggestions aren't helpful.
