### ISSUE TITLE
[MU4 Issue] Dotting a whole note in a 4/4 bar.

### ISSUE THREAD

**Issue by GoodMannSamm** [musescore/MuseScore#15360]
**Describe the bug**
This file is odd in that you are unable to create a whole note and then dot it, but only in this specific file.

**To Reproduce**
1. Open the attached file. [MS4 Crash Rep 1.zip](https://github.com/musescore/MuseScore/files/10256179/MS4.Crash.Rep.1.zip)
2. Go to bar 77 where there is a large chord with lots of instruments (note: the file has been cleared of unneeded music for clarity.)
3. Select any of the quarter notes for any staff.
4. Go to the top of the screen and click the whole note button.
5. Click the augmentation dot button.
6. See error: MuseScore will promptly crash.

**Expected behavior**
I anticipated the normal behavior where musescore would tie a half note to the whole note.

**Platform information**
 - OS: Windows 11

**Additional context**
I have no clue what causes this issue, but it's likely related to the corrupted file. I also am not sure if this issue is at all helpful to the development of MS4, but I thought I would contribute per the advice of @MarcSabatella.

**Comment by cbjeukendrup** [comment]
It's indeed related to the corrupted file; I had to disable some sanity checks in the code before I could even open the file. 

The corruption is in the parts; basically all of them. It looks very much like de corruption described in #15185, which has a fix pending in #15257; after that fix, it won't happen again, that's the good news. The bad news is that it is currently not possible to recover this score; in order to do that, you would need to delete the parts containing the corruption, but that can't be done in your case, see #15546. As an alternative way to get composing again, you can copy the contents of the full score to a newly created score. That should leave the problems behind, since those are only in the parts.

**Comment by Tantacrul** [comment]
My understanding is this corruption issue has been solved. Is that right @vpereverzev ?
