### ISSUE TITLE
[MU4 Issue] Instruments are louder when editing than during playback

### ISSUE THREAD

**Issue by 5ucur** [musescore/MuseScore#15375]
I just upgraded to 4 and tried out a score, just to see how it all works now, and if the bugs I encountered before are fixed (they are).

Then I noticed that during editing, instruments are louder (placing notes, moving notes, etc) than during playback. I don't know which is the 'normal' volume and which is the quieter/louder. All I know is I can't go changing my volume every time I want to hear the composition.

This wasn't happening in 3. Is there a way to fix this on my end, or is this a bug?

Edit: Marc has determined that this only occurs with MS Basic and has asked me to include that info here too.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new score, add Piano (or any other instrument).
2. Add some notes, note the volume of their sounds.
3. Play the score, note the volume of playback - it's quieter than in step 2.

**Expected behaviour**
The expected behaviour is that both have the same volume.

**Platform information**
 - Arch Linux 6.0.12-arch1-1 (just been fully upgraded)

**Comment by MarcSabatella** [comment]
It's normal that while editing, all notes play the same volume, but during playback, they respect the dynamic markings.  MuseScore 3 was the same way.  So it's certainly normal that playback might sound different from note input.

But it does seem the volume of note input is a bit more than mf, whereas in MuseScore 3 I think it was exactly mf.

**Comment by ableunable** [comment]
There aren't any dynamic markings in my example (see 'To Reproduce' section). Which volume is the default one for when there are no markings used? mf?

**Comment by MarcSabatella** [comment]
Generally yes, although it's certainly possible Muse Sounds might choose something else if you don't specify anything.  Always best to be explicit if you want consistent results, both from MuseScore and from human musicians.

**Comment by ableunable** [comment]
I see. That still doesn't address the fact that the editing volume is at ff levels, though. Is there any way to change that?
I don't mind that the editing volume is at a set level while the playback volume follows the markings. But I don't like the editing volume being quite as loud as it is.

**Comment by MarcSabatella** [comment]
There isn't a setting for that.  For me it's nowhere near ff, more like somewhere between mf and f but closer to mf.  Maybe it depends on the specific instrument. or other details of your particular score.  If you attach your score and say if you are using any non-default sounds, that might help others understand why you are hearing something different.

**Comment by ableunable** [comment]
If there isn't a setting, I feel like it's a bug on my end then. On what OS are you trying it? The fact that you're not getting the same results makes me think it's got something to do with my particular installation.

Please, take the time to check the 'To Reproduce' section in the issue:
- there are no non-default sounds used,
- no specific instruments (it happens with a piano as well as with other default instruments)
- no details of the particular score,
- no dynamic markings used.

I only created a completely regular score, first thing after opening the program, without any extra settings or markings; just a few notes as described in the 'To Reproduce' section. I am also not using the new feature (Muse Sounds, was it?) but the regular old sounds.

I will attach the same minimal example score as which can be created by following the steps in the 'To Reproduce' section when I am at my computer, if you need me to. If need be, I can also make a screen recording.

**Comment by MarcSabatella** [comment]
I can confirm it is slightly louder still with MS Basic specifically (you might want to edit the original report to clarify, it's only MS Basic).  It's still quieter of course than a full score playing (because it's only one note), so you shouldn't need to change volume.  just set something comfortable for the full range of volume that music can have.

**Comment by FloraCanou** [comment]
I have exactly the same issue on Windows 11.

**Comment by MarcSabatella** [comment]
MS Basic is indeed the old MU3 soundfont, tweaked slightly and renamed.

By "one note", I mean, during note inut, you are hearing only a single note.  But when playhing your score, you are usually hearing many notes at once.  So the loudest parts of a score are almost louder than any one note being entered during note input.  So it's best to set your system volume appropriately, so the loduest passage of actual music are not too loud for you.  And then the single notes you enter during note input will also be fine.

**Comment by ableunable** [comment]
Please, do take a look at the recording I attached. Only one note is played at a time in it, as I've only inputted a sequence of twelve notes in the upper staff. Nothing else, as it's a *minimal example*.

Also, you're saying that the loudest parts of a score are almost always louder than any one note being entered. But my issue is the exact opposite of that; notes are louder *during input/editing* than at playback.

If I were to set the system volume so that the loudest passages of music and inputting volume are not too loud, regular volume passages (mf for example) would be very quiet.

I have hearing problems and having to turn my volume up to hear what I expect to be at a normal volume, then having to turn it down so that I can input notes without bothering other people, and so on every time, is annoying. Please have someone check this out.

**Comment by MarcSabatella** [comment]
I'm saying that playback is a score will usually be louder *in practice* because you're hearing the entire score.  For instance, even if you enter a bassoon note and it plays "f", when you play the entire score with flute and clarinets and trumpets and timpani and violins etc, it's going to be louder than your single bassoon note played "f".

Anyhow, I do agree it's not good that the playback during note input using MS Basic is playing louder than mf, so hopefully one of the developers will indeed look into fixing that.  I was simply trying to get clarification since the original problem description didn't specify it only happens with MS Basic, and also I am trying to help you meanwhile.

Meanwhile, indeed, if you have hearing issues such that you need to turn up volume to be able to hear quiet passages and the loudest passages (include note input) are too loud as a result, you will indeed need to adjust volume manually for now, I'm afraid.  Or, you could use install Muse Sounds, where this note input problem at least does not occur.  You can probably also find a compressor effect to use on the master channel to equalize volume more - that might be effective also for the more general issue of not being able to hear quiet passages.

**Comment by ableunable** [comment]
Thanks for your input and assistance in trying to solve this issue. The other person's comment shows it's not just about my installation, so I hope a developer will take a look! I looked at the source code for a bit, but I'm not at all good at C++ so I would probably not be able to contribute in any way.

I don't have an issue with the quiet parts being quiet; it's the normal parts being quiet when compared to input volume that is problematic. (I expect input/editing volume to be at normal volume too - 'normal' being as when no dynamics marking is used, which is usually mf; and as it is now, it's at ff levels).

I will look into Muse Sounds, as well as putting a compressor on the master channel, in the meantime.

**Comment by MarcSabatella** [comment]
Yes, to be clear: I said I can reproduce this as well now, so there is no one thinking this is just about your installation.  It was only before I knew you were using MS Basic that I was wondering what was different about your system.  And now we know: it's that you were using MS Basic and I wasn't.

**Comment by ableunable** [comment]
No, of course - I may not have been clear as I'm not a native speaker; I didn't mean to imply anyone else thought it was just about my installation. I only knew I did.

**Comment by ableunable** [comment]
I tried bumping up the Playback volume, under Properties>General, from 64 to 100. Playback seems to be equally as loud as input/editing volume now, using MS Basic. Could be used as a workaround in the meantime.

**Comment by rgreen5** [comment]
I'm astonished that this issue hasn't even been prioritised yet. IME, it's really annoying for the user.

The input volume should be set to **_mf_** as it was in MuseScore 3.

**Comment by bkunda** [comment]
@vpereverzev Are there any implications we should be aware of if we were to bump down the general volume for note input slightly? 
@Tantacrul FYI

**Comment by AlteriusOmega** [comment]
Just tested this and yes mine also needs to be at _ff_ to be as loud as editing which is pretty annoying. It would be great to have a setting for editing volume. It could be on the mixer like chord symbol playback volume is
