### ISSUE TITLE
[MU4 Issue] Lyrics layout breaks on incomplete input

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#15407]
**Describe the bug**
Lyrics self-intersect when ending with a minus (`-`).

**To Reproduce**
1. Enter more than one note.
2. Click on the first note
3. Type Ctrl-L to enter lyrics mode
4. Type "Froh-" without quotes
5. Press the `Esc` key, or click some empty part of the score, to abort entering lyrics

**Expected behavior**
I wouldn't be surprised by any of the following behaviors:
1. Because the minus key is supposed to indicate a single connected word and the user refused to write the rest of the word, the minus is removed, and only "Froh" remains.
2. Because the user refused to enter anything further, the lyrics "Froh - " appear.
3. A dialog appears asking the user what they want.
4. Because the input doesn't make sense, MuseScore reinterprets the input as "Froh_".

**Actual behavior**
The layout algorithm seems to think that "Froh" is the only remaining text node, and does the layout accordingly. However, the "-" (minus symbol) also appears, in a place that would be reasonable if "Froh" hadn't moved in the meantime. The result is that "Froh" and "-" overlap awkwardly.

**Screenshots**
I wrote "Fröh-", but that doesn't really make a difference:
![Bildschirmfoto_2022-12-20_01-02-35](https://user-images.githubusercontent.com/2690845/208552270-da3432bb-a713-4500-8517-2f357287458f.png)
I didn't edit that screenshot, the weird line in the text is the minus sign.

**Platform information**
 - OS: Linux, German locale, but that probably doesn't matter.

**Additional context**
Am I spamming too much or should I keep going? Writing 8 bug reports in a row starts feeling like I should stop doing that.

**Comment by oktophonie** [comment]
Not spamming at all - if they are all valid bugs, we need to know about them :)
(though do check whether they have been reported already)

I feel like 1. is the best solution here; we can't assume what the user wants. If they are just interrupting the input process and will return to it, then can then easily do so.

The syllable should also return to being centered (rather than left-justified) when this happens.

The same should happen if the user exits after pressing _ only once. Currently MuseScore 3 left us with this in that situation:
![image](https://user-images.githubusercontent.com/20604032/208699462-d1747052-6460-431c-b228-b70700d0faa8.png)
which is also no good. MU4 doesn't show the _ (probably because very short melisma lines are now now shown by default), but there shouldn't even be an implied one.

**Comment by BenWiederhake** [comment]
Thank you! That sounds reasonable. And yes, I always check first, and in one case even found out that a translation bug is already fixed in Transifex (and is apparently just in the pipeline for the next website update or something.)
