### ISSUE TITLE
[MU4 Task] Add 'Beam type' to Properties panel for rests

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#15446]
**Task description**
The properties panel has a 'Beam type' section for Notes:
![image](https://user-images.githubusercontent.com/20604032/208718559-78e9c395-7bba-483e-b49b-636e0e2b9d0e.png)

This should be added for Rests too. At the moment, only the 'Beam properties' palette can be used to apply these to rests.
For notes, one can consult the properties panel to see which 'beam type' has been applied to a note, but one cannot do this for rests.

(I can't shake the feeling that there's already an issue/task for this but I can't seem to find it. If anyone does, close this one and shout at me.)

**Comment by Harmoniker1** [comment]
In MU4 the rests don't have any specific section for them in Properties, where as in MU3 they have a section that only contains the "Small" option, but I guess that's covered more consistently in MU4. So this here seems to need the design for a new "Rest" section for Properties? Can't think of anything else though that might need to go in that section besides reusing the "Beam type" panel there.

**Comment by Harmoniker1** [comment]
![image](https://user-images.githubusercontent.com/46259489/208731079-739a6793-682f-4e25-b2fe-5a43f6774ede.png)

I played with this for a while and saw that if I select both the first note and the first rest here, setting the beam mode in Properties would make the note's beam mode change, but not the rest's, so I went into the code and added one line that made the rest's beam mode able to change, but still if I only select the rest, there isn't any setting in Properties.

It can definitely be fixed by adding a "Rest" section, in which the "Beam type" panel is reused, but then there's the question of whether or not the "Rest" section is shown when there're both note(s) and rest(s) selected, since the one single setting available in "Rest" is already covered in the "Note" section. In this case maybe it's better to just show the "Note" section, and only show "Rest" if no notes are selected. But of course, if there's other settings that need to be in "Rest" and are not covered in "Note", then both need to appear.

Anyway, I may seem overzealous about this, if so, I apologise.

**Comment by bkunda** [comment]
> there's the question of whether or not the "Rest" section is shown when there're both note(s) and rest(s) selected

We already have a design solution for this, which is to show buttons for each property type when more than one different element is selected.

<img width="695" alt="Screenshot 2023-01-06 at 2 43 22 pm" src="https://user-images.githubusercontent.com/86290556/211024145-68ad5fb8-ce1c-406d-bb54-7d06e6b10363.png">

So I think we fall back on this in adding a new properties section for "rests". 

The fact that you can only open one of these popups at a time should hopefully allay any confusion concerning the adjustment of beaming for either notes or rests (because you can only do either one of these at a time). 

Personally, I think a dedicated "rests" section makes sense here, because it seems intuitive to want to modify a beam over a rest by first selecting the rest. 

@oktophonie can you think of any other properties we might need for rests? I might give this one a go now.

**Comment by bkunda** [comment]
> (I can't shake the feeling that there's already an issue/task for this but I can't seem to find it. If anyone does, close this one and shout at me.)

@oktophonie was this the task you were thinking of? https://github.com/musescore/MuseScore/issues/9892
I was certainly reminded of it. This was to add an option for "beam end".

**Comment by oktophonie** [comment]
@bkunda For now, not that immediately springs to mind; but when we get to implementing stemlets it would make sense for control(s) for those to live under Rest -> Beam too.

**Comment by oktophonie** [comment]
Closing as subsumed by https://github.com/musescore/MuseScore/issues/15779
