### ISSUE TITLE
[MU4 Issue] Open cloud score on another computer

### ISSUE THREAD

**Issue by LuFlo** [musescore/MuseScore#15453]
**Describe the bug**
Saved scores to the cloud do not appear in Home-Tab.

**To Reproduce**
1. Create a new score
2. Add some notes
3. Save score to the cloud (privately)
4. Go to another computer
5. Sign in to account
6. Express great sadness, as the score does not appear in the Home-Tab (or somewhere else?) :(

**Expected behavior**
Score should appear, it should be possible to open and edit the score.

**Platform information**
 - OS: Tried on Windows and Linux, no luck on both :(

**Comment by Tantacrul** [comment]
> Express great sadness, as the score does not appear in the Home-Tab

Haha. 

Yes, account management is on our radar.

**Comment by cbjeukendrup** [comment]
There's one big problem that needs to be resolved before we can tackle this one: when a score has been modified on MuseScore.com, this will not be detected by MuseScore Desktop. So MuseScore Desktop just opens the old version that's still on your local harddisk, and when saving, it overrides any changes on MuseScore.com.

The first step to solve that is a mechanism to detect which version of the score is the newest (the local one or the MuseScore.com one). When opening the score, simply use the newest version. But when both are modified\*, we're in a difficult situation, since we don't have any mechanism to merge changes to scores\**. This is far from trivial. For the time being, we'll have to ask the user to make a blind guess which version they want to open, with the risk of loosing changes. We used to have a tool to compare scores, but that's not implemented anymore either currently.

\* This will happen if you edit the score on computer A, which is temporarily not connected to the internet so the changes will not be uploaded on save; then edit the score on computer B, and save the changes to MuseScore.com; then try to open the score on computer A again. The version on computer A has "diverged" (as Git calls it) from the version on MuseScore.com (and computer B).

\** We don't really need to reinvent the wheel here since general diff algorithms may well be applicable to scores too; but the big problem is, _how_ to apply them, since the data structure of a score is way more complicated than a simple text file. (And looking at the diff of the underlying XML file is probably meaningless.)

**Comment by shoogle** [comment]
There are certainly some challenges here, but nothing we can't solve. Diffing and merging would be great, but in the short term I think we can get 90% of the way there simply by warning users when they are trying to edit a cloud score offline. If they dismiss the warning and continue to edit offline, we'll check for conflicts the next time they are back online. If conflicts are detected then we can open the online score in separate window and ask the user to choose which one they want to keep, or save them both with different names.

**Comment by LuFlo** [comment]
I don't think we need a "diffing and merging" feature in the short term. Technically it would be possible to implement something like this, but I see more issues on the user interface side. I assume most musicians do not have experience with versioning tools like software developers do. So I agree with @shoogle that it might be easier to just ask the user what should happen when a conflict arises. For example Steam Cloud works very similarly.

**Comment by cbjeukendrup** [comment]
It looks like this feature is currently being implemented as part of task #16808, which is planned for 4.1. So I'll close this issue, since one open task is enough!
