### ISSUE TITLE
Musescore 4 missing font rendering on startup? MacOS Mojave

### ISSUE THREAD

**Issue by ianchia** [musescore/MuseScore#15500]
I just started up Musescore 4 for the first time (MacOS Mojave 10.14.6, MBP 2012 i7) and it is missing almost all, but not quite all of the font rendering onscreen? I see "Musescore 4" at the top, "Getting Started" but all the buttons and dialogs are missing text labels.
![Musescore 4 missing font display](https://user-images.githubusercontent.com/76875/209109409-fcc7af6d-fd6e-4be3-826a-2f35ec4a3b4e.jpg)

**Comment by cbjeukendrup** [comment]
Strange... all text that's missing should use the system font. It's apparently not a general font rendering issue, because icons in the toolbars appear correctly (and those are also characters of a font). The few other texts that do appear are rendered by the system rather than by MuseScore.

Do you have the "SF Pro" font installed on your Mac? Did you ever have it installed but uninstalled it? Is there anything special about fonts on your system that you can think of?

**Comment by ianchia** [comment]
I have SF Pro installed, but to test further, I downloaded fresh copies of all SF Pro and SF variants from apple.com and reinstalled. Launched MuseScore 4 with the same result. Rebooted, and relaunched again - still with same rendering issues on MuseScore 4.

See attachment with Font Book showing SF Pro installed and buggy MuseScore 4 rendering.

There's nothing unusual about fonts on my system. I use a range of apps in Adobe Creative Cloud as well as the Affinity Designer and Photo apps and they work fine with my fonts.

Any other ideas I can try to debug this? Thanks!

![Missing Muse Score font rendering - SF Pro installed](https://user-images.githubusercontent.com/76875/209419120-ca6b6116-1c29-48c0-b614-8de1592025d1.jpg)

**Comment by cbjeukendrup** [comment]
@ianchia I have created a test version, which might resolve the issue. You can download it in ca. 40 minutes from now from https://github.com/cbjeukendrup/MuseScore/actions/runs/3775802804 (scroll down to "Artifacts").

**Comment by ianchia** [comment]
@cbjeukendrup Thank you Casper. This one renders fine! However, under the Learn tab under Get Started, it says "Sorry we are unable to load these videos right now. Please check your internet connection or try again later." Not sure if this is because this is a a development build? Musescore does correctly pull my profile image down after launch so it is connected to the internet.

**Comment by cbjeukendrup** [comment]
Glad to hear that this solves it! Then I'll go ahead and nominate this change for the next patch release. 

You could keep using the build I gave you for the time being, but be aware that because this is a development build, your settings etc. will not be synced with officially released builds. The file format _is_ compatible with release builds though.

> Please check your internet connection or try again later." Not sure if this is because this is a a development build?

Exactly: development builds don't have access to the API key that's necessary to load the videos.
