### ISSUE TITLE
[MU4 Issue] Measure Number Range

### ISSUE THREAD

**Issue by Ahh6483** [musescore/MuseScore#15635]
**Describe the bug**
When "Show Measure Number range at multimeasure rests" is on on there is a % at the start of every range or some just are not correct. 

**To Reproduce**
1. Open Any Part
2. Go to 'Format --> Style'
3. Click on 'Measure Numbers'
4. Click on 'Show Measure Number range at multimeasure rests'
5. Click on 'Ok'
6. See error on score

**Expected behavior**
Expected to show a correct range of measures.

**Screenshots**
<img width="606" alt="Screenshot 2022-12-28 at 9 59 26 PM" src="https://user-images.githubusercontent.com/79336035/209897739-1e006a0d-12ea-49c9-8637-cb7f4684d3b9.png">
<img width="939" alt="Screenshot 2022-12-28 at 9 59 40 PM" src="https://user-images.githubusercontent.com/79336035/209897755-8a765e04-0c41-4736-b70f-42f315712a31.png">
<img width="533" alt="Screenshot 2022-12-28 at 9 59 51 PM" src="https://user-images.githubusercontent.com/79336035/209897767-443ce468-513f-4059-99e7-a7a2541e8e20.png">
<img width="374" alt="Screenshot 2022-12-28 at 10 00 12 PM" src="https://user-images.githubusercontent.com/79336035/209897794-267493f5-5470-45ac-87e6-175f24c6f450.png">
<img width="459" alt="Screenshot 2022-12-28 at 10 01 30 PM" src="https://user-images.githubusercontent.com/79336035/209897900-38e3647e-d991-4fff-acfe-6cadcec6f875.png">

**Platform information**
 - OS: MacOS

**Additional context**
This score was imported from MS3, issue appears to be on all parts.

**Comment by cbjeukendrup** [comment]
@Tantacrul Is this a candidate for the patch release? This specific issue is maybe a bit niche, but it was caused by a bug in a pretty general function that may cause similar problems in other places. @igorkorsukov What do you think about how risky this is? (The fix was https://github.com/musescore/MuseScore/pull/15644/files)

**Comment by igorkorsukov** [comment]
I think it's very good that this bug is fixed. But despite the fact that it is in a general function, I don't think that in reality it is having a big impact. At a minimum, we can monitor if we encounter at least one more situation in which this error is guilty, then we can draw the appropriate conclusions.

**Comment by Tantacrul** [comment]
I can see @oktophonie has added it to 4.0.2, so we're all good.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/342659

**Comment by oktophonie** [comment]
This fix wasn't included in 4.0.2, but was bumped to 4.1.
