### ISSUE TITLE
[MU4 Issue] It doesn't work with MuseScore4 installer from MuseHub in Windows 10.

### ISSUE THREAD

**Issue by anjwl** [musescore/MuseScore#15637]
**Describe the bug**
MuseScore4 closes or crashes at start.

**To Reproduce**
1. Download MuseScore4 from MuseHub
2. Open MuseScore4
3. Wait until Loading window appears

**Expected behavior**
It should work with MuseScore4 installer from MuseHub.

**Screenshots**

**Platform information**
 - OS: 64-bit Window 10

**Additional context**
It's same as https://github.com/musescore/MuseScore/issues/13899.
But it doesn't work with MuseScore4 installer from MuseHub in Windows 10.

**Comment by L0uisc** [comment]
Can you try to attach the logs as you did with #13899? I'm also on Windows 10 64 bit and I have no issues with MuseHub, so there must be something unique to your system that triggers the crash.

**Comment by cbjeukendrup** [comment]
Could you do the following: 

1. Go to https://www.dropbox.com/s/cv4vvn3lutdezna/MuseScore-4.0.0.223622217-x86_64.zip?dl=0 and click "Download" in the top left corner (you don't need to log in).
3. The downloaded file is a zip file; unpack it.
4. Inside the resulting unpacked folder, you should find a subfolder called `bin`, and inside that folder you should find `MuseScore4.exe`. This is the file you need; double-click it to launch MuseScore.
5. It should crash again, just like the official version 4.0.0; or maybe it does load but playback doesn't work.
6. Now, in Windows Explorer, please go to `%localappdata%\MuseScore\MuseScore4Development\logs` to find the logs. (Note that this is a different location than for the logs of the official version: this test version puts the logs in `MuseScore4Development`, while the official version puts them in `MuseScore4`.)
7. Here you should find the logs from the last attempt to run the test version. Please upload them here; you may need to rename them to have .txt at the end, so that the forum lets you upload them. 
8. When you are ready, you can simply remove the downloaded folder; with this procedure, nothing is installed on your computer, so you don't need to uninstall anything either.

For many people, this crash appeared to be related to audio devices. As a workaround, you could try changing some settings or switching to a different device for the time being. It would be great if you could give some details about the audio device that causes the crash: which sample rate and bit depth does it use? And has it more than two audio channels or some kind of "spatial audio" mode enabled?

**Comment by anjwl** [comment]
@cbjeukendrup It does load but playback doesn't work. This is my logs folder. (I can't find the logs.)
[logs.zip](https://github.com/musescore/MuseScore/files/10324957/logs.zip)

It uses 24bit, 48000Hz. It has two audio channels and spatial audio mode is not enabled.

**Comment by cbjeukendrup** [comment]
Hi! Could you please try if the build from https://github.com/musescore/MuseScore/suites/11044663711/artifacts/561149134 works correctly?
