### ISSUE TITLE
[MU4 Issue] inactive Muse Sounds Big Sur - MuseSampler not found

### ISSUE THREAD

**Issue by brousseau6933** [musescore/MuseScore#15670]
Sorry to use this dev channel but ZenDesk help didn't received anything yet: https://musehub.zendesk.com/hc/en-gb/community/posts/8525041768221-Big-Sur-MuseScore-4-and-Muse-Hub-Muse-sounds-unavailable-inactive-

I've reinstalled, uninstalled, cleared, etc... all related files and software in any order and always face the dreaded "Muse Sounds Inactive".

iMacPro, Big Sur 11.7.2. Muse Hub installed and MuseScore 4 also. Libraries under ~/Library/Containers/com.muse.hub/Data/InstallData/Instruments/

I looked at different places awaiting for support and found that MuseSampler should be working for Muse Sounds to be working, right?

A search with EasyFind found nothing for MuseSampler and obviously, MuseScore diagnostics reports: "Muse Sampler Library not found". Confused???

Thanks,

Patrice

![Capture d’écran, le 2022-12-31 à 17 03 32](https://user-images.githubusercontent.com/12112968/210156429-dab08bb5-4656-4731-b171-e18818bb28c6.png)

**Comment by brousseau6933** [comment]
Reinstalled again, still no MuseSamplerCoreLib in MacOS, what's up?

**Comment by cbjeukendrup** [comment]
`libMuseSamplerCoreLib.dylib` should be in `/usr/local/lib`.

If it's not there, you could try going to `~/Library/Containers/com.muse.hub/Data/InstallData/Installers`. There, you should find several subfolders; one of them contains the MuseSampler installer (for me it's the one called `acb2c6fc-5136-4c18-95c9-70c656e3c6e5`). There's a zip file inside it, and if you unzip it, you should get `libMuseSamplerCoreLib.dylib`. Copy that to `/usr/local/lib`.

(Note that this is not really an official comment since I work for MuseScore, not for Muse Hub / Sounds, but I wanted to give you at least some reply.)

**Comment by brousseau6933** [comment]
> `libMuseSamplerCoreLib.dylib` should be in `/usr/local/lib`.
> 
> If it's not there, you could try going to `~/Library/Containers/com.muse.hub/Data/InstallData/Installers`. There, you should find several subfolders; one of them contains the MuseSampler installer (for me it's the one called `acb2c6fc-5136-4c18-95c9-70c656e3c6e5`). There's a zip file inside it, and if you unzip it, you should get `libMuseSamplerCoreLib.dylib`. Copy that to `/usr/local/lib`.
> 
> (Note that this is not really an official comment since I work for MuseScore, not for Muse Hub / Sounds, but I wanted to give you at least some reply.)

I'll take a look ASAP and report back. Thanks!

**Comment by brousseau6933** [comment]
Unfortunately, the only MuseHub folder I have in ~/Library/Containers is called "Muse Hub".

The only installer in there ( ~/Library/Containers/com.muse.hub/Data/InstallData/Installers ) is MuseScore4.zip. Unzipping it, no MuseSampler lib...:(

Why this MuseSampler lib is not present on my system?

**Comment by brousseau6933** [comment]
You don't have a copy you could share?

**Comment by cbjeukendrup** [comment]
> why MuseHub doesn't install it when I download Muse Sounds???

Yeah, that's exactly the question... because that's indeed what should happen. And I don't know the answer to that.

I'm not sure what those things in .musedl are, but I don't think they are real data, rather auxiliary files for the download process.

If you haven't tried it yet, you could uninstall one of the sounds (tip: choose Harp, the smallest one) using Muse Hub by holding the Alt key and pressing the trashcan button that appears, and then re-installing it, hoping that Muse Sampler will be installed this time.

Anyway, here's my copy: [musesampler-mac-0.3.2.18.zip](https://github.com/musescore/MuseScore/files/10419965/musesampler-mac-0.3.2.18.zip)
Hope this helps.

**Comment by brousseau6933** [comment]
> > why MuseHub doesn't install it when I download Muse Sounds???
> 
> Yeah, that's exactly the question... because that's indeed what should happen. And I don't know the answer to that.
> 
> I'm not sure what those things in .musedl are, but I don't think they are real data, rather auxiliary files for the download process.
> 
> If you haven't tried it yet, you could uninstall one of the sounds (tip: choose Harp, the smallest one) using Muse Hub by holding the Alt key and pressing the trashcan button that appears, and then re-installing it, hoping that Muse Sampler will be installed this time.
> 
> Anyway, here's my copy: [musesampler-mac-0.3.2.18.zip](https://github.com/musescore/MuseScore/files/10419965/musesampler-mac-0.3.2.18.zip) Hope this helps.

Ok, I should had checked first in /usr/local/lib... It's already there??? Should this folder be root:wheel? It's the case now so I had to use my admin account to check inside...

Thanks for your help BTW...

**Comment by brousseau6933** [comment]
Ah, just giving "read" permission to /usr/local/lib dit it. A big thank you!!!

**Comment by brousseau6933** [comment]
Solved with the help ofcbjeukendrup...

**Comment by cbjeukendrup** [comment]
@brousseau6933 Glad to hear that!

@iamtesch This might be good to keep in mind: apparently users don't always have read access to `/usr/local/lib`, which prevents MuseScore from finding the MuseSampler lib. Either Muse Hub should modify these permissions automatically when installing, or we should think about putting the lib in a different location.

**Comment by brousseau6933** [comment]
In fact, there was also a Lame library from an old install of Audacity in there. Maybe it was Audacity back then (2016) that flagged this folder as unreadable? This computer was migrated from an old one with Sierra (updated from Snow Leopard, Lion, Mavericks, Yosemite, El Capitan). Then, this iMacPro got Mojave and lately, Big Sur... A lot of things could had gone wrong since.
