### ISSUE TITLE
[MU4 Issue] Change "Hide/delete palette" to "Hide/Delete palette"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15672]
**Describe the issue**

In the palettes area, "Hide/delete palette" needs to be changed to "Hide/Delete palette".

**Comment by Rishav1707** [comment]
In which file? @rgreen5

**Comment by Harmoniker1** [comment]
>  "Hide/delete palette" needs to be changed to "Hide/Delete palette"

Why exactly is that?

**Comment by cbjeukendrup** [comment]
> In which file?

Open the MuseScore repo in Qt Creator, hit Ctrl+Shift+F (Cmd+Shift+F on macOS) and search for "Hide/delete palette"; then you'll find it automatically :)

---

> Why exactly is that?

Because "Hide" and "Delete" are alternative beginnings of the sentence, and therefore both need to be capitalised, like we already do with "Staff/Part properties".

**Comment by Rishav1707** [comment]
> > In which file?
> 
> Open the MuseScore repo in Qt Creator, hit Ctrl+Shift+F (Cmd+Shift+F on macOS) and search for "Hide/delete palette"; then you'll find it automatically :)
> 
> > Why exactly is that?
> 
> Because "Hide" and "Delete" are alternative beginnings of the sentence, and therefore both need to be capitalised, like we already do with "Staff/Part properties".

Why in Qt creator?
Is it not running in VS code?

**Comment by cbjeukendrup** [comment]
VS Code is probably also fine. But the "big" Visual Studio not, because it won't see the QML files.

**Comment by DmitryArefiev** [comment]
Retested on Win10
