### ISSUE TITLE
[MU4 Issue] app crashes when transposing

### ISSUE THREAD

**Issue by jennifer-hiller** [musescore/MuseScore#15727]
**Describe the bug**
App crashes when using transpose

**To Reproduce**
1. Open attached file
2. Click Tools > Transpose
3. Select To Key > Closest > F Major / D Minor

**Expected behavior**
Score transposes

**Platform information**
 - OS: MacOS 13.1

Crash log file attached

[score.mscz.zip](https://github.com/musescore/MuseScore/files/10355127/score.mscz.zip)
[musescore.log_.txt](https://github.com/musescore/MuseScore/files/10355152/musescore.log_.txt)

**Comment by Eism** [comment]
The problem is also in MU3.
A simple solution: open B Clarinet 1, go to measure 53 and delete the key signature. Works only in MU3, in MU4 you can't delete the key signature, maybe it's another bug.

------------
If in more detail:
The problem is that mscx has a key signature for instrument change, but there is no instrument change. See 'score.mscx', 399864 line. The crash occurs when trying to find instrument change and transposing.
It looks like this is the result of another bug.
@oktophonie @mike-spa what do you think?
