### ISSUE TITLE
[MU4 Issue] Display key, brackets and braces doesn't work on horizontal frame at the start

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#15732]
**Describe the bug**
I'm creating vocal music with a prefatory bar to show range information, and I can insert a horizontal frame after the first bar to make sure that the start of the music is clearly shown, but if I create a small horizontal frame before the first bar to use its "Display key, brackets and braces" to hide the opening bracket across all systems, nothing is hidden.

**To Reproduce**
1. Create a score with several instruments, so that a bracket is shown across the instruments
2. Insert a horizontal frame before the first bar
3. In properties, with the new frame selected, untick "Display key, brackets and braces"
4. Nothing happens

**Expected behavior**
Same as for frames further into the piece:
1. In the same score as above, insert a horizontal frame before the second bar
2. In properties, with the new frame selected, untick "Display key, brackets and braces"
3. Key, brackets and braces are hidden

**Platform information**
OS: Windows 10 Version 2009
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-223472200
Revision: github-musescore-musescore-5485621

**Comment by oktophonie** [comment]
It would be useful to see an example of what you're trying to achieve exactly. I _think_ I get it, but it seems a very unusual thing to want to not have any of this information at the very beginning of a score, which makes me suspect that the current behaviour is by design. It's possible that a better solution could be devised.

**Comment by MarcSabatella** [comment]
FWIW, I don't think there was ever a specific use case we knew about for which we deliberately ignored this option at the start of the score.  I think it's more that when the option was added a few years back, no one ever considered it might be used at the start of a score, so no one ever added a check for it when generating the usual default system header.

Note the same issue occurs at the start of *any* system.  The option currently will force a header to be generated if one wouldn't have been otherwise, but it doesn't *prevent* one from being generated that *would* have been otherwise.  I'm assuming it would be a trivial change though.

I guess the one case I'd be concerned about is a mid-system frame where you've disabled the option for whatever reason:

![image](https://user-images.githubusercontent.com/1799936/220368738-6a41b0f5-0407-4341-9072-a4dd4200a14d.png)

If the layout later shifts in a way that forces the measure after the frame to the next system, you probably *don't* want to suppress the header.  Of course, you probably don't want the frame in that case either, so I'm not sure this is reason enough not to make the change.

**Comment by iainhallam** [comment]
I guess what I'm really trying to achieve would also be solved by #15741 - turning off the extra stuff on the prefatory bar would allow me to isolate the ambitus in it's own bit of stave, which is a style I see more in modern vocal music. (The ambitus next to the clef within the music is the original style from the medieval period, sometimes used on contemporary editions of renaissance music.)

Here's my aim:

![Isolated ambitus](https://user-images.githubusercontent.com/282030/220397589-13004658-4f6d-4e11-bb0b-4f3fe31740ba.png)

**Comment by oktophonie** [comment]
It feels to me like a better way, then, would be to implement a cleverer ambitus/incipit feature for this purpose (which I'd be very happy to have!) With that, one could control all aspects of its appearance, exclude it from playback, etc.

I'm not certain that a fix for https://github.com/musescore/MuseScore/issues/15741 would help, as it supposes that the visibility of brackets will be changeable on each of their appearances (rather than score-wide) which may not necessarily be the case, at least at first.

I'm also somehow uncomfortable with the idea of changing the behaviour of the horizontal frame option for the purpose of enabling something quite specialised, particularly if it has the potential to have some unintended consequences (as Marc describes); to me, at least, it feels like this option should affect mid-system gaps, but system headers should remain immune. I could probably be swayed though; it just requires some thought and discussion.

**Comment by iainhallam** [comment]
A proper incipit feature would be amazing - Lilypond has excellent support for it: http://lilypond.org/doc/v2.24/Documentation/notation/working-with-ancient-music-_002d-scenarios-and-solutions#incipits. That would, I'm guessing, be a different feature request than this!

**Comment by jonarnoldmusic** [comment]
A proper incipit tool would be a game-changer for me. I was about to open a request and then found this thread.

Some desired specs:
Automatic width, simpler creation than current process
No system bracket to the left
Use of medieval/renaissance characters from Bravura (ideally Leland someday)
Positioning of clefs by line rather than manual offset
Centered mensuration sign
Idiomatic key signature selection that follows the clef, noting that sometimes mensural notation has the b-flat in two places
Easy entry of note/rest values placed by note name rather than manual offset
Good (meaning consistently equal) horizontal spacing

Here's what I've been able to accomplish in Musescore (all with manual insertion and positioning of symbols):
![Screenshot 2023-04-02 210113](https://user-images.githubusercontent.com/11447289/229395207-427965f1-88c3-41a3-b811-d5ed599d5b3a.png)

Here's an example of what I've done with Lilypond:
![g2226](https://user-images.githubusercontent.com/11447289/229395485-0d92c629-010d-40d6-9f1b-2cc5ddeb7b2f.png)

**Comment by iainhallam** [comment]
Having opened a request for incipit bars, I feel this could probably be closed now.
