### ISSUE TITLE
[MU4 Issue] Export audio (MP3) of small score is 3-4 times longer comparing with MS3

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#15810]
**To Reproduce**
1. Open [small score MS3.mscz.ZIP](https://github.com/musescore/MuseScore/files/10384598/small.score.MS3.mscz.ZIP) (remove ZIP) in MuseScore3
2. Export MP3 and measure the time - it's about **8sec**
3. Open [small score MS4.mscz.ZIP](https://github.com/musescore/MuseScore/files/10384628/small.score.MS4.mscz.ZIP) in MuseScore4
4. Export MP3 and measure the time - it's about **40-50sec**

**Platform information**
Windows10

**Additional context**

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/211605559-1e005395-9670-40cb-8462-9ac096f78a3a.mp4

https://user-images.githubusercontent.com/90187801/211605587-0bb8dfcf-d311-4eb9-aa4b-70f6633f33af.mp4

**Comment by Jojo-Schmitz** [comment]
Is the score using Muse Sounds or MS Basic? If the former that'd explain the increased size, wouldn't it?

**Comment by DmitryArefiev** [comment]
It uses MS Basic (the second video demonstrates this when I opened the mixer)

**Comment by DmitryArefiev** [comment]
Yes, please see the video

**Comment by MalignantCarp** [comment]
My experience has been similar, though I have been using MuseSounds. Export speed seems to hover around 1-2X real-time, on a 3.8 GHz (overclocked to 4GHz) 6 core Ryzen 5 processor. That is especially painful when exporting each part as individual tracks so I can master in my DAW. A 2 minute and 40 second composition takes around a minute and a half to render each individual part (not sure why it doesn't just do them all at once, since it already has to produce each track for the final mix that it can do at approximately real-time speed).

**Comment by DmitryArefiev** [comment]
> My experience has been similar, though I have been using MuseSounds. Export speed seems to hover around 1-2X real-time, on a 3.8 GHz (overclocked to 4GHz) 6 core Ryzen 5 processor. That is especially painful when exporting each part as individual tracks so I can master in my DAW. A 2 minute and 40 second composition takes around a minute and a half to render each individual part (not sure why it doesn't just do them all at once, since it already has to produce each track for the final mix that it can do at approximately real-time speed).

Thanks for the info. What OS do you have?

**Comment by MalignantCarp** [comment]
Windows 10 Pro Windows 10 Pro 64 Bit, Version 21H2 Build 19044.2486.
It renders much quicker with MS Basic, definitely on par with Reaper, though Reaper would render all those stems simultaneously in that time. So some of that major slowdown seems to be Muse Sounds, perhaps needs some rendering optimization.

I decided I needed to compare apples to apples, since I only ever render to FLAC, so I made use of the MP3 settings from the OP's video to some very strange results:

Muse Sounds FLAC - 2m5s
Muse Sounds MP3 - 2m8s
MS Basic FLAC - 22s
MS Basic MP3 - 1m5s

Definitely an odd difference in export times between the Muse Sounds FLAC and MP3 and the MS Basic FLAC and MP3.

I wouldn't know of any comparisons, timewise, to compare. I normally use FLAC and OGG Vorbis, myself.

**Comment by Kqpout** [comment]
It's apparently slower yet in 4.0.2 
For the same score, same parameters, 3:20 in 4.0.1 vs 4:15 in 4.0.2

**Comment by DmitryArefiev** [comment]
@zacjansheski Can you check MP3 export time using scores from description on you Windows machine (MS3 and latest 4.2 master) please?

**Comment by zacjansheski** [comment]
MU3 - 17.43 sec
MU4 - 1min 5sec

**Comment by DmitryArefiev** [comment]
Fixed in #19078
