### ISSUE TITLE
[MU4 Issue][Regression (by design)] Reinstate multi-sequence shortcuts

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#15820]
**Describe the bug**
It is no longer possible to assign multisequence shortcuts.
While I get that they where not used by a lot of people and don't make sense for all types of actions, keyboard shortcuts are a limited resource and having sequences (at least up to two actions) can alleviate this limitation and/or keep them within single hand range.

**Use Case**
I used the sequence option consistently for the beaming mode actions, where the initial shortcut (Ctrl+Shift+B) was then followed by another single keystroke to further differentiate between single/middle/auto (my most used ones).

Going over a score to modify beaming is now a much slower process (mousing) or requires to sacrifice other shortcut combinations for this single function (change beaming).

**Comment by Jojo-Schmitz** [comment]
See also #13324

**Comment by MarcSabatella** [comment]
My favorite use case was for the various voice exchange functions; I used Backtick-1-2 for exchange voices 1 & 2, etc.

Realistically, if it is decided not to add this functionality back in the UI,. I wonder if there aren't a reasonably easy-to-identify set of cases where these could be useful, and simply define some good defaults for them?

**Comment by Gai-Luron** [comment]
I didn't use this kind of functionality that much, but it was useful to me. I thought it was in the Todo List. Too bad if it disappears.

**Comment by aige02** [comment]
Since I do most of my note entry using the keyboard, I prefer to use a shortcut to mousing to the palette.

**Comment by oMrSmith** [comment]
+1 
Just because users have created several shortcuts for one and the same command by accident,
the possibility to do so should not be taken out as a whole, I think.

**Comment by Tantacrul** [comment]
At present, we do not want to bring this back. The old system came with a really terrible tax on UX. When I tested it on people, they just had absolutely no idea what was going on. I myself didn't get it until a community member explained it.

If we were to bring it back, it would need some kind of specialised (and separate) design, so users would need to consciously 'opt in' to it. I'm going to close this for now because it's not something we are realistically going to look at this year. If someone brings a proposal for how it could work, we'll consider it for sure.

Regarding beaming options, I think we need to make the process of streamlining that workflow as a separate task. Not really relevant to your overall point @jeetee, but I thought I'd mention it.

Thanks!

**Comment by oMrSmith** [comment]
If I may share my experience as a user: I could easily comprehend that one command can have several shortcuts.
What I couldn't understand right away is that they can (or ought to be) be entered in a sequence all at once. 
So maybe if one could only enter one shortcut at a time and click add, it would have been less confusing...

**Comment by jeetee** [comment]
I think @oMrSmith just has proven that a better though out design would indeed be required for this in the future; as this issue is **not** about entering multiple different shortcuts for a single action :-p

As stated initially, as long as fiddling with the shortcuts file keeps working to enable shortcut-chains (multiple sequential "shortcuts" act as a single action) my needs are satisfied.

Totally fine with not tackling a UX for it and eventually future reopening if non-power users come to request this functionality.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/390879. 

Can this issue get reopened?

**Comment by Gai-Luron** [comment]
Hello,
for me is a good idea to reopen this issue. 
Robert
