### ISSUE TITLE
[MU4 Issue] measure number range under multimeasure rests has a weirdly wrong first number...

### ISSUE THREAD

**Issue by bmillions** [musescore/MuseScore#15846]
Please accept my apologies if this is the wrong place for this bug report. I was directed here by a fellow musescore user, "Jojo-Schmitz."

Here's what's happening:

<img width="591" alt="Screen Shot 2023-01-11 at 12 01 43 PM" src="https://user-images.githubusercontent.com/122565138/212163242-08d48ffc-c7be-4472-b8b9-7e1c03167d4e.png">

See screenshot. For a measure number region like "measures 71-78" I'm getting the following text: "[%61-78]"

The first digit is always 1 lower than what it should be. And I have no idea where the "%" is coming from.

I do have a pickup measure, 3 8th-notes long.

I'm using musescore 4.0.0.223472200, revision 5485621 on a mac, os 10.14.16.

I'm attaching the musescore file. 

[I Can Cook Too m4.mscz.zip](https://github.com/musescore/MuseScore/files/10405371/I.Can.Cook.Too.m4.mscz.zip)

Again, apologies if this is the wrong place for this. We're all busy humans and I don't want to waste anybody's time - and I freaking love this program and am over the moon with joy at the monster update that is 4.0. 

THANK YOU, AWESOME PEOPLE.

**Comment by MarcSabatella** [comment]
It's the right place, but you're too late - this has already been reported and fixed :-).  See https://github.com/musescore/MuseScore/issues/15635

**Comment by bmillions** [comment]
WOOT!!! That's rad!

**Comment by bmillions** [comment]
Forgive my ignorance, but: where can I download a build with this bugfix in it? I'm new here.

**Comment by MarcSabatella** [comment]
Well, normally I would say it's in the latest nightly builds, except right now, the nightly builds are from the "4.0.1" branch instead of the "master" branch, and I don't think this fix is being considered for 4.0.1 - that release is focused on the most critical issues like corruptions and crashes.  So you'd need to find the most recent "master" build you can.  Nightly builds are available for testing at https://ftp.osuosl.org/pub/musescore-nightlies/
