### ISSUE TITLE
[MU4 Task] Add two MS4 project issue labels.

### ISSUE THREAD

**Issue by jjdonson** [musescore/MuseScore#16007]
**Task description**
Add two issue labels at https://github.com/musescore/MuseScore/labels

- MuseScore3xFileUpgradeTesting
  - The reason for this is to aggregate those issues that regard MS3 file upgrades.

- MuseScore4xCopyPasteBestPractices
  - The reason for this is to aggregate those issues that regard MS4 copy/paste best practices.

**Comment by cbjeukendrup** [comment]
What would be the benefit of this? (Except that it will be a lot of work to apply these labels to each issue and that it most likely won't be done consistently because people don't know or don't care so it will be useless a priori.)

If you can see a list of the issues that happen to be related to 3.x files, what does that help? It does not fix the issues, it does not mean they will get fixed faster, and since most of these issues are technically completely unrelated, they will need to be solved one by one anyway. For those <1% of issues that happen to be related to some other issue, it is way more practical to link them together by positing a comment. (And having a list of issues that belong to a certain topic but have no further relation, won't help much in finding issues that _are_ related. If you want to see less issues at once, a topic-based list is hardly more helpful than any random subset.)

So, topic-based issue lists and labels might seem a nice idea in theory, but they have no utility in practice. 

> The reason for this is to aggregate those issues that regard MS4 copy/paste best practices.

What do you mean? That definition including the words "best practices" sounds like some kind of support article that doesn't belong here on GitHub; definitely not the definition of a kind of issue.

**Comment by jjdonson** [comment]
Good Morning.
Thanks for your questions.
You assume I am suggesting all issues must be properly labeled?
Nope.  That was all yours.

It would take 5 seconds to add 2 labels.
_The time invested against high-quality upgrade support seems much higher, without any payoffs._

Also, not everything in issues is for the dev team.
I place a high value on organized and effective user support.
That includes sample file testing, and demos of what reliably works.
User empathy is at the core of that sensibility.

"What would be the benefit of this?"

My suggestions are for improved user support, not for the dev team.
Test-Driven paving of the MS4 road using sample files is for user support.

- Losing any of the MS3 user base is worth avoiding.
- Preventive user support is better than reactive user support.
- The benefits are to the install base of MS3.x users who want to use MS4.
- Proactive user support prevents predictable confusion.
- Forcing the MS3 user base to waste time and risk work is simply not acceptable.
- Even risking this is counter-productive to user experience.

By the way, I have worked in open source for 20+ years.
Until there are sample files to test for upgrades, this is haphazard and sad to watch.
Every new MS4 feature presents challenges for MS3 upgrades.  Every single one.... <nods>
File testing is how to pave the road for upgrades.

With regard to the second label I suggested....
Copy-paste is expected to save time, right? (rhetorical)
Copy-Paste issues in the app are their own set of varied challenges.
Acting like those copy-paste issues are unrelated issues serves no one.

Takeaway Emphasis:  User Empathy

Next Steps:
- Choose sample MS3.x files for testing.
- Show how they can be upgraded safely.
- Use that sensibility to verify that new 4.x features can support MS3.x file upgrades with min or no hassles.
- Begin solid CLI tool development for file testing.

**Comment by cbjeukendrup** [comment]
GitHub is absolutely not for users and user support. It _is_ meant to be used internally (among dev team + community developers). Users who know what they are doing are welcome to log bugs here directly, but support happens on musescore.org, so that GitHub remains clear and to-the-point. 

The situation on musescore.org is admittedly not great. We do what we can to make small incremental improvements there, but we don't have full front-end and backend teams available to work on it full time. 

You also mention testing; we have pretty good automated unit test systems that prevent regressions when it comes to reading and rendering files (the "visual tests", as we call them). But for the rest, it is true that our automated interaction tests deserve some love. 
But what you couldn't know, is that we have professional Quality Assurance engineers in the team, who work full time on testing every aspect of the app; migration from MS 3 included. So it is absolutely not true that things are not tested properly or that there is any danger or risk for users (not more than in any other app). The amount of issues relating to upgrade problems is indeed small (apart from maybe a few conscious changes).

(Also, it seems you're regarding "upgrading to MS4" as something huge; it isn't. You just open your file in MS4 and it just works.)

**Comment by jjdonson** [comment]
"You just open your file in MS4 and it just works"

But that is simply not the case with 3.x files.
Denying reality is not how to do good tech support.

  Why not deal with reality?

You clearly have no interest in protecting the 3.x files, and that is inexcusable.

Those who want to do marketing instead of engineering are a joke.

Open source depends upon honesty, not BS.

**Comment by cbjeukendrup** [comment]
Your comments always seem completely disconnected from the reality. I have no idea what you are talking about. If you can point us to examples of well-written issues with 3.x files, that haven't been fixed yet, we will consider those of course.
