### ISSUE TITLE
[MU4 Suggestion] Change shape of mouse cursor on tabs/title bar of detachable panels to make clear that they can be detached

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16011]
It has happened a few times that a user suggested "It would be great if we could detach those panels from the main window". 
And the answer is of course: you can already!

Apparently this is not very discoverable. We could try to give users a hint by changing the shape of the mouse cursor, for example to the "grab" / "open hand" cursor ![image](https://user-images.githubusercontent.com/48658420/213937347-536d6aee-6143-4a53-8f5b-e69d945c733a.gif) from https://doc.qt.io/qt-6/qt.html#CursorShape-enum. More ideal would be the "move" cursor ![image](https://user-images.githubusercontent.com/48658420/213937310-e7298eb9-fb2f-49f2-9e36-95c0f96f5bf4.gif), but that doesn't seem supported by Qt.

**Comment by iwoithe** [comment]
> More ideal would be the "move" cursor image, but that doesn't seem supported by Qt

`Qt::SizeAllCursor`?

**Comment by cbjeukendrup** [comment]
Ah yeah, that's the one probably. Somewhat strange name...

**Comment by FigmentBoy** [comment]
> Ah yeah, that's the one probably. Somewhat strange name...

To me, that cursor image feels more adequate to signal being able to resize the panel rather than to signal being able to move the panel. I believe it is used in most applications when resizing the window from the corner, resizing in all directions instead of just on one axis, which is where it got its name. Personally, I think the "grab" image better signals being able to detach the panel.

**Comment by daijingz** [comment]
I want to work on this issue, can I?

**Comment by daijingz** [comment]
I have a question: which part of MuseScore Windows can be detached from the main window?
Here I see different sections of the main window, 
![C`5FNPH}`W_~_%WW_ ~(QV3](https://github.com/musescore/MuseScore/assets/61481741/57fb89a0-c889-47eb-9012-55cd6481ba46)

I see an option in this issue: we can detach the left sidebar from the main window. To detach the window, we can add a "detach" button on the top right side of the whole page. After clicking this button, the mouse cursor was changed, and now we can use the mouse to detach the window.

There are some places else, where we can detach the window. I am still looking for it.

**Comment by cbjeukendrup** [comment]
@daijingz The following parts of the UI can be detached:
- the panels at the left (or right) side of the window
- horizontal panels like the Mixer panel
- some of the toolbars

For the vertical and horizontal panels: you don't need to know all panels that exist, because there is one component that's reused for the tab bar of each panel. You should implement the changes in that component. These components are the following:
- DockPanelTab.qml, which are the tabs that you see when multiple panels are attached in the same part of the window
- DockTitleBar.qml, which is the title bar that you see when one panel is attached alone in some part of the window

For the toolbars: actually the same applies. You just need to modify the base component. For toolbars, the draggable area is that "grip" button that you see at the left of the toolbar content. You can find this button somewhere in DockToolBar.qml.

Visual explanation:
<img width="1552" alt="Scherm­afbeelding 2023-07-28 om 13 36 45" src="https://github.com/musescore/MuseScore/assets/48658420/e5dfb514-089b-430a-926b-5d9ec59754a2">

So, to be clear: the only task is to change the mouse cursor shape when hovering these components. As I've explained before, that can be done by setting the [`cursorShape`](https://doc.qt.io/qt-6/qml-qtquick-mousearea.html#cursorShape-prop) property of a MouseArea; you can create a new MouseArea for that, or reuse an already existing MouseArea.

**Comment by daijingz** [comment]
Step 1: find the corresponding code part: https://codebrowser.dev/qt5/qtdeclarative/src/quick/items/qquickmousearea_p.h.html#QQuickMouseArea
So I only change the mousearea code here

**Comment by daijingz** [comment]
Step 2: Analyzing the code
In this given program, there is a defined mouse area class "QQuickMouseArea", which sets up a mouse area.
I am building a new mouse area like this.

**Comment by cbjeukendrup** [comment]
@daijingz Why are you re-creating MouseArea? You can just use the one from Qt. We are already doing that in numerous places. You just need to make sure that you have `import QtQuick 2.15` at the top of the QML file, and then you can simply write `MouseArea { … }` to instantiate a MouseArea. 

If it wasn't clear yet, MuseScore uses the Qt library; so you can use all components from that library, and shouldn't recreate them. That link that I had given you (because you asked for it) is indeed the source code of MouseArea, but as I said, that is not relevant if you just want to _use_ it.

You can search in the code for `MouseArea {`, to find places where it is already used, as examples.

**Comment by daijingz** [comment]
I see

**Comment by daijingz** [comment]
Current Status: I have added mouse cursors inside the DockTitleBar.qml, and I am running it.

**Comment by daijingz** [comment]
URGENT: Now I add the mouse area to the three fields:

    MouseArea {
        id: mouseArea
        anchors.fill: parent
        acceptedButtons: Qt.NoButton
        cursorShape: Qt.SizeAllCursor
    }

But the original problem still exists: the software does not have any changes when the mouse cursor is moved to the dragable area. Seems like there is no syntax and semantics mistake, 

Maybe I made a mistake on the build & run process so that the output effect is invisible. What I test is, at first I change program files. After saving it, I USE the Qt creator the run the software. Is my process correct?

**Comment by cbjeukendrup** [comment]
@daijingz I've tried it out for you, and it works fine when I add it to DockTitleBar.qml just above the `Column {`:

https://github.com/musescore/MuseScore/assets/48658420/e766a6a6-d03a-4d6e-94c6-1aed099efa29

However, adding it to DockPanelTab.qml does _not_ entirely work, because in DockFrame, where DockPanel is used, there is a MouseArea that covers the tabs and thus takes priority over any MouseArea inside DockPanelTab. However, the solution is simple: you just change the cursor shape of that existing MouseArea.

And in DockToolBar.qml, it works too, when I add a new MouseArea inside the FlatButton. However, the FlatButton already contains a MouseArea, and exposes this via the `mouseArea` property. So you can save performance cost of creating a new MouseArea, and set the properties of that existing MouseArea instead.

**Comment by daijingz** [comment]
My Progress: 
![3609AFOKWJ6MR3~JDS8ON3J](https://github.com/musescore/MuseScore/assets/61481741/49b22bd2-cb95-4eef-9854-70efe241c008)
![YJA11(YFMTUO3$AF{365O}6](https://github.com/musescore/MuseScore/assets/61481741/d23bfccb-c183-4a6f-998a-a7378c228a9a)
![0ODST{JFMZ9B SSM5LB$X~Y](https://github.com/musescore/MuseScore/assets/61481741/64194b5b-6db6-46c1-9feb-c5f8a617cabb)
The first is in DockTitleBar.qml, while the second is in DockToolBar.qml and the third is in DockFrame.qml. Because later two files there are already had some defined mouse areas, I directly changed their parameters as well.

The most upsetting thing is, my PC running did not show any changes in the mouse cursor shape. It is clear that my running and testing methods must have problems. I can provide files for others to test. I wonder how I can see the effects.

**Comment by cbjeukendrup** [comment]
Let's see if we can find out what's wrong with your environment. Perhaps that's easier to do on Discord, so I'll message you in the Development channel.
