### ISSUE TITLE
PLUGIN: Add Lillylyrics plugin to MuseScore 4

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#16023]
**Task description**
It has been pointed out to me that this '[Lilypond Lyrics](https://musescore.org/en/project/lilypond-lyrics
)' plugin already works in MS4 by placing it in the plugins folder and making two quick changes to the QML so it pops up in the UI.

![image](https://user-images.githubusercontent.com/21022311/214058345-3aa966a9-1f0b-41bb-8608-81b55a0bceb0.png)

We should include this plugin.

@jessjwilliamson - we'll probably need a new image for lyrics-related plugins.

**Comment by themodrnhakr** [comment]
@Tantacrul, what are the QML tweaks? I haven't been able to get it to work.

**Comment by jessjwilliamson** [comment]
Thumbnail is on its way :) @Jojo-Schmitz

**Comment by Jojo-Schmitz** [comment]
Also `property var font:"\"FreeSerif\"";` should probbaly use Edwin instead?

**Comment by MarcSabatella** [comment]
I was checking this out, and it definitely has potential!  However, I would question whether it is worth holding onto the actual LilyPond syntax - which requires two hyphens delimited buy spaces rather than ordinary single hyphens placed within words, and a weirder harder to describe method of doing melisma.

I'm not a plugin expert by any means, but it looks like it would be pretty straightforward to fix the syntax to be more like that old MU3 syntax, which people are used to and is simpler to type.  The "Expand" function looks to already fix hyphens (turning normal ones into the LilyPond format) so we could simply call that function automatically.  Underscores are a bit weirder still I think.

**Comment by DmitryArefiev** [comment]
Implemented in #17139
