### ISSUE TITLE
[MU4 Issue] No indication when error occurs while saving a file

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16104]
**Describe the bug**
Users have reported that sometimes nothing happens when saving, nor when clicking "Save" in the "Do you want to save" dialog. The dialog just disappears, but the score stays unsaved, and MuseScore doesn't close.

**Proposed solution**
We should show a dialog that saving failed, preferably with detailed information about why, so that the user can do something about it.

Came up in:
- Discord (https://discord.com/channels/818804595450445834/818804809784229898/1068615895938773013)
- https://musescore.org/en/node/340287

**Comment by bkunda** [comment]
Note: in this case, errors while saving a file occur due to operating system issues (destination location not available, SSD failure, etc.).

**Comment by DmitryArefiev** [comment]
Fixed in #17369 

Message when trying to save in folder without permissions:
![Capture](https://github.com/musescore/MuseScore/assets/90187801/77876810-10b9-43de-aa9d-4ab4c364e67d)
<img width="386" alt="Screenshot 2023-06-30 at 16 13 55" src="https://github.com/musescore/MuseScore/assets/90187801/7fdb9732-42d9-4b3d-982b-f283ab4039da">

Message SSD failure:

![Capture2](https://github.com/musescore/MuseScore/assets/90187801/e754cb5d-f7b4-4a09-ad2f-2a1ad3ea396b)

<img width="358" alt="Screenshot 2023-06-30 at 16 23 39" src="https://github.com/musescore/MuseScore/assets/90187801/6c86b8b2-2b05-45a9-bda6-6dbd95b589fb">
