### ISSUE TITLE
[MU4 Issue] Crash when exiting Remote desktop

### ISSUE THREAD

**Issue by ThoStaKa** [musescore/MuseScore#16230]
**Describe the bug**
MU4 shuts down when exiting remote desktop session with MU4 running on the remote computer.
Tested with Chrome remote desktop, windows RDP and Azure Virtual Desktop

**To Reproduce**
1. Log in to a remote computer with remote desktop
2. Start MU4 on the remote computer
3. Exit remote computer without, but keep MU4 and the remote computer running
4. Log into the same remote computer again
5. Observe that MU4 is closed
6. Start MU4
7. Error message: "The previous session quit unexpectedly. Do you want to restore the session?"

**Expected behavior**
I expected MU4 to stay alive on the remote computer

**Screenshots**

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
Hi! I think there is a chance that this will be fixed by #17485. Could you please do the following:
1. Download this build: [MU4_231261829_Win_fix_windows_crash](https://github.com/musescore/MuseScore/suites/12721517963/artifacts/683225342)
2. Run the MSI installer from that ZIP folder
3. Try to reproduce the crash in the version installed by that installer

**Comment by zacjansheski** [comment]
Closing due inactivity
