### ISSUE TITLE
[MU4 Issue] Parts are not formating correctly (URGENT)

### ISSUE THREAD

**Issue by GabrielYudenich** [musescore/MuseScore#16243]
**Describe the bug**
I think i don't need to describe it. But its clear on the picture. The parts are not formatting correctly and are giving an awful experience! This need to be fixed RIGHT NOW!

**Screenshots**
![image](https://user-images.githubusercontent.com/51841352/217063860-3f53475d-78eb-4e32-a520-651f172ce5ac.png)

**Platform information**
Windows

**Additional context**
It's my composition, and the parts (almost all of them are like that). The full score its okay but the parts are awful. Please fix it!

**Comment by cbjeukendrup** [comment]
That score is corrupted, otherwise you would not get something like that. (At present, you won't see a warning about this if the corruption is in the part scores only; that is being worked on.)

If you would like us to investigate this issue, you need to upload the score here (wrap it in a ZIP file so that GitHub lets you upload it). 

We are working on a way to reset parts, which would get rid of the corruptions so that the parts should display fine again.

**Comment by GabrielYudenich** [comment]
If i can send you by email or any kind of transfer because it's composition of mine soo if i send here the edited file, someone can stole my work or comercialize without my consent unfortunatelly

But i'm very very happy to help with this issue

I love this new update of musescore 4 but it's really with a lot of bugs

**Comment by cbjeukendrup** [comment]
You could email me the score at `c.jeukendrup (at) mu.se`. Or, if you use Discord, you can send me a private message (you can find me in the MuseScore Discord server, which is at https://discord.gg/HwHhXEbJ4r).
