### ISSUE TITLE
[MU4 Issue] Edit - Preferences - Appearance - Background doesn't work

### ISSUE THREAD

**Issue by RichardJECooke** [musescore/MuseScore#16255]
**Describe the bug**
Selecting a wallpaper for the app background and paper background has no effect.

**To Reproduce**
1. Open Musescore 4 on Windows 10
2. Edit - Preferences - Appearance - Background - Select wallpaper
3. Ok and exit menu
4. No change

**Expected behavior**
Change

**Comment by zacjansheski** [comment]
Closing

**Comment by MarcSabatella** [comment]
I suspect the confusion is regarding "paper" vs "background".  "Background" doesn't affect the page itself, but the area outside the border of the page:

![image](https://github.com/musescore/MuseScore/assets/1799936/faed5ace-8dfb-47ef-8ccb-d732255c5280)

This does work as expected.  If you want to change the paper color, use the paper setting instead of the the background setting:

![image](https://github.com/musescore/MuseScore/assets/1799936/2b9f267e-a5a5-400b-9ff9-5f7a21d548ff)

The settings do work as expected, *however*, neither of these settings get applied if you quit/restart, and that's still true in current master.  See https://github.com/musescore/MuseScore/issues/16930

**Comment by JasonKayel** [comment]
Is this issue solved yet?
