### ISSUE TITLE
[MU4 Issue] "Play'' box on dynamics is greyed out and effect on playback can't be disabled

### ISSUE THREAD

**Issue by Stccl** [musescore/MuseScore#16279]
**Describe the bug**
The "Play" box in the properties for dynamics (including hairpins) is greyed out, making the creation of a dynamic that doesn't affect playback impossible.
Current workarounds include adding it as plain text using the ctrl+shift+letter method (but then musescore doesn't know it's a dynamic and doesn't position it accordingly in the layout), or adding a dynamic that doesn't have playback support and edit this with the previously mentioned method.

**To Reproduce**
1. Place notes on a staff and add a dynamic.
2. Select it and go to properties
3. The "Play" box is unusable

**Expected behavior**
The "Play" feature should be usable and unselecting it should make the dynamic have no effect on playback.

![image](https://user-images.githubusercontent.com/50422710/217574849-a76492b2-8fea-4241-9090-ae9cddd8764b.png)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by cbjeukendrup** [comment]
Related to https://github.com/musescore/MuseScore/issues/15899

**Comment by Reedbeta** [comment]
In addition to this, we've lost the ability from MuseScore 3 to fine-tune the MIDI velocity value sent by dynamic markings. 😢

**Comment by Fristover** [comment]
> In addition to this, we've lost the ability from MuseScore 3 to fine-tune the MIDI velocity value sent by dynamic markings. 😢

This got moved to the notes instead of the dynamics themselves, you have to select all the notes and change their velocity now (though it won't work with Muse Sounds)

**Comment by exegetor** [comment]
This one is important!  Given the inconsistent playback volumes in the new soundfont, it can't be overstated that we need to use visible but inactive dynamics for a printed score as well as invisible but active dynamics for exporting a good playback.

**Comment by fsgregs** [comment]
I cannot stress enough that assigning a different velocity or volume to a dynamic mark or a hairpin, is absolutely vital to me being able to use MS 4.1 or later.  The difference between a "p" (dynamic of 49) and "mp" (64) is just too large.  I want to be able to quiet an "mp" or louden a "p" to values between the two, as MS 3.6 allowed us to do.  I use custom dynamics all the time, but I cannot even create and save a custom dynamic with the "Play" box darkened in MS4.  

Likewise, a hairpin should be able to be set via a **Play** tab to any value we want without it ending in a letter dynamic, as in MS 3.6.  For example, in this screenshot, I want the red hairpin at the top to boost ALL instruments in the score by a volume of 10 as a crescendo, so that a 'p" dynamic on a horn goes from 49 to 59, and a "pp" dynamic on a violin goes from 33 to 43.  The hairpin allows me to crescendo all instruments, without having to force them all to jump to a particular letter dynamic following the hairpin.  This is very common in scores that may have 20 or more instruments to deal with.

![image](https://github.com/musescore/MuseScore/assets/133777637/27624fb9-c987-465a-a63b-751942f527ce)

**Comment by cbjeukendrup** [comment]
See https://github.com/musescore/MuseScore/issues/13858#issuecomment-1662938977
