### ISSUE TITLE
[MU4 UI] Add icons to palettes

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#16301]
**Describe the issue**
I often find myself looking through the palettes and have difficulties finding the right palette, so because I think it's a known fact that icons often can communicate information faster than text, I'd recommend adding them.  

**Drafts**
Here I made some (ugly) drafts. It's up to the team what to choose (other alternatives can be made).

![pallete-new](https://user-images.githubusercontent.com/79419198/217945318-536e09ad-e292-43f6-b149-71c720ed2870.png)

**Comment by DaddyLudwig** [comment]
That sharp could conceivably fit with the accidentals palate though, maybe if you used the sharp for accidentals and a 2 sharp key signature for key signatures? Just a thought. I know it’s hard to take some things down to icon size and a 2 sharp key signature might be one of those.

**Comment by PetJer** [comment]
@DaddyLudwig, sure! I forgot that palette existed. But no worries, it's just a quick scetch in Libresprite mainly to show the possible arrangements of the elements. The real icons will be svgs and design by the UI designers from the internal team, so they'll possibly have a talk for what icon best represents the palette.

**Comment by Tantacrul** [comment]
I'm not really into this suggestion. However, I do think we need a 'minimal' version of Palettes that _should_ make use of icons without text. There was a design for this a few years ago I can't find but it's in my head.

I'm going to close this suggestion just because I don't really think it's the right solution. It'll be really noisy and cluttered looking.
