### ISSUE TITLE
[MU4 Issue] Ties not being registered by playback

### ISSUE THREAD

**Issue by MouldyCheese** [musescore/MuseScore#16333]
**Describe the bug**
In all scenarios, when a tie is used to extend the value of a note, the playback will ignore it and play the following note as if there was no tie.

I have attempted restarting musescore and my computer.

I posted this on the musescore forums and other people tested the score and said they had the same issue, which makes me think the issue is unique to this specific score. 

https://user-images.githubusercontent.com/120740677/218327294-8f8dc204-a9ce-494c-8ae5-ea2fb1d0143d.mp4

**Comment by Jojo-Schmitz** [comment]
Score attached to [v](https://musescore.org/en/node/344813#comment-1173904)

**Comment by ChriiMoral** [comment]
This issue is also present in other instruments. (MuseScore 4.1.1)
While more subtle, you can hear the note re-triggering.

https://github.com/musescore/MuseScore/assets/63615949/77e81799-a2ab-4a08-9d67-e9ae4738219c

**Comment by MarcSabatella** [comment]
I think your issue is something different - a more subjective call as to whether there should be a subtle bump in the middle of a tremolo to indicate where a note has been broken with a tie or not.  To me it's an open question, but it's really a special case of https://github.com/musescore/MuseScore/issues/15713, not related to the current issue, which doesn't involve tremolo at all.

**Comment by ChriiMoral** [comment]
> @ChriiMoral I think your issue is something different - a more subjective call as to whether there should be a subtle bump in the middle of a tremolo to indicate where a note has been broken with a tie or not. To me it's an open question, but it's really a special case of #15713, not related to the current issue, which doesn't involve tremolo at all.

Thanks for clarifying!

**Comment by MarcSabatella** [comment]
As noted in the forum thread, the issue here are the bogus "a tempo" and "rit" markings, which are not atempo marks at all but rather playing technique annotations.  As such, this is similar to the issues fixed in https://github.com/musescore/MuseScore/pull/18891 - but unfortunately, this particular variant is still present in master.

Fix for this score is to remove the bogus markings and enter those as regular tempo text, or expression text or staff text etc.

**Comment by wizofaus** [comment]
Looking at that score how can tell that what appears to be just expressive text "rit." is actually a particular playing technique? And what is that technique?  It sounds truly bizarre using Muse Keys piano.

**Comment by bkunda** [comment]
I can no longer reproduce the primary issue above (with the attached score) using MS Basic in the current master.

https://github.com/musescore/MuseScore/assets/86290556/99b3792c-d934-4d42-9035-672573c971ad

(Muse Sounds currently shows other issues, which seem unrelated and will be addressed on the sampler end).

For this issue to be helpful, it needs to be specific. It's both untrue and unhelpful to write: 

> In all scenarios, when a tie is used to extend the value of a note, the playback will ignore it and play the following note as if there was no tie.

The matter of tremolos being re-triggered by ties has been raised elsewhere. Please refrain from raising overly general issues as they just waste valuable time investigating what the precise problem is.
