### ISSUE TITLE
[MU4 Issue] -f option not working

### ISSUE THREAD

**Issue by 00sapo** [musescore/MuseScore#16444]
**Describe the bug**
Option `-f` is ignored with musescore 4.0.1 (don't know about previous versions)

**To Reproduce**
* Download attached `test.xml.zip`
* `mv test.xml.zip test.mxl` (needed because github doesn't let me attach `mxl` files)
* `mscore -fo test.mid test.mxl`

**Expected behavior**
Produce `test.mid` without GUI interruptions. It instead creates the dialog saying that the file is corrupted and asking if it should continue opening it.
[test.xml.zip](https://github.com/musescore/MuseScore/files/10784225/test.xml.zip)

**Platform information**
-OS: Linux Manjaro (Arch-based)
-Musescore version: Manjaro repository 4.0.1 and AppImage 4.0.1 tested

**Comment by Eism** [comment]
try `mscore -f -o test.mid test.mxl`

**Comment by 00sapo** [comment]
Doesn't work. It works with 3.6.2

**Comment by 00sapo** [comment]
Any news about this?

**Comment by 00sapo** [comment]
Tested and it has the sme issue: it opens a gui popup asking confirmation because the file has some issue (it was prepared using Final). If -f is used, it should just convert it...

**Comment by nasehim7** [comment]
Greetings @Eism @cbjeukendrup @00sapo My initial analysis why it works in 3.6.2 and doesn't in MuseScore 4.x version is due to the following:
 3.6.2:- https://github.com/musescore/MuseScore/blob/4566605d92467b0f5a36b3731b64150500e48583/importexport/musicxml/importxml.cpp#L205

During the start, we set that the task is going to be noGui so when we check here, this should come as true and give no error in the file.

On the other hand:
master:- 
https://github.com/musescore/MuseScore/blob/e7049332389a42a1571116882a0340f1abd8ee68/src/importexport/musicxml/internal/musicxml/musicxmlvalidation.cpp#L198

We are doing something similar but this time the property is RunMode::ConsoleApp which makes the condition false and executes line 201 which is the Dialog Box.

I think a better solution would be to propagate the `forceMode` information downstream from  `MusicXmlReader::read` till `doValidateAndImport` function of importxml to decide beforehand to validate or not. Let me know what is your take on this? meanwhile I am on it
