### ISSUE TITLE
Fix implementation of ghost notes and dead notes

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#16500]
**Task description**
We should support both ghost notes and dead notes (to use Guitar Pro parlance, for now):

![image](https://user-images.githubusercontent.com/20604032/220854984-482b18b4-b0a5-4795-9bd8-a1e1abd15b90.png)

In MU3 a fret mark could be turned into an X (albeit too small) with `Shift`+`X`.

Since MU4.0, since at least https://github.com/musescore/MuseScore/pull/10444 (which was to enable correct import from Guitar Pro), this shortcut now parenthesises the fret mark instead. This makes it impossible to achieve the X (as reported at https://github.com/musescore/MuseScore/issues/16490; this task replaces that issue).

This is my proposal to sort out the interactions. (Guitar mavens please weigh in to tell me in what ways it's inadequate or stupid):

- A dead note is created by selecting a fret mark and pressing `Shift`+`X`, which turns it into an a X; the linked note should also change to a cross notehead. You can achieve the same by selecting the note and changing its notehead to a cross, which will likewise change the corresponding fret mark to an X. (It would be nice to use `Shift`+`X` on a note for this, but that has a different function on standard staves.)
- A ghost note is created by selecting a fret mark and pressing `(` (i.e. `Shift`+`9`), which applies parentheses to it; the linked note should also have parentheses applied (from the music font; their placement is not good just now but that's a separate task).
- Both of these act as toggles, so pressing a second time undoes these changes.
- If there's a use for doing both of these on the same note (i.e. a parenthesised-X-fret and a parenthesised-X-note), then fine.

Naturally, any changes made must not negatively affect GP import.

The problem with migration remains open as a separate (but obviously related) issue (an X-fret in MU3 should remain an X-fret in MU4): https://github.com/musescore/MuseScore/issues/13736

See also this task: https://github.com/musescore/MuseScore/issues/14294

**Comment by rgreen5** [comment]
The proposal looks OK. Just to add the obvious, that dead and ghost notes should also be similarly applicable for tablature both on its own and in unlinked (same instrument) staff/tab pairs.

**Comment by bkunda** [comment]
This makes sense to me. I'd add that these shortcuts should also be reflected in relevant settings in Properties, because shortcuts shouldn't be the only available method. Currently the notehead type ‘X' produces a different kind of notehead to the dead note shown in the image above, so perhaps this needs to be added to the ‘Notehead type‘ palette (and selected when the Shift+X command is used). Similarly for ‘Notehead parentheses‘, which currently produce a different kind of parentheses to the one achieved by Shift+X.

Perhaps this is a separate issue, but I think it's not unrelated and should be considered for implementation together with addressing the issue of these shortcuts.

**Comment by rgreen5** [comment]
Presumably, the size of the X will be increased as well in this fix.

**Comment by abariska** [comment]
Just linking related issue https://github.com/musescore/MuseScore/issues/11602
