### ISSUE TITLE
[MU4 Issue] Colored notes (and other elements) don't appear colored when "invert score colors" is enabled

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16506]
**To Reproduce**
1. Change the colour of some note or other element using the Properties panel or a plugin
-> the coloured note appears coloured correctly 
2. Go to Preferences > Appearance and enable "invert score"
-> the coloured note appears just white

**Comment by GabeS573** [comment]
The question is, should any color that is not black or white remain as it is, or be inverted as well? (For example, should red stay red or should it become cyan?) It would probably make more sense to not invert all the colors besides black and white, but then the name "Invert score" might be a bit misleading.

**Comment by MarcSabatella** [comment]
What I might suggest is convert the values to HSV and preserve the "hue" and "saturation", but invert the "value".  Probably there is some alogrithm out there for this.  The idea being, someone might have selected a relatively dark red to stand out nicely on white, but that same red won't stand out so well on black, so replace it with a light red.  Mid-value colors would remain unchanged.

**Comment by Jojo-Schmitz** [comment]
@cbjeukendrup could you please use American English spelling, at least for the title ?

**Comment by cbjeukendrup** [comment]
Yes, changed it. (It's my auto-correct that turns everything into British English...)

**Comment by PepijndeMaat** [comment]
@MarcSabatella I think you mean to swap the 'saturation' and the 'value'. In that case bright red stays bright red while dark red and pink swap places. If you just mirror the 'value' then bright blue (on white) becomes black (on black), which is likely not what you intent.
Or equivalently, if you use a 'hue', 'saturation', 'lightness' model and then you can mirror the 'lightness'.

**Comment by MarcSabatella** [comment]
The way I learned it in art classes, value *is* lightness.  So yes, I want to turn a dark color into a light color, while keeping the hue (red vs blue) and saturation (= intensity; pure color vs dull).

**Comment by PepijndeMaat** [comment]
@MarcSabatella Okay, then we agree.
From draw/types/color.cpp I think the colour is stored in rgb (and ɑ), so then a possible (simple) algorithm is (for r,g,b values 0 to 255):

- If (0, 0, 0) then return (255, 255, 255).
- Else calculate m=Min(r, g, b) and M=Max(r, g, b), find x = (255 - m - M), return (r+x, g+x, b+x).

This formula looks a bit odd, but correctly rescales M to (255 - m) while keeping the chroma C = M-m fixed. The lightness L is M - C/2 and that becomes (255 - m) - C/2 = 255 - L, so that should look about how you intended it. Please do check if this is what you meant; there are other ways of inverting the lightness but this is the only linear model.

**Comment by Jojo-Schmitz** [comment]
When in doubt, try it out. Then post images of the result ;-)

**Comment by PepijndeMaat** [comment]
![image](https://user-images.githubusercontent.com/26623282/222910491-f910329f-133a-4ca5-9f70-f1a532808daa.png)

This is what the above linear algorithm looks like. The odd columns are input, increasingly dark colours on a white background. The even colours are output, increasingly light colours on a black background.
To check that the algorithm works for arbitrary colours, here is the same table but with the top row of odd columns randomly generated:

![image](https://user-images.githubusercontent.com/26623282/222911568-8962a81f-d68b-4040-9ca7-bf36640e3df1.png)
![image](https://user-images.githubusercontent.com/26623282/222911880-f12587a7-e072-44ba-8b76-e1b374771672.png)

Images made in Mathematica.

**Comment by Jojo-Schmitz** [comment]
OK, now is seems time to implement that in MuseScore

**Comment by limse10** [comment]
This looks cool! Can I work on this?

**Comment by PepijndeMaat** [comment]
@limse10 
Your implementation seems to correctly work for custom colours, but note that it also changes the default colour from the slightly grayish white to white. Was this intentional?
I didn't account for that in my pseudocode (which was intended for custom colours, sorry for that), but you could e.g. check if x is 255 and if so set it to 220 instead? Or you could also argue that anything above a certain brightness should then also be dulled and use an inequality?

Anyway personally I don't mind if you leave it like this, but I thought I should let you know that this is changing the default behaviour for people who don't use colour.

**Comment by limse10** [comment]
@PepijndeMaat You're right, it was an oversight on my part. I've made it so that if the resulting color is pure white, it sets it to the dulled white instead. Values in between 220 and 254 are left as is. I would justify it as "if the user wanted to change colors, they are allowed to do so" but default behavior should not be modified. Thanks for letting me know!

**Comment by RobFog** [comment]
Should an in-house design person look over the colours, @Tantacrul?

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/362222
