### ISSUE TITLE
No option to close show paths and show profiler window.

### ISSUE THREAD

**Issue by Tejkh1** [musescore/MuseScore#16702]
### Issue type

Choose option...

### Bug description

No option to close show paths and show profiler window.
by pressing  esc we can close the  opened window.

### Steps to reproduce

1) open any score
2) click on diagnostic
3) click system
4)open show paths 
5)show profiler

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

WIindows 11

**Comment by cbjeukendrup** [comment]
I guess this might be because those windows are too tall for the screen, and apparently the Windows OS does not automatically position windows in such way that at least their title bar is on-screen. (On macOS, windows are prevented automatically from going off the screen.)

Anyway, since this just concerns the dev tools and thus doesn't really affect users, this is not an urgent issue.

**Comment by DmitryArefiev** [comment]
Fixed in #16720
