### ISSUE TITLE
[FEATURE] Improve usability of guitar capo settings

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16803]
This feature will enable capo settings to be applied and configured via a new palette element which, when applied to the score, will trigger a new contextual popup widget containing these settings: 

![Image](https://user-images.githubusercontent.com/86290556/234057107-94d3d22c-e4cc-405b-a03c-1143020fe646.png)

N.B. There are a range of bugs related to guitar capo performance that should also be addressed as part of the overall "improvement" of guitar capo settings, including:

- [ ]  https://github.com/musescore/MuseScore/issues/14937
- [ ]  https://github.com/musescore/MuseScore/issues/13361
- [ ]  https://github.com/musescore/MuseScore/issues/11631 

A full design specification has been sent to the development team. 

FYI:
@oktophonie 
@alexpavlov96 
@abariska

**Comment by scorster** [comment]
Appreciation and comments about the new capo element and partial capo functionality:

https://musescore.org/en/node/353203

scorster

**Comment by scorster** [comment]
Currently I'm creating a lot of partial capo arrangements, for configurations like 022222, 022200, 002220, 024442 — Note that this "numbered list" nomenclature describes the "capo fret positions" from the lowest pitched string to the highest string.

Sadly, since version 4.1 MuseScore doesn't allow capo-relative fret numbering on uncapoed strings. So I only have the option of hearing the wrong pitch (or writing the wrong fret to hear the right pitch would make the tablature notation unreadable—so that's not an option. 

https://musescore.org/en/node/353203#comment-1320280

I hope there's some interest in investigating **capo-relative fret numbering** a developing the solution. It's the right answer. But for those who want or need Nut relative, MuseScore could still provide that as well, as a setting in the capo popup.
