### ISSUE TITLE
Musescore 4 : Capo Playback with Tablature vs. Chord Symbols

### ISSUE THREAD

**Issue by kkslider9999** [musescore/MuseScore#16823]
I'm creating a score with tablature underneath a couple of vocal parts. The tablature also has chord symbols on it. When I put the capo setting on the tablature staff, it only changes the playback pitch of the chord symbols and not the pitch of the notes/fingerings on the tablature. Is there anything I can do to fix this/a workaround?

Thanks in advance!

**Comment by Tantacrul** [comment]
I'm going to remove the mention of a corruption because that is a separate problem. It would be great if you could upload that as another ticket. You can upload the score by changing the filename to **nameoffile.zip**. Then Github will let you upload it. Annoying workaround, I know.

Alternatively, link to the other place where you've provided the file to save us from having to search for it.

**Comment by Tantacrul** [comment]
@bkunda - is this related to the guitar work we're doing for 4.1? If so, we should probably add it.

**Comment by kkslider9999** [comment]
Got it! Here is the file:

[College Best Friends Forever - Guitar - Copy.zip](https://github.com/musescore/MuseScore/files/10973771/College.Best.Friends.Forever.-.Guitar.-.Copy.zip)

**Comment by rgreen5** [comment]
The issue of no capo playback of notes is already covered in #11631.

**Comment by kkslider9999** [comment]
Got it! So this is being fixed currently for 4.1 then yes? Is there an ETA on that release? Or, in the meantime, any workaround for the issue?

**Comment by bkunda** [comment]
Yes, we need to fix this as part of 4.1. 
I think the nature of the bug is adequately covered in #11631 – including mention of how it doesn't affect chord symbols – so will close this issue for now (unless it transpires that there is something extra we need to know in this issue, in which case we can always reopen it 🙂).
Many thanks for reporting this @kkslider9999!
