### ISSUE TITLE
Hairpin alignment can break even if dynamics are placed

### ISSUE THREAD

**Issue by Stccl** [musescore/MuseScore#16845]
### Issue type

Engraving bug

### Bug description

When placing a hairpin on each side of a dynamic marking, the alignment breaks if the right side is moved, either by dragging it or adding things on the staff that move its position.

### Steps to reproduce

- Place one hairpin on each side of a dynamic so that the three elements are linked;
- Try dragging the right hairpin, or adding something on the staff that lowers it

### Screenshots/Screen recordings

![VmJMfFibxJ](https://user-images.githubusercontent.com/50422710/225370049-bb67896f-2564-4ba3-b3e3-e910a58640fa.png)
![YjgQVofdkx](https://user-images.githubusercontent.com/50422710/225370080-87b1f7aa-d617-4fec-a083-a8c21d40ec57.png)
![ANvPdodFbd](https://user-images.githubusercontent.com/50422710/225370088-53270f1b-1e7a-49cf-b9e0-0cfa50cd3bf2.png)
![MuseScore4_qGuTFTep8K](https://user-images.githubusercontent.com/50422710/225373829-2b9458c9-33d3-4145-99c3-e97a87767494.gif)

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10 version 2009

### Additional context

The issue occurs with cresc. and dim. lines as well, and maybe more but I haven't tested further

**Comment by mike-spa** [comment]
I could also go ahead and just fix the immediate issue pointed out here, but I think this first needs some serious design input, because the whole feature is a bit of a mess currently, and I'd prefer not to risk adding more mess to it. Just to point out the things I personally find more painful (and time wasting):
- It is not always clear _when_ (as in, by which logic) dynamics and hairpins get locked together and when they don't.
- If they get locked by default, there is no way to unlock them (at least afaik) except disabling autoplace for one of the two.
- If they _don't_ get locked by default, there is way to lock them. 

In general, regarding the last two points: hairpin and dynamics being close to each other can't be the sole factor determining whether or not to lock their alignment. It's a sensible default, but the user should be allowed to change it case by case.
Finally:
- Hairpins and dynamics are by no means the only items that need to lock the horizontal alignment. Another obvious example is Tempo and Tempo change lines. In general, I believe it makes sense for this to be implemented as a general feature, applicable to different objects.

I'm sure I heard @Tantacrul and @bkunda talk about this feature before. I guess it's a good time to decide how to tackle and what to do with this!

**Comment by bkunda** [comment]
Yes this one definitely requires some careful design. Let's keep it on the 4.1 list for now, but I can't make any definite promises it will end up there (we can only try though!)

**Comment by MarcSabatella** [comment]
Definitely it would be great to have a more general solution.  Of course, there is already system-wide alignment for a number of element types, but that's probably not what is wanted here - should only affect elements that are "adjacent", however that is defined.

Meanwhile, though, one observation: you actually *can* unlock the alignment without disabling autoplace.  Do it by enabling the diagonal option for the hairpin.  Obviously, the whole point of diagonal hairpins is for situations where you don't want normal alignment, so that's why we disable the alignment for diagonal lines.  It just happens to also provide a convenient (but very non-obvious) workaround for other hairpins you don't want aligned.

**Comment by Tantacrul** [comment]
Agree with @bkunda - I think we need to create a new design for hairpins + dynamics as a whole.

- How the user can move more than one at a time (across multiple instruments)
- How the user can quickly change dynamics attached to a hairpin
- How dynamics + hairpins can be grouped across multiple instruments
- Rules for 'breaking' hairpins apart and rotating them

I definitely think this should be thought through properly first - before trying to make mini solutions we end up discarding.

**Comment by oktophonie** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/23046
