### ISSUE TITLE
Customised positions of beams which begin on a rest are not saved

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#16919]
### Issue type

Engraving bug

### Bug description

When the beam position is adjusted and saved, it goes back to the default placement after reopening the file.

### Steps to reproduce

1. Create a beam which begins on a rest
1. Move it up or down using the arrow keys (or by dragging, etc)
2. Save
3. Close MuseScore and reopen the file

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/120861729/226147333-463afb91-4d51-46ed-88c0-90d6d0af1ad2.png)

the right beam went back to default placement which could be too close to the rest

### MuseScore Version

4.0.2

### Regression

No.

**Comment by mike-spa** [comment]
As far as I can tell, this is already fixed in the latest master by #16602, so I'm going to close it (feel free to reopen in case I'm wrong).

**Comment by Jojo-Schmitz** [comment]
As per https://musescore.org/en/node/347983 it isn't fixed

**Comment by MarcSabatella** [comment]
I suspect the person in that thread was confused and using a 4.0.2 nightly.  For me it's definitely fixed in master, and indeed, you don't normally even need to adjust beams to avoid resets anymore.  But if you do perform manual adjustments, they are preserved across save/reload even when the rest starts the beam, in the examples I just tested.

**Comment by Jojo-Schmitz** [comment]
Possibler. I do have my serious doubts about the usefullness of 4.0.2 nigthlies...
