### ISSUE TITLE
[Instruments panel] Staves cannot be unhidden without first unhiding the associated instrument 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#17068]
### Issue type

Other type of issue

### Bug description

@bkunda  My expectation for this case is that the user is able to make visible in parts one (or more if available) of instrument staves, but it could be discussed if you don't agree.

@abariska my proposed solution is in the [comment below](https://github.com/musescore/MuseScore/issues/17068#issuecomment-1493335028).

Could be linked with https://github.com/musescore/MuseScore/issues/17066 and https://github.com/musescore/MuseScore/issues/17067

### Steps to reproduce

1. Open any score with 2+ instruments
2. Open a part
3. Make visible and invisible back one hidden instrument (if https://github.com/musescore/MuseScore/issues/17066 not fixed yet)
4. Expand the instrument drop-down
5. Try to make visible specific staves

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/101250347/228572815-43918737-2a37-49d1-85bc-4b975681d723.mp4

### MuseScore Version

MuseScore 4.0.2 

### Regression

No.

### Operating system

macOS 13

**Comment by bkunda** [comment]
I don't think this should be too complicated to fix. Just to be clear though, this is an issue with **Instruments** and **Staves**, not with _parts_ (i.e. part scores). 

(I will update the title and description accordingly).

The issue is that, if an instrument is hidden, the user is unable to make any of its staves visible without first making the instrument visible. 

I think a more predictable interaction would be that, if an instrument is hidden, clicking the 'eye' icon to make any of its staves visible should also make the instrument visible again. I.e.

<img width="1128" alt="Frame 1648" src="https://user-images.githubusercontent.com/86290556/229356133-23501d00-b0a0-4cc0-bf42-02a2b665e849.png">

**Comment by vashutangri** [comment]
Hey, I would like to try and solve this issue

**Comment by shoogle** [comment]
@vashutangri, sure, go ahead!

**Comment by abariska** [comment]
🟢 **FIXED**
