### ISSUE TITLE
Updating the website soundfont to musesounds

### ISSUE THREAD

**Issue by Captain-Quack** [musescore/MuseScore#17090]
### Your idea

Right now, the instruments on the website sound much worse than what's possible on the app. That means something sounding amazing when played on our computers might sound trashy after we've published it for everyone else to listen to. Can we get an update to the website SoundFont? 

### Problem to be solved

Making the website playback better.

### Additional context

The MuseHub app has some lovely-sounding instruments, maybe use those?

**Comment by DaddyLudwig** [comment]
If you go to File -> Publish to Musescore.com, it will upload the Muse Sounds audio if you have the score set to Muse Sounds. If you go to the site and click upload, it will give you the MS Basic audio. I found this out when uploading Mozart pieces for my Classical Music Library that I've wanted to do since 2012.

**Comment by Captain-Quack** [comment]
Thanks!
