### ISSUE TITLE
The preview for the page settings is gone 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#17160]
### Issue type

UI bug

### Bug description

In MU3 the page settings show a preview within the settings window:

![image](https://user-images.githubusercontent.com/78870770/230600702-07e519e3-d489-4aa7-a84b-fa7590adb306.png)

This overview, which I find very useful, is gone in MU4.

### Steps to reproduce

Open the page settings in MU4 and compare 
the content of the window with the page settings of MU3.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-230940304, revision: github-musescore-musescore-abb91a4

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

**Comment by bkunda** [comment]
I'm going to guess this was removed because the entire score now responds immediately when page settings are changed (so instead of seeing a detached "preview" in a different dialog, you see the effects on your score straight away). 

This is a pattern we want to increasingly move towards (i.e. interacting more directly with the score, rather than relying on indirect dialog actions), and the functionality in the old dialogs will gradually get moved into move obvious places in and around the score to make this kind of interaction even more practical. With this in mind, I don't think we will be reintroducing this feature.

**Comment by oMrSmith** [comment]
Ok, I get your point. I found this especially helpful to preview, how many pages you'll end up...

**Comment by cbjeukendrup** [comment]
In the meantime you could maybe use the Navigator for that, or just zoom out :)

**Comment by oMrSmith** [comment]
Actually: If you change the scaling in the page settings in MU4, changes don't become visable until you hit OK, do they?

**Comment by oMrSmith** [comment]
Ah, I see: You have to click outside the field as it seems.

**Comment by bkunda** [comment]
@oMrSmith 

https://user-images.githubusercontent.com/86290556/230773624-06587c3a-9f0c-43d0-a319-ff8827722177.mov

**Comment by oMrSmith** [comment]
Thanks for that I'll make a video, how that works for me on windows.
Only problem I have is that the recent nightly builds no longer start the application
so I'm looking for an older one...

**Comment by oMrSmith** [comment]
![image](https://user-images.githubusercontent.com/78870770/230775020-cbcb0b28-9771-426d-bc4a-b8ec9f876be2.png)
If I take this Master build - maybe I shouldn't take master builds? - it doesn't seem to work as expected:

https://user-images.githubusercontent.com/78870770/230774953-e9bd7a6e-e23e-4924-a624-aec49b9e5ec2.mp4

Whereas if I take

![image](https://user-images.githubusercontent.com/78870770/230775052-64b6e97c-7688-4f54-a801-adcb318215f2.png)
It works like in your video.
