### ISSUE TITLE
32nd (demisemiquaver) grace notes do not play properly

### ISSUE THREAD

**Issue by toewl-dev** [musescore/MuseScore#17169]
### Issue type

General playback bug

### Bug description

32nd grace notes play for the duration of half of the note value they are applied to. Instead of 1/32nd of the expected tempo.

### Steps to reproduce

1. Create a blank score
2. Add any note on the score
3. add a 32nd grace notes underneath "Grace Notes" in palettes
4. Playback is bugged.

### MuseScore Version

MuseScore 4.0.0

### Regression

I don't know

### Operating system

Windows 10

### Additional context

[32nd_graces.zip](https://github.com/musescore/MuseScore/files/11182005/32nd_graces.zip)

**Comment by MarcSabatella** [comment]
This is currently by design - if you add an appoggiatura (without slash) instead of an acciaccatura (with slash), it's correct according to standard Baroque/Classical interpretation that they take half the value of the main note.  What you want is an acciaccatura - the one with the slash.

Eventually it is hoped to provide additional controls over this, and to perhaps adjust the defaults to make this confusion less of an issue.

**Comment by toewl-dev** [comment]
I see, thank you very much for the clarification.
