### ISSUE TITLE
Error log completely filled hard disk

### ISSUE THREAD

**Issue by EMailly** [musescore/MuseScore#17180]
The error log within the MuseScore App continued to accumulate data after each of the many crashes that I experienced until it (literally) filled up my hard drive. The lack of space on the hard drive caused the program to behave erratically -- like being unable to adjust the score properties -- creating further error log files.  This sequence repeatedly endlessly until everything stopped working.

Out of a half terabyte storage environment, I had less than 5% space available. Everything except program files are stored to the Cloud, so the fill was 100% attributed to the applications/programs resident on the computer.  

I don't know what is included in the error logs, but whatever it is, it is a huge storage drain on the system.  It was a hidden file on the system but the tech support person at Geek Squad found the file (just labeled MuseScore something) and removed the file.  The computer went back to having 95% storage available.)

**Comment by Jojo-Schmitz** [comment]
I guess it wasn't jist one log file, MuseScore creates one ber session as far as I can tell.
And them filling some 90% or a 500GB disk is also quite unusual.

Still those log files should better not collect, but rather just recycle the files, overwrite a set of existing ones. Logs from last week/month/year are not really worth being kept, or are they?
Or there should be option to a) remove them and/or b) disable them entirely and/or c) move them to a place where they can more easily be found and cleaned up, ideally in a automated fashion. Other than via a factory reset that is.
Same goes with autosave fails BTW, those too can collect space and are not very interesting anymore after a week or so.

**Comment by Jojo-Schmitz** [comment]
Oh, it wasn't just a missing feature but a downright bug! Good to see it fixed.

**Comment by warptengood** [comment]
I am sorry to re-open this issue. But I have stumbled upon rather unusual situation. 

It is awesome, that logs older than 7 days are deleted, BUT, not when you can accumulate 300-400GB worth of log files within  a few days. 

Recently I was using MS to process the huge dataset of mxl files. I ran MS using python's `subprocess` and converted files. Obviously, some of them fail for different reasons (I did not set the flag `-f`), which created error logs. I utilized 32 workers using `multiprocessing` to convert files on 32 CPU cores in parallel. 

Well today I noticed that my script stopped since I don't have space in my disk. 

I understand that this is rather an edge case, and thus is not worth to add an additional "observer" to the logs folder to prune it if it exceeds certain threshold in memory. I have written such check function as a part of my python script, and I am sure anyone who will face such a problem could do it without any issue. 

Just wanted to share if someone is interested, or so that devs could know it just in case.
