### ISSUE TITLE
Crash after deleting several instruments (one score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17387]
### Issue type

Crash or freeze

### Steps to reproduce

1. Open [Smoke Test 8a.zip](https://github.com/musescore/MuseScore/files/11353909/Smoke.Test.8a.zip)
2. Press **I** to open Add or remove instruments dialog
3. Delete **Contrabasses** and **Violonchellos** and click OK

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/90187801/235160774-d3cd8844-b9c7-4acb-90a5-71d2b6cb6280.mp4

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of **MuseScore 4.0.2**

### Operating system

Windows 10

**Comment by DmitryArefiev** [comment]
Can't recreate from scratch for now

**Comment by cbjeukendrup** [comment]
I've also seen this crash a few times. One way to reproduce it is very simple: just create a score from the Symphony Orchestra template, and then delete the Bass Drum using the Add/Remove Instruments dialog.

`git bisect` indicates that this was caused by commit 117e457ea09c4ead1a81479c7f37d5eb5ec5e8ee. Somehow, this causes the method `MasterScore::removeDeletedMidiMapping()` to malfunction; the InstrChannel is correctly moved within the `_midiMapping` vector, but the channels of the `InstrChannels` of the `part->instrument()` are not updated, which causes the crash later in `MasterScore::updateMidiMapping()`, because of reading out of bounds. 

That's all I know so far. I don't quite see why this is the case, and can't spot any mistakes in `TRead::read(InstrChannel*, …)` nor `TWrite::write(InstrChannel*, …)` either. @igorkorsukov Could you maybe also take a look? Maybe you do see what's wrong...

**Comment by cbjeukendrup** [comment]
I found the problem, is was really quite subtle :)
https://github.com/musescore/MuseScore/pull/17405

**Comment by DmitryArefiev** [comment]
Fixed in #17405
