### ISSUE TITLE
Crash on loading a specific score

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#17404]
### Issue type

Crash or freeze

### Bug description

Loading the attache file works in 4.0.2 and did work in previous development builds, but doesn't anymore
[Children_of_God.zip](https://github.com/musescore/MuseScore/files/11359128/Children_of_God.zip)

### Steps to reproduce

Just load the attached score, and observe the crash

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.1.0, revision: ebe0372

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
Seems to be caused by #17001. The `delete` that is performed when replacing old `Text` elements with the new `Expression` element seems to cause problems with linked elements in part scores.

**Comment by cbjeukendrup** [comment]
Also, I'm afraid that doing this while reading the score is going to cause trouble anyway, because the text style property is not synced between parts. So in the full score, the text style might be `Expression`, while in a part score, it might theoretically be something different, if I'm not mistaken. It's a bit worrying to think about what would happen in that case...

So I think we'll need to use an approach similar to `CompatUtils::replaceStaffTextWithPlayTechniqueAnnotation`.

**Comment by Jojo-Schmitz** [comment]
I take you noticed yourself, but I should have mentioned from the start the score here originally stems from Mu3 and had been imported to Mu4 and adjusted.

**Comment by mike-spa** [comment]
@cbjeukendrup let me know if you've found a solution for this, otherwise I'll look into it as soon as I can. Also thanks for pointing out the play technique thing

**Comment by cbjeukendrup** [comment]
I'm not actively working on this, so feel free to take it! My guess is that the best way is to look at the item in the MasterScore (_after_ all part scores have been read), replace that item; then loop through the list of linked items of the old item, and replace all linked items with a `linkedClone` of the new item.
