### ISSUE TITLE
MuseScore can't support VST only plugins

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#17441]
So I've installed a plugin called "VirtualSoundStage 2.0 Demo". I thought it would be usable for creating better room panning for the Muse Sounds presets. But apparently, I looked at the requirements info on the website, and it only supports VST and AAX plugin formats, and it of course doesn't have a VST3 version.

Is there possibly a way that MuseScore 4 can support VST only versions of plugins like this? Cause I really don't want to export every single individual part one at a time in audio format and import the files into a DAW software like GarageBand and Reaper that supports VST only plugins. That'll take too long.

**Comment by cbjeukendrup** [comment]
I take that with "VST only" you mean "VST***2*** only".

MuseScore won't support VST2 plugins. Steinberg is not giving licenses for it anymore, because it is deprecated. The developers of the plugin will need to update it. (Or it might be possible to use a third-party adapter VST3 plugin, so that you can load VST2 plugins inside that VST3 plugin... but I don't know about that.)

(One tip regarding exporting in audio files: in the "Export" dialog, it should be possible to select all individual parts at once, so that you can get audio files for each individual part in one action.)
