### ISSUE TITLE
System texts do not appear in parts or PDF export

### ISSUE THREAD

**Issue by hirunatan** [musescore/MuseScore#17455]
### Issue type

Other type of issue

### Bug description

Hello. I've a score with some staff texts and some system texts. When I export it to parts or to PDF files, I see that the staff texts correctly appear in the corresponding part. But system text only appear in the complete PDF, not in any of the parts. According to the documentation, they should be in all of them, don't they?

Also I have some jumps. I see that the segno and coda symbols, and the "D.S. al Coda" text appear in all parts, but the "To Coda" text also shows only in the complete score, not in parts. I don't know if it's the same problem.

Any clue of how to do it? Thanks.

I have 4.0.2 github version, but the problem has been reproduced in Windows with 4.0.2.

### Steps to reproduce

1. Open attached score.
2. Open all parts.
3. At the first measure there is a staff text "(guitarras no entran...". It shows in the "Voz" part, but not in the others. This is ok.
4. At the measure 38 there is a system text "(segunda vuelta...". It should show in all parts, but does not appear in any of them.
5. Same thing occurs with "Al Coda" text in measure 33.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: dbe7c6d

### Regression

I don't know

### Operating system

Windows 10 and Arch Linux

### Additional context

[Bug-score.zip](https://github.com/musescore/MuseScore/files/11390165/Bug-score.zip)

**Comment by bkunda** [comment]
Hi @hirunatan;
I'm not quite sure how you created these text elements, but all I did was delete and re-add them and they seem to be working fine.
See these example:  
[Memoria de una noche-rem.zip](https://github.com/musescore/MuseScore/files/11420603/Memoria.de.una.noche-rem.zip)
(Note I only fixed the stave text element at m.38 in this file, but I have since been able to correct the "to coda" element as well by deleting and re-adding it.
It certainly seems to be an issue with this specific score as I am unable to reproduce this on other scores.
