### ISSUE TITLE
Figured bass continuation lines don't create with Ctr/Cmd+number shortcut

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17552]
### Steps to reproduce

1. Create a figured bass
2. Type _ (underscore) after number 
3. Press Ctr+5 several times - **continuation line are missing** (see video)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/07daf5da-ebf0-4f47-88a1-b0a1437fc367

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Comment by MarcSabatella** [comment]
I've never fully understood how figured bass entry works, but one thing I see is that Ctrl+7 works to set the duration directly, but Ctrl+5 four times does not, whereas it did in 3.x.  So, you can only set durations that correspond directly to note values (eg, quarter or half), not things like dotted half or half plus eighth.

I took a look at the code - the main functions involved are NotationInteraction::navigateToFiguredBass(const Fraction& ticks) and FiguredBass::addFiguredBassToSegment(Segment* seg, track_idx_t track, const Fraction& extTicks, bool* pNew).  I don't see anything obviously off just from looking but presumably someone with access to a debugger could step through and see where things are going wrong.

My best guess is that the first press of Ctr+5 is working correctly but when you hit Ctrl+5 for the second time, the code that looks backward for a figured bass element to extend is finding the empty one you just left whereas previously that was cleaned up sooner.  But that's just a guess, because I'm not seeing anything else obvious that could be going wrong.

**Comment by MarcSabatella** [comment]
This is the code where the previous FB element is *supposed* to be extended:

https://github.com/musescore/MuseScore/blob/24a7f7b58e02e755b817a4c6d6251df126b540c8/src/engraving/libmscore/figuredbass.cpp#L1174-L1195

**Comment by DmitryArefiev** [comment]
Fixed in #17605
