### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by alex81308** [musescore/MuseScore#17614]
### Issue type

Crash or freeze

### Bug description

In Muescore 4, when I open one of my scores, it crashes right after opening it. This has been happening for about 3 days now. I was informed by Jojo Schmitz that this is an OS issue.

### Steps to reproduce

I would say to open the file, but my computer is not showing the file and I cannot find it.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/133918682/b9fddf68-9447-4655-9c6d-e6e047e504c0

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
I assume you mean the file you attached in this forum thread - https://musescore.org/en/node/350002

I can't reproduce on Windows, but @Jojo-Schmitz can on Windows apparently.

**Comment by cbjeukendrup** [comment]
Looks like it's potentially Muse Sounds related. I'll have a look at some point.

**Comment by opExe** [comment]
It's another case of #16642.

**Comment by cbjeukendrup** [comment]
@opExe is right. I've reproduced it in the debugger and the stack trace is the same as in #16642. (Not sure if I can trust the Windows debugger, since the stack trace is pretty weird, but it is for sure caused by Muse Sounds.)
<img width="848" alt="Scherm­afbeelding 2023-05-18 om 22 49 48" src="https://github.com/musescore/MuseScore/assets/48658420/b410e545-5cfe-4c7f-9814-09007748bee0">
