### ISSUE TITLE
Crash message after closing musescore

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#17636]
### Issue type

Other type of issue

### Steps to reproduce

1. Open a file
2. Close musescore and exit

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

macOS 13.2.1

### Additional context

[MU4 Crash log.pdf](https://github.com/musescore/MuseScore/files/11510927/MU4.Crash.log.pdf)

**Comment by cbjeukendrup** [comment]
Does this happen _always_ and with _any_ score? Or with specific scores, or after specific actions?

And does it still happen in the Nightly Builds? https://musescore.org/en/nightly-builds

Otherwise, maybe https://github.com/musescore/MuseScore/pull/17249/commits/f037856f2e1bd49bdb250d364978aaa6dca6a753 fixes it, but that's not part of the nightly builds yet, so you can't test that yet.

**Comment by bkunda** [comment]
@amijaishalev does this happen when the mixer is open when you try to close MuseScore? (Or, put in another way, does the crash happen if the mixer is closed when you try to close the app)?

**Comment by amijaishalev** [comment]
Usually I have the mixer opened, but I will try with the mixer closed and let you know.

**Comment by amijaishalev** [comment]
So with the last nightly it hasn't been happening....
