### ISSUE TITLE
System breaks are  reset when adding new time signature

### ISSUE THREAD

**Issue by MuseScoreBugger** [musescore/MuseScore#17724]
### Issue type

Engraving bug

### Bug description

When adding a new time signature, previously made system breaks (manual and automated) that occur after the new time signature are deleted.

### Steps to reproduce

1. Create new score
2.  Format -> Add system breaks  -> break systems every 4 measures
3.  Select any note/rest
4. Click on a new time signature

### MuseScore Version

4.0.1

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
That is by design and has been that way ever since.
Explicit system breaks don't make any sense anymore after a time signature change, unless it is a 'compatible' one, i.e. mathmatically identical, e.g. 4/4 and 2/2. If not, there may now fit more or less measures unto a system, and also the barlines, which is where the breakes are attachetd to are not gone and recreated at a different spot

**Comment by MuseScoreBugger** [comment]
Ok, that makes sense thanks!
