### ISSUE TITLE
Position relative to barline for clef disabled when opening in musescore 4.1.0 nightly

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#17747]
### Issue type

Engraving bug

### Bug description

Save score with clef change in musescore 4.0.2 (official release):

https://github.com/musescore/MuseScore/assets/919446/baaf61c3-a17c-42b1-8f56-5424b123bc5c

If I open it in 4.1.0 nightly, position relative to barline is disabled. Also clef looks larger:
![musescore4 1 0_open_clef_bug](https://github.com/musescore/MuseScore/assets/919446/4b87e07b-9584-4dbd-b299-4b071684dfdd)
And I can change its size using Cue size checkbox (I don't know if it is correct behavior)

### Steps to reproduce

1. Create new score in Musescrore 4.0.2.
2. Select rest (it's important, so clef will be added after barline) and add new clef
3. Save file
4. Open file with 4.1.0 nightly
5. Select clef, you can't change its "position relative to barline" in properties.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231462149, revision: github-musescore-musescore-2be9061

### Regression

I don't know

### Operating system

Windows 10 Version 2009

**Comment by mike-spa** [comment]
**Short answer** 
Unfortunately, this is not a 4.1 issue, but a legacy issue (i.e. one that originates from errors done in 4.0 and earlier versions) and I think it is impossible to back-solve it. Also, it is not a regression of 4.1 VS 4.0, so I think it should be closed.

**Long answer**
Here's what's going on. Musescore treats clefs in two separate ways: _header_ clefs, and _non-header_ (or mid-system) clefs. The two are completely different, and have completely different layout rules. Most visibly: header clefs are full-sized, whereas mid-system clefs are small. The problem described in this issue arises because, when saving the file, Musescore does _not_ write whether the clef is a header or not: it just writes a clef. Upon reopening the file, the header/non-header property is deduced from context. 

This is just one example of why that's a _very_ bad idea. A clef that's found at the very beginning of a measure is deduced to be a header, and that's true in the vast majority of cases, but not in _this_ case. When that file was saved in 4.0.2, the header/non-header property was not written, and when reading it back, Musescore interprets that as a header clef (you can see this also in 4.0.2 because, as you reopen the same file, the clef looks bigger). And for header clefs, the new "Position relative to barline" property does not apply (and it shouldn't, cause it makes no sense), hence why it is disabled. The information that that clef is a non-header is simply lost: I can't think of any way that we look at that clef when reding the file and reliably deduce that it is a non-header. 

Of course, starting from 4.1, we simply tag the clef as header in the file, so the problem doesn't arise anymore. But in older files, I'm afraid that that information is just lost. (And, to stress this point again: it isn't lost because of the 4.0 -> 4.1 translation. It was lost in the 4.0 file itself.)

**Comment by mercuree** [comment]
@mike-spa Thanks for your detailed explanation. 
Is there a way (option, checkbox, etc) to change clef type from header to non-header? I understand that removing incorrectly treated clef and adding new one will fix it in 4.1.0, but can it be done easier?
This is also relevant to all musescore 3 files.
