### ISSUE TITLE
Instrument Rename Consistency

### ISSUE THREAD

**Issue by Aurigon81** [musescore/MuseScore#17756]
I've renamed a few parts in the rock band template, but they only show in the opening system, with blank spaces through the rest of the score.  I can't seem to figure out how to fill in those empty parts with the new instrument names throughout the rest.  Has anyone come across/know how to correct it?

**Comment by cbjeukendrup** [comment]
For support-related questions, which this seems to be, please use the support forum on MuseScore.org: https://musescore.org/en/forum/6

Once you are certain that you have encountered a bug, feel free to open a new issue, and when doing that, make sure to fill in all the necessary details in the "Bug report" form, so that we have enough information to fix it.

(Sorry for not being super helpful here right now, but GitHub is really the place of the developers rather than of the support specialists, and the developers are very busy and already have a huge amount of issues to deal with here 🙂)
