### ISSUE TITLE
User should have ability to add a second interval trill with displayed auxiliary note too

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17776]
### Issue type

Engraving bug

### Bug description

![Capture](https://github.com/musescore/MuseScore/assets/90187801/f471f8c3-583b-46ca-a719-2b4b0a1e49b1)

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/90187801/9ee291ce-6335-4130-b12a-d8905f763a2a

### MuseScore Version

4.1

### Regression

No.

### Operating system

Windows10

**Comment by Dima12357** [comment]
I support this request. Since the accidental above the trill sign is not very convenient to read, and the best notation is to indicate the interval with a cue-sized note. I suggest setting this notation as the default. 
I suggest adding all other notation options to the style of the score and leaving it for use at the discretion of the user.
I also suggest adding the option to mark the interval with an accidental located as a superscript character after the trill sign.
![Снимок экрана (203)](https://github.com/musescore/MuseScore/assets/134041121/a11bce54-eceb-4393-adc0-7278199ce4e6)
 I propose to redo the currently existing notation in Musescore when using the second interval a little, making the accidental bold and bringing it closer to the trill sign.
![Снимок экрана (204)](https://github.com/musescore/MuseScore/assets/134041121/3adc80db-ce91-4d7c-87ba-fe2f7e3508d0)
