### ISSUE TITLE
[MU4 Task] Give user a strong recommendation to update MuseSampler version (update MuseSounds via MuseHub) after MuseScore 4.1 is release

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17889]
### Task description

In **MuseScore 4.1** we updated **Reverb** effect.
 
If user has an old version of **MuseSampler** (0.3.2), he will get a combination of old reverb and new reverb when he play score with MuseSounds. That means:

1. It will be more wet signal
2. It will be higher db level and he can get clipping

Actually, the difference is not so big (noticeable on good equipment)
You can compare:

[starwars_orch_old rever.zip](https://github.com/musescore/MuseScore/files/11676373/starwars_orch_old.rever.zip)
[starwars_orch_old+NEW rever.zip](https://github.com/musescore/MuseScore/files/11676375/starwars_orch_old%2BNEW.rever.zip)

### MuseScore Version

4.1

**Comment by cbjeukendrup** [comment]
What's "difficult" about this, is that the user does not know about the existence of MuseSampler, because we have kept that hidden. The user only knows that there are several Muse Sounds sound packs, but not that there is also a MuseSampler executable that's necessary to actually use those sounds. This is installed silently along with the Muse Sounds packs, and the user will never see any reference to it (except in some hidden places like the Diagnostic menu).

**Comment by DmitryArefiev** [comment]
Yes, we can only strongly recommend check MuseHub updates.

> and the user will never see any reference to it (except in some hidden places like the Diagnostic menu)

Actually, he can check Muse Sampler Libray version in Diagnostic>MuseSampler>Check MuseSampler

It's not hidden in release version

https://github.com/musescore/MuseScore/assets/90187801/1ae0467d-68f2-4450-8260-f606bd7e2c9d

User just needs to make sure the version is 0.4.x

**Comment by bkunda** [comment]
I am working with @davidwhearn and @iamtesch on a solution to this problem, which is that the Hub will be released in beta mode with the new version of musesampler (0.4.0) in time for us to announce testing to the community. 
We will need to be clear in our announcement messaging about the user needing to open Muse Hub before they open the any test builds. 
This means we won't need to resort to any in-app prompting to manually update the musesampler. 
I'll therefore close this issue now, and we can re-open if something in this plan changes.

**Comment by iamtesch** [comment]
The plan here was to detect the version of musesampler via the library helper functions.  You cannot just use the new functions on an older musesampler binary, because they don't exist.  So you should check the version of musesampler, and disable the internal reverb, get reverb level, and add external reverb if higher than 0.4.0.

**Comment by iamtesch** [comment]
I just looked through the source, and this should not be an issue.  Here is why:

**0.3.1 MuseSampler**
MuseScore 4.1:
- The wrapper will not find the "get reverb level" function, and therefore the `MuseSamplerResolver::defaultReverbLevel` function will return "0" for the level of reverb to be applied by MuseScore.  MuseSampler will continue to apply internal reverb.
MuseScore 4.0:
- MuseScore will not apply reverb, MuseSampler will continue to apply internal reverb.

**0.4.0 MuseSampler**
MuseScore 4.1:
- When the `init` function is called, it calls "disable_reverb" on the wrapper, turning off MuseSampler internal reverb
MuseScore 4.0:
- MuseScore will not apply reverb, MuseSampler will continue to apply internal reverb because "disable reverb" is not called.

Therefore, if there is a difference here, it might point to a different issue or an issue with the reverb implementation...

Additionally, I'll note that the new MuseSampler should download automatically, so I don't think a strong recommendation needs to be shown to the user.
