### ISSUE TITLE
Feature request: dynamics and hairpins should automatically go above vocal staves

### ISSUE THREAD

**Issue by nweininger** [musescore/MuseScore#17883]
Transferring a very old feature request here from: https://musescore.org/en/comment/1193294#comment-1193294

Still a major issue for large scores containing both vocal and instrumental staves, where no one default placement is right for all instruments.

**Comment by MarcSabatella** [comment]
The problem is that this setting is score-wide.  The request here is to make it staff -specific.  So that mixed instrumental/vocal scores can have correct dynamic placement by default.  Which absolutely makes sense to me.  The hard part is figuring out which *other* style settings are worth making staff-specific and how to design the UI for that.

**Comment by nweininger** [comment]
FWIW, for a minimal UI option, I think having the dynamics position dropdown in Format -> Style -> Dynamics have an "Auto" setting along with "Above" and "Below", where in "Auto" mode MuseScore just selects a position for each staff based on the type of instrument, would satisfy most choral-orchestral composers.

It's a good question whether other style settings should be staff specific. I will take a personal TODO to read through Elaine Gould's "Behind Bars" to see if she has other instructions about instrument-specific positioning of elements that aren't already implemented. IMO adhering to the recommendations in Gould's book for each type of classical instrument is a reasonable default, since that book is regarded as something of an authority on best practices for classical music engraving (of course, non-classical composers may have a different perspective).
