### ISSUE TITLE
Pedal symbols render from Leland when using Finale Maestro music font

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#17885]
### Issue type

Engraving bug

### Bug description

The keyboard pedal symbols (Ped. and *) use Leland instead of Finale Maestro. No other fonts (including Finale Broadway) have this issue.

### Steps to reproduce

1. Create a new score
2. Add a pedal marking, make note of how it looks
3. In the style window, set the musical symbols font to Finale Maestro
4. No change

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Some images to confirm, Bravura:
![Ped-Bravura](https://github.com/musescore/MuseScore/assets/1786669/3ce6267c-ec4b-45ca-9c4a-ed97fd683a68)
Leland:
![Ped-Leland](https://github.com/musescore/MuseScore/assets/1786669/71b0d296-8ee6-4490-8a8e-30a279b457d3)
Finale Maestro:
![Ped-Maestro](https://github.com/musescore/MuseScore/assets/1786669/bd7c5362-2853-4c3f-9a8b-9bde8ef61794)

**Comment by Jojo-Schmitz** [comment]
But that seems by design, seems Maestro Text (!) doesn't have that glyph so falls back to Leland Text:
```cpp
        fontProvider->insertSubstitution(u"Finale Maestro Text", u"Leland Text");
```
That in turn would fall back to Bravura Text for missing glyphs, but doesn't need to here.

For the Musical Fonts though (those without "Text" in the name) the fallback is always Bravura, apparently.
Seems inconsistent to me, but is a different issue

**Comment by oktophonie** [comment]
The task/fix here is to change pedal lines to use the Musical Font, not the Musical Text Font (just as with ottavas).
