### ISSUE TITLE
Layout changes when open 4.0.2 score in 4.1 (one score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17916]
### Issue type

Engraving bug

### Steps to reproduce

1. Open [Estudo no. 1 - Piano.zip](https://github.com/musescore/MuseScore/files/11707352/Estudo.no.1.-.Piano.zip) in **4.0.2**
2. Open [Estudo no. 1 - Piano.zip](https://github.com/musescore/MuseScore/files/11707354/Estudo.no.1.-.Piano.zip) in **4.1 master**
3. Compare layout 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/a6bc28ca-23c0-4443-9152-3b975a78451d

### MuseScore Version

4.1 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

**Comment by oktophonie** [comment]
I get the one-page layout in 4.0.2 and in 4.1; I think it's because we're getting different substitutions for e.g. the tuplet number font and in my case they nest together:
![image](https://github.com/musescore/MuseScore/assets/20604032/c1a54809-4f7d-4966-a6d7-b3a586217709)
(not ideal either, but there it is).

In any case, I don't see this as a bug; the one-page layout is likely borderline and spills over to two because of some slight difference. The fact that (for whatever reason) 4.1 allows _more_ in the page is, if anything, a bonus!

**Comment by DmitryArefiev** [comment]
OK! let's close it for now
