### ISSUE TITLE
Make all drum kits available to the user (not just the standard); allow to be added from New Score Wizard?

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#17927]
### Your idea

MS3 had a range of drum kits; MS4 only has one in MS Basic. This is especially irksome when you are updating pieces from MS3 to MS4 which used a brush drumset. It is especially important to retain the kick /snare / hihat sounds. At the same time the average user should not have to spend time searching for alternative kits on the Internet.

So is it possible to include a few extra kits in MS Basic with alternative snare sounds and a separate brush set?

**Comment by MarcSabatella** [comment]
MS basic does include the brush kits still, you just can’t access them yet because the mixer UI does not yet support selecting individual sounds.  Hopefully then that is finally implemented it will include access to the alternative drum kits.  Meanwhile see the separate files I provide in https://community.masteringmusescore.com/c/resources/ms-basic-individual-sounds that allow you to use the brush kit today.

**Comment by rgreen5** [comment]
All the drum kits are present in the MS Basic soundfont; the problem is that they cannot be accessed. Surely a simple solution is to allow the user to choose from a range of drum kits (Std, Room, Jazz etc.) from a list presented in the New Score Wizard "Choose instruments section" – rather than being restricted to one standard kit.

**Comment by MarcSabatella** [comment]
Presumably this will be covered by the design being implemented for https://github.com/musescore/MuseScore/issues/17233

**Comment by rgreen5** [comment]
> Presumably this will be covered by the design being implemented for #17233

So OK to close thread?

**Comment by zacjansheski** [comment]
Closed by https://github.com/musescore/MuseScore/pull/18976
