### ISSUE TITLE
Search / navigate fonts list by pressing a letter key

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17971]
### Issue type

UI bug

### Bug description

In MuseScore 3.6, when the font selection dropdown menu is open, you could go directly to the fonts starting with letter M by pressing "M"

In MuseScore 4 it takes much longer to find desired fonts as you have to scroll through a long list.

Marc mentioned this (more-or-less) functioned in 4, but I did not see that in any of the versions.
https://github.com/musescore/MuseScore/issues/10460

### Steps to reproduce

1. Select text
2. Open the fonts dropdown menu
3. Press Z to attempt to get to the end, or M for MuseJazz (multimeasure rests are created) or A to go to the beginning of the list (a note might be made)

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231640302, revision: github-musescore-musescore-d9e8f71

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

All

**Comment by MarcSabatella** [comment]
I believe I was referring to using the cursor keys to navigate within controls, not letter keys.  So that if I open the font list, I can use up/down keys to select a font (now; I couldn't when the issue was originally filed).  But as far as I know typing a letter has never worked in MU4 - only MU3.

This however, is reported separately in https://github.com/musescore/MuseScore/issues/16508

**Comment by zacjansheski** [comment]
Thank you.  Closing as dupe of https://github.com/musescore/MuseScore/issues/16508
