### ISSUE TITLE
Unable to create Volta line on multiple staves holding Ctr/Cmd

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18048]
### Issue type

Other type of issue

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/90187801/ac63ab6a-c018-4f65-9d93-0b2d52db41b1

### MuseScore Version

4.1 nightly master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Comment by MarcSabatella** [comment]
Ctrl+click is meant to be the way to override the normal application of system-level elements - it's how to create local (staff-specific) key or time signatures, for instance.  Also barlines.  These all still work in MU4, so I'm not sure it makes sense from a UI perspective to have voltas work differently.

Meanwhile, it appears that Ctrl+drag does still work to create staff-specific voltas.  But it's not ideal since it requires use of a mouse and thus is not accessible to all users.

Of course, Ctrl+click isn't the most discoverable interaction either, and it seems it is not working correctly via keyboard either (neither Ctrl+Enter or Ctrl+Space actually apply the selected palette item).  So that's perhaps a bigger issue to address as part of this.
