### ISSUE TITLE
Can't connect to musescore.com/audio.com on Linux using beta build (or latest master builds)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18120]
### Bug description

Using https://github.com/musescore/MuseScore/actions/runs/5345606550 I can't access to **My online scores** or to **Publish** score.

The problem is with sign in to **musescore.com** or to **audio.com**. 
Web browser shows successful sign in but MuseScore beta build remains in not signed in state

(**nightly master build of June 22** and **4.0.2 work fine**)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/075699bf-f4ea-42f5-9f72-3cf782e216a0

### MuseScore Version

4.1 testing mode build

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux Ubuntu 22.04
Linux Mint 21

**Comment by DmitryArefiev** [comment]
Log file from Ubuntu 22.04.2 LTS 
[MuseScore_230623_104222.log](https://github.com/musescore/MuseScore/files/11846013/MuseScore_230623_104222.log)

**Comment by cbjeukendrup** [comment]
The log file suggests that Qt cannot load the OpenSSL library. As far as I can see, on Linux, we use the OpenSSL from the system. So I've looked at recent changes in GitHub Actions, and there was an Ubuntu update 3 days ago: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230619.1 but that doesn't mention any changes in OpenSSL.

@DmitryArefiev do you know on which date when this regression was introduced?

**Comment by DmitryArefiev** [comment]
@cbjeukendrup 
It **works** in nightly master from June 22 
and **doesn't work** in beta build created on June 22 afternoon 
and **doesn't work** in nightly master from June 23

**Comment by DmitryArefiev** [comment]
I've installed now Ubuntu updates and still has the issue

**Comment by DmitryArefiev** [comment]
@MarcSabatella Can you check if this happens on your Linux machine too please?

**Comment by MarcSabatella** [comment]
I have no problems logging into musescore.com or audio.com using the most recent 4.1 nightly build (the one from June 21 - the builds after that are master/4.2).  The first master/4.2 also works fine for me with login.  I can't test the latest master because it no longer starts - I get versions errors with GLIB_C and GLIB_CXX in crashpad_handler.

I'm happy to test a "beta" build if one exists that is different from these, but I'm not sure which to use, as apparently there is not an updated one for Linux yet.

I tried the one from https://github.com/musescore/MuseScore/actions/runs/5345606550 but I can't start it either, same GLIB errors and a hang on the splash screen as current master.

So I'm kind of guessing whatever is going with the SSL library is the same reason I can't run it at all - a change to the build environment.

**Comment by Tralen** [comment]
Hello,

I can't confirm the issue on Mint 21 Vanessa with the nightly builds I have.

My previous nightly version 4.1.0-231710304 is able to login normally to musescore.com, and the current version 4.2.0-231740316 is able to login as well. The version linked by @MarcSabatella 4.1.0-231731237 was also able to login.

My system wasn't updated since 2 months ago, so I then updated the system, restarted the machine, and all versions were still able to logout and login properly.

**Comment by DmitryArefiev** [comment]
> So I'm kind of guessing whatever is going with the SSL library is the same reason I can't run it at all - a change to the build environment.

@MarcSabatella Yes, it's probably similar. The issue with login started on June 22 and still persists (tried latest master and 4.1 build).  

Thanks for testing!

**Comment by DmitryArefiev** [comment]
@Tralen Thanks for testing! I'm trying **Chrome** (had some problems with chromium setup) on LinuxMint but still have the problem

**Comment by cbjeukendrup** [comment]
Here's an experiment: https://github.com/musescore/MuseScore/actions/runs/5364399778

It is quite likely that this will fix the startup problem for @MarcSabatella. If it also fixes the login problems, I would be surprised, but we can try; so far, I wouldn't know what else could cause this.

**Comment by MarcSabatella** [comment]
Thanks, for me it works perfectly, it starts up and I can log in.  Not that I was having logging problems before, but I guess I might have in the builds from the last few days, had I been able to start up at all.

**Comment by DmitryArefiev** [comment]
> Here's an experiment: https://github.com/musescore/MuseScore/actions/runs/5364399778
> 
> It is quite likely that this will fix the startup problem for @MarcSabatella. If it also fixes the login problems, I would be surprised, but we can try; so far, I wouldn't know what else could cause this.

@cbjeukendrup Yes, this build also fixes the login problem on my side!

**Comment by cbjeukendrup** [comment]
Hm, that's very strange. So that would mean that the crashpad handler executable somehow influences the OpenSSL version that Qt is trying to load... 

Meanwhile, Elnur has created a real fix: https://github.com/Eism/MuseScore/actions/runs/5369278399 (my build was just reverting some commit to confirm a conjecture of mine)

**Comment by Eism** [comment]
@DmitryArefiev @MarcSabatella 
Please check this build
https://github.com/Eism/MuseScore/actions/runs/5377230612/jobs/9755420030

**Comment by MarcSabatella** [comment]
Yes, this works for me!  I am able to start up normally, and log out/in to both musescore.ocm and audio.com.  Although again, for me I never had a problem with that, because I wasn't able to use the builds that might have had an issue.

**Comment by DmitryArefiev** [comment]
Fixed in #18214
