### ISSUE TITLE
When upgrading to a newer version of MuseHub, the custom Sounds Install Location should be preserved

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#18153]
### Issue type

Choose option...

### Bug description

I recently updated to the latest version of MuseHub.  As was instructed in the forums, I first uninstalled the old musehub and then installed the new one.  Unfortunately, this also reset the sound download directory to the default.  I feel that my old setting should have been preserved.

### Steps to reproduce

Have an older version of MuseHub installed.  Set a custom Sounds Install Location
Uninstall MuseHub.
Install the latest version of MuseHub
Note that the Sounds Install Location has changed.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
I wonder if this is caused purely by the upgrade, or rather by the uninstall+re-install (which users normally don't need to do when updating; that's only necessary when switching from non-beta to beta or vice versa)

**Comment by Tralen** [comment]
> I wonder if this is caused purely by the upgrade, or rather by the uninstall+re-install (which users normally don't need to do when updating; that's only necessary when switching from non-beta to beta or vice versa)

On Linux (Mint 21 Vanessa), I uninstalled and reinstalled multiple times and never had any problem with MuseHub losing my custom path. Checking the `.json' configuration file, it hasn't been touched at all by the reinstallation process, it still dates to the last time I changed a configuration and MuseHub seems to read it properly.

I have not tried just updating MuseHub because there wasn't a new release after I started using it (I'm on 1.0.1.451).

**Comment by bkunda** [comment]
@iamtesch would appreciate your thoughts on this one :-)

**Comment by DominicMaas** [comment]
So an uninstall and re-install will likely delete the MSIX package data, although on the top of my head, the sounds storage location is not actually stored there, but instead in `C:\ProgramData\MuseHub\Settings.json`. In the released version of Windows Hub, the MSIX location only contains settings for app theme and language. A future update will combine both these setting files into  `C:\ProgramData\MuseHub\Settings.json`.

Still shouldn't have reset, unless you manually deleted the data folder?

On linux, this should already be fine as noted by @Tralen . The DEB/RPM packages don't touch the user settings on uninstall.

**Comment by cbjeukendrup** [comment]
(Somewhat off-topic, but:

> A future update will combine both these setting files into `C:\ProgramData\MuseHub\Settings.json`.

That sounds like these settings will become system-wide, but shouldn't they settings be local for each user?)

**Comment by DominicMaas** [comment]
Yup... It's an ugly intermediate step. (And a side effect of the linux code base combining settings into one - we have some shared code here). The service runs system-wide (as we need admin permissions to install apps, effects and update hub), so that's why we have the settings in a system-wide location (and why there is a current split between settings files).

It's nasty, and I'm not entirely sure if anyone is running and using Hub on multi-user machines tbh 

Ideally the background service would run per-user, as an administrator, and we simply use local per-user settings. I do recall coming across this ability (new in Win10), but I'm not sure where I wrote down all my notes!

**Comment by zacjansheski** [comment]
Closing as fixed in V2
