### ISSUE TITLE
Treble clef E natural causing shifts in elements

### ISSUE THREAD

**Issue by MyCatIsAChonk** [musescore/MuseScore#18203]
### Issue type

Engraving bug

### Bug description

When moving notes via up and down arrow keys, elements like rests and time signatures shift slightly upwards when it hits E natural. This would make sense if the space between two staves needed to be expanded, but E natural is in the lines and (in my case) does not need to move anything. See the attached video for more details. I'm not sure if this is just E natural, nor if it's already been brought up, but felt worth reporting.

### Steps to reproduce

1. Create a score (my score is in 4/4 time and C minor)
2. Input a random note. Use up/down arrow keys to change the pitch of the note to E natural.
3. See the elements shift as you move to E natural.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/121187295/c8bb4b93-53e0-449e-a628-ba3f797ed6f0

### MuseScore Version

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

macOS 13.4

**Comment by cbjeukendrup** [comment]
My first thought about this is that this might be the same effect as described in https://github.com/musescore/MuseScore/issues/13887, perhaps in combination with some kind of pixel-rounding that might happen when drawing on the screen.

**Comment by oktophonie** [comment]
The slight shifts, though annoying, are just pixel-rounding as mentioned; the staves _are_ shifting a tiny bit (I assume because the natural extends downwards towards the slur). The positions of the items on the staves, even though some seem to move a little, will remain correct - they would look fine on a higher-resolution display, or when more zoomed in, or on paper. This is not really a bug.

**Comment by MyCatIsAChonk** [comment]
I see then, thank you for clarifying that.
