### ISSUE TITLE
MS3 and MS4 cannot run at the same time

### ISSUE THREAD

**Issue by meganlavengood** [musescore/MuseScore#18327]
### Issue type

Other type of issue

### Bug description

I try to open one version with the other already open, nothing new opens—it just refocuses on the app window for the version already open.

### Steps to reproduce

1. Open MuseScore 4
2. Try to open MuseScore 3, nothing happens

or the reverse, doesn't matter which is open first

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/60526470/d1d2e8fb-f71e-43db-b421-283fc9ab7eed

### MuseScore Version

3.6.2 and 4.0.2

### Regression

I don't know

### Operating system

macOS 13.4.1

**Comment by cbjeukendrup** [comment]
This is a macOS bug (or annoying design), so we cannot do anything about it. When you try to open a second instance of an application that is already running, macOS will bring the running instance to the front, instead of creating a new one. So far so good. But the problem is, that Spotlight considers MS3 and MS4 to be the same app\*, so if one is running and you try to open the other, Spotlight will just bring the existing instance to the front, even though the running instance is not the requested app.

\* In some sense, this is correct: MS3 and MS4 are just different versions of the same app. But Spotlight apparently only looks at the so-called bundle identifier, instead of looking which actual app you are trying to open.

I guess https://feedbackassistant.apple.com is where you need to be (but Apple seldom responds, is my experience).

**Comment by cbjeukendrup** [comment]
By the way, fortunately it is easy to get around this. It's just Spotlight that has this problem. You can add both versions to the Dock, or you can open them from Finder, and then it does work.
