### ISSUE TITLE
When plugins have identical file names, only one is displayed in the menu

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#18381]
### Issue type

Other type of issue

### Steps to reproduce

1. Unzip the attached folder and move it to MuseScore's Plugins folder
2. Open MuseScore, only 'Plugin 1' is displayed
3. Rename one of the plugin files to something else
4. 'Plugin 1' and 'Plugin 2' are displayed
[filenamedemonstration.zip](https://github.com/musescore/MuseScore/files/11947978/filenamedemonstration.zip)

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by wizofaus** [comment]
To add, in order to get the Plugins page to *show* the updated plugins, you must click "Reload plugins" *AND* navigate to a different page to close the "Plugins" page, then repoen it (i.e. it will never refresh while it's still open. The Plugins menu might.).

**Comment by cbjeukendrup** [comment]
@wizofaus It seems that problem is actually logged as https://github.com/musescore/MuseScore/issues/13220. If you'd indeed like to work on that issue, please post a comment there so that I can assign you (GitHub only lets me assign people from the `musescore` organisation or who have already commented on the issue).

And if you would like to work on this issue too, that's also welcome!

**Comment by wizofaus** [comment]
Is it considered a priority for 4.4? It's not assigned to any project so I'd rather not spend time on it if the PR is likely to be take some time to be looked at.

**Comment by cbjeukendrup** [comment]
It's perhaps not a priority, but that doesn't mean that if you create a PR it won't be reviewed. (to be honest, in my case, how soon I review a PR depends on how easy it is to review, not on the priority)
