### ISSUE TITLE
Horn plays an octave higher

### ISSUE THREAD

**Issue by innerthought** [musescore/MuseScore#18425]
### Issue type

General playback bug

### Bug description

One note seems to be playing an octave higher by the horn
[try - copy.mscz.zip](https://github.com/musescore/MuseScore/files/11962040/try.-.copy.mscz.zip)
![horn_in_octave_higher](https://github.com/musescore/MuseScore/assets/119835219/eec9b1c5-8ca9-4317-a734-3d24041a7cbc)

### Steps to reproduce

1. open my file
2. play it back and see that the first two of the four notes are an octave higher

Happens with MS Basic as well as Muse Sounds. 

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Win-10, 64-bit operating system, x64-based processor

**Comment by MarcSabatella** [comment]
I can reproduce with this score.  FWIW, it plays correctly when you enable concert pitch.  That's normally a sign that the tpc1/tpc2 data has gotten out of sync.  I also note it works if you replace the key signature, or if I replace the note.  So I can't figure out how to reproduce this from scratch.

**Comment by MarcSabatella** [comment]
@sammik This is probably related to https://github.com/musescore/MuseScore/pull/17601 or one of the various followups.  I wonder, for the sake of compatibility, if we shouldn't keep the old default for prefer sharps/flats in imported scores?  That is, explicitly change the old "default" to "none" instead of "auto" when importing older scores.

Meanwhile, explicitly changing it from auto to none after import is another workaround - better than re-entering the notes :-)

**Comment by sammik** [comment]
@MarcSabatella I can try to look into, but I cannot gurantee If it will be today, sorry.

(My children are screamin "Come on daddy, we are ready".)

**Comment by MarcSabatella** [comment]
I will try to have a PR in later today.  But, there are lots of import paths to consider, not just 4.0.2.  I'll do what I can.

**Comment by sammik** [comment]
@MarcSabatella thank to Your investigation, I crated slightly different PR - if part contains more than 6 accidentals, it has to be PreferSharpFlat::NONE, otherweis it is left in default state.

**Comment by DmitryArefiev** [comment]
Fixed in #18425
