### ISSUE TITLE
Custom-sized spaces in text objects disappear if copied, or when file is closed and reopened

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18553]
### Issue type

UI bug

### Bug description

This bug was supposed to have been fixed in #12756 but is still operative.

Amongst other things, this bug stops guitarists from adding angled brackets to fretmarks to indicate harmonics, because the custom-sized space between the brackets disappears if the element is copied, or dragged to a palette, or the file is closed and reopened.

N.B. There is currently no other way to add guitar harmonic symbols to fretmarks.

### Steps to reproduce

See OP of #12756. 

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment]
While I have been able to reproduce the problem copy+paste of custom sized spaces in text objects, I'm curious to learn more about this point:

> There is currently no other way to add guitar harmonic symbols to fretmarks.

Is this the harmonic symbol you are referring to @rgreen5? Or is it something else?  

<img width="148" alt="Screenshot 2023-09-14 at 1 55 39 pm" src="https://github.com/musescore/MuseScore/assets/86290556/74c1b180-91b5-4149-a586-eda50bd4eace">

Some extra visuals to describe "angled brackets to fretmarks to indicate harmonics" would be really helpful.

Thanks!

**Comment by mike-spa** [comment]
@rgreen5 we didn't fix it back then because 
1. We found that the problem arises from something that we can't directly control/fix (and personally I am not 100% sure that it _can_ be fixed).
2. There is a very simple solution: using an empty character instead of the space. You can probably find something that works for you [here](https://emptycharacter.com/#:~:text=to%20test%20it-,Unicode%20empty%20characters,-Bored%3F%20Free), but for me it is as simple as typing "ctrl+space" instead of "space". Can you please try and let me know?

**Comment by rgreen5** [comment]
> There is a very simple solution: using an empty character instead of the space.

Good idea.

**Comment by Jojo-Schmitz** [comment]
This issue is resolvable, see #32144, which extends the fix from #17739 to not work for "ScoreText" (i.e. Musical Text Fonts) only.
In fact it just automatically uses whet here is being mentioned as the workaround: it uses a non-breaking space
