### ISSUE TITLE
[TIED NOTES] Trill lines over tied notes only affect the first note if a staccato is added to the last note

### ISSUE THREAD

**Issue by PholMC** [musescore/MuseScore#18626]
### Issue type

General playback bug

### Bug description

Trills lasting multiple measures would work normally however, if the last note of the trill is a staccato, the trill would only play for one measure. This appears to have been an issue since Musescore 4.0 as the bug applies regardless if the soundfont is the default (MS Basic) or Musesounds.

### Steps to reproduce

1. Create a new score
2. Add notes that cover multiple measures and insert ties
3. Insert a staccato at the end of the last note
4. Add a trill above the notes including the staccato
5. Play back the notes and the issue should be noticeable

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/124211487/f8dc9811-0411-40d3-9094-aae2966b3e15

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by bkunda** [comment]
I believe this issue is actually another instance of playback problems we currently have with ties, rather than having anything to do with measures. 

**SoundFont**

https://github.com/musescore/MuseScore/assets/86290556/c5c8e87a-41eb-4ac4-83b4-2f34429b0359

**Muse Sounds**

https://github.com/musescore/MuseScore/assets/86290556/e2bbd0cd-ffc3-4931-aa85-b7e5b76976e0

I'll adjust the title of this issue and add it together with our other tied notes issues.
