### ISSUE TITLE
Advantages of MuseScore 3 that could be in MuseScore 4

### ISSUE THREAD

**Issue by Beniegenie** [musescore/MuseScore#18677]
### Your idea

It would be nice to have the ability to change the sounds of the instruments like in this score: https://musescore.com/user/28700996/scores/6447800?share=copy_link
The moog synthesizer is actually an electric piano. It would also help if one could take the sounds from past MuseScore versions and use them for MuseScore 4. One last thing, you should be able to have different dynamics for different voices and staves within the same instrument.

### Problem to be solved

This would allow people to get the sound they want for any score.

### Prior art

[_No response_](https://musescore.com/user/11780191/scores/5799378?share=copy_link) (for the ability to change the dynamics within the instrument)

**Comment by cbjeukendrup** [comment]
Thanks for reaching out! However, issues like this, that contain multiple requests are not really workable for us, because it is inconvenient to have to keep track of which parts has been done and which not. 
But in this case, all things you mention have already been requested, so you don't need to create any new request. 

For selecting individual sounds from soundfonts, see #17233.
For using the sound font from MuseScore 3: this can already be done by installing the MuseScore 3 sound font to MuseScore 4's sound fonts folder. Please ask on the forum on musescore.org if you need help with that. However, the "MS Basic" sound font is almost exactly the ("high quality" version of) the MS 3 sound font. 
For different dynamics per staff, see #16812.

So here are two things to keep in mind in the future when creating issues:
- discuss exactly one issue per GitHub issue
- before creating a new issue, make sure that there is not already an open issue for that topic

Thanks!
