### ISSUE TITLE
Implement 'up', 'down', 'between' direction setting for cross-staff beams

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#18687]
By default, cross-stave beams go between the staves.

Beams can be dragged above or below all the notes, but it would be nicer to have a per-beam (not score-wide) setting for this which would also find the optimal placement for the beam on whichever side is selected, following all the normal placement rules (i.e. without the user needing to find a good position by themselves).

![image](https://github.com/musescore/MuseScore/assets/20604032/25b286f3-97c8-45f5-8366-3981d89e76ee)

Partially ground work for https://github.com/musescore/MuseScore/issues/15544

**Comment by cbjeukendrup** [comment]
Perhaps we should extend this idea to work for cross-three-staves beams too (so that you can choose between which pair of staves you want the beam). 
<img width="347" alt="Scherm­afbeelding 2023-07-18 om 19 47 49" src="https://github.com/musescore/MuseScore/assets/48658420/cae99e4d-2d13-484a-aaa3-f854acd89aee">
(It's a bit exotic, but I think I must have seen such notation somewhere, probably in some exotic music)

**Comment by worldwideweary** [comment]
Could it be that the direction command defined as "x" could also toggle between these 3 instead of 2 states? From my *user's* point of view it seems like it would work well when cross-staffing.
