### ISSUE TITLE
Cue size notes not maintained when parts are generated

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#18772]
### Issue type

Engraving bug

### Bug description

Cue size notes are not maintained when the part is generated.

[Adagio from Concierto de aranjuez - no parts generated.zip](https://github.com/musescore/MuseScore/files/12138507/Adagio.from.Concierto.de.aranjuez.-.no.parts.generated.zip)

Not sure if this is a Engraving or UI bug.

### Steps to reproduce

Open the attached score
Observe the measures 32->35 and measures 43->57 contain cue notes.
Generate the part for the Solo Flugelhorn
Check the measures in the generated part. These contain normal sized notes, instead of the expected cue size notes.

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
What happens in both MU3 and MU4 is that if you set cue size - or any other appearance-related properties - *before* generating parts, that property is copied to the part.  But changes to these properties *after* parts are generated are not linked, in order to allow you to have the sort of independent control that is often necessary.  That's by design and not different between MU3 and MU4.

But while this behavior might make some amount of sense as a default in at least some cases, clearly it would be great to have more control over this.  That has been a very long-standing desire, and it appears it is being prioritized for a future update - see https://github.com/musescore/MuseScore/issues/16544

Meanwhile, in MU4, you can reset the part to pick up any new changes made in the score.  In MU3 you could achieve the same in two steps, by deleting and regenerating the part.

**Comment by henkdegroot** [comment]
@MarcSabatella, thank you for spotting my mistake. As you can see from the filename, I really believed I had not generated parts for this score yet. I wish there was an easy method to see parts have been generated or not.

**Comment by MarcSabatella** [comment]
Could be there were parts automatically generated on import from a previous version?  Also, because MU4 allows you to close the *tabs* for the parts while leaving the part itself intact, it's easy to not be sure.  Anyhow, it's certainly possible there is a bug here somewhere, but also, the reset does work.

I do agree it would be great to have a clearer sense of which parts have been generated and which have not.  The ability to actually remove parts is also a separate request.  See for instance https://github.com/musescore/MuseScore/issues/18089, although the real fix for that is is not requre deleting parts just to use certain features in the first place.

**Comment by henkdegroot** [comment]
Initially yes, but later I did create them (and forgot) as the score crashed (due to a bug which has been fixed already).
Thinking for now, I will pay more attention to the file size.
