### ISSUE TITLE
Part deletion pop-up window sometimes lacks text content until next keystroke

### ISSUE THREAD

**Issue by paulalndwhr** [musescore/MuseScore#18814]
### Issue type

UI bug

### Bug description

When trying to delete corrupted parts from an orchestral score, the deletion dialogue asking the user to confirm their intentions to delete the score is only rendered partially.

### Steps to reproduce

I have not checked if I can replicate it since I do not know a sure way to force a file to get corrupted.

1. Have a big score
2. Have corrupted parts which are rendered correctly in the main score
3. Try deleting the fault scores
4. Poorly rendered pop-up window appears a majority of the scores, but not all the time

### Screenshots/Screen recordings

<img width="668" alt="Bildschirm­foto 2023-07-26 um 22 40 32" src="https://github.com/musescore/MuseScore/assets/109522890/3e882f2c-75b7-4101-9ebb-9cf45affd99f">
<img width="660" alt="Bildschirm­foto 2023-07-26 um 22 37 01" src="https://github.com/musescore/MuseScore/assets/109522890/47848057-c4fd-46b1-8991-f3dcb27cf44b">

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921401, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

macOS 13.1

### Additional context

I have not had issues of this kind with any other dialogue/pop-up window.

**Comment by zacjansheski** [comment]
Could you share log files for this issue?

**Comment by philipplndwhr** [comment]
I did not actively obtain any log files, unfortunately.
How would I find one (on Mac) if one was automatically created?
This post by Jojo Schmitz was written with Windows as OS in mind and I cannot find a /logs folder inside my Musescore 4 directory.
https://musescore.org/en/node/345455

**Comment by cbjeukendrup** [comment]
The logs are in `~/Library/Application Support/MuseScore/MuseScore4/logs`, but the easiest way to obtain them is using "Diagnostic" > "Save diagnostic files" inside MuseScore itself.

**Comment by philipplndwhr** [comment]
[MuseScore_230726_085535.log](https://github.com/musescore/MuseScore/files/12240590/MuseScore_230726_085535.log)
[MuseScore_230726_145338.log](https://github.com/musescore/MuseScore/files/12240592/MuseScore_230726_145338.log)
[MuseScore_230726_223344.log](https://github.com/musescore/MuseScore/files/12240593/MuseScore_230726_223344.log)
[MuseScore_230726_224158.log](https://github.com/musescore/MuseScore/files/12240594/MuseScore_230726_224158.log)
[MuseScore_230726_224316.log](https://github.com/musescore/MuseScore/files/12240595/MuseScore_230726_224316.log)

Hey guys, I am ever so sorry that I do not exactly remember the time the bug occurred. Those should be all .log files that might have logged the bug.

**Comment by philipplndwhr** [comment]
[DIAGNOSTIC-error-provoked.zip](https://github.com/musescore/MuseScore/files/12250668/DIAGNOSTIC-error-provoked.zip)

It happens sometimes, but not all times. I tested it today and it
- only happens if the part in question is not empty, i.e. contains at least one instrument. Otherwise, the dialogue window is not triggered and the score is being deleted right away
- happened to non-corrupted files/parts
- only happens with a probability of approx. 20% (10 runs, 2 errors)

**Comment by cbjeukendrup** [comment]
@paulalndwhr Hi! Is this problem still actual? If it still occurs in 4.3.2, could you please check if it also still occurs in the latest nightly build from https://musescore.org/en/nightly-builds?

Sorry that we didn't get back to you anymore last year. The reason for that is that we just haven't been able to find any logical explanation for this bug, especially because it happens so intermittently. So I really hope that it's gone in the latest nightly builds; those use a newer version of Qt, which gives some hope.

**Comment by zacjansheski** [comment]
Closing as stale (no response)
