### ISSUE TITLE
MS4.1 can't replace cloud scores created in MS3

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#18821]
### Issue type

Cloud saving/loading issue

### Bug description

If you have a MuseScore 3 score on MuseScore.com and you open it in MuseScore 4 via _Home > Scores > My online scores_, it is not possible to overwrite the online score when saving via _File > Save_ or the shortcut Ctrl+S.

### Steps to reproduce

1. Upload a MuseScore 3 score to [musescore.com](http://musescore.com/).
2. Open MS4.1 and sign in.
3. Go to Home tab > Scores > My online scores.
4. Find the MS3 score you uploaded earlier and open it.
5. Make a change and attempt to save (Ctrl+S).

**Actual behaviour:** You will be presented with the "How would you like to save?" dialog. (In this dialog, if you click "Save to cloud" it creates a new online score instead of overwriting the existing one.)

**Expect behaviour:** No dialog should appear: the existing online score is simply overwritten like MS4 cloud scores.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/11011881/18a9950d-ddc5-4b71-ac0f-5834e81f1d8e)

### MuseScore Version

4.1 or latest nightly

### Regression

No.

### Operating system

Windows 11

### Additional context

The above appears to be a side effect of the following intentional behaviour:

1. Open a local MS3 score in MS4.
2. Make a change and press Ctrl+S to save.
3. The "Save as" dialog will appear.

We show the "Save as" dialog to give the user a chance to save the score as a new file, thereby preserving the original file so that it can still be opened in MuseScore 3. However, we never explicitly mention this to the user.

Perhaps we should show a dialog like this when overwriting local MS3 and cloud MS3 scores:

> __Replace the existing score created in MuseScore 3__
> Once saved in MuseScore 4 you will no longer be able to open it in MuseScore 3.
> [ Cancel ] &nbsp;&nbsp;&nbsp;&nbsp; [ Save as new score ]  &nbsp;&nbsp;&nbsp;&nbsp;   __[ Replace ]__

Here the middle button would trigger the "How would you like to save?" dialog. Or it could go directly to either the "Save to cloud" or "Save as" dialog depending on whether the current score is a cloud score and the user could click "Cancel" if they want to use the other option (they would find it in the File menu).

The user would not see this dialog again for this score once it has been saved with MuseScore 4 via any method.

**Comment by bkunda** [comment]
It took me some time to realise what this issue was about (I initially thought it was that scores saved in MS3 trigger the "how would you like to save?" dialog when attempting a cloud-save in MS4, which would be expected). 

To be clear (do correct me if I'm wrong), this issue is about opening a score created in a pre-MS4 version **from the "my online scores"** tab in v.4. This score would have been uploaded to musescore.com either through the MS3 "publish" flow, or directly via the website itself.

Indeed, it does feel odd that, when opening a score from the "my online scores" tab and hitting "save", you should be prompted with the "how would you like to save?" dialog. Obviously true "cloud" scores saved from v.4 won't trigger this dialog, so I can see the user scratching their heads to figure out why some scores would trigger this when their impression is that they are already saved to the cloud. 

What I think we shouldn't trouble ourselves too much with is the backwards-compatibility problem (which with @Tantacrul we have already discussed enough already). I think we open an unnecessary can of worms if we try to introduce additional messaging in the cloud flow to alert users that their file will no longer be openable in a version prior to v.4.

A cleaner solution would be to not call the "how do you want to save?" dialog at all when opening a score from the "my online scores" tab. If a score is opened from this tab, then it should be considered a cloud score, and so subsequent saves will simply continue to overwrite the file on musescore.com. As already stated, the fact that this renders the score no longer openable in MS3 is consistent with our current behaviour for all other methods of opening and saving old scores in v.4.

**Comment by Tantacrul** [comment]
Agree. There should be no extra messaging. You should just be able to press **Save** and then it replaces the MS3 cloud score with the MS4 cloud score.
