### ISSUE TITLE
whole note display problem

### ISSUE THREAD

**Issue by Auase** [musescore/MuseScore#18843]
### Issue type

Engraving bug

### Bug description

Is there a calculation error with the whole note? It seems like there shouldn't be any other note values within the same measure, right??? It also shouldn't cross over bar lines, right?

### Steps to reproduce

any staff.
I found that in the code, whole notes are composed of other note values added together, rather than having their own individual duration.

### Screenshots/Screen recordings

![whole](https://github.com/musescore/MuseScore/assets/56365735/ea7359d9-6531-4510-8fee-c5a0ece46d8a)

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

win11

**Comment by cbjeukendrup** [comment]
I see nothing strange here. A whole note has the length of four quarter notes. So, for instance, in a 2/4 time signature, the note needs to be split into two measures, because there is only room for 2 quarters in a measure. And in a 6/4 time signature, there are six quarters, so after a whole note there are still two quarters left.

However, I understand the source of your confusion. For whole _rests_, there is an exception, namely that a whole rest can be used to indicate a _measure rest_, rather than 4 quarters rest. But this does not apply to whole _notes_.

**Comment by MarcSabatella** [comment]
Indeed, MuseScore is behaving correctly here.  If you have further questions about music notation or how MuseScore works, please ask for help in the Support forum on musescore.org.

**Comment by Auase** [comment]
@cbjeukendrup 
Yes, I am indeed confused because of whole rests
