### ISSUE TITLE
at every start of the appImage it behaves like it is running for the first time

### ISSUE THREAD

**Issue by Louis-JR** [musescore/MuseScore#18899]
### Issue type

Other type of issue

### Bug description

every time starting MuseScore-4.1.1.232071203-x86_64.AppImage
it behaves like it is starting for the first time.
In particular it resets the folder preferences to its own preset.

### Steps to reproduce

1. start MuseScore-4.1.1.232071203-x86_64.AppImage
2.  check folder preferences set in a previous run

### MuseScore Version

OS: Ubuntu 22.04.2 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

(X)Ubuntu 22.04.2

**Comment by MarcSabatella** [comment]
I have no problems with preferences being saved in the 4.1.1 AppImage, including folder preferences.

Be sure when you make changes to preferences that there is only one one open MuseScore window, and then close MuseScore when done.  Otherwise Preference made in one window may clobber settings made in another window that is open at the same window.  Also be sure there are no permissions issues in your home folder that might be preventing MuseScore from saving preferences in ~/.config/MuseScore
