### ISSUE TITLE
Ms 4 does not include a "Save" button in the main toolbar

### ISSUE THREAD

**Issue by fsgregs** [musescore/MuseScore#18896]
### Your idea

MS 3.6 and many many other Windows programs always include a "**Save**" button for a user to click frequently, so that his/her changes will save as they proceed.  MS 4 does not include a **Save** button in its main toolbar.  While we can use "**Ctrl + S**", an actual button would be more common and convenient.  It should be placed on the left top of the toolbar as most Windows programs place it. 

### Problem to be solved

Restore a feature in MS 3.6 that was useful and handy, and establish MS 4 as a program using very common toolbar buttons.

**Comment by Jojo-Schmitz** [comment]
See also #15426 and #18883

**Comment by Tantacrul** [comment]
I don't see any harm in adding a 'Save' feature to our list of actions that can be enabled / disabled on the main toolbar. However, we should not enable it by default because it clearly isn't a need that the majority of our users have, especially given that there are already two tried and tested ways of doing it.

I'd counter the example given of apps that do have a save button by pointing out that there are many more creative apps which don't.

**Comment by Jojo-Schmitz** [comment]
What exactly does you mean by "main toolbar"?, The note input toolbar?

**Comment by oMrSmith** [comment]
> I'd counter the example given of apps that do have a save button by pointing out that there are many more creative apps which don't.

Just throwing in an example - I think a good one - of how Studio One deals with this controversy:

https://github.com/musescore/MuseScore/assets/78870770/95046a62-84b1-4b36-93aa-000cc520551e

**Comment by fsgregs** [comment]
I do mean the Note Toolbar as the main toolbar.  While I may not be familiar with the programs that do not include a "Save" button on their toolbars, I am very familiar with the many programs that do.  I find that the button to **Save** is used by many folks as a default convenience in these many programs, so if adding a button to the notes toolbar in MS4.2 is not difficult, please do so.

**Comment by Jojo-Schmitz** [comment]
See PR #18883, 3rd commit

**Comment by Tantacrul** [comment]
To play devils advocate here, since we have a customised menu bar for Windows, we could always place a save button there. Not much use for Linux users but they're all so smart and shortcut savvy, they'd probably feel insulted by it

Apart from that an option in the note input toolbar (disabled by default) seems harmless.

**Comment by fsgregs** [comment]
Tantacrul:  I wish I was better at Windows, but I have no idea how to add a Save button to the "Windows" toolbar when MS 4 is running.  In fact, I see no Windows toolbar at all.  If it is there, please show me where it is, and how it could be customized so that a Save Button could be added and would work on the open MS 4 program.  Thanks.

**Comment by Jojo-Schmitz** [comment]
I too have no idea what @Tantacrul is refering to here.

**Comment by cbjeukendrup** [comment]
He means that MuseScore's menu bar is built by us, rather than provided by Windows; so we can customise it ourselves, and add a "Save" button next to the menus (File, Edit, View... those menus). However, it would seem a bit weird to me though, to have one single button up there in that corner.

**Comment by Tantacrul** [comment]
It wouldn't be weird at all. Microsoft Office have been doing it for years.
<img width="608" alt="image" src="https://github.com/musescore/MuseScore/assets/21022311/ab10b93c-8480-4496-9153-f509e1da363d">

**Comment by fsgregs** [comment]
Sigh!!!  I see the menu bar in MS4 but I have no idea how to edit it in any way.  The File menu does have a Save tab and a shortcut (Ctrl+S), but I am unaware of any way to add a "Save" menu to the menu bar, or create a Save button on the menu bar.  Is there such a way to customize this?

**Comment by cbjeukendrup** [comment]
In the case of Microsoft, it's not one button but a whole group of buttons, and it's not next to the menu bar but above it. 
Also, in many other apps, people find an app icon in the top left corner (which displays a window context menu when you click on it). It might be a bit surprising to find something completely different there. 
<img width="709" alt="Scherm­afbeelding 2023-08-04 om 00 04 10" src="https://github.com/musescore/MuseScore/assets/48658420/e8027168-a358-4aff-b8e9-2dcf58d9223e">

We could indeed put those buttons above the menu bar, but that will leave us with a total of _four_ rows of content at the top of the window (if you count the note input bar too).
<img width="704" alt="Scherm­afbeelding 2023-08-04 om 00 09 07" src="https://github.com/musescore/MuseScore/assets/48658420/bbffa17f-f2a7-41ab-9ef1-1bd7d7ad8e8e">

**Comment by cbjeukendrup** [comment]
> Sigh!!! I see the menu bar in MS4 but I have no idea how to edit it in any way. The File menu does have a Save tab and a shortcut (Ctrl+S), but I am unaware of any way to add a "Save" menu to the menu bar, or create a Save button on the menu bar. Is there such a way to customize this?

No, I mean that _we_ (developers) can decide to do things with that menu bar in a future update, if we want.

**Comment by fsgregs** [comment]
Ah, OK.  I don't know about all the other File commands, but the "Save" tab at least would get used by everyone frequently, every time we worked on a score.  Respectfully, please add a Save icon to the one of the toolbars at the next patch of MS 4.

**Comment by oMrSmith** [comment]
> but that will leave us with a total of _four_ rows 

Oh no! ;) My vote is:
![image](https://github.com/musescore/MuseScore/assets/78870770/e2fe1f9c-b5a0-435a-bdae-ba8de375da31)

**Comment by Tantacrul** [comment]
> Ah, OK. I don't know about all the other File commands, but the "Save" tab at least would get used by everyone frequently, every time we worked on a score. Respectfully, please add a Save icon to the one of the toolbars at the next patch of MS 4.

It's not a common request. It's a nice to have. Please don't try to suggest that people can't save without this button.

**Comment by cbjeukendrup** [comment]
Sometimes I feel a bit ridiculed by your reactions to my attempts to mock up things with the limited tools I have at my disposal, as if I need to realise VERY WELL that I'm NOT a certified designer (which is certainly true). But that must be exclusively a problem with how I interpret it.

Anyway, @oMrSmith's idea was actually my first idea too. So far, in this solution it looks the least like the button was forced into a design where it doesn't belong.

**Comment by Tantacrul** [comment]
@cbjeukendrup - the last thing on my mind is to try and make fun of a non designer for attempting to mock something up in order to get an idea across.

I create awful mockups all the time in order to do the same thing. My use of the phrase 'but designed to look nice' is one I use on my own speedy mockups all the time. Don't know if you saw my presentation on Monday but I did it then too.

**Comment by Tantacrul** [comment]
I don't like the idea of permanently placing the save button in the UI because it takes up more space in an area where we really need it and it's not really necessary for the majority of users. The save button would look fine in the top (top) bar or in the note input bar.

**Comment by Eism** [comment]
I don't like the idea of placing the save button or program icon in the top left corner of the window because I'm used to accessing the file menu quickly by moving the mouse cursor to the top left corner. If we put something else there, accessing the file menu will be more challenging. We discussed a similar case with the window close button, and Martin shared a video where Jensen Harris talk about the same issue with the start menu on Windows. https://www.youtube.com/watch?v=3wbnf87dGms

We can consider the option of adding buttons to the top right corner before the system buttons. There is enough space there to accommodate several buttons.

<img width="910" alt="Screenshot 2023-08-04 at 10 25 16 AM" src="https://github.com/musescore/MuseScore/assets/10116828/388685cd-b37f-4ded-9199-bf7692caee72">

**Comment by Jojo-Schmitz** [comment]
Yes, that one looks like a winnde to me. The indo/redo buttons to the far right were worring me too from the beginning
And indeed there's plenty space in the title bar. Not sure though whether that translates to all platforms?

**Comment by cbjeukendrup** [comment]
> Not sure though whether that translates to all platforms?

This would indeed work for Windows only, but I'm not worried about that; on macOS, save buttons are very uncommon (Apple seems to have dropped the concept of explicitly saving a file in most standard apps) and Linux users are probably not afraid of using a keyboard shortcut.

**Comment by Tantacrul** [comment]
> Hmm, but certaily undo/redo is needed on Mac and Linux too. Even if they also do have shortcuts. I doubt though that amongst the Linux and Mac users are significantly less mousers than under Windows.

Undo / Redo are remarkably commonly used in creative apps. In Paint 3D, 'Undo' was the most clicked on button in the interface. Perhaps that says something about the reliability of the drawing :)

'Save' is a bit different though. You don't need it anywhere near as much as Undo and the 'FILE/SAVE' (or Ctrl + S) pattern is really well known.

Anyway... I say we pop it as an option in the Note Input bar menu which you can enable? Any haters on that idea?

**Comment by cbjeukendrup** [comment]
Well, if we hide it by default and put it at the very bottom of the list of available buttons, I guess we don't have much better options... but it's not ideal since it's so unrelated to _note input_.

**Comment by Jojo-Schmitz** [comment]
I did that in my PR's 2nd commit (along with other former members of Mu3's File Operations toolbar).

However: that Note Input toolbar is pretty crowded already, having it next to undo/redo would put it into a place with plenty space. Making it optional there though would reqire a cod wheel button, so that space would get 'wasted' anyhow, so we could directly just put the Save botton there. Although with a cog whelel, we could also place the above mentioned other buttons too)
Putting it into the titlebar wouldn't 'waste' space, there's plenty too, but, as said, that'd be restricted to Windows only.

**Comment by Jojo-Schmitz** [comment]
My personal favourite would be to put just the Save button in front of the existing Undo/Redo buttons.
Plenty space, available on all platforms, similar grouping as in Mu3, win-win-win IMHO

**Comment by Tantacrul** [comment]
I should mention that there will be two more options next to 'Parts' and 'Mixer' soon enough (one will be for automating velocity, which we're building now) and I've seen plenty of screenshots of folk using small laptops, where space is pretty tight. 

A separate point but we do actually need to build some responsiveness into the toolbar in general, so certain parts of the app collapse nicely when there isn't enough room.

**Comment by MarcSabatella** [comment]
I think I'm with @Jojo-Schmitz - all things considered, adding the save button to the undo/redo area is probably the way to go.

Yes, it costs a little space, but if we also give this area a name and allow the user to disable it via View / Toolbars if they want, it's a net win for users who value saving space over having buttons (that would be me).  How feasible is that?  And would disabling this actually work in terms of allowing the window to be made smaller?

Eventually a cog for further customization, maybe a dock handle.  But really, as @Tantacrul says, the whole toolbar design needs to be looked at again in terms of responsiveness.  And that's probably a bigger project for another day.

As for the title bar and note input toolbar ideas - I don't love them as they feel like hacks of convenience as opposed to anything I'd actually choose from a design perspective (disclaimer: IANAD).  But either is better than nothing for those wanting this feature, so I wouldn't complain too much.

**Comment by Jojo-Schmitz** [comment]
2b: on the 2nd toolbar to the right (after or before the undo/redo buttons), my favourite...

**Comment by Tantacrul** [comment]
Option 1 for me - with a small spacing adjustment. It's also pretty clear looking at these screenshots that if we add it to the toolbar with 'parts'  and 'mixer' it's going to cause clash almost immediately with upcoming features.

I also want to remind everyone, almost no one will use this button, no matter where it goes.

**Comment by MarcSabatella** [comment]
2b (an option not actually pictured) still for me as well - next to the undo/redo - for the reasons already stated, it's the only option I actually *like*.  But I'm less keen on the idea if we can't then disable that group completely in View / Toolbars.  In which case I'd pick 1 or 3 as the less undesirable of the others.

**Comment by fsgregs** [comment]
I also want to remind everyone, almost no one will use this button, no matter where it goes.

See, I disagree a lot.  I asked for the Save button because people WILL tap it frequently when working on a score, far more than a Print or Save As button.  I think it will be used every 10 - 15 minutes or so, so the score changes we just made will be saved.

**Comment by shoogle** [comment]
A few people will use it very frequently. Everyone else wouldn't use it at all.

@Eism's suggestion to [put it on the right of the title bar](https://github.com/musescore/MuseScore/issues/18896#issuecomment-1665146420) looks the best to me by far. That could be made to work on macOS too. Here's how Office for Mac does it:

Windowed: https://mspoweruser.com/wp-content/uploads/2018/01/Office-for-Mac.jpg

Full screen: https://i2.wp.com/9to5mac.com/wp-content/uploads/sites/6/2015/07/office-2016-for-mac-is-here-3-1024x596.png

Of course, this would only be worthwhile for MuseScore if we had something else to put up there in addition to the save icon, otherwise it just results in wasted space, particularly in full screen, where the Home, Score, Publish row would have to move down to accommodate it.

**Comment by Jojo-Schmitz** [comment]
Well, I do ha a severe left-right weakeness, but isn't it to the left on those images?

**Comment by MarcSabatella** [comment]
I do also like the title bar idea, especially if it can be done for macOS.  It wouldn't bother me to not have it for Linux, and I suspect none of the folks requesting this so strongly are Linux users.  I guess we could keep undo/redo where they are for Linux?  Wouldn't break *my* heart to lose them, but I guess we could consider adding the save icon there, so save/undo/redo are all together on all platforms, just in slightly different places.

**Comment by Jojo-Schmitz** [comment]
See #24833, which will fix this

**Comment by Jojo-Schmitz** [comment]
As #24833 has been merged, can we consider this issue fixed and close it?

just how is it supposed to work?

**Comment by cbjeukendrup** [comment]
The examples (especially "example2") at https://github.com/musescore/MuseScore/tree/master/share/extensions seem a good source of information. It should be possible to use `api.dispatcher.dispatch("file-save")` to actually save the file. 

I'll indeed close this issue, since those who want it can achieve this via extensions now. If it turns out there are still any problems with the extensions framework, feel free to open a new issue specifically about those.

**Comment by Jojo-Schmitz** [comment]
I hav't been able to get that "example2" to work

**Comment by cbjeukendrup** [comment]
Have you enabled it via Home > Plugins, or does it not even appear there? 
(And of course it's only going to work in 4.5 builds.)

**Comment by Jojo-Schmitz** [comment]
O did enable it via Home > Plugins. but nothimnghsappened, esp, no Save button showed as in the video on the PR
