### ISSUE TITLE
Playback option is grayed out

### ISSUE THREAD

**Issue by Aurivox** [musescore/MuseScore#18978]
### Issue type

UI bug

### Bug description

Playback option is grayed out regardless of the file.

### Steps to reproduce

1. Click on Playback option.
2. No changes are possible

### Screenshots/Screen recordings

![Bildschirmfoto 2023-08-07 um 18 20 47](https://github.com/musescore/MuseScore/assets/103463374/aabf636d-12b3-4638-83a8-7a0546d74898)
![Bildschirmfoto 2023-08-07 um 17 32 18](https://github.com/musescore/MuseScore/assets/103463374/1c291dd0-4459-440c-a932-63c34c6968ef)

### MuseScore Version

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13.4.1

**Comment by cbjeukendrup** [comment]
I'm not sure I understand what you mean. The options in the playback _popup_ only become enabled when they are relevant for the elements that are selected in the score. So if you select a note, like on the screenshots, only the "Notes" options will be enabled in the popup, which is indeed the case on the screenshot. And if you select an arpeggio, the "Arpeggio" options would become enabled. 

Or perhaps you mean that absence of a "Play" _checkbox_; I believe it is absent when viewing a part score instead of the full score. That is by design. If you switch to the full score, it should be visible in the "General" ("Allgemein") section.
