### ISSUE TITLE
Cannot get 3 bars in 1 system

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#19013]
### Issue type

Engraving bug

### Bug description

Now I made this score from scratch. 
How to get 3 bars in 1 system without awful spacing??
[spacing2.zip](https://github.com/musescore/MuseScore/files/12317114/spacing2.zip)

### Steps to reproduce

see mscz file

### MuseScore Version

latest nightly 

### Regression

I don't know

### Operating system

win 11

**Comment by MarcSabatella** [comment]
The best method would be to reset some or all of customizations you made to your style settings in Format / Style / Measure, and then also reduce the overall staff size in Format / Page settings.  There is no getting around the laws of phsycis here - that many notes with the staff size as big as it is just won't fit without awkwardness.  But, if you wish to force the measures to fit - and thus accepting the resulting issues - select the measures you want to crowd and then click the "group measures" icon on the Layout palette.  Then you can play with the remaining settings to see which oproduce the least objectionable results.

In the future, when you have questions about how to use MuseScor,e please ask on the official Support forum on musescore.org.  Only open issues here on GitHub after another commonuty member has confirmed that what you are encountering is a bug, and one not already reported or already fixed for an upcoming release.

**Comment by mart661331** [comment]
Hi,
In my opinion there IS enough space, but it is not used.
If a program made for score writing is not able to properly space the notes
without a very lot of tuning effort, you should ask yourself what has
priority:
Making nice scores without a lot of work, or ....

Three bars in a system with 16th notes may really not be problem. Also with
this staff size/spacing.

So I consider this a bug.

Regards
Martin


Op vr 11 aug. 2023 01:21 schreef Marc Sabatella ***@***.***>:

**Comment by oktophonie** [comment]
Put a "Keep bars on same system" item from the Layout palette on the first two barlines.

![image](https://github.com/musescore/MuseScore/assets/20604032/6daa382b-9c8f-4526-a8d8-68804bf55338)

I'm not sure what you expect. Call this a 'bug' if you like.

**Comment by mart661331** [comment]
Hi,

This is nice spacing with same staff distance in page settings

Took me about 30 minutes. And worse, if I want to change layout (bars to
other system) - I must do it all over again..

So, yes, I call it a bug.

SIncerely
Martin

Op vr 11 aug 2023 om 10:12 schreef Simon ***@***.***>:

**Comment by mart661331** [comment]
Hi,

This is nice spacing with same staff distance in page settings

Took me about 30 minutes. And worse, if I want to change layout (bars to
other system) - I must do it all over again..

So, yes, I call it a bug.

SIncerely
Martin

Op vr 11 aug 2023 om 01:21 schreef Marc Sabatella ***@***.***

**Comment by mart661331** [comment]
Hi Marc,
what a pity that there is no response to my last picture with much better
spacing..
But apparently it's not important enough for you....

Regards,
Martin


Op vr 11 aug. 2023 01:21 schreef Marc Sabatella ***@***.***>:

**Comment by MarcSabatella** [comment]
I'm not sure why you're addressing me specifically - I'm just a volunteer helping to update issues here when the original report seems not clear, as was the case with yours.  Anyhow, I am still not sure what you are saying the bug is exactly - e.g., which specific style setting you feel is not being honored correctly, or the results of your calculations showing that it should all fit give your settings as is.  But I do know that just a general sense that things should fit given your settings because "in your opinion" it should is not really anything the developers can go on.

I can't speak for anyone else, but I personally recommend asking for help on the forum to discuss this in more detail.  If it then turns out as a result of those discussions that there is a bug - a setting not being honored correctly, or a case where the calculating is overestimating the amount of room required based on your settings, etc - you can update this issue with the more specific info that would allow people to investigate further.

**Comment by mart661331** [comment]
Thanks for the feedback!

Op za 12 aug 2023 om 15:39 schreef Marc Sabatella ***@***.***>
