### ISSUE TITLE
Bad Header text positioning, adds space consuming gap unexpectedly reducing the available music area

### ISSUE THREAD

**Issue by HeinzVo** [musescore/MuseScore#19014]
### Issue type

UI bug

### Bug description

Bad Header text positioning, adds space consuming gap, thus unexpectedly reducing the usable music area.

Placing Header text ABOVE the top page margin is NOT POSSIBLE without loosing rare page space at the music area,
while placing Footer text BELOW the bottom page margin perfectly works with no interaction at the music part.
This inconsistency between Header and Footer should be removed!

At header text (Format / Style / Text Stiles / Header) positive and negative offsets both add a useless gap, unexpectedly limiting and shifting down the music area.
At footer text (Format / Style / Text Stiles / Footer) positive and negative offsets (referred to page margin) work fine as expected, not clipping the music part.

Header features should be well harmonized with Footer to achive full and free positioning control without influencing, reducing or shifting the music area.
Also swiching Headers and Footers on/off should NOT influence the music area or score page rendering (as worked excellent in MS 3.6.2).

### Steps to reproduce

At header text (Format / Style / Text Stiles / Header) positive and negative offsets both add a useless gap, unexpectedly limiting and shifting down the music area.

At footer text (Format / Style / Text Stiles / Footer) positive and negative offsets (referred to page margin) work fine as expected, not clipping the music part.

Test score and screenshots included inside following zip:
[Detected Problems MuseScore-4.X.X.zip](https://github.com/musescore/MuseScore/files/12317206/Detected.Problems.MuseScore-4.X.X.zip)

### Screenshots/Screen recordings

![MuseScore 4_Style_Header_off (mark)](https://github.com/musescore/MuseScore/assets/140117374/436a0082-eab5-4e7a-bb01-a7732bc621d3)
![MuseScore 4_Style_Header_2mm (mark)](https://github.com/musescore/MuseScore/assets/140117374/d40f2cbb-fb99-41b3-bd8b-c7f4da16f6f9)
![MuseScore 4_Style_Header_-3mm (mark)](https://github.com/musescore/MuseScore/assets/140117374/7ce4d1aa-feef-487a-b92f-99bec7d6ca81)
![MuseScore 4_Style_Footer_off (mark)](https://github.com/musescore/MuseScore/assets/140117374/7ea36a3e-ccfa-49cc-aa23-736c6c667756)
![MuseScore 4_Style_Footer_-1mm (mark)](https://github.com/musescore/MuseScore/assets/140117374/d3d00910-72d1-435d-a601-33beda0c5405)
![MuseScore 4_Style_Footer_3mm (mark)](https://github.com/musescore/MuseScore/assets/140117374/56132462-0c2e-45d0-8041-fcce93fe18e1)

### MuseScore Version

MuseScore 4 (any version)

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10 and 11, 64-bit

**Comment by MarcSabatella** [comment]
It seems to me there *is* a bug here, but there is also a misunderstanding about the new design.  Headers no longer "steal" space from the score as they did in MU3.  So you no longer *need* the old hack of applying a negative offset to the header text style to force the header into the marign area just to avoid collisions, nor do need to artifically increase the margin size to account for this header.  Just set the margin to the actual amount of white space you desire, and leave the header offset at the default.

However, it does appear there is a bug in the algorithm that calculates the amount of space required for header.  As shown in the example, the space is reserved for the header even it ends up not being needed because the header text itself has been shifted upwards, and in fact the amount of space reserved actually *increases* when offseting the text in this manner.

So in the following example:

![image](https://github.com/musescore/MuseScore/assets/1799936/4dd2f289-8c7f-4781-9c9a-9a6563ff6513)

The text in the score runs right up to the top margin.  If I add a header using the defaults, it correctly adds space:

![image](https://github.com/musescore/MuseScore/assets/1799936/3b069d91-5e9b-48cd-8def-d0c4b5c6bfc5)

However, rather than decreasing the space if the header text itself is moved into the margin (via negative offset in the text style), actually *increases* the amount of space required:

![image](https://github.com/musescore/MuseScore/assets/1799936/63d4fb38-939d-44dd-ad53-14dc3831beb0)

**Comment by oktophonie** [comment]
I'll grant that the behaviour of offsetting header text downwards is inconsistent with offsetting footer text upwards.

However, why you'd do this anyway is bizarre. Margins are supposed to be empty (that's what they are for); the header and footer text are part of the page image and do not encroach upon the margins. If you want your header higher or your footer lower you can adjust the top/bottom margins accordingly.

See https://github.com/musescore/MuseScore/pull/9193, and also https://github.com/musescore/MuseScore/issues/17201.

**Comment by HeinzVo** [comment]
No. Headers and footers are usually placed fully outside the page-content-margins (see Microsoft-Word or every similar apps). Headers and footers are "optional additional information", NOT belonging to the real page-content (e.g. copyrights or references or page numbers). Only that way it is possible to optional switch on/off the headers/footers without always corrupting the whole page-content-layout.
Also headers and footers could only be present on some pages (e.g. not on the first page) and therefore it's unpractical or completely nonsense to adjust the page-content-margins all the time when selecting or unselecting them. So the behavior in MuseScore 3.6.2 should be the correct way and equals to most other text- or graphics-app.

**Comment by MarcSabatella** [comment]
MU3 allows headers to collide directly with the page content, or to encroach upon the margin and even extend right off the page.  Neither is even remotely acceptable.  No other program does any such thing - all programs I know, including Word, allocate space for headers as needed.  Meaning yes, as your header grows in size, it will push content off the page.  This is trivial to demonstrate for yourself in Word.

**Comment by HeinzVo** [comment]
Then the positioning should be limited in a way that it lies always inside the page but outside the defined contents-margins. See at Microsoft Word how it does this correctly. Headers and contents have different limits/sizes usually not influencing each other, when properly set to not overlap.
