### ISSUE TITLE
Is there a (not *insanely* difficult) way to pull out notation view/editor for my own app/does the license allow it?

### ISSUE THREAD

**Issue by kaifastromai** [musescore/MuseScore#19053]
Hello,
I am trying to write my own app that helps with piano practice, and I need a robust way to show potentially very complicated notation. Writing this from scratch on my own would require an immense amount of time and effort, so I was wondering if it would be possible to extract the notation view out of MuseScore and use that? I could maybe use something like lilypond, but I suspect that might much harder to expand (do correct me if I am wrong).

**Comment by kaifastromai** [comment]
I'm not sure why this was closed as "not planned"--it isn't a feature request? I'm just wondering if there is anyone here familiar enough with the architecture to give an educated opinion on the feasibility of isolating the notation view. I've taken a look at the architecture docs, and it seems quite modular, but there also appears to be a sort of specific harness around that modularity that I'm not sure can be removed. The first comment was not particularly elucidating.

**Comment by oktophonie** [comment]
It's basically a support request. GitHub is for reporting bugs and requesting new features. If you want to ask development questions, the MuseScore forum is probably the best place.

**Comment by Jojo-Schmitz** [comment]
Only that only very few staff memember are active in the musescore.org forums. And this is a question directed at the staff.

**Comment by cbjeukendrup** [comment]
Anyway, to give a quick answer to your question: 
- license-technically it's possible if your project uses a suitable license. The code for MuseScore is available under a GPL3 license; so if your project uses GPL3 too, you can use MuseScore's code in your project. On the internet, you can find tons of "license compatibility matrices" to find out which other licenses your project can use if you want to include someone else's GPL3 code. I don't have enough expertise in this area though to give you more detailed advice on this. 
- technically, it will be a big challenge, because if you want MuseScore's score view, you'll need almost everything of MuseScore: the score data model, the layout engine, and possibly the file format / reading / writing too, and the score paint view is tightly connected with the interaction code. So you'll have a lot to hook up even if you just want to display a score without any interaction possibilities. Or you can write your own score view (but still use our data model / layout / painting engines), so that you don't need to worry about all those interaction things that we have.
- It also depends a lot on what tech stack your project uses. If it's a desktop app using Qt (and QML), it will be the easiest. Otherwise, it is still possible, but more difficult: you'll either need to embed a Qt view in the rest of the app, or you need to write your own viewer for each platform (which is possible by the way; the data model and layout engine don't depend on Qt and are even tested regularly without Qt, and our painting system allows you to build a custom backend to replace the Qt backend).
- So, the layout engine and painting system are designed in a way that will make things like this possible, but our own UI code (and score view code) is not really suitable for reuse in other projects. Regarding how much support you can expect from us: don't expect that we'll do it for you :) but if you have concrete questions, you can ask them in the suitable places for that, namely MuseScore.org or preferably or Discord server (see https://github.com/musescore/MuseScore/wiki). I'll try my best to answer them on my free evenings :)

**Comment by kaifastromai** [comment]
Thank you so much!
