### ISSUE TITLE
MuseScore no longer exports dynamics as MIDI CCs (Breath Controller data is missing, CC2)

### ISSUE THREAD

**Issue by hmturnbull** [musescore/MuseScore#19096]
### Issue type

Other type of issue

### Bug description

Previously (in 4.0), exported MIDI contained the dynamics as the Breath Controller CC, which could then be used for automation in a DAW. But since updating to MuseScore 4.1, the exported MIDI only has an assortment of empty automation tracks. The only representation of dynamics is the note velocity.

Is there something I'm missing?

### Steps to reproduce

1. create a score
2. add some dynamics (such as dynamic text and hairpins)
3. export as a MIDI file
4. drag the MIDI file into a DAW
5. all included automation is static, and dynamics/breath controller CC are missing

### MuseScore Version

4.1.1-232071203

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 (64-bit)

### Additional context

[Missing MIDI CCs - Example.zip](https://github.com/musescore/MuseScore/files/12384613/Missing.MIDI.CCs.-.Example.zip)

------------------

Was broken in **4.0.2** with #16232

Additional info in #19680

**Comment by bkunda** [comment]
@zacjansheski @DmitryArefiev would be good to try reproduce (potential candidate for 4.2 project).

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/assets/69917893/bb9d380b-6b3d-4861-8d55-4bbf691d87cf

**Comment by bkunda** [comment]
Definitely should be addressed, but I'm going to suggest this is more a P2 than a P1 owing to the user workflow not being super common.

**Comment by ShawTakeuchi** [comment]
I concur except with MS4.0 dynamics expression export ("hairpin" data) was buggy (data was mostly there with large "zero" gaps mid-score).  

With MS4.1.1, the control data is missing in entirety.

Please also keep in mind MS3 had an important option for exporting dynamics/expression data to user selectable MIDI CCs: 1, 2, 4, and 11.  

Suggested workaround until the issue is addressed:

1.  Compose on MS4
2.  On MS4: Export MusicXML file 
3.  On MS3: Import MusicXML file
4.  On MS3: Export MIDI File
5.  On DAW: Import to MIDI File

**Comment by ChriiMoral** [comment]
> Definitely should be addressed, but I'm going to suggest this is more a P2 than a P1 owing to the user workflow not being super common.

Personally, I massively depend on this feature as I'm a terrible keyboardist, and have an easier time humanization MIDI from MuseScore than trying to play things myself in a DAW. Just a note though.
