### ISSUE TITLE
slur direction changes after reopening file

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#19206]
### Issue type

Engraving bug

### Bug description

On some note combinations, a slur that was saved in the down position below the notes will be flipped to above the notes when reopening the file if the slur connects from one system to another below it or starts on one page and ends on the next page.

### Steps to reproduce

[slur direct.zip](https://github.com/musescore/MuseScore/files/12458537/slur.direct.zip)

1. open the file
2. make the slur go under the notes
3. save and close the file
4. open it again to see the direction flipped

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/120861729/3a7c5dd2-e1f1-4564-9372-dac818f080e5)

the problem was first seen in this case where the flipped slur also collided with tremolo slashes

### MuseScore Version

4.1.1-232071203

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

**Comment by oktophonie** [comment]
Neither @miiizen nor I can reproduce this (in 4.1.1), but I'm pretty sure this is a real issue as I've encountered it, or something very similar, myself in the past.

**Comment by Vykoiazon** [comment]
Did you use the hotkey x to flip the slur while selecting it¿

**Comment by ShibuyaCyana** [comment]
+1 for this, I have the feeling that my ties keep resetting themselves for reason I can't figure out...
and I notice, if you try to drag a tie (added from left panel, the tie from upper panel doesn't behave like this) to reverse it, it will become invisible, and actions like drag, pan and zoom will become laggy, as long as the invisible tie is selected:
![jammed tie](https://github.com/musescore/MuseScore/assets/39703247/0bb942d9-15d8-44d5-b804-98c070b352f7)
and if I mess with spacing and line breaks, a seemingly normal tie will may become a invisible one:
![tiebecomeinvisible](https://github.com/musescore/MuseScore/assets/39703247/95d670cc-3fdd-4f0a-8b2a-4434d4ace6cd)
which...might indicate something tricky is happening, and might have something to do with this problem...

**Comment by ShibuyaCyana** [comment]
some other strange behaviors:
again only happens to ties from left panel, if any of the two notes has an upward beam, the tie will become reluctant and refuse to transform itself:
![reluctant](https://github.com/musescore/MuseScore/assets/39703247/9501372a-2a47-4b2b-9a16-0aa4339fe2f6)

and again, strange thing happen if I separate these two notes with a line break:
![strange thing after line break](https://github.com/musescore/MuseScore/assets/39703247/42c87a0f-8692-4e7e-a89b-cb548443a404)
in this case the first half of the tie still refuse to transform, but the second half doesn't, tho it's actually sticking to a note with an upward beam.

This one maybe more related to this issue, since from the OP's picture the tie ends on a 16th note with beam upward.
