### ISSUE TITLE
Vertical offset for text in lines is disabled

### ISSUE THREAD

**Issue by TheNotSoOkayGuy** [musescore/MuseScore#19230]
### Your idea

The title is all that's it. I just reckon that vertical offset for the text on pedals shouldn't be greyed out.

MuseScore 4.0 | MuseScore 4.1
:---:|:---:
![image](https://github.com/musescore/MuseScore/assets/11011881/9c9a50aa-37f6-4a88-9f7a-6f5a0ed31a89) | ![image](https://github.com/musescore/MuseScore/assets/11011881/fb228d0f-5689-45db-83c3-824f0d4404aa)

### Problem to be solved

Here's an example of a use case for vertical offset
![image](https://github.com/musescore/MuseScore/assets/126557120/85fd719a-b30f-4777-ace1-988da8a249bc)
Sometimes the pedal can be pushed down a bunch along with the Rosette, which may make it a tiny bit troublesome for some performers to make out exactly when they should stop pedaling. But by adding vertical offsets to pedals texts, and by extension, rosettes, you'd be able to communicate to the performer by like 5-10 milliseconds faster or something.
![image](https://github.com/musescore/MuseScore/assets/126557120/43b858d0-3730-4841-bffb-b443eadb255e)

**Comment by bkunda** [comment]
Seems like this one could be solved if we implement diagonal adjustments of lines (See https://github.com/musescore/MuseScore/issues/14382). 
Closing as a duplicate.

**Comment by MarcSabatella** [comment]
Implementing diagonal lines fixes this one special case, but it doesn't solve the more general problem of vertical text offset, which is really what this issue is about.

For instance, in 3.6.2 as well as 4.0 you can do the following:

![image](https://github.com/musescore/MuseScore/assets/1799936/93e62057-718d-40bd-ac41-c7131a7bb93c)

The vertical offset is used here to push the text above the line instead of even with it as per the default.  This worked fine in 4.0.2 but for some reason is grayed out as of 4.1, so you can't set it anymore.  The property itself is still honored - a line  with a vertical text offset created in 4.0.2 continues to be displayed correctly in 4.1.1; you just can't edit that offset anymore (except to reset it).

**Comment by shoogle** [comment]
Sounds like this is a bug, and a new one at that.

**Comment by MarcSabatella** [comment]
Could use a better title, like "Vertical offset for text in lines is disabled"
