### ISSUE TITLE
Playback doesn't start at cursor after using escape then making a selection, play goes to beginning of score instead.

### ISSUE THREAD

**Issue by AliWood282** [musescore/MuseScore#19259]
### Issue type

General playback bug

### Bug description

Using escape to end playback returns playback to beginning of score even after selecting a new note

### Steps to reproduce

1. Make a selection, Loop the selection.
2. Play
3. Escape, turn off loop
4. Select a note, play, playback returns to the beginning of the score
5. Escape will return playback to the beginning of the score afterwards despite selecting a different note

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

Using escape while in playback of loop seems to be key here.

https://github.com/musescore/MuseScore/assets/69917893/2655f5af-5a22-4d69-b98d-d305d69bd8b7

_No response_

**Comment by MarcSabatella** [comment]
In order for someone to investigate, please ZIP and attach the specific score that is triggering the problem for you, and give more precise steps to reproduce the issue (e.g., say which note to select that causes playback to not start there, or whatever other steps need to happen first in order for the problem to appear).

If you need help figuring out the steps, please first ask for help on the official Support forum on musescore.org where fellow users can help you narrow down the problem, so that by the time you come back here to GitHub, you can say exactly how to reproduce the problem.

**Comment by AliWood282** [comment]
Yes I can provide the steps. This is a really annoying problem for someone who uses playback a lot.
Step 1: select first note of soprano in bar 14. Hit the play button. 
My result: as expected, no problem, it starts to play at bar 14 .
Step 2: select the whole of bar 14, and hit the loop arrow in the playback window.
My result: as expected, plays the loop of that bar.
Step 3: UNSELECT the loop. Select the first note of the bar again
Step 4: Hit the playback button:
My result. Starts playback at the beginning of the score! 
Conclusion. This is a bug. Clearly the playback should continue at bar 14 as it did in step 1.
File attached.
[Next piece 21 recapitulation shortened a bit.zip](https://github.com/musescore/MuseScore/files/12515249/Next.piece.21.recapitulation.shortened.a.bit.zip)
.Please let me know that you received this.

**Comment by AliWood282** [comment]
Why has it marked it as closed?

**Comment by cbjeukendrup** [comment]
You must have hit the wrong button accidentally. But don't worry, I've reopened it :)

**Comment by AliWood282** [comment]
I closed it by mistake, sorry

**Comment by AliWood282** [comment]
Thankyou

**Comment by MarcSabatella** [comment]
FWIW, for me it doesn't go back to the beginning, but it also doesn't start with the selected note, either - it just continues where it left off.

**Comment by AliWood282** [comment]
Is this message for me? If so, I provided all the information I could 2 days ago. Please tell me what other information you need. Ali Wood

**Comment by AliWood282** [comment]
Is there a way I can receive an e-mail when this topic is amended, please?

**Comment by zacjansheski** [comment]
We havent reproduced the issue yet as described.  In the description it says you are using 4.0?  Could you confirm this is an issue with the latest release?  (4.1.1)

A screen recording could also help us reproduce/resolve

**Comment by MarcSabatella** [comment]
I was able to reproduce as problem in 4.1.1, but as I said, it didn't go back to the beginning - it just continued where it left off.  Which is also wrong, but not as bad.

The key seems to be going directly from the range selection to the single selection at step 3.  If you *clear* the selection first by pressing Esc and *then* select the first note, it works as expected.

Here is a recording of how it works for me following the steps provided - notice the last playback continues where it left off rather than starting with the selected note.

[Screen recording 2023-09-06 12.08.14 PM.webm](https://github.com/musescore/MuseScore/assets/1799936/0ce98ead-a2b0-4be1-892a-10bbbbeda08f)

**Comment by zacjansheski** [comment]
So this is the issue:
1. Make a selection, play, stop
2. Select a note within the earlier selection
3. Play, playback will start where it was paused instead of the selected note.

Am I correct in understanding this?  I don't think it has to do with the loop at all.

https://github.com/musescore/MuseScore/assets/69917893/1d98f6e0-e980-4a6a-8343-4e638720de0d

**Comment by AliWood282** [comment]
That may be accurate for what Marc has raised.
But I am having the issue that I raised.
I'm struggling to do a video of the screen, but will TRY to get you one using my mobile phone. (is there an easier way? - I'm not very tech savvie)

**Comment by zacjansheski** [comment]
A mobile video is fine.  Most people use OBS.  Are you on 4.0?  If so please update to 4.1.1 before taking the time to make a video.

**Comment by AliWood282** [comment]
I am on 4.1.1

**Comment by AliWood282** [comment]
What is OBS

**Comment by AliWood282** [comment]
Can you try what I indicated, pressing the escape button. In the meantime I'll get a video somehow

**Comment by MarcSabatella** [comment]
Bingo, hitting Esc instead stopping playback normally with the space bar or toolbar icon triggers the "back to the beginning" big for me as well.

There are lots of tools that can record your screen directly, and the quality will be better than your phone.  I use Screencastify a lot; Loom is also popular.  Both can run from your browser so you don't need to install anything.  For short recordings that don't need sound, you can also use gifcap.  A web search on any of those names should send you there.  Same for OBS< but tha'tsa a far more complex piece of software; overkill for simple demos like this.

**Comment by zacjansheski** [comment]
We can reproduce now, so no need for a screencapture

**Comment by AliWood282** [comment]
Cheers, hope that details the issue satisfactorily. I will use the spacebar or toolbar now, it's just that I'd always used the ESC button in the past.

**Comment by zacjansheski** [comment]
@MarcSabatella I'll re-scope this issue report and raise the select and play issue separately.  Thank you for your help!
