### ISSUE TITLE
Allow user to view key signature of tablature

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19317]
### Your idea

On standard music staffs the key signature is explicit, i.e. displayed on the staff itself. This is not the case with tablature staves which, AFAIK, can "hold" a key signature, but for obvious reasons do not display it.

However it is still useful for the user to know the "hidden" key signature of the tablature. For example, s/he may want to generate a linked staff from the tab, or copy notation from the tab to another staff, and wants to make sure that the new staff has the correct key signature already in place.

It would also allow the user to differentiate between a staff in C major and one with an open/atonal signature.

So, it would be useful, IME, to display the key signature of all staves, perhaps as a read-only property in the status bar or the Staff/Part properties window etc.

**Comment by MarcSabatella** [comment]
Since key signatures can change throughout a piece, I'm not sure it really makes sense to display it as if it were a staff property.  But you can "see" each key signature on the tab staff by navigating to it via the keyboard - Alt+Left/Right and then checking the status bar.  So, to examine the initial key signature for example, select the tab clef then press Alt+Right.

**Comment by rgreen5** [comment]
> – to examine the initial key signature for example, select the tab clef then press Alt+Right.

Problem solved. :+1:
