### ISSUE TITLE
2nd submission: there is a major bug with sets on MuseScore.com.

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#19321]
### Issue type

MuseScore.com set update bug.

### Bug description

#####PLEASE don't just close this ticket. I tried to contact MuseScore.com directly, and they are not responding. I can't proceed with publishing my book of saxophone etudes on Amazon until this bug is resolved.#####

I submitted this bug before and it was closed. The closer said that I need to contact the Musecore.com Team. I did contact them more than 10 hours ago, and they have not responded. This bug is very frustrating, and it caused me to delete an entire set. I recreated the set, and now the bug has reappeared in the new set. When I try to update my set's description, I get this error message "Page not found, sorry about that". This is a major major problem because I'm going to publish my book on Amazon soon, and I need to be able to update the set's description with the URL of my book on Amazon.

Deleting and re-creating the set is problematic because the URL of my set is in my book: if it changes, then the paper book will no longer have the correct set URL.

The set is here: https://musescore.com/user/18100066/sets/6457480
When I try to update the set's description, I get an error page here, and the set's description is not updated: https://musescore.com/score/collections/set/update-process?id=6457480

### Steps to reproduce

1. Login to MuseScore.com
2. Goto MuseScore set https://musescore.com/user/18100066/sets/6457480
3. Click on "Update this set"
4. Update the set's description and try to save.

Expected behavior: changes are saved.
Actual behavior: receive this error message: "Page not found, sorry about that".
The error message appears on this page: https://musescore.com/score/collections/set/update-process?id=6457480

This error forced me to delete my previous set of 500 etudes. I created a new set, added the 500 etudes to the new set, and I was able to add a new description. However, a few hours later, the bug re-appeared on the new set.

Please see the image of the error message below.

### MuseScore Version

4.1.1.232071203 Revision e4d1ddf

### Regression

I don't know

### Operating system

Pop!OS 22.04

### Additional context

![Screenshot from 2023-09-07 16-11-35](https://github.com/musescore/MuseScore/assets/1860586/e9d9527a-d979-476d-972d-3f801e6981a3)

**Comment by cbjeukendrup** [comment]
I understand your frustration very well, but we really really can't do anything with your issue here. We cannot fix MuseScore.com problems, nor provide support for them (and even though some of us have a "staff" account, we don't have access to change scores from other people to fix things). MuseScore.com is really a separate project from a different part of the company. The only thing I can do is try to find out who is responsible for MuseScore.com support and give them a kind reminder, but I don't know if that will work. But I will try it for you.

(And yes, you might see some other MuseScore.com issues here, but those are only related to the integration of the desktop app and the website. If it turns out the problem is on our side, the issue stays open, if it's on their side, the issue gets closed here, because this issue tracker is only for the desktop app.)

**Comment by RexDjere** [comment]
@cbjeukendrup Thank you Casper!! I understand. I'll send a new message to the Musescore.com team about the re-curring bug. Hopefully, I hear from them soon.
