### ISSUE TITLE
I submitted a bug report to the MuseScore.com team more than 48 hours ago, and they have not responded. As a result, I'm going to have to do several hours of unnecessary re-work.

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#19339]
### Issue type

Choose option...

### Bug description

I've given up on hearing from the Musescore.com team. There is a very serious bug on the MuseScore.com website that prevents updating the description field for this MuseScore set: https://musescore.com/user/18100066/sets/6457480. Every time I try to update the set description, I get a "Page not available, sorry" error. This has been happening for more than 2 days. 48 hours ago, I submitted a bug report to the MuseScore team, and I haven't heard from them at all. Every one of the 500 etudes that I've written has a link to the set that I can no longer update. I'm going to sell the book of 500 etudes on Amazon.com, and now I have to delete the existing set (that I can't update), create a new set, put a link to the new set in the description field of all 500 etudes, and then hope that I can successfully put a link to my book's Amazon page in the description field of the new set before it locks me out. This is going to take several hours of unnecessary work that I could have spent doing something else.

I'm not going to wait any longer to hear from the MuseScore.com team: as soon as I submit this report, I'm going to delete the set that I can' update, and start work on creating a new set. I hope that we can prevent this bug from hurting other members of the MuseScore community. Thank you for listening, and thank you for MuseScore 4: it's great!!!!

UPDATE:
I've deleted the broken set, and I've created a new set here: https://musescore.com/user/18100066/sets/6460858
I left the description field completely blank. I'll update it once once I get all the information, so hopefully it won't matter if it later locks me out (once I publish the book on Amazon, the description should never change again).

### Steps to reproduce

1. Log in to my MuseScore.com account.
2. Try to update the description section of this set: https://musescore.com/user/18100066/sets/6457480
3. Result: the update fails (please see the image below).

### MuseScore Version

4.1.1.232071203 Revision e4d1ddf

### Regression

I don't know

### Operating system

Pop!OS 22.04

### Additional context

![Screenshot from 2023-09-08 15-42-14](https://github.com/musescore/MuseScore/assets/1860586/5bd2de25-e9de-4f1d-b490-4af5d428bfe6)

**Comment by jeetee** [comment]
Please keep .com issues confined to that site and/or your previous issue about this (https://github.com/musescore/MuseScore/issues/19321 ).

Spamming the open source notation software issue tracker remains the wrong place for those issues (as you've been explained before).

**Comment by RexDjere** [comment]
@jeetee I understand. I'm just frustrated that I have to spend several hours going unnecessary rework. I estimate that it will take me 4 to 6 hours to change the URL in 500 etudes, work that I shouldn't have to do.

**Comment by shoogle** [comment]
@RexDjere, I'm sorry the set update didn't work for you. Perhaps you encountered a bug to do with the set having so many scores. I will ask the web team to look out for this in future.

But for now, to reduce the likelihood of thing going wrong again, I suggest doing things in this order:

1. Create a new set but **don't add any scores to it yet**.
2. If possible, create your Amazon listing so that you have a URL for it.
3. Click the "Update this set" button and:
    1. Edit the set description to be what you want it to be. Include the link to the GitHub repo and the URL for the Amazon listing if you have it.
    2. Choose the sort order you desire (presumably "Title" order since you named them 001 to 500).
    4. Click "Save changes". **You should not have to edit the set information ever again.**
3. Add the scores to the set, starting with 001 and ending with 500.
5. Double check that all the scores are in the set and in the right order, and the set description is what you want it to be.
6. Edit the score descriptions to add the new set link and the Amazon URL, starting with 001 and ending with 500.

Observations:
- Editing the 500 score descriptions is the bit that requires most effort, so doing that last means that you'll have wasted as little time as possible if things go wrong before you get to that point.
- Notice that I tell you to add the new set link and the Amazon URL at the same time, whereas you planned to do this separately before, which would have meant updating all 500 descriptions twice!
- Even if the original set hadn't broken for you, you would still have had to go back and add your Amazon link to all 500 score descriptions, so if you can now add the set link at the same time as the Amazon URL then you haven't lost any significant amount of time compared to if things had worked out the first time.

**Comment by RexDjere** [comment]
@shoogle Thank you so much for the rapid response!!! I'm sorry for being so much of a pain. I'll do everything that you recommended. Have a great weekend!!!
