### ISSUE TITLE
Cross Grand Staff Arpeggio Markings 

### ISSUE THREAD

**Issue by Lumi618** [musescore/MuseScore#19441]
### Your idea

Arpeggio markings that extend through both treble and bass clef without the user having to drag an arpeggio either down from the top staff, or up from the bottom staff, and also un-selecting "auto-place" in the properties menu so the staves don't space themselves out to account for the longer arpeggio symbol.

It would also be great if the playback could reflect this change as well.

![arpeggio examples](https://github.com/musescore/MuseScore/assets/121732752/ba091c22-278b-46fa-b193-c4d8fb0445af)

### Problem to be solved

This would solve composers/ people notating music having to edit their arpeggios themselves to make them look right, even though the playback would play each

**Comment by DaddyLudwig** [comment]
Well, for one thing, you don't have to drag and disable autoplace, there's another way to do this notation. If you put the arpeggio in the top staff and then select the arpeggio and press Shift + Down, it will put the arpeggio across the chord in both staves without having to disable autoplace to do it.

And second, I'd rather that if they are going to do anything with cross staff arpeggios that they put their energy into actually getting them to play back properly so that I don't have to do my workaround with 1 big chord in the bass staff encompassing the whole arpeggio, turning the notes there invisible, and then setting the notes that are visible to be silent.

**Comment by oktophonie** [comment]
As described, the notation can be achieved easily.
For playback, create a separate issue for that if you want it, if one doesn't exist already.
