### ISSUE TITLE
Transparent .svg

### ISSUE THREAD

**Issue by Ili4sV** [musescore/MuseScore#19555]
### Issue type

Engraving bug

### Bug description

When exporting to .svg in Musescore 4, a white background is added. In Musescore 3, the background of .svg images would be transparent.

### Steps to reproduce

1. Open a score
2. Export to .svg
3. Image is not transparent

### MuseScore Version

Musescore 4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by rettinghaus** [comment]
Both make sense, so this would be best to set as an option.

**Comment by Jojo-Schmitz** [comment]
Of course, just like for PNG

**Comment by MaxiSchwindler** [comment]
Just opened a pull request for this: #19996

**Comment by haklein** [comment]
unfortunately this cannot be toggled via commandline. This did work as workaround for me:
`sed -i 's/<.*fill="#ffffff".*>//g' filename.svg`
It's a pity that default behavior doesn't match previous versions. Also there seems to be a bug where only the SVG output of an excerpt has an additional background margin on top. PDF export of the same part adheres to the page settings and doesn't add that white margin. Due to the non-transparent background, cropping the margin via inkscape commandline didn't work either (`inkscape --batch-process --export-area-drawing --export-plain-svg --export-filename=crop.svg part.svg`). And for the records: the broken part export via job file can be worked around by unzipping the mscz and exporting each mscx (+mss) in the excerpts folder. I fully understand that my use case might not be a major one, but such breaking changes do not make the life easier of anyone using scripts/commandline to manage a large amount of musescore files and excerpts (book generation via xsl-fo here)
