### ISSUE TITLE
Braille Panel to be included in View Menu & Associated Shortcut

### ISSUE THREAD

**Issue by jmwmusic** [musescore/MuseScore#19556]
### Your idea

It would be really helpful if the Braille Window once enabled in preferences could be included in the View Menu and be able to be hidden/shown from there and with an assigned shortcut similar to the mixer, instrument panel, etc.

### Problem to be solved

Much quicker to unclutter the screen when the Braille window is not being used and also saves a number of keyboard strokes for screen readers getting around it when not in use if it can quickly be toggled on or off.

**Comment by daijingz** [comment]
I want to do this issue, can you allow me?

**Comment by daijingz** [comment]
@jmwmusic @cbjeukendrup mentor I have some questions about the Braille Window: Is the braille window mentioned in this video the target you are looking for? https://www.youtube.com/watch?v=P7aBt8f3c30

**Comment by jmwmusic** [comment]
Yes, the live Braille panel that Marc shows how to activate from the Edit/preferences/Braille menu is indeed the one.

**Comment by daijingz** [comment]
Then which section is the view menu? I feel the third top menu is the view menu (showing here):
![QQ截图20231109181012](https://github.com/musescore/MuseScore/assets/61481741/bae36095-7058-4dff-895c-4ebbdece6bcb)
My understanding is, that we need to add a button in this menu so that the braille panel can be enabled and disabled via a single slick in the options in the view table, is that correct?

**Comment by daijingz** [comment]
@cbjeukendrup @jmwmusic Mentor, then the most important part is, where is the view menu code? And how can we call the braille panel in the project?

**Comment by cbjeukendrup** [comment]
Yes, that's the correct menu. I think it makes sense to place the "Braille panel" option just below the "Navigator" option. I'd recommend to change MuseScore's UI language to "English (US)" in the Preferences dialog, so that it is clearer to you what we're talking about and clearer to us what you are talking about 🙂

I'll give you some hints about the code; not directly the answers, but the strategies to find them. That's probably the most educative.
- <details><summary> To find the code for the view menu: (click to expand) </summary>

   - search the codebase (Ctrl+Shift+F) for some string that only occurs in the view menu. It's the easiest when you set MuseScore's UI to English (US). For example, "Restore the default layout". You will find it in exactly one place in the code:
      <img width="457" alt="Scherm­afbeelding 2023-11-10 om 00 34 34" src="https://github.com/musescore/MuseScore/assets/48658420/b7a14e86-73f8-42ad-9137-bbb92473f9a2">
      Looks like the definition of some "UiAction", whatever that may be. Not very helpful, but this thing must be referenced somewhere else, right? Those lines with `mu::context::…` don't look like ways to reference this action, since they are very general, but that upper line, `"dock-restore-default-layout"`, does look like an ID or something. 
   - Let's search the codebase for `"dock-restore-default-layout"`, to see where it is referenced. You will find out that this leads you to the place where the View menu is defined.

   </details>
- <details><summary> To find how the braille panel is opened/closed:  (click to expand)</summary>

   - Again, when you have no clue where to look, it is often helpful to start from the UI. Currently, the only way to enable/disable the braille panel is in Preferences, using a checkbox called "Show braille panel". Let's find this string in the code. And again, luckily only one hit, so that must be the place. 
   - When this checkbox is clicked, it emits a signal, called `braillePanelEnabledChangeRequested`. Let's find where this signal is listened for. Search the codebase for `braillePanelEnabledChangeRequested`, and you'll find that it's in `BraillePreferencesPage`. 
   - There, you'll see that when this signal is emitted, the `braillePanelEnabled` property of `preferencesModel` is toggled. `preferencesModel` is a `BraillePreferencesModel` object. Look where that is defined; it will turn out to be a C++ class. Let's look specifically at the setter method of the `braillePanelEnabled` property; this method is called `setBraillePanelEnabled`. 
   - Now, you're very close: apparently, the way to toggle this panel is by calling `brailleConfiguration()->setBraillePanelEnabled(…)`.
   - There are still a few loose ends: what is `brailleConfiguration()`? If you Ctrl+Click it (in Qt Creator), it will show you this line:
      <img width="457" alt="Scherm­afbeelding 2023-11-10 om 00 51 46" src="https://github.com/musescore/MuseScore/assets/48658420/13d3631e-b0f8-4d7d-8b61-7ea0999e9d23">
      `INJECT` is a macro that generates a method to access "the" instance of an "interface". In this place, it is used to generate a method called `brailleConfiguration` that provides access to "the" instance of `braille::IBrailleConfiguration`. You'll also need to use this macro in the place where you want to implement the action of toggling the braille panel. And don't forget to #include the necessary header files; look in braillepreferencesmodel.h which ones that might be.

   </details>

- There are some more things you'll need to figure out; for example, how to create your own UiAction for the braille panel action. I recommend researching how the **`"toggle-navigator"`** action is implemented, since that one is very similar to what you would need to implement.

**Comment by jmwmusic** [comment]
Can I suggest a shortcut key.  As this shortcut and panel are mainly used by blind users and we love staying on the home keys rather than Function keys could I suggest Shift B or Ctrl Shift B if not already being used by another MuseScore function.  they seem to be unassigned currently to anything for NVDA but you would probably want to check they aren't being used for anything in Jaws also.

**Comment by daijingz** [comment]
Code for the view menu: D:\MuscScore\MuseScore\src\appshell\internal\applicationuiactions.cpp

**Comment by daijingz** [comment]
@cbjeukendrup @jmwmusic Mentor I just understand briefly what it is going to do. At first, I need to add a line for the code file:        makeMenuItem("toggle-BraillePanel"). Then there is a new option in the view menu. Then I need to set up the toggle-braille Panel has the appropriate Braille panel behavior.

For the short key, please wait a moment.

**Comment by daijingz** [comment]
Updating soon

**Comment by daijingz** [comment]
@cbjeukendrup @jmwmusic I understand how `toggle-navigator` works. By following its structures, I inserted a braille button after "navigator" section, although it is still doing the same thing as the "navigator" button, here is the screenshot:
![1704591592(1)](https://github.com/musescore/MuseScore/assets/61481741/a8807120-7dd2-48e0-8850-179318daeff2)

**Comment by daijingz** [comment]
These days I am always confused with one point: how do we call the function `setBraillePanelEnabled` in the UI action? because I have a search in the given code of this, and here is the result:
  
![1704591966(1)](https://github.com/musescore/MuseScore/assets/61481741/6e9b5f48-53e3-4a35-b383-ef83cd88d5d1)

I did not see any direct callings, but I learnt that we should use the macro to call: `INJECT(braille::IBrailleConfiguration, brailleConfiguration)` Let me do some research about it. @cbjeukendrup I am very closed.
@jmwmusic for a shortcut key, can we choose `F6`? This is not conflicting from other options.

**Comment by daijingz** [comment]
For the arrow before the term "braille", I am going to animate it as well.
Tonight I have an early-stage attempt, with failures on signals.

**Comment by cbjeukendrup** [comment]
Let's call the new menu item "Braille panel" instead of just "Braille". 

Indeed, you will need to call the `setBraillePanelEnabled` method of `IBrailleConfiguration` (not the one of `BraillePreferencesModel`). 

It is also correct that you use `INJECT(braille::IBrailleConfiguration, brailleConfiguration)` in the class where you want to call this method, so that you can use `brailleConfiguration()` to get access to _the_ `IBrailleConfiguration`, so that you can call `brailleConfiguration()->setBraillePanelEnabled()`.

But the question is indeed _where_ you will need to call this method. As said, I think the situation is very similar to the case of the navigator, so that would still be a good example.
The action code for the navigator is `"toggle-navigator"`, but that is not written in the code directly; instead, a constant is defined for it, called `TOGGLE_NAVIGATOR_ACTION_CODE`. 
So let's take a look where `TOGGLE_NAVIGATOR_ACTION_CODE` is used:
<img width="600" alt="Scherm­afbeelding 2024-01-09 om 00 07 11" src="https://github.com/musescore/MuseScore/assets/48658420/636bf366-8dff-486d-b8af-e5e84e528e38">
Not a lot of places. The first one is the definition; the second one is in the UiAction constructor, so not really interesting; the third one is about updating the check mark state of the action (i.e. whether a ✔️ is shown or not) so also doesn't really tell us how the action is implemented.
Then the fourth occurrence must be the interesting one. It relates `TOGGLE_NAVIGATOR_ACTION_CODE` to something else, called `NOTATION_NAVIGATOR_PANEL_NAME`. So, let's have a look where this `NOTATION_NAVIGATOR_PANEL_NAME` thing is used. This should give you some pretty useful inspiration for how to implement the braille panel action.

**Comment by daijingz** [comment]
@cbjeukendrup Got it!

**Comment by daijingz** [comment]
@cbjeukendrup Its name has been changed to "Braille panel"

**Comment by cbjeukendrup** [comment]
Okay. When you're ready, feel free to submit a PR, so that I can review it! :)

**Comment by daijingz** [comment]
> Okay. When you're ready, feel free to submit a PR, so that I can review it! :)

Sorry for these days' lack of time. I am learning UX/UI advanced features now.

**Comment by re1san** [comment]
@daijingz Are you still working on it?

**Comment by daijingz** [comment]
I am working on this and I have some progresses. @ddmngz @re1san I am debugging now, and I am going to post some of my codes soon. These days I met some unfixable difficulties on this issue, but I will fix this.

**Comment by cbjeukendrup** [comment]
@daijingz In case you have it mostly ready but are blocked by one or a few specific bugs, then feel free to create a draft PR already. That will allow us to give feedback already and perhaps help debugging. That's probably the most efficient!

**Comment by ddmngz** [comment]
@daijingz No worries, I know how it is! If you'd like another set of eyes on it let me know, I'd be happy to collaborate!

**Comment by daijingz** [comment]
Waiting for tomorrow.

**Comment by daijingz** [comment]
@cbjeukendrup @re1san @ddmngz @jmwmusic  In the last 60 days, I was trying to insert a shortcut key. However, I found these files, and I did not see any changes:
![C5BIS17`6L3JR)HH6OGVVL](https://github.com/musescore/MuseScore/assets/61481741/ef268c98-46b2-462f-8c51-40b8f7f15558)
I guess I changed the wrong place, let me find the correct place.
(I modified other places previously, and they did not work well too)

**Comment by daijingz** [comment]
I guess `Shift+B` is not a good shortcut key, since it is ambiguous. This is the page before using `Shift+B`:

![{R)DFO{2)2FZN)6ZSNJUQ65](https://github.com/musescore/MuseScore/assets/61481741/3154623a-3017-4a0a-b1ed-3260616748ae)

This is the page after using `Shift+B` once (**I did not select anything**):
![SF7VU4$L)6AD))QS3J W 7D](https://github.com/musescore/MuseScore/assets/61481741/f499e88a-a68f-4ed7-ae38-f06fd237d88b)
Looks like some other operators are selected. 

I suggest `Shift+Z` to be used, because it does not have additional effects.

**Comment by jmwmusic** [comment]
+ B is already assigned to add a B to an existing note.  Alt B adds a guitar bend, from memory I think Ctrl B selects a bar and Alt Shift is the insert bar dialogue box.  So as you can see blind users have a lot to remember so it is important that shortcut keys are easy to remember and use.  I would associate Z with undo and similar.  Maybe Ctrl Shift B for this as that I think is unassigned?  It would be good if this shortcut is also customisable once that bug s fixed so blind people can customise it themselves.  NB I have no idea how all this is done, this is just from the perspective of an end user.

**Comment by jmwmusic** [comment]
not sure that wrote correctly above, should have started SHIFT B is already ...

**Comment by jmwmusic** [comment]
@ddmngz If you are looking for something to work on there are a whole load of accessibility issues open relating to screen reading, some of which I've seen marked as good first time issues.17922, #15521, 20183, 19935, 19983, 19987, 19928.  I'm just an end user who logs some of these for the blind community and it would be great if someone was interested in getting into this area.

**Comment by shoogle** [comment]
I recommend using one of the function keys (F1 to F12) to open the Braille panel, possibly with Ctrl or Shift modifier since we might want to use the unmodified function key for something else.

For example, you could use **Ctrl+F12**. We use F12 to open the Timeline, which is like an alternative view of the score. Braille is also an alternative view, so it seems reasonable that they could use the same key. (We could use Shift+F12 for the Navigator, as in View > Navigator, which is another alternative view.)

Ctrl+F12 is available on Windows. Can anyone confirm it's available on Ubuntu/GNOME?

On macOS the shortcut would be **Cmd+F12**. Can anyone confirm this combination isn't already used as a system shortcut on macOS?

**Comment by jmwmusic** [comment]
Is alt F11 available.  My suggestion for this is because most of us using this feature are likely to then be exporting our music as xml from MuseScore and using it in Sao Mai Braile to transcribe the music.  SMB uses Alt F11 as its key to insert a music xml.  So this is a very familiar and easy one to remember that could sort of become the Braille music key.

**Comment by shoogle** [comment]
Alt+F11 is available on Windows. Can anybody confirm for macOS?

**Comment by ddmngz** [comment]
@jmwmusic Thanks for the recommendations! I'll see what I can do :)

**Comment by ddmngz** [comment]
@shoogle Confirmed!

**Comment by shoogle** [comment]
I think it's probably best if @daijingz makes the change as part of his PR.

> I was trying to insert a shortcut key. However, I found these files, and I did not see any changes:

It's possible that only `shortcuts.xml` is being used at the moment. I think `shortcuts-Mac.xml` and `shortcuts_AZERTY.xml` are not used, even on macOS, so make sure you change the main `shortcuts.xml`. You can change the other files as well just to keep them in sync.

If you edit those files but the shortcut isn't working, go to **Help > Revert to factory settings**, then see if the shortcuts are working after you restart MuseScore.

**Comment by daijingz** [comment]
@shoogle after reverting to factory settings, it works well:
![QQ截图20240315154044](https://github.com/musescore/MuseScore/assets/61481741/cda0a25e-56cf-4377-bf64-0c188371ec9c)
Submitted
