### ISSUE TITLE
sf2 file support bug

### ISSUE THREAD

**Issue by JustTheEMailGuy** [musescore/MuseScore#19618]
### Issue type

VST bug

### Bug description

Some sf2 files work just fine, while others don't. Every sf2 file gets recognized by Musescore as it should and are choosable as normal, but some just don't seem to play sound.

### Steps to reproduce

1. Put sf2 file into the Musescore 4 soundfonts folder
2. Open musescore
3. Open random sheet music
4. Choose an sf2 instrument sound
5. Be sad

### MuseScore Version

4.1.1.232071203

### Regression

I don't know

### Operating system

Windows 10

### Additional context

These named sf2 files do work.
They do play with other players, such as juicysfplugin.
No, the juicysfplugin does not seem to get recognised by musescore 4, so this doesn't solve the problem.

**Comment by DaffodilAura** [comment]
I was able to use MuseScore 1's .sf2 soundfonts with MuseScore 4, so these also need to be checked.

**Comment by cbjeukendrup** [comment]
This probably has to do with the fact that MuseScore automatically tries to choose which preset from the SoundFont to use, based on the layout of the MS Basic SoundFont; some sound fonts follow this same layout, while others don't. 
Starting with MuseScore 4.2 (since #18976), you will be able to select the desired preset manually, which should solve this problem.

**Comment by JustTheEMailGuy** [comment]
@cbjeukendrup Thanks for answering so quickly
Looking forward to every update!

**Comment by bkunda** [comment]
Closing this for now as it seems it will be solved by https://github.com/musescore/MuseScore/pull/18976
