### ISSUE TITLE
MuseFX Pro EQ settings not saved for presets other than "Pop Vocals"

### ISSUE THREAD

**Issue by klassisti** [musescore/MuseScore#19681]
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Apply the Pro EQ effect to an instrument.
2. Change the preset to anything other than "Pop Vocals".
3. Adjust the knob values.
4. Save the file and close it.
5. Reopen the file.
6. Open the Pro EQ dialogue again and the knob values will have reverted to the preset's defaults.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10

**Comment by ComposingPlanarian** [comment]
This is still a problem in 4.2.0.233521124. I consider this a major problem because we shouldn't have to go through every ProEQ in the mixer and set it back to where it should be.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

**Comment by cbjeukendrup** [comment]
I can also reproduce this in Dorico, which confirms that it's a bug in the VST plugin itself, not in MuseScore. I'll notify the relevant team about this.
