### ISSUE TITLE
File will not open

### ISSUE THREAD

**Issue by pib42305** [musescore/MuseScore#19698]
### Issue type

File corruption

### Bug description

I created a file, saved it and when i tried to reopen the file, it will not open and will shut down the program. 

### Steps to reproduce

1. try to open file
2. (https://drive.google.com/file/d/17RTZVVwDQpOFD3mC7P5nyEMmLj8bBghX/view?usp=sharing)

### MuseScore Version

4

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
The mscx inside the mscz opens without a crash.
The mscz also opens when first removing the Excerpts folder or even just the Organ sub-folder.

Interestingly ther organ.mscx itself loads without issies, but it seems to contain the entire score.

**Comment by cbjeukendrup** [comment]
This turns out to be the same problem as https://github.com/musescore/MuseScore/issues/17720#issuecomment-1565451171, or at least it crashes at the same place.

**Comment by cbjeukendrup** [comment]
I created a simple fix so that the score can be opened again, see #19708. It is a bit questionable how much sense that makes, because probably a crash will occur anyway sooner or later while working with this file, since it's simply corrupted.
I did find that the corruption _seems_ to go away when you go to the Organ part, reorder some staves in the Instruments panel, go to the full score and back to the Organ part again.

But much more importantly, I found how to reproduce this kind of corruption. It's frighteningly easy:
1. Create score with 2 instruments
2. Open 1 part score
3. Add the other instrument to that part score
4. Undo

Might actually be the same problem as #17333. Will work on a fix.
