### ISSUE TITLE
Hairpins disappearing in part scores

### ISSUE THREAD

**Issue by RedCoder09** [musescore/MuseScore#19852]
### Issue type

Engraving bug

### Bug description

When creating a score, I put hairpins in the Main score, attached to a part. But when I open said part, the hairpins seem to have disappeared.

### Steps to reproduce

Unknown.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/70098883/e3c9867e-6678-49b4-bad7-9ca57b806904
![image](https://github.com/musescore/MuseScore/assets/70098883/1cac3ccd-357c-46b7-8110-7859e2157e36)
![image](https://github.com/musescore/MuseScore/assets/70098883/faea6bbb-9db7-4a61-92f7-de8600a1f326)

### MuseScore Version

4.1.1232071203

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Go to https://musescore.org/sites/musescore.org/files/2023-10/Autumn%20Dream.mscz to find the score where this bug is happening.
Interestingly, when opening the Horn part, it thinks both the Piano and Horn are visible as well and plays it accordingly.

**Comment by oktophonie** [comment]
This is https://github.com/musescore/MuseScore/issues/16096, again.
What we really need, still, are exact reproduction steps. If I open the existing horn part in this score, then indeed the hairpins are missing. But what was the exact sequence that led to those steps?

If I reset the horn part from the parts dialog, then everything synchronises with the score and the hairpins appear.

Weirdly all the hairpins are duplicated in the score (i.e. there are two identical hairpins on top of each other, each time).

**Comment by cbjeukendrup** [comment]
When did you notice for the first time that the hairpins were gone? Was that just after opening the file? Or directly after opening the part score after that it had been closed? Or did you do anything between opening the file and going to the part score?
It might be helpful if you could share your log files. You obtain those using MuseScore via `Diagnostic` -> `Save diagnostic files`. That gives you a ZIP file that you can attach here. It would be great if you could additionally say approximately at which date/time you discovered that they were missing, so that we can look at that moment in the log files.

**Comment by RedCoder09** [comment]
I don't know exactly when I discovered that there was an issue, but I would guess around 16:00 on 28-10-23. I've attached the log file for you. As for the sequence of events leading up to this, I'll take a closer look and see if I can give reproduction steps.
[autumnnightmare.zip](https://github.com/musescore/MuseScore/files/13196241/autumnnightmare.zip)

**Comment by RedCoder09** [comment]
Wait a second, I think I might have a lead. In "MuseScore_231026_105904.log", it says the following:
![image](https://github.com/musescore/MuseScore/assets/70098883/09f46c77-d5fb-442d-ad4e-29364817250d)
I think this might be why this is happening. Could also just be a red herring, though.

**Comment by cbjeukendrup** [comment]
That seems very useful information. Meanwhile, I've also looked at the content of the mscz file, and I seem to recognise a sort of corruption that I've seen before, and of which I've fixed the root cause recently. To reproduce that corruption, you had to add an extra instrument to a part score, and then undo, i.e. add the Piano instrument to the Horn part using the Instruments panel, and then Ctrl+Z. Is there any chance that you did that? I will now try if that also allows me to reproduce the hairpins issue.

**Comment by RedCoder09** [comment]
I actually think I might have done that, yes. I'll try using the nightly build and see if that fixes it.

**Comment by cbjeukendrup** [comment]
In the nightly build, the already-disappeared hairpins won't come back, but at least that add-instrument-followed-by-undo corruption shouldn't happen anymore. It might be more useful to try if this corruption in 4.1.1 gives a way to reproduce the disappearing hairpins problem from scratch. I have no luck with that so far, but we'll see.

**Comment by cbjeukendrup** [comment]
Still no luck. I did find a quite easy way to get a single missing hairpin in a part: 
1. Create score (1 instrument is enough)
2. Write notes
3. Add hairpin, not aligned to measures
4. Open part
5. In the part, clear the notes from a measure that overlaps with the hairpin
6. Save and reopen -> hairpin is gone in part

But this cannot be the cause of the problem in your score, because
- it doesn't cause `doesn't have an endpoint!` to be printed to the logs
- the hairpins in your score _are_ measure-aligned

**Comment by RedCoder09** [comment]
Thank you for figuring that out, should I add it as a step guide for my original post?

**Comment by cbjeukendrup** [comment]
I will instead create a new issue for that, since it's almost certainly unrelated.

By the way, by now I think that it doesn't have to do with the add-instrument-followed-by-undo corruption, and that it's just a coincidence that this file contains both problems. I've namely found another score on the forum that does have the hairpin issue but not the corruption.

**Comment by RedCoder09** [comment]
Ah, so the corruption was unrelated. That's good to know, at least. Thank you for creating another issue for that.

**Comment by NicolaRulli** [comment]
"hairpin doesn't have an endpoint" sounds familiar - I remember distinctly once having placed a harpin between dynamics (and it snapping to them), then finding it going past the intended endpoint dynamic. And it might have been one that had disappeared upon first opening of the part and I had restored via copy paste. I think the two phenomena might be related.
