### ISSUE TITLE
CRITICAL: Unsafe Use of memcpy Allows Buffer Overflow in stb_vorbis.c

### ISSUE THREAD

**Issue by DawmosTomie** [musescore/MuseScore#19863]
### Issue type

Other type of issue

### Bug description

The size limit is larger than the destination buffer, while the source is a char* and so, could allow a buffer overflow to take place.
Line: 2303 - Filename: MuseScore\thirdparty\stb\stb_vorbis.c
memcpy(x, buffer, sizeof(*x) * n2);

### Steps to reproduce

1.Filename: MuseScore\thirdparty\stb\stb_vorbis.c
2.Line: 2303

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

windows 10

**Comment by cbjeukendrup** [comment]
I see the compiler warning every day, but unfortunately we can't really change it because it's 3rdparty code. However, it looks like there is an updated version available so perhaps they fixed it. Will try that.

**Comment by cbjeukendrup** [comment]
It turns out that this code lives inside a `#elif 0` block, so is never compiled at all. 
So that compiler warning that I was seeing must be for a different issue :)

Also, I looked at the latest version of the file, from https://github.com/nothings/stb/blob/master/stb_vorbis.c, but there are no changes related to this issue. 

But anyway, since this is an issue in third party code that is never compiled, let alone run, I think it can be closed.
