### ISSUE TITLE
Graphical glitch with bend arrowhead during playback

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19885]
### Issue type

UI bug

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/90187801/c0cf11f3-cf95-4e2d-a769-13229728279c

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

Windows 10

**Comment by oktophonie** [comment]
See also: https://github.com/musescore/MuseScore/issues/19924

**Comment by mike-spa** [comment]
I can't reproduce this on my machine, unfortunately. If someone can find more detailed steps to cause this, please let me know

**Comment by cbjeukendrup** [comment]
I've found the cause of this issue: 
- As an optimisation, when the playback cursor is moved, not the entire screen is redrawn, but only the rectangle of the old position of the cursor, united with the rectangle of the new position of the cursor.
- When redrawing only a part of the screen, only those elements that overlap with that part are considered for redrawing. Those elements are collected based on the "BSP Tree" of the Page on which they are, and this selection is based on whether the BBox overlaps with the rect to be redrawn.
- The parts of the elements affected by this issue are exactly the parts that are outside the BBox of the element. In this video, where I've made the BBoxes visible, the part of the bend (which is awfully deformed to demonstrate the effect) as well as the white backgrounds of the TAB numbers are erased:

    https://github.com/musescore/MuseScore/assets/48658420/4f224131-4ce9-49d0-8258-cb2232174b3d


So, the "erasing" effect happens because when the area where the cursor has just moved away is being redrawn, the bend (or other element) on that position is not considered as being part of that area, so is not redrawn when redrawing that area; and it is caused by the BBox being calculated incorrectly.

Especially the case of the TAB numbers background makes me wonder about something: it looks like we actually need two bounding boxes, one for layout purposes (which is generated based on the Shape) and another one for redrawing purposes (and another one for clickable area?? but I believe we already have that). For those TAB numbers, the layout should only consider the number itself, as it does currently, but for redrawing, the bounding box of the background must also be considered.

Anyway, @mike-spa this seems to bring this issue back to the Engraving team :)

**Comment by mike-spa** [comment]
@cbjeukendrup thanks so much. I've made a quick fix for bends which fixes the most obvious issue (half of the arrow was being left out of the bounding box). The "erasing" will still happen if one deforms the curve like you did there, but in no real world case can the curve of the bend end up further right than the edge of the arrow, so we'll take it for now. In future, it may be worth doing a more serious refinement of the bend Shape (i.e. break it down into more rectangles). I believe someone also complained about the clickable area being too large.

Having said all that: your investigation doesn't explain the disappearing tuplets from the referred issue. If anyone can reproduce that, let me know

**Comment by cbjeukendrup** [comment]
> your investigation doesn't explain the disappearing tuplets from the referred issue.

True. I could not reproduce that issue, and wouldn't have any explanation for it so far.

**Comment by DmitryArefiev** [comment]
Fixed in #20322
