### ISSUE TITLE
articulations not placed properly on notes below staff lines with flipped beam

### ISSUE THREAD

**Issue by WhateverAWS** [musescore/MuseScore#20065]
### Issue type

Engraving bug

### Bug description

Articulations stuck on the staff lines no matter how far down the notes are. This happens with any articulations isolated or mixed.

### Steps to reproduce

1. Put beamed note below staff line
2. Place articulations on the note
3. Flip the beam

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/151141957/02d1763c-3048-452d-a8be-1a70344eab68)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
This is by design.
If you want those markings that can to stay close to the note, that's what the option Style > Articulations & ornaments > Combined articulation > Prefer closeness to notehead is for:
![image](https://github.com/musescore/MuseScore/assets/20604032/80085be8-aa27-48cb-98b7-e0b1fe4ba1b6)
