### ISSUE TITLE
MuseScore4.1.1 will not run on macOS

### ISSUE THREAD

**Issue by JDexterus** [musescore/MuseScore#20089]
### Issue type

Crash or freeze

### Bug description

MuseScore 4.1.1 produces only a crash report when trying to open it.

I have completely uninstalled MuseScore 4.1.1 and as many supporting system files as I could find. Did a new installation and still will not run.

MuseScore 4.0 used to run on this Mac M1 Mini, but always generated a crash report whenever I closed the program.  

I updated my system software from MacOS 13.6 to 14.1 but the inability to run MuseScore 4+ continues.  MuseScore 3.6 runs perfectly.  Crash reports using both systems are attached, below.

### Steps to reproduce

(on a Mac M1 Mini)
1. Open Applications
2. Select MuseScore 4 Icon and double-click
3. After a moment, Apple's crash report pops up, is sent to Apple, and the text of it appears onscreen.

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Both Mac OS Ventura (13.6) and Mac OS Sonoma (14.1)

### Additional context

Crash Report generated from MacOS 13.6 (Ventura)
[Musescore Crash Report.txt](https://github.com/musescore/MuseScore/files/13401709/Musescore.Crash.Report.txt)

Crash Report generated from MacOS 14.1 (Sonoma)
[MuseScore4.1.1 Crash Report.txt](https://github.com/musescore/MuseScore/files/13401714/MuseScore4.1.1.Crash.Report.txt)

**Comment by zacjansheski** [comment]
I did a clean install of 4.1.1 with and without MuseHub without issue on macOS (14.1.1). No issues on my end.
This seems to be system specific.
@JDexterus if you have any additional info to help us reproduce, please share.
@cbjeukendrup please check crash reports for additional information.

**Comment by cbjeukendrup** [comment]
Some things I found in the crash reports: 
- They are completely different, and it seems impossible they are related; so either one problem got solved but another problem came in its place, or something is just completely flaky. Would be good to try a few times, look at the crash reports, and check if they are similar to these ones (similar as in: which thread crashed, and what is its stack trace, i.e. those numbered lines following the thread name)
- The macOS 13.6 one crashes due to a graphics error on the main thread; quite deep inside macOS and Qt, so most likely outside our control
- The macOS 14.1.1 one crashes in a Muse Sounds thread inside a call to `ms_InstrumentList_get_next`; there is not really any more info than that

@JDexterus It might be interesting to look at the log files; you can find them in `~/Library/Application Support/MuseScore/MuseScore4/logs` (to get there, open Finder, press Cmd+Shift+G, enter that path and press Return). Please upload the content of that folder here

**Comment by JDexterus** [comment]
Thanks so much.  I dug deeply and deleted everything I could find related to Musescore and MuseHub.  I must have reached the problem file as, when reinstalling everything, it now works. You guys are very much appreciated..
Jack

**Comment by cbjeukendrup** [comment]
@JDexterus Glad to hear that! 
Since this is to my knowledge the only report of not being able to start MuseScore on macOS, I think you've experienced just an unlucky coincidence that caused this... Investigating further what might have happened exactly would likely be cumbersome and not lead to much result; therefore I propose to close this issue. I hope that's okay. 
However, if the problem comes back or you have additional information, please let us know!

**Comment by JDexterus** [comment]
The boot up problem has recurred. I thought it was a quirk, because I had just tried to save a file, which MuseScore ID'd as corrupted.  I cleaned up the corrupted measure (never could see the extra 8th note it said was there), and then saved the file. I then resumed work in a text program, with MuseScore running in the background.

MuseScore suddenly crashed (in the background) and generated a crash report (auto-sent to Apple). After that it never has reopened.  I once again cleared out as many MuseScore system files as I could find, reinstalled using MuseHub (result: startup crash), cleaned out all files again, and installed directly from the website.  The program refuses to open despite clean installs.  Attached is the Apple crash report. 
Thanks.
[Musescore4 Crash Report.txt](https://github.com/musescore/MuseScore/files/13605292/Musescore4.Crash.Report.txt)

**Comment by cbjeukendrup** [comment]
The crash report looks similar to the report from macOS 14.1 you initially uploaded: it crashes somewhere in the MuseSampler library. 

I suggest deleting the library file; it can be found in `/usr/local/lib/libMuseSamplerCoreLib.dylib` (you can get there using Finder by pressing Cmd+Shift+G and typing `/usr/local/lib`). 
Then, MuseScore will detect that it's not there, and will not care about it.

If you want to use Muse Sounds again, then you'd need to uninstall one of your Muse Sounds sound packs and reinstall it, to trigger Muse Hub to re-install the MuseSampler library. Hopefully, it will then give you a version that does not crash.

**Comment by JDexterus** [comment]
Thanks for the quick response.  I uninstalled MuseHub and its library, reinstalled it, and now MuseScore works again...so that appears to be the core of the problem.  However the library file you refer to (libMuseSamplerCoreLib.dylib) is not included anywhere in my Mac OS 14.1.2 system files, even though it is identified in the crash report.  I can't find any file referring to MuseSampler on my computer.  I have no idea what it is.

If the MuseHub instrument files location is what you are referring to, their default installation location on my Mac Mini is:   users/username/library/containers/Muse Hub/Data/InstallData/Instruments

I have made sure to add that file location in the MuseScore4 Preferences for soundfont folder. However, that location is not what shows up as the default for MuseScore4.  The MuseScore default location is /users/username/Documents/MuseScore4/Soundfonts (which is empty).  Hopefully this helps identify the problem.   Thanks again....

**Comment by cbjeukendrup** [comment]
Muse Sounds instruments are indeed stored in `~/Library/containers/Muse Hub/Data/InstallData/Instruments`. But this folder contains only _data_, and no 'instructions' that your computer can 'execute' in order to produce sound from that data. So to bring the sounds to life, there is MuseSampler, which is a "library" in the meaning of "a set of instructions that a program like MuseScore can load and execute". 

So, MuseScore loads MuseSampler, and tells it to produce sound, based on the data in `~/Library/containers/Muse Hub/Data/InstallData/Instruments`.
It's similar to some VST plugins, for example with Kontakt or HALion: you can download sound data for these VST plugins in a lot of places, and then you need the VST plugin itself in order to actually produce sound from that data.

Because MuseSampler is closed source and MuseScore open source, it was not possible to package MuseSampler with MuseScore, so it needs to be installed separately by Muse Hub.  
It is installed to `/usr/local/lib/libMuseSamplerCoreLib.dylib`. (Note that `/usr` is a different folder than `/Users`, and that Finder does not expose it by default; you can only find it by using Cmd+Shift+G or after pressing Cmd+Shift+dot (which reveals hidden files).)

The "SoundFonts" option in MuseScore's Preferences is unrelated: SoundFont is a different playback technology that MuseScore also supports. SoundFonts are `.sf2` or `.sf3` files containing sounds; using the option in Preferences, you can tell MuseScore where to look for such files.
