### ISSUE TITLE
Corrupted file 

### ISSUE THREAD

**Issue by literallyjustbeeb** [musescore/MuseScore#20118]
### Issue type

File corruption

### Bug description

I am writing an arrangement of Liebestraum no.3 for Wind Ensemble and while trying to save the file it appeared that it had became corrupted, i made a copy of the file and saved to the latest save, but it now says this whenever i try to save or close musescore (see image)

While it seems to be working fine it frightens me to lose all my progress as this is a very important project i am working on, attached is the corrupted file.

### Steps to reproduce

1. open corrupt file
2. try to save or close
3. corrupt screen

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/84479717/8988f570-0022-4041-8616-dd5ff09097e2)

[Liebestraum_WID_ENSEMBLE.mscz.zip](https://github.com/musescore/MuseScore/files/13421097/Liebestraum_WID_ENSEMBLE.mscz.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
Thanks for the report! I investigated the file, and there was indeed a problem in measure 54; for some instruments, the first dotted half note of the measure had become a dotted whole note, making the measure too full (9/4 in total instead of 6/4).

Unfortunately, as so often with corruptions, without more information there is no way to tell how the corruption happened (i.e. nobody knows steps to reliably reproduce the corruption from a non-corrupted score as a starting point), so we have no way to investigate _why_ it happens and how to prevent it in the future. Eventually, it will either get fixed by chance (possibly without anyone knowing), or someone will figure out how to reproduce it. But this is really a matter of luck. Fortunately, corruptions like this are not common. 

For these reasons, I will close this issue, but not before providing you with a manually fixed version of the score, as a Christmas gift :)
[Liebestraum_WID_ENSEMBLE_uncorrupted.mscz.zip](https://github.com/musescore/MuseScore/files/13767704/Liebestraum_WID_ENSEMBLE_uncorrupted.mscz.zip)
Make sure to check if the notes in measure 54 are still correct. I hope this helps!

**Comment by cbjeukendrup** [comment]
One more thing: at least in this case, an effective way to fix the corruption is to erase and re-notate the measures in question, in case you ever encounter another one like this.
