### ISSUE TITLE
Bends: need to allow user to correct errors after the bend goes into the red

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20132]
### Issue type

UX/Interaction bug (incorrect behavior)

### Bug description

After applying bends it is possible to go back and edit them. Some of these edits make sense, others don't. Please open the attached MS4 file.
[bend_adjustment.zip](https://github.com/musescore/MuseScore/files/13428650/bend_adjustment.zip)

For example, in the attached file, in the tab staff, it is possible to use the up/down arrow once (normal mode) to change the parenthesized fretmarks. This leads to an error/meaningless result which cannot be put right except by UNDO.

![tab_bend_triplets](https://github.com/musescore/MuseScore/assets/87246583/d81a0cb5-5a13-4ca3-8ca0-100d284d3e4c)

AFAICS, this action should be disallowed.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233250304, revision: github-musescore-musescore-fbe370a

### Regression

N/A

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment]
Yeah I think this makes sense, although looking into this has made me realise an interesting problem: that of being unable to correct the release pitch using only the tablature stave in a situation where one of these errors occurs. Rather than disallow the user to change the parenthesized fretmarks, I think we should either: 

- Automatically correct the release pitch when the starting pitch is adjusted in the tablature, so that the release isn't drawn as an error, OR
- Actually allow the user to adjust the release pitch in the tablature so that they can correct the error themselves

I expect [this video](https://www.dropbox.com/s/3qbh10ms9ep498n/bend-release-issue.mov?dl=0) will make more sense than my explanation:

**Comment by rgreen5** [comment]
Amended title.

**Comment by mike-spa** [comment]
A quick note: the fret at the end of a bend _must_ be always set to the same number as the start of the bend, that's just how bends work. Not doing that would result in wrong notation.

> * Actually allow the user to adjust the release pitch in the tablature so that they can correct the error themselves

This is the solution I'm going to do :)
