### ISSUE TITLE
3rd Party VST doing weird

### ISSUE THREAD

**Issue by YourOldPalTim** [musescore/MuseScore#20205]
### Issue type

VST bug

### Bug description

I'm using Crenona Quartet from N/I and it is doing a few weird things.  First off it will randomly grab a note and play it forever, even outside of playback, when I have clicked on nothing at all.  Second it will randomly grab a note and refuse to let go DURING playback.  Third, and this one I admit needs more testing on my end, it will start to play notes a half step down and then slide up to the note, for each and every note.  

### Steps to reproduce

1 go to https://www.native-instruments.com/en/products/komplete/cinematic/cremona-quartet/ 
2 purchase the quartet, 
3 install
4 set up your play back to be using kontact 7 running the quartet
5 ???
6 profit?

### MuseScore Version

4.1.1.232071203

### Regression

I don't know

### Operating system

Mac os Montery 

### Additional context

I have recently purchased the Cremona quartet VST and this is my first set of experiments with it.  
I also recently purchased a Focusrite Scarlet 4i4 which is also new to my set up. Doubt it is the problem but never know.

**Comment by zacjansheski** [comment]
Could you confirm if this is an issue in the current master/nightly?

**Comment by YourOldPalTim** [comment]
Hello Zac,

in the current master/nightly? I don't know what you mean by that.  Do you
mean does the issue happen just on the master bus? no it is channel based.
I have no idea what you might mean by nightly.

Cheers
-Tim

**Comment by ShibuyaCyana** [comment]
well, AFAIK:

There's an little exclamation mark in the right top corner of Kontakt; click it, and it should stop these indefinitely playing notes, for this instance of the plugin, at least temporarily.
And I have to say it's not a very good choice to use MuseScore and Kontakt together. These libraries are designed to be used in DAWs, with probably half a dozen of painstakingly hand drawn control message curves, to make the sound you hear in demo. For now it's better to simply ignore VST - especially VSTi (instrument) support, and use MS Basic with MuseSound instead. In the future it's possible if someone write a plugin dedicated for this library to make it respond to all the expression marks and articulations, but for the aforementioned reason, I'm afraid it still won't sound as good as MuseSound.

If you're willing to read more: 

this kind of problem is referred as "hanging notes"; just google this word and you'll see how common it is, from hardware to software, stages to studios, and from 1980s to now. It's almost unavoidable - partially thanks to the MIDI protocol being real-time - but the combination of MuseScore & Kontakt would only make it worse: the former one is using its own playback engine rather than MIDI, which means your score data will be handled by a conversion engine in real time prior to being sent to Kontakt; and the later one is using an complex inline script system to handle all kinds of convoluted sample playback, which - let me be direct - is simply prone to be buggy, at least more than other VSTs.

From my experience, MuseScore does hang notes more often than others; there could be some improvement, like sending `all note off` messages when playback is stopped (this is how most DAWs behave), but I believe it couldn't be problem free; this _will_ happen now and then.

And for the sliding note problem: I didn't find any articulation that starts with a slide up in this library, so I would guess it's just triggering the portamento articulation somehow, maybe from the high velocity range of the default "virtuoso" articulation, or accidentally setting legato mode to portamento.

**Comment by YourOldPalTim** [comment]
Shibuya Cyana,

Thank you so much for this in depth response.  the ! note has been getting
me through my day, slowly but through it.  I will avoid using VST's with
Muse Score going forward but as I was approaching a final version of my
score I wanted to hear it with those VST's.  Guess I'll have to port it
over to my Daw and spend some time with it there.

Cheers
-T

**Comment by YourOldPalTim** [comment]
I swapped back to its MSBasic sounds and it cleaned up all my issues.I’ll look into the muse sounds. I think I’m already using them but I haven’t checked to see if there have been any updates since I originally grabbed them.  Just finished my string quartet this evening. (Yay!) I’ll export it to my daw and use Kontact and the VST’s there. Hopefully I can get a finished product by end of year. I appreciate the help and support. If I run into any solutions (or further issues) in the future I’ll send them your wayCheers-tOn Nov 30, 2023, at 17:15, ShibuyaCyana ***@***.***> wrote:﻿
You're welcome.
I'm kinda surprised you really continued with Kontakt; in that case maybe try to play that hanging note on your MIDI keyboard, or click on the same note on score, or just write one and delete it, as this may solve the problem without opening Kontakt interface.
Also be sure to check out MuseSound, it's free and sounds incredible for things like string quartet, and will respond to dynamics and many other expression marks on your score. And it doesn't hang, at least not often : )
Here's a random demo of a MuseSound string quartet (not by me):
https://www.youtube.com/watch?v=OE2TvboM5ic
Just download MuseHub then download MuseSound from it, there's no hassle like registration or so.

**Comment by cbjeukendrup** [comment]
It would be appreciated if long support discussions could stay in the forums on MuseScore.org, so that we can keep GitHub very to-the-point and developers can quickly get the info they need without having to read through long discussions.

So, it seems the question above has not been answered yet: (https://github.com/musescore/MuseScore/issues/20205#issuecomment-1828149814)
*Does this issue still occur in the latest development build?* You can download this development build from https://musescore.org/en/nightly-builds. This page includes some info about how to download and run these builds; and if needed, some slightly more detailed info may be found here: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds

**Comment by ShibuyaCyana** [comment]
at least part of the problem: #19254

**Comment by zacjansheski** [comment]
We will refer to https://github.com/musescore/MuseScore/issues/19254 moving forward
