### ISSUE TITLE
Newly installed Muse Sounds don't replace MS Basic for existing instruments in existing scores

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#20236]
### Issue type

Muse Sounds bug

### Bug description

Not sure if this is a bug or expected behaviour.

If a score is created using MS Basic as the default sound, then a suitable Muse Sound is subsequently installed, should the existing instruments in that score automatically switch to using Muse Sounds?

Currently, existing instrument stay with MS Basic, but any newly added instruments will use Muse Sounds.

### Steps to reproduce

1. Launch **Muse Hub** and...
    1. **Uninstall** the Muse Harp sound.
    2. Make sure at least one other Muse Sounds library is **installed** (e.g. Muse Keys).

2. Launch **MuseScore**, create an empty score, and...
    1. Go to _View > Playback setup_.
    2. Ensure Muse Sounds is the active profile and set as the default for new scores.
    3. Close this score without saving.

3. Create another score, this time with a Harp instrument.
    1. Do not change any playback settings for this instrument or score. The harp should use MS Basic by default, but do not explicitly choose MS Basic in the Mixer.
    2. Save the score somewhere and exit MuseScore.

4. Launch **Muse Hub** again and install the Muse Harp sound.
5. Launch **MuseScore** again and open the score with the harp instrument.

The existing harp will still use MS Basic, but if you add another harp instrument it will use Muse Sounds.

### MuseScore Version

Latest nightly (master)

### Regression

I don't know

### Operating system

Windows 11

**Comment by avvvvve** [comment]
I think this is the expected behavior. I don't think we should automatically override any sound selections users have saved to existing files, especially with automation and sound flags coming down the line which can be overridden by swapping sounds.

We'll be adding a reset button for edited playback profiles to the Playback setup dialog soon enough (in #19845). This should, in a couple clicks, "refresh" the mixer with any newly installed Muse Sounds.

We could take it a step further:
If Muse Sounds is the activate profile in an exisitng score, we could run a check when opening it to see if there have been new Muse Sounds installed for instruments that are set to MS Basic. If there are, we could pop a message telling users new sounds are available.
Figma does this in a nice non-instrusive, way by popping a small, easily dismissed message in the bottom right corner of the window when there are updates to components available. 
<img width="482" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/216421d0-7d74-4358-af36-e9ce32653ead">

**Comment by shoogle** [comment]
Yes, I agree the current behaviour is the best compromise. The user created their score with MS Basic, so if we suddenly switch existing instruments over the Muse Sounds the balance might be wrong, or the notes might go out of range of the Muse Sound.

The user might open their score just to export an MP3, email it to someone as a demo, and not notice that all the instruments have changed until it's too late. So the safest option is to stick with MS Basic for existing instruments and allow the user to change it if they want to.

However, if the user adds a new instrument to their score, we can safely use Muse Sounds for the new instrument. The new instrument will affect the balance either way, so the user will have to listen to the score before they export it and switch the new instrument over to MS Basic if they really want to.

I like the idea of a notification when a score is not using Muse Sounds but a suitable sound is available.
