### ISSUE TITLE
Crash after deleting linked tab staff with guitar bend

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#20422]
### Issue type

Crash or freeze

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/90187801/83e79f50-0fd4-4db9-b12d-ff3a6f851cf3

### MuseScore Version

4.2

### Regression

Yes, this used to work in MuseScore 4.1.1 (with an old bend)

### Operating system

Windows10

**Comment by cbjeukendrup** [comment]
@mike-spa I did some investigation in case its helpful:
- When removing the staff, all elements on it are removed
- When removing the bend, the FRET property of the note is modified in https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/score.cpp#L1649
- After that (or possible before, idk), the note is removed
- Finally the staff itself is removed from the score
- After the whole operation, the `ChangesInfo` is collected 
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/undo.cpp#L648
by checking each subcommand's `objectItems`
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/undo.cpp#L663
Including those of the `ChangeProperty` for changing the FRET property of the now-removed note from the now-removed staff
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/undo.cpp#L2577-L2580
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/undo.cpp#L91
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/note.cpp#L584
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/note.cpp#L602
Below, staffIdx() is the staff index of the now-removed note/chord, but the staff corresponding to that index has been removed
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/chordrest.cpp#L434-L437
So below is where it goes wrong, because trying to retrieve the removed staff by its index results in a `nullptr` Staff, but we still try to do things with it, which leads to a crash at some point
https://github.com/musescore/MuseScore/blob/50ae319023598364898b26e2e2d41eac65b3e89b/src/engraving/dom/measure.cpp#L1882-L1886

Possible solutions:
- Don't use undoChangeProperty but just set the fret directly? (because when undoing, the re-addition of the bend should already cause the fret change to be effectively undone? I don't know if that's actually the case)
- Create a way for UndoCommand to specify that some elements should be ignored even if other UndoCommands specify them as their object items, and then use that for `RemoveElement` (maybe not great)
- Ad hoc checking for nullptrs or other unexpected things in one or more of the places mentioned above

**Comment by mike-spa** [comment]
@cbjeukendrup thanks so much, your first solution seems to work perfectly
