### ISSUE TITLE
Musescore not opening on Hyprland Linux

### ISSUE THREAD

**Issue by leumaswein** [musescore/MuseScore#20499]
### Issue type

Accessibility issue (e.g. for keyboard-only or screen reader users)

### Bug description

![Screenshot_2023-12-14-23-31-37_8733](https://github.com/musescore/MuseScore/assets/153871315/4388a34c-c3a6-47d9-a6ea-2f09d34f815c)

I'v installed hyprland and now I cannot load Musescore. Before it was ok on Sway (wayland). Pleas help, I am stuck...

### Steps to reproduce

1. install hyprland on garuda sway
2. launch musescore

### MuseScore Version

4

### Regression

No.

### Operating system

Garuda Sway with Hyprland

**Comment by MarcSabatella** [comment]
Is this the official AppImage, or a third-party build?  Seems like it might be the latter - "mscore" isn't a proper command name for the installed AppImage, and I don't see a build number in the log.  Those third-party builds are often problematic.  Please try it with the official AppImage.

**Comment by zacjansheski** [comment]
Closing as stale / no response

**Comment by alejoguitar** [comment]
I'm having the same issue on NixOS hyprland. First with the NixOS package which is based on the Appimage. Now with the appimage itself

**Comment by alejoguitar** [comment]
Some progress on my end: sometimes I get musescore to work. I'm quite motivated because, frankly, without this I just can't work...

one of the errors complains about the qt_qpa_platform, so, trough some googling I  realized problem might be there. 
The flatpak app sometimes work. Some days, it's the appimage. I uninstalled the NixOS package. But starting musescore trough the comand line works pretty consistenly on the flatpak version when prepending `QT_QPA_PLATFORM=wayland`
So, for me, the full command is `QT_QPA_PLATFORM=wayland flatpak run org. musescore.MuseScore`

That same variable is set to "wayland" on my config, something which is quite standard to any wayland config. So, I'm guessing this is one of the annoyances coming from Wayland. 
I know we Linux users are a small portion of Mscore users, but I really hope the open source gods will ask you to consider doing something with this info... thanks in advance!

**Comment by cbjeukendrup** [comment]
We can only really comment about the AppImage, and not about the FlatPak because that is not made by us. 

In the 4.2 and 4.3 AppImage, we excluded the Wayland libraries (https://github.com/musescore/MuseScore/pull/20391). The reason: without these libraries, MuseScore should fallback automatically to `xcb` (or whatever it's called) which worked at least to some extent. _With_ the Wayland libraries, MuseScore would completely fail to launch (https://github.com/musescore/MuseScore/issues/18598). That issue is closed, but superseded by https://github.com/musescore/MuseScore/issues/24068. 

Since recently, there is some hope, see the bottom of #24068. It looks like if we do package Qt's Wayland plugin, and _not_ package some Wayland library so that the system library gets used, it might work.

**Comment by cbjeukendrup** [comment]
There is a good chance that this fixed in 4.4 (RC downloadable at https://musescore.org/en/node/367322). 

The Wayland platform plugin is packaged with the AppImage again, _and_ the crash that happened with it (that was the reason for not packaging it in 4.2 and 4.3) was fixed in https://github.com/musescore/MuseScore/pull/24111. 

Could you please try it out and let us know your findings? Thanks!

**Comment by alejoguitar** [comment]
Yes! It worked OOTB. 
Not only that, but everything looks sharp as it's supposed. I sort of got used to the XWayland version that looked a little blurry. Now I'm amazed by the beauty of MuseScore. 
I'll keep using this build and report if I find some other problems, but, as far as "Musescore not opening on Hyprland Linux", I think this can be closed as "solved". Thanks very much!

**Comment by cbjeukendrup** [comment]
Thanks for testing! I'll close this indeed, and if you find new issues you're welcome to report them.
