### ISSUE TITLE
MuseScore Freezes After Arpeggio is altered by Timesig change + Delete

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20492]
### Issue type

Crash or freeze

### Bug description

After writing a tied arpeggio, then changing the time signature, then deleting, MuseScore freezes.

### Steps to reproduce

1. Open "Treble Clef" template
2. Write a chord that lasts a whole note
3. Add an arpeggio
4. Change the time signature at the beginning to 3/8 (note "values" are recalculated)
5. Delete the measures
6. MuseScore freezes

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/f57d60f0-3b11-45df-878c-19b2e728b3da

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233471824, revision: github-musescore-musescore-21cfc4e

### Regression

I don't know

### Operating system

Mac OS 14

### Additional context

Diagnostic file

[ArpegTimeSigDeleteFreeze.zip](https://github.com/musescore/MuseScore/files/13677182/ArpegTimeSigDeleteFreeze.zip)

**Comment by zacjansheski** [comment]
This is a regression on 4.1.1

**Comment by RomanPudashkin** [comment]
@miiizen it was broken in [this commit](https://github.com/musescore/MuseScore/commit/8254462fe71bd7a5343c61c389ce4bdda3c22941). We get an infinitive loop because of curTrack (it's unsigned and -2 gives us the maximum value of the type)
![Screenshot 2023-12-15 at 10 22 11 AM](https://github.com/musescore/MuseScore/assets/67867444/090e5b58-ca45-4f6d-9931-33c653186e21)
