### ISSUE TITLE
Check for Update not Working

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#20553]
### Issue type

Other type of issue

### Bug description

The Check for Update feature is failing to recognize MuseScore 4.2 is available.

### Steps to reproduce

Go to _Help>Check for Update_ in the top menu bar

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102642087/e3dec5c2-0062-44f6-b9eb-a28e43df67f4

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
At this moment that is intentional. It's a bit of a safety measure: we don't want to immediately push the update through all channels, just in case anything critical comes up among the early adopters. 

(That's the reasoning at least; there is doubtlessly a lot of things that can be said against that, or even-better-but-also-more-complicated things that could be done.)
