### ISSUE TITLE
Incorrect alignment of simultaneous notes in multiple voices

### ISSUE THREAD

**Issue by irwir** [musescore/MuseScore#20571]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Create a new score and enter a "chord" of three notes with different duration (expecting heads to be at the same vertical line):

### Steps to reproduce

1 New score
2 Strings - Bowed
3 Violin
4 Done
Now entering notes:
5 Voice 1, quarter C6
6 Voice 2, half C5
7 Voice 3, full C4 (middle C)

At that moment C6 and C4 are moved right, C5 stays, so the alignment is broken.
Alignment is also broken if both stems were down - C4 remains shifted to the right.
The only way to get heads aligned is to set both stems up.

### MuseScore Version

4.2.0

### Regression

No

### Operating system

Windows 11

**Comment by sammik** [comment]
I think, it is by design, 
as this:
![voices1](https://github.com/musescore/MuseScore/assets/1646034/4c732dcb-e10e-47de-8ac1-139a686aaacf)
looks better, than this:
![voices2](https://github.com/musescore/MuseScore/assets/1646034/dffa81f2-3412-4b8c-88d9-d6a7939c4b47)
in my opinion

**Comment by oktophonie** [comment]
It is indeed by design: voices with stems up (voices 1 and 3 normally, but other voices too if you manually flip them) will align with each other, right-aligning to the position of the downward stem, and down-stem voices (2 and 4) do the opposite. And voices with the same stem direction won't avoid collisions with each other (unless you put them a second apart), but will avoid collisions with voices of the opposite stem direction.

You can see the difference in your example if you move the whole note from voice 3 to 4, or flip the middle half note, etc.

**Comment by irwir** [comment]
> I think, it is by design, as this:

Would it be correct to guess that you did not even try to reproduce the given actions?
In my example C6 has stem up, C5 has stem down; and it looks unpleasantly misalingned.

**Comment by irwir** [comment]
> It is indeed by design: voices with stems up (voices 1 and 3 normally

Voice 1 starts with stem down, and it was flipped automatically when voice 2 note was entered.
And ` by design` argument might need another consideration.
Both PriMus and SIbelius 2023.5.1 with the same set of tones and voices showed all three notes perfectly aligned.

**Comment by sammik** [comment]
Ah, sorry, I didnt realised, that bottom note is whole (without stems).

So it may be valid point to think about, if stemless notes should affect layout as if the were stemness.


https://github.com/musescore/MuseScore/assets/1646034/9327e24f-57cb-455a-b252-aaadcc83d199

@oktophonie ?

P.S. @irwir please, it would be great, if you could post a video, or image next time, so distracted people, like me, wouldnt miss a point

**Comment by irwir** [comment]
@sammik
Thanks for the video; now I know that whole notes have stems with flippable direction. :)
This gives a better workaround for my alignment issue.
Still would prefer this to be fully automatic as in other notation programs.

**Comment by irwir** [comment]
@oktophonie,
As said above, two other notation programs were able to align notes without any extra actions.

Maybe this issue could be added to the list of furure improvemnts - instead of being simply closed?

**Comment by oktophonie** [comment]
The "other notation programs" operate according to different logic.

If you want to change the logic in MuseScore, please open a feature request and describe in detail how you'd expect it work in different circumstances.

**Comment by irwir** [comment]
> The "other notation programs" operate according to different logic.

Different logic? Different code, but the logic in notation programs is expected to follow common engraving rules and practices.
In this particular case nothing forbids automatic alignment of three notes so that centers of all heads were on one vertical line.

This issue will be copied as a feature request if you prefer so.

**Comment by MarcSabatella** [comment]
Yes, in *some* situations it makes sense to align the notes.  In *other* cases - like the ones shown - it most definitely does not.  The "common engraving rules" absolutely call for notes to be offset in many situations, even if there also exist situations where they shouldn't be.  What is needed is an easy option to specify either behavior on a case-by-case basis.  I'd recommend updating your feature request to clarify this.

**Comment by irwir** [comment]
@MarcSabatella 

> The "common engraving rules" absolutely call for notes to be offset in many situations, even if there also exist situations where they shouldn't be. What is needed is an easy option to specify either behavior on a case-by-case basis. I'd recommend updating your feature request to clarify this.

It was not my idea to turn a relatively minor and specific issue into a general feature request.
MuseScore usually aligns notes nicely, and there was no intention to review the whole "Placement of note heads and accidentals" part from "Standard music notation practice" (could be easily found in the net).
Could you please explain what needs to be clarified?

**Comment by MarcSabatella** [comment]
The whole problem here is that it *is* a general issue - figuring out which cases should offset the notes and which cases shouldn't.  Right now the algorithm is pretty simple: same stem directions align, opposite stem directions offset.  It's a pretty good rule of thumb in many cases, but plenty of room for improvement.  It sounded like you were implying you had some design insight into how to refine that the algorithm based on your professional engraving experiences, and I'm pretty sure that is what you were being invited to share in a feature request.  But I don't see that you have provided any sort of description of proposed algorithm to differente the cases.

Personally, I'm skeptical that any algorithm could ever guess correctly 100% of the time, so to me a better solution is just to continue to do "pretty well" at guessing but also add an explicit override.

I'm commenting here rather than in that issue because it makes more sense keep that issue "clean", with just the proposal itself - once a concrete proposal is developed.  If you'd like to discuss potential design ideas - either for improvements to the algorithm that decides what to align and what not to, or for controls over that alignment - the better place is the Feature Request forum on musescore.org.  Then if a consensus develops, you could update your feature request to describe it in more detail.

**Comment by MarcSabatella** [comment]
So, again, the trick is to define what "this specific case" actually means.  Surely you don't mean, add special casing to the code to handle the exact combination of those three specific pitches with those specific durations in those specific voices?  Instead, there would need to be a *rule* that is followed to cover that case.  One such rule was alluded to in a previous comment - to treat whole notes as "wild cards" in which they don't affect alignment regardless of stem direction.  That might seem plausible, but you'd also need to study a lot of examples to see if following such a rule would negatively impact other cases.

**Comment by irwir** [comment]
There are endless possibilities and maybe even a simple solution to the problem.
People who will be changing the code may also decide on the necessity of forum discussions.
