### ISSUE TITLE
Rhythm mode always plays back the note

### ISSUE THREAD

**Issue by KnightOfSPUD** [musescore/MuseScore#20721]
### Issue type

General playback bug

### Bug description

When entering notes in Rhythm mode, it always plays back the note. This also includes toggling the dot. It would be nice to enable or disable playback of notes at least in rhythm mode since the pitch of the note would not matter in my workflow of transcribing music.

### Steps to reproduce

1. Go into Note input (Rhythm only)
2. Click on any of the note durations or use any of the duration shortcuts
3. This also applies to toggling the dotted note mode.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

### Additional context

I don't know if whther my playback MS Basic, MuseSounds or VSTs

**Comment by MarcSabatella** [comment]
This is not a bug - it’s very much by design.  It’s important audible feedback for accessibility purposes, letting you know both that a note was entered and what pitch it is.  And the pitch definitely matters when entering drum music or other purposes for which this mode was designed.

You can turn off playback during note input in your preferences.  but as a feature request, I could imagine an additional option to control playback during rhythm mode specifically, if others feel it would be helpful.
