### ISSUE TITLE
Musescore 4 is extremely sensitive to mouse

### ISSUE THREAD

**Issue by fernandomartin777** [musescore/MuseScore#20743]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Musescore 4 is extremely sensitive to mouse clicks. Most times when I click in any object it moves as if I had clicked and held. It doesn't happens in MU 3.x nor at other softwares from my part, so I conclude that MU 4 is extra sensitive. 

### Steps to reproduce

Keep your mouse sensitive well calibrated for most softwares in your pc, go to MU 4 and write scores on it and probably many clicks you will understood as hold and dragging and will move objects slightly out of their positions.

### MuseScore Version

Musescore 4.x (All new versions)

### Regression

I don't know

### Operating system

Ubuntu 23.10

**Comment by MarcSabatella** [comment]
Please provide more information - like *exactly* what you are trying to click, what you expect to see happen, and what happens instead.  A screen recording would be extremely helpful.  In general, there should be no special difference between how MuseScore respond to the mouse versus any other program, though.

**Comment by fernandomartin777** [comment]
> Please provide more information - like _exactly_ what you are trying to click, what you expect to see happen, and what happens instead. A screen recording would be extremely helpful. In general, there should be no special difference between how MuseScore respond to the mouse versus any other program, though.

I couldn't screencast yet. But here's what often happens. I click on a note to select it and it moves a semitone above or below. I click at a rest and it moves slightly in some direction. And the same thing happens if I click in a measure number to start playing from there, with chord symbols, articulations, dynamics, almost everything movable.
I could think it's me or my hardware but that doesn't happen in MU 3.x nor other softwares here. 
The position of every object seems extremely sensitive in MU 4.

**Comment by MarcSabatella** [comment]
Hmm, I've never seen this and cannot reproduce this, but perhaps someone else can confirm.  Might be specific your mouse/driver or some other setting in your OS.  If you are ever able to find the precise steps to trigger this, be sure to update this issue with that information!

Do be sure to be using 4.2 - there *was* an issue in an older 4.0 version that was fixed quite a while ago, that could produce results like what you describe if your hand moves while clicking.

**Comment by fernandomartin777** [comment]
Currently there was one more user who reported the same thing in the forums.
[https://musescore.org/en/comment/1220629#comment-1220629](url)
What is hard is that even if I screencast what happens I can't record my hand movements and the exact strenght they're done.
But if someone else can agree on it or find a better explanation it will be helpful.

**Comment by ShibuyaCyana** [comment]
I guess it's just because MU4 let you directly drag something to move its location. in MU3 before doing this, we have to double click the element to enter so called _edit mod_.
Sadly afaik this is an intentional design change, having benefits as well as drawbacks like this.

**Comment by MarcSabatella** [comment]
But, that's not really true.  Most elements can be dragged directly in both MU3 and MU4.  Edit mode exists in MU3 and MU4 but it isn't about how dragging works - it's about enable the *cursor keys* to move elements.  There *have* been changes to which elements require Edit mode in order to activate keyboard adjustments, but that shouldn't have any bearing on how drag works.

I don't perceive any difference whatsoever in how clicking works between MU3 and MU4 - I essentially never accidentally drag when I mean to click with either version.  But I *could* imagine this will depend on the resolution of your display and of your mouse.  I could imagine that somewhere there is a fixed number of "pixels" that is used to determine when a move has happened and thus higher resolutions displays and mice might be resulting in the normal minute shifts that happen upon click being misinterpreted as a drag because these higher resolution devices report that shift as being more pixels.  Which is to say, the issue might have to do with comparing raw pixels rather than somehow scaling according to resolution properly.  In which case, the issue ould only be seen on devices that have significantly higher than normal display and/or mouse resolution, which would explain why most people (including me) don't notice anything different).

**Comment by ShibuyaCyana** [comment]
> But, that's not really true. Most elements can be dragged directly in both MU3 and MU4.

The change bugged me most is note horizontal movement. In early version (earlier than 3.6, like 3.2) you have to double click prior to do that. I though it was the same for ties or dynamic marks etc but I'm wrong, I can directly drag them in older version.

I see no difference in pitch change interaction between 3.0 and 4.2; but I do have the same feeling with OP. Trying to come up with some reason:
1. more things become movable, like accidental or time signature. They just can't be moved in early versions.
2. the hitboxes of some elements are too large, such as guitar bends. More element suffers from this problem but I can't recall them now.

**Comment by MarcSabatella** [comment]
It's not true that you needed to double-click to move notes in MU3 - in fact, the ease with which people would accidentally do that creates quite a few problems.  MU4 actually makes it marginally *harder* to do this accidentally.

It's also not true that accidentals and time signatures couldn't be dragged in MU3.  There might be *something* that couldn't be moved and now is, but I can't find any examples in some random attempts.

Some elements do indeed have larger bounding boxes for selection than they should, but I'm not aware of any that have changed between MU3 and MU4.  And in any event, that would have no impact on dragging, unless you are saying that you are dragging an element you weren't trying to select in the first place.  Like if you were resorting to dragging the canvas for some reason by clicking an empty area and accidentally dragged an element instead.  Again, though, this isn't different in general between MU3 and MU4, unless there is some very specific element type whose bounding box has changed, and I'm not actually aware of any although I wouldn't doubt one exists somewhere.  MU4 doesn't use the old MU3-style guitar bends, but if I create one in MU3 and import it into MU4 as I can tell their bounding boxes are identical.

There *is* a different default in how close you need to be to an element in order to select it - but again, here, it's *harder* to accidentally select (and thus drag) things in MU4 by default.  You can change this proximity setting in Edit / Preferences / Canvas.

**Comment by fernandomartin777** [comment]
> But, that's not really true. Most elements can be dragged directly in both MU3 and MU4. Edit mode exists in MU3 and MU4 but it isn't about how dragging works - it's about enable the _cursor keys_ to move elements. There _have_ been changes to which elements require Edit mode in order to activate keyboard adjustments, but that shouldn't have any bearing on how drag works.
> 
> I don't perceive any difference whatsoever in how clicking works between MU3 and MU4 - I essentially never accidentally drag when I mean to click with either version. But I _could_ imagine this will depend on the resolution of your display and of your mouse. I could imagine that somewhere there is a fixed number of "pixels" that is used to determine when a move has happened and thus higher resolutions displays and mice might be resulting in the normal minute shifts that happen upon click being misinterpreted as a drag because these higher resolution devices report that shift as being more pixels. Which is to say, the issue might have to do with comparing raw pixels rather than somehow scaling according to resolution properly. In which case, the issue ould only be seen on devices that have significantly higher than normal display and/or mouse resolution, which would explain why most people (including me) don't notice anything different).

You raised a valid point about resolution. My screen has 1920x1080 resolution and I write in MU4 200% zoom and horizontal continuous view. If you or anyone else can use MU4 in similar or higher resolutions would you have the same issue that I'm having?

**Comment by MarcSabatella** [comment]
That could be.  I recommend starting a new thread on the Support forum on musescore.org where other users will see this - this issue tracker is seen by a handful of developers others only.  Be sure to mention what OS you are on and also give more information about your mouse.  1920x1080 is not unusually high resolution, and zoom level shouldn't really affect anything.  But if your mouse is unusually high resolution - like if it sends 1600 pixels per inch rather than a more typical 400 or 800 - that could be the issue, as I mentioned.  Gaming mice apparently do this, and video games specifically are designed to handle that extra precision.  But other software might not always scale it correctly.  If so, then perhaps simply adjusting the mouse resolution its settings might solve this.

Again, the place to discuss this with more users who have a broader range of experiences is the Support forum on musescore.org.  Then if a specific set of steps to reproduce the problem is found, you can update this issue.

**Comment by fernandomartin777** [comment]
My mouse is a logitech m170. Very basic. I tried MU4 with 150% zoom but the issue remains. Less than this objects become too tiny at the screen.

**Comment by DaddyLudwig** [comment]
> > But, that's not really true. Most elements can be dragged directly in both MU3 and MU4. Edit mode exists in MU3 and MU4 but it isn't about how dragging works - it's about enable the _cursor keys_ to move elements. There _have_ been changes to which elements require Edit mode in order to activate keyboard adjustments, but that shouldn't have any bearing on how drag works.
> > I don't perceive any difference whatsoever in how clicking works between MU3 and MU4 - I essentially never accidentally drag when I mean to click with either version. But I _could_ imagine this will depend on the resolution of your display and of your mouse. I could imagine that somewhere there is a fixed number of "pixels" that is used to determine when a move has happened and thus higher resolutions displays and mice might be resulting in the normal minute shifts that happen upon click being misinterpreted as a drag because these higher resolution devices report that shift as being more pixels. Which is to say, the issue might have to do with comparing raw pixels rather than somehow scaling according to resolution properly. In which case, the issue ould only be seen on devices that have significantly higher than normal display and/or mouse resolution, which would explain why most people (including me) don't notice anything different).
> 
> You raised a valid point about resolution. My screen has 1920x1080 resolution and I write in MU4 200% zoom and horizontal continuous view. If you or anyone else can use MU4 in similar or higher resolutions would you have the same issue that I'm having?

I also have 1920x1080 screen resolution, but I use page view and regularly set the zoom to 50% so that I can see the full page and I don't have issues with either objects being too tiny or click sensitivity. But I don't really use a mouse either, I use the touchpad on my laptop for clicking.

**Comment by MarcSabatella** [comment]
I'm not sure what you mean abotu needing to zoom into 200% to see your score, unless it's an orchestral score with very small staves.  Objects on screen should be the same size at 100% zoom as they are when printed.  Sounds like something is off with the resolution settings on your computer.  Again, please ask for help on the support forum on musescore.org and include more details there, including what OS you are on and the symptoms you are seeing.  The support forum is the place to find people who can help.  *Then* if a bug is confirmed, you can come back here to update this thread.

**Comment by cbjeukendrup** [comment]
@fernandomartin777 I've found one thing that could potentially cause MS4 to behave differently, and created a fix for it here: #20781
In 40 minutes from now, a test build should be ready. It would be great if you could try if that improves the situation for you! See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests for instructions how to download/run the test build.

**Comment by fernandomartin777** [comment]
> @fernandomartin777 I've found one thing that could potentially cause MS4 to behave differently, and created a fix for it here: #20781 In 40 minutes from now, a test build should be ready. It would be great if you could try if that improves the situation for you! See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests for instructions how to download/run the test build.

Thank you very much. It's much better now. As far as I tested it seems to be solved at this new fix you linked above.

**Comment by NicolaRulli** [comment]
To the people that experienced this bug, did it also cause your click-shift-click mass selections to immediately deselect themselves in favour of the last clicked element, as if you had double-clicked? I'm trying to understand if it's the same problem (and thus if it's fixed in the next patch) or if it's something related to my trackpad. The way it works is, if you let the shift key go immediately after clicking the last item in the area you want to select, then the whole area will be highlighted as desired for a quarter of a second, but immediately after the program will behaved as if the user had clicked again, AFTER the mass selection was done, on the last clicked item.

**Comment by fernandomartin777** [comment]
> To the people that experienced this bug, did it also cause your click-shift-click mass selections to immediately deselect themselves in favour of the last clicked element, as if you had double-clicked? I'm trying to understand if it's the same problem (and thus if it's fixed in the next patch) or if it's something related to my trackpad. The way it works is, if you let the shift key go immediately after clicking the last item in the area you want to select, then the whole area will be highlighted as desired for a quarter of a second, but immediately after the program will behaved as if the user had clicked again, AFTER the mass selection was done, on the last clicked item. If you keep Shift pressed for a good half second more after your last click, then this bug doesn't occur.

I don't if it's related and if the patch solves it. For me, what happened to mass selection is that everything inside it was unwantedly transposed. You may try the patch or submit yours as a new issue.
