### ISSUE TITLE
Add options to show/hide clefs only on the first system of music they appear

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#20795]
It's a common style in guitar tab and jazz scores to see clefs appear only on the first system, and to hide them on subsequent systems in order to reduce visual noise on the score. 

A new feature in Format > Styles > Clef will give the user additional controls over the visibility of clefs in their score: 
 
**Design mockup updated 8Jan23**

<img width="2189" alt="Screenshot 2024-01-08 at 4 35 14 pm" src="https://github.com/musescore/MuseScore/assets/86290556/f6e07615-aeec-407f-8de5-5fd5b47b3997">

**Note**
The above settings replace these checkboxes, currently in Format > Page

![image](https://github.com/musescore/MuseScore/assets/86290556/d377eefe-1e46-4f8e-8d07-91605d040250)

**Comment by rgreen5** [comment]
In effect this will probably also resolve #18447.

**Comment by MarcSabatella** [comment]
Might make sense then to revisit the other existing options in Format / Style / Page:

![image](https://github.com/musescore/MuseScore/assets/1799936/89326109-daa1-4e66-b672-66161947762d)

I assume the first of the new proposed options basically replaces the first of the existing options shown, and thus should be removed from this page to avoid conflict.  The second one for tab only is new.  But perhaps the ones for key and time signatures should *also* be moved?  It is kind of nice having the clef & key options together since for lead sheets, you typically want to hide them both if you want to hide either.

**Comment by bkunda** [comment]
Good spot, @MarcSabatella.
I think it makes sense to co-locate those check box settings under the umbrella of a "Clefs, key & time signatures" page. They make little sense cobbled together under "Page", and I expect they'll be easier to understand if they are more clearly separated into subsections according to the element they affect. 
I'll update the issue description accordingly.
