### ISSUE TITLE
I'd like to hear an instrument's muted sound when clicking a note, just as it sounds during playback.

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#20969]
### Your idea

MuseScore 4.2 nicely plays Guitar Sounds Vol. 1 instruments with a muted effect wherever we have noteheads set to x.

Can we also have an option to hear the muted sound on clicking a note? So the sound of a clicked note matches what we hear from the note during playback. Also, I'd recommend that this option be the default.

### Problem to be solved

Allows the user to accurately preview a note without playing the score. It can be hard to hear an individual note as it plays amongst its neighbors.

**Comment by cbjeukendrup** [comment]
We might want to generalise this to all playing techniques and dynamics, i.e. arco/pizzicato etc..

**Comment by scorster** [comment]
> We might want to generalise this to all playing techniques and dynamics, i.e. arco/pizzicato etc..

**Agreed!** Years ago I requested the *option* to have clicked notes sound according to velocity and dynamic. But that was shot down as something that nobody would ever want.

But I'll state again, when listening to a section with ppp dynamic, I may turn up the volume to hear it better. But when I decide to select a note MuseScore sounds note with some default dynamic and velocity ... and that can be quite jarring.

If I dare piggyback a related request, it would also be great to have an option to silently select notes. 

Thanks! scorster

**Comment by MarcSabatella** [comment]
I for one would love to see all playing techniques and articulations supported for playback during note inut, but would definitely argue *against* following dynamics.  I don't want to have to struggle to hear my own note input on a passage marked ppp, nor do I want to have to turn up the volume just to do that, then remember to turn it down again when entering notes into a different part of the score.  Since some people apparently do seem to want that, though, I could imagine it being a preference, like the existing one for note duration during note input.

Perhaps more to the point, the default playback is generally perceived to be too loud, and simply toning that down would be better still.  See https://github.com/musescore/MuseScore/issues/15375

**Comment by scorster** [comment]
I'm all for the option of WYSIWYH (What You See Is What You Hear). And it definitely makes sense to have a preference setting to allow that. A larger Play Panel could house a link to the note-click prefs where users could toggle options like  • Include dynamics • Include velocity ...

Prior discussions here:

https://musescore.org/en/node/322984

https://musescore.org/en/node/314090

scorster

**Comment by avvvvve** [comment]
@scorster I believe the original issue (about playing techniques/noteheads/sound flags previewing correctly) has been addressed in our releases since you wrote this up. Could you confirm that it's completed so we can close this request as done?

The bits about dynamics/velocity are already logged separately here: https://github.com/musescore/MuseScore/issues/22498 (thanks!)

**Comment by scorster** [comment]
@avvvve asked > * I believe the original issue (about playing techniques/noteheads/sound flags previewing correctly) has been addressed in our releases since you wrote this up. Could you confirm that it's completed so we can close this request as done?*

Yes, regarding the initial issue, I ran a couple simple tests I hear muted notes when I click on notes that have X noteheads.

**Comment by avvvvve** [comment]
Completed in 4.4
