### ISSUE TITLE
Automatic system breaks change position

### ISSUE THREAD

**Issue by georggleixner** [musescore/MuseScore#21011]
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

1. open attached sample score
2. go to part 'Klarinette in Es'
3. it looks like this:
![Bsp_nach-Oeffnen](https://github.com/musescore/MuseScore/assets/44394350/10ffde34-7149-4a25-8df1-d06ee56b1753)
4. Select measures 55-59
5. decrease stretch (shortcut {, Mac: Ctrl+Alt+8)
6. increase stretch (shortcut }, Mac: Ctrl+Alt+9)
7. now it looks like this
![Bsp_vor-Schließen](https://github.com/musescore/MuseScore/assets/44394350/bb070b07-8bc4-4fbb-b54b-a369bfd81036)
8. save, close and re-open
9. i looks again like in (3.)

### MuseScore Version

(64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

[Bsp_v2.1.mscz.zip](https://github.com/musescore/MuseScore/files/13933048/Bsp_v2.1.mscz.zip)

**Comment by Jojo-Schmitz** [comment]
Stems from https://musescore.org/de/node/359190

**Comment by MarcSabatella** [comment]
As far as I can tell, the actual bug is that measure 59 didn't fit on the system with 55-58 to begin with.  Because it seems that it *should* be there, and that's the only reason that { followed by } leaves 59 on that previous system rather than returning things to how they started.  In fact, it seems just about *any* edit to that system will move bar 59 to the previous system, including for instance double-clicking the tempo text, then immediately pressing Esc (thus making no actual change).  Suddenly bar 59 fits, which presumably it should have all along.

Hard to say if if this is one of those rare-but-inevitable cases where results can be inconsistent due to the nature of rounding in floating point math, or if there is something else going on to cause the first layout to be incorrect.

ABTW, if the actual goal is to have more measures on the system, better to use { alone, not { followed by },. which should normally get you back where started.   But better yet, use the "Keep measures on the same system" element from the Layout palette and forget about stretch completely.
