### ISSUE TITLE
[Musicxml Export] - Unwanted transposition again in C score

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#21013]
### Issue type

Import/export issue

### Bug description

[Symphony_No.7_Op.131__Sergei_Prokofiev.zip](https://github.com/musescore/MuseScore/files/13933378/Symphony_No.7_Op.131__Sergei_Prokofiev.zip)

### Steps to reproduce

This score is written in C, thus no instruments are transposed to other keys. However, when converting into Musicxml and braille, I found the transposition is applied. For example, horns 1 2 at the beginning should be C-sharp octave chord, but it's converted as G-sharps with correct key signature in C instrument, thus key not transposed but notes transposed. I can't transcribe such score into braille at all!

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Windows

**Comment by sammik** [comment]
see https://musescore.org/en/node/302677

Workaround: export with concert pitch turned off

**Comment by sammik** [comment]
I dont understand, what You mean by "score iswritten in C"?

If You mean "score is written in concert pitch", than there is little problem: MusicXml doesnt support transposing instruments in concert pitch, which means transposing information would be lost during export.

Thats the reason, why scores are exported to musicxml always in transposing pitch.

And Yes, there is bug, that key signatures of transposing instruments are exported in concert pitch.

May be one day, there could be option in mxml export dialog to choose export in Concert / Transposing pitch.

**Comment by hhpmusic** [comment]
When I read this in Musescore 4, it reads out everything in C, thus concert pitches are shown. If so, exporting musicxml should reflect concert pitches, and if it's turned off, Musicxml should reflect transposed pitches. This works in Sibelius well.

Haipeng

**Comment by sammik** [comment]
> When I read this in Musescore 4, it reads out everything in C, thus concert pitches are shown. If so, exporting musicxml should reflect concert pitches, and if it's turned off, Musicxml should reflect transposed pitches. This works in Sibelius well.
> 
> Haipeng

I just tested Sibelius, and it exports concert pitch score to musicxml in **transposed pitch**, like MuseScore does. 
If I didnt miss something.

**Comment by sammik** [comment]
It seems, it is possible to have concert pitch score with part transposition information in mxml, see https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/for-part/

**Comment by SteveBlower** [comment]
I think there is some confusion here about how horn parts are traditionally written.  That is,  without a key signature and with all necessary accidentals written explicitly (i,e, next to the notes they affect).   Note that the lack of sharps or flats in the key signature does **not** indicate C major tonality in this case.  The tonality is defined by the accidentals.

In Musescore this "no key signature" look is achieved using a local Atonal key signature (the one with a light grey X) for the horn parts.  But in the example score this has not been done.  If an atonal key signature is added, the score looks as the OP desires.

The "no key signature" tradition is slowly dying out and horn parts with key signatures can be found quite commonly, particularly in band rather than orchestral contexts, but it is certainly not extinct.

I should also add that the same tradition is often found in trumpet parts.

**Comment by cbjeukendrup** [comment]
It would be great if someone could confirm that https://github.com/musescore/MuseScore/pull/21075 indeed fixes the problems here! (See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests about how to download test builds)

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/pull/21075#issuecomment-1925327938

**Comment by cbjeukendrup** [comment]
Reopening, as the corresponding PR hasn't been merged yet :)
