### ISSUE TITLE
Pedal marking nullified by previous adjacent pedal marking

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#21062]
### Issue type

General playback bug

### Bug description

Often when I am entering adjacent pedal markings, I will find that the one that I most recently does not work. I am usually able to solve this by deleting and re-entering the preceding pedal marking, suggesting that it has something to do with the interaction between adjacent pedal markings. However, on a particular score that I'm working on, I just cannot get the pedal marking to work, and the workaround is ineffectual.

### Steps to reproduce

[This is the project.](https://github.com/musescore/MuseScore/files/13972947/prelude_1-16-24.zip)

The pedal marking in question:
![image](https://github.com/musescore/MuseScore/assets/73259774/18e89e99-a8a6-46a2-a669-efa9fdaaed9d)

So long as measure 35 has a pedal marking, the one across m. 36 does not play back. If m. 35's pedal marking is removed, the one across m. 36 plays again. It stops working once more if a new pedal marking is added across m. 35.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

### Additional context

The issue can be heard for both MS Basic and Muse Sounds. It is likely related to #20839, except that the present file was created in MuseScore 4.0.2.
Seemingly unrelated to the playback issue, at measure 36 (the same measure with the pedal issue), the tuplets I entered began to be bracketed, instead of number-only, and also swapped sides. I did not touch any settings before this happened. This may be related or just a coincidence:
![image](https://github.com/musescore/MuseScore/assets/73259774/fc660929-21dd-4e94-846e-47506aab4cf9)

**Comment by bkunda** [comment]
I've just had a close look at this score, and it is indeed a very strange bug! 
It's almost like there's a curse on m.36...🫤. 
At any rate, I got the playback to work in master by subtly adjusting the end point of the preceding pedal mark (via our new anchors mechanism). 

https://github.com/musescore/MuseScore/assets/86290556/6b8be06f-d7f6-4cde-81a1-d207252f39ae

#### New file with adjusted anchor point
[prelude_6-11-24.mscz.zip](https://github.com/user-attachments/files/15787867/prelude_6-11-24.mscz.zip)

What this suggests to me is that this issue is potentially more subtle than suggested by the title. I suspect there's some interaction between the pedal end anchor point and some other element at this part of the score. The fact that the score was created in a very early version of MuseScore 4 might also be giving rise to some quirk.

At any rate, as annoying as this is, what we really need for this to be a helpful issue is clear reproducibility. This means the issue needs to be closed until a more precise one can be raised. 

Thank you!
