### ISSUE TITLE
Easier Programming: Adding more information for program and repository functions with README files

### ISSUE THREAD

**Issue by daijingz** [musescore/MuseScore#21086]
### Your idea

(This is the part 1 of my issues)
While reading the code, an obvious difficulty is to understand the overall structure. When going to the next branch folder, a developer finds it difficult to find which files are contained inside, unless reads more of these files' code lines. Simultaneously, he may become messy in finding the target file with his expected functions. This leads to much more redundant time consumption on reading codes, and rising of difficulties finding the target code file.

### Problem to be solved

In the repositories under `src`, e.g., `appshell`, `cloud`, it is convenient for us to write a README file or a readable introduction page, to describe each sub-repository's containing files and their common topics.

### Prior art
(This is an example, it do not need to be consistent with realistic information)

**braille**

* Contains braille basic functional program files

**Comment by cbjeukendrup** [comment]
The problem with documentation is that it takes often a lot of time to write, and even more time to maintain, because it can get outdated very quickly in which case it's the opposite of helpful. Therefore, we try to name all modules, classes and variables in the most descriptive way possible, to reduce the need for separate documentation. 
However, it may indeed be a good idea to have some basic documentation about the high level structure of the code, because that won't change too often. Note that a lot of that already exists here: https://github.com/musescore/MuseScore/wiki/Find-your-way-around-the-code (see in the sidebar at the right hand side, under "Beyond compiling" and "Architecture general").
