### ISSUE TITLE
Crash after changing beam type to No beam in Properties

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21099]
### Issue type

Crash or freeze

### Bug description

Similar to #21069 

### Steps to reproduce

1. Add two eight notes
2. Select beam
3. In Properties, select 'No beam'

It's easy reproduce on Mac:

https://github.com/musescore/MuseScore/assets/90187801/b8bf15ab-7bdc-4ee1-b54c-84631e012b88

It's hard to reproduce on Windows on my side. 
Try to open parts, undo, delete, add new eights etc

https://github.com/musescore/MuseScore/assets/90187801/35c30453-79be-4e05-ac2f-ac420d949e5b

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in  **MuseScore 4.2.0**

### Operating system

Windows/Mac

**Comment by MarcSabatella** [comment]
I ran into what I assume is a related if not identical crash on Linux the other day using the nightly from just before the RC, except it happened running "join beams" on a note that was already beamed, but I wasn't able to reproduce it later.  Luckily (?) the original happened "on camera" during a live stream, so I do have a recording of it, so just now I reviewed it was then able to retrace my steps and confirm the crash in 4.2.1 RC:

1. enter four eighth notes into an empty measure in 4/4 time
2. select the second eighth note
3. break beam left (using the icon in the Properties panel)
4. undo
5. join beams (using the icon or a keyboard shortcut if defined)

This crashes for me every time.

Additional info:

If in that last step, instead of join beams, I try break beam left again, nothing happens at all.  That seems to be because after the undo, the icon never resets to auto, so clicking the break beam left icon never actually invokes the command - you can see that nothing happens on the console.  That lack of updating the icon on undo is a bug in itself I guess.

But if I use a keyboard shortcut to do the break beam left immediately after the undo, it *does* crash.  Presumably, because now it *is* actually trying to perform the operation instead of skipping it as happened with the properties panel

However, if after the undo I clear the selection then re-select that same note, it does update the icon, and also - now there is no crash upon changing the beam property of the re-selected note (whether using the Properties panel or keyboard shortcut).  So that may explain any difficulty in reproducing this - this particular crash only happens if applying a new beam property immediately after undoing another.
