### ISSUE TITLE
Elements disappear in parts

### ISSUE THREAD

**Issue by Postoli** [musescore/MuseScore#21286]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When opening parts from a full score, sometimes certain elements disappear in the parts. This doesn't happen EVERY time, but it does happen often. 

The elements I've experienced it with are:
- Slurs
- Crescendos/Diminuendos
- 8va/15ma lines
- Gradual tempo change lines (rit., accel., etc)

This is especially frustrating when exporting string parts, as disappearing slurs mess up the bowings.

### Steps to reproduce

**NB: This does not happen with every element**
1. Create a score with multiple parts
2. Add slurs, crescendos, gradual tempo changes, 8va lines.
3. Create parts

### Screenshots/Screen recordings

<img width="876" alt="Full Score" src="https://github.com/musescore/MuseScore/assets/147510877/77fdd625-33ec-4f05-b5b6-9e7604249520">
<img width="1007" alt="Part (missing slurs)" src="https://github.com/musescore/MuseScore/assets/147510877/7afb303f-98b4-45f6-a90a-66fa6f456309">

### MuseScore Version

4.2.1-240230937

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma

### Additional context

See https://musescore.org/en/node/345542

**Comment by MarcSabatella** [comment]
There have been a number of other similar reports, but unfortunately so far no one has been able to find the actual step to reproduce it.  Please followup if you figure anything out!

See for instance https://github.com/musescore/MuseScore/issues/21232, https://github.com/musescore/MuseScore/issues/20086, https://github.com/musescore/MuseScore/issues/19852, and possibly others.

**Comment by MarcSabatella** [comment]
For anyone expewriencing this: the cut/paste trick above is nice for a workaround (great idea!), but it's true that it won't generally address rehearsal marks or other system-level markings (tempo, volta, etc).  The more complete workaround is to reset the part from the Parts dialog, but that also loses any custom formatting you've done.

**Comment by NicolaRulli** [comment]
Two important updates: 
1. Mass cut-and-repasting seems to break the links between hairpins and dynamics, and that connection seems to be flimsy regardless since changing the time signature / deleting bars also seems to displace one of those but not the other. This means that in the scenario where you use the cut-paste workaround, you then need to go through the whole score, in each part, on hunting down any misaligned amd delinked elements.
2. I'm not 100% confident on this one, but I think I'm getting the bug over and over. As in, fixing it to export parts on a work-in-progress, then working on the main score for many more hours, then switching back to parts to export an update, seems to be making hairpins disappear again (however, on this score I'm not getting any ghost rehearsal marks for some reason; I can't recall, however, if it happened once and then the fix was, in that case, permanent, or if reh. marks were never missing on this specific score)

**Comment by cadiz2** [comment]
Reported again: https://musescore.org/en/node/361348#comment-1231700

**Comment by cadiz2** [comment]
And again: https://musescore.org/en/node/361380#new

**Comment by mercuree** [comment]
I found one way to reproduce this issue
1. It happens after mmrest in parts, skip first two measures
2. Parts should be generated before, but you need to reopen file (all parts closed) before adding hairpin
3. I'm aware of #21633, this case should be tested anyway.

https://github.com/musescore/MuseScore/assets/919446/abb3826e-d503-4fb3-b4ab-59cd0b18cacf

**Comment by mercuree** [comment]
Is there any chance to see a temporary fix in MS 4.3.0? 
I say temporary because new spanner implementation in #21633 more likely not affected.
But this bug is very annoying.
Since main contribution to this bug "no parts were opened during entire session" (at least in case I could reproduce), it looks like there should be easy fix.

**Comment by cadiz2** [comment]
With the same steps, I cannot reproduce for slurs (used on a massive scale and therefore with a great impact)
Do you can? (I tried with alternative ways, without success for now)

**Comment by mercuree** [comment]
> With the same steps, I cannot reproduce for slurs (used on a massive scale and therefore with a great impact) Do you can? (I tried with alternative steps, without success for now)

The only way I could find for slurs is when you set/change time signature before already entered notes.
There are many time signature changes in [Disappearing elements.mscz](https://musescore.org/sites/musescore.org/files/2024-02/Disappearing%20elements.mscz) from https://musescore.org/en/node/345542
which I investigated.
Tested 4.2.1, 4.3.0, 4.4.0 master, 4.4.0 new spanner implementation #21633. All of them are affected.

https://github.com/musescore/MuseScore/assets/919446/637cd3e7-5ac2-4a93-929c-ad932f0a29f9
