### ISSUE TITLE
"Explode" tools copypastes all grace notes instead of exploding them

### ISSUE THREAD

**Issue by NicolaRulli** [musescore/MuseScore#21291]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

CONSISTENT BUG

Using the "explode" tool on a staff with chords, to spread the voices across different staves, doesn't work correctly on grace notes (both acciaccature and appoggiature). Instead of putting each note on a different staff, all notes are pasted onto each staff.

### Steps to reproduce

1. create a score with several staves
2. write a chord onto the first staff, with as many notes as there are staves
3. input a grace note chord onto the chord in point 2
4. select the measure
5. use the "explode" tool

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No.

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

### Additional context

Behaviour has been the same since at least 3.6 (if not forever)

**Comment by oktophonie** [comment]
Certainly this is incorrect with grace note chords, where the grace notes should explode just as the normal notes do:
![image](https://github.com/musescore/MuseScore/assets/20604032/63573afd-7834-4624-ae21-722a471c4907)

It's perhaps acceptable for single grace notes leading to a chord, since it may not be clear which 'voice' they belong to, and it's easy enough to delete the duplicates:
![image](https://github.com/musescore/MuseScore/assets/20604032/61cb1421-96cd-4a11-9757-44478e23b6db)

**Comment by XiaoMigros** [comment]
I'd like to take this on
