### ISSUE TITLE
quarter ptich

### ISSUE THREAD

**Issue by mrfefi** [musescore/MuseScore#21334]
### Your idea

How can I define quarter ptich for example between e and f, or b and c ??
This is very important for the hungarian folk music,

### Problem to be solved

How can I define quarter ptich for example between e and f, or b and c ??
This is very important for the hungarian folk music,

**Comment by Valdessir** [comment]
You have a wealth of accidentals to choose from in the accidentals palette for your purposes. Additionally, you can customize the tuning of each note via the properties, playback, then tuning (cents). 

Furthermore, this is a place to report bugs, or put requests. If you intended a request to support the notation of this music, it's much preferable to word this as a request. Otherwise, for queries, you ought to repost this in the musescore forums
