### ISSUE TITLE
Issue with Multi-Touch Laptop when scrolling horizontally

### ISSUE THREAD

**Issue by Neldor258** [musescore/MuseScore#21349]
Hey there! I just installed MuseScore (latest Version) on my Laptop which has Multi-Touch support.

As I opened a project and scrolled along horizontally, not only the expected visual scrolling happened, but there also was some sort of selection going on - I understand it is not only scrolling the view but simultaneously selecting any next or previous notes accordingly.
Scrolling vertically works fine as expected, as does any scrolling (any direction) with a mousewheel.
I'm using the pageless horizontal layout, although I confirmed the behaviour does not change with any layout option.

Since I didn't find anything regarding Multi-Touch or scrolling in the preferences or under the issues here, I'm now opening this issue.
I hope I didn't just miss any obvious settings or posts and want to kindly ask for help or explanation what is happening.

My MuseScore help > about stats are:
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433
(on a HP Pavilion Laptop)

While I don't think I it would make sense to provide any example file since this is a global issue, I hope you can understand my experience and will be able to help me out. 
If you should need additional information or material, I will try to deliver it on request.

Greetings, Neldor258

**Comment by bkunda** [comment]
@DmitryArefiev are you able to investigate this one? 
We may need to track down relevant hardware if you don't already have the right kind.

**Comment by DmitryArefiev** [comment]
@bkunda Yes, I have Lenovo IdeaPad 5 Pro 16IHU6 with multi-touch touchpad.  Scrolling horizontally/vertically works fine on my side

**Comment by DmitryArefiev** [comment]
@Neldor258 Do you have a problem with touchpad (or maybe you have a touchscreen)? What is the model of your laptop?

**Comment by Neldor258** [comment]
> @Neldor258 Do you have a problem with touchpad (or maybe you have a touchscreen)? What is the model of your laptop?

Hey, sorry for the late reply! 
I've got the "HP Pavilion 17-g054ng" with multi-touch on a touch pad (not on screen).
Sadly, I don't have any other touch hardware to test on myself.

**Comment by DmitryArefiev** [comment]
OK. Is it an old laptop? What CPU is there? 

Do you scrolling horizontally with the two fingers left-right? Did you try that in other apps?

**Comment by Neldor258** [comment]
Hi! The laptop is rather old I think. I didn't buy it myself though, I just got it from a friend.
Here's the additional specs:
Prozessor	AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G   1.80 GHz
Installierter RAM	16,0 GB (15,4 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

As for other apps, did you have anything specific in mind?
I just tested a zoomed in Firefox PDF preview for example which works as expected.
And yes, I'm using two fingers to scroll in any direction.

Oh wow, you've got a point! I just tried out Visual Studio and when I zoomed in, then scrolled horizontally it did not just scroll the view but it actually scrolled the cursor sideways! X.X
So eventually, it does not seem to be an issue with MuseScore at all. :)

However, do you happen to have heard of anything like this before or have experience with Multi-Touch? 
Anyways, thanks a lot for your investigation and I apologize for not testing enough other applications beforehand. 😅

**Comment by DmitryArefiev** [comment]
Hi! Oh, that's probably not MuseScore issue. The old laptops might have a problems with touchpad because of drivers or technical specs of touchpad itself. You can try to update drivers or edit touchpad settings in Windows, maybe this helps..

I've tried two my Windows laptops (Lenovo IdeaPad 5 Pro 16IHU6, ASUS VivoBook 14 X415JA, both from 2021y). Their touchpads are work fine with MuseScore

**Comment by MarcSabatella** [comment]
FWIW, it's pretty common on Windows laptops - especially older ones - that sideways swipe does not function to scroll horizontally.  Most support Shift+scroll instead for horizontal scrolling.  Sounds like this one is sending *some* sort of info on the horizontal scroll but it isn't just scrolling info.  It's possible a new driver might allow sideways swipe to function as plain horizontal scroll (since there does appear to be some sort of hardware support for the gesture itself), or you might simply need to use Shift+scroll instead on this device.
