### ISSUE TITLE
MuseScore 4 freezes when pressing Enter editing Text

### ISSUE THREAD

**Issue by SDutr4** [musescore/MuseScore#21380]
### Issue type

Crash or freeze

### Bug description

When I am editing text in any score (either a new score or an already existing one) and press "Enter" to add a line of text (for example when writing basso continuo), MuseScore freezes. This happens with any kind of text.
This has been happening in every MuseScore 4 update so far. It doesn't happen in MuseScore 3 (I have tested it recently in 3.6.2 and it works just fine)

Edit: I have also noticed that if I open scores that already have boxes with multiple lines of text (made in MS 3, for example) and try to edit that text it also freezes.

### Steps to reproduce

1. Open MuseScore 4
2. Open any score (or create a new one)
3. Insert any kind of text
4. Edit text
5. Press Enter
6. Freeze

### Screenshots/Screen recordings

[MS4 Freeze Recordings.zip](https://github.com/musescore/MuseScore/files/14173514/MS4.Freeze.Recordings.zip)

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
I am not able to reproduce this issue on my Mac or Windows devices.
Could you tell me what language / keyboard you are using?
Could you share diagnostic files? (Diagnostic>Save Diagnostic files)

**Comment by SDutr4** [comment]
> I am not able to reproduce this issue on my Mac or Windows devices. Could you tell me what language / keyboard you are using? Could you share diagnostic files? (Diagnostic>Save Diagnostic files)

I am using Portuguese (Portugal)

The .zip file is too big to upload (47MB), but here's a Google Drive link with the diagnostic files: https://drive.google.com/file/d/1pmM0JOaSfo68e7JOCHt96mkj7NkShpEH/view?usp=sharing

**Comment by zacjansheski** [comment]
@cbjeukendrup can you take a look at those diagnostic files when you get a chance?

**Comment by cbjeukendrup** [comment]
The log files reveal that there is probably an infinite loop involving `AccessibleItemInterface::characterRect` and `AccessibleItem::accessibleTextAfterOffset`.
It doesn't look like a recursion loop, because then you'd get a stack overflow crash much sooner. But since these methods are called from inside Qt, it's not easy to find out from where they are called and why. 
The fact that these methods are called does suggest that @SDutr4 has some accessibility features of the OS enabled, such as a screen reader. @SDutr4 do you indeed use anything like that, and if so, could you tell what exactly?

**Comment by zacjansheski** [comment]
No response
