### ISSUE TITLE
Make default drumset instrument more conventional

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21402]
### Your idea

The default drumset instrument is a hot mess.

A few "easy fixes" to consider:

1. Omit the congas
2. Shift Hi-hat open to the same space as the closed Hi-hat, there will be visual redundancy, but when the percussion UX/UI is changed in 4.4 this will not be an issue.
3. Shift the splash cymbal up to -4, the smallest cymbal, highest pitch, set highest on the staff
4. Omit Hi-Mid Tom, it is visual redundant with High Tom, there are still plenty of toms for most user's needs.

A few other considerations:
1. Change Side Stick to "Rim knock" and change note head to "Slashed Forwards"
2. Offer a minimal drum kit instrument that omits all but the essentials of a basic kit: Kick, snare, two mid toms, a floor tom, HH, 1 crash, 1 ride.

### Problem to be solved

This is the current drumset

<img width="880" alt="Screenshot 2024-02-07 at 12 01 43 PM" src="https://github.com/musescore/MuseScore/assets/69917893/b1602077-d77a-41ea-b30d-7559ad7fc1cc">

This is drumset with simple fixes

<img width="780" alt="Screenshot 2024-02-07 at 12 03 02 PM" src="https://github.com/musescore/MuseScore/assets/69917893/b51be694-6c65-47c0-902a-211faa48ee5c">

This is a minimal drumset

<img width="504" alt="Screenshot 2024-02-07 at 12 21 20 PM" src="https://github.com/musescore/MuseScore/assets/69917893/04fff001-00a1-4c1b-8496-cc5aae0a1ce5">

### Prior art

Minimal Kit DRM

[Minimal Drum Kit.drm.zip](https://github.com/musescore/MuseScore/files/14197189/Minimal.Drum.Kit.drm.zip)

### Additional context

The drumset instrument is "hard coded" in MuseScore.  It would be important to understand the potential problems of changing anything there.

Offering a "Minimal Drum Kit" could be done without making changes to the hard-coded drumset

**Comment by zacjansheski** [comment]
Really that top line should be used for a tom at all unless working with 5 toms

**Comment by EvansSC1** [comment]
I would say that the current side-stick sound is more suited for a rim-click, and I would very much enjoy the actual adding of a rim-knock (cross-stick) sound at some point as well.

**Comment by zacjansheski** [comment]
@EvansSC1 agreed.  

I need to understand the "hard coded" business better, the drum kit is glued to MIDI General drum mappings which uses the "Side-stick" term.  So I would say that the fault is in the MS Basic soundfont.

I think if I have to prioritize this in a way, it should be Notation>Playback.  The reason this matters is that we want to conform to standards of third party libraries.  

In VDL, that C#2 is a "Cross Stick" not a rim.  I believe most drumset libraries that are mapped to MIDI general follow that convention.

Additional functionality/sounds/playback features will be developed for Muse Sounds.

**Comment by RobFog** [comment]
I had read a while ago that there are plans to rework support for drum kit and percussion. I'm currently writing my master's thesis on drum notation support in scorewriters and I've spent some time analysing MuseScore. I did find that many aspects of MuseScore's drum notation deviate from standard notation. I'd been wanting to reach out to you folks at MuseScores to see if my findings could be of any use.

I didn't realise changes to MuseScore's default would be considered for version 4.3 already.

> Omit Hi-Mid Tom, it is visual redundant with High Tom, there are still plenty of toms for most user's needs.

Like those two, "High Floor Tom" and "Low Floor Tom" are also placed in the same spot in the staff.

I would argue that in the non-minimal drum set users should be able to write six different toms as the percussion map of the General MIDI Specification stipulates.

> Change Side Stick to "Rim knock" and change note head to "Slashed Forwards"

What do you mean by "Rim knock"? The MIDI key MuseScore refers to as "Side Stick" produces a sound we get from using what is commonly referred to as the "cross-stick" technique. The slashed notehead you propose is usually used to indicate a rimshot.

> The drumset instrument is "hard coded" in MuseScore. It would be important to understand the potential problems of changing anything there.

I agree that changes to MuseScore's default drum input need to be very carefully considered. 

Relevant thoughts and questions that come my mind:
- How will changes we make now affect scores written in older versions of MuseScore?
- MuseScore's drum input palette appears to be tied to the percussion map of the General MIDI Specification. Does it facilitate standard notation in its entirety?
- How will MuseScore drum notation defaults affect interchange of scores between different scorewriters through MusicXML?

I have started writing out my thoughts on how the drum input palette needs to be changed: https://github.com/orgs/musescore/discussions/21517

**Comment by zacjansheski** [comment]
@RobFog thanks for the input. 

Cross-stick, rim-knock, and side-stick are used interchangeably.  Cross-stick is the most clear so we should use that as the default term.

Weinberg is great, but also a little dated now.  His rim-shot, ride bell, and rim-hit symbology have not really caught on in the common practice.  I think the OrnateX is better suited for rim-shots.

My short-term solution is to offer a 4-piece and 5-piece drum kit as more simplified versions of the current kit.  The current kit can be referred to as "Large Drum Kit" and the toms can be put on their proper lines.  Musicxml imports should be opened with the "Large Drum Kit" by default.

**Comment by RobFog** [comment]
> @RobFog thanks for the input.
> 
> Cross-stick, rim-knock, and side-stick are used interchangeably. Cross-stick is the most clear so we should use that as the default term.

Okay, thanks. I hadn't come across "rim knock" until now.

> Weinberg is great, but also a little dated now. His rim-shot, ride bell, and rim-hit symbology have not really caught on in the common practice. I think the OrnateX is better suited for rim-shots.

Are you sure?
- Weinberg's book was endorsed by the Percussive Arts Society (PAS), apparently "the world's largest percussion organization", when it was published. What does the PAS say now? They have a guide at https://www.pas.org/resources/specialties/drum-set but I cannot access it.
- The book was also reviewed by the Hal Leonard Corporation (now part of Muse Group since December) and Modern Drummer magazine.
- Drumeo, arguably the largest online website for learning drums, uses Weinberg's symbology in their July 2023 article [How To Read Drum Music (For Beginners)](https://www.drumeo.com/beat/how-to-read-drum-music/).

I can't say I have ever seen an Ornate X notehead used for rim shots…?

> My short-term solution is to offer a 4-piece and 5-piece drum kit as more simplified versions of the current kit. The current kit can be referred to as "Large Drum Kit" and the toms can be put on their proper lines. Musicxml imports should be opened with the "Large Drum Kit" by default.

You want to offer separate drum kits for people who want to notate either for two toms or for three toms?

**Comment by zacjansheski** [comment]
Weinberg's book was written over 25 years ago (published in 1998)

Percussion resists standardization, users can change noteheads if they like.
We want to use the same symbols as VDL as our percussion defaults:
![Screenshot 2024-02-15 083414](https://github.com/musescore/MuseScore/assets/69917893/fba089d4-2260-405c-87f7-035915fdec0a)

Offering smaller kit instruments will be more non-percussionist friendly and third-party VST friendly

**Comment by RobFog** [comment]
> Weinberg's book was written over 25 years ago (published in 1998)
> 
> Percussion resists standardization, users can change noteheads if they like.

I am well aware how old the book is. It is difficult to estimate a) how much more standardised drum notation has become thanks to the book and b) how standardised drum notation is in published works.

However, scorewriters Sibelius ([Sibelius Reference Guide, Version 2023.11](https://resources.avid.com/SupportFiles/Sibelius/2023.11/Sibelius_Reference.pdf), p. 379), Finale (["Percussion" in Finale's user manual ](http://usermanuals.finalemusic.com/FinaleWin/Content/Finale/Percussion.htm)) and MuseScore ([Comment by former lead developer "lasconic"](https://web.archive.org/web/20221006074739/https://musescore.org/en/node/36206)) have all stated they intend to follow Weinberg through their defaults. I reckon this contributes greatly to standardisation.

If MuseScore chooses to be the outlier, this hurts standardisation.

**Comment by zacjansheski** [comment]
The Sibelius guide references the book then proceeds to not follow it:
![Screenshot 2024-02-15 092716](https://github.com/musescore/MuseScore/assets/69917893/90c458a5-db42-4ced-830a-7168671814fe)

**Comment by RobFog** [comment]
The drum key from Sibelius' Reference Guide lists "side stick" twice, once with an X note head and once with a slashed notehead, so either a) it's a typo and of them was supposed to say "rim shot" or b) they offer both options. But I don't see how it does "not follow it"?

I hadn't previously looked into Dorico but [Inputting notes on a drum set](https://steinberg.help/dorico_first_steps/v3.5/en/dorico_first_steps/topics/first_steps_further_notations/first_steps_notes_drum_set_inputting_t.html) states: "The default drum set in Dorico is already set up with the most common percussion playing technique noteheads, so the side stick snare drum note appears with a cross notehead."

**Comment by zacjansheski** [comment]
But that's not what is in the Weinberg book.  Weinberg uses the circled note for side-stick/cross-stick.  If they (Dorico/Sibelius) mean a "rim", Weinberg uses a square articulation symbol for that.  Weinberg didn't use x's for rims/rim-knocks because he didn't want to use the same noteheads as the cymbals.  The square articulation symbol, I have never seen that "in the wild"

I have see the circled note commonly, but it isn't great because it is visually very close to a ghost note.

Rims are used far less than cross-sticks, so they shouldn't be included in a minimal drum kit.

The slashed notehead is great for cross-stick and the ornate-x for shots.  Very clear and easy to read.

Once again, users can change the noteheads to whatever they want.

**Comment by RobFog** [comment]
> But that's not what is in the Weinberg book. Weinberg uses the circled note for side-stick/cross-stick. If they (Dorico/Sibelius) mean a "rim", Weinberg uses a square articulation symbol for that.

You're right and I'm sorry. I did get things confused there.

> The square articulation symbol, I have never seen that "in the wild"

I also haven't seen the square articulation symbol.

> I have seen the circled note commonly, but it isn't great because it is visually very close to a ghost note.

Agreed.

> Rims are used far less than cross-sticks, so they shouldn't be included in a minimal drum kit.

Okay. 👍

> The slashed notehead is great for cross-stick and the ornate-x for shots. Very clear and easy to read.

Easy to read, yes. But not clear because slashed notepads are frequently used for rimshots:
- Sibelius Reference Guide: "Noteheads with slashes through them (shortcuts Alt+Shift+11/12 or Option+Shift+11/12) are used for things like rim-shots in percussion notation."
- [Drumeo](https://www.drumeo.com/beat/how-to-read-drum-music/): https://drumeoblog.s3.amazonaws.com/beat/wp-content/uploads/2021/08/20153107/6k-1-1.png

> Once again, users can change the noteheads to whatever they want.

I know. But lack of standardisation is a real pain in education. And "slashed notehead for cross-stick and the ornate-x for shots" appears to be an entirely new idea.

What's wrong with X notehead for cross-stick and slashed notehead for rimshots? That does seem be a very common variation.

> Weinberg didn't use x's for rims/rim-knocks because he didn't want to use the same noteheads as the cymbals. 

Is that a reason you're against the X notehead?

**Comment by zacjansheski** [comment]
I think the VDL approach is strongest candidate for us to adopt for our defaults. 

- Using x-noteheads for "something metal" is the common practice, whether cymbals or rims.
- There is a precedent for using that symbology, it has been adopted by high-caliber and modern percussion publishers writing with Sibelius/VDL.
- That system gives clear differentiation between "rims" and "rim-shots" and rim-knocks" without having to add awkward text or odd articulation pictograms.
- We can have consistency across other instruments that will use shot-like symbols, like conga slaps, marching drumline shots, timbale shots, I'm sure there is more.

It is also my personal preference because the slash notehead looks like a stick laid over the drum, like a cross-stick, also the ornate-x "looks louder" than the slashed notehead.  Of course my personal opinion is completely subjective. :)

Rather than pushing for standardization (which I would argue can be shackling), the inclusion of "legends" in every book/solo/piece should become the norm.

**Comment by MarcSabatella** [comment]
I did not see there further discussion of the first point in the original issue -  the notation of open vs closed hi-hat.  This has come up in support discussions and I definitely found this a surprising change to have been made for 4.3.  Yes, of course, notating both open & closed on the same line/space makes sense *if* the appropriate articulation can be added automatically, but that’s not the case right now (4.3.2).  So now we have users adding alternating open & closed hi-hat and not understanding why they look the same or what to do about it.

I guess it’s too late to do anything about this except start documenting it better and spreading the word.  *Unless* there is any thought of a 4.3.3, in which case, I’d advocate for backing this particular change (the hi-hat) out.  Or using a different notehead at least.  And if a 4.3.3 happens, I’d also argue for naming the ”drum kit” instruments back to “drumset” because that’s what people are accused to typing into the search box or selecting from the list and pretty much daily we have people asking where the drumset went.  This also feels to me like a change that would have been better reserved for 4.4.

**Comment by zacjansheski** [comment]
There is no accepted notation that puts the open HH on a different line or uses a different notehead.  Using a different line/notehead makes it _more difficult_ to use proper notation.

"Drumset" is fraught.  Sometimes one word, sometimes 2.  The term is used for the percussion panel in "edit drumset" the nomenclature change is an objective improvement.

Searching for instruments should be to be improved at a higher level to more forgiving.  Many instruments have alternative names / spellings

**Comment by MarcSabatella** [comment]
I totally agree that long term the change makes sense in order to encourage proper notation.  I’m just surprised to see it slipped into 4.3 with no warning to users, because now there is confusion that didn’t exist before.  We’re going to have a lot of scores where people don’t add the articulations because they have no idea that is a thing and they just accept the articulation-less defaults, and then their scores will not differentiate open from closed at all.  Which to me is worse than using the “wrong” line.  That plus the cases where users notice the duplication and assume it’s a bug and report it as such.  So I there is a very real cost to the change, even though it also comes with a benefit for users savvy enough to realize what has happened and they now need to do to get correct notation.

To me this would would have made more sense to wait on until 4.4, both because there will presumably be some more direct articulation support to help automate the correct notation, but also because we *will* be doing the sort of messaging that a change like this calls for.

Anyhow, as I said, it’s kind of moot now.  We’ll just have to make sure we inform users that they will now have to manually add articulations to differentiate open from closed, whereas previously it wasn’t necessary because of the non-standard (but very well-established within the world of MuseScore) line assignments.

FWIW, the image above shows Sibelius supporting open hi hat with a different notehead as one alternative (first note of third line).  So there is at least *some* precedent for it.
