### ISSUE TITLE
[Musicxml Export] - Inconsistent page/system breaks

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#21424]
### Issue type

Import/export issue

### Steps to reproduce

Taking this score:
https://musescore.com/user/35916268/scores/9376147
  When exporting it to PDF, it has 104 pages, correct. But when exporting into Musicxml, at page 70 two pages are combined, where page 71 becomes a system break. What's wrong? The page system breaks should be the same as pdf.

### MuseScore Version

4.2.3 nightly

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows

**Comment by oktophonie** [comment]
There don't seem to be an explicit system or page breaks in the original file, so the layout is just 'as it comes'.

When exporting to MusicXML the layout will therefore likely change since some items may be in a different position, be missing, be at a different size, etc. So there's not really a bug here.

**Comment by hhpmusic** [comment]
Thanks, I see. Then Musescore works differently from Finale and Sibelius, which uses exact breaks which will not change among versions and during exports. Publishers will like such software than a varying format. But Musescore's flexibility is at the other side a different advantage for some engravers.

**Comment by oktophonie** [comment]
You _can_ input system and page breaks which don't change, and that's what you'll see in lots of files. This file just happens to not have any.
