### ISSUE TITLE
Flute Flageolet playback is not working

### ISSUE THREAD

**Issue by Fiaegel** [musescore/MuseScore#21591]
### Issue type

Muse Sounds bug

### Steps to reproduce

1. create a new project with a flute part
2. use muse sounds 
3. write the same note twice
4. apply the harmonics circle to one of them
5. observe in playback they sound the same

### MuseScore Version

4.2.1-240230937

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 14.2.1

**Comment by Fristover** [comment]
Test file here (remove .zip, don't extract):

[harmonics.mscz.zip](https://github.com/musescore/MuseScore/files/14335393/harmonics.mscz.zip)

I'll also confirm these worked when Muse Woodwinds were released, first with triggering a different note than written (with no clear sense) and then triggering the notated pitch as a harmonic.

Also, I wonder if other woodwind instruments ever had harmonics in the first place, they've never been there but the Muse Hub says "Consistent array of articulations" which makes me expect at least harmonics for every instrument...

**Comment by Fristover** [comment]
Found the problem after almost 7 months. lol

The harmonic articulation (little circle) only works for string instruments (kinda like how bends also only work there: #21369 )


Here you have a Flute instrument using the Muse Sounds Flute 1 sound:
https://github.com/user-attachments/assets/4e10bbf6-2216-4cbb-820b-a51ce477d820


And here you have a Violins (section) instrument using the same Muse Sounds Flute 1 sound:
https://github.com/user-attachments/assets/2a986734-f9f8-4bb2-80f5-7e64729bb35d


I get that bends are disabled on winds, that does make sense, but why harmonics? specially since we don't really have any other way to trigger them, no sound flags and no other notation systems currently.

I hope this gets reverted soon on the MS Studio side as it wasn't the case when Muse Sounds had just launched.

**Comment by matthewreadbass** [comment]
Thanks for bringing this to our attention. As this is the MuseScore repo, I'm going to open a separate ticket in the Muse Sounds repo for this issue.

**Comment by cbjeukendrup** [comment]
Closing as per the comment above; this is being addressed by the Muse Sounds team.
