### ISSUE TITLE
Notes and other elements don't change color when hovering over to drop an element

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21640]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In master notes don't change to blue when you drag and element and hover over the note

### Steps to reproduce

1. Open master
2. Drag an element from the palette
3. Hover over note

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/9779282b-d9ec-452a-b594-c81dd2eca218

### MuseScore Version

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.4.0-240520304, revision: github-musescore-musescore-a81416d

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Not an issue in 4.3
Probably Qt 6 related

**Comment by mathesoncalum** [comment]
I've had a good look into this on multiple occasions but never quite got to the bottom of it… 

 The problem seems to be (at least partially) that `AbstractNotationPaintView::dragMoveEvent` doesn’t receive a call. If you monitor the event types arriving at `AbstractNotationPaintView::event`, in Qt5 we receive repeated `DragMove` events while in Qt6 we get repeated `DragEnter` and `DragLeave` events instead.  
 
 The Qt code that determines which event type to send is in `deliverDragEvent`. In Qt5 this method is in `qtquickwindow.cpp`, in Qt6 this is in `qtquickdeliveryagent.cpp`. Our answer probably lies in there somewhere...
