### ISSUE TITLE
When entering plain system/stave text (<CTRL>+T) beginning with A-G with or without accidentals, these are interpreted as chords and not as text

### ISSUE THREAD

**Issue by avronp** [musescore/MuseScore#21642]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

As in the title

### Steps to reproduce

1. Enter plain system/stave text (<CTRL>+T) beginning with A-G with or without accidentals and a space after
2. Click Enter
3. These are displayed and played as chords and not as text

### MuseScore Version

 4.2.1.240230937

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
I cannot reproduce.  Is it possible you have customized your keyboard shortcuts (Edit / Preferences / Shortcuts) so that Ctrl+T is now the shortcut for chord symbol instead of for staff text?  Or have you perhaps selected a font that has special characteristics for those characters?

If you continue to have problems after checking these possibilities, please ZIP and attach a score that demonstrates this problem.

**Comment by bkunda** [comment]
I cannot reproduce this on macOS.

**Comment by zacjansheski** [comment]
Closing, can't reproduce, no response
