### ISSUE TITLE
MuseScore 4 Project File Won't Open--Stuck on Not Responding 

### ISSUE THREAD

**Issue by HeyStyle** [musescore/MuseScore#21725]
### Issue type

Opening/saving issue

### Bug description

My MuseScore 4 file will not open, despite having tried on numerous devices.  It stays loading until I click a button, and then it goes not responding.  It an attempt to view the project another way, I uploaded it to MuseScore online, and it has been processing for two days now.  The compressed Zip file with the project is attached.   
[Dance of a Hundred Steps Full Score.zip](https://github.com/musescore/MuseScore/files/14425001/Dance.of.a.Hundred.Steps.Full.Score.zip)

### Steps to reproduce

1. Open "Dance of a Hundred Steps Full Score" in MuseScore 4.

### MuseScore Version

MuseScore 4 

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 and Windows 10

### Additional context

This worked on the same MuseScore 4 version I have now only a few days ago, but has since stopped working even though I haven't updated anything.

**Comment by mercuree** [comment]
Discussed here https://musescore.org/en/node/361077
Transposition for one staff was set to 4 octaves down causing serious performance issue on score opening.
![image](https://github.com/musescore/MuseScore/assets/919446/03a29241-33fe-4afc-9079-9cb5ac33a4d8)
Since the set value was inadequate, I wonder if there should be a fix for this issue.

**Comment by Jojo-Schmitz** [comment]
How can you tell it to be a rgression if no older version can read that score?

**Comment by Jojo-Schmitz** [comment]
Hmm, it'd still be interesting to get this issue investigated
