### ISSUE TITLE
"A" keyboard shortcut no longer triggers note entry on macOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#21736]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Using the keyboard shortcut "A" no longer triggers note entry on macOS. 
Checked in today's master (not a problem in 4.3). 
Verified on both QWERTZ and QWERTY keyboards.

### Steps to reproduce

See video:

https://github.com/musescore/MuseScore/assets/86290556/3d8ae5cf-18f9-4865-b301-c66bcc0d834c

### MuseScore Version

OS: macOS 14.3, Arch.: x86_64, MuseScore version (64-bit): 4.4.0-240590302, revision: github-musescore-musescore-fe4d7a4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.3.1

**Comment by MarcSabatella** [comment]
Not sure if someone already has a handle on this, but see also https://github.com/musescore/MuseScore/issues/20866.  Seems the root cause of that issue a questionable Qt handling of some specific keyboard layouts on Mac - https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-85660.  Somehow this seems likely to be similar, but - new version of Qt, new cases that aren't handled right.

**Comment by zacjansheski** [comment]
First appeared with QT6 in
OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.4.0-240540301, revision: github-musescore-musescore-6a94196

Checked on QWERTY on MacOS and Windows.  MacOS (11 and 14), and Ubuntu.
Issue is only on MacOS
