### ISSUE TITLE
Bug: Instrument, part and channel names out of sync and not all stored in save file

### ISSUE THREAD

**Issue by vHeemstra** [musescore/MuseScore#21839]
### Issue type

Opening/saving issue

### Bug description

1. The part names (orange in screenshot below) are not synced with the instruments names (yellow in screenshot below).
   When renaming an instrument, the part name stays the same.
2. Part names are not stored in the save file.
   When renaming a part in the Parts dialog, the new name is not stored in the project file.
3. Part names in Mixer are not in sync with part names in Parts dialog window.
   When you rename a part in the Parts dialog, the new name is not shown correctly in the Mixer window/panel.

### Steps to reproduce

1. Create a new project with an instrument.
2. Go to Parts dialog/panel and rename the part.
3. Save the project.
4. Re-open the project: the part name is reset to the default naming.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/17368112/07cc55db-b717-431d-8b51-681457cca1f4)

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by vHeemstra** [comment]
So maybe I don't quite understand how the channels in the Mixer are related to the project, but:
* If they are the instruments, then the should show the instrument's name (currently not in sync after renaming an instrument).
* If they are the parts, then they are currently not synced after renaming a part.

**Comment by cbjeukendrup** [comment]
> 1\. The part names (orange in screenshot below) are not synced with the instruments names (yellow in screenshot below).
>   When renaming an instrument, the part name stays the same.

The things you see in the Instruments panel and the things that you see in the Parts window are not the same. There is in general no one-to-one relation between them, but a many-to-many relation: one Instrument may be printed in multiple Parts (i.e. "part scores"), and a "part score" can contain any number of instruments.

For that reason, the names of the "part scores" are not directly linked to the names of the instruments. 
However, we could enhance this in the future, so that _if_ a "part score" contains only one instrument, then the name of that part score follows the name of that instrument by default (but the user can still customise it).



> 2\. Part names are not stored in the save file.
>     When renaming a part in the Parts dialog, the new name is not stored in the project file.

As far as I can see, this only applies parts that have never been opened yet. This is the result of some technical difficulties that are explained here: https://github.com/musescore/MuseScore/pull/20702#issuecomment-1883954363. Solving it would be very non-trivial, unfortunately.

**Comment by vHeemstra** [comment]
@cbjeukendrup Thank you for the great answer!

And do you know why the Mixer channel names are not synced with the instrument names? (I assume they are linked 1:1)

**Comment by cbjeukendrup** [comment]
For the record, I found that there is some duplication between this issue and #15660, #16962, and to some extent #14341 and #19466.
And #21255 might be technically related.

**Comment by zacjansheski** [comment]
Let's close this and refer to 
https://github.com/musescore/MuseScore/issues/16962 (in depth discussion)
and
https://github.com/musescore/MuseScore/issues/14341 (feature request)
