### ISSUE TITLE
Tab key should move focus to next field instead of OK button at Project properties dialog window

### ISSUE THREAD

**Issue by shoorick** [musescore/MuseScore#21878]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Dialog window “Project properties” has a lot of text input fields. Pressing `Tab ↹` button inside these fields moves focus to `OK` button but this behavior is wrong because an user expects that focus moves to next field.

### Steps to reproduce

1. Open existing scores or create new one.
2. Open the dialog: File → Project properties
3. Click to any text field
4. Press `Tab ↹` button

### Screenshots/Screen recordings

![musescore-properties-tab-order](https://github.com/musescore/MuseScore/assets/190892/634b5b1a-cbf1-4612-a30b-7fdacb7e24c5)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Debian GNU/Linux 11 (bullseye)

**Comment by MarcSabatella** [comment]
This is currently by design - MuseScore has moved to a hierarchical model used by other applications, where Tab moves between *groups* of controls but cursor keys move *within* groups.  This allows one to traverse larger windows more quickly.

It’s been suggested that some dialogs should perhaps be excluded from this, and this could potentially be one such dialog, but anyhow, definitely you’ll want to adjust expections to use cursor keys as well as Tab (and F6 for an even higher level navigation in the main window).
