### ISSUE TITLE
Shadow beneath menus missing in master (Qt6)

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21920]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

There is a shadow beneath menus in 4.3, that shadow does not appear in 4.4

### Steps to reproduce

1. In 4.4, right click the score, notice a shadow does not appear beneath the menu
2. Same for menu in mixer (three dots or other menus)

### Screenshots/Screen recordings

4.3 (notice shadow beneath menu)
<img width="220" alt="Screenshot 2024-03-13 at 12 03 31 PM" src="https://github.com/musescore/MuseScore/assets/69917893/e9407141-74b0-49e8-bc63-32967b0d8325">
<img width="370" alt="Screenshot 2024-03-13 at 12 05 53 PM" src="https://github.com/musescore/MuseScore/assets/69917893/f1abbc12-f25c-4f0a-8a7e-6faec665d16c">

4.4 (no shadow beneath menu)

<img width="214" alt="Screenshot 2024-03-13 at 12 03 08 PM" src="https://github.com/musescore/MuseScore/assets/69917893/8db689dc-293a-49f3-82fe-d6523f190729">

<img width="381" alt="Screenshot 2024-03-13 at 12 06 04 PM" src="https://github.com/musescore/MuseScore/assets/69917893/c24d0fe7-f6a6-4b67-a732-b84d6bd4b1c7">

### MuseScore Version

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.4.0-240730302, revision: github-musescore-musescore-6d832aa

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

### Additional context

Qt6 issue

**Comment by cbjeukendrup** [comment]
Same with popups and undocked panels (like Palettes). 

The reason is that the shadow component gets the same "theoretical" size as the menu/popup/panel, and since Qt 6 it is apparently clipped at its theoretical size. In Qt 5, that was not the case, so there the shadow component was allowed to go visually beyond its theoretical size so that you could see the shadow.
I have a commit somewhere to fix it for dock panels, but not yet for menus/popups, although a similar fix would apply there.

**Comment by avvvvve** [comment]
While we're at it, it would be great if the shadow on nested context menus would sit under the entire group of context menus rather than overlapping the last level up.

<img width="189" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/b3cb5896-6f14-425f-943b-278778c127c9">

**Comment by cbjeukendrup** [comment]
@avvvvve Unfortunately, that seems difficult to change. However, personally I like it the way it is. It makes it namely clear which one is the submenu and which one the parent menu (the submenu sits "on top" of the parent). That is crucial for keeping things clear in situations with deeply nested menus on small screens, where submenus may open to either side and may start overlapping. 
Also, note that the native menus in macOS also have the shadows this way.

**Comment by avvvvve** [comment]
@cbjeukendrup Ok, I'm convinced! I've never noticed that about macOS. They also actually have a bit of pixel overlap rather than just sitting directly next to the previous menu—even nicer for recognizing stacking order. Noting that in case we ever revisit context menu designs.

<img width="538" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/70b4f319-f5b6-4b86-bcac-f54d48201a82">
