### ISSUE TITLE
Remove "Exclude from parts" and "Exclude from score" properties for Staff text

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#21941]
These options should be removed because when turned on for Staff text with a sound flag attached, the sound flag is also hidden in the score/part, but its playback effects are still heard. Users can rely on unsyncing "Style/appearance" and turning visibility off to achieve the same result but retain the visibility of the sound flag button.

Ideally, to make sure this change does not affect the appearance of older scores where these checkboxes have already been used, we should do the following:

- If Staff text in the **main score** has "Exclude from parts" turned on, for the corresponding Staff text in the **part**, turn off the "Style/appearance" toggle in synchronization properties and uncheck "Visible"
- If Staff text in a **part score** has "Exclude from score" turned on, for the corresponding Staff text in the **main score**, turn off the "Style/appearance" toggle in synchronization properties and uncheck "Visible"

![image](https://github.com/musescore/MuseScore/assets/20806406/084dc5b4-d84b-454e-b208-530f559055cd)

**Comment by lgvr123** [comment]
Why impacting all the Staff Texts while you would only address the "Sound flags staff texts" ?

**Comment by shoogle** [comment]
@lgvr123, the exclude property isn't needed for staff text because you can simply make it invisible. Exclude is only needed for things like clefs and ottava lines that impact the surrounding elements.

For example, if you make a bass clef _invisible_, later notes stay where they are as if the bass clef was still there. But if you _exclude_ a bass clef then later notes move to their treble clef positions.

Staff text doesn't affect the appearance of surrounding objects, so excluding it is no different to making it invisible.
