### ISSUE TITLE
Install from Microsoft Store shouldn't require admin rights

### ISSUE THREAD

**Issue by jian-x-li** [musescore/MuseScore#21956]
### Your idea

v3 MuseScore doesn't need admin right when installing from Microsoft Store, but v4 requires it. This prohibits users who don't have Windows admin rights to install MuseScore v4, for example, students in a school.

### Problem to be solved

Remove admin rights requirement when installing from Microsoft Store.

**Comment by cbjeukendrup** [comment]
The difference probably arises from the fact that MS3 was packaged in a very special way for the Microsoft Store. Nowadays, the Store also accepts apps packaged in the classical way (namely as a .msi installer) but that has the consequence that an admin password is needed.
However, I'm afraid we won't return to that very special way of packaging that MS3 used, because that's very complicated. (That was also the reason that MS3 was almost never updated in the Store.)
