### ISSUE TITLE
App icon and group windows on Ubuntu

### ISSUE THREAD

**Issue by metemaddar** [musescore/MuseScore#21996]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

In Ubuntu 22.04, When I open MuseScore 4.2.1 app image, it doesn't have icon. it uses the cog icon instead. Also when I need more than one window, for example multiple scores, it doesn't group them and shows new cog icon. I have added a desktop icon for it to applications, but it is used only to lunch and doesn't used for the software itself. Also it would be great if the MuseScore were opened on top of the app icon instead of openning in new icon.
![Screenshot from 2024-03-20 15-11-04](https://github.com/musescore/MuseScore/assets/3726265/1a729f32-2110-4834-a055-57f24fa886e6)

### Steps to reproduce

On Uubuntu, open the MuseScore 4.2.1 by it's app image.
You can also add a desktop icon for it like the following:

```
[Desktop Entry]
Version=4
Name=MuseScore
Exec=~/Downloads/MuseScore-4.2.1.240230938-x86_64.AppImage
Icon=~/Downloads/musescore.512x512.png
Terminal=false
Type=Application
Categories=Utility;Application;
```

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

Ubuntu 22.04

**Comment by MarcSabatella** [comment]
Did you install the AppImage by running it with the "install" option?  That should create the necessary desktop integrations automatically, and does for me on Debian.  The one you created manually has the wrong Name and is missing other necessary info likeStartupWMClass.

**Comment by metemaddar** [comment]
@MarcSabatella 
Unfortunately, I did not see any option to install the AppImage on Ubuntu 22.04. I think maybe you mean the `.deb` file. Because frome chatGPT:

> Installation of the AppImage: AppImages are designed to be portable and don't require installation in the traditional sense. You can simply download the AppImage file, make it executable, and run it. The "install" option you mentioned might refer to creating desktop integrations, which you can achieve by creating the .desktop file as described above.

Also I tried to change the MuseScore desktop file to the following as chatGPT suggested for the StartupWMClass but it has the same behaviour as before:

```
[Desktop Entry]
Version=4
Name=MuseScore
Exec=~/Downloads/MuseScore-4.2.1.240230938-x86_64.AppImage
Icon=~/Downloads/musescore.512x512.png
Terminal=false
Type=Application
Categories=Audio;AudioVideo;Music;GTK;
StartupWMClass=MuseScore
```

**Comment by MarcSabatella** [comment]
To install the \AppImage for MuseScore, just run it from the terminal normally with the "install" command-line option.  Instead of checking ChatGPT, try the MuseScore 4 Handbook.  Here's the relevant info: https://musescore.org/en/handbook/4/download-and-installation#AppImage

As I mentioned, your "Name" field is wrong, and that's also why your window manager can't make the association.  You also have the incorrect icon it seems, and your Exec line is missing the parameter to allow it to open scores via file associations or the "Edit on desktop" function on musescore.org.

Again, it's much better to just let MuseScore do the install automatically - it does all of these things automatically (including actually settings the file associations).

For further questions about how to use MuseScore, please ask on the Support forum at musescore.org

**Comment by bkunda** [comment]
Closing for now as it seems like more of a support issue than a bug. 
If it is indeed a systemic problem, we'll re-open the issue.
