### ISSUE TITLE
Home/Score/Publish tab width should be determined by text's width when bold

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22055]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

In the Home/Score/Publish tabs, text is regular weight when the tab is not in its active state and bold when active (or in the case of Score, bold when a score is open).

Because of this, the width of each individual tab changes when selected/deselected and it causes a slight horizontal shift.

We should set the width of the text container based on its width when the text is bold and always center the text, so that when the text is regular weight, the width of the tab does not change.

- Make sure this works with different languages. The width should not be determined just by the English tab labels.

### Steps to reproduce

Click between the Home/Score tabs

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20806406/fd581299-6c8e-4509-9860-0dc717964d8a

### MuseScore Version

4.2

### Regression

No.

### Operating system

macOS 14.1.1

**Comment by daijingz** [comment]
@cbjeukendrup @avvvvve Let me fix this issue, not sure whether #11335 is completed or not. If it does not need any additional work, I will work on this.

**Comment by avvvvve** [comment]
That would be great @daijingz! I just added one note to make sure that this works with any language. Thanks!

**Comment by cbjeukendrup** [comment]
@daijingz I was thinking it would be a good idea to use `FontMetrics` for this issue: https://doc.qt.io/qt-6.2/qml-qtquick-fontmetrics.html

**Comment by daijingz** [comment]
@cbjeukendrup I forgot this section's name, which tab bar is it? The first step is, I am directly using the keywords "home", "score", and "publish" to search in the program bases, but I found a lot of files have these strings. But there is no better source to discover the corresponding code positions. Do we have any keys for these three tabs?

@avvvvve From observation, it is clear that this bug does not occur on Windows (since my machine is Windows, and I did not see such errors during testing). I guess the problem takes place on the QML file specializing in the MacOS system.

**Comment by SirKuzalot** [comment]
Would it be alright if I was assigned to this issue? I was looking through the qml part of the code and I believe I have found a fix using the TextMetrics you mentioned within the definition of the PageTabButton, as making changes purely on the aforementioned file caused a problem with the buttons' position on the page

**Comment by cbjeukendrup** [comment]
Unless @daijingz has a PR ready (@daijingz please let us know), feel free to create a PR!

**Comment by daijingz** [comment]
> Would it be alright if I was assigned to this issue? I was looking through the qml part of the code and I believe I have found a fix using the TextMetrics you mentioned within the definition of the PageTabButton, as making changes purely on the aforementioned file caused a problem with the buttons' position on the page

Giving Solutions so quickly!

**Comment by cbjeukendrup** [comment]
> Giving Solutions so quickly!

@daijingz I don't understand what you mean. Do you mean that you will open a PR very soon (like, today), or do you mean that @SirKuzalot was very quick and therefore he can open a PR instead?

**Comment by daijingz** [comment]
My attempt: ONLY AT `src/appshell/qml/MainToolBar.qml`
![KBCLR07U%WWU()Y NG~D~~R](https://github.com/musescore/MuseScore/assets/61481741/4608a671-cf50-4735-aa47-60036a98e6f2)
Here is the update:
![D%A B$QE2Y{( MSS%UKXORW](https://github.com/musescore/MuseScore/assets/61481741/c1a434e6-b1e3-47a1-9211-644f527ac6ce)
Here I define a new font metric, to receive updated title width and resize the metrics. It is error-free on syntax, but I did not submit my PR because I have not tested this. My machine has some implementation problems. @cbjeukendrup Very sorry to say.

**Comment by daijingz** [comment]
This is my error: (The same error before and after my modifications)
![9}A%Q4CV@XJ@XHV}EMKW1Z3](https://github.com/musescore/MuseScore/assets/61481741/f99bdbd2-9477-43e5-bff5-e524d7a4f2ae)
(Just ignore those unrecognizable words because I have already switched the language to English, but there are still some other languages' words.) I rebuilt several times, sometimes 5 errors, sometimes 9 errors, and sometimes even 17 errors.

I did not change anything, I just updated the MuseScore day by day, and after updates, these errors occur. Before rebuilding and re-opening options made sense, so I did not spend so much time on this. But this time, the situation is strange.

@SirKuzalot If you can please try my code, I know your solutions may be well working for this issue, but changing general files may result in other code section modifications.

@cbjeukendrup code is ready but has not been tested, please decide for me: whether or not I should submit it now.

**Comment by SirKuzalot** [comment]
@daijingz Though it is true that changing the general file could be problematic, I chose it as a solution for this problem, not only because purely changing the size of the buttons in the main tool bar seemed to offshift the buttons, but also because the problem presented would be common to any buttons that made use of the component I altered, as the buttons themselves were set to change size

**Comment by daijingz** [comment]
I guess this issue is completed, is that correct?

**Comment by cbjeukendrup** [comment]
https://github.com/musescore/MuseScore/pull/22132 has not yet been merged, so therefore it isn't closed yet, but yes, it's pretty much completed.

**Comment by daijingz** [comment]
@cbjeukendrup I do not know why my answer has some problems here, because the program just terminates without error messages. I did not find some syntax errors, but do I change in the correct place (I mean my modification positions)?

**Comment by daijingz** [comment]
@cbjeukendrup meet something wrong, fixing it.

**Comment by cbjeukendrup** [comment]
@daijingz It seems something was wrong; see #22610. But the reason that this problem didn't happen to us is probably that you hadn't re-run the CMake configure step after rebasing. 
Anyway, let's please have this discussion on Discord in #development, because it isn't related to this issue.

**Comment by cbjeukendrup** [comment]
@avvvvve Now that there is a working solution in #22055, I realised that this has the implication that the spacing becomes uneven. Currently, the padding between the boundary of the button and the text is some fixed amount of pixels. Making the button as wide as it would be when the text is bold, means necessarily that some extra padding will be added when the text is not bold: half of the difference in width between the bold and non-bold text is added to each side. Since this difference naturally varies per word, that may produce uneven results. Here is Dutch for example:
<img width="521" alt="Scherm­afbeelding 2024-04-29 om 00 41 08" src="https://github.com/musescore/MuseScore/assets/48658420/03e6d288-9c9f-4433-8033-33aff623aaa1">
This seems not a technical limitation, but a geometrical limitation.

So, it's a trade-off between this unevenness and the changing width when changing tabs. What do you think?

**Comment by daijingz** [comment]
@cbjeukendrup I feel if this is a question about choosing one option from binary choices: the mentioned unevenness and the changing width when changing tabs, then changing width is a better choice.
Because if following our original design (not only my attempts but also @SirKuzalot attempts), the button length is a fixed number, meaning that it can only capture the text no longer than its length.

Although all texts are short words, I wonder if some available languages translate them into long, long strings, the fixed length may not display the complete text.

**Comment by cbjeukendrup** [comment]
The width is _not_ fixed; it is calculated based on the text. So no text clipping will occur. 
Anyway, my question about which option to choose was primarily intended for @avvvvve.

**Comment by avvvvve** [comment]
@cbjeukendrup Short answer: I'd say the slight difference in spacing that results from this change will mostly be trivial—I'm not sure I would've noticed it in your screenshot if it hadn't been pointed out. So let's move forward with this solution!

Long(er) answer:
The difference is most obvious in the space to the left of "Ontwikkelaarstools" since that's the longest string and therefore has more extra padding, but most users won't see that option anyway since it's only in the development builds. I am taking a bit of a leap in assuming that the other three tabs titles will be shorter than that in most languages, and even if they are super long, ideally we (i.e. translators) should find shorter labels since these tabs shouldn't take up a ton of horizontal space anyway.

**Comment by SirKuzalot** [comment]
For what it's worth, Portuguese (in which I have the program set) has one of the longest strings in that part (I forget the exact wording but it's at least 20 characters) and the padding is not all that significant

**Comment by avvvvve** [comment]
Right, and that's still the DevTools tab which won't be seen by non-dev users (not to say devs don't deserve a beautiful app too - but it's still better than the tabs jumping, IMO 😄)

**Comment by daijingz** [comment]
Oh yes, sorry I misunderstand the mentioned problem. The padding is just a few pixels and it won't take much space (minimized effects).
