### ISSUE TITLE
Can’t play from beginning after the first time entering notes

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22068]
### Issue type

General playback bug

### Bug description

The first time you add notes to a new or existing score, you can’t rewind to the beginning.

### Steps to reproduce

1. Make a new score and enter a few notes into it.
2. Click rewind, or exit Note Input Mode and select the first element in the score, like the clef or key signature, or even the first note.
3. Hit play and hear error: It plays back from the last note entered, and not from the beginning

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/43882ee9-0430-4e54-93c2-3c249e6cf690

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 12.7.2

### Additional context

It’s only the first time you enter notes into the score that it doesn’t work—it works fine from then on until you reopen the score, or create a new one.
Note: if you click the second note, it plays back from that position, just not if you click the first note.
This behavior was present in 4.2, but not 4.1

**Comment by dcorson-ticino-com** [comment]
I see the same behaviour under Win10.
It happens both with MuseSounds and the MS-Basic soundfont.
It appears to be independent from the problem with MuseSounds that the first note is often not played completely, i.e. often starts to late so it is short.  In the meantime I start every piece with a quarter rest so that the entire first played note is heard.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

**Comment by Grillzombie** [comment]
I have this issue too on 
OS: Linux Mint 21.3, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

**Comment by Riley-Sullivan** [comment]
Should a priority marking be added to this, or not?

**Comment by Eism** [comment]
Was fixed for master, ported to 4.3
See #22330
