### ISSUE TITLE
Notes not played when using MuseSounds 

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#22109]
### Issue type

Muse Sounds bug

### Bug description

C4 notes in left hand, measure 21-23 are not played when using MuseSounds.

Changing the C4 in the right hand to a D4, makes them play but then the D4 in measure 23 is missed.

[Salsa Amigo - Piano.mscz.zip](https://github.com/musescore/MuseScore/files/14807832/Salsa.Amigo.-.Piano.mscz.zip)

### Steps to reproduce

Use the attached score to check

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
This is because the notes overlap the notes of the same pitch on the other staff.  This had been a long-standing Muse Sounds issue finally fixed not so long ago, but is awaiting the release of 4.3 & Muse Sampler 0.6.  See https://github.com/musescore/MuseScore/issues/15306 and various other duplicates.

**Comment by henkdegroot** [comment]
Thx, I did search but did not find an issue like this. I will close this one.
