### ISSUE TITLE
When switching to the "Hands-Free AG Audio" from an Bluetooth audio device, it creates a spooky sound

### ISSUE THREAD

**Issue by Fastball2880** [musescore/MuseScore#22118]
### Issue type

General playback bug

### Bug description

When switching to a "Hands-Free AG Audio" from Musescore, the playback slows down and it creates this weird, spooky sounds. However, when using this device (from the Hands-Free AG Audio) from other sources, it plays as the same as normal (YouTube, Spotify, etc.)

I wanna know if this occurs to other devices that uses Bluetooth, as this features on devices that has this when getting a call from someone, by switching it to that particular audio source.

### Steps to reproduce

1. Go to Edit > Preferences > I/O
2. Switch it to the device that has a "Hands-Free AG Audio"
3. It should play as normal, but only to produce spooky sounds

### Screenshots/Screen recordings

**WARNING - LOUD AUDIO WHEN USING HANDS-FREE AUDIO SOURCE**

https://github.com/musescore/MuseScore/assets/147415340/4f963634-2a30-4be4-8fa7-94446320192f

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10 Pro

### Additional context

Speaker I used - https://www.jbl.com/bluetooth-speakers/JBL+GO+2.html

**Comment by cbjeukendrup** [comment]
Maybe there is a very big difference in the sample rates used by these two devices and MuseScore fails to handle that correctly. If you could find out which sample rates the devices use, that could be useful.

**Comment by cbjeukendrup** [comment]
8000 Hz seems a relatively low sample rate, so that makes my hypothesis slightly more likely. 

What if you connect to the bluetooth audio device first, and then close and restart MuseScore? Does it sound better then?

(If yes, then if you switch back to internal speakers while MuseScore is still running, you would probably get something very high-pitched and sped up.)

**Comment by RomanPudashkin** [comment]
We suspect it may have been fixed in https://github.com/musescore/MuseScore/pull/23954. Could you please check it on the latest 4.4 nightly? You can download it here:
https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D

You need to have MuseSampler 0.100+ if you want to test Muse Sounds. Thanks!

**Comment by zacjansheski** [comment]
Closing, no response
