### ISSUE TITLE
Implement new dynamics & hairpins positioning properties, style settings, and preferences

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22175]
### Task description
Time to implement new properties, style settings, and preferences for automatically (or if a user so chooses, not) repositioning dynamics & hairpins relative to their respective voice AND centering dynamics & hairpins on multi-staff instruments.

The full Figma spec & prototype will be sent on Slack shortly. As JLo would say, Let's Get [More Precisely] Loud.

<img width="915" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/e0c2d1a0-1afd-4587-8b96-4bedc0ac28c9">

**Comment by Dima-S-Jr** [comment]
Please take into account the automatic alignment of the text of technical instructions and dynamics (especially in two-staff parts). If the indication applies to the entire part, then it should be vertically aligned strictly in the center between the staffs, and not closer to the staff to which it is added, which is currently happening in Musescore.
![21-47-07](https://github.com/musescore/MuseScore/assets/134041121/4a38c378-02fe-4440-843b-56f6d682231b)
I also ask you to take into account that users, if desired, can create not only a two-staff part, but three, four or more, and it will be ridiculous if you add one indication to one staff and assign it to the entire part. If there are three or more note carriers, then I see only one way out here: to force the program to automatically duplicate the indication under all the staffs of the part, which will be logical. But in this case, it is not necessary to resort to an alternative method of notation by marking with an enlarged indication over the entire part. This can only be applied to the instrument section in the full orchestra score, but not to a single part!
![Снимок экрана (269)](https://github.com/musescore/MuseScore/assets/134041121/b72c19fc-8e87-49a8-b0ec-317950afeaf3)

The indications should be as close as possible to the voices to which they are assigned, and this should happen automatically (and not so that the user manually adjusts each label to the appropriate note). Regarding the different instructions for each staff of the same batch, I recommend setting the following rule for the program: in order to distinguish between dynamic instructions and technical instructions of a two-staff part combined with a curly brace, all instructions related to the 1st voice of the upper staff are automatically placed above the upper staff, and all instructions related to the 1st voice of the lower staff is automatically placed above the lower staff; for 3 and 4 and further voices, the instructions are placed in close proximity to the anchor point (and in a cramped situation to the left, but not to the right). Ideally, these instructions will also be distinguishable by scale (depending on which voice number they are attached to, for example, 1st voice: scale 100%, 2nd voice: scale 80%, etc.).
![Снимок экрана (268)](https://github.com/musescore/MuseScore/assets/134041121/2b334757-e985-4c9a-bb23-248275d945a5)

And finally, the most important thing. In the score, there can be two staffs in one part, intended for a divided part (string-bow, wind, etc.). I ask you to make sure that if the user selects a binding to the entire part (two-staff) in the properties, a small curly brace is automatically entered, which is exactly what it is intended for (in the SMuFL, it is called both _Brace_ (to begin with) and _Reversed brace_ (to end)). At the same time, I also ask you to ensure the automatic alignment of such the brace between the staffs both in the Cartesian coordinate system and in scale. Please note that this can only be applied if the part is presented as divided for a group of instruments (in the orchestra it is united by a secondary bracket) and has two staffs (but in no case keyboards or any others united by a curly brace!). This is usually either a string-bowed part or a wind instrument. If it is 3 or more staffs, then in this case the option that I described above should work. Unfortunately, I do not fully understand the sequence in which these small curly brace should be arranged, since in different musical examples these brackets are placed differently (either before dynamic/technical instructions, or after), however, I am more inclined to believe that these braces should stand before the instructions + we must not forget about the reversed curly brace, for example, before the indication, which refers to the staff, and not to the part.
![Снимок экрана (270)](https://github.com/musescore/MuseScore/assets/134041121/0a4883a6-b49a-4399-80d5-df03528e7c36)

@oktophonie, I really ask you to take all this into account when implementing this new property. This should apply not only to dynamic notation, but also to verbal technical instructions (from the "Text" palette), since I very often need to indicate (for example) that the first voice sounds like _arco_, and the second like _pizz._. And then I can give you an infinite number of examples, but I think you get it. If you find it necessary, you can publish it as a separate issue. (but it's up to you).

**Comment by oktophonie** [comment]
@Dima-S-Jr This is already a defined task. By all means suggest minor changes to it, but if you want significant extra functionality, raise it as a separate feature request. (And it would be nice if you wouldn't spam us constantly with those either; there might be some chance of us getting to some of them if you didn't post several per day.)

**Comment by Dima-S-Jr** [comment]
> @Dima-S-Jr This is already a defined task. By all means suggest minor changes to it, but if you want significant extra functionality, raise it as a separate feature request. (And it would be nice if you wouldn't spam us constantly with those either; there might be some chance of us getting to some of them if you didn't post several per day.) In this case I'm removing the enormous essay you've posted here as it's quite inappropriate.

Simon, you have a very strange policy. I posted a comment directly related to the issue topic. I spent time and study on it, and you just took it and deleted it. Why is this inappropriate here? Can only contributors write here, or do you have some kind of limit on the number of text posts in your repository? I don't understand this. If so, give me a link to this policy and I will review it.
Anyway, I don't see any violations in my publications. Unlike the spammers here, I write only on business, isn't that what the repository for Musescore was created for? And I don't have a task to publish something every day. I post as I find problems in Musescore that I consider relevant and need to be resolved. At the moment, I no longer notice anything that could be re-published by the issue. Except for the fact that you deleted my comment, which had important information in terms of engraving. Of course, I will publish it in a separate issue, since you don't want to see it here. And as you can see, duplicates are not found in my latest issues, because I carefully study all the content in this repository and I am very glad that some relevant issues are also highlighted here. 
And I also don't understand why you don't like the excerpts from Elaine Gould's guide? Yes, maybe you can read these excerpts in the book yourself, but I'm not writing all this just for you alone. There are a lot of people who besides you are watching all these issues. If there are no examples from official sources, then my issue on changing the engraving may be considered irrelevant, since there is no evidence of standardization of what I propose, and my issue will be shelved (if they do not forget about it at all). 
Once again, I'm writing about the case. This is not spam. I compose issues only on the most relevant topics, and not on all the little things. I hope that all of this will eventually be implemented in Musescore. I respect your and other participants' contributions to the development of Musescore. This is a wonderful program! The interface is simple and very user-friendly (unlike Sibelius and Finale, as @Tantacrul once mentioned). Therefore, do not be afraid of my issues. Do everything on your own and as far as possible, but do not forget at all. Sorry for writing this here. I know that you will delete it. But I can't contact you personally, Simon, because I don't know how to do it. And please, in the future, let me know where I can write and where I can't, because I respect my time and it's not in my best interest to publish anything if it's deleted. As you put it, the "essay" that was deleted here was very important in terms of appropriate notation. And you just deleted it. You could save it or publish it in a separate issue (I suggested it to you).

**Comment by mike-spa** [comment]
@Dima-S-Jr let me clarify something.
1. Tasks like this one come directly from the internal team. They are well-defined projects that often taken weeks/months of study. We welcome suggestions, but we don't need your additional "time and study" on top of it. We have a team of professionals, we know what we're doing.
2. You have opened 63 issues in 3 months. _Nobody_ does that, and communities less welcoming than ours could have already banned you for that. You have to understand that triaging and classifying issues is a process that itself takes time, effort and resources. Opening dozens of feature requests does _not_ help us, it _wastes_ those resources.
3. You overestimate the importance of your contribution. You are one person who logged 60 issues: we have 2500 of them. And most of those 2500 are actual issues. Most of yours are feature requests. 
4. You overestimate the importance of your opinions. A 2000 words essay on what you whink we should do is not a groundbreaking innovatively researched eye-opener, it's just a 2000 words opinion. If we get one of those every other day, it's also a 2000 words waste of time, cause nobody is ever going to be able to read everything you post, let alone implement it.
5. How we prioritize issues is up to us, because, again, we know what we are doing and because, again, nothing makes your issues more important than the other 2500. Shouting at us "please deal with this" is extremely annoying for all of us and all but guarantees that you'll be ignored.
6. Behind Bars is not a bible, reading Behind Bars does not make you an engraving expert, and posting screenshots from the book does not constitute "research". We _make_ the engraving guidelines, we don't read them in Behind Bars. And we don't want people to think we do, hence why we remove the screenshots.

End.
