### ISSUE TITLE
Line spacing is too wide

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#22189]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Line spacing is now too wide, shown here in 4.4 master (4 Apr nightly) with composer and stave text:
![image](https://github.com/musescore/MuseScore/assets/20604032/2c69645c-8d01-43cd-bae5-231c25c60136)
(Line spacing is defined as 1.0li in each case, as usual)

Here in 4.3 (4 Apr nightly), which also matches previous versions and is as expected:
![image](https://github.com/musescore/MuseScore/assets/20604032/a87c9ce3-bebd-4d09-9991-5eee778dfd17)

I first noticed this around 7 March.

### Steps to reproduce

1. Create a new score
2. Add some text which has line breaks in it

### MuseScore Version

master (4 April, MuseScore version (64-bit): 4.4.0-240950306, revision: github-musescore-musescore-6af0ba1, but have noticed this earlier)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux; also reproduced on Win 11

**Comment by bluebear94** [comment]
Bisecting indicates that the regression happened between d9218609b20bb01cb597e2a01cf85080c673eab7 and 7f2956a9b2d3338e3a10c635f8115ba771036661. Unfortunately, a lot of the commits in between had to be skipped as they either failed to build or crashed on startup.

**Comment by mike-spa** [comment]
I've investigated this issue. I'll write here what I've found just so we have a trace of it.

Like we thought (or at least as far as I can tell) the issue originates from the switch to Qt6 (@cbjeukendrup @igorkorsukov you may want to be aware of this too). 

In Musescore the line spacing of text is determined by `FontMetrics::lineSpacing()` which is just a wrapper around to `QFontMetrics::lineSpacing()`. The [Qt documentation](https://doc.qt.io/qt-6/qfontmetrics.html#height) says that: `lineSpacing = height + leading` where `height = ascent + descent`.

The problematic quantity here is this so-called "leading", which should represent the "additional vertical space" between text lines. Consider these examples (top is version 4.3, bottom is 4.4):
![Screenshot 2024-05-15 135518](https://github.com/musescore/MuseScore/assets/93707756/25c008bc-9b26-4a2e-85e0-d21b8a2f45ab)
![Screenshot 2024-05-15 132756](https://github.com/musescore/MuseScore/assets/93707756/3500ed67-db5e-4078-bdd9-04da4f0fe711)

In Musescore 4.3, QFontMetrics returns the following:
```
Edwin  -> ascent = 55.79; descent = 15.09; leading = 0.00;
Arial  -> ascent = 45.26; descent = 10.59; leading = 1.64;
NCS    -> ascent = 48.25; descent = 12.50; leading = 0.00;
```
In Musescore 4.4 (which uses Qt6), QFontMetrics returns the following:
```
Edwin  -> ascent = 55.79; descent = 15.09; leading = 10.0;
Arial  -> ascent = 45.26; descent = 10.59; leading = 1.64;
NCS    -> ascent = 48.25; descent = 12.50; leading = 10.0;
```

Now, not only did the "leading" value change inexplicably from Qt5 to Qt6 (for 2 out of 3 of the fonts), but it's also impossible to understand _where_ Qt is getting this value (couldn't find anything in the documentation). 

Here is the font metadata for Edwin:
<img src="https://github.com/musescore/MuseScore/assets/93707756/066e5289-950f-4f90-a766-9b26aec67e1c" width=400>
Arial:
<img src="https://github.com/musescore/MuseScore/assets/93707756/e40c3ca4-fb78-41bc-9f2c-940858c0dff9" width=400>
NCS:
<img src="https://github.com/musescore/MuseScore/assets/93707756/daad9d65-44db-4c31-86e6-6bf8a45e61a2" width=400>
taken from a different program. 

By doing some proportions, it's clear that `QFontMetrics::ascent()` is returning the "safe top" property, and `QFontMetrics::descent()` is returning the "safe bottom". However, `QFontMetrics::leading()` seems to be returning random stuff: in Qt6, it returns the "line gap" property for Edwin and NCS. But in Qt5 it returns zero for both of them. And in both versions it returns a value for Arial which seems to come out of nowhere.

My conclusion is that Qt has some problem with fonts, and that we should consider `leading()` (and therefore also `lineSpacing()`) to be unreliable. So, even though technically it would be correct to use `QFontMetrics::lineSpacing()`, I think our safest bet is to use `QFontMetrics::height()` instead. It will make things look like they did before (given that the leading of Edwin used to be zero), and for all the fonts I've tried the resulting line distance looks completely fine (also because the leading is generally quite small anyway). Plus, the user can always customize the line distance.
