### ISSUE TITLE
Poor score rendering quality

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#22244]
### Issue type

UI

### Steps to reproduce

0. (Change the display scaling setting to a specific scaling)
1. Open any score
2. Look at staff lines

### Screenshots/Screen recordings

4.4.0 (master)
![スクリーンショット 2024-04-07 122911](https://github.com/musescore/MuseScore/assets/139459177/35a10ff3-9a49-4c89-8a4c-d717f4c6fe0d)

4.2.1
![スクリーンショット 2024-04-07 123023](https://github.com/musescore/MuseScore/assets/139459177/d0cb4641-efb7-44b4-9867-435780cf528f)

### MuseScore Version

latest nightly (master)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

It seems to happen only with certain display scaling. On my 2880x1920 display, it only occurred when set to 150%.

**Comment by cbjeukendrup** [comment]
Probably related to Qt 6. 

In Qt 6, a lot was changed w.r.t. handling of UI scaling. Compare https://doc.qt.io/qt-6/highdpi.html to https://doc.qt.io/qt-5/highdpi.html (which only describes the user-exposed aspects, but still; since it was rewritten so extensively, it seems reasonable to assume that a lot changed under the hood too).

For this reason, I wonder if the unusual-looking stuff in `muse::uicomponents::QuickPaintedView` is still needed or that it's only causing trouble now.

**Comment by nmu-nyasan** [comment]
It was fixed between July 5 and July 6 nightly, so I will close this issue.

**Comment by cbjeukendrup** [comment]
> between July 5 and July 6 nightly

Then it has most likely been fixed by https://github.com/musescore/MuseScore/pull/23438! Nice!
