### ISSUE TITLE
Scheduled CI builds for 4.3.0 fail

### ISSUE THREAD

**Issue by rettinghaus** [musescore/MuseScore#22400]
### Issue type

Other type of issue

### Bug description

The scheduled CI builds for 4.3.0 fail because it looks for the `buildscripts` folder which is missing on that branch.

### Steps to reproduce

- https://github.com/musescore/MuseScore/actions/runs/8683679622/job/23810066524
- https://github.com/musescore/MuseScore/actions/runs/8683678179/job/23810063474
- https://github.com/musescore/MuseScore/actions/runs/8683681205/job/23810069707

### MuseScore Version

4.3.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

all

**Comment by Jojo-Schmitz** [comment]
That may be the reaseon why the latest nighly builds for 4.3.0 don't download the correct translations (@cbjeukendrup): they are 3 days old by now

**Comment by Jojo-Schmitz** [comment]
Fuxed by 42b4ceb?

**Comment by Jojo-Schmitz** [comment]
> That may be the reason why the latest nighly builds for 4.3.0 don't download the correct translations (@cbjeukendrup): they are 3 days old by now

Yes, it sure is, the latest 4.3.0 nightly is 10 commits behind the one that updated the translations URL

**Comment by cbjeukendrup** [comment]
Aha, that explains it indeed. 

The problem is that the CI workflow from master is used and tries to check out the 4.3 branch, which is obviously incompatible. There must be better ways to run scheduled actions on non-master branches. I was going to look into that anyway because I need it for something else too. 

@igorkorsukov To be honest I'm not so sure about the solution from https://github.com/musescore/MuseScore/commit/42b4ceb12ec518e94fd11fb05f52229f36f622d8... I think it would be better to create a different workflow on the master branch; make that scheduled; then in that workflow, trigger the nightly CI actions using the GitHub API.

**Comment by igorkorsukov** [comment]
fixed 
![image](https://github.com/musescore/MuseScore/assets/3818029/224d9f7a-d875-4118-bd47-5dc4af8aeeac)

**Comment by Jojo-Schmitz** [comment]
Can you upload them (their artifacts)  too?

**Comment by igorkorsukov** [comment]
> Can you upload them (their artifacts) too?

I don't quite understand the question, are you asking if the artifacts are downloaded? - Yes

![image](https://github.com/musescore/MuseScore/assets/3818029/142c091e-bebb-4157-be1e-c597cead4428)

**Comment by Jojo-Schmitz** [comment]
I mean https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D etc

**Comment by igorkorsukov** [comment]
done

**Comment by Jojo-Schmitz** [comment]
thanks!
