### ISSUE TITLE
toujours erreurs apres passages Musescore3 vers Musescore4

### ISSUE THREAD

**Issue by fredule2** [musescore/MuseScore#22404]
### Issue type

General playback bug

### Bug description

J'utilise mainenant Musescore 4 Mes partitions sur Musescore 3 etaient stockées dans Partitions
Dans Musescore4 dans le dossier score Lorsque j 'ouvre et corrige une partition sur Musescore 4 ,celle-ci edst sauvegardée sur Musescore3/Partitions Pourquoi?
gros problemes de lecture ,des notes ne sont pas jouées  points d'entrée et sorties de boucles ne sont pas respectées à la lecture 

### Steps to reproduce

exemple de partition partie 1 les boucles sont respectées mais impossible de boucler partirB C ou D
[ABS_Sher10.mscz.zip](https://github.com/musescore/MuseScore/files/14976823/ABS_Sher10.mscz.zip)

### MuseScore Version

Musescore4

### Regression

Choose option...

### Operating system

Mac Os Monterey 12.7.3

**Comment by cbjeukendrup** [comment]
First of all, three house rules:
1. Please try to write issues in English. If you're really unconfident about your English, feel free to include a French version as well, but having an English version makes it easier to quickly see what the issue is about.
2. Please don't constantly (e.g. [#22318](https://github.com/musescore/MuseScore/issues/22318)) express the sentiment that everything was good in MS3 and bad in MS4. That doesn't help anyone.
3. Please discuss only one problem per issue on GitHub. This issue contains two problems:
   - Something about where scores are saved
   - Something about loop playback

Having one problem per issue has the crucial advantage that we can close an issue whenever we fix a problem; that means that if an issue is open, the problem is fixed, and when it's closed, the problem is not yet fixed. Half-fixed issues are annoying to handle.

Now, about your actual points:

> J'utilise mainenant Musescore 4 Mes partitions sur Musescore 3 etaient stockées dans Partitions
> Dans Musescore4 dans le dossier score Lorsque j 'ouvre et corrige une partition sur Musescore 4 ,celle-ci edst sauvegardée sur Musescore3/Partitions Pourquoi?

When you import or open a file in MuseScore, and use the "Save as…" functionality, MuseScore's default choice is the folder where the file comes from. To my knowledge, this is in line with the behaviour in other apps like Microsoft Word. 



> gros problemes de lecture ,des notes ne sont pas jouées points d'entrée et sorties de boucles ne sont pas respectées à la lecture

The issue about loops is covered by #16875.

About the issue with notes not being played: you'll need to give us more specific steps to reproduce that, because for me it works just fine. But probably this is already covered by https://github.com/musescore/MuseScore/issues/19999.
