### ISSUE TITLE
Sound flag warning dialog should appear when changing playback profile from Muse Sounds to MS Basic

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22539]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1. Activate Muse Sounds
2. Add some sound flags
3. Go to View>Playback setup
4. Switch from Muse Sounds to MS Basic. The **Sound flag warning dialog** should appear after clicking **Activate this profile** button

![Capture](https://github.com/musescore/MuseScore/assets/90187801/051dadf0-29cc-47bd-beea-9cbbbaf1f049)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/c1accafc-4729-4b3e-82a2-ae7527800ca9

### MuseScore Version

4.3

### Regression

No.

### Operating system

all

**Comment by avvvvve** [comment]
@Eism Can we trigger a version of the warning dialog with slightly tweaked copy to refer to "sounds" instead of a single "sound"?

Copy would read as follows:

> Are you sure you want to change sounds?
> Sound flags may be reset, but staff text will remain. This action can’t be undone.
> [Change sounds]

![image](https://github.com/musescore/MuseScore/assets/20806406/1b8b6295-50dc-480c-9da0-f8047ccc7b8e)

I also just noticed that the order of the buttons is different in @DmitryArefiev's screenshot ('Change sound' is on the left instead of the right). Is that standard practice for dialogs on Windows?

cc @bkunda

**Comment by DmitryArefiev** [comment]
Fixed in #22618
