### ISSUE TITLE
Wrong SVG page size

### ISSUE THREAD

**Issue by eiffel31** [musescore/MuseScore#22531]
### Issue type

Import/export issue

### Bug description

Generated SVG does not correctly reflect page size.

### Steps to reproduce

New partition
Select page size A5
Export to SVG

Start of SVG generated file:
...
<svg width="2098.8px" height="2977.2px" viewBox="0 0 2098.8 2977.2"

Open the file with inkscape, observe page size in mm: 555x787

This fails because MuseScore assumes 360 DPI and inkscape assumes 96 DPI.

The fix is quite simple: just output the size as it is defined by the page size. So, the line should be:
<svg width="148mm" height="210mm" viewBox="0 0 2098.8 2977.2"

Note: the size in pixels has high similitude with A4 paper size (210x297), but this is just coincidence!

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

Debian 12.5

**Comment by oktophonie** [comment]
See also https://github.com/musescore/MuseScore/issues/20084

**Comment by irwir** [comment]
Remarks on `px` value.
In CSS it is required to be 1/96 `in` for printed media, and the same value was typically used for html presentation on screen instead of actual pixel size.
Inkscape can change value of `px` for import/export in `Preferences - Input/Output - Imported images`.
Switching to unambiguous `mm` would be definitely beneficial.
