### ISSUE TITLE
The Choose Instruments window uses the plural instead of the singular of the instrument name for the string sections

### ISSUE THREAD

**Issue by minimalmusic** [musescore/MuseScore#22548]
### Issue type

Other type of issue

### Bug description

The Choose Instruments window uses the plural instead of the singular of the instrument name for the string sections. I request to use the singular of the instrument name for the string sections, since the use of the singular of the instrument name for the string sections is more common in orchestral scores.

I request to change `<Instrument id="violins">` to `<Instrument id="violin-section">` and `<trackName>Violins (section)</trackName>` to `<trackName>Violin (section)</trackName>` and `<longName>Violins</longName>` to `<longName>Violin</longName>` and `<shortName>Vlns.</shortName>` to `<shortName>Vln.</shortName>` in the instruments.xml file.

I request to change `<Instrument id="violas">` to `<Instrument id="viola-section">` and `<trackName>Violas (section)</trackName>` to `<trackName>Viola (section)</trackName>` and `<longName>Violas</longName>` to `<longName>Viola</longName>` and `<shortName>Vlas.</shortName>` to `<shortName>Vla.</shortName>` in the instruments.xml file.

I request to change `<Instrument id="violoncellos">` to `<Instrument id="violoncello-section">` and `<trackName>Violoncellos (section)</trackName>` to `<trackName>Violoncello (section)</trackName>` and `<longName>Violoncellos</longName>` to `<longName>Violoncello</longName>` and `<shortName>Vcs.</shortName>` to `<shortName>Vc.</shortName>` in the instruments.xml file.

I request to change `<Instrument id="contrabasses">` to `<Instrument id="contrabass-section">` and `<trackName>Contrabasses (section)</trackName>` to `<trackName>Contrabass (section)</trackName>` and `<longName>Contrabasses</longName>` to `<longName>Contrabass</longName>` and `<shortName>Cbs.</shortName>` to `<shortName>Cb.</shortName>` in the instruments.xml file.

### Steps to reproduce

1. Create new score
2. Add Violins (section)
3. Add Violas (section)
4. Add Violoncellos (section)
5. Add Contrabasses (section)

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/159690586/1afcf9ec-5aab-43e4-b74a-c20b705fe3a6)

### MuseScore Version

 4.2.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
I'm not even sure this change is desirable. Pluralised names are _very_ common for sections (also in languages other than English), though not universal, and the more distinct they are from their solo versions the easier it is to not confuse the two. You can obviously change the labels in the score to anything you like, and if you find yourself having to do it a lot and find it tedious you can make yourself some templates or create a customised instrument definition file locally.

There is likely a better general solution which would allow specifying whether pluralised names should be used or not in the automatically generated labels, which could be relevant for all instruments, not just string sections (some styles prefer "Oboes 1.2" rather than "Oboe 1.2", for example).

**Comment by minimalmusic** [comment]
I request to use the singular of the instrument name for the string sections, since the use of the singular of the instrument name is common in orchestral scores.

Joseph Haydn: Symphony No. 104
https://issuu.com/breitkopf/docs/pb_4380_issuu

Ludwig van Beethoven: Symphony No. 1
https://issuu.com/breitkopf/docs/pb_5231_issuu

Franz Schubert: Symphony No. 4
https://issuu.com/breitkopf/docs/pb_4464_issuu

Robert Schumann: Symphony No. 1
https://issuu.com/breitkopf/docs/pb_5261_issuu

Johannes Brahms: Symphony No. 4
https://issuu.com/breitkopf/docs/pb_16103_issuu

Gustav Mahler: Symphony No. 1
https://issuu.com/breitkopf/docs/pb_5631_issuu

Claude Debussy: La Mer
https://issuu.com/breitkopf/docs/pb_5516-07_issuu

Richard Strauss: An Alpine Symphony
https://issuu.com/breitkopf/docs/pb_5710_issuu

Jean Sibelius: Symphony No. 4
https://issuu.com/breitkopf/docs/pb_5694_issuu

Maurice Ravel: Bolero
https://issuu.com/breitkopf/docs/pb_5299_issuu

George Gershwin: Concerto in F
https://issuu.com/breitkopf/docs/pb_15140_issuu

**Comment by DaddyLudwig** [comment]
I prefer seeing the plural form of the instrument when there's more than one of the instrument in the staff. Do I see the singular with string sections a lot in Haydn, Mozart, etc.? Yes, but the fact that I'll see Violino I in both a string quartet and an orchestral score by the same composer is, in my opinion confusing. Likewise, I prefer seeing Flutes over Flute in a symphony score unless the symphony really does call for a single flute(Haydn Symphony no. 6 being an example of that) and Horns 1, 2 over Horn 1, 2.

**Comment by bkunda** [comment]
As @oktophonie pointed out, the use of the plural is very common, so I'm not really sure what the issue being raised here really is, beyond being a request for a different representation of the labels. 
Since this doesn't really solve any problem, I'll close this one for now.

**Comment by shoogle** [comment]
@minimalmusic, you can edit the names to be whatever you like and save the file in your `Documents/MuseScore4/Templates` folder for easy access in the **New Score** dialog _Create from template_ view.

However, **don't** change the instrument IDs (e.g. from `<Instrument id="violins">` to `<Instrument id="violin-section">`) because the IDs are what MuseScore uses to recognise these instruments and load the correct settings for them.

If the ID is wrong the instrument will say `Unknown` in the Staff/Part properties dialog and it won't have a track in the Mixer, so there won't be any playback for it.

`<Instrument id="violins">` | `<Instrument id="violin-section">`
:---:|:---:
![image](https://github.com/musescore/MuseScore/assets/11011881/057ed353-304b-4349-9316-2dd94153f975) | ![image](https://github.com/musescore/MuseScore/assets/11011881/b1bd7f74-c6f5-4f35-8c34-9e6595a359f8)
![image](https://github.com/musescore/MuseScore/assets/11011881/afecb65a-1e7c-440d-bc34-bda5268a5dc8) | ![image](https://github.com/musescore/MuseScore/assets/11011881/826a0b5c-00e2-4284-8be7-e69007313da3)

The IDs aren't displayed in the score or in the program anyway, so you never need to look at them unless you manually edit the MSCX.

**Comment by minimalmusic** [comment]
I disagree. The use of the plural of the instrument name is not very common in orchestral scores. The opposite is the case. The use of the singular of the instrument name is very common in orchestral scores. I prove the statement with links to various orchestral scores of various composers. I wonder about the discussion. I disagree to close the issue.
