### ISSUE TITLE
Very difficult to use drumsets/percussion staves

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#22645]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Facing multiple challenges trying to set up drumsets/percussion staves. See repro steps.

### Steps to reproduce

1. Create a new score based on the "Concert Band" template
2. Edit the drumset for Percussion 1, in order to create a mapping for "Tam-Tam".
3. There appears to be no way to know how which "note #" to use for tam-tam, so add a "change instrument" instruction and choose "tam-tam" as the instrument
4. Now edit the drumset at some point after the change-instrument instruction and note that there's a single mapping "No. 52 e3  = Tam-tam".
5. Delete the change-instrument instruction and try to modify the original drumset to include a mapping for "No. 52/e3".  Add a note using this mapping and play it back - it sounds nothing like a tam-tam (maybe a tom-tom?)
6. Open the staff properties for the "Glockenspiel" staff with the intention of changing it to a generic "Percussion" instrument
7. Click "Replace instrument"
8. Initially, "Percussion" is nowhere to be found.  But after selecting "Family = Concert Band" and "Percussion - Unpitched", you can select "Percussion".
9. Now view/edit the drumset for this staff, and notice that a) it's very different to the default Concert Band percussion drumsets in the other other percusssion staves, and b) there appears to be no way to add "Crash cymbal" (or "Concert cymbal") to the drumset.  If you try to use the Concert cymbal mapping from the other percussion staves (which is note 59/b3), it doesn't work as expected (again, sounds nothing like a cymbal).

Further if you had first applied a key signature to the score before trying to change "Glockenspiel" to "Percussion" the key signature persists and is almost impossible to remove (ultimately I had to insert another measure before the 1st, and then remove it).
And if you then wish to introduce an instrument change to a pitched percussion instrument (e.g. Xylophone), the key signature does not get shown automatically - you *can* force it by using CTRL+key signature palette to add a key signature, but then it unnecessarily messes up the spacing in other parts (despite the fact the you've added the key signature to an empty measure in the one staff it affects).  I would have thought logically simply having a percussion clef should always automatically cause a key signature to be hidden, and then a change to treble or bass clef would be accompanied be the right key signature as necessary, e.g.:

![image](https://github.com/musescore/MuseScore/assets/5364225/89b1bfa4-87c1-430a-a834-39cd408230ac)

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Windows 11

### Additional context

I'm aware that the GM percussion map is limited and doesn't include all unpitched percussion instruments, particularly tam-tam.  But why should we use GM notes at all if it's so obviously limited?  I would expect a drumset should allow mapping any particular named instrumental/audio sample to any particular staff line/notehead, regardless of whether it might be represented in the GM percussion map or not.

**Comment by MarcSabatella** [comment]
There are changes being designed percussion, but I don't know any details, so I'll leave it to others to consider how much of this might still be relevant to the new designs.  However, there are also some points of confusion here with respect to the current design that I can address.  Also, it is much better to file separate issues for separate problems so they can be tracked individually.  I suspect this issue isn't really actionable as is.  But I will try to summarize the separate issues being raised here and comment on them briefly:

1. The key signature issue is real and I *think* is also being tracked as https://github.com/musescore/MuseScore/issues/14714 which is still open with some activity, although that issue also references https://github.com/musescore/MuseScore/issues/14702 which is marked as resolved, so I'm not really sure of the current status
2. "Percussion" should definitely be listed among "Common" instruments; that seems a trivial fix.
3. It is true the "Percussion 1" and "Percussion 2" instruments in the Concert Band template have different drumset definitions than the Percussion instrument available to add from the main instruments dialog.  So that too is a real and separate issue that would have a trivial fix.  Note that while many pitches are the same between these, it looks like some pitches were defined in one but not the other, and some namings are different.  But anyhow, when the new system for percussion definitions is created, we should be sure to update both the default Percussion instrument and the templates that use it.
4. I think you (@wizofaus ) may have overlooked the fact that MIDI pitch 59 *is* defined and works as expected in the default Percussion instrument - it is simply mislabeled as "Ride Cymbal 2".  But it behaves in all other respects just like it does in the concert band template
5. Tam-tam is indeed missing from GM, but hopefully the new system will allow percussion instruments to assign Muse Sounds to individual notes instead of being limited to pitches within a GM soundfont.

**Comment by wizofaus** [comment]
BTW I just noticed this was assigned to 4.4, but I'd think in the form I've logged this, I haven't really made it clear what the "expected behaviour" should be, plus it does sort of collate multiple issues into one.  Probably doesn't make sense to consider this "ready to implement" in its current form anyway.  I'm not sure how much design work has actually been completed?

**Comment by wizofaus** [comment]
(BTW somebody asked on the forums just recently how to get a "suspended cymbal" sound in a concert band score. It seems reasonable to me that you should be able to use the Muse Sounds "Suspended cymbal" sample in a drumset, but I couldn't work out how. The default Concert Band drumset only has "Concert Cymbals" which I assume is crashed/clashed cymbals)

**Comment by MarcSabatella** [comment]
Currently, Muse Sounds cannot be combined on a single staff, so no way to get a “Muse Drumset”.  See for example https://github.com/musescore/MuseScore/issues/14016

**Comment by wizofaus** [comment]
I actually think if that was implemented, we could clarify that issue was just about (or create a separate issue for) the clef problem.

**Comment by zacjansheski** [comment]
The main action item I took from this is to correct the "Ride Cymbal 2" in the Percussion instruments "drumset"
Done in https://github.com/musescore/MuseScore/pull/23326
I am going to close this as we seem to have other issues open relevant to the other topics.  Thank you!

**Comment by wizofaus** [comment]
Which issue captures the problem with clefs and key signatures (when changing between percussion and pitched clefs?)
