### ISSUE TITLE
Synthesizers in a midi are shown as different instruments.

### ISSUE THREAD

**Issue by Philorganic** [musescore/MuseScore#22744]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Many of my song files contain synthesizers. In MuseScore Studio these are now shown as other instruments.
I have had to uninstall MuseScore Studio and reinstall MuseScore 4.2.1 to get the instruments to show and play correctly.

### Steps to reproduce

1. Open MuseSore Studio
2. Open a file with synthesizer instruments
3. All instruments have been changed.
4.

### MuseScore Version

MuseScore 4.3 Studio

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
If I am understand this and other reports elsewhere correct, this isn't an engraving issue, but a playback issue.  Certain of the "synthesizer" instruments like "saw synthesizer", "sine synthesizer" and others now playback as piano by default.  Same for scores created in 4.2.1 as for new scores created in 4.3.  It seems the automatic mapping for MS Basic has broken for these.  Other synthesizers such as "goblins synthesizer" and "pad synthesizer" seem fine.

Workaround is to use the Mixer to choose the appropriate sound from within MS Basic directly instead of relying on the "choose automatically" option.

**Comment by Philorganic** [comment]
Hi Marc, yes ,that is the problem. As to the workaround, with about 200 pieces of music, that is going to take a ridiculous amount of time.
I have uninstalled MuseScore Studio and reverted to the previous version where everything works.
