### ISSUE TITLE
Show "displayed" measure number in addition to "internal" measure number in status bar

### ISSUE THREAD

**Issue by alex44444444** [musescore/MuseScore#22755]
### Issue type

Other type of issue

### Bug description

status bar shows wrong measure number (unchanged) if in some measure before some number added to measure number in it's properties

### Steps to reproduce

1.select some measure
2. click right mouse button and open measure properties 
3. add some number more than 0 to measure number and click OK
4. select some measure after, better with number above 
5. see wrong (unchanged) measure number on the status bar at the bottom. 

### MuseScore Version

4.3

### Regression

No.

### Operating system

Windows

**Comment by MarcSabatella** [comment]
This is currently by design.  the status bar shows the "internal" measure number to avoid ambiguity in cases where the measure numbers are manipulated.  It's a reasonable feature request to change this to show the displayed measure number in addition (or possibly instead, but I'd recommend against that).  I don't see an open issue on GutHub for this although it's come up many times on the forums etc.  So probably this should just be re-titled and re-categorized.

**Comment by cnicolasgr** [comment]
Hi! Can I work on this?

**Comment by cbjeukendrup** [comment]
@cnicolasgr Yes, welcome!
