### ISSUE TITLE
Prebends in music staff do not translate correctly in tablature

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#22902]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

IMV, ideally, prebends should translate from music staff to tablature in a way shown by the following example (see measure 2):

![prebend1](https://github.com/musescore/MuseScore/assets/87246583/4099930a-b44b-41dd-aca6-ae7bd526493c)

However, in practice, what happens is this:

![prebend2](https://github.com/musescore/MuseScore/assets/87246583/50979dc1-71ac-48ec-ab5f-9d37c2cfe1a6)

The prebend, indicated by a small notehead in parentheses does not appear in the tablature (though it plays back OK).

### Steps to reproduce

Just input the example shown above to confirm the exact behaviour.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment]
I'm not quite sure what the issue is here. 

When I enter the pre-bend in the standard staff (i.e. not the tab stave), I can produce the example you give in the first image above (which is correct). 

The only way I can achieve the example you give in your second image is to add a grace note before the first beat of the second bar, then parenthesise it, then add a regular bend. MuseScore won't recognise this as a pre-bend, which is a specific class of bend. Instead, all you have to do is add a pre-bend to the first beat of the second bar (then the parentheses and bend lines are drawn automatically). 

Can you please clarify the steps you took to achieve the (incorrect) example in the second image above?

**Comment by rgreen5** [comment]
Sorry about that. I can't reproduce the initrial problem either,

**Comment by rgreen5** [comment]
Issue resolved.
