### ISSUE TITLE
Rit ending inside measure - Clear measure+Undo+Redo and repeat causes crash

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#22932]
### Issue type

Crash or freeze

### Bug description

This crash is in master, not 4.3.1

### Steps to reproduce

1. Make a score with a rit (or other tempo line) ending on beat three of a measure
2. Select measure with end of rit
3. Clear, undo, redo
4. Click away and then repeat step 2 & 3
5. Crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/afa767e8-ef5e-4bc1-a6a8-36761968232f

### MuseScore Version

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241420305, revision: github-musescore-musescore-449a64e

### Regression

Yes, between 4.3.1 and 4.4 (master)

### Operating system

All

### Additional context

[Crash.zip](https://github.com/musescore/MuseScore/files/15395086/Crash.zip)

**Comment by wizofaus** [comment]
Has anybody started working on this? If not, I can have a look.

**Comment by wizofaus** [comment]
Did manage to reproduce though not using those exact steps, but you can see a problem even earlier, and in fact that's a clue as to why it's crashing later. Basically just after clearing the measure with the half rest, then undoing and redoing, you can see that redo hasn't restored back to the correct state - the dynamic tempo change (text line) still extends half way through the measure, i.e. the extra segments haven't been removed correctly on redo. Will keep looking tomorrow.

**Comment by wizofaus** [comment]
There's a general problem here, that when you have spanners that end part way through a measure, if you clear a measure, the extra segments get removed but the spanners are not updated. Then during *layout* it actually recreates those segments, but doesn't put them on the undo stack. Then when you redo the list of segments isn't really right, which ultimately causes a crash as there's an attempt to remove a segment that's no longer part of the list of segments for a measure. It's easy enough to prevent the crash (just ignore the attempt to remove that segment), but the behaviour is still problematic because you can see elements resize themselves incorrectly as you continue to make other changes.
So the question is what the correct behaviour should be - to me there's two choices:
a) if clearing a measure would remove segments that existing spanners need, then those spanners need to be adjusted to end (or start) only where there are now segments, as part of the undo-able action.
or
b) if clearing a measure would normally cause segments to be removed, but there are existing spanners that need them, then those segments should be left there.

I'd personally prefer b) - unless there's a problem with leaving a segment there that's unoccupied by an actual note or rest, which I'm pretty sure there shouldn't be.

The decision will make a difference to the user experience (and b) is surely the better user experience - that the spanners keep their existing position/length even though the notes/rests are removed), but I can think either can be justified.  Would like advice before proceeding.

**Comment by oktophonie** [comment]
b) is the desired behaviour. See https://github.com/musescore/MuseScore/issues/22751

**Comment by wizofaus** [comment]
Btw the same crash happens even with dynamic markings etc. that explicitly belong to the same staff.

**Comment by wizofaus** [comment]
The behaviour still isn't really ideal when you delete notes at time ticks where gradual tempo change elements *start* - they get moved to the next measure. Or if, for instance, you have two 1/2 notes tied, with a hairpin starting at the 2nd 1/2 note, then convert it to a whole note (the hairpin is deleted). But the crash is definitely gone, so that's the important thing.

**Comment by oktophonie** [comment]
Those issues are known and are being addressed elsewhere.
