### ISSUE TITLE
Muse Brass Mixer menu is broken

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#22947]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

After installing the latest Muse Brass, the Mixer menu is broken in two - with some instruments under "Muse Brass" directly and others under "Muse | Muse Brass".

Oh and "Muse Choir" is also under "Muse" for some reason.

### Steps to reproduce

1. Install Muse Brass
2. Create a new score, and in the mixer, try to change the Sound for one of the channels
3. Note the layout of the menu - the instruments are not all in one place

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/5364225/124bc05f-bdc9-42a5-83d7-a3f1b8767ccb)

### MuseScore Version

4.3

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by wizofaus** [comment]
(I gather this *has* already been fixed, but hasn't been moved to the 'release channel' yet?  I couldn't find an existing issue for it though)

**Comment by wizofaus** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/22530, however this is closed, despite it still being a problem in the latest version for me.

**Comment by MarcSabatella** [comment]
It is closed because it *is* fixed internally and available in the beta.  The problem here is that for whatever reason, this version of Muse Brass wasn’t released “for real” along with 4.3.  Same issue for Muse Choir.  Also issues with some sound flags that should be present not showing up.  See #22957 , which is the real issue here.
