### ISSUE TITLE
Glissando playback issue Muse Strings

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#22968]
### Issue type

Muse Sounds bug

### Bug description

"Chromatic" glissando sound very odd (mostly barely audible, with occasional random notes)
Changing them to "portamento" glissandi can cause notes to be come inaudible

### Steps to reproduce

1. Create a new score that has Violins 1 (Muse Sounds)
2. Enter as 1/2 notes, C5, G4, E4, C4.
3. Link these with glissando lines (but leave the playback options to default to "chromatic", despite this not making much sense for violins)
4. Now enter B4, C6 (up a ninth), B4, C6
5. Link these with glissando lines but change playback to Portamento
6. Play back the entire piece
7. Note the quite random nature of the chromatic playback, and that for the portamento glissando the last B is inaudible

### Screenshots/Screen recordings

[Audio sample](https://audio.com/dylan-nicholson/audio/22968)

(NB I boosted the mixer levels for this to be readily audible, it's much quieter by default)

![image](https://github.com/musescore/MuseScore/assets/5364225/ae3a7ab1-f7cb-47ea-907d-4c145f679572)

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Windows 11

### Additional context

A piece I'm working on uses a number of glissandi in strings where this playback issue means I have to turn off the "play" flag for them.

Actually I don't care particularly about the "chromatic" playback, it doesn't even make sense that that's supported for strings, but it *is* the default, and caused considerable confusion when I first heard the playback.

**Comment by bkunda** [comment]
If the linked audio sample is supposed to represent the attached score, then there's definitely some problematic behaviour there. 
@sampleeditor @matthewreadbass can you please see if this is an issue on the sample end? Otherwise it might need attention from @RomanPudashkin.

**Comment by bkunda** [comment]
For clarity, here is a screen recording of the example illustrated above: 

https://github.com/musescore/MuseScore/assets/86290556/ba9ff54d-a789-4f67-9006-ffdeb6597bfc

More-or-less correct playback is achieved if the playback setting "portamento" is used instead of "chromatic". This doesn't satisfy every interpretive situation though, and ideally we'd expose a more granular control for portamenti that allows users to change its speed and duration. 

There do remain other bugs when "portamento" is selected though. In this example, a legato interval creates a portamento effect where there is none notated, and a note gets dropped off entirely. So more investigation is required to isolate these separate issues. 

Therefore I'll close this one for now, because these other bugs should be raised as separate issues.

**Comment by adavismusic89** [comment]
@bkunda To clarify, have these bug issues been raised?

**Comment by wizofaus** [comment]
Wait, why would this be "not planned"? Is it covered in another issue? @bkunda

**Comment by wizofaus** [comment]
I've retested with 4.4 (but still Muse Sampler 0.6.3) and these issues are still very much present:
a) the *default* playback for a glissando line is very odd (but as I've noted, "chromatic" doesn't make much sense for string instruments and possibly shouldn't even be available)
b) the portamento playback isn't right either, there's no glissando and the second "B" isn't played at all

So can this please be re-opened.  I'm happy to help fix it.
