### ISSUE TITLE
Tubular Bells staff labels incorrect

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#22990]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The staff labels for the "Tubular Bells" instrument are incorrect. The long label says "Tubular bells" when it should say "Tubular Bells", and the short label says "T.b.." when it should be either "T.B." or T.b."

### Steps to reproduce

1. make a score with the tubular bells instrument
2. see the incorrect labels

### Screenshots/Screen recordings

![Screenshot 2024-05-27 002453](https://github.com/musescore/MuseScore/assets/21023353/0c35b49b-abbd-4daa-8da2-e23ae87f207d)
![Screenshot 2024-05-27 002503](https://github.com/musescore/MuseScore/assets/21023353/880856cc-e9bd-4ec2-adb5-20ff12f128f0)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

I don't know

### Operating system

Reported on Windows 11

**Comment by Jojo-Schmitz** [comment]
"Tubular Bells" and T.B." are the British English translations for "Chimes" and "Cme.", respectively, but these translations are correct on Transifex, so I wonder where those strings stem from?

**Comment by shoogle** [comment]
It was in the English (US) translation, not English (GB), so it should be "Chimes" rather than "Tubular Bells".

@Jojo-Schmitz, it looks like you might have edited it accidentally?

![image](https://github.com/musescore/MuseScore/assets/11011881/56e2193c-2908-411b-97c1-42ecd1c1ca62)

Anyway, I've corrected it now. Within MuseScore Studio, if you go to __Preferences > General > Check for language updates__ then you should get the new version.

**Comment by Jojo-Schmitz** [comment]
Oops. I don't recall, but the evidence is there, sorry about that.
