### ISSUE TITLE
Lyric entry - focus moves to note even if tied to previous.

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23058]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

My expectation is that when entering lyrics you only need to hit hyphen/space after each word/syllable. But in fact that's not true - if the note you're entering a syllable for happens to be expressed as a tied note, after hitting space or hyphen, focus jumps to the next notehead which is part way through the tied note. 

### Steps to reproduce

1. Create a new score
2. Enter an 1/8 note then a dotted 1/4 note.  Then enter two 1/8 notes with the second tied to a subsequent 1/4 note. Then one final note.
3. Start lyric entry mode at the beginning 
4. Type "hel - lo hel - lo world"
5. Note that the "world" actually lands on the 4th 1/4 note of the 1st measure, despite there being no noted articulated at this point - indeed the rhythm is precisely the same as the first two notes.
6. Expected: the "world" should land on the final note (in the 2nd measure), with an extender line automatically added to "lo".

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/5364225/1da0fb51-9204-4b07-8df2-0d927f3dd788)

### MuseScore Version

4.3.1

### Regression

I don't know

### Operating system

Windows 11

### Additional context

I'm assuming it automatically puts the extender line in too.

**Comment by MarcSabatella** [comment]
This isn’t a bug per se but the way it was designed to work and has always worked.  It’s reasonable to ask if the design should be revisited, however.  It would indeed be rare to need to put a syllable in a note that is tied-into.  Not sure it should be impossible, but as with lyrics on rests, as it is *possible* it can still make sense for it not to happen *by default* during lyric entry.

**Comment by nmu-nyasan** [comment]
Please don't make it the default. Or at least make it configurable.
Japanese scores use the prolonged sound mark “ー” instead of the melisma line, and it is not uncommon for lyrics to be written on tied-into notes.
![image](https://github.com/musescore/MuseScore/assets/139459177/56dfe91c-6dd1-4681-9b8b-c5b66f5866fb)
![image](https://github.com/musescore/MuseScore/assets/139459177/8653bd52-e0d2-4d39-a993-291edf09ccba)

**Comment by wizofaus** [comment]
Fair point, I can't considered that other languages might use a different convention.  If it were smart, it'd recognise what language you were using for the lyrics!

**Comment by DaddyLudwig** [comment]
I'd definitely prefer configurable over defaulting to always moving to next untied note. I work primarily with German and Italian lyrics with a little dabble of Latin(mostly in masses) and English(mostly in folk songs) here and there and I haven't seen a syllable on a tied into note in any of those languages(not yet anyway, maybe it does happen in those languages sometimes), but I know I'll run into lyrics in Czech(Dvorak) and Russian(Tchaikovsky) and French(Bizet and a lot of other composers), and maybe others too like Hungarian perhaps? 

I don't know if those languages besides the 4 I'm working with right now do have changes of lyrics on tied into notes or not, haven't really delved deep into vocal music in those languages. In any case, even if those languages all most commonly have extender lines for tied notes and next word or syllable on the next untied note, it would be nice to be able to configure it so that I could put lyrics on a tied into note if I had to.

**Comment by wizofaus** [comment]
I'd certainly never suggest you *couldn't* do it, just that to do so, I'd expect you'd need to explicitly navigate to it.

**Comment by wizofaus** [comment]
Is it not possible to convert into a feature request? More than happy to contribute an implementation even if it's only controllable via a hidden (devtools) flag initially. The existing behaviour does seem pretty unexpected at least to me, and I suspect many (most?) other similar applications do in fact skip tied notes by default when entering lyrics.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jojo-Schmitz** [comment]
@oktophonie an explanation why this got closed would be good

**Comment by Jojo-Schmitz** [comment]
Esp. whether if got closed as not being a bug, or as a dismissed feature request?
