### ISSUE TITLE
Too hard to select barlines enclosed by (winged) brackets

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23145]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

There appears to be no way currently to use the mouse to select a barline if it's at the start of system where there's any winged bracket (e.g. the bracket type that's simply called "bracket" in the palette) present.

### Steps to reproduce

1. Create a new score with a system grouping bracket with wings (e.g. any ensemble template will have this).
2. Try to use the mouse to select the barline at the beginning of any system. Only the bracket will be selected

Workaround: select a clef then use ALT+left arrow.

Expected behaviour: even though the bracket's bounding rectangle may encompass the barline, I'm not clicking ON the bracket, only the barline, so the selection logic should be able to cater for that. Even if it's by assuming that brackets are at a lower Z-order by default.  However similar problems exist with, e.g. diagonal lines, where the bounding box represents too great an area to make sense from a mouse-selection point of view.

I also gather there will be a return of the feature in MS 3 to cycle through overlapping elements with the mouse, but in this case I don't believe it should be necessary.

### MuseScore Version

4.3.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by wizofaus** [comment]
Nice, works perfectly! Wonder why the logic used to be that complex, couldn't find any case it seemed to be needed.

**Comment by cbjeukendrup** [comment]
In the past, bbox and shape were two separate things (that _should_ be in sync, but were not always, but that was not the problem here). Therefore, both had to be calculated.

**Comment by wizofaus** [comment]
So why can't diagonal lines have a selectable shape that just contains the line? Currently selection is painful in measures with gliss. lines etc.

**Comment by cbjeukendrup** [comment]
Because shapes can only consist of axis-aligned rectangles, and not diagonal ones. In the case of beams, this is solved by making not one big rectangle but a lot of small ones (see mainly `BeamSegment::shape()`), but for glissandi this hasn't been done yet. Also, having many small rectangles could affect performance, so this must be done somewhat sparingly. (OTOH, if we do it for beams, we can do it for glissandos too, because I think it's safe to say that there are more beams in the world than glissandos.)

**Comment by cbjeukendrup** [comment]
> Worth creating a separate issue for then?

It turns out that I already did that long ago: https://github.com/musescore/MuseScore/issues/15997

> I'm not sure why shapes can't be just any polygon

Unless I'm missing something, polygons are very hard to work with. Even detecting whether a point lies inside a polygon or not is not completely trivial; and detecting whether polygons overlap, or what's the distance between them, or what should be the distance between their origins to prevent overlap, is even more difficult. So it's much more difficult to work with and even worse for performance.

**Comment by wizofaus** [comment]
I've just used the winding number algorithm in the past. Or whatever built in "point in polygon" functions are supplied by the OS or graphics engin (QPolygon:: contains() ?).
Anyway if a series of rectangles works well enough and is what's already being done for beams that's cool.
