### ISSUE TITLE
Slurs on multiple grace notes do not attach to correct pitch

### ISSUE THREAD

**Issue by LordXaos** [musescore/MuseScore#23199]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

I used a pair of grace notes for an arpeggiated entry into a trichord, and added slurs to the two grace notes, the closer (second) grace note slur is alright, but the slur for the first grace note is shown at the wrong pitch (where there is no grace note). The acoustic preview sounds alright, so it appears to be a rendering bug.

Tried finding if already reported, but might have been spoiled by language barrier, sorry if duplicate.

### Steps to reproduce

1. Enter a trichord (say B E G#) 
2. Add two grace notes before, for B and E, in this order.
3. Select grace notes one after another, and add slurs.
4. Slur for E is shown correctly, slur for B is shown at G# instead.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/172435190/9a39ec10-acab-41d5-be8d-521915933ec9)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241490900, revision: github-musescore-musescore-026c26b

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
This is in fact 'by design'; the tie shown is at the normal expected position to connect two notes on the middle line:
![image](https://github.com/musescore/MuseScore/assets/20604032/53fddbe0-e4ec-44e1-b29c-3ed820eea1c1)

MuseScore draws single-note ties 'outside' the notes (starting from above and below) - and indeed, from 4.2, chord ties too, but since 4.2 it is also configurable; so you could set this tie to be 'inside' via the Properties panel:
![image](https://github.com/musescore/MuseScore/assets/20604032/edb052c4-fc93-4e72-8407-5f2115214135)
![image](https://github.com/musescore/MuseScore/assets/20604032/91316203-611b-4aaa-acd7-10e6a422cd74)

Though in my opinion it would be better to flip it instead:
![image](https://github.com/musescore/MuseScore/assets/20604032/d9f3528b-895b-459d-8a2c-95b60eff43a9)

which would probably be the better default behaviour in this situation, if the logic could be generalised.
