### ISSUE TITLE
Lost Scores

### ISSUE THREAD

**Issue by snappylizard** [musescore/MuseScore#23424]
### Issue type

Cloud issue (opening, saving, logging in/out)

### Bug description

Hi, my old PC with all of my un-uploaded scores in the middle of the night, has died do to its motherboard frying. With my new PC, I have lost all of my musescore files. Is there any way I can get my lost scores back?

### Steps to reproduce

Sorry, but I am not sure how to give step by step instructions on how this can happen.

### MuseScore Version

Musescore 4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
In the first place, this is a support request rather than a bug report or feature request, so should actually have been posted in the forums on MuseScore.org. But for now it's fine, I'll reply here. I'll close the issue though, for this reason; but feel free to keep replying to it.

I think I don't have enough information about your exact situation to give a definitive answer. Did you copy the entire contents of the harddisk of the old computer to the new one? What do you mean with "all of my MuseScore files"? Just files on your old computer, or files that were opened at the moment that the crash happened, or cloud files that contained unsaved changes?

Anyway, here's something you can try:
1. In Windows Explorer, paste the following into the address bar: `%LOCALAPPDATA%\MuseScore\MuseScore4`
2. You might find an autosaved version of the latest never-saved score in the file called `new_project.mscz`
3. In the `cloud_scores` subfolder, you might find cloud scores that were somehow saved but not yet uploaded successfully.

**Comment by shoogle** [comment]
If you still have access to the old PC then you might be able to take out the old hard drive and put it in an external drive caddy/enclosure that plugs into the new PC via USB.

The type of enclosure you need depends on the form factor (physical dimensions) of the drive and the type of connector used to plug it into the motherboard of the old PC. The most common options are:

- SATA connector (form factors: 2.5 inch or 3.5 inch)
- m.2 connector (form factors: 22mm wide by 30mm, 42mm, 60mm, 80mm or 110mm long)

If you're not familiar with these things then it's best to take the PC to a repair shop and ask them what type of enclosure you need, or simply ask them to get the data off the old drive for you.

Once you can access the data from the old drive, you can look for scores in the folders @cbjeukendrup [mentioned](https://github.com/musescore/MuseScore/issues/23424#issuecomment-2203066598).

If you need more help, please ask on the [forum](https://musescore.org/en/forum/6).
