### ISSUE TITLE
prevent accidentals and first note being too close to the left staff edge when clef hidden

### ISSUE THREAD

**Issue by foss-** [musescore/MuseScore#23698]
### Your idea

Currently when clef is hidden, notes with accidentals are too close to the edge of the left staff. See how the left line of the b is unnecessarily hard to view:

![currently](https://github.com/user-attachments/assets/e2a2494f-43c6-4bcc-993a-97a0535d5f1d)

### Problem to be solved

Make sure notes and accidentals are always readable when following auto layout. I know this can be adjusted by offsetting appearance for both note and accidental. But it would be nice, if this would look great in auto layout.

This is what I'd expect and after correcting the offset manually:

![expected](https://github.com/user-attachments/assets/21f7433a-26e5-4dc4-8213-d736d7de38b1)

### Prior art

This is a classic problem Sibelius suffered from in all (?) of it's versions.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by MarcSabatella** [comment]
That’s not how it looks for me.  Check your “barline to accidental” setting in Format / Style / Measures, and make sure it hasn’t been turned down from the default.  Or increase it more.

If you continue to have trouble, please ZIP and attach your score.

**Comment by foss-** [comment]
Thanks for your quick response @MarcSabatella 

Setting. which iirc I have not altered, is as follows:
<img src="https://github.com/user-attachments/assets/55d15d7a-eb1b-42f0-8a11-e21ab4b41b06" width="350">

Attached please find a file to reproduce:
[reproduce file.mscz.zip](https://github.com/user-attachments/files/16323960/reproduce.file.mscz.zip)

**Comment by MarcSabatella** [comment]
As your picture shows, that is *not* the default value - notice how the reset button next to the value is highlighted?  Click that and the value should return to the proper default, 0.65 sp.  You can also increase it further.

I notice this file was imported from a MusicXML file.  Perhaps the file you started from contained something that overrode the normal default.  You might consider running "Format / Reset entire score to default layout" to get things closer to normal after an import, or at least "Format / Stye / Reset all styles to default", since MusicXML files often contain formatting that made sense in whatever program created the file but that won't translate well anywhere else.

**Comment by foss-** [comment]
You are correct with all assumptions. Thanks so much for helping me out and your prompt responses. Case closed.

I'll take note so I'll remember when doing another transfer from Sibelius. To keep my settings and styling I copied the transferred file and created new sheets from there.
