### ISSUE TITLE
Ability to playback "portamento" for Oboe glissando (Muse Sounds)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23703]
### Your idea

When notating a glissando with Muse Sounds Oboe you should be able to choose "portamento", as the default "chromatic" option is unusable (the notes sound staccato and nothing like an oboe attempting from slide from one note to another). 
Currently if you select "portamento" no pitch bend is heard at all.

### Problem to be solved

https://www.youtube.com/watch?v=Ti4W9ycDuWI&t=114s is an example of where this is required

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
This sounds more like a bug than a feature request. If I'm understanding it right, there is no pitch bend heard at all when "portamento" is selected, and when "chromatic" is chosen, the sound is overly staccato-like and unusable.  

If this is correct, then it's a playback issue specific to the Muse Sounds oboe. We'll need to close this issue here and ask that you raise it by contacting Muse Hub customer support. If you can reproduce it also with MS Basic/VST, then please raise this as a bug report so we can collect the required evidence/documentation.

**Comment by wizofaus** [comment]
Ok, have reported as a problem on Muse Hub. Feel free to close this.

**Comment by zacjansheski** [comment]
Closing per comment above
