### ISSUE TITLE
Ability to close a score and return to home screen in development builds, even when "official" release is still running in background

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23727]
### Your idea

If I'm running the 4.4 nightly build I should be able to close the current score and return to the home screen even if there are instances of MuseScore 4.3 running.

### Problem to be solved

I downloaded and installed the 4.4 nightly development build with the intention of trying out a few scores to see what differences I could notice. But after opening the first and clicking the X on the score tab to close just that score, it quit the entire process/closed the top-level app window, which I thought was because it must have crashed.  But on further experimentation it seems that the behaviour of closing the current score tab depends on whether there are instances of MuseScore 4.3 (effectively a different application!) running, which seems very unexpected.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
I agree with this; even so much that I already logged it here: https://github.com/musescore/MuseScore/issues/13408 :)

**Comment by wizofaus** [comment]
Wait, I disagree that's the same issue, though obviously it's related - what you're asking for there is a much bigger change...

**Comment by cbjeukendrup** [comment]
Hm, okay. I think my issue is a superset of this one, but perhaps it does indeed make sense to keep this smaller concrete request open too.
I'm not sure though whether it's a good idea to implement this without making the bigger change, because an alternative fix might become a bit fiddly... if you want, feel free to give it a try, but be aware that we might decide not to merge it so I'm not sure if you should spend your time on that.

(2 minutes later:) 
Actually I took a look at what would be required to make the bigger change, and actually it seems as trivial as modifying `SERVER_NAME` in `ipc.h` to depend on the major version number and stable/unstable. So I'm going to try what happens when I do just that!

**Comment by wizofaus** [comment]
Well I will say personally I want a DevMode flag to set so that when you close the score tab it ALWAYS returns to the home tab no matter what :)
