### ISSUE TITLE
"1" above the one-measure rest in parts

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#23918]
## My idea

I suggest adding the ability for users to mark one-measure rests with the number "1" in instrumental parts.

## Problem to be solved

This will allow the performer to be sure that the rest is not multi-measure and that nothing was missed. 
At the moment, in MuseScore Studio, the number "1" can only be specified manually, while aligning it in the center above the bar. 
![Снимок экрана (472)](https://github.com/user-attachments/assets/c54a91f8-d84d-4c4b-8a2c-d64d277ff17c)

If you try to specify a minimum value of "1" for multi-measure rests in the style settings, this will not be displayed correctly.
![Снимок экрана (474)](https://github.com/user-attachments/assets/3c32d2ba-3d03-431a-ab05-263b3ead89d1)

## Additional context

The number "1" should not be specified if the bar is **_G.P._** or there is a cue in it (but see #23912)

## Checklist

- ✅ This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- ✅ I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by SteveBlower** [comment]
You can get the appearance in your first picture if you enable "Old-style multimeasure rests"  (multibar in GB English)

![Clipboard_08-06-2024_01](https://github.com/user-attachments/assets/0305bb03-e2c1-49e1-bdc5-e1d2cc84d3e3)

**Comment by rpatters1** [comment]
I am using the latest dev build, and this seems to be resolved with following settings:

<img width="657" alt="Screen Shot 2024-09-27 at 7 21 16 AM" src="https://github.com/user-attachments/assets/872f41be-d07d-43cf-8ef2-5980726ff07c">

In answer to @SteveBlower, you absolutely would want to do this. Nice-to-haves would be

- the ability of a single bar "multimeasure" rest to be the same width as an empty bar.
- automatically suppress the printing of a multimeasure rest range under a single-bar multimeasure rest, and instead display the measure number normally (if it would be displayed otherwise).

FWIW: I accomplished all of this for Finale with a plugin, but it did require running the plugin to set up the mm rests.

**Comment by rpatters1** [comment]
P.S. I would be happy to work on the last two bullet points, if they are desirable. Otherwise I wonder if there is any reason to keep this issue open.

**Comment by SteveBlower** [comment]
I would say there is no need.  The desired behaviour described in the original post can be achieved already with the right combination of style settings.

**Comment by rpatters1** [comment]
If you are referring to my bullet points, I very much have need of them myself. Or else I wouldn't have mentioned them. :) But before working on them, I'd like some indication of whether the changes might be accepted.

**Comment by SteveBlower** [comment]
Sorry, I was referring to the original post, not your bullet points.  Perhaps a new issue for them?

**Comment by Dima-S-Jr** [comment]
@SteveBlower, @rpatters1, it makes sense to keep this issue open, because the style settings you mentioned above, which allow you to achieve the look I outlined in my issue, are nothing more than a workaround. The number "1" should be used not only in the old style. Therefore, first of all, I focus on ensuring that this behavior is by default, and the user does not have to resort to the workarounds mentioned above.

**Comment by rpatters1** [comment]
I don't see it as a workaround. Is it that you don't want to have to check "Old Style"? It literally is the old style. Contemporary style is not to show a 1 at all but just an empty measure.

**Comment by Dima-S-Jr** [comment]
> This will allow the performer to be sure that the rest is not multi-measure and that nothing was missed.

The number "1" is used in the contemporary style, as well as in the old one. The reasons why the number "1" should be used (regardless of whether the style is old or contemporary) I also outlined in the issue. I suggest continuing the discussion on the forum or in the Discord, because this is not the most suitable place for this.

**Comment by FrancRos31** [comment]
> I am using the latest dev build, and this seems to be resolved with following settings:

It works also in version 4.4.2 (OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97).
![1](https://github.com/user-attachments/assets/0eb5c45a-0957-430a-9c0d-a0cae544cb22)

**Comment by SteveBlower** [comment]
The style settings to get that look are already available.  Is it just the wording in the dialogue that you are concerned about?  *"The number "1" is used in the contemporary style, as well as in the old one"*

Perhaps the label on that tick box could be changed,  How about "Traditional grouping"?  Or, how about reversing the logic and having a tick for "Use centred beam style"  and having a minimum number of rests before that kicks in rather than a maximum before "traditional" rests kicks out?

**Comment by rpatters1** [comment]
Personally, I think the dialog is very clear how to use as-is. I'm cool with it if someone decides to implement a feature that prevents a "1" over a mmrest shape, substituting a whole rest instead. But I don't see a need to change the dialog. Any change will make it less clear, in my opinion.

(I admit my opinion may be colored by coming from Finale, where the options are quite similar.)

**Comment by Jojo-Schmitz** [comment]
Having that option is fine, having it set as the default as #25199 does, is not, IHMO
See discussion in https://musescore.org/en/node/393912
