### ISSUE TITLE
Changing repeat markers size is broken in 4.4.0

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#24330]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Add repeat marker  (Segno or Coda)
2. Try to change font size in properties

This is a regression. It works in 4.3.2
Reported twice
https://musescore.org/en/node/367710
https://musescore.org/en/node/362373

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/3564a0f6-afcd-4797-8b46-cbc9dc4e941f

### What is the latest version of MuseScore Studio where this issue is present?

Musescore 4.4.0 and master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
By design: the size of these symbols is now changed via __Style > Text styles > Repeat text left/right > Musical symbols scale__.

**Comment by MarcSabatella** [comment]
Would still be nice to have this setting available as a per-element override in the Properties panel, though (and with the "..." menu to update default style).  Especially since the default size is now much larger than before and many people immediately want to shrink it and it isn't at all obvious how to do so.  Of course, I'm assuming the increase in the default size of these elements was by design.  If not, that's also worth looking at.

**Comment by Biscuit-Trolley** [comment]
+1 for Mark's suggestion.
This feels like a regression. Aside from making it significantly more inconvenient to change the sizes, it is now impossible to change the sizes of different symbols independently. 
I also think they looked better previously, so it would be nice to have the option to change the font if that would allow the previous design to be regained.

**Comment by jeetee** [comment]
To what is the current relative scaling percentage? I'd expect it to be compared to the (relative) font size of the text, no?

As such, I'd also expect being able to scale those symbols by changing the font size of the (part of) the text they belong to. So for a musical symbols size of 100% I expect the symbol at a text at 20pt to be twice as big as the same symbol in a text at 10pt.
If I then change the scale % to 80% I expect both symbols to become scaled accordingly, with the one inside the 20pt text still being twice as big as the one inside the 10pt text.

But if I then select that symbol inside the 10pt text and set it to 20pt, I do expect it to match the symbol from the 20pt text. Just as I would expect any text character to behave that way when setting it with a custom text size.

**Comment by oktophonie** [comment]
The percentage is 'absolute'; the point is that they are music symbols, designed as part of a single music font, all in proportion to each other. A normal note on a stave is at 100%, and all other symbols on the stave are normally at 100% as well (unless you make them cue-sized, for example).

Things like dynamics, 8vas, pedal symbols, etc _used_ to be treated as text (and it's understandable why they would be thought of that way) but they aren't, really - they are music symbols and should be in proportion with other music symbols. The complication arises because they are used as part of text items, hence why there's a method to control the size of text and music symbols independently.

**Comment by jeetee** [comment]
It's funny how I indeed initially expect Pedalling/8va/plain dynamics as musical symbols and don't really hold that same anticipation with regards to repeat texts/symbols. Perhaps in part due to having seen very varying sizes of those symbols in the wild.

While I understand (and appreciate) the logic behind the current behavior, the interaction with those symbols and the text within their text-like containers *feels* unnatural to me. My UX expectancy might be a bit skewed and conditioned by the previous MuseScore versions; but even after letting the current logic sink for a few moments I can't shake that feeling..

A style I'd like to still be able to use is one where the symbols in the jump instruction are slightly smaller (and as such more inline with the text of the instruction) than the in-score symbol markers. I'd use a default sized Segno and Coda and then in the jump instruction use "D.𝄋. al 𝄌" have those symbols scaled a bit smaller. These type of jump instructions using symbols happen more often in scores where varsegno/coda are also used; clarifying the specific targets in that instruction.
If I'm not wrong, this approach is currently no longer feasible, leading to larger jump instructions.

**Comment by oktophonie** [comment]
@jeetee You're quite right, of course. We (sort of) had the problem in reverse before - different text sizes for Repeat text left and right (in order to get different sized symbols) which led to inconsistent text sizes between the two. But the new system is at least as bad (and confusing).

SMuFL does give us two different scales for glyphs, by means of the musical symbols font vs the musical text font; perhaps the former could be used for individual symbols, the latter for when you have them in text. But what we don't have yet is a way to specify which of these is used for a given text type, or even a given item - some types use the former (pedal markings, dynamics, ottavas, repeats/jumps), others (like plain Staff text) use the latter.

We can't add _that_ flexibility right now (i.e. for 4.4.3) but it seems sensible to me to just revert this change for repeat/jump text so that it works as before.
