### ISSUE TITLE
MuseScore 4 freezing when hiding an instrument (Mac only, memory leak)

### ISSUE THREAD

**Issue by mapsblu3** [musescore/MuseScore#24431]
### Issue type

Crash or freeze

### Description with steps to reproduce

I have a score with two instruments (vocal + piano).
I can hide the piano without trouble, but when I try hiding the vocals, I get the spinning wheel of death.
MuseScore 4.4.0.242390800 on Mac (Sonoma 14.6.1)

[Tomkins - Then_David_Mourned - SS.zip](https://github.com/user-attachments/files/16873445/Tomkins.-.Then_David_Mourned.-.SS.zip)

### Supporting files, videos and screenshots

![musescore](https://github.com/user-attachments/assets/004c5566-dce7-4fd5-810d-55fda4fdba97)

Also see https://github.com/musescore/MuseScore/issues/24431#issuecomment-2329416158

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in **MuseScore 4.3.2**

### Operating system

macOS 14

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
@mapsblu3 Please attach the score (zip the file before attaching), I can't reproduce the crash on my scores

**Comment by DmitryArefiev** [comment]
> Came up again in https://musescore.org/en/node/368111, along with a score I can't reproduce on Windows And it is more likely a regression vs. 4.3.2

Thanks! I **can reproduce** with that score on my **Mac13.6**




https://github.com/user-attachments/assets/bf0e59a2-13cf-4ff0-95cf-0371b62d3bbe
![Screenshot 2024-09-04 at 18 38 05](https://github.com/user-attachments/assets/180f97c3-46e7-4a04-be10-3ae249b9bd86)

(Doesn't occur on Win/Linux)

**Comment by cbjeukendrup** [comment]
Did some debugging. The problem seems that at some point in https://github.com/musescore/MuseScore/blob/08e952c8a67596781db89803d70474aa2bd6a114/src/engraving/rendering/score/lyricslayout.cpp#L343-L344
`startLyrics->shape()` returns an empty shape because `startLyrics->shape()` has not been initialised; and `emptyShape.right()` returns `-DBL_MAX`. This `-DBL_MAX` results in `dashCount` being a huge number, which is problematic because that is used as an upper bound for a `for` loop later on.
@mike-spa I see you worked on this code most recently, so you might be the best person to figure out _why_ `startLyrics->shape()` is not initialised. Tip: run in the debugger, and pause when the memory usage starts exploding.

(It is not a memory _leak_ though, and also not an infinite loop. In theory, if you had 100GB RAM or so, the loop would terminate, and when the score is closed, the memory is properly freed.
(A memory leak is namely when memory is allocated but then every reference to it is lost so that it can never be deallocated anymore until the program terminates.))

**Comment by cbjeukendrup** [comment]
I think I found a solution myself :) https://github.com/musescore/MuseScore/pull/24486

**Comment by Flemminglr** [comment]
This seem to occur if you have used a hyphen in your lyrics. Remove any hyphens in the lyrics and you can hide the instruments without crashing.

**Comment by Jojo-Schmitz** [comment]
These hyphens may very well be the elements with an empty shape. If they are: they should not, same for the melisma underscores, as that screws up the automatic layout, the collision avoidance

**Comment by cbjeukendrup** [comment]
The thing with the empty shape was the `Lyric` element at the left of the hyphen or extension line. This is because the `Lyric` is not laid out when it is on a hidden staff. By error, we _were_ trying to lay out the hyphen / extension line on hidden staves.

**Comment by Jojo-Schmitz** [comment]
That's what I mean. If those hyphen/melisma shapes weren't empty, that not only had prevented this crash, but also layout collisions. Until now, only the former is fixed

**Comment by cbjeukendrup** [comment]
But that's not what I said. It's the `Lyric`, i.e. the syllable, that has an empty shape, _not_ the hyphen/extension. (Well, the hyphen/extension may or may not have an empty shape too, but it is the empty shape of the `Lyric` that is causing the crash.)

I don't fully know what you mean about collisions; but note that all of this only applies to hidden staves, so you would not have seen the `Lyric` nor the hyphen/extension anyway.

**Comment by Jojo-Schmitz** [comment]
Ok, misunderstanding then

**Comment by MarcSabatella** [comment]
Also, as I recall from having attempted to add collision avoidance for lyric lines several years ago, the issue isn’t the lack of a shape for them, but rather a matter of when during layout  they get generated.  Here is a comment I made about it back then that has a little more detail (more than I would otherwise have remembered) - https://musescore.org/en/node/280139#comment-895889

**Comment by Jojo-Schmitz** [comment]
That's the problem I was referring to

**Comment by mike-spa** [comment]
Which collisions are you guys referring to exactly? Can you share an example from 4.4?

**Comment by Jojo-Schmitz** [comment]
Hmm, no, I can't reproduce un 4.4.1.
Mu3: 
![image](https://github.com/user-attachments/assets/b297f009-2d3e-4c8c-b6db-995cab0d7f5e)

**Comment by mike-spa** [comment]
Yeah, and that's because lyrics line collisions [have been fixed](https://github.com/musescore/MuseScore/pull/22434) in 4.4
