### ISSUE TITLE
The second score file cannot be opened

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#24478]
### Issue type

Opening/saving issue

### Description with steps to reproduce

The first score file opens normally. But if you want to open another score file, the following message will appear: "This file does not exist or cannot cannot be accessed at the moment."
1. Open/create any score file
2. Try to open any other score file

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/fa99b1eb-ab3b-4fba-8e63-d8539b0efec3

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mercuree** [comment]
It's already fixed in 4.4.1

**Comment by MarcSabatella** [comment]
I believe what youŕe seeing has nothing to do with the order of opening the scores, but everything to do with the special characters in the pathname.  But that bug is indeed already fixed for 4.4.1, releasing imminently - see https://github.com/musescore/MuseScore/issues/24289

If you are seeing another issue *not* connected to the special characters in the pathname, please provide more details to allow that issue to be reproduced.  But in general, 4.4. certainly allows opening as man y files as you like - provided the pathname does not contain special characters.

**Comment by Dima-S-Jr** [comment]
To be sure: I tested this in the last nightly build, but apparently the problem has not gone away. The only thing that has changed is that the message "This file does not exist or cannot cannot be accessed at the moment." has stopped appearing at all. So, @MarcSabatella, I don't think it's related specifically to #23811.

https://github.com/user-attachments/assets/ad694bbe-91c9-44b5-b0ea-64652b22855a

Just in case, I have attached the diagnostic files (below).
[The second score file cannot be opened.zip](https://github.com/user-attachments/files/16895938/The.second.score.file.cannot.be.opened.zip)

**Comment by mercuree** [comment]
@Dima-S-Jr 
1. Maybe this is unrelated crash on opening. Can you open that file in the normal way?
2. Diagnostic zip archive doesn't contain log files, because user folder contains cyrillic letters #19111

**Comment by Dima-S-Jr** [comment]
Hmm, it's strange, this doesn't happen anymore in 4.4.1. But in 4.5.0 MuseScore Studio just crashes. Moreover, it crashes when opening not any (second) score, but when opening some specific scores. 
Okay, I'm closing this issue for now, if I notice that regression continues to be relevant, then I'll reopen it.

**Comment by mercuree** [comment]
@Dima-S-Jr Can you share with us that specific score which crashes for you?

**Comment by Dima-S-Jr** [comment]
> @Dima-S-Jr Can you share with us that specific score which crashes for you?

Yes, of course. Here are some of them: [not opening in 4.5.0.zip](https://github.com/user-attachments/files/16898256/not.opening.in.4.5.0.zip)

**Comment by Dima-S-Jr** [comment]
Wow! I just updated to 4.4.1 and when opening the files I attached above, MuseScore Studio also started to crash, as in 4.5.0. 
@DmitryArefiev, please check the reproducibility for yourself (I attached a list above in the comment)

**Comment by Jojo-Schmitz** [comment]
Better reopen this issue

**Comment by Dima-S-Jr** [comment]
> Better reopen this issue

It is better to open a new issue, because this one was originally for a completely different situation.

**Comment by MarcSabatella** [comment]
I tried the "piano piece based on fibonacci sequence" and confirm it crashes in 4.4.1.  It opens normally in both 4.3.2 and 4.4.0, so it's a very recent regression.

**Comment by Dima-S-Jr** [comment]
> I tried the "piano piece based on fibonacci sequence" and confirm it crashes in 4.4.1. It opens normally in both 4.3.2 and 4.4.0, so it's a very recent regression.

Do my other files open normally, or the same way?

**Comment by MarcSabatella** [comment]
I will take your word for it if you say they all have the same problem.  I just wanted to be sure at least one did, and that it was singled out by name so we wouldn't waste time trying out different files from the ZIP looking for one with a problem.  Presumably these files all have something in common and that is what is triggering the bug, but once someone is able to take a look and identify the cause of the one, it would be a simple matter to spot check a few of the others too.

**Comment by rpatters1** [comment]
This problem is caused by the following lines of code added to `beamtremololayout.cpp` on September 2 in commit a606904e9e.

```cpp
            } else if (chordRests.size() == 3) {
                const Chord* otherOuterChord = outerChord == firstChordRest ? toChord(lastChordRest) : toChord(firstChordRest);
                const int otherOuterLine = ldata->up ? otherOuterChord->upNote()->line() : otherOuterChord->downNote()->line();

                if (innerLine == otherOuterLine) {
                    sameLineException = 1;
                }
```

Specifically it is failing when attempting to call `toChord(firstChordRest)`. (That is, it crashes.)

I am a newbie around here, but I might be able to figure out a fix with a little more context for why the code was added.

**Comment by Jojo-Schmitz** [comment]
See #24500

**Comment by rpatters1** [comment]
I have a question about the `CONVERT` macro. Is there a specific reason it does not use `dynamic_cast`? At first glance, this seems like a safer version of `CONVERT`:

```cpp
#define CONVERT(a)  \
    static inline a* to##a(EngravingObject * e) { a* ret = dynamic_cast<a*>(e); assert(ret); return ret; } \
    static inline const a* to##a(const EngravingObject * e) { const a* ret = dynamic_cast<const a*>(e); assert(ret); return ret; } \
    bool is##a() const { return dynamc_cast<const a*>(this) != 0; }
```

This appears to have the following advantages:
- potentially eliminate the need for a separate list of codes of `EngravingObject` types (that must be manually maintained).
- removes risk of accidental `reinterpret_cast` caused by the C-style cast.
- eliminates the need to maintain two lists of `CONVERT` macros.

I am a big believer in the old adage, "if it ain't broke don't fix it", so I am not proposing any refactoring at this time. Rather, I am wondering if there is context behind the choice not to use `dynamic_cast` that I should be aware of.

Thanks

**Comment by cbjeukendrup** [comment]
I believe a problem with `dynamic_cast` is that it requires the type, that is casted to, to be a "complete type", i.e. the header file where it is defined needs to be included. This means that almost _all_ header files will need to be included in `engravingobject.cpp`, also leading to circular includes. 

But I see a trick that will maybe get around that: in EngravingObject, define
```c++
    template <class T> 
    bool is() const { return dynamic_cast<const T*>(this) != nullptr; }
    
    template <class T>
    const T* to() const { return dynamic_cast<const T*>(this); }
```
Because of the use of templates, these methods are only "instantiated" when they are called; so if `is<Pedal>` is not used in a certain translation unit, then it won't be instantiated, and the compiler won't see any `dynamic_cast<Pedal*>`, so pedal.h doesn't need to be included in this translation unit but only in those translation units that do use `is<Pedal>` and/or `to<Pedal>`.

Bonus:
```c++
    template <class T1, class... T2s> // I always forget where exactly the ... belongs
    bool is() { return is<T1>() || ... || is<T2s>(); } // this is intended to be a C++17 fold expression but I'm not sure if I got the syntax right
```
call like `is<Pedal, Ottava, Volta>`.

Another possibility would be something like this:
- `EngravingObject` declares `template <typename T> bool is() { return T::classOf(this); }`
- and `template <typename T> T* to() { assert(!this || is<T>()); return T::convert(this); }`
   (I think we _can_ use `dynamic_cast` here, because 
- Every class defines `static bool classOf(EngravingObject* e) { return dynamic_cast<ThisClass*>(this) != nullptr; }` 
- and `static ThisClass* convert(EngravingObject* e) { return dynamic_cast<ThisClass*>(this); }`

Interestingly, a while ago, a start was made with that approach, but it was never fully rolled out. 

However: the existence of `ElementType` has advantages too:
- being able to see the element type in the debugger, even during contructors/destructors
- being able to do `switch (element->type())`
- being able to create elements by type at runtime, see `Factory::createItem`

**Comment by rpatters1** [comment]
It looks to me like both `Factory::doCreateItem` and the `switch` example are instances of the [Curiously recurring template pattern](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern). C++17 has an elegant (or at least "c++") solution for this using `std::variant` and `std::visit` that would not require an element type.

One severe disadvantage I discovered to `std::variant` and `std::visit` is that macOS does not support them in pre-10.13 sdks. I believe we are still using 10.10. For my plugins, I ended up cutting off support for pre-10.13, but I realize that could be a big step for MuseScore.

I haven't used the debugger enough to notice, but shouldn't it be showing the fully qualified element type even inside a generic routine? I know it's possible, because both XCode and VS debuggers do, but of course that doesn't mean Qt's debugger does. Oh well.

**Comment by rpatters1** [comment]
To give a simple example (with no doubt syntax errors):

```cpp
class sc1;
class sc2;
class base
{
    using scptrType = std::variant<sc1*, sc2*>;
    scptrType m_scptr;
public:
    base(scptrType scptr) : m_scptr(scptr) {}
};

template<typename T>
static base* CreateItem() { return new T(); }

class sc1 : public base
{
public:
   sc1() : base(this) {}
};

class sc2 : public base
{
public:
   sc2() : base(this) {}
};

base* val = CreateItem<sc1>();
```

I can't actually think of reason to use `std::visit` for the switch statements I found. Most could be done with virtual functions.

Anyway, it's just idle blue skying at this point.

**Comment by cbjeukendrup** [comment]
But in this example, `sc1` still has to be specified at compile time. Sometimes it has to be specified at runtime, for example by the QML plugin API, or during pasting or reading files, see also Factory::createItemByName. The latter can of course also be implemented though as `if (typeName == "Accidental") return new Accidental(); else if (typeName == "Ambitus") return new Ambitus(); etc.`

**Comment by Jojo-Schmitz** [comment]
What confuses me about those CONVERT macros is that not only the to<something> ones are done via CONVERT, but also the is<something> ones, I'd rather have them having a different name.
