### ISSUE TITLE
Add Undo Text and Undo History

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24509]
### Your idea

Add Undo Text that describes each Undo item on the stack and add a History that allows undo/redo to a specific point on the stack.

### Problem to be solved

Currently, it is not possible to see what Undo steps have been performed nor to pinpoint a specific Undo step to which one wishes to Undo. This is an extremely helpful feature, and not having it seriously degrades the editing experience, especially for users coming from Finale.

### Prior art

Both Finale and Dorico support this feature. I don't have Sibelius to check, but I would be surprised if it did not.

Here is an example of the menu on Finale. (Dorico is quite similar.)

<img width="286" alt="Screen Shot 2024-09-06 at 10 22 32 AM" src="https://github.com/user-attachments/assets/cbaf91b7-b3af-4f22-8d8d-8544655a0fb4">

Here is the history window in Finale. (Dorico is somewhat similar.)

<img width="604" alt="Screen Shot 2024-09-06 at 10 23 24 AM" src="https://github.com/user-attachments/assets/d92c6a82-d871-4bed-a4f2-4846092963f9">

### Additional context

I have searched the open issues but did not find this after searching "Undo History". I realize it is probably not a trivial change, but I thought I would add it to the pile so we have it documented.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
Implementation ideas:
- Add a parameter of type `TranslatableString` to `UndoStack::beginMacro`, that will be used to specify the name of the action
- Adjust all methods that indirectly call `UndoStack::beginMacro`
- The history dialog shouldn't be too difficult to implement; just use `StyledDialogView`, `StyledListView`, `ListItemBlank` etc.
- To get the data for this dialog, add some new methods to `INotationUndoStack`; then create a new `UndoHistoryModel` class that uses these new methods and exposes the data from C++ to QML
- The "--- Document saved ---" feature from Finale will take a bit more work potentially, since I believe this is not recorded in the `UndoStack` from the engraving module; adding this feature can potentially be done in a later iteration
- Another slightly difficult part will be to dynamically display the names of the undo commands in the menu bar. One way would be to implement this in AppMenuModel and UndoRedoModel individually. 
Another way would be to add infrastructure to do it via `NotationUiActions`; that class currently contains `actionEnabled` and `actionChecked` methods with corresponding change notification, and you could add another `actionTitleOverride` method; this method would return an empty `TranslatableString` (or MnemonicString?) for most actions meaning that the titles of those should just use the default, while for undo/redo it returns the currently actual names. 
The first option (AppMenuModel and UndoRedoModel) might be better though because of its simplicity.

**Comment by rpatters1** [comment]
One of the features the Finale plugins have is the ability to specify an Undo string. I don't know what that entails, vis-a-vis MuseScore plugins, but it seems like it should be a consideration in the design.

**Comment by rpatters1** [comment]
I am looking at this as a way to get my feet wet. I think I'll go in phases, where phase 1 is displaying the Undo/Redo text. Phase 2 would be the history function, and Phase 3 (if we get to it) would be including last-saved point in the history. Let me know if that does not sound like a good approach.

**Comment by cbjeukendrup** [comment]
Certainly!

**Comment by rpatters1** [comment]
It looks like the only place `beginMacro` is called is `startCmd`. Is the idea to change every call to `startCmd` to pass in text that describes the command? If so, is there some convention to follow for the context parameter (to the `TranslatableString` constructor) that allows it to be gracefully translated? Or is the string already there somewhere and I'm missing it? (That seems too good to be true.)

**Comment by cbjeukendrup** [comment]
Usually, the context is the module name, where the module name can be determined from the file path (in `src/notation`, it would be `notation`). 
But it might be desirable to have a separate context for all the undoable action names. Maybe just `undoableaction`?

When you write `TranslatableString("undoableaction", "Some action name")`, this string can automatically be detected in the source code, to be sent to Transifex, where users can create a translation for it. So you don't need to do anything extra other than explicitly using the TranslatableString(…) constructor.

**Comment by rpatters1** [comment]
Using `undoableaction` makes the many changes of `startCmd` calls a lot more straightforward, so with your approval I think we'll go with that.

Another feature that I added for my Finale plugins (and was glad I did) is a selection range where appropriate (of only measure numbers). That is, instead of "Undo Delete Measures" to have "Undo Delete Measures 1 - 3". It seems like that information my be readily available in the undo object, but it would be helpful to know if there is an easy way to know when it is applicable.

This would probably be either phase 3 or phase 1.5. But it would be helpful to get a sense of how feasible it is before embarking on a bunch of changes.

**Comment by cbjeukendrup** [comment]
It is possible to dynamically insert values into a translatable string. For example consider this string:
```
TranslatableString("undoableAction", "Delete measures %1 - %2").arg(startMeasureNumber, endMeasureNumber)
```

When you call `.translated()` on this string, you will get `"Delete measures 1 - 3"`. (Calling `.translated()` will be done in the UI code that presents the string to QML; so you won't need to think about that bit (yet).)

**Comment by rpatters1** [comment]
Thanks for the information about how to call `.args`. That is most helpful.

To make this less dependent me figuring out which messages to add ranges to for every call to `startCmd`, I was hoping to append the measure range inside `beginMacro` based on the undo selection range. Is there a way to know when the undo selection range is applicable?

**Comment by rpatters1** [comment]
Also, I notice that MuseScore uses sentence case for menu items. Does that mean the undo messages should be all lower case? `TranslateableString("undoableaction", "delete measures")` would result in (e.g.) `Undo delete measures`.

**Comment by cbjeukendrup** [comment]
> I was hoping to append the measure range inside `beginMacro` based on the undo selection range. Is there a way to know when the undo selection range is applicable?

I'm afraid that's going to be difficult, because an `UndoMacro` knows nothing specific about its "content". Also, I think it is preferable to keep beginMacro abstract and simple, and do action name computations outside it. 

Re. sentence case: maybe that would be good actually. (Another option would be to use it as `Undo 'Delete measures'`, i.e. with quotation marks. That's probably what's going to happen in many translations anyway.)

**Comment by rpatters1** [comment]
I decided to see if I can get the undo menu to dynamically change to something hard-coded, so I modified `UndoRedoModel::makeUndoItem` as follows (just as a test).

```cpp

QVariant UndoRedoModel::makeUndoItem()
{
    MenuItem* item = new MenuItem(actionsRegister()->action("undo"), this);

    static std::unique_ptr<QString> originalUndoTitle;
    if (! originalUndoTitle) {
        originalUndoTitle = std::make_unique<QString>(item->translatedTitle());
    }

    muse::ui::UiActionState state;
    state.enabled = undoStack() ? undoStack()->canUndo() : false;
    item->setState(state);
    item->setTitle(muse::TranslatableString::untranslatable(*originalUndoTitle.get() + " '" + "Delete measures" + "'"));

    return QVariant::fromValue(item);
}
```

This sure enough changes the title of `item` as intended, but the change is not reflected in the UI. One thing I noticed is that `MenuItem::setTitle` calls `emit actionChanged` rather than `emit titleChanged`, but that may be by design.

There is definitely something I am missing here.

**Comment by cbjeukendrup** [comment]
It's weird that it is not reflected in the UI; when I copy that into my `makeUndoItem`, I certainly see the change in the UI, but note that this affects only the undo/redo _toolbar_ (top right corner), rather than the Edit menu. The Edit menu is handled by AppMenuModel.

The current UndoRedoModel implementation is actually quite problematic because it creates a `new MenuItem` every time that it is called (which means, every time you perform any action). It's not really a memory _leak_, because it uses the `QObject` parent/child relation (`QObjects` delete their child objects in their destructor, so when UndoRedoModel is deleted it deletes these MenuItems), but still this is not good for memory footprint.

So I would suggest:
- refactor UndoRedoModel so that it creates exactly two MenuItems, and not more than that; store these in member fields
- intialise these fields with `nullptr`
- create new getter methods that just return the MenuItems from the member fields, and lazily create the MenuItems when the member field is `nullptr`
- make the `Q_PROPERTY` in `undoredomodel.h` use this new getter method instead of `makeUndoItem`
- whenever something about the undo stack changes, update only the title and state of the MenuItems, don't create new MenuItems

A bit like this:
```c++
MenuItem* UndoRedoModel::undoItem()
{
    if (!m_undoItem) {
        m_undoItem = makeUndoItem();
    }
    return m_undoItem;
}

MenuItem* UndoRedoModel::makeUndoItem()
{
    MenuItem* item = new MenuItem(actionsRegister()->action("undo"), this);

    // Set title
    TranslatableString undoableActionName = undoStack() ? undoStack()->topmostUndoActionName() : {}; // TODO: create topmostUndoActionName in INotationUndoStack
    if (!undoableActionName.empty()) {
        item->setTitle(TranslatableString("action", "Undo ’%1’").arg(undoableActionName));
    }
    
    // Set state
    muse::ui::UiActionState state;
    state.enabled = undoStack() ? undoStack()->canUndo() : false;
    item->setState(state);

    return item;
}

void UndoRedoModel::updateUndoItem()
{
    // Update title
    muse::ui::UiAction action = actionsRegister()->action("undo");
    
    TranslatableString undoableActionName = undoStack() ? undoStack()->topmostUndoActionName() : {}; // TODO: create topmostUndoActionName in INotationUndoStack
    if (undoableActionName.empty()) {
        m_undoItem->setTitle(action.title);
    } else {
        m_undoItem->setTitle(TranslatableString("action", "Undo ’%1’").arg(undoableActionName));
    }

    // Update state
    muse::ui::UiActionState state;
    state.enabled = undoStack() ? undoStack()->canUndo() : false;
    m_undoItem->setState(state);
}
```

**Comment by cbjeukendrup** [comment]
I made a start already at cleaning up `UndoRedoModel`, see https://github.com/musescore/MuseScore/pull/24543. You can probably fetch the commit from that PR and build on top of it.

**Comment by rpatters1** [comment]
Perfect, thank you.

**Comment by rpatters1** [comment]
With your help, I have the Undo/Redo panel text updating correctly in the UI (using PR #24543). Now I am proceeding to `AppMenuModel` for the text in the Edit menu.

It looks to me like I need to register for an event when the undo stack changes, but I'm just too green with Qt to know how to set it up. As far as I can see, there is no function in the `AppMenuModel` that is called after program startup.

**Comment by cbjeukendrup** [comment]
See `AppMenuModel::load()`, or more specifically, `AppMenuModel::setupConnections()`.
It may also be useful to know that you can call `findItem("undo")` to retrieve the 'undo' item, so that you can update its title. See also `AbstractMenuModel::onActionsStateChanges` and how/where it is used; you won't need to use or modify it, but it may be useful as an example.

**Comment by rpatters1** [comment]
Got it, thanks.

It seems like all that's left in Phase 1 is adding all the descriptions (and probably cleanup).

FWIW: I tested plugins with and without strings sent to `sendCmd`. Works like a champ either way. I don't know if earlier versions of MuseScore will balk at strings that don't recognize, though.

Now for slog time...

**Comment by rpatters1** [comment]
Any idea why this code is in `NotationActionController::canReceiveAction`:

```cpp

    if (!masterNotation->hasParts()) {
        return code == UNDO_ACTION_CODE || code == REDO_ACTION_CODE;
    }
```

It causes `Redo` to be available on the Edit menu after deleting all parts. But there is not actually anything to redo.

**Comment by rpatters1** [comment]
I have the Undo/Redo history dialog working now, but I ran into a small issue. If you do as follows:

- Open a New Score and add an instrument
- Make any change (I change the title) -- this step is probably not necessary
- Open the Add Instrument panel and immediately close it without changing anything
- Open the Add Instrument panel again and add an instrument

When you are done, there are 2 undo events on the stack, but the Undo and Redo menu commands skip the one that didn't change anything. Is there an easy way to get similar behavior in the history?

**Comment by rpatters1** [comment]
Other than the question above, which doesn't seem to hurt anything but creates a bit of UI inconsistency, phase 2 is ready to go. I could go ahead submit it, but I think it would be safer to stage in the techdebt PR and the phase 1 PR before doing so. Then I could submit a clean rebased single-commit PR. (I could also do that still, but it probably would eliminate both of the earlier PRs.) Anyway, I'm holding off with the final PR until I get an indication of how to proceed. I know everyone is busy with `4.4.2` (and `4.4.3` and >gasp< `4.4.4`) at the moment, so no worries here.

The only concern I have is if someone adds a new call to `startCmd()` or the functions that call it.
