### ISSUE TITLE
MSS.4.1: Clicking a Text object's bounding box deselects the Text object

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#24531]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

In MuseScore 4.4.1
Add  a Text object to a score
Paste in:
 
Lorem ipsum dolor sit amet, 
consectetuer adipiscing elit. Praesent et erat. 
Donec blandit, lectus vitae
tempus semper, urna lorem posuere pede,

When you click the bounding box (for instance, the white background to the right of "amen" or "vitae" or in the blank lines below "pede") MuseScore deselects the entire Text object. 

This was not the case in 4.3.2 or earlier versions of MuseScore.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/76d881c9-9d05-47bb-8b9f-975bc489e413

### What is the latest version of MuseScore Studio where this issue is present?

MS 4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13.5.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
To some extent, this is by design: the shape of the text element is now calculated more precisely than just taking the bounding rectangle. This leads to better spacing and positioning. However, for interaction it might not be ideal indeed... on the other hand, it makes it easier to select exactly what you want in situations with many elements close together. If the entire bounding box of the text item would accept clicks, that would be annoying if you have to select an item that is underneath the bounding box but does not actually overlap with the text.

**Comment by scorster** [comment]
Thanks for your reply. 

Indeed selection is affected depending if the bounding box accepts clicks or not. And that could be a significant matter in a score with densely pack objects. Nevertheless, the current behavior definitely makes text editing more challenging. 

So there are competing interests. But isn't there a standard approach to select through the z axis? Command-click?

I just noticed another side effect. Previously I could click anywhere a Text Objects bounding box to drag the object. Now the same gesture drags the score.

If this could be governed by a Preference I'd turn off the new behavior and rely on command-click to get the the object I want. Those who commonly work in densely packed scores may want to have the new behavior as their default.

**Comment by bkunda** [comment]
This is by design. The idea of being able to select text by clicking somewhere in an empty space around the text (which is in no way visually indicated to the user) is actually the surprising (indeed, odd) behaviour. It makes much more sense to actually select the text you want to select, which is indeed the current behaviour.

I'm also not a huge fan of developing additional preferences to govern such peculiar behaviour, as this just adds to feature bloat.

**Comment by scorster** [comment]
Thanks for your reply Bradley.

For the record, it's not entirely uncommon to select a text object by clicking "empty space" within its bounding box. 

I tried two applications (Affinity Designer and Apple Pages) and in both cases it works. I believe Adobe Illustrator also behaved this way, but I don't have a current version to test.

Videos attached.


https://github.com/user-attachments/assets/b5d43334-96e6-4efe-8f6e-1d676fbaf1c0

https://github.com/user-attachments/assets/f4b80467-1c41-4f20-ac5c-09430e551f56

**Comment by scorster** [comment]
Also, you can click beyond text in this line and drag leftward to select.

If one uses that common selection technique in MSS4.4.1, rather than selecting text, MuseScore drags the score.
