### ISSUE TITLE
Preferences: Remember which tab was last open within a session

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#24678]
### Your idea

The Preferences window currently always opens to the 'General' tab. If I switch to a different tab, close the window, and reopen it, it should open to the last tab I had open.

If I quit and reopen MuseScore Studio, it should start back on the 'General' tab.

### Problem to be solved

This would remove the extra step of pointing and clicking back to where you were if you're trying to stay focused on one area of preferences (i.e. setting up a bunch of shortcuts or changing appearance).

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by pacebes** [comment]
Hi

I volunteer to try to implement this issue with help.

I have been looking into the code and if I'm right:

- PreferencesDialog.xml creates the window and "on completed" calls _preferencesModel.load(root.currentPageId)_. If you change _property string currentPageId: ""_ to _property string currentPageId: "canvas"_ Preference windows will be opened on this tab
- preferencesmodel.cpp: _void PreferencesModel::load(const QString& currentPageId)_ could be used to set the initial tab
 
But, it seems Preference window is created and destroyed (_PreferencesModel::~PreferencesModel()_)every time the user asks for it.  Then currentPageId is forgotten.

Are there within MuseScore any method to store key Values that last while the application is running ?. That could be a way to store the _PreferenceCurrentPageId keyValue_ and restore within PreferencesModel::load if _currentPageId_ is empty

Kind Regards

**Comment by avvvvve** [comment]
@pacebes I can't find a specific code example for you (I am but a humble UX designer), but the code for the Format > Style... dialog might be helpful to look at. That dialog remembers the last "tab" that was open from the list on the left when you close and open it.

<img width="956" alt="image" src="https://github.com/user-attachments/assets/dab0c246-ee24-4ac3-b5ce-805d51fafd31">

**Comment by cbjeukendrup** [comment]
@pacebes That looks about right! There are some stylistic details, but those are easier to point out when you open the Pull Request, because then I can comment on individual lines. 

In general, make sure that the indentation is correct, and that there are no multiple blank lines in a row (one is enough) and that there are no blank lines before a `}`.

Also, note that names of member fields should start with `m_`, i.e. `m_preferencesDialogCurrentPageId`. 

For the rest I'll check it in the Pull Request itself!

**Comment by pacebes** [comment]
Hi @cbjeukendrup 

I don't know if I should ask about them here or in the pull request...

I created the pull request which failed because of "Codestyle / codestyle". I have run " tools/codestyle/uncrustify_run_file.sh" on them and then

- git add ...(Files)
- git commit --amend --no-edit

I have tried to push it again and I get

> git push --force
> fatal: The current branch 24678-rememberTabPreferencesWithinSession has no upstream branch.
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin 24678-rememberTabPreferencesWithinSession
> 
> To have this happen automatically for branches without a tracking
> upstream, see 'push.autoSetupRemote' in 'git help config'.

But I'm not sure if this is the right option. Could you help me with that ?
