### ISSUE TITLE
I cannot open previous version file(score)

### ISSUE THREAD

**Issue by Balllllamute** [musescore/MuseScore#24722]
### Issue type

Crash or freeze

### Description with steps to reproduce

I don't have much time

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/4822a756-a746-4a9d-b001-5813edbba581

[Utterance amidst the junk pile (고물덩이 속 속풀이) Acl 젊은작곡가 공모작.zip](https://github.com/user-attachments/files/17003300/Utterance.amidst.the.junk.pile.Acl.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows.11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Attach the score, zip if first

**Comment by Balllllamute** [comment]
> Attach the score, zip if first

[Uploading Utterance amidst the junk pile (고물덩이 속 속풀이) Acl 젊은작곡가 공모작.zip…]()

**Comment by cbjeukendrup** [comment]
> I don't have much time

This is perhaps not very respectful to the developers: they also don't have much time, and will need to set aside time to look into your issue. Of course, that's part of their job, but especially taking into consideration that MuseScore is completely free, it would not be out of place to help the developers a tiny bit by at least describing the issue properly as far as necessary (or at least not explicitly refusing to do so). 

Anyway... it turns out that this crash has already been fixed for 4.4.2, which will be released within the next few days. In the meantime, you can download a 4.4.2 nightly build from https://musescore.org/en/nightly-builds.
