### ISSUE TITLE
MuseSampler is found but MuseSounds don't appear in MuseScore 4.4 (in Mixer)

### ISSUE THREAD

**Issue by iwoithe** [musescore/MuseScore#24760]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

1. Either update MuseScore 4.4 or install it via MuseHub
2. Install MuseSounds via MuseHub
3. Open MuseScore via "Launch" in MuseHub
4. Create new score with an instrument that you have installed with MuseSounds

**Observations**
- Open Mixer and observe MuseSounds do not appear in the drop down
- Checking via the diagnostics menu does indeed show that the latest version of **MuseSampler is found**
- In the playback setup dialog, MuseSounds is selected and active, but greyed out
- Deleted MuseSamplerCoreLib.dll and restarted MuseHub

### Supporting files, videos and screenshots

Diagnostic of the screen recording below: [diagnostic.zip](https://github.com/user-attachments/files/17021401/diagnostic.zip)

https://github.com/user-attachments/assets/a67175d8-f301-47b8-ad13-eccdc3157409

### What is the latest version of MuseScore Studio where this issue is present?

Latest release (4.4.2)

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

**What I've tried so far**
(MuseScore always installed via MuseHub and always opened MuseScore with the "Launch" button in MuseHub on first start)
- Uninstalled and reinstalled MuseScore
- Uninstalled and reinstalled MuseHub and MuseScore
- Uninstalled and reinstalled MuseHub, MuseSounds, and MuseScore + restart my device

**Similar-ish issues (can't find one exactly like this though)**
- https://github.com/musescore/MuseScore/issues/24366
- https://github.com/musescore/MuseScore/issues/24480
- https://github.com/musescore/MuseScore/issues/13952
- https://musescore.org/en/node/367919

If there is a report exactly matching this one that I've missed while searching, feel free to close this one 🙂

**Other random context**
- I have not changed any of the default paths in MuseHub or MuseScore

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
@iwoithe Hi! 
* Can you check your system Time and Date are setup correctly in Windows?
* Did you use MuseHub Beta previously?
* You can try to delete **MuseSamplerCoreLib.dll** in  c:\Users\user name\AppData\Local\MuseSampler\lib\ and restart MuseHub

**Comment by iwoithe** [comment]
@DmitryArefiev

- Time and date are setup correctly
- Yes, but hadn't downloaded MuseSounds
  - I installed MuseScore via the new MuseHub a month or two back
  - Recently (within the last week) downloaded MuseSounds, then immediately found this issue
- Yes, I've tried that as well already (forgot to mention), but didn't work

**Comment by DmitryArefiev** [comment]
@iwoithe Can you try **Clear application cache** (MuseHub>Settings>Technical) and restart MuseHub?

**Comment by iwoithe** [comment]
Just tried it but unfortunately it still doesn't work

**Comment by DmitryArefiev** [comment]
Can you try to delete **.config** file in c:\Users\username\AppData\Local\MuseSampler\ and restart MuseHub?

**Comment by iwoithe** [comment]
Didn't work either.

Just noticed something a little bizarre: every now and then `Diagnostic > Muse Sampler > Check Muse Sampler`  says Muse Sampler isn't found (the playback setup dialog also reflects this), but then upon restarting MuseScore it's found again (but still with the same bug as in this report)

**Comment by DmitryArefiev** [comment]
OK.

Can you also attach a screenshot what you have in Diagnostic>System>Show paths ?

**Comment by iwoithe** [comment]
![{7993F9CF-EE60-45EA-8976-E96824FBE517}](https://github.com/user-attachments/assets/3bc45421-62ff-46a7-8fc1-1923a2528fd9)

**Comment by DmitryArefiev** [comment]
> Edit:
> This gets interesting...

O, that's expected. It should be empty for MuseSampler path in DevTools

**Comment by DmitryArefiev** [comment]
@iwoithe Last thing you can try is to clean up all folders related to MuseSounds and MuseSampler. 
My assumption that MuseHub 2 Beta->MuseHub 2 is involved somehow

1. Close MuseHub and MuseScore Studio
2. Delete **MuseSampler** folder from c:\Users\username\AppData\Local\
3. Delete **MuseHub** settings folder from c:\Users\username\AppData\Local\
4. Delete MuseSounds and settings: **MuseHub** folder from c:\ProgramData\MuseHub\ and/or  c:\Users\username\
5. Reinstall MuseHub and MuseSounds

**Comment by iwoithe** [comment]
@DmitryArefiev That seems to have resolved the issue, thank you!

**Comment by scorster** [comment]
I hope this post is relevant to this topic.

For weeks my purchased MuseScore libraries have failed to in the Mixer>Sounds menu in museScore studio 4.4 and 4.5.0 and 4.5.1.

[I've posted here on Github](https://github.com/orgs/musescore/discussions/25963#discussioncomment-12544603), and on .org and have posted Bug and Support tickets with MuseHub. These efforts produced no insights or solutions.

Nevertheless I got it working today with the following steps:

    1) open the MuseHub app
    2) click on the Library "tab" in the bottom left
    3) locate a problematic/missing library (for me, Muse Guitars Vol 2) 
    3b) chose **Uninstall** from the "down arrow" menu
    4) when uninstall finished a download button appears
    5) click the download button
    6) close MuseHub
    7) open MuseScore Studio

    **Result:** Best I can tell **ALL my missing libraries now appear in Mixer>Sound>MuseSounds>Muse**

If there's no wiki on this issue, perhaps my list of step will help others. 

MuseHub didn't help in the least. [I've post this solution to my discussion.](https://github.com/orgs/musescore/discussions/25963#discussioncomment-12665334)

**Comment by scorster** [comment]
Since the release of MuseScore Studio 4.5.2 I've been using various MuseSounds libraries without issue.

But again today I encountered [the missing Muse Guitars Vol. 2 issue (posted above.)](https://github.com/musescore/MuseScore/issues/24760#issuecomment-2764362869) Fortunately I was able to remedy the situation with the steps I had provided in the mentioned post.

Anybody know what causes this disconnect?

**Comment by lahmn** [comment]
**System affected:** Dell Latitude 5300 2-in-1  
**OS:** Windows 11  
**MuseHub version:** 2.3.8.1908  
**MuseScore version:** 4.5.2  
**MuseSampler status:** Detected  
**MuseSounds status:** Installed and active in playback configuration  
**Mixer behavior:** MuseSounds not available; only MS Basic appears

---

**Description of the issue:**

MuseScore correctly detects MuseSampler and MuseSounds. Playback works with MuseSounds if the score was previously configured on another system (MSI Prestige 15), where everything functions as expected. However, on the Dell Latitude 5300, MuseSounds do not appear in the Mixer interface. Only MS Basic is shown, despite MuseSounds being selected in the playback configuration.

All installations were done using default paths. Cache and config files were cleared. MuseSamplerCoreLib.dll is present in `AppData\Local\MuseSampler\lib`, and diagnostics confirm MuseSampler is detected and paths are correct.

Replacing the MuseSamplerCoreLib.dll with the working version from the MSI system did not resolve the issue.

---

**Steps taken:**

- Full reinstall of MuseHub, MuseScore, and MuseSampler using default paths ✅  
- Cleared MuseHub cache and MuseSampler `.config` ✅  
- Verified playback configuration (MuseSounds selected) ✅  
- Verified MuseSampler detection via diagnostics ✅  
- Replaced MuseSamplerCoreLib.dll with working version from MSI system ✅  
- Mixer still only shows MS Basic ❌

---

**Conclusion:**

This appears to be a confirmed bug affecting specific systems, even when all components are correctly installed and detected. The issue is not resolved by reinstalling or replacing libraries. It seems to be a UI-level failure to expose MuseSounds in the Mixer, despite backend functionality working.

Please advise if further logs or diagnostics are needed. Happy to assist with testing or provide additional system details.

**Comment by nadovaalexandra18-maker** [comment]
Dobrý deň, potrebujem poradiť. Mám naištalovaný musehub aj zvuky , ale v musescore musesapler chýba. Ja som už zúfala. Ale zaujímave .že v starom počítači problem nieje ale v novom áno......prosím poraďte
