### ISSUE TITLE
Replacing instruments doesnt update instrument numbering and brackets correctly

### ISSUE THREAD

**Issue by Ash-86** [musescore/MuseScore#24848]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

If you add a second instrument of an already existing one, the instrument numbering doesnt update correctly. 
If you replace an instrument with an already existing one, numbering and brackets dont update correctly. 

### Supporting files, videos and screenshots

first, violas should become **violas 1** and **2**. Brackets with violin should be removed.  **violin 1** shoud lose its numbering.
second, when adding cellos, first cello should become **cellos 1**

note that the viola brackets update correctly after an instrument is added. 

https://github.com/user-attachments/assets/54b281c2-0875-47d0-8b48-bdfab21f7224

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

No.

### Operating system

windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Numbering and bracketing is something supplied as a starting point when you create the score, which you can modify thereafter as you like. Therefore some of this behaviour is (for now) 'by design' - we don't renumber things, for example, because we have no way of knowing what your intention is or what operation you might perform next. Also the numbers are added as part of the instrument name itself, rather than as something separate.

I'm wary of trying to be clever about adjusting brackets right now because of e.g. https://github.com/musescore/MuseScore/issues/15027 (basically: whatever you do, you're bound to get it wrong for someone!)

There is a long-term to plan to address all of these issues so that this can work in a more intelligent way, it's just going to take time (see, for example, https://github.com/musescore/MuseScore/issues/15616, https://github.com/musescore/MuseScore/issues/15027, etc.)
