### ISSUE TITLE
All versions after 4.3.2 freezing on startup

### ISSUE THREAD

**Issue by c-bueller** [musescore/MuseScore#24860]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open Musecore Studio 4
Expected behaviour: be able to open up scores and create new ones
Actual behaviour: cannot click on anything, everything is frozen

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/9b207bb9-967d-48d3-ab6e-d590595702cf

white boxes are to block out names, are not part of musecore

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

I've recently upgraded from a laptop to a new pc, used an ssd cloner to transfer programs, used to work perfectly on my old laptop, no idea why it stopped working here.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Do you by chance use multiple monitors? There is currently a problem where dialogs and popups tend to appear on the wrong monitor or appear not at all; so maybe there is a dialog open, blocking interaction with the main window, but you can't see that dialog. Idea: you could use a screen reader (such as Microsoft Narrator) to find out. 

You could also try if #24644 solves it (see [How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) for how to test it).

**Comment by c-bueller** [comment]
I downloaded the test build but when i clicked it my antivirus deleted a file and musecore didn't open. I also tried the screen reader but nothing seemed out of the ordinary. I use one monitor.

**Comment by cbjeukendrup** [comment]
It's inconvenient that you can't run the test build. The reason that the antivirus complains is that this build is not signed, because it is only a test version and not a definitive release. So it's exactly as safe as a normal build, but only doesn't have certain signatures. Maybe you can find a way to let your antivirus allow this build.

Another thing that might be useful is the following:
1. In Windows Explorer, enter `%LOCALAPPDATA%\MuseScore` into the address bar
2. Create a ZIP archive of the `MuseScore4` and `MuseScore4Development` folders
3. Upload it here

**Comment by c-bueller** [comment]
[MuseScore4.zip](https://github.com/user-attachments/files/17090399/MuseScore4.zip)
[MuseScore4Development.zip](https://github.com/user-attachments/files/17090401/MuseScore4Development.zip)

**Comment by cbjeukendrup** [comment]
Thanks for uploading. The main log files show nothing enlightening; no unexpected error messages. Have you tried pressing 'Esc' at the moment that MuseScore gets stuck?

The "development" log files (from the test version) show that the app failed to launch because of a missing library, so probably indeed because the antivirus deleted that. You can try re-downloading the test build, and then convincing your antivirus not to mess with it.

**Comment by c-bueller** [comment]
Thank you! as simple as it may seem pressing esc allowed musecore to work! was it because it dismissed the invisible dialog box?

**Comment by cbjeukendrup** [comment]
Yes, Esc would indeed dismiss the invisible dialog. So that must have been the problem!
That probably means that you're indeed experiencing the "popups and dialogs appearing on wrong monitor or not at all" problem (even though you have only one monitor); the fact that the menus are not appearing is most likely the same problem. Others have reported that that seemed to be fixed by https://github.com/musescore/MuseScore/pull/24644, so that's why I mentioned that build. But if you can't get that working because of antivirus, you can also wait for the next update, because the changes from that test build are planned to be included in the next update.

**Comment by c-bueller** [comment]
My issue's completely solved now. The problem was that in my display settings in settings, I had to make sure everything only displays on the monitor I'm currently on despite not having any other monitors.
![image](https://github.com/user-attachments/assets/a432c1e5-5f60-47d8-9184-19026f268d2d)
