### ISSUE TITLE
Mixer not opening

### ISSUE THREAD

**Issue by DaltoGit** [musescore/MuseScore#24874]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

On Opensuse Tumbleweed, with Musescore 4.4.2 Flatpak.
Simply opened a file, and pressed mixer, doesn't do anything. I tried View/Restore default layout. Worked on 4.3 from Opensuse Repos. I've tried reinstalling Musescore, and reinstalling Muse Sounds.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/c24cb3f2-bc0c-47a9-9a83-0415ffed7bd9
(you might need to download video to see it, it's viewable in VLC)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OpenSUSE Tumbleweed

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bloodwolfepc** [comment]
This also Broke for me in the latest version.

OS: NixOS 24.11.20240919.c04d565 (Vicuna) x86_64
LOGS: https://gist.github.com/bloodwolfepc/ae45deb08fbd582423b419c8d714b01c

**Comment by cbjeukendrup** [comment]
First of all, neither the FlatPak nor the NixOS distribution are maintained by us, so we can only provide a limited amount of help.

It would be good to double-check if this problem also occurs in the 'official' AppImage (downloadable from musescore.org homepage; then make executable using `chmod +x` and just run it, no install required). 

I seem to recall that FlatPak and NixOS build MuseScore with Qt 6.7.2, while the AppImage uses Qt 6.2.x. With Qt 6.5+, there are some known issues; actually it looks like this issue is covered by https://github.com/musescore/MuseScore/issues/24866 (see also the discussion in https://github.com/musescore/MuseScore/issues/24097). If you agree, then we should close this issue and refer to https://github.com/musescore/MuseScore/issues/24866 instead. 

The probable reason that it didn't happen with MuseScore 4.3 and earlier, is that those versions still used Qt 5, which did not have problems like this.

**Comment by adam248** [comment]
it is still strange that going from version 6.2.x to 6.5+ leads to a breaking change.
I thought versioning should be A.B.C == A = major (breaking changes), B = Minor (non-breaking changes), C = Patches (also non-breaking). or is Qt versioning not following that rule?

**Comment by cbjeukendrup** [comment]
I don't really know if Qt has any specific versioning policy. And of course there is the concept of _accidentally_-breaking changes 😉

Anyway, I'll close this issue then. But thanks for bringing it up!
