### ISSUE TITLE
tablature accessibility

### ISSUE THREAD

**Issue by nobody459** [musescore/MuseScore#25339]
### Your idea

it would be great to add the possibility to write using tablature (at least for string instruments). this feature already exists in guitar pro and tuxguitar so why not with muse ?

### Problem to be solved

it would make the program more accessible for musicians who struggle with sight reading.

### Checklist

- [x] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
Writing for tablature is already supported: 
- for many stringed instruments, there is a TAB option available in the Add/remove instruments dialog
- to convert an existing staff to tablature, go to the Instruments panel, expand the row of the instrument containing the staff, then on the row for that staff, click the ⚙️ button, and in the resulting popup, change the staff type.
    <img width="302" alt="Scherm­afbeelding 2024-10-27 om 19 07 17" src="https://github.com/user-attachments/assets/459409d3-0d0a-4f4a-bdfc-0225c17dc495">
- bonus: you can also create _linked_ staves, so that the staves are automatically synchronised. Open that same popup for the desired staff, and click "create linked staff". 
    <img width="302" alt="Scherm­afbeelding 2024-10-27 om 19 08 42" src="https://github.com/user-attachments/assets/1062f92e-880d-41c4-937f-14cddeb3df33">

See https://musescore.org/en/handbook/4/working-instruments for more information.
