### ISSUE TITLE
problem with the french translation

### ISSUE THREAD

**Issue by nobody459** [musescore/MuseScore#25338]
### Your idea

i'm a native french speaker and the way the instruments are named in the french version of the site is extremely weird.
i really doubt a native french speaker has done it.

### Problem to be solved

?

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
> of the site

Do you mean MuseScore**.com**? In that case, this problem needs to reported to the MuseScore.com team instead, for example at https://musescore.com/groups/improving-musescore-com. (To be honest, indeed I doubt whether the MuseScore.com team have any human French translators…)

But if you actually mean in MuseScore Studio, then it would be great if you could explain a bit more specifically about what's wrong. Since MuseScore Studio uses an open translation platform, you can make corrections yourself, if you want, at: https://app.transifex.com/musescore/musescore/translate/#fr
More information: 
- https://github.com/musescore/MuseScore/wiki/Help-translate-MuseScore
- https://github.com/musescore/MuseScore/wiki/Translating-instrument-names

I hope this helps!

**Comment by nobody459** [comment]
hi !

no i was talking about the muse score app.

well i can give you an exemple if you want :
in the synths group there s an instrument labelled as "synthetiseur de maillet".
i'm almost sure no french speaker as ever used that world.

there s also many instruments (especially synthetizers) that are given a french name when in fact
(as far as i know)
every one calls them by their english name.
(i.e. the synth called "synthetiseur d effet" which doesnt mean much in french.)

thx for replying !

best regards !!!!


________________________________
De : Casper Jeukendrup ***@***.***>
Envoyé : dimanche, octobre 27, 2024 5:42:21 PM
À : musescore/MuseScore ***@***.***>
Cc : nobody459 ***@***.***>; Author ***@***.***>
Objet : Re: [musescore/MuseScore] problem with the french translation (Issue #25338)


of the site

Do you mean MuseScore**.com**? In that case, this problem needs to reported to the MuseScore.com team instead, for example at https://musescore.com/groups/improving-musescore-com. (To be honest, indeed I doubt whether the MuseScore.com team have any human French translators…)

But if you actually mean in MuseScore Studio, then it would be great if you could explain a bit more specifically about what's wrong. Since MuseScore Studio uses an open translation platform, you can make corrections yourself, if you want, at: https://app.transifex.com/musescore/musescore/translate/#fr
More information:

  *   https://github.com/musescore/MuseScore/wiki/Help-translate-MuseScore
  *   https://github.com/musescore/MuseScore/wiki/Translating-instrument-names

I hope this helps!

**Comment by cbjeukendrup** [comment]
I see. Feel free to make these corrections on Transifex, using the links above; that would be great!

**Comment by JLWALTENER** [comment]
@nobody459 , A better way is to join us on our French translation forum :  https://musescore.org/fr/forum/688
Open a new thread with your suggestions, the French translators team, a few people, will be glad to review your suggestions.
Cordialement

**Comment by cbjeukendrup** [comment]
Thanks @JLWALTENER, that sounds like a good idea. Assuming this will be sorted out at the forum, I'll close this issue.
