### ISSUE TITLE
Interface Issue - Strange Language Switching While Working

### ISSUE THREAD

**Issue by Y-PLONI** [musescore/MuseScore#25359]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Body: As shown in the video, the language displayed in the software on my end is Hebrew. However, when I click on a menu item, it switches to Arabic. Then, when I click on another text, it reverts back to Hebrew, and the current item turns to Arabic! This behavior is quite frustrating, and I would appreciate any assistance in resolving this issue.

### Supporting files, videos and screenshots

![20241028-1616-18 5406934](https://github.com/user-attachments/assets/366fdb51-def5-46d9-85f2-41abae4e034f)

### What is the latest version of MuseScore Studio where this issue is present?

Latest version

### Regression

I was unable to check

### Operating system

WIN11, 24H2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
This seems another manifestation of https://github.com/musescore/MuseScore/issues/24287, so I'll have to close it as a duplicate. It's a Qt bug, so fixing it requires another Qt update, which we could not do in MuseScore 4.4.3 because it would have been too risky. However, a fix is planned for 4.5. In the meantime, you can try selecting a different font in Preferences > Appearance; some people say that that fixes it for them.
