### ISSUE TITLE
Musescore Playback System Overhaul

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25392]
### Your idea

This is a formal request for Musescore's playback system to be overhauled to provide better playback for fast music, strings, and orchestral pieces. This is not a Muse Sounds request; it deals with the actual playback system of Musescore.

### Problem to be solved

Musescore's system presents an incorrect rendering of music. Two examples: Mahler's Second Symphony, final movement, when played in Musescore, sounds thin, awkward, and the general impression is that it was orchestrated by an amateur. This is unfortunate, because Mahler's Second Symphony is hailed as a masterwork of orchestration. If Musescore cannot render it acceptably, it cannot be trusted to provide a faithful musical rendering to those who use it to compose today.
Shostakovich's 5th Symphony, final movement, is not given any momentum, and what is lacking in both examples is musical cohesion. (e.g. When the wind section doubles the strings, it creates a new texture; some might say a new sound. Musescore simply provides a conglomeration of instruments.)

### Prior art

Noteperformer solves this with AI.

### Additional context

If Musescore does not intend to provide compatibility with Noteperformer, it should have a good alternative. I fully support the idea of attempting to create an alternative, and propose a few rules of playback for energetic passages and orchestral works:
1) Quarter note passages should be played marcato.
2) Any repeated notes should be played staccato, and slightly more accented than the rest of the passage.
3) Staccato in general should be increased (in any tempo, repeated notes are currently slurred beyond recognition, and it is ridiculous to have to add staccato marks to every repeated note for an allegro tempo.)
4) The last note of any and all string runs is always staccato/accented
5) Eighth notes, when bracketed by a rest on both sides, should always be accented.
6) Two note groups should have a clear attack on the first note, but the emphasis falls on the second.
7) Three-note figures and turn-like figures, when repeated, should have a clear separation (rest) between them, and the final note of each figure is staccato.
8) A grace note lead-up to any single note automatically makes that note accented.

Musescore should be able to sense "pulse" in music and apply it to playback accordingly; it should sense "buildup" (which usually extends throughout a whole piece); and it should "lean" into phrases.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
This partly _is_ a MuseSounds issue. Certain libraries will be better suited to more articulate rendering at faster tempi than others. More libraries will soon be released in MuseHub that will allow users to access to a broader range of playback possibilities. 

It's true though that there's still room for optimising how the playback engine itself renders notation events. What's difficult, though, is imposing rules the likes of which you've outlined above. For example, there is no reason for quarter-note passages to always be played back marcato, or for the last note of string runs to be accented (these would be highly undesirable in a lot of cases). 

What works well for some music won't work well for others. The better solution is therefore to provide more options for the user to flexibly customise their playback. We are working on these at the moment. 

If you have specific library requests, please don't hesitate to send them directly to the Muse Sounds team: https://support.musehub.com/hc/en-gb/requests/new.

Otherwise, I do also agree that we need to look for ways to express what you describe as "build up" and "leaning into phrases". This really is a feature request in itself. 

For future reference, it's more helpful for us to read issues that are more precisely scoped than general ones like this that call for an "overhaul" and rely too much on subjective assessments ("orchestrated by an amateur" / "...cannot render it acceptably").

**Comment by Fourniture** [comment]
If all that is planned is to have greater customization ability, with more and more sound libraries for tedious fine tuning, then I would request support for Noteperformer. Orchestrators and composers don't want high quality audio if it is at the expense of realistic playback. I offered some rules for an algorithm based playback system if Musescore did not want to use AI. These rules have exceptions,  but they apply in the great majority of cases. Right now, string runs in sixteenths sound better when every note is marked staccato; the default slurring is that extreme. There are numerous other playback problems that the Musescore team seem anxious to sidestep or work around, which is quite frustrating. I repeat, if they cannot do what Noteperformer does, they should add support for it. Playback was to check for wrong notes and to give an idea of the shape and form of the work. In this respect, midi works better than any MuseSounds; it is much easier to mentally make up for deficiencies in playback than to re-imagine what the system actively plays wrong. A poor playback system defeats the purpose of playback, no matter the quality of its libraries.
