### ISSUE TITLE
Software Crash

### ISSUE THREAD

**Issue by cslov260** [musescore/MuseScore#25448]
Almost every time I try to write a piece it keeps crashing and making me loose all my progress and I don’t know what to do.

**Comment by MarcSabatella** [comment]
If you have a specific score and series of steps that reliably reproduces the crash, please ZIP and attach the score here and give the steps.  Otherwise, please ask for help on the support forum at musescore.org, where you can attach your score describe the problem you are seeing more generally, and people may be able to help you find the precise steps to reproduce the problem.

**Comment by bkunda** [comment]
Closing due to lack of information and inactivity. 

If you are able to reproduce the crash reliably, please raise a new issue and follow the prescribed format in our issue template (including attaching relevant score(s) and diagnostic files).
