### ISSUE TITLE
Disconnect between Musescore 4.4 and Muse Sounds Manager

### ISSUE THREAD

**Issue by cddurham** [musescore/MuseScore#25510]
OS: Linux Mint 22 Cinnamon
Musescore 4.4.3.242971445
Muse Sounds Manager 1.1.0.587(x64) beta

I noticed Muse Sounds were not available after upgrade to the version listed above. Diagnostics said library not found. Muse Hub was removed; I read that it was deprecated and Muse Sounds Manager was to be used instead. The current version of Muse Sounds Manager at musescore.org is the beta version listed above. I downloaded that and installed it. Muse Sounds Manager would only start if I invoked it from CLI with sudo. At first, it indicated the sounds were already installed and would not let me reinstall. I deleted them through the manager and reinstalled. 

Same problem with Musescore. Log indicated the sample library is not compatible. I then checked the default download location in Manager, which is /root/muse-sounds-manager/downloads. Musescore is expecting a library file at /home/[username]/.local/share/MuseSampler/lib/libMuseSamplerCorelib.so, There is no such file at that location; the fikder is empty.

Instead of a lib file, Manager downloaded a tree. Folder muse-sounds-manager in /root contains folders Installers, Instruments, and .musedl along with two files: .dlcache and .receipt.
Folder Installers contains a folder with a long hex number name. That folder contains musesampler-linux-0.6.3.196.tar.zip and musedownload-manifest.json. I could not do anything with the zip file.
Folder Instruments contains folders for various instrument types and a file .instruments. Each instrument type folder contains folders for individual instruments; each of these contains a SFZ folder and an optional [instrument name].spx file. The SFZ folder contains a file: [instrument name].sts.

It thus appears Muse Sounds Manager has implemented a file structure different than what MuseScore 4.4 is expecting for Muse Sounds.

**Comment by MarcSabatella** [comment]
A new Muse Sounds Manager is expected pretty soon, so this may turn out to be moot, but FWIW, the current version *does* work in general.  It isn't clear what is off on your system - if something went wrong with the installation Muse Sounds Manager, or if something went wrong installing the sounds, or if something is wrong with your installation of MuseScore Studio (are you using the ofificla Appimage? Third party builds often have problems like this).

But on my system, the libMuseSamplerCoreLib.so is indeed present in ~/.local/share/MuseSampler/lib.  So I'm assuming that is correct, and the question is, why is it *not* present on your system.

I'm going to guess it's because you run Msue Sounds Manager under sudo - so then it makes sense it wouldn't install into your home holder.  What do you mean when you say it "would only start" if involved with sudo?  What went wrong otherwise?  Works just fine for me in user mode.

But I'd guess you could also run MuseScore Studio as root and then it might find the Muse Sampelr library wherever Muse Sounds Manager did actually put it.

**Comment by cddurham** [comment]
Hi Marc, 
Thanks for the fast reply. I did install MuseScore from the official appimage. When I try to run Muse Sounds Manager any way except via command line with sudo, nothing happens. I could try reinstalling the manager, but the last time I tried it, it said the latest version was already installed. I had to go in and remove the downloaded file and download again to get it to work.
Hopefully the new manager will clear things up. 

    On Thursday, November 14, 2024 at 06:57:59 AM PST, Marc Sabatella ***@***.***> wrote:  
 
 


A new Muse Sounds Manager is expected pretty soon, so this may turn out to be moot, but FWIW, the current version does work in general. It isn't clear what is off on your system - if something went wrong with the installation Muse Sounds Manager, or if something went wrong installing the sounds, or if something is wrong with your installation of MuseScore Studio (are you using the ofificla Appimage? Third party builds often have problems like this).

But on my system, the libMuseSamplerCoreLib.so is indeed present in ~/.local/share/MuseSampler/lib. So I'm assuming that is correct, and the question is, why is it not present on your system.

I'm going to guess it's because you run Msue Sounds Manager under sudo - so then it makes sense it wouldn't install into your home holder. What do you mean when you say it "would only start" if involved with sudo? What went wrong otherwise? Works just fine for me in user mode.

But I'd guess you could also run MuseScore Studio as root and then it might find the Muse Sampelr library wherever Muse Sounds Manager did actually put it.

**Comment by MarcSabatella** [comment]
When you say "nothing happens" when you run Muse Sounds Manager without sudo, does the process exit right away and return to a shell prompt, or just hang and never return to the prompt?  Is nothing at all printed to the console?  Normally it would produce quite a bit of console output even before opening a window.  if you're not even seeing that, something definitely seems very strange about your system.  it definitely works for others; you are the first person I can recall reporting a problem.

**Comment by bkunda** [comment]
It seems like there may be an issue with running MSM as sudo. In addition, there may be issues with using Linux Mint (which is not a fully tested/supported system).

For further support discussion, it'd be best to refer to the [support community](https://musescore.org/en/forum/6).

Closing this issue for now.

**Comment by cddurham** [comment]
Update: I read the messages produced when trying to start Manager without sudo. One said that permission was denied for /root/srv/muse-hub/downloads. I used chown to take ownership of srv, and reinstalled Manager. It now ran from CLI without sudo and also ran from the start menu. I then reinstalled the Sounds. Muse Sounds are now available in MS 4.4.3. The library file is back as well. 
Question: Are the plugins I see in Windows Muse Hub available in Linux, or will they be?
    On Thursday, November 14, 2024 at 08:11:46 PM PST, Marc Sabatella ***@***.***> wrote:  
 
 


When you say "nothing happens" when you run Muse Sounds Manager without sudo, does the process exit right away and return to a shell prompt, or just hang and never return to the prompt? Is nothing at all printed to the console? Normally it would produce quite a bit of console output even before opening a window. if you're not even seeing that, something definitely seems very strange about your system. it definitely works for others; you are the first person I can recall reporting a problem.

**Comment by MarcSabatella** [comment]
Is "root" your own user name?  Normally muse-sounds-manager should be installed into your own home folder, not anything privileged.  But maybe you had set a custom install folder?  Or the fact that you previous ran it under sudo caused it to remember that folder?  Anyhow, glad you got that sorted for now even though your libraries are now in the wrong location.  It's going be moot soon when the update comes out.

All the free Muse Sounds should be available on Linux, just from what I hear, not the paid ones unfortunately.  And since MuseScore Studio on Linux does not yet support VST3, none of the plugins.
