### ISSUE TITLE
Rhythm Notation Mode

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25553]
### Your idea

One style of rhythm notation is to write the notes without heads. I suggest that the "Rhythm Only" note input mode be amended or expanded for this. When in this mode, any notes written would be headless, but still be situated on the staff in the melodic line in which they are entered.

### Problem to be solved

There is no dedicated feature for this, and it is essential to have this capability for both Big Band and Jazz.
![20241116_144526](https://github.com/user-attachments/assets/5d3f28aa-1aba-49d3-ac72-5101581b5e19)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Fourniture** [comment]
This is an example of where the composer has an idea where he wants a comped melody to go, and he knows the rhythm he wants,  but he wants to give the pianist a bit more freedom than clearly defined notes. 
    Perhaps instead of amending the rhythm mode, there could be a whole extra mode, which is exclusively for inputing headless notes. This would not be as ridiculous as it sounds; it would make sense to a jazz musician, and it would set precedent for if and when Musescore has capabilities to write chant. Then there would be another mode for chant, which writes out old style chant notes in free rhythm.

**Comment by MarcSabatella** [comment]
I'm a jazz musician and while I've seen the notate you show here, it is exceedingly rare.  I would disagree that there should be a special input mode for it.  It would be much more sensible to have it be an alternate engraving style, as rhythmic slash notation basically is.  So you could easily toggle between all of these modes for the same musical passage.

Chant is kind of a different beast; there it actually does make sense to have a separate mode since it also affects things like how durations and barlines are treated.

Anyhow, it's better to have these sorts of discussions on the forums, and only open issues here once a consensus has been reached as to both the necessity of a proposed feature and what it should like.  Then there is a much greater chance of the proposal being considered.

**Comment by Fourniture** [comment]
I can only say that I consider this an issue with good opportunities for expansion from a fix, and if development disagrees, they can close it.
