### ISSUE TITLE
The Method for Adding Frames is Counterintuitive

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25589]
### Your idea

Currently, the workflow for adding a new text frame to the first page of a score is:
Add -> Frames -> Insert Text Frame.
But nothing happens.
One instead has to select a rest, measure, or some other element in the score before adding a text frame. This is counterintuitive, because a text frame is by nature different from other kinds of text in that it is separate from the staff; it is not a staff element. I suggest that the method of adding text frames should be restructured as follows:
The "Add text frame" option should be moved from the "Add" menu to the right click menu, and replaced with the "Add Instruction Text Frame" option proposed in #25555. This preserves the workflow of selecting a place in the score and adding a text frame, but makes it more intuitive. When a user selects an element in the score, he can then right-click and choose to "Add text frame above system".
By replacing the generic text frame option in "Add" with an Instruction frame, the system would also make more sense; since the Add -> Text menu includes dedicated types of text, the Add -> Frames menu should have dedicated frames (even if they are technically the same as a generic text frame).
[Note: Instruction frames have left justified text and always appear below the title frame.]

### Problem to be solved

As above: One has to select a rest, measure, or some other element in the score before adding a text frame. This is counterintuitive, because a text frame is by nature different from other kinds of text in that it is separate from the staff; it is not a staff element.

### Additional context

If my above suggestion is rejected, I would at least ask that if a user tries to add a text frame without any part selected, then they see a message: "No note or rest selected | Please select a place in your score for the text frame to appear". This will make the process a little clearer.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
Since text frames can be added anywhere in the score, the user needs some way to tell the program _where_ a text box needs to be added. Making a selection seems to me the most intuitive way to do that.
We _could_ make it so that if nothing is selected, the frame will be added at the beginning of the score, but that would be a bit arbitrary; it make the behaviour less predictable, and prevents users from discovering that they can add frames anywhere. 
So if any change is needed at all, I think that the option of informing the user that they need to make a selection, is a better alternative. Ideally, we would do that in a slightly more elegant way than throwing an error message at the user; for example a small notification in the corner of the window that automatically disappears after 5 seconds. (same goes for the existing error messages about "nothing selected")

**Comment by bkunda** [comment]
I definitely agree that there's scope for improving the UX for adding frames. 

As it stands, it's fairly unavoidable to have to initiate a selection first before clicking any palette element to add it to the score.

**Comment by Fourniture** [comment]
I understand. That is why I suggested the right click option: it provided a clear connection between the place in the score and what the user wants to add. In my idea, only the elements that have a fixed destination are in the Add menu, but the right click menu contains what applies to a selected spot in the score.
