### ISSUE TITLE
Bug Muse Sounds messagem "purchasing is currently unavailable in your region"

### ISSUE THREAD

**Issue by ezabran** [musescore/MuseScore#25818]
Hello guys.
I'm trying to buy some playback expantions in Muse Sounds on Muse Hub but it always show this message:
"Purchasing is currently unavailable in your region..."
I'm in a country supported by Musescore and I'v tried VPN too but didn't solve.
Thank you.

**Comment by bkunda** [comment]
Hi there, 
this issue is actually one for MuseHub customer support. Please contact them here: https://support.musehub.com/hc/en-gb/requests/new.

This is the official list of supported regions: https://support.musehub.com/hc/en-gb/articles/20370299398429-Supported-countries

Please note that MuseHub and MuseScore Studio are separate products, so while MuseScore might be available to you, purchasing products via the Hub might not.

**Comment by ezabran** [comment]
Thank you Bkunda. I'm gonna try your suggestions.
