### ISSUE TITLE
when two voices playe the same note only one is heard

### ISSUE THREAD

**Issue by maddanio** [musescore/MuseScore#6241]
hi,
my son has just fallen in love with musescore, and he loves the pre-listen. but he discovered when two voices play the same note only one is played, he thinks it also happens with different instruments, but definitley when its the same (i.e.e two celli)

**Comment by MarcSabatella** [comment]
This is generally true when using the same MIDI channel, MIDI doesn't really have a straightforward way to do otherwise.  Depending on what his actual goal is, there are ways to achieve it, but we'd need to see the score in order to understand and assist better.

However, this isn't the right place to use when asking for help with MuseScore.  Please use the Support forum on musescore.org instead.
