### ISSUE TITLE
[MU4 Issue] Palettes and search field should be 30xp tall

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7634]
**Describe the bug**
Search field is taller then Palettes

**To Reproduce**
1. Create a new score
2. Look at search button on instrument panel

**Expected behavior**
Palettes and search field should be 30xp tall

**Screenshots**
![Скриншот 24-12-2020 03 49 07](https://user-images.githubusercontent.com/71372310/110156444-04c03980-7df8-11eb-9ed8-fd1726a36405.png)

**Desktop (please complete the following information):**
Windows 10 x64
MacOS

**Comment by wizofaus** [comment]
Not entirely sure what the problem is here, it looks like this for me on Windows:

![image](https://user-images.githubusercontent.com/5364225/121961653-090ed200-cdab-11eb-893b-ad61e9b433d6.png)

The "Add Palettes" button is indeed 30px tall, the search button is 31px tall - is this just a request to make the search button the same height as "Add Palettes"?
Has this had a UX review though?  To me the "Add Palettes" button looks quite like a text field that indicates what you're searching for. And the MU3 [...] button (with commands to Collapse/Expand all Palettes etc.) is missing.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/8098
