### ISSUE TITLE
Double and Halve note values (W/Q) only works on single notes, not selection

### ISSUE THREAD

**Issue by jwmatthys** [musescore/MuseScore#7637]
**Describe the bug**
In the past, it was possible to select a passage and press "W" to double all of the note lengths or "Q" to halve note values. This still works for individually selected notes, but no longer works when you select 2 or more notes.

**To Reproduce**
Enter two or more notes in a staff.
Select them.
Press the keyboard shortcut for Double Note Values (usually W)

**Expected behavior**
The passage should be converted into the same pitches with double note values

**Screenshots**

**Desktop (please complete the following information):**
 - OS: tested on Windows & OSX
 - Browser Chrome
 - Version: tested on 3.5.2 and 3.6.2
![double_bug](https://user-images.githubusercontent.com/716646/110171843-f48d6780-7dc1-11eb-9180-532bc9552e3d.png)

**Comment by jwmatthys** [comment]
Apparently this has always been the behavior. Apologies!

**Comment by worldwideweary** [comment]
By the way, the described behavior exists in "3.x" or "3.7" found within @Jojo-Schmitz stuff and no longer applies in MuseScore 4/4.1 

It's a strong productivity enhancement  to be able to make a range selection and half/double real quick through the keyboard. So even though this is a few years old and closed, maybe someone could make an effort to make it work more efficiently like the 3.x branch?

**Comment by MarcSabatella** [comment]
I think there is some confusion here.  "W" to double note durations couldn't possibly work in cases like the one shown - the notes would all overlap each other.  I think what you are really looking for is to not only double the duration, but also move the notes away from each other - stretch the whole passage out.  That works the same in MU4 as MU3 - Edit / Paste double duration (and also Paste half duration).

Now,* halving* (as opposed to doubling) duration "in place" - leaving the notes on the same beats, and adding rests between them - would of course be possible.  but no version of MuseScore has ever been released that supports this as far as I know.  It may be an unofficial build with an unmerged PR was made available, but that PR would need to be made for the current master and merged there to make it into an official release.

**Comment by worldwideweary** [comment]
@MarcSabatella Of course, which is why "3.x" or "3.7" with quotes was mentioned. Got used to the behavior since 2021 or so, along with a host of other functionalities, so now in half of 2023 it feels like a lacking, even though the "official" 3.6.2 or 4 never had it for the general populous.

As a demonstration of Q/W behavior, which is kinda nifty: 

https://github.com/musescore/MuseScore/assets/7139517/728e1e32-e548-4304-95e9-bbb7c3bf23a4

**Comment by MarcSabatella** [comment]
Hmm, from that picture it looks like it just does a paste half/double duration.  That to me isn't as useful as what I thought it might have been, a half/double *in place*.  Why have a second command to do what the existing ones already do?

**Comment by worldwideweary** [comment]
Yeah, an in place or "non-compressed" version would be useful for users I'd imagine. 
Not as *useful* as an alternative command, but very convenient. Maybe it's mere habit formed from having 3.x being able to do it. Seems easier to press Q (especially if the user wants twice half/double) instead of [copy/cut command] (Ctrl+C),[paste as half duration command] (Ctrl+Shift+Q). 

At least it seems better than Q *doing nothing* with range selection, but only toggling while in note-entry. But again, this is from being used to the 3.x PRs.
