### ISSUE TITLE
[MU4 Issue] Remove animations on scrolling

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7657]
**Describe the bug**
If user uses mouse wheel to scroll, scrolling speeds up when your starts scrolling and slows down when your stop scrolling

**To Reproduce**
1. Open Score Wizard
2. Try to scroll list of categories or instruments

**Expected behavior**
Remove all scrolling animations: Dialogs, palettes, inspector, etc. It is frustrating to use with both mouse wheel and trackpad. 
The scroller should immediately stop scrolling when the user stop scrolling.

**Desktop (please complete the following information):**
MacOS

**Comment by wizofaus** [comment]
On Windows using the mouse wheel to scroll doesn't even work in the New Score wizard - should it?

**Comment by wizofaus** [comment]
Google search finds quite a few people trying to work out how to change this behaviour (of all Qt Flickable elements), and it appears it's not straightforward - you can set "interactive" to false but that turns off mouse-wheel scrolling entirely. It seems you then have you implement that part yourself?  I also tried setting flickDeceleration and maximumFlickVelocity in InstrumentsView.qml (inside the ListView properties) but can't get it to stop the inertial scroll entirely, and the problem is these values can apparently act in a platform-dependent manner.
Note that this "flick" behaviour is actually pretty standard at least in Windows apps, e.g. when scrolling through a long Word document.  I suspect there wouldn't be a fixed pair of values for these properties that would work well for everyone.
Specifying maximumFlickVelocity to 1500 seems to make it slightly easier to navigate for me at least (Windows 10). The Qt documentation claims the default is platform dependent, but in the source it appears to be 2500. The default flickDeceleration is 1500, I tried making it as high as 50000, but it doesn't seem to make much difference.
If you're able to experiment yourself @vshalkevich  with different values to see what works best on various platforms that's probably the best?

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10085
