### ISSUE TITLE
[MU4 Issue] Popup blocks the user from clicking on the app when pop-up not in focus

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7658]
**Describe the bug**
Popup blocks the user from clicking on the app when not in focus

**To Reproduce**
1. Open a popup (parts, workspaces, etc.)
2. Navigate to a different app, like a browser
3. Try to click on the MS4 interface
4. You hear an error sound because the popup is blocking you from returning back to the main focus

**Expected behavior**
Pop-up should appear above other windows (should be visible) if user clicks somewhere in MU4
Pop-up behaviour should be the same as pop-ups in Adobe Photoshop for example

**Desktop (please complete the following information):**
Windows 10 x64

**Comment by wizofaus** [comment]
With the latest MU4 I don't observe this for the "Parts" dialog, but I do for "Score Properties".  Note that in MU3 it's true for "Parts" too, so MU4 appears to be an improvement here.  Where's the "workspaces" popup?  I believe in Windows this happens when a window doesn't have its "owner" set properly (and the main window is otherwise disabled).

**Comment by wizofaus** [comment]
Have tried everything I can think of to fix, it seems all the QWidget style dialogs have this problem and did in MU3 too.  The strange thing is that the system file open/save dialogs work fine, even though a nullptr parent is being passed in there too (which is what's happening here because MainWindowProvider::qMainWindow() is coded to always return nullptr).
They supposedly use QApplication::activeWindow() in this case - however this always return nullptr too - I believe because we're no longer using a QWidget-derived main application window.
In MU3 the "Export" dialog does actually behave correctly, but that's because it is able to get hold of a QMainWindow (the "MuseScore" itself is one of these) and pass it in as a parent.  There doesn't appear to be a QWidget available in MU4, and creating one with createWindowContainer doesn't work either. So I'm a bit stuck sorry...

**Comment by wizofaus** [comment]
Also I notice that we're using `KDDockWidgets::DockRegistry::self()->mainwindows()` but from the KD header files it seems this is a private implementation detail...
Anyway as far as I can tell QDialog just doesn't seem to be able to behave as expected when there's no top-level widget we can use as the parent.  But given most of the Widget dialogs seem to have been converted to QML dialogs now I'm guessing the plan is convert the rest of them too, in which case the problem goes away...

**Comment by Tantacrul** [comment]
Fixed
