### ISSUE TITLE
[MU3 Issue] when characters (time signatures) are removed, dimensional architecture breaks down 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7743]
**Describe the bug**
when characters (time signatures) are removed, dimensional architecture breaks down 

**To Reproduce**
1. Download exapmple score
2. Delete time signatures

**Expected behavior**
The score long should stay the same with time signature as without time signatures

**Screenshots**
[C.zip](https://github.com/musescore/MuseScore/files/6160459/C.zip)

**Desktop (please complete the following information):**
Windows build 3.6
Mac 3.6

**Comment by mattmcclinch** [comment]
Okay, I am going to say that this is by design. When time signatures are removed, MuseScore rewrites the affected measures (until the next time signature) so that they all have the new correct number of beats. In many cases, this means that extra time will have to be added to the last rewritten measure. There is no way around this. Time signatures are not just characters on a page. They have meaning that determines the length of the measures in the score, and yes, the length of the score as a whole.

**Comment by vshalkevich** [comment]
Thanks. 
If nobody will be against it, I could close this issue as it by design.
