### ISSUE TITLE
[MU4 Issue] Playback issues. Cursor and sound stopping on certain notes. Stops after second quarter note.

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7768]
**Describe the bug**
Playback issues. Cursor and sound stopping on certain notes. Stops after second quarter note.

**To Reproduce**
1. Create a score with notes
2. Start playing score
3. Stop playing at random note place

**Expected behavior**
Should be the same as in MU3 

**Desktop (please complete the following information):**
MacOS

**Comment by wizofaus** [comment]
Does this happen if you don't *change* the music?  There's definitely a bug currently that the playback is not updated after the first time you play the score, regardless of what subsequent changes you make, which can cause it to look like it's stopping randomly (e.g. if you'd added notes at the end since, the playback info doesn't have them),

**Comment by vshalkevich** [comment]
Cant reproduce this issue
