### ISSUE TITLE
[MU4 Issue] [enhancement] the slur button should not be a toggle

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7985]
**Describe the bug**
the slur button should not be a toggle: it should do the exact same thing as pressing the 'S' shortcut in MS3.6

**Comment by Tantacrul** [comment]
This is a high priority. In addition, the slur should work EXACTLY like it does in MS3. When the user adds a slur, it should remain selected. In addition, the shortcut (on Mac) cmd+Shift+Left (or right) should extend or contract the slur.

I would assign this to either @RomanPudashkin  or @elerouxx because these bugs have been introduced due to the new Slur button in the Note Input bar changes.

**Comment by wizofaus** [comment]
Cmd+Shift+Left/Right is implemented in my branch (https://github.com/musescore/MuseScore/pull/8908/).
It no longer appears to be a toggle, but it doesn't select it by default, can add that fix too easily enough.

**Comment by wizofaus** [comment]
Ok but in MuseScore 3 the slurs are *not* selected when you add them, but they are in edit mode anyway.
Are you happy with my proposal that adding a slur should deselect whatever note was selected and select the slur instead?
And what about the cases where slurs are added over a list or range of notes? (where in v3 you can't adjust the newly added slur).

**Comment by Tantacrul** [comment]
Oh, yes, I see. That MS3 behaviour would actually be quite clever... if it didn't block the user from using the main note input UI :) 
(although elements from palettes still work though, which is useful)

I think your suggestion for MS4 sounds about right. If indeed we could be clever and try not to interrupt further note input, that would be ideal. I have suggestions for new 'special' types of selection we could try in later versions but def out of scope for this.

Regarding list / range selections.... I'm in two minds. I can see why there wouldn't be a need to select the slur in those cases since multi-selection effectively specifies the length, so users most likely wouldn't need to shorten / lengthen them. I actually suspect MS3 has this right (despite all other major apps **_not_** doing this)

**Comment by Tantacrul** [comment]
About Palettes: we've deliberately not fiddled with this in MS4. I think there are some pretty simple and powerful UX changes we can make to how elements behave when applied / dragged. Won't burden this conversation with that detail though!

**Comment by wizofaus** [comment]
Ok but now we're proposing that slurs have a different behaviour to all other lines/spanners, in that they *do* get selected when added.  It'd be just as easy to make that true for all lines rather than just slurs if it makes more sense from the user POV.

**Comment by wizofaus** [comment]
Ooh - there's also commands "add cresc. " and "add dim." which add hairpins using shift+< and shift+>, and they *do* behave the same as slurs added (either via 's' command or the palette), whereby they're in edit mode automatically.  But as I said, when you add hairpins from the palette this doesn't happen.

**Comment by Tantacrul** [comment]
I can't see a reason not to do the same thing for other lines, like hairpins, ottava marks, pedal lines, etc. In those cases, it would be desirable. I didn't know that hairpin shortcut but the result makes sense. I'd say let's do it for all lines.

**Comment by wizofaus** [comment]
BTW it's not quite enough for the newly added line itself to be selected - it's "end" grip handle must also be selected for  SHITFT+arrow keys to work to length/shorten it (btw it is just SHIFT you need to hold down, CMD/CTRL shouldn't be necessary)

**Comment by Tantacrul** [comment]
> BTW it's not quite enough for the newly added line itself to be selected - its "end" grip handle must also be selected for SHITFT+arrow keys to work to length/shorten it (btw it is just SHIFT you need to hold down, CMD/CTRL shouldn't be necessary).

Yes exactly

**Comment by wizofaus** [comment]
Ok I have it working on my branch, except not when adding from the palette, because I can't see how to grab back the keyboard focus after clicking on the palette.  This is general problem with the way the various Qt windows work in MuseScore4 - there doesn't seem to be a good mechanism of ensuring that focus can be restored to the window showing the current score, and we need that in a quite a few places (e.g. while editing text, and using the toolbar to apply formatting etc.).

**Comment by wizofaus** [comment]
Interestingly there is a case right now where the keyboard focus has to be requested - if you manage to select a text element with the mouse and use Alt+Shift+E to enter edit mode (which in only implemented in my branch, so I'm surprised this works), then the window picks up the "textEditingStarted" notification and effectively grabs the keyboard focus back (though in a round-about way via QML scripts...), I guess we can make this mechanism more generic (in fact this appears to be the only use of the "textEditingStarted" notification, so it would be safe to send one after adding an element from the palette too, but to remove confusion it should really be renamed to something like "keyboardFocusRequested").

**Comment by Tantacrul** [comment]
Sounds like a question to put to @Eism @RomanPudashkin or @vpereverzev.

It would be great.

**Comment by wizofaus** [comment]
I noticed the logic to "toggle" the slur is in fact still in place. But is this so bad? Surely it's better than adding multiple slurs exactly the same to the same note (all drawn on top of each other, which is what v3 does)?  I agree if the first slur has been adjusted then it shouldn't toggle though.  But someone obviously wrote that code for v4, it's not just happening by accident.

**Comment by wizofaus** [comment]
So there is ONE useful case for adding two slurs between the same two start and end notes, which is if it's a passage in chords and you want to have slurs above and below:

![image](https://user-images.githubusercontent.com/5364225/132948092-8380ae63-97a2-4ae7-8a72-a8a1ac273e26.png)

But as long as the logic to "toggle" detects this and ONLY toggles if you have the exact default unadjusted slur in place already that won't be an issue.  I mean it's simpler just to get rid of the toggle logic, but the behaviour in v3 where you end up with multiple slurs all exactly the same on top of each other doesn't seem to be desirable either...

**Comment by Tantacrul** [comment]
> But someone obviously wrote that code for v4, it's not just happening by accident. 

Yes. I believe this was done on the assumption that slurs were the same kind of thing as ties. I personally don't see any massive reason to keep it as a toggle.

Regarding that thing MS3 does - where you can endlessly keep adding slurs, if it's a problem that we think people are likely to run into, we can always (eventually) set some smart limits.

Palettes is annoying that way. You can keep adding multiple articulations, etc.

**Comment by wizofaus** [comment]
Not hard to have it so that "adding" a slur that's already there just selects the existing one instead...

**Comment by wizofaus** [comment]
I've put some logic in that detects that there's already a "default" slur for a note, i.e. one that extends to the next note or rest, with stem direction = "auto", and if so, instead of adding a new one, just selects that one and puts it in edit mode.
However the "slur" button on the notation input model toolbar still acts as though it's supposed to show the status of the current note (whether it has a slur or not), which is consistent with the other buttons in the toolbar, but it doesn't make sense for it show the slur as "active"/selected, implying that clicking it again will toggle "off" the slur if that's not what it does, so I'll fix that too.

Having said that the toggle behaviour esp. in note entry mode had some advantages - it basically meant you could type S to add a slur from the note you just entered to whatever note you're about to enter, but then realise it's not what you meant and type it again to remove it, which is consistent with other commands like shift+v for accent or shift+s for staccato.   "S" is the only shortcut during note entry mode in v3 that keeps stacking more elements on top of each other (with no real visual clue that this has occurred, though weirdly every time you type S, the selection status of the slur changes).  At least with my changes that no longer occurs - typing 'S' multiple times after the initial slur is added does nothing.  I'll let you know when there's a build you can try it out on.

**Comment by Tantacrul** [comment]
OK, cool. Will test when ready

**Comment by wizofaus** [comment]
You should be able to test it in the latest build from PR, let me know if it doesn't work.

**Comment by Tantacrul** [comment]
Slurs are definitely a lot better.The toggle 'on/off' thing doesn't seem to be working but I quite like it as is.

**Comment by wizofaus** [comment]
Can you describe a bit better what you mean by on/off not working?

**Comment by Tantacrul** [comment]
I mean that the slur button in the top bar doesn't toggle on/off when I select a note with a slur attached. I seem to recall you liked the idea of keeping it as a toggle that would work a bit like the tie button?

**Comment by wizofaus** [comment]
Nah, I got rid of that, there were too many cases it didn't make sense (and this issue did explicitly say it shouldn't do that!). It's only a toggle in note entry mode depending on whether the slur is "active" or not (automatically extending as new notes are added)

**Comment by Tantacrul** [comment]
Gotchya

**Comment by wizofaus** [comment]
What exactly doesn't work? And did you try ensuring the notation window has the focus first?

**Comment by DmitryArefiev** [comment]
I mean shortcut to extend slur doesn't work 
(Shift+Left/Right to connect with next note, (Cmd)+Left/Right to extend end of slur - how it works in MU3)

I will leave a comment in #8908 to show you all my findings soon
