### ISSUE TITLE
[MU4 Issue] Using specific template via New Score Wizard leads to crash

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8105]
**Describe the bug**
Using the “Liturgical Unmetrical” template (“Choral” category) via New Score Wizard leads to crash

**To Reproduce**
1. Open New Score Wizard dialog
2. Open "Choose from template" tab
3. Add the “Liturgical Unmetrical” template (“Choral” category).
4. Click "Done" button

**Desktop (please complete the following information):**
MacOS

**Additional context**
Additional info from a developer:
"When debugging in Xcode, it says EXC_BAD_ACCESS (code=1, address=0xfe000000a5) in element.cpp, line 363.
There is a class ScoreElement, which is the abstract base of all elements. Then there is a subclass Element, of which other elements are subclasses. The Element class has properties like the z index (in the code `_z`). The `ScoreElement` does not have these. Maybe  a ScoreElement is casted to an Element, and in that case the _z property is undefined (there is no memory reserved for it)."

**Comment by njvdberg** [comment]
Not reproducible with current (`master`)[https://github.com/musescore/MuseScore/commit/33b11e01558fea81d76289d164e28849038d7571] on Linux.

What version of MuseScore is used for reporting this issue? (@vshalkevich )

**Comment by cbjeukendrup** [comment]
I can reproduce it in the latest master on macOS.

**Comment by njvdberg** [comment]
So it seems to be platform dependent?
Or compiler options?

**Comment by cbjeukendrup** [comment]
On Windows, it does not crash, so it seems to be macOS only. 
On macOS, it also happens when normally opening the file of the Unmetrical template. On Windows, it doesn't. MuseScore 3 opens this file perfectly fine on both OSs.

So it's the combination of macOS + MU4 + Liturgical_Unmetrical.mscx that causes a crash. 

Also remarkable: on macOS, the templates appear in a totally different order than on Windows. 
On Windows, they appear sorted by the filename (which starts with a number to indicate the order).
On macOS, they appear in a seemingly random order (but the order seems to be the same every time you run it). 
The behaviour on Windows seems correct to me, and is also the same as in MuseScore 3. So something is wrong on macOS. 

Another issue: on both platforms, there is a category called "templates", which should not appear in the dialog. It seems to represent the "superfolder" that contains the other templates folders.

**Comment by njvdberg** [comment]
> On macOS, they appear in a seemingly random order
On Unix systems (like Linux and MacOS), the "default" ordering is on inodes, resulting a more or less random or (but just try `ls -if1` on a template directory, my best guess this is the same order as you see the templates in MuseScore. In that case the cause is in how we collect the files from the underlying systems (Qt??).

> on both platforms, there is a category called "templates"
Also on Linux.
