### ISSUE TITLE
[MU4 Issue] Tabbing outline stroke needs to sit on the outside of each element (currently it is inside)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8442]
I've created this visual to help explain the idea:

![image](https://user-images.githubusercontent.com/21022311/123637000-64ae7600-d815-11eb-9d22-9c99aca2bc0c.png)

The stroke for tabbing needs to sit on the outside of interface elements so that it does not clash with the strokes in High Contrast mode.

This was in the initial design document but seems to have been overlooked.

**Comment by cbjeukendrup** [comment]
I discussed this some days ago with @ArjunBoi. I believe he is willing to do this in his accessibility PR (or maybe also just in a separate PR). 

So Arjun, would it be okay if you were assigned for this issue?

**Comment by ArjunBoi** [comment]
Sure!
I will take up this issue 😄 
The current implementation has us choose between which border to display in a lot of elements `border.color : keyNavCtrl.active ? ui.theme.focusColor : ui.theme.borderColor`, with the same logic for the border's Width.

I believe the solution for this would be to have another Rectangle element (The size of this new element would be the same as the background Rectangle element + 2px + ui.theme.borderWidth) and have that as a dedicated Navigation Control border rectangle. The width of the border would be 2px, and the existing background Rectangle would hold the "normal" use case's borders. 
These are just my initial ideas of course 😅

**Comment by shoogle** [comment]
@ArjunBoi, I suggest you implement it however you think it best and then ask for a review.

If it is going to take a lot of work to get it right everywhere then I suggest you just do it in one place to start with, get your method confirmed in a review, then extend it to work the same way in other place.

**Comment by ArjunBoi** [comment]
@shoogle, @Tantacrul, @cbjeukendrup 

I've got the navCtrl borders working (the idea is working, and i have implemented it for FlatButtons only as of yet so that i can get it approved first before making large scale changes) 

The navCtrl borders, in decreasing order of visibility are:

* Light Theme [very good visibility]
* Dark Theme [moderate visibility]
* High Contrast White Theme [not that great visibility, since we already have black borders]
* High Contrast Black Theme [near invisible, unless you're REALLY looking out for it]

The color being used for these borders is `#75507b`, which isn't that great for darker themes. 
I think increasing the size of the navCtrl borders from 2px may not improve visibility at all, so we could try switching up the border color for different themes instead?

**Demonstration:**
Pay attention to the following buttons:
* "File", "Edit", "View" ... etc. buttons at the top 
* The note-entry/modification/playback buttons. 
* The "Add Palette" and Magnifying glass buttons on top of the default palette elements.

The navCtrl borders are drawn outside the main button now as per the design.


https://user-images.githubusercontent.com/72261568/126872264-70141d7e-68df-49f5-9897-8245ff110302.mp4

**Comment by cbjeukendrup** [comment]
Great job, that looks very good!
One minor thing: I think you need to adjust the corner radius of the focus border, to make sure that there is no gap in the corner, like this:
<img width="2033" alt="Schermafbeelding 2021-07-24 om 17 23 17" src="https://user-images.githubusercontent.com/48658420/126873104-467992c5-c2d7-4db8-aebd-ce95dcb1256b.png">

**Comment by ArjunBoi** [comment]
I was literally trying to figure out the math behind how to get the border radii to line up before you commented this...
Thanks for the rescue! 😄

**Comment by Tantacrul** [comment]
I would set the border to the accent colour for now. Or the main font
colour.
