### ISSUE TITLE
[MU4 Issue] Shortcut sequences don't work

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8517]
**Describe the bug**
The default shortcut sequence for adding ottava symbols (Ctrl+Y,Ctrl+O,Ctrl+A/B) doesn't work, and in general sequences that rely on holding down a modifier key and typing a sequence of keys don't seem to work in MU4, instead triggering other actions along the way.

**To Reproduce**
1. Create/open a score, select a note/rest
2. Hold down Control and type Y O A
3. The file|open dialog opens!

**Expected behavior**
Ottava above symbol should be added

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - 
**Additional context**

Actually for me it doesn't work properly in MU3 either, because Ctrl+Y is already mapped to Redo, so if Redo is enabled, it binds to the Ctrl+Y shortcut and typing O then A/B afterwards trigger other actions.  But in MU4 it never works, even if you ensure there are no duplicate mappings.  I would think as part of fixing this we should reconsider the 4 default sequences that start with Ctrl+Y - maybe use Alt+Y instead, as Alt+Y doesn't seem to be mapped to anything?

Also I noticed in the Shortcuts dialog that many existing shortcuts are shown as sequences (separated with ",") but I'm pretty sure they're actually alternative shortcuts, which in MU3 are shown separated with ";".  Not that I'd argue that such as a system is ideal but at least you can distinguish the two cases.

**Comment by Tantacrul** [comment]
I'm closing this in favour of a comprehensive issue to address the full problem with the shortcuts panel, which is riddled with bugs.

**Comment by wizofaus** [comment]
But this isn't a problem with the shortcuts panel?  The specific issue listed above (holding down CTRL and typing Y O A) is still occurring, and I don't think we should just sweep it under the carpet, as similar problems apply to other sequences.

**Comment by Tantacrul** [comment]
It's mainly a problem of resource allocation. Shortcuts are still not in a great place and the system we (tried) to port over is really unintuitive and riddled with issues. It makes sense to get the typical functionality of shortcuts working, remove the ability to assign multiple shortcuts to the same action. Once that's in place, we'll find time to address sequences for a later release.

In essence, we don't want to be stuck with something that doesn't work well and that is very hard to learn. We'd prefer to outright replace it with something that works well and is intuitive.

With 4.0, we'll have to accept that a few things won't make it, since the system is very different.

**Comment by Tantacrul** [comment]
However, I do agree that this issue should be reopened after 4.0 is released. I seem to have not tagged this one as 4.x. 

I've now done so.
