### ISSUE TITLE
[MU4 Issue] Can`t hide voices via Parts dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8568]
**Describe the bug**
Can`t hide voices via Parts dialog
Voice 1 still visible after untick it in Parts dialog

**To Reproduce**
1. Create a score
2. Add notes to the score (in voice 1)
3. Open Parts dialog
4. Expand "Visible voices" dropdown
5. Untick Voice 1

**Expected behavior**
Voice should be hidden

**Screenshots**
![2021-07-07 10_42_59-Window](https://user-images.githubusercontent.com/71372310/124884341-d9826c80-dfda-11eb-959a-1e1698a52b48.jpg)

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
Actually this is crashing for me, NotationParts::score() is running NULL

**Comment by wizofaus** [comment]
Tried fixing this but it's not obvious what the intention was, basically the parts aren't "properly" created until you close the dialog, before that they're in a disconnected state (they have no reference to current Score).  It would require a few changes to ensure the ExcerptNotation is created with a pointer to the current Score so that setting the voice will work before the part/excerpt is fully created.

**Comment by njvdberg** [comment]
In the last spec (Instruments_2020_V07_Second_Amendment_V01, page 3) , voices will be removed from the parts dialog.

@wizofaus This will be part of my PR, implementing this new spec.

**Comment by wizofaus** [comment]
Thanks! Where can I can see that design document?

**Comment by Eism** [comment]
removed voices from dialog in https://github.com/musescore/MuseScore/pull/8751
