### ISSUE TITLE
Lines not resizing correctly

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8694]
Line items from the palette can't be lengthened or shortened in the score/project editor.

This seems to be affecting ALL line objects (e.g. slurs, hairpins, crescendo lines, pedal lines, etc.... albeit with **some** inconsistency, as you will see in this demo video):
 
https://user-images.githubusercontent.com/86290556/126642964-de6b6bb1-79ae-4bd0-8aee-fabe50db18bf.mp4

**Expected behaviour**
User should be able to lengthen/shorten all line objects by adjusting left and right handles. 
Line objects should also snap to notes.
See for example: 
https://user-images.githubusercontent.com/86290556/126642985-aa6e2405-2620-4c8c-b741-184b400a2197.mov

Apple MacBook Air M1 MacOS 11.4
Reproduced in Windows 10 ARM (via Parallels)

**Comment by Jojo-Schmitz** [comment]
Maybe #8510 is the culprit?

**Comment by Jojo-Schmitz** [comment]
Hmm, maybe not. But it was the last change dealing with lines (AKA spanners), as far as I can tell.
Anyway: I can confirm the issue. It always behaves as if the middle handle were user, i.e. it moves about the entire line rather than making it longer or shorter

**Comment by wizofaus** [comment]
The changes in there shouldn't affect the dragging of grip handles - I'd think that it's more likely to be due to the recent changes to control how the context menu worked (as it involved mouse events), though it's not clear why that would cause this problem. It may just have been there a while, though I had done a fair bit of testing of this to fix an issue where dragging grips around caused the app to crash or the layout to change erratically (the fix for which had nothing to do with the actual grip dragging code).

**Comment by cbjeukendrup** [comment]
Seems to affect all elements with grips, also slurs, brackets, frames...

**Comment by wizofaus** [comment]
The hit-test code for grips is not working currently, investigating.

**Comment by wizofaus** [comment]
Needs to be re-opened, I didn't fix this properly at all, it's only working for elements on the first page!
