### ISSUE TITLE
[MU4 Issue] Tech-debt: Ms::Score class needs rationalisation

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8777]
The Ms::Score class is something of a overgrown beast with far more public functions than is really needed (over 500 - just the 
class declaration is 900 lines of code), and many (most?) of which don't need privileged access to the class at all, so would be better done as helper functions (pity C++ doesn't support extension functions!). At least a few functions appear to be completely unused (e.g. forAllLyrics(), overloads of spell()), or only referenced by unit tests.
The naming conventions and layout of the function declarations in the header file could also use some work, e.g. why do some commands start with "cmd", some with "undo" and others with no prefix.

I have started on some basic tidy up but not sure if this is better left until later in the piece...

**Comment by igorkorsukov** [comment]
I believe that all this needs to be corrected step by step and within the work of solving other problems. that is, I don’t think it makes sense to make a lot of changes now. It is better to take some part of the functionality and put it in order, at the same time cleaning the Ms::Score. For example, take work with lyrics and see what can be improved, how to put work with lyrics in order.
And so, piece by piece, everything will be fixed.
Otherwise, it is possible that the massive work will be done empty because the code after it will be changed anyway.
Also, in any case, it is better to do it in small pieces to track changes.

**Comment by wizofaus** [comment]
Sure, though it'd be good to have some sort of picture of what the score class should be responsible for.  E.g. I didn't really think the "changeEnharmonicSpelling" function I added recently did ideally belong in it, given it doesn't require any privileged access, but it seemed to have it in a different location to functions like spell( ) or transpose( ) etc. wasn't ideal either.
At any rate at this stage I'm just going through the existing functions and working out what truly needs to be public etc.

**Comment by Tantacrul** [comment]
@igorkorsukov - shall I close this issue? I'm not sure it can be actioned.

**Comment by igorkorsukov** [comment]
> @igorkorsukov - shall I close this issue? I'm not sure it can be actioned.

@Tantacrul  Yes, it can be closed
