### ISSUE TITLE
[MU4 Issue]  Remaining paste issues

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8860]
While the most obvious issues were addressed, just leaving this here so we don't lose track of what still doesn't quite work as expected when copying/pasting notes. I'd say most of these are pretty minor issues though.

a) articulations/ornaments lost while copying/pasting notes/rests
b) Pasting a single rest on to a note/rest does nothing
c) pasting a single note/rest onto a selected range does nothing
d) pasting a list-selection of notes/rests on to anything does nothing
e) pasting a range selection onto a list of notes/rests does nothing (MU3 shows error "no destination to paste")
f) there's no way to copy *just* a single chord to the clipboard (only as part of a range, which means you get all elements in the same time frame)
g) pasting a single note of one pitch on to an individually selected note of a different pitch in a chord  when the chord already has two notes in the copied-from pitch produces a chord with 3+ notes of the same pitch, even though only 2 can be seen, but note this is already possible to achieve in other ways
h) stem length, stem direction and "cue size" properties are not preserved when copying notes (as they're properties of the containing chord, but so is duration!)
i) tuplets: only the note-head duration is preserved, regardless of what sort of tuplet it was originally part of, or pasted on to. Which is possibly not always what would be expected.
j) pasting a note too long to fit on the score (e.g. pasting a whole note into a final 2/4 measure), currently the note is truncated, just as it is when adding from the note entry toolbar. But I would expect the score to be extended, as per what happens when pasting a single note selected as a range. 
k) pasting, e.g., a whole note onto a half note that's followed by a half-note tied to a subsequent note. Currently this just replaces the first two half notes, breaking the tie and leaving the subsequent note in place. But this is a bit inconsistent with what happens if pasting onto notes of the same effective durations but that don't need a tie (due to the time signature etc.), where the entire second note is replaced, and the gap padded out with rests as necessary. But tied notes aren't exactly equivalent to notes of the same effective duration notated without ties - for a start, you can paste onto the 2nd of a pair of tied notes (which again requires breaking the tie), but you can't paste "half way" through a single note.

**Comment by Tantacrul** [comment]
Christ what an enormous issue. OK...

A) Behaviour is now the same as MS3. Needs improvement but not for 4.0
B) Now the same as MS3. Improve in later releases
C) Now the same as MS3. Improve in later releases
D) Agree but it is the same as MS3, so good for 4.0
E) Agree but it is the same as MS3, so good for 4.0
F) Can't replicate
G) Don't understand despite my best efforts. Perhaps a separate issue if still valid
H) Same as MS3. Fix later
i) I'm beginning now to realise that these aren't bugs in 4... but 'nice to haves' that we've never supported. Wish I'd realised this before spending time testing. Hey only 2 left.
j) Ditto. Same in 3 & 4
k) Ditto. Same in 3 & 4

-- 

OK, I've moved all these to a feature list of improvements that we keep internally. I'm closing for now because I want to spare our testers and devs the time needed to read this and comprehend it.

Thanks!
