### ISSUE TITLE
[MU4 Issue] Pencil doesn`t selected when note selected

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9002]
**Describe the bug**
Pencil doesn't selected when note selected

**To Reproduce**
1. Create a score
2. Click on any note

**Expected behavior**
Pencil should be automatically selected after clicking on a note

**Screenshots**
![2021-09-02 00_27_32-Window](https://user-images.githubusercontent.com/71372310/131752092-351b4151-84ff-492e-9adc-6aa376de9012.jpg)

**Desktop (please complete the following information):**
Windows 10

**Comment by cbjeukendrup** [comment]
I think this is expected behaviour. When creating or opening a score, the first measure rest becomes selected. When you click a note duration while something is selected, that duration is applied to the selected element, instead of toggling note input. When you click a note duration while nothing is selected, note input mode is toggled as expected. 

Maybe we should not select the first rest when creating a new score, to avoid this behaviour (it sometimes annoys me too).

**Comment by wizofaus** [comment]
Yeah, the actions for most icons in the notation input toolbar work differently depending on what's selected. Only if nothing's currently selected do they automatically activate note input mode.
