### ISSUE TITLE
[Inspector] "Force Horizontal" and "Beam height" not working / reflecting beam height

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9037]
**Describe the bug**
Force horizontal and beam height text fields not working in the inspector.

https://user-images.githubusercontent.com/21022311/167021190-d23e51fc-02c6-442c-b039-d74f76ee07dc.mov

**Comment by wizofaus** [comment]
Pretty sure this is actually at least partly my fault, I'd changed the internal representation of 'beamPos' to `QPair<float,float>` but missed a couple of spots where it's still using PointF.

**Comment by Tantacrul** [comment]
@oktophonie - I've assigned this to you for now and given it a provisional P2. Feel free to reassign, reprioritise or close as needed.

**Comment by Tantacrul** [comment]
Uploading 01_Beam_Height_Settings_Not_Working_in_Inspector.mov…

Also adding this here, since I'd imagine beam height parameters and 'force horizontal' functionality in the inspector should be fixed together.

For example, if changing force horizontal, it will affect the values in the text fields here. Elevating to P0 because this is non-functional.

**Comment by wizofaus** [comment]
My comment explained what I'd found while trying to investigate why this wasn't working, which is likely to be useful to whatever developer takes this on, so I'm not sure why it got deleted?
