### ISSUE TITLE
[MU4 Issue] Note entry position is always start of the score if no selection

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9061]
**Describe the bug**
While the v3 behaviour is quite hard to defend (it's literally too complex to ever be predictable), the v4 behaviour of always jumping back to the very first note of the top staff when starting note-entry mode when there's no selection is something of a regression.

**To Reproduce**
1. Create a new empty score, enter a few measures' worth of notes, then hit Esc twice (one to exit note entry mode, another to clear the selection)
2. Pan to the end of the score
3. Hit a key from A-G
4. The first note at the very beginning (that you entered before) gets replaced and scrolls back into view

**Expected behavior**
Debatable!  I'd be fine with the default note entry and playback position *always* just being whatever element was last selected, even if there was no current selection, but I do think it would be better if there were some marker indicating where that was exactly.  And certainly if you click on a measure to select a range, then deselect it, I'd expect the playback position to move to that point (currently in v3 it only does this if you select an individual note or rest, and even then, only if that note/rest is within the current viewport. If not, v3 has some exceedingly complex logic to pick a spot to begin note entry, that I don't think any user would ever be able to figure out)

BTW I can't exactly work out when it jumps to the top staff vs when it just uses the staff you last had a selection on (even after looking at the code). 9 times out of 10 it uses the top staff, but e.g. if I select an empty measure in another staff then hit a key 1-9 to change the rest duration, it does so, clearing the selection in the process, but hitting A-G takes you back to the very first note (at the beginning of the piece) in that same staff.  For whatever reason it seems this particular operation (and maybe some others?) is one that clears the selection *without* resetting the internal input state current track variable, but normally it gets reset to 0.

@Tantacrul @bkunda 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Tantacrul** [comment]
@wizofaus - it seems that this has improved at some point, so that the cursor now jumps to the last measure / instrument a user placed a note in.

**Comment by MarcSabatella** [comment]
FWIW, MU3 *also* would jump to the last note input position, but only if that position was currently visible.  Otherwise, it would go to the topmost/leftmost of the currently-visible measures.  This was requested by numerous users and was the consensus favorite in discussions on the forums etc.  Could that optimization be added back?  People did not like it at all when note input suddenly jumped to a place not visible, and were very happy when we implemented that improvement.

**Comment by Tantacrul** [comment]
Yep - that makes sense. Could you create a new issue for it?

**Comment by MarcSabatella** [comment]
Done, see https://github.com/musescore/MuseScore/issues/11494

**Comment by wizofaus** [comment]
But that's about playback position, not note entry position? As far as your "Otherwise, it would go to the topmost/leftmost of the currently-visible measures" description goes, it's the logic that I believe is attempting to do something like that I was referring to above as being something so complex that I don't believe any user could reasonably predict what the behaviour would be.

@MarcSabatella

**Comment by Tantacrul** [comment]
@wizofaus - I also share the concern that the 'choose the top-left' stave is over design and may cause more confusion than it is worth. However, I can also very much appreciate that if a user is tidying up a finished score - going from page to page to add things here and there - it would be maddening if the view kept lurching back to the last place you worked.

Perhaps the answer is not more rules but less. For example, I notice that both Sibelius and Dorico **don't** move the view to focus on the note entry cursor, although the **do** choose place it where you were last working. In this way, you can simply edit where you were intending to edit anyway.

**Comment by wizofaus** [comment]
I would think automatically scrolling the view to ensure any edits you have just made are visible is pretty standard, certainly word processing/spreadsheet software etc. do this - even your web browser! (scroll the text box you're typing in out of view, then type some more...it scrolls back into view).
BTW I just tried it out with the current version and I think the behaviour is pretty good - after panning to the end of the score, the next note got added after the ones I'd previously added, and scrolled back into view.  V3's behaviour really is very odd in comparison - it *might* make sense for starting playback, but not for note insertion.
As I noted, for me the main improvement now would be ensuring that the insertion/edit cursor location was always visible somehow, which would bring MuseScore more in line with text editing software (not always a good parallel, but probably the closest we'll ever get!).

**Comment by MarcSabatella** [comment]
As far as I know, everything I've said is about note input position.  Playback position is of course totally separate - normally it simply continues where it left off, unless you've changed selection.

As for choosing the top left, it could also be center of screen, or whatever is closest to mouse cursor.  And yes, it's unlikely any of these will happen to be the exact spot the user wants.  But that's not the point.  it's not about MuseScore predicting the user's wishes perfectly, nor is it about the user predicting MuseScore's behavior perfectly.  it's about not *punishing* the user for forgetting to select something first before entering note input mode.  If the user makes that mistake - and we've all done it - we don't want to rub it in their face by banishing them to some far away unrelated part of the score with no way to get back.

So, this isn't about predicting the One True Location where the user wants note input.  It's simply about not stopping their workflow dead in its tracks - instead, giving them an opportunity to realize they still need to get to the right spot.  We used to get loud complaints about this sort of "score jumping" from very many frustrated users, including a number of long time supporters.  We've worked hard over the years to address as many of these cases as possible.

Anyhow, I agree there are multiple solutions and I'm certainly not married to the specific one that users agreed upon a couple of years ago as the best consensus for MU3.  But I'd also not like to see us simply throw away all the user input we've had on this and the compromise developed and agreed upon by the community unless we are sure we are having something better.

The good news here is, whatever solution we adopt now, it's harmless to change later based on user feedback.

**Comment by MarcSabatella** [comment]
...and now I see why there was confusion about playback, somehow I wrote up the issue title and initial description wrong.  I really meant note input all along.  Fixed.

**Comment by MarcSabatella** [comment]
My web browser doensn't have note input mode, so I'm not sure how it compares?

To be clear, here's the use case that generates the problem:

Imagine you have a score, and it's basically completed.  You now decide you want to go through and fix a few spots - the flute in one section of the piece, the timpani in another section later, the viola in another section, etc.  So, you scroll around to find the place to fix the flute part and make that change.  Now you scroll around to find the section with the timpani part you want to change.  It takes a while because all timpani parts kind of look alike, but finally, you find it.  So now you go to enter note input mode, but you make the fatal mistake of forgetting to *select* the measure first.  So even though you successfully found the right spot and it's right there on the screen and you're looking directly at it when you press "N", suddenly it vanishes before your eyes and you're teleported back to the flute part and now you start to start your hunt over again.  Sorry to be so dramatic, but it's important to realize what an *enormous* source of frustration this sort of jumping about really is in the real life.,

There is nothing I can think of that is remotely like this in a web browser, or a word processor, because they don't have note input mode - nothing that you can do that suddenly triggers this bizarre unexpected jumping.  If other programs punish you in this way for making the mistake of forgetting to select a measure before entering note input mode, that's their problem, but here's our opportunity to continue to do better.

**Comment by wizofaus** [comment]
A web browser *does* have data entry mode though, I'm using right now as I type this message.  If I scroll up and down such that this moves off-screen, then resuming typing, it comes back into view and the next characters I type are added after the ones I'd previously typed.
I don't see note input in a score being any different - if I type A B C, those 3 notes appear. If I scroll elsewhere, then type D, D is added after A B C and scrolled back into view.
If do the same but happen to deliberately exit note entry mode after typing A B C, more or less the same occurs, except the D replaces the C (which is still selected).
If do the same but not only deliberately exit note entry mode AND explicitly deselect the C, then scroll elsewhere then hit "D", it behaves the same as the previous scenario (i.e. internally the C is still somehow selected, even if not visibly so).  That seems pretty reasonable to me.

I particularly don't know or care what happens if I hit "N", there's no need to ever do so as far as I can see.

The idea that someone might just happen to scroll a particular measure into view but not click on the score at all to ensure it is the "active" input location, then hit a key (A-G) and expect the newly entered note to appear in that measure is very odd to me and I can't think of any parallel in other software.  But worse, in v3, often you simply can't predict which measure it might actually pick, it certainly isn't always the topmost/leftmost visible measure.

**Comment by MarcSabatella** [comment]
I think if you're not pressing "N" you're already unlike the majority of users.  So that alone suggests a disconnect between how you are seeing this scenario going down versus how it would actually go down for other users.  consider the possibility that other users might have a different workflow than you, and take another look at this from from the beginning, going through my scenario but assuming the user does what we normally advise - pressing "N" to enter note input mode, pressing it or Esc to leave it, and then Esc again to clear the selection as a safety precaution against inadvertent changes to their score.

The user is now in a state that is unlike a word processor or web browser in actual practice.  They are *always* in "text input mode".  Whereas MuseScore is normally in, well, "normal mode".  And the change between the two modes is what makes this apples and oranges.

So to be clear: if you for whatever reason stay in note input mode after doing your edit, then scroll somewhere else and continue typing, then *of course* note input should continue where you left off, because now you are constructing an artificial use case that *is* similar to word processors or web browsers.  But in the usual case - a user has left note input mode, cleared the selection, and now want to re-enter note input mode somewhere else - it's quite relevant to look at what happens if they make the mistake of forgetting to select something first.  This happens often enough in real world usage to be a concern to real users.  If it weren't they wouldn't have asked for the change, and we wouldn't have listened if they had.

And again, the actual visible measure that ends up being chosen is immaterial, and no one is suggesting the user should be able to predict the exact spot where note input occurs.  That's not important at all for us to succeed.  All that matters is that score should not jump to some random unrelated place.  As far I'm concerned, we could simply put up a dialog that says, "sorry, you need to select a measure first" (not that I'm advocating that).  As long as the score doesn't jump to some random unrelated place.  It's not that much to ask, and that's why when people asked for it, we did it.

But for the record, the measure chosen *is* always the topmost leftmost measure as far as I know, for a suitable definition of "topmost" and "leftmost" once one considered the possibility of a measure or staff being only partially visible.  Not that it matters in the slightest.  As ling as it doesn't jump the score somewhere else, it's a win.

**Comment by wizofaus** [comment]
I wouldn't suggest Web browsers are normally in "input mode".  If I type in here, then press TAB, I'm no longer entering text (no text field is active).  If I then press shift-TAB, it "reactivates" input mode, and text entry resumes at the exact position in that field I was previously.

Pressing 'N' used to be required in MS3, it no longer is in MS4, and there's really no good reason to use it that I can see.

"no one is suggesting the user should be able to predict the exact spot where note input occurs"

Personally I would suggest exactly that, or it's all but useless.  Unless you're deliberately writing aleatoric music of course, but surely there are better tools for that.

I just experimented with v3 a bit, and there were definitely several times when the measure it chose was *not* the topmost/leftmost visible one, and from looking at the code, it's not surprising that this would occur.  It's not even hard to have it so that after locating a particular measure you're interested in, then pressing N, it scrolls the view so that that measure is no longer visible, and it seemingly picks some random measure that happened to be partly visible.  Indeed in all cases where a number of measures are partly visible, it's especially unpredictable as to which one it will choose (remembering that you have to keep on "resetting" so that the last note entry mode location you used is no longer visible).  I honestly cannot imagine trying to defend the current v3 behaviour even if I was paid to!

**Comment by wizofaus** [comment]
(btw this discussion should surely be in the newly opened ticket rather than this closed one! I had copied my comment to that ticket and meant to delete the one here but you beat me to it replying...)

**Comment by MarcSabatella** [comment]
(agreed regarding moving the discussion)

**Comment by Tantacrul** [comment]
Although let's not massively complicate the new issue with too much inconclusive conversation. I'm trying to clear out the cognitive load on each issue so the developer in question has a clear idea of what to do. In that other issue, it seems pretty clear what the next steps are.

I would also mention that my move to simplify issues is really a measure to help us get to alpha 2 / beta 1 more quickly. Later, I think it's fine if things get looser and more inconclusive again :)
