### ISSUE TITLE
[MU4 Issue] mscz score file saved in v3 is loaded using "Emmentaler" font 

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9070]
**Describe the bug**
Scores created in v3.6 are loaded in v4.0 with the wrong musical symbols/text font ("Emmentaler").

**To Reproduce**
1. Create a score in v3.6 (can be empty) and save it
2. Open it in v4
3. Go to Format|Style|Score and observe that Musical Symbols font is Emmentaler (even though it was Leland in 3.6)

**Expected behavior**
Font should remain as Leland.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by oktophonie** [comment]
Just to add that this problem is concealed if the 'use Leland' box is ticked, but that shouldn't be necessary in this case (similarly for Emmentaler). To be addressed as part of #10120

**Comment by oktophonie** [comment]
In fact, this problem appears to be more general: it looks like the style defaults (for a 3.6 file) are being overwritten by the style sheet from a previous version (3.5, perhaps?), some obvious indicators of which are the page numbers appearing at the bottom of the page rather than at the top, etc. Ticking the 'use Leland'/'use Edwin' buttons muddy the water as they will reapply the music and text font settings, but other unrelated settings will still change unexpectedly.
