### ISSUE TITLE
[MU4 Issue] "Save As..." dialog missing file type selector

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9132]
In MuseScore 3.6, the "Save As..." dialog contains this dropdown, allowing users to select their file save format from between uncompressed .mscx  or the regular .mscz.
<img width="799" alt="Screenshot 2021-09-15 at 20 50 42" src="https://user-images.githubusercontent.com/86290556/133420655-0bf714cb-c126-490d-a496-942a5354ceae.png">

In the MacOS nightly, this dropdown selector is not visible.
In the Windows nightly, this dropdown only shows the option for .mscz

**Expected behavior**
.mscx should be available as an option in the dropdown selectors

Macbook Air M1, MacOS 11.5.2
Windows 10

**Comment by wizofaus** [comment]
My understanding is that this is by design - I believe the intention to support saving as uncompressed files into a directory. .mscx files aren't guaranteed to hold all necessary information on their own, though they are very useful for troubleshooting and development purposes (e.g. for creating unit test reference files).  It's arguably not a huge loss of functionality as you can always unzip .mscz files yourself after saving, but that can be a bit annoying when you're used to just being able to save them directly in v3.

**Comment by riaanvn** [comment]
Checking with a 2022-01-10 nightly on macOS 12.1 show be both the mscz and mscz file options (e.g. identical to the v3 options: 
<img alt="v4 save as" src="https://user-images.githubusercontent.com/4170969/149002345-8d3c182c-4fc3-4c6e-8b0f-1ad0ba9e8ad1.png">

Side note: this string still needs to be updated to reflect the new version; still referencing version 4.
