### ISSUE TITLE
[MU4 Issue] tools->Unroll repeats doesn`t work 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9141]
**Describe the bug**
tools->Unroll repeats doesn`t work 
It should work the same as in MU3 

**To Reproduce**
1. Create a score
2. Use Unroll repeats (tools->Unroll repeats)

**Expected behavior**
File created with title "_unrolled"

**Screenshots**
This is how it looks in MU3
<img width="727" alt="Screenshot 2021-09-14 at 17 49 22" src="https://user-images.githubusercontent.com/71372310/133514349-86df3597-be23-48da-9259-b6a0c60a8e0e.png">

**Desktop (please complete the following information):**
Windows 10
MacOS

**Comment by wizofaus** [comment]
Yep, I looked into this extensively (and mentioned elsewhere), it's a strange command.  We can't do it the same way for v4, as v4 doesn't allow opening new unrelated score in the same top-level window, so it would require opening a whole new top level window.
Or better...unroll repeats should just modify the current score (and be undoable).  Unfortunately the way that's implemented isn't particularly straightforward (it specifically creates a whole new "score" object internally - in principle that new score object could then become the current score, but making undoable would be a challenge as it would also replace the undo stack!).
I'm assuming @Tantacrul that would be the ideal result from a UI/UX perspective though, rather than starting up a whole new top level instance of MuseScore just for the "unrolled" version?
Actually ideally I'd expect to be able unroll repeats just for whatever range is currently selected, rather than only the whole score.

**Comment by Tantacrul** [comment]
Yeah. I would expect the same. For now, I would suggest that unroll repeats simply affects the original score (does not create a new one) and also marks it dirty. We'd need to build any of the other capability, which would just add more time to MS4 (for probably minimal benefit).

**Comment by wizofaus** [comment]
Ok but that's going to require a substantial rewrite of the existing unroll repeat logic, which isn't entirely trivial. But I was planning to take it on along with all the other actions I've hooked up so far...

**Comment by wizofaus** [comment]
Actually it might not be too bad, basically it just needs to be changed to clone the original score, then delete everything in the current score and unroll the repeats from the clone into the current score.  Preserving the undo stack might be the main challenge but should be OK.

**Comment by wizofaus** [comment]
Turns out this is rather more difficult than I'd hoped, especially with part excerpts.  I do have it working so you can undo & redo fine, but after unrolling the parts are no longer properly linked to the main score (so modifying one doesn't update the other).
In v3 it actually destroys all the parts and re-creates them after unrolling, so they're linked fine, but you've lost any adjustments you made to them, which seems worse than leaving them unlinked!
Also getting it to work for just selected measures may be a bit ambitious, it'll probably be whole-score-only for day 1.

**Comment by wizofaus** [comment]
Ok it took a significant rewrite of the existing logic but I think I finally have it working so that:
a) unroll repeats works as expected if there are multiple parts (notes remain linked between master score and parts)
b) undo & redo work as expected, including the following sequence:
    1) unroll repeats
    2) modify some notes
    3) undo all the way back to before "unroll repeats"
    4) redo all the way back to the end of the stack, all modifications should be replayed as expected

Still a few edge cases to double check but it's looking promising.

**Comment by Tantacrul** [comment]
#godswork

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/9670
