### ISSUE TITLE
[VST - MIXER] VST Windows should be prevented from 'going behind' the main window

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9157]
**Describe the bug**
In many other DAW's, VST windows are forced to front of the main interface. If this isn't done, then they very easily get lost and it is quite painful for the user to relocate them.

**Expected behaviour**
All VST windows stay 'in front' of the main MS4 window.

**Comment by DmitryArefiev** [comment]
Hi @Tantacrul , 
we talked with @vpereverzev and @RomanPudashkin about this.. and turned out it's hard to implement this feature.

Also that behavior with locked VST window usually appears only in DAW and not in notation software (e.g. Sibelius)

>If this isn't done, then they very easily get lost and it is quite painful for the user to relocate them
Now Roman did a fix by using button on the mixer and user can easily return VST window in front just but clicking on VSTs name in mixer.

Another argument to use the mixer button only is that the VST plugin can have a wide window and overlap score view (please see my video from comment above with Vital plugin)

So, if the initial goal/behavior is important I can leave the bug in Open state

**Comment by Tantacrul** [comment]
Hmmm. It is quite a problem, I feel. I'm aware of how Sibelius performs here but it's quite bad. I've already had the experience of losing my VST windows a few times. I also don't think it matters that the windows are large and can overlap the score because that's just the nature of VST's. As you've said, most DAWs do it - and they do it for a reason.

How difficult are we talking? I'm reluctant for this issue not to get fixed.

**Comment by cbjeukendrup** [comment]
I've looked into this a little bit, and I'm really stunned how difficult this is, while it seems a quite straightforward and reasonable task.
 
With one extra line of code, you can make the window stay on top of the whole OS, but I expect that is not what we want, right?

Keeping a window in front of just the _application_ seems impossible using Qt; there is just no API for it. So to achieve this, we would need to use native, OS dependent APIs.

On macOS, it is relatively easily doable, once you've got hold of the underlying `NSWindow*`. A complication though, is that you need Objective-C++ to be able to work with macOS APIs, so we would need to add an extra Objective-C++ source file to get just this simple thing done. In that extra file should be something like:
```objective-c++
    NSView* nsView = (__bridge NSView*)reinterpret_cast<void*>(window->winId());
    NSWindow* nsWindow = [nsView window];
    if (nsWindow) {
        [nsWindow setLevel:NSFloatingWindowLevel];
    }
```

On Windows, it seems much less straight forward, but we would probably need this method: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos. On Windows, it can fortunately be just in C++. 

And of course, Linux is totally hopeless because every Linux is different.

**Comment by jessjwilliamson** [comment]
I was about to write an issue about this and found this one.. Yes, this is very problematic, and as been a producer myself it's a very uncomfortable experience, it will make users furious. This is also involving in multiple monitors. (Click here: https://github.com/musescore/MuseScore/issues/9723) VST windows should remain on top because users literally edit inside for mixing and other tools, until user closes it.
