### ISSUE TITLE
[MU4 Issue] File | Print command doesn't work

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9165]
**Describe the bug**
The File | Print command is always available but never appears to do anything.

**To Reproduce**
1. Immediately on opening application (before opening a score) note that File | Print is available but does nothing
2. Open/create a score - File | Print still does nothing

**Expected behavior**
Should be able to print score!

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Nightly build from https://github.com/musescore/MuseScore/actions/runs/1244135645

**Comment by igorkorsukov** [comment]
I think this is a task, not a issue
And I think it's worth removing the File-> Print menu item, because we have a Publish page

@bkunda What do you think?

**Comment by bkunda** [comment]
I think we definitely still need to have the File-->Print menu item because it is such a common one and people will be baffled if they find it gone. 
It should point to the same dialog that gets triggered when the user clicks "Print" from the **Publish** page. 
This is something I recall discussing with @Tantacrul some time ago, and I can't quite remember the resolution, although we definitely discussed designing a bespoke print dialog v. triggering the standard OS print dialog.
Given current project timelines, I suspect the latter might be preferred. @Tantacrul?

**Comment by Tantacrul** [comment]
For now, we should match what MuseScore 3 does. Bespoke print dialogs are not all that easy to make and test.

**Comment by Tantacrul** [comment]
Also, we should definitely keep File -> Print in the menu!

**Comment by bkunda** [comment]
@igorkorsukov do you still need this raised as a separate task? (I'm happy to raise it if so).
The File > Print command will be triggering the OS print dialog for now.

**Comment by igorkorsukov** [comment]
> @igorkorsukov do you still need this raised as a separate task? (I'm happy to raise it if so). The File > Print command will be triggering the OS print dialog for now.

Yes, please, task about print function in general

**Comment by igorkorsukov** [comment]
Will be implemented by this task https://github.com/musescore/MuseScore/issues/9858
