### ISSUE TITLE
[MU4 Issue] Score and DevTools protrude past the "title bar" slightly when not maximized

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#9177]
**Describe the bug**
TItle: Score and DevTools protrude past the "title bar" slightly when not maximized. 

**To Reproduce**
1. Run MS4
2. Make sure not maximized
3. Cycle through Home, Score, Publish, & DevTools
It seems going to Score and DevTools specifically leave extra flap (or in a sense it could be seen as if the title bar isn't big enough... not sure)

I include a sloppy screen-capture to demonstrate:

https://user-images.githubusercontent.com/7139517/133776933-548a8d74-2c34-447d-8bdb-44802807acba.mp4

**Desktop (please complete the following information):**
Linux + XFCE

**Comment by cbjeukendrup** [comment]
Seems a problem of the title bar that was fully implemented in QML. First, the title bar on Windows was also implemented fully in QML, and then this problem also occurred on Windows, but after that, the implementation of the title bar was changed (it now uses some native Windows things), and since then I've never seen this problem anymore. So, something similar would need to happen on Linux, but that's difficult because every Linux is different.

**Comment by worldwideweary** [comment]
Hrm. Wonder if there's an issue with MacOS...

Aside observation: a cross-platform music tracker named Renoise I think does a fairly decent job in having a custom title bar and windows buttons (dialogs within also are custom). They got it so that when maximized, the reference to itself and the current project no longer appears. Not to say that's worth emulating, just figured it's worth mentioning while I'm up here since it feels slightly on topic. A quick capture:

https://user-images.githubusercontent.com/7139517/133792339-9963c75a-fc84-4c2a-a1dc-1c78053f01d1.mp4

**Comment by cbjeukendrup** [comment]
On macOS, there is no issue, because it just uses a native Cocoa window (albeit via QML) with a native title bar. The only customization to the macOS title bar is that it has the same color as the MU4 window; this is done using native Cocoa APIs.

Would be nice to know how Renoise does it, but it seems it's not open source...

Anyway, there's a bunch of other [issues reported by Niek van den Berg](https://github.com/musescore/MuseScore/issues/created_by/njvdberg) related to the main window and its title bar on Linux.

**Comment by Eism** [comment]
Fixed
