### ISSUE TITLE
[MU4 Issue] Grip handles are too small in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9257]
Grip handles used to resize lines are appearing too small in MacOS.

Demo video: compares MU4 handle size with MU3 handle size. Desired behaviour: handles should appear as they do in MuseScore3. 

![grip-handles-too-small](https://user-images.githubusercontent.com/86290556/134617175-eaf5731c-5701-40d3-bed2-a523f67ec12b.gif)

MacBook Air M1, MacOS 11.6

**Comment by cbjeukendrup** [comment]
I think this is not related to macOS, but to high-dpi screens (because if you run the app in low dpi mode on macOS, the problem is solved).

Also, I doubt whether we should exactly follow the behaviour of MU3. In MU3, grip handles have a fixed size, regardless of the zoom level. That way, they look okay-ish with common zoom levels, but they are relatively too big at smaller zoom levels and invisibly small at higher zoom levels (because they don't stand out from the black lines).

In Dorico, the grips follow the zoom level, which looks and works a lot better in my opinion. We could also do that, and maybe set a minimum and maximum size, so that they don't get too small at smaller zoom levels or too big at higher zoom levels.

**Comment by DmitryArefiev** [comment]
Checked #9257 on Mac11 - FIXED
