### ISSUE TITLE
[MU4 Issue] Button UI accent colours in dark mode are incorrect

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9260]
In dark mode, hover state colour is currently 50% opacity and hit state is 100% opacity.

**Expected behaviour** 
Hover = 100% opacity
Hit = 50% opacity

<img width="850" alt="Screenshot 2021-09-24 at 3 55 13 pm" src="https://user-images.githubusercontent.com/86290556/134625286-3cfd7e06-6eb0-49b5-b1bf-2e9fd1a2efbe.png">

Macbook Air M1, MacOS 11.6
Windows 10

**Comment by jessjwilliamson** [comment]
@cbjeukendrup This could be a nice task for you :)

**Comment by cbjeukendrup** [comment]
Sure! 

https://user-images.githubusercontent.com/48658420/134673226-d662edb1-e6e9-44f8-8f5b-c3e6faaad63b.mov

I will create a PR with this fix soon. (Note: the fix will likely only work after "Reset Preferences".

Question: in some places in the app, different values for the opacity are used when dealing with the accent color instead of the button color. In fact, only in the following places:
- FlatToggleButton which is selected (can be found in DevTools > UI Gallery)
- Inspector > Notehead > notehead group
- Inspector > Beam > Beam type
- Text field selection color and number input field color (see for example the time input field in the playback toolbar)
- Selected dropdown items
- Selected items in some lists, like the instruments panel

Shouldn't we unify this, and just use the normal opacity values in all places?

**Comment by bkunda** [comment]
Thanks @cbjeukendrup! Always so good to have you put your hand up for this stuff 😌

I'm not quite sure about the design concept for those properties buttons etc. This is a question for @jessjwilliamson.

Having a unified approach seems to make sense to me in theory, but I'd want to be sure that we get the right results across the entire UI. 

Over to you @jessjwilliamson!

**Comment by jessjwilliamson** [comment]
> Sure!
> 
>  Schermopname.2021-09-24.om.14.20.16.mov 
> I will create a PR with this fix soon. (Note: the fix will likely only work after "Reset Preferences".
> 
> Question: in some places in the app, different values for the opacity are used when dealing with the accent color instead of the button color. In fact, only in the following places:
> 
> * FlatToggleButton which is selected (can be found in DevTools > UI Gallery)
> * Inspector > Notehead > notehead group
> * Inspector > Beam > Beam type
> * Text field selection color and number input field color (see for example the time input field in the playback toolbar)
> * Selected dropdown items
> * Selected items in some lists, like the instruments panel
> 
> Shouldn't we unify this, and just use the normal opacity values in all places?

Ohhh yes, it seems we need to revise and clean up some states! :) Let's discuss and make some fixes!
