### ISSUE TITLE
[MU4 Issue] Sharps are not laid out correctly when notes are a 6th apart

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9302]
**Describe the bug**

When notes are a 6th apart, sharps are stacked. They should be next to each other instead.

**Current**

<img width="285" alt="Screen Shot 2021-09-27 at 9 42 40 AM" src="https://user-images.githubusercontent.com/5659171/134950694-3a32e3fc-6463-491d-a2c9-35ecde9e8d9d.png">

**Desired**

<img width="317" alt="Screen Shot 2021-09-27 at 9 43 06 AM" src="https://user-images.githubusercontent.com/5659171/134950744-47b9e998-d821-4c74-9c84-066b42a28306.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.6

**Additional info**

Here's a minimal file to test with: 
[sharps.mscz.zip](https://github.com/musescore/MuseScore/files/7238018/sharps.mscz.zip)

**Comment by Jojo-Schmitz** [comment]
Doesn't look desired to me

**Comment by Nick-Mazuk** [comment]
> Doesn't look desired to me, IOW: looks OK to me as is.

The current behavior goes against the best practices, standards, and rules of music notation.

**Comment by Jojo-Schmitz** [comment]
As per what sources exactly?

**Comment by Jojo-Schmitz** [comment]
I see, Gould's "Behind Bars", page 108, "Accidentals a sixth apart". Shows pretty your example. So I rest my case ;-)

**Comment by Jojo-Schmitz** [comment]
Actually it does not strictly forbid our current layout though

**Comment by Nick-Mazuk** [comment]
> Actually it does not strictly forbid our current layout though, as there's no overlap, none of the lines of one sharp continues in the other and only that is listed there as being 'forbidden'.

True, but at smaller sizes (and realistically the size that most people read printed music), that 8th of a space distinction isn't going to make a difference.

In general, we've been wanting to change this for a while, there was just never an issue for it.

**Comment by MarcSabatella** [comment]
It's not a "rule" of notation, it's really quite dependent on the design of the accidentals themselves  If you switch a font where the sharps are a little larger, we don't do this - we detect that they overlap by too much.  Instead of arbitrarily disallowing sixths from stacking like this, we should instead make it a style setting to control how much overlap is allowed.  Then one can have a more compact layout if one wants and the font supports it.  There was a recent-ish forum discussion on this topic as well - see https://musescore.org/en/node/322164.  In that thread there are examples from Gould but also a number from different publishers showing it's entirely subjective (eg, the arrangement we produce by default is actually extremely common in practice).  It's important were don't force one particular arrangement on people here when a simple style setting will let the user have the choice.  And then if we want to make the default setting for Leland prevent this, that's fine.

**Comment by MarcSabatella** [comment]
Here for the record is the very first example I found of sharps on notes a sixth apart, it shows more or less what we do:

![image](https://user-images.githubusercontent.com/1799936/135030105-37b03145-31ed-4fb5-9816-e0ad067bfeb5.png)

In my own brief research of the literature I found this arrangement was actually four times more common than the other.  So it's definitely incorrect to call say that this is "against the best practices, standards, and rules of music notation".  It's a valid and quite common choice, even if we should decide to change the default to go the other way.

**Comment by oktophonie** [comment]
Also for the record:

![2021-09-28 11 06 24](https://user-images.githubusercontent.com/20604032/135069022-22d910ac-8b09-4747-af67-c9660fe297fb.jpg)
(Henle, 1983)

![2021-09-28 11 06 38](https://user-images.githubusercontent.com/20604032/135069166-461707d2-8374-4d5a-97cb-18a56418d288.jpg)
(PWM, 1999)

Whether the symbols can overlap does depend on their design, of course (they are quite tall in both these cases), but doing so does give you the advantage of saving horizontal space, which can be useful in situations such as this where you have a lot to fit in and don't want to over-distort the rhythmic spacing. I've certainly done that before on occasion in my work, in extremis.

Also,

![2021-09-28 11 07 01](https://user-images.githubusercontent.com/20604032/135069241-1ea1e53d-75fc-4c4f-aa1b-2bb7671fd1a1.jpg)
(Ted Ross)

Furthermore the style guides for Schott, Boosey and Schirmer all state and illustrate that only once you get to a seventh can accidentals overlap/align (with some exceptions; naturals a 6th apart can overlap if their design allows - or at least kern closely - and, in some designs, even aligning sharps a 7th apart is problematic).

In any case, my personal view is that I don't like the verticals of sharps interlocking like this simply because it looks visually inelegant and noisy to have those lines so close together. It's certainly not how I'd like Leland to look under normal circumstances (it goes against various considerations we have for its design in general in terms of minimum distances and such) - which isn't to say it shouldn't ever be done, but it wouldn't be my preferred default. If the sharp were less tall it wouldn't be so bad.

**Comment by MarcSabatella** [comment]
Thanks for the input!  Again, I don't have a strong opinion on what the default should be for Leland, but I just wanted to make sure it was clear that the current layout isn't really out of line with accepted practice.  So instead of considering this a bug to be fixed, I'd prefer to see it as an opportunity to add additional customization via a style setting.  There are a number of other hard-coded constants in this code that could also be made into style settings, FWIW.

**Comment by Nick-Mazuk** [comment]
Great discussion! I probably was too argumentative (and not willing to even listen to other's opinions) in my first response, so thanks to all of you for keeping it civil. I learned a lot from them!

---

Anyways, I wouldn't mind having a style setting to toggle this on/off. I think the default should be them placed horizontally, but I'm probably biased there.

**Comment by MarcSabatella** [comment]
No worries!  But based on how it works internally, and the fact that this is really just one special case for one particular accidental (sharp) and one particular interval, it shouldn't be a special case toggle.  A more general setting to control how far two accidentals are allowed to overlap would be much simpler to implement and be much more useful - then it would also automatically apply to all the various microtone accidentals and also to other fonts etc.

**Comment by micpap25** [comment]
Can the name of this issue be changed to better reflect the current goal - to create a slider or some other input for how far two accidentals for overlap?

**Comment by Tantacrul** [comment]
@oktophonie - is this one you want to target for 4.0 or shall I bump it to 4.x?

**Comment by MarcSabatella** [comment]
Adding a style setting isn't particularly difficult, but it's definitely more work than simply changing the hardcoded value.  If we decide to put off adding a style setting, I'd still recommend we consider changing that hardcoded value now if we expect that the default behavior needs to change at all.  So the default layout of 4.x will be the same as 4.0 in this respect, even if 4.x also provide ways to override it.  It's probably a very small change to one constant, like here:

https://github.com/musescore/MuseScore/blob/master/src/engraving/layout/layoutchords.cpp#L643-L653

Might be the 0.33 sp value that needs to be reduced, might be the calculation of "allowableOverlap", but I'm pretty sure it's all about this chunk of code.

**Comment by irwir** [comment]
`Standard music notation practice` says:
![acc](https://github.com/musescore/MuseScore/assets/20182149/7288317b-55b7-487e-8e0e-16eb65a1b7f7)
That is, placement depends on symbol sizes in the used font.
