### ISSUE TITLE
[MU4 Issue] MU4 crashes on save after style parameter is changed.

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#9310]
**Describe the bug**
A save after changing a style parameter MU crashes:

```
10:14:15.366 | ERROR | main_thread | XmlWriter  | tag: "UNREACHABLE!":/data/MuseScore/MuseScoreDevelopment/MuseScore/src/engraving/infrastructure/io/xmlwriter.cpp250
10:14:15.366 | ERROR | main_thread | Qt         | ASSERT failure in UNREACHABLE: "UNREACHABLE was reached", file /data/MuseScore/MuseScoreDevelopment/MuseScore/src/engraving/infrastructure/io/xmlwriter.cpp, line 250
10:14:15: The program has unexpectedly finished.
10:14:15: The process was ended forcefully.
10:14:15: /data/MuseScore/MuseScoreDevelopment/build-MuseScore-Desktop_Qt_5_15_2_GCC_64bit-Debug/src/main/mscore crashed.
```

**To Reproduce**
1. Create a new score, any score will do.
2. Save the score, this works fine.
3. Open the Style form (Format -> Style)
4. Change any parameter, e.g.  ```Display in concert pitch``` at the ```Score``` page.
5. Close the form with ```OK```
6. Save the file, now MU4 crashes.

**Expected behavior**
A saved score file without a crash and without corrupting an existing score file.

**Screenshots**
N.a.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Additional context**
N.a.

**Comment by cbjeukendrup** [comment]
I believe the problem is that the EditStyle dialog sets some properties to a QColor value (which is hidden inside a QVariant). That is also the reason that the assert in EngravingItem::setProperty (line 1341) fails when opening the style dialog. 

I suspect that one of the calls to `textStyleValueChanged` in the EditStyle dialog is causing this.

For this reason, it might be better to create our own Variant type, that works with our own Points, Rects, Color etc., instead of using QVariant.

**Comment by njvdberg** [comment]
Please note this also causes a "spontaneously" crash due to the auto save.

**Comment by njvdberg** [comment]
And unfortunately, auto save can't be disabled :disappointed:

**Comment by cbjeukendrup** [comment]
Curiously, the crash when opening the style dialog only seems to occur with scores that are opened from disk, not with newly created ones...
