### ISSUE TITLE
[MU4 Issue] MU4 shows ampersands in menu

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#9311]
**Describe the bug**
Menu items contain an ampersand in the text instead of underlying the shortcut character.

**To Reproduce**
1. Open MU4

**Expected behavior**
Instead of ```&File``` I expected to see ```File```

**Screenshots**
![image](https://user-images.githubusercontent.com/48352523/135056413-3eb441d8-2a97-4167-808c-d810fe14b867.png)

**Desktop (please complete the following information):**
 - OS: OS: openSUSE Tumbleweed, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Additional context**
Normal behavior (on KDE/Plasma) is that the character preceded by the ampersand is underlined when the `Alt` key is pressed. However is MU4 always underlines there characters is fine too.

**Comment by exegetor** [comment]
This also happens under Windows 10 x86_64, with the current commit (a1979d7).

**Comment by martin-danhier** [comment]
It seems that the translator is not working properly, thus Qt uses the key of the string instead which is not supposed to be seen directly.

After looking more into it, I couldn't get any translation working:

- By default, no language appears to be selected:

![image](https://user-images.githubusercontent.com/36641081/144097717-fabc4eef-2128-47fc-80b2-72788dde1668.png)

- After selected another language, I didn't see any differences in any of the strings (#9195)
- There wasn't any "English" option in the list to revert back to (#9539)

It would seem that all of those issues are related. 

(While I'm referencing issues, I will also reference #8090 since this issue is one of the listed tasks)

I imagine that the translation files on the MuseScore website are obsolete because of MuseScore 4 changes. Are these translations accessible somewhere, or are they closed source like the website ?

**Comment by cbjeukendrup** [comment]
There are (almost) no translations done for MuseScore 4 yet. Because many strings and their translation contexts changed, the translators will have a big amount of work to do. I believe the plan is that they can start translating when the alpha is released.

The translation process is mostly a community effort, and takes place on Transifex: https://www.transifex.com/musescore/musescore/

Your reasoning about the ampersands is not completely correct; those ampersands are namely also written in the translated strings. What's going on is that we are using a custom menu bar component, and we haven't yet written the code to replace the ampersand with an underline for the next character and add a shortcut.

**Comment by Jojo-Schmitz** [comment]
Also reported in https://musescore.org/en/node/327250

**Comment by wizofaus** [comment]
Note that while the & no longer appear, the underscores that do appear when you press ALT (on Windows) seem too close to the text:
![image](https://user-images.githubusercontent.com/5364225/147613903-471b4543-ce7a-40fc-967c-f1e9b7c8e55b.png)

Also other than the top level menus, the only commands that seem to show accelerators are ones that open out submenus ("File|Open Recent", "View|Toolbars", "View|Workspaces" etc. etc.).

Perhaps best done as a separate bug? @Tantacrul @njvdberg

**Comment by Eism** [comment]
@wizofaus 
> Perhaps best done as a separate bug? 

Yes, you are right. Thanks
Need to open an issue on porting ampersands from MU3. @DmitryArefiev for you

**Comment by DmitryArefiev** [comment]
> Note that while the & no longer appear, the underscores that do appear when you press ALT (on Windows) seem too close to the text: ![image](https://user-images.githubusercontent.com/5364225/147613903-471b4543-ce7a-40fc-967c-f1e9b7c8e55b.png)
> 
> Also other than the top level menus, the only commands that seem to show accelerators are ones that open out submenus ("File|Open Recent", "View|Toolbars", "View|Workspaces" etc. etc.).
> 
> Perhaps best done as a separate bug? @Tantacrul @njvdberg

@wizofaus @Eism I've logged #12467 for the 1st issue. The 2nd bug doesn't occur on my side (Win/Lin)
