### ISSUE TITLE
[MU4 Issue] Weird score scrolling (need to specify exactly how scrolling should work)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9397]
**Describe the bug**
Videos with weird scrolling attached: 
1) Using mouse scroll, it is possible to scroll under the manually scrolling bar
2) Scrollbar UI disappeared, scrolling is possible by using mouse scrollbar

**Expected behavior**
need to specify exactly how scrolling should work

**Screenshots**

https://user-images.githubusercontent.com/71372310/136481040-bd5903cd-19eb-4068-84ab-5bfc9ae7915a.mp4
https://user-images.githubusercontent.com/71372310/136481053-f5929641-813f-4f7e-9ea4-8a1042be5587.mp4

**Desktop (please complete the following information):**
Windows 10 
Linux
MacOS

**Comment by bkunda** [comment]
Hi Slavovich! Good spot here.

I've tried to explain my preference for expected scrollbar behaviour in this video: https://www.dropbox.com/s/zzdqkd1i7mvlopk/Weird-scrollbar-behaviour.m4v?dl=0

Basically, click on scrollbar + drag should work in the same way as using the scroll wheel.

**Current behaviour**: click on scrollbar + drag locks scroll to page height/width.
**Expected behaviour**: both scrolling methods should scroll past the edge of the page to the x/y-axis limit currently in place (a limit that does not allow the user to scroll the score out of view). 

I was unable to reproduce the disappearing scrollbar issue on Windows or Mac, or perhaps I didn't understand it completely. 

Another issue I spotted in the meanwhile: click on scrollbar + scroll with scroll wheel produces an undesirable result. In my video, I advocate for disabling scroll with this behaviour (consistent with how Windows and MacOS works, as well as some apps like Adobe apps). I'm open to discussion on this though (Figma, for example, allows users to click on a scrollbar and use a scroll wheel); were this to be permitted, scrolling should work exactly as it does by using scroll wheel alone.

Hope this helps!
