### ISSUE TITLE
[MU4 Issue] Palettes > More > Duplicate paletees. After transferring from more box to main box they disappear 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9398]
**Describe the bug**
[MU4 Issue] Palettes > More > Duplicate palettes. After transferring from more box to main box they disappear 

**To Reproduce**
1. Create a score
2. Open Palettes 
3. Expand any palette
4. Click "More" button
5. transfer from More tab to main tab palette (video attached)

**Expected behavior**
No duplicates when click on "More" button

**Screenshots**
https://user-images.githubusercontent.com/71372310/136481888-e84f33f1-c7e7-42e9-a733-d12cde7825c5.mp4

**Desktop (please complete the following information)
Windows 10 
Linux

**Comment by cbjeukendrup** [comment]
The problem here is, that when you open a palette for the first time, the "More" popup contains elements that are already in the palette itself, so they shouldn't be in the popup. When closing the palette and reopening it, or, as described in this issue, when dragging an element from the "More" popup, the problem fixes itself: the popup becomes empty, or at least, has no more duplicate items that are already in the palette.
