### ISSUE TITLE
[MU4 Issue] UI glitch on 'Learn' icon

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9403]
Tiny tiiiiny glitch I noticed on the 'Learn' icon (nothing to do with the actual icon from musescore font). 
Same on Mac and Windows. It may be hard to see, but it is definitely there. You can notice 2 tiny dots beside it.
Probably a render issue. 

Can be found on the Learn tab

**Screenshots**

![Screenshot 2021-10-08 132717](https://user-images.githubusercontent.com/71656189/136575235-622ffc5f-fb79-43fb-984e-65ac74f7f806.png)

![Screenshot 2021-10-08 153304](https://user-images.githubusercontent.com/71656189/136575339-19ae2c00-805c-48ff-8f22-fef0b10ff8bd.png)

**Desktop (please complete the following information):**
 - OS: Mac & Windows.

**Comment by cbjeukendrup** [comment]
I suspect that I'm seeing a similar problem with the eight note in the note input bar:
<img width="479" alt="Schermafbeelding 2021-10-10 om 23 26 06" src="https://user-images.githubusercontent.com/48658420/136713428-25043067-4586-4d28-b2db-16b12cac44b2.png">

No idea whether/how we could fix this... I'm afraid that the problem is either in the icons font, or in Qt's rendering.

**Comment by jessjwilliamson** [comment]
Aww, the paper icon doesn't look good :c 

![image](https://user-images.githubusercontent.com/71656189/143612336-2cf5026c-9a64-4d8c-bf4b-f6a17d8c263d.png)
![image](https://user-images.githubusercontent.com/71656189/143612362-27aec48d-41b3-4c30-9957-a40554266c3b.png)

**Comment by jessjwilliamson** [comment]
@cbjeukendrup I may have found the solution to these icon glitches! These icons had some vector issues which I've cleaned up. Can you update the musescoreicon font and check if they look better in the app? :)
