### ISSUE TITLE
[MU4 Issue] No playback sound for Sousaphone (concert pitch)

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#9426]
**Describe the bug**
No playback sound for "Sousaphone (concert pitch)". The other Sousaphones (currently just Sousaphone in B♭) have sound.

**To Reproduce**
1. Create a new score that includes the "Sousaphone (concert pitch)" instrument.
2. Add some notes.
3. Click Play to listen to the score. 

**Expected behavior**
You should hear the notes you added but there is just silence.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6 with Intel processor (not tested on Windows or Linux)

**Comment by Jojo-Schmitz** [comment]
Isn't that about the very recent soundfont changes to extend the Tuba range up so that it fits for Sousaphone too?
That updated soundfont is not yet part of MuseScore nor available via the resource manager

**Comment by Tantacrul** [comment]
The mapping is now working. @shoogle - let me know if there's a reason to reopen this!

**Comment by azmeuk** [comment]
@Tantacrul I am not sure this is the same issue or if I should reopen a new one:

With MS4 with Musehub soundfonts, no sound come for the sousaphones or wagner tubas with scores written with MS3. I see that there is no sousaphone nor wagner tubas in Musehub yet, however playing those parts with a Tuba sound should be enough in the meantime.

Migrating all my score manually and tell every people in my bands to download them again is not very fun, so I would really appreciate backup soundfonts!

**Comment by MarcSabatella** [comment]
This works as expected for me.  I just created a test score in 3.6.2 and added tuba, Wagner tuba, and sousaphone, and all played normally in 4.1.1 as well.  Wagner tuba and sousaphone both used MS Basic as the fallback just as I'd expect.

If you have a score where this isn't working correctly, please be sure you do in fact have MS Basic and didn't accidentally delete it from your system and aren't using a third-party build (like those found in some Linux repositories) that omits MS Basic.  If you continue to have trouble, please ZIP and attach the score with the issue here.  It could also be your score was using a custom instruments.xml file that isn't supported in MuseScore 4.
