### ISSUE TITLE
[Inspector] 'Mode' dropdown for key signatures non-functional (both in MS3.6 and MS4.0)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9444]
**Describe the bug**
It seems this feature has not been working for a while. Here is an old bug: https://musescore.org/en/node/304086

Currently if you choose any option and then click away from the key signature and then click back on it, the dropdown defaults back to 'unknown'.

![image](https://user-images.githubusercontent.com/21022311/136992678-3021e5db-b618-4bf6-8487-36b68ee0dc5f.png)

### Desired to fix

1. This is intended to specify the key signature mode for XML import/export. Since it is not currently functioning - and does not appear to have functioned in a long time, I suggest hiding the UI for now.
2. Alternatively, if a community member wants to tackle it, we can assign the task to them. If fixing this issue, it would be wise to alter the description to make it clear that it is an XML-related feature only. Currently, its intended function is not obvious at all.

**Comment by slimvince** [comment]
I'd like to add a concrete **import-side** facet to this issue, and make the case for *fixing* the key-signature mode rather than hiding it.

### An import-side mechanism that silently drops `<mode>`

In `addKey()` (`src/importexport/musicxml/internal/import/importmusicxmlpass2.cpp`), the guard that decides whether to create a `KeySig` compares **fifths only**:

```cpp
// TODO only if different custom key ?
if (oldkey != key.key() || key.custom() || key.isAtonal()) {
```

`<mode>` is parsed correctly just above (`key.setMode(...)`), but when a key's fifths match the prevailing key, the whole `KeySig` is deduped away — taking the parsed mode with it (→ `KeyMode::UNKNOWN` downstream). The common trigger is a **0-fifths key carrying an explicit mode**: at score start the prevailing key defaults to `{C, UNKNOWN}`, so `<fifths>0</fifths><mode>minor</mode>` (A minor, or any 0-signature modal key) matches on fifths and is dropped. (The maintainers' own `// TODO only if different custom key ?` on the line above already flags this dedup as incomplete.)

### It breaks export/import round-trip

Export **does** write `<mode>` (`exportmusicxml.cpp`, for every `KeyMode` value). So:

1. A score with an A-minor key signature exports as `<fifths>0</fifths><mode>minor</mode>`.
2. Re-importing that file **drops** the mode (the Inspector then shows "Unknown").
3. Re-exporting can no longer recover it.

Information present in the file is lost on a plain round-trip.

### A minimal fix — and it's the same correctness class MuseScore already applies

The dedup **already** preserves one mode value: the `|| key.isAtonal()` term, and `isAtonal()` is defined as `m_mode == KeyMode::NONE` (`key.h`). So *atonal* mode already survives the dedup — only the tonal/modal values are dropped. Extending the guard to also compare mode closes the gap:

```cpp
if (oldkey != key.key() || oldKeySig.mode() != key.mode() || key.custom() || key.isAtonal()) {
```

A key matching the prevailing one in **both** fifths and mode still produces no `KeySig`, so plain mode-less C-major scores are unaffected. In my own build this restores `<mode>` on round-trip and adds no spurious key signatures.

### Why fix rather than hide: mode is already load-bearing

The key-signature mode isn't XML-only or cosmetic:

- It's persisted in the native `.mscz` format (read/write) and round-trips through MusicXML.
- It's exposed in the Inspector (`Pid::KEYSIG_MODE`) and the plugin API.
- `isAtonal()` (== mode `NONE`) already gates real behavior — e.g. transposition skips atonal keys (`transpose.cpp`, `edit.cpp`).
- The tonal modes are the only thing that distinguishes **relative pairs that share a signature** (C major vs A minor — both 0 fifths). Anything that names a key or reasons about tonality (harmonic analysis, plugins, import/export fidelity) needs that distinction.

Hiding the UI removes the only way to *set* a property that the data model, the native format, the MusicXML round-trip, and the plugin API all already carry. Making mode functional — a working editor plus this import fix — looks like the better direction: it's small and well-scoped, and it lets mode become a dependable signal rather than a silently-dropped one.
