### ISSUE TITLE
[MU4 Issue] Time Signature Properties: Remove redundant functionality and fix broken signifiers

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9618]
This issue contains a few interrelated fixes for the Time Signature Properties dialog: 

1. Remove the "Values" field (contains redundant functionality). Reposition "Appearance" field to take its place.
2. Relocate "Beam Properties" above "Note Groups" panel and ensure it functions as per MS3.6 (i.e. with click and drag interaction)
3. Relocate checkbox to right-hand side of the dialog
4. Ensure "Other" dropdown functions as per MS3.6
5. Remove the connection between the time signature displayed in the "note groups" panel and the "appearance" panel (i.e. time signature visualisation should reflect the "actual value" and NOT the value assigned in the "appearance" section).
5. Lastly, please note the following changes to UI copy:

- "Appearance" --> "Appearance (visual only; will not affect actual measure duration)"
- "Note groups" --> "Beam groups"
- "Beam properties" --> "Beam selector"

**Current dialog**
<img width="689" alt="Screenshot 2021-11-01 at 10 10 00 pm" src="https://user-images.githubusercontent.com/86290556/139663435-bc7ed56a-8d56-4570-9746-0d202fd0a8f2.png">

**New dialog (showing repositioned elements)**
<img width="899" alt="Screenshot 2021-11-01 at 10 58 35 pm" src="https://user-images.githubusercontent.com/86290556/139668094-0d33644e-801a-4ef5-9d2e-eaf1a2111aba.png">

Thank you!

**Comment by Jojo-Schmitz** [comment]
I believe we still need (and that had been discussed earlier) some indocation what the current time signature is

**Comment by bkunda** [comment]
I'm not sure this is hugely necessary. As you know, the "Appearance" section only changes the visual appearance of the time signature, not the metrical value of the bar(s) in question. The actual metrical value of the bar is still correctly represented by the visualisation in the "Note Groups" panel, even if the user changes its visual appearance. And if the user is still unsure what the actual time signature is from this, then simply deleting their text field entries will return the appearance of their time signature to the correct value in the score.

We realise this is not an optimal fix, and we certainly don't plan to keep it this way permanently! Ideally we would redesign this quite substantially for a later release of MS. This proposed fix simply removes incorrectly functioning UI in an attempt to make it visually less confusing for the user.

Perhaps I've missed something here, in which case let me know and we can take a second stab at this. Our aim though is to keep the workload down for our devs by not introducing too many new UI/UX elements ahead of the alpha release of MS 🙂

**Comment by cbjeukendrup** [comment]
I think "will not affect playback" is not fully accurate. Playback is one thing, but more importantly, it won't affect how many notes fit into a measure. Perhaps something like "visual only; will not affect actual measure duration" is better.

**Comment by bkunda** [comment]
That's a good point, @cbjeukendrup. I think this can be improved. I will update the screenshot and copy suggestion above accordingly.

**Comment by Jojo-Schmitz** [comment]
In that dialog, for, say, a 5/4 time sig, change the text to, say, 2+3/4. Now the beaming dialog shows 2+3/4 (well, it does not, but it really should) and you'd have no idea whether it is a 5/4 or what else, without either deleting the text or counting the beats.

**Comment by bkunda** [comment]
In your example, you would still see 5 quarter notes represented in the note groups panel, so I don't see there being any material difference here between designating this meter as either 5/4 or 2+3/4. In other words, the user won't have any reason to be confused about how many beats there are in a bar.

I do concede that the case for confusion might arise if the user, say, renders a 4/4 bar with text specifying 5/4 (or 2+3/4). Now in THIS case, it _might_ be helpful to still see the "Actual value" as 4/4. This would be entering some pretty esoteric (and frankly, musically questionable) territory, however, and I would like to see us develop a more sophisticated system in future that could handle such edge cases more elegantly.

**Comment by Jojo-Schmitz** [comment]
Seeing the actual value amd the set value may prevent those _esoteric_ cases, if introduced by accident

**Comment by MarcSabatella** [comment]
Indeed, users make mistakes.  They also download or otherwise acquire scores created by others that may contain mistakes.  And actually, there are non-esoteric cases where the actual time signature might not be immediately obvious (the “mensural” symbols, any number of “modern” notations, etc).  Seeing the actual time signature seems like a no-brainer obvious important thing.  Could be in the title of the dialog or somewhere else unobtrusive but please don’t remove it entirely.

**Comment by Jojo-Schmitz** [comment]
Exactly my point. The old dialog was somewhat missleading in giving the impression those values could get changed, but it also served a real purpose, for displaing it

**Comment by cbjeukendrup** [comment]
I think we should just add a readonly label saying the actual values, maybe accompanied by a hint like 

> "To change these values, replace the time signature on the score with a new one from the Palettes."

Probably we can find a better wording for this. 

In MuseScore 4.1, we can improve it further, to make it possible to edit the actual values.

**Comment by bkunda** [comment]
Could a solution be that, when the user makes any adjustment in the "Appearance" section, the time signature displayed in the "note groups" panel just retains the _actual_ time signature, and doesn't revert to the time signature displayed in the appearance section? 

For example, a time signature with an actual value of 12/8 would look like this..
<img width="775" alt="Screenshot 2021-11-05 at 12 12 22 am" src="https://user-images.githubusercontent.com/86290556/140319640-51422289-d30c-41c6-b7f3-d1ea664da8eb.png">

...as opposed to this (current behaviour):
<img width="778" alt="Screenshot 2021-11-05 at 12 15 12 am" src="https://user-images.githubusercontent.com/86290556/140319721-498e0d7c-fa3a-4f9c-80b4-e5531aa18056.png">

(bear in mind I'm using the old (i.e. current) dialog from MS3.6 in this example). 

The argument here is twofold: first, displaying this is musically inaccurate: 
<img width="215" alt="Screenshot 2021-11-05 at 12 16 59 am" src="https://user-images.githubusercontent.com/86290556/140319992-e811b03e-1a92-4fca-8344-7a1797c932b0.png">

and second, retaining the actual time signature in the "note groups" section reinforces the idea that whatever is entered in the "appearance" section is not connected to the actual number of beats per bar. In other words, it reinforces the fact that the values entered in the "appearance" section are exactly that: for appearances only.

And so if the user changed the appearance of the time signature as follows, they would see the "note groups" section displayed like so:
 
<img width="1095" alt="Screenshot 2021-11-05 at 12 20 39 am" src="https://user-images.githubusercontent.com/86290556/140320885-df4e373e-21f9-4c47-bc5b-ac3728e0bdb2.png">

Thoughts on this?

**Comment by martin-danhier** [comment]
Hello,
I was wondering, what is the reason why we don't allow to update the actual value of the time signature here ?

As a user, if I want to update a specific time signature midway through my score, I might naturally head to this dialog and I might not directly think of dragging a new time signature from the palette, since there is already one in the score at that location.

For example, if I want to replace 4/4 by something else here:

![image](https://user-images.githubusercontent.com/36641081/144077747-1652d0a2-2bee-4584-bb6c-5f448cf4950f.png)

Also, it is not quite clear where you need to go if you want to set a specific time signature that is not in the palette. Using the measure properties dialog, it is possible to set the actual value used in the measure (which changes the number of notes you can place), but it doesn't update the time signature itself, which remains at the old value, even if you reset the time signature properties.
It is also possible to add a custom time signature to the palette, then drag it, but a user might not want to do that if they just want to play around with various time signatures just one time and don't want to add them to their favorite ones...

Besides that, when we will be sure of the changes we want to make in this dialog, I'd be glad to help implementing them, as well as #9620 which is related.

**Comment by cbjeukendrup** [comment]
I believe that the only reason that you can't change the value in that dialog is that it nobody has implemented it so far :)
And we are a bit reluctant to work on that for MuseScore 4, because we're busy with higher-priority tasks.

So if you would like to give it a try, that would be very welcome!

If you're also going to work on that task about the redesign, you could try to do that in the existing QWidget dialog, but you could also consider rewriting it entirely in QML (which needs to be done eventually anyway). That's something you could keep in mind. 

When you start working on this or the other task seriously, please leave a comment here on GitHub, so that nobody else starts working on it too.

**Comment by martin-danhier** [comment]
Okay thanks! I will look into it today.

**Comment by bkunda** [comment]
Hi @martin-danhier, thanks for your willingness to contribute on this task, and great to have your input!

@cbjeukendrup is spot on in that, at least for the moment, we're trying to reduce adding too much new functionality as it compounds our testing workload and can potentially create extra issues to fix. 

In saying that, I think you're absolutely right that it would make to be able to change the time signature from a central "time signature properties" place. We're actually thinking of potentially overhauling this kind of dialog-style interaction in future, and so altering time signature properties may end up being done in a different place, where it would totally make sense to implement something along the lines of what you've suggested 🙂.

Looking forward to seeing your work on this task, and thanks so much again 🙏🏻

**Comment by martin-danhier** [comment]
Hello everyone !
Here is a little update on my progress so far.

I learned QML and I reimplemented the first half of the dialog with it. I had to slightly modify the qml ``Dropdown`` to support icons (it only supported text until now).

![image](https://user-images.githubusercontent.com/36641081/148998835-2625efaf-e3a5-45fd-afea-ecd2e82a76d7.png)

I also started to implement the "Note groups" section.
The original dialog used an internal `QWidget`, ``NoteGroups``. However, if I understood correctly, QWidgets aren't compatible with QtQuick 2, so I started to implement it in QML as well.

I noticed that it is also used in the "Time dialog", the dialog that allows users to create new time signatures in the palette:

![image](https://user-images.githubusercontent.com/36641081/148999328-f1a29d08-a2cf-46e9-87d4-b3392e201ce8.png)

I will make it reusable, that way it will be easy to recreate that other dialog in QML. I can also do it alongside the other one, since most of the work would already have been done.

I just have one question for now: the `QWidget` version of the note groups section uses an `ExampleView` to display a preview of what the beams will look like in a score. Is there an equivalent widget in QML that allows to do the same ? I noticed the notation is already implemented with QtQuick so it should be possible...

Thank you in advance for your answers !

**Comment by bkunda** [comment]
Hi @martin-danhier, have you been able to find out some answers to your questions above? 

I have just noticed that the "Create time signature" dialog (where the user can make their own custom time signatures) doesn't seem to be working at all (The `Add` button does nothing). Have you experienced this too? 

I might raise this as a separate issue, because it is a regression from 3.6, but I will reference this issue and you can maybe advise whether you will also be addressing it in your build?

Admittedly, the way custom time signatures works in MS3.6 is fairly problematic – when the user clicks `Add`, there's no feedback to indicate that the time signature has been added anywhere. I'll specify this in a separate issue, but you can reference it if you're also able to implement it into your build. Otherwise one of our internal team devs will get onto it 🙂

**Comment by martin-danhier** [comment]
Hi @bkunda,

I didn't have much time this week to experiment with notations, but I should be able to find time in the next couple of days.

As for the "create time signature" dialog: I tried it on my branch (which is about 500 commits behind master, which reminds me I should do a rebase once in a while ^^) and the app crashes when I press the "Add" button. When I try it on the latest master branch, the button does indeed nothing.

Also, interestingly, on the latest master branch, the "beam properties" icons aren't broken anymore.

For the lack of feedback in MS3.6, perhaps a solution would be to close the dialog on add and to automatically add the new signature in the main palette instead of hiding it in the "More" button by default ? And perhaps auto select it as well to make it more visible ? If users create a custom time signature, they are likely to use it again immediately. Also there seem to be the same problem with other customizable palette elements like custom key signatures. As you said, a dedicated issue would be best :)

Currently, my main focus is to get the "time signature appearance" dialog working in QML. However, once it does, it shouldn't be too hard to update the "create time signature" one as well. The lack of feedback problem seem to be global among all customizable palettes, so maybe it is better to fix it in a separate patch ?
However, if a patch requires fixing the create dialog itself, I might include it in this one to avoid someone to lose time to fix the old dialog if it is going to be reimplemented in QML anyway :)

**Comment by bkunda** [comment]
> For the lack of feedback in MS3.6, perhaps a solution would be to close the dialog on add and to automatically add the new signature in the main palette instead of hiding it in the "More" button by default ?

This is exactly what I had in mind ☺️

I'll raise this as a separate issue. Meanwhile, keep us posted with how you get on with this issue, and if you have any questions for our developers then don't hesitate to reach out!

**Comment by martin-danhier** [comment]
Will do, thanks !

**Comment by martin-danhier** [comment]
Hello, here is a little update:

I managed to display the examples in QML by creating an `ExamplePaintView`. It is inspired by the `TemplatePaintView` used in the score creation which loads a template file and displays a readonly preview. Here, the example paint view will display a `Ms::Score` that can be created with a `Ms::MCursor` as in the original `NotesView` widget.

![image](https://user-images.githubusercontent.com/36641081/152145619-d3c2d2f5-d7d5-4d5e-a85f-8ef2ae8cf46d.png)

I will now start implementing the interaction itself to update the beam groups properties.

**Comment by bkunda** [comment]
Good stuff @martin-danhier. Just to confirm – the preview won't be entirely read-only, will it? (I.e. will it still be interactive as specified in the design)?

**Comment by martin-danhier** [comment]
Thanks @bkunda! Yes, that's what I'm working on right now. It is read-only in the sense that users are not allowed to add, modify or remove notes, but they will be able to click on notes to edit the beam properties as specified in the PDF file.

**Comment by bkunda** [comment]
Terrific. Thanks for the clarification!

**Comment by RomanPudashkin** [comment]
Hi @martin-danhier! I reworked the existing dialog because this issue is critical and blocks the alpha release. But you can continue rewriting this dialog using qml because this will be quite useful. Your version of the dialog can be included in the master branch later. Thanks!

https://github.com/musescore/MuseScore/pull/10429

**Comment by martin-danhier** [comment]
@RomanPudashkin Hello, thanks for the explanation. I will continue then, and I will update my branch to your version once its merged to reuse the system you implemented for the logic (such as the live preview of the changes in the score).
I will also reimplement the "create time signature" dialog at the same time since it reuses most of the logic of this one.
Should I create a new issue to keep track of it once these two are closed with your pull request ?

**Comment by RomanPudashkin** [comment]
> Should I create a new issue to keep track of it once these two are closed with your pull request ?

You can open a new issue after that. But for now, one issue is enough for both of us :)

**Comment by bkunda** [comment]
HI @martin-danhier! @Tantacrul and I had a chat this morning about this dialog and before you spend too much more time recreating it in QML, we've realised there could be significant design changes to the UX of creating and modifying time signatures in the future. This might include moving away from this kind of dialog to a different design pattern entirely. 

I know you've already put some time into this so I thought I'd flag this now, especially since our dev team has just found a solution for this dialog that doesn't involve rewriting it in QML.

For now I'd say the implementation in QML is probably not as pressing as it was. We're very grateful for your contributions though and would be keen to keep you posted about any new designs for this particular feature if you're still keen to be involved with it post-MS4 🙂.

**Comment by Tantacrul** [comment]
Yes, I apologise for only weighing in on this now. My attention has been on other things and I did not notice this ongoing work. The current Time Signatures dialog is one we just want to completely replace with a much simpler, more intuitive (and more powerful) system once MS4.0 is released. Ideally, this new widget would not be a dialog.

We can prioritise the design for this and send them to you if you are interested?

**Comment by martin-danhier** [comment]
Hello! Don't worry, I understand, I also think a new system would be better.
I already spent quite some time on the issue, but I also was learning QML and the codebase at the same time. I think I would be more efficient if I had to do it again now.

> We can prioritise the design for this and send them to you if you are interested?

Yes, that would be great, thanks! I'd be glad to help implementing the new system :-)

**Comment by Tantacrul** [comment]
@bkunda - this appears to be the same issue https://github.com/musescore/MuseScore/issues/9620

If so, can you close one of them?

**Comment by DmitryArefiev** [comment]
Fixed in #12109

@bkunda You can check briefly on your side (if I missed something)

**Comment by bkunda** [comment]
> Fixed in #12109
> 
> @bkunda You can check briefly on your side (if I missed something)

Tested briefly. Most things have been addressed, except for point 5 in the above issue description. 

This was somewhat important for showing what the actual time signature was when changing its "appearance". There is also some other resultant jankiness, which is that if the user changes the "appearance" using one of the other radio-button options (e.g. common time "C"), the preview in "beam groups" will still show any numbers entered into the "Appearance > Text" field.

<img width="973" alt="Screenshot 2022-06-24 at 11 35 45 pm" src="https://user-images.githubusercontent.com/86290556/175547133-2fbb8ac0-026c-42f8-a3fc-8088f6495a84.png">

Hence my suggestion to unlink these two parts of the UI. Reading back over this now, however, I can see that perhaps I mightn't have explained it as clearly as it needed to be. 

Worth mentioning that this doesn't render this dialog unusable, only somewhat janky. But if this extra element could still be implemented, that would be the ideal fix for now.

**Comment by Tantacrul** [comment]
@bkunda - I'd suggest making that a separate issue and we can bump to Beta 2. We know this dialog isn't long for this world anyway!

**Comment by RomanPudashkin** [comment]
> @bkunda - I'd suggest making that a separate issue and we can bump to Beta 2. We know this dialog isn't long for this world anyway!

There is no need for a new issue since we already have this task in 4.x
https://github.com/musescore/MuseScore/issues/9620
