### ISSUE TITLE
[MU4 Issue] The search button in Palettes is still 32 x 30

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9681]
**Describe the bug**
This bug is still not being fixed, it needs to be 30x30!

**Screenshots**
![image](https://user-images.githubusercontent.com/71656189/140962152-9461ff90-0259-4173-9442-a1365e2fddc3.png)

**Desktop (please complete the following information):**
 - OS: Windows, Mac

**Comment by cbjeukendrup** [comment]
Ha, a third report of this problem :) (see also #9278 and #8098)

The problem is that the size of the buttons is calculated dynamically based on the content size. This has the disadvantage that icon buttons are not square, and that text-only buttons are 29px instead of 30px high. 

So we should probably give icon-only buttons a fixed size of 30x30px. But we should also do something for text buttons.

We could
- specify a _minimum_ height of 30px for text buttons (but then it starts looking ugly for font sizes of 14+ pixels, because text buttons are then 31px)
- specify a _fixed_ height of 30px for text buttons (but then, text could get clipped at larger font sizes)
- anything else?

What would be the best solution?

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/8098
