### ISSUE TITLE
[MU4 Issue] MacOS shows incorrect default template in New Score Wizard

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9729]
**Describe the bug**
When opening a new score on MacOS, it's still showing the Liturgical template as first template to show whereas Windows shows Treble Clef.
The order of the category templates are also still wrong on MacOS. MacOS version needs to match Windows version. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/71656189/141512399-9a75e404-d3da-402a-90fa-9e6febf5708c.png)

**Screenshots**
<img width="1280" alt="Screenshot 2021-11-12 at 17 48 08" src="https://user-images.githubusercontent.com/71656189/141512094-409c2eb5-9e27-4cff-bfad-4bbe11bc0861.png">

**Desktop**
 - OS: MacOS

**Comment by cbjeukendrup** [comment]
This came up earlier, in #9131 and https://github.com/musescore/MuseScore/issues/8105#issuecomment-841172849. Problem is that the templates are not sorted by us, so the order depends on the ordering of the file system. The fact that macOS and Windows indeed use different file systems explains the discrepancy. Because macOS is Unix-based like Linux, the ordering on Linux will probably match that on macOS.

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/10126
