### ISSUE TITLE
[Learn Section] Thumbnails for YouTube videos are the wrong size / ratio

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9737]
**Describe the bug**
In the learn section, the thumbnails appear to be at a 5:3 ratio which is narrower that the standard for YouTube thumbnails: 16:9.

Below, I've compared a thumb from MS4 (above) and the same thumb from YouTube (below)

![image](https://user-images.githubusercontent.com/21022311/141764280-758b4980-887d-4700-b90b-1b3018630811.png)

This will cause our thumbnails to look distorted when we begin creating tutorial videos.

Essentially, the height of the thumbnails is roughly fine but they should be made wider to fit an exact 16:9 ratio (and it should be an exact integer too). Measured on my Mac (high res), the thumbs appear to be 500x300. Perhaps they could be changed to 512x288?

**Comment by jessjwilliamson** [comment]
I agree absolutely fine to go ahead and fix the ratio. 256x144 looks good just did a test on Figma. That would also mean 50 pixels spacing in between instead of 56 if we want to keep the width of the overall row the same.
![image](https://user-images.githubusercontent.com/71656189/141770677-22851f17-fb5c-4cb1-b659-522c7407a66e.png)
