### ISSUE TITLE
[MU4 Issue] "Pan score automatically" does not work

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9775]
**Describe the bug**
Two parts to this issue: 

1. "Pan score automatically" does not follow the score during **playback**.
2. "Pan score automatically" does not follow the note entry point in **note entry** mode

In both cases, the score zooms in to a high magnification on an outermost corner of the document.

(Apologies for the lengthy video, but I thought it was worth demonstrating current behaviour and why it's important)

https://user-images.githubusercontent.com/86290556/142393675-55142bba-3585-4fbf-9683-3d8a90d6278f.mp4

**Expected behavior**
Replicating MS3.6 behaviour would be a good fix for now.
I.e. When "Pan score automatically" is switched ON, the current playback point should be followed during playback, and when the user is in note entry mode, the score should follow the active note entry point.

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Windows 11

**Comment by jessjwilliamson** [comment]
Was about to report this! Thanks @bkunda!

**Comment by MarcSabatella** [comment]
BTW, speaking of behavior in note input mode: while I like it as is, it's worth mentioning that a significant number of people would prefer to see the score track note the *input cursor*, but the *current selection*.  This is an important distinction when you reach the last note of the last measure of a page while entering notes - does the view stay on the last measure you just completed, or jump to the new?  If you're entering music for a single voice instrument like flute with no chords, you like that we currently do move on to the next page, so you can see the measure you are about to enter notes into.  But in piano and guitar music, it's extremely common that after entering one note on the last beat of the measure, you actually intend to add more notes to form a chord.  For keyboard users, no big deal since Shift+letter still works.  For mouse users it feels extremely wrong to have to constantly scroll back to click in another note.

I don't have a solution - again, I *like* the current behavior.  But it's something to think about - is there a way to somehow have the best of both worlds?

**Comment by bkunda** [comment]
Very good point @MarcSabatella. I'm adding this to my list of design improvements. We may need to think a few things through to achieve a "best of both worlds" scenario, so it will most likely be a post-MS4 improvement 🙂

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
