### ISSUE TITLE
[MU4 Issue] VTests not fails on crash

### ISSUE THREAD

**Issue by igorkorsukov** [musescore/MuseScore#9777]
**Describe the bug**
If a crash occurs during the generation of the current images, then the remaining images will not be generated, only those that have been generated will be compared, and the test will not be marked as failed (if the comparison is successful)

**To Reproduce**
1. Make PR with problem with some vtest score (should be crash with some score)
2. On CI will be run vtest
3. The vtest artifact will show that the images were generated only before the problem file, after the crash, the rest of the images were not generated. And vtest passed successfully.

**Expected behavior**
vtest should be fail with any crash

**Screenshots**
see https://github.com/musescore/MuseScore/pull/9738

**Comment by Jojo-Schmitz** [comment]
Could we also make the vtests artifacts (much) smaller, by only archiving the 'compare' directory('s content)? The other 2 directories ('current' and 'ref') don't really serve any purpose IMHO. The 3.x vtests didn't include them either BTW.
Such an artifact is currently 7.4MB, with almost all of that due to 'current' and 'ref'.
Downloading and checking the vteste results would be much faster if those unneeded files weren't there.

**Comment by njvdberg** [comment]
I see the generation of vtests fails on an assert, is it an option to use a "normal" build for vtests instead of a "debug" build?
Then mscore shouldn't crash on an assert, should it??

**Comment by Jojo-Schmitz** [comment]
I'd rather get the assert fixed though

**Comment by njvdberg** [comment]
I agree it is better to fix the assert but now a `Q_ASSERT` is causing a crash which stops further vtests while reporting an incorrect success. In that case I think leaving the assert for now and run a normal build is best of 2 bad cases.

**Comment by Jojo-Schmitz** [comment]
The lesser evil... OTH the assert is easier to fix, so the low hanging fruit: just comment it out.
Extra benefit: the crash is gone in the FlatPak version of MuseScore too (which for some stupid reason gets build in Debug mode)
