### ISSUE TITLE
[MU4 Issue] Line objects showing incorrect thickness in properties panel

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9844]
**Describe the bug**
The default thickness of line objects (e.g. hairpins, cresc. and dim. lines) appears to be 2.98, which is much thicker than the actual line weight of the selected object. 
Moreover, changes made directly to the **Thickness** text edit field are replaced by the default value (2.98) once the corresponding object has been deselected and reselected.  

https://user-images.githubusercontent.com/86290556/143030363-e5135ed9-5512-40fe-bf2d-15ac01a0bb45.mp4

**Expected behaviour**

1. Default line thickness for these objects should be 0.12sp (@oktophonie please correct me if I'm wrong here).
2. The line weight of the selected object should correspond with the value shown in the **Thickness** text edit field in the **Properties** panel.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by cbjeukendrup** [comment]
I think this is related to #9840, and it might have to do with @igorkorsukov's work regarding PropertyValue. I can't think of any other recent changes that could have affected this.

**Comment by Howard-C** [comment]
I believe this issue is due to some properties not having been fully changed to the new `Milimetre` type, causing a `Milimetre` property to be interpreted as a common `double`. An ideal fix would be properly updating the types of these properties, such as changing the type of `Ms::Stem::m_lineWidth` from `double` to `Milimetre`. I already tried it out and it solved the inspector issue regarding that particular property.

I sense @igorkorsukov is probably working with things like this now, but if you haven't started on this particular issue and wouldn't mind me stepping in, I'd very much like to take this one on. `Milimetre` should also actually be spelled `Millimetre`. And IIRC there has been a convention of using American English in the code? If so, `Millimeter` should work best.

**Comment by igorkorsukov** [comment]
@Howard-C I am currently working on other data types. So, it will be great if you deal with this problem.

> And IIRC there has been a convention of using American English in the code?

As far as I know, there is no such convention. In this case, I was guided by Wikipedia, in which writed that millimetre is international (https://en.wikipedia.org/wiki/Millimetre). But the truth is I was mistaken and missed the second l :(, needs to be corrected.

**Comment by Jojo-Schmitz** [comment]
The convention indeed is to use American English in the software and translate to British English, like to any other language

**Comment by Jojo-Schmitz** [comment]
But as the text "millimetre" is not exposed to the users (in that PR), it is fine IMHO.
