### ISSUE TITLE
[MU4 Issue] can we embed muse score view into app?

### ISSUE THREAD

**Issue by imiskolee** [musescore/MuseScore#9865]
Can musescore embed to appliction as a view?

eg: the score view on a DAW.

**Comment by cbjeukendrup** [comment]
Hi!

We do our best to keep the code modular. So if anyone would ever want to use MuseScore's engraving engine in another application, they would only need to pull in a few core modules, and maybe write some adaptation classes. 

However, there is no kind of documentation of support for this, so if you're looking into this seriously, I'd recommend to get yourself a bit familiar with the code (maybe you can even contribute some patches while doing so, which would be appreciated very much!)

Also, at the moment, MuseScore's code is quite a fast-moving target. I foresee some restructuring in the modules, and since we are in the process of rewriting very big parts of MuseScore's code, not everything is stable right now. So you should probably wait at least a month, and then we'll see how the situation looks by that time.

MuseScore used to depend strongly on Qt, but as part of the restructuring, this is being reduced. In some cases, we have written "wrapper" classes that in our case wrap Qt APIs, but you could also make them wrap other APIs in case you're working with a different framework.

One more thing: be careful about licenses. MuseScore's code is currently available under the GPL-3.0 license, so there are restrictions for applications that use (parts of) MuseScore's code. Please research that yourself, to avoid trouble.

Cheers!

**Comment by imiskolee** [comment]
@cbjeukendrup  it's ok for me, I will starting learn muse,

I think  some core modules we need for embed:

#1. Graphics Symbol System
#2. Layout Engine(it's not related to UI & platform)
#3. Render Interface(so, we can easy to use QT / GTK , even flutter for rendering)

In  face, I am working on a new DAW based on flutter.

**Comment by cbjeukendrup** [comment]
Hm, with Flutter, I'm afraid it will be more difficult, because MuseScore is written completely in C++ and Flutter works totally different, doesn't it? But doubtlessly there exist ways to use C++ libraries in Flutter...

The modules that are probably the most interesting for you are:
- `engraving`, which contains all "logic" to layout music on pages and the drawing code;
- `fonts`, which contains the fonts containing the musical symbol
- `notation`, which manages most of the interaction between the user and the score, and could serve as an example about how a score view could be implemented.

**Comment by imiskolee** [comment]
> Hm, with Flutter, I'm afraid it will be more difficult, because MuseScore is written completely in C++ and Flutter works totally different, doesn't it? But doubtlessly there exist ways to use C++ libraries in Flutter...
> 
> The modules that are probably the most interesting for you are:
> 
> * `engraving`, which contains all "logic" to layout music on pages and the drawing code;
> * `fonts`, which contains the fonts containing the musical symbol
> * `notation`, which manages most of the interaction between the user and the score, and could serve as an example about how a score view could be implemented.

thanks. 
we can use flutter as score render based on FFI.

**Comment by imiskolee** [comment]
> [@imiskolee](https://github.com/imiskolee) is this possible?

Hi, We're leave Flutter stack and move to QT right now.
