### ISSUE TITLE
[MU4 Issue] Incorrect brackets for Accordion

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#9940]
When creating a new score containing an accordion, the staves of the accordion are grouped by a brace (which is correct) **and** a square bracket (which is wrong).

**To Reproduce**
1. Create a new score
2. Add an accordion and a piano
3. Click `Done`
4. Observe the create score.

**Observed behavior**
![Screenshot_20211201_103508](https://user-images.githubusercontent.com/48352523/144209357-952e7f65-bf54-4795-99ab-a18d3a1cd881.png)
Please note the superfluous square bracket for the accordion.

**Expected behavior**
![Screenshot_20211201_103532](https://user-images.githubusercontent.com/48352523/144209416-30ef1380-803f-410d-9bb3-bc348c33345b.png)

**Desktop (please complete the following information):**
 - OS: Linux (openSuse Tumbleweed)

**Additional context**
This is a regression, MU3 was working fine.

**Comment by HemantAntony** [comment]
Something that might hopefully help whoever wants to solve this, this occurs for all instruments part of the family "accordions". If you change the family name to something else, the "square" brackets get removed. I got this far before I got stuck. I did try searching the entire project for "accordions", since that was the family name, but nothing useful showed up. I thought the brackets might be explicitly added for instruments of family "accordions"

**Comment by njvdberg** [comment]
See #9971

**Comment by njvdberg** [comment]
The accodion belongs to the `Group` `Accordions`. In the score order `Orchestral` this group is not defined so any instrument belonging to this group `Accordions` is placed in the group `Unsorted`. This group `Unsorted` is not member of any section so there should no bracket generated because this bracket is generated to group all instruments belonging to a section.
Because of a wrong definition of this `unsorted` group this bracket was generated. PR #9971 solves this.
