### ISSUE TITLE
[MU4 Task] Compile for Apple Silicon

### ISSUE THREAD

**Issue by david-shortman** [musescore/MuseScore#9951]
**Task description**
Compile the app for Apple Silicon arm64 architecture.

**Comment by cbjeukendrup** [comment]
The app can already be compiled in x86_64 mode on Apple Silicon machines. I do that hundreds of times per day 😉.  (If you're interested, see https://github.com/musescore/MuseScore/wiki/Compiling-on-Macs-with-Apple-Silicon)
Once you've set up everything correctly, you won't notice any difference in the development process between Apple Silicon and Intel.

It will not be possible to compile MuseScore in arm64 mode. Really not. That's because we depend on Qt 5.15, which does not exist for arm64 (yes, it does exist for iOS, but not for macOS). We can't move to Qt 6.2 (which does support Apple Silicon), because:
- Qt 6 is so different from Qt 5, that it is not possible to adapt our code base for it. We depend on a lot of things that got removed in Qt 6. But except for those things that got removed, I have a personal branch where I have fixed all other things.
- Qt 6 does not support Windows 32 bit. In the Windows world, 32 bits machines are apparently still common, so many people will be angry when we drop Windows 32 bit support. And the only benefit would be a slightly better performance for those few people with an Apple Silicon Mac (or not even that, because those M1 chips are so fast that you won't notice any different between Intel and native).

It is also not possible to maintain two versions of MuseScore, one for Windows 32 (and other old devices that need Qt 5.15) and one for newer devices with Qt 6. The difference between the Qt versions is simply too big, and we don't have enough manpower to develop two different versions at the same time.

For more elaboration, see https://musescore.org/en/node/323841.

**Comment by david-shortman** [comment]
Thanks for the details!

**Comment by JunielKatarn** [comment]
> 

According to the Qt website, it CAN be built for Apple Silicon.

https://musescore.org/en/node/323841#comment-1142163

**Comment by cbjeukendrup** [comment]
I know about that, but that's about Qt 5.15.4, but we use 5.15.2. Officially, 5.15.2 is the last version for which prebuilt binaries were released for open source license users. Initially, Qt 5.15.3 and later was only available to commercial customers. But Qt has an agreement with some open source organization that every version of Qt _must_ become open source after one year after it has been released. So while the latest commercial version is 5.15.10, the source code of versions up to 5.15.6 has silently been published. Of course, we could try to build Qt from source, but that would be another full-day-task for one of our developers and is not without risk. 
So currently, I think it's not worth the trouble. MuseScore runs perfectly fine with Rosetta, and the speed improvement will be absolutely minimal. (The Apple Silicon native Qt 6 version of MuseScore runs not noticeably faster.) Also keep in mind that the Qt 6 version of MuseScore will probably be released relatively soon after version 4.0, so if we try to support Apple Silicon natively for 4.0, that would be a lot of effort/risk for a solution that will be used only a few weeks or months.
